### ISSUE TITLE
URLSearchParams.toString()  After the conversion is complete. Is null

### ISSUE THREAD

**Issue by ToBePlus** [swagger-api/swagger-editor#1004]
**Swagger File**

```yaml
 # paste your swagger document here
```

* Version: 
* Browser/OS: 

**Issue**

public userRegisterSmsPost (mobile: string, rnd: string, sign: string, extraHttpRequestParams?: any ) : Observable<models.CommonResponse> {
        const path = this.basePath + '/user/register/sms';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        let formParams = new URLSearchParams();

        // verify required parameter 'mobile' is set
        if (!mobile) {
            throw new Error('Missing required parameter mobile when calling userRegisterSmsPost');
        }
        // verify required parameter 'rnd' is set
        if (!rnd) {
            throw new Error('Missing required parameter rnd when calling userRegisterSmsPost');
        }
        // verify required parameter 'sign' is set
        if (!sign) {
            throw new Error('Missing required parameter sign when calling userRegisterSmsPost');
        }
        headerParams.set('Content-Type', 'application/x-www-form-urlencoded');

        formParams['mobile'] = mobile;

        formParams['rnd'] = rnd;

        formParams['sign'] = sign;

        let requestOptions: RequestOptionsArgs = {
            method: 'POST',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = formParams.toString();   //toString() = "";
       //**After the conversion is complete. Is null**

        return this.http.request(path, requestOptions)
            .map((response: Response) => response.json());
    }

**formParams.toString(); After the conversion is complete. Is null**

**Comment by saharj** [comment]
This issue was moved to swagger-api/swagger-codegen#3381
