### ISSUE TITLE
apikey security schema issue

### ISSUE THREAD

**Issue by rapw3k** [swagger-api/swagger-editor#1006]
Hi, 
I am relatively new to swagger, but after investigating the spec and some examples, I am unable to make this simple example with authorization work.
I want to make this simple API work from Swagger:

---curl -X GET -H 'Accept: text/plain' -H 'Authorization: Bearer 4e5b6138-5885-4c8f-a794-cf368c67a4e4' http://sandbox.wf4ever-project.org/rodl/ROs---

I made the file below, but it does not work. 
In Chrome I get response: ERROR Server not found or an error occurred
In Safari I get a pop-up window asking for username and password: "To view this page, you must log in to area “ROSRS” on sandbox.wf4ever-project.org:80"
Any ideas where is the problem?
Thanks in advance

* Version: 2.0 (running on a linux ubuntu server)
* Browser/OS: Chrome and Safari (with cross-origin resource sharing), Mac OSX El Capitan

**Swagger File**
```yaml
swagger: '2.0'
info:
  version: "1.0.0"
  title: Basic Auth Example
  description: |
    An example for how to use Basic Auth with Swagger.
    
host: sandbox.wf4ever-project.org
basePath: "/rodl"
schemes:
  - http
  - https
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /ROs:
    get:
      security:
       - Bearer: []
      responses:
        200:
          description:  Will send `Authenticated` if authentication is succesful, otherwise it will send `Unauthorised`
```

Attached is the chrome debugging, where its visible that the request header is not including the token

<img width="1264" alt="screen shot 2016-07-14 at 21 31 55" src="https://cloud.githubusercontent.com/assets/557493/16853124/64c32fac-4a0b-11e6-8de0-0636e862ed4d.png">

**Comment by saharj** [comment]
@webron can you help?

**Comment by webron** [comment]
@rapw3k what response do you get from the server? 500 or something else?

**Comment by rapw3k** [comment]
Hi @webron , not sure about the response code, I just receive information: ERROR Server not found or an error occurred in chrome and in safari a pop-up window asking for username and password: "To view this page, you must log in to area “ROSRS” on sandbox.wf4ever-project.org:80". 

<img width="1273" alt="screen shot 2016-07-17 at 19 04 52" src="https://cloud.githubusercontent.com/assets/557493/16901943/840de27e-4c51-11e6-8658-b5b4c4257eb4.png">

**Comment by webron** [comment]
You're showing the network tab of our browser's console - the response code will be there, it's just not in the screenshot.

**Comment by rapw3k** [comment]
I think its 200. See new screenshot.

<img width="1276" alt="screen shot 2016-07-18 at 10 36 45" src="https://cloud.githubusercontent.com/assets/557493/16909570/f332b706-4cd3-11e6-80f6-9ef42492b0fb.png">

**Comment by rapw3k** [comment]
In any case, would it be possible for you just to copy my swagger file (at the top) and try to execute to see what is the problem? Thanks

**Comment by webron** [comment]
If you're getting 500 for OPTIONS, then it's likely you don't have CORS enabled on your server. You need to fix that before being able to proceed with executing calls - https://github.com/swagger-api/swagger-editor/blob/master/docs/cors.md

**Comment by rapw3k** [comment]
I have CORS enabled explicitly in both chrome and safari and it works because if I try the same API call from the editor without authentication it works fine. Was there any possibility for you to try to execute it from your editor ? - The token information is above.

**Comment by rapw3k** [comment]
To complement.  I tried also using the last solution on the link you provided: Run Swagger Editor in a browser that ignores HTTP access control,..... For example in OSX you need to run the following command:
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --disable-web-security --user-data-dir

and when executing the call, I get the pop-up window as with safari, asking for some username and password  (see figure 1), and when I close that windows (as I don't have username password), I get error 401 Unauthorised (see figure 2). 

Please note that if I don't use the authorisation, it works fine (see figure 3)

Figure 1
<img width="1274" alt="screen shot 2016-07-19 at 16 15 17" src="https://cloud.githubusercontent.com/assets/557493/16953337/eef7e4e6-4dcc-11e6-8d7a-820ef25b93a5.png">

Figure 2
<img width="1277" alt="screen shot 2016-07-19 at 16 14 51" src="https://cloud.githubusercontent.com/assets/557493/16953305/d62977cc-4dcc-11e6-8e10-ad1bba0b24b6.png">

Figure 3
<img width="1278" alt="screen shot 2016-07-19 at 16 17 32" src="https://cloud.githubusercontent.com/assets/557493/16953210/84052536-4dcc-11e6-88d9-612044e18109.png">

**Comment by webron** [comment]
Using the version at http://editor.swagger.io, disabling CORS in Chrome, providing the Authorization header in the example - it works as expected and doesn't pop up any other window.

**Comment by rapw3k** [comment]
Not for me. I am not able to make it work using the version at http://editor.swagger.io if I provide the key. **It works if I don't provide any key**. 

- Can you confirm me if you provided they key? 

- What was the result? The expected result is only one entry when you give the key, not multiple entries as in the Figure 3 above. 

- If you got one entry, then can you tell me how did you disable CORST in Chrome? I tried both, using the chrome plugin Allow-Control-Allow-Origin, and using the --disable-web-security option.

- Can you show me a screenshot of your screen?

**Comment by webron** [comment]
I used the value of `Bearer 4e5b6138-5885-4c8f-a794-cf368c67a4e4` from the curl command you shared.

<img width="941" alt="screenshot 2016-07-20 10 18 45" src="https://cloud.githubusercontent.com/assets/241629/16995865/653bcc8a-4e63-11e6-9346-6bb71a5620f4.png">

I used the command you shared to run Chrome with CORS disabled.

**Comment by rapw3k** [comment]
Thanks, I realised what was my mistake: In the api key box, I need to write explicitly the word "Bearer" before the key, and previously I was writing only the key.

My question would be now how to make the call from Swagger UI? I mean how to pass the token appropriately in the header?

<img width="871" alt="screen shot 2016-07-21 at 16 33 04" src="https://cloud.githubusercontent.com/assets/557493/17026605/eacca66e-4f60-11e6-969a-d3e53c3aec19.png">

**Comment by webron** [comment]
That's a separate issue. If there's no more issues with swagger-eeditor, please close this one and open one on swagger-ui, mentioning which version you use and so on.
