### ISSUE TITLE
Invalid Downloaded Zip Package

### ISSUE THREAD

**Issue by techana** [swagger-api/swagger-editor#1010]
Zip packages for swagger-editor 2.10.2 and 2.10.3, downloaded from the links provided below, are missing "templates" and "views" folders. One needs to separately download the missing contents and manually put them in swagger-editor folder after extracting the downloaded packages.

* Version: 2.10.2, 2.10.3
* Links: [2.10.3](https://github.com/swagger-api/swagger-editor/releases/download/v2.10.3/swagger-editor.zip)

**Comment by saharj** [comment]
Can you try again? I just tested 2.10.3 again to make sure it's correct. It should work fine.

**Comment by techana** [comment]
I redownloaded 2.10.3 and it worked after extraction without the need for any extra contents. Thank you.
