### ISSUE TITLE
Yamal/Json file size in Swagger online editor

### ISSUE THREAD

**Issue by Rasika3091** [swagger-api/swagger-editor#1011]
- Version: Swagger online editor
- Browser/OS: Chrome/ Windows 10

Hello,
        Can you please tell me the size limit for a document(yaml/json) when editing it in swagger editor online. First before 2 weeks was not able to add data after the size limit was exceeding some 105 KB. But today I checked again, it accepted file documentation more than 340 KB. Are these size changes done recently ? What is the max size limit now then for the file ? I have to combine my whole documentation in one file. Because of the file issue before I had to divide my documentation in different modules. But if the size issue is now solved then I can combine my documentation. 

```
                                                 Thankyou.
```

**Comment by saharj** [comment]
There is not set size limit. If your Swagger is really large it will make the app slow and sometime it breaks the app. See the Instagram or Twitter examples as large file examples.

**Comment by Rasika3091** [comment]
I have checked Instagram example. The file size is 51 KB only. But when I combine my documentation the file size will go more than 600 KB. Is there any way I can divide my files an give references in online swagger editor ?

**Comment by simar15** [comment]
@Rasika3091  can you provide more information about your spec? as in what do you want to reference?
