### ISSUE TITLE
Nested tags 

### ISSUE THREAD

**Issue by bhupesh99** [swagger-api/swagger-editor#1013]
**Swagger File**

```yaml
 # paste your swagger document here
```

* Version: 2.0
* Browser/OS: Chrome

**I have a requirement of using nested tags. But I am not able to find out how to do that. I mean for passing nested request parameters, we can use type and all to resolve, but how to do that in case of tags?**

**Comment by webron** [comment]
There's no support for nested tags. I don't even know what you mean by nested request parameters. You can emulate nested tags by using something like `tag1/tag2` but you'd have to modify any tool you'd want to reflect this yourself.
