### ISSUE TITLE
Swagger generates invalid Angular 2 typescript

### ISSUE THREAD

**Issue by bendg25** [swagger-api/swagger-editor#1014]
Given an Integer pageNumber on a java Rest controller, Swagger generates:

public getAllTemplatesUsingGET (pageNumber: number, pageSize: number, 
     
        if (pageNumber !== undefined) {
            queryParameters.set('pageNumber', pageNumber);
        }

Error (Webstorm): TS2345: Argument of type 'number' is not assignable to parameter of type 'string'

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger-codegen#3427
