### ISSUE TITLE
Building from source fail

### ISSUE THREAD

**Issue by calmriver** [swagger-api/swagger-editor#1018]
➜  ~ git clone https://github.com/swagger-api/swagger-editor.git
Cloning into 'swagger-editor'...
remote: Counting objects: 29333, done.
remote: Total 29333 (delta 0), reused 0 (delta 0), pack-reused 29333
Receiving objects: 100% (29333/29333), 83.31 MiB | 188.00 KiB/s, done.
Resolving deltas: 100% (16208/16208), done.
Checking connectivity... done.
➜  ~ cd swagger-editor
➜  swagger-editor git:(master) npm install
/usr/local/lib
└── swagger-editor@2.10.3

➜  swagger-editor git:(master) npm start

> swagger-editor@2.10.3 start /Users/CALM/swagger-editor
> node server.js

Development server started at http://127.0.0.1:8080
Opening the browser

ERROR in multi app
Module not found: Error: Cannot resolve module 'webpack-dev-server/client' in /Users/CALM/swagger-editor
 @ multi app

ERROR in multi app
Module not found: Error: Cannot resolve module 'eslint' in /Users/CALM/swagger-editor
 @ multi app
webpack: bundle is now VALID.

**Comment by saharj** [comment]
It seems like maybe the `npm install` didn't work properly. Try to install again, and hopefully it works this time.
