### ISSUE TITLE
Is there a way to integrate swagger-editor like an angularJS directive

### ISSUE THREAD

**Issue by seecomedia** [swagger-api/swagger-editor#1019]
* Version: 2.10.1
* Browser/OS: ALL

**Issue**

I've downloaded and installed swagger-editor 2.10.1 and it works fine.
As a next step, I would like to have swagger-editor fully embedded as part of my web-app like any other angularJS directives I'm using to build my web-app.

Is there a way to integrate swagger-editor like an angularJS directive/component (using bower ?) ?.

Thanks for your feedback.

**Comment by saharj** [comment]
You can use `iframe` for it. You can read more [here](https://github.com/swagger-api/swagger-editor/blob/master/docs/config.md#external-hooks) for hooking to editor events.

**Comment by seecomedia** [comment]
Thanks @saharj .
This is an option. However, it is not the best I would tend to think. I saw there's a discussion to migrate to Swagger 2. Could be probably an opportunity to have Swagger UI a directive.
Thanks.
