### ISSUE TITLE
keyboard handler (i.e. vim) not saving settings on reload

### ISSUE THREAD

**Issue by sreich** [swagger-api/swagger-editor#1022]
- Version: http://editor.swagger.io/#/ 2.10.2
- Browser/OS: Windows: Chrome, Firefox

**Issue**

open http://editor.swagger.io/#/ , editor settings -> keyboard handler -> set to vim.

notice the editor using vim. now close the tab and reopen it. it forgot the setting.

other settings like theme, however, are persisted.

this of course applies to closing the browser as well and of course the desired behavior is for met o only have to set this setting, like the others (hopefully all work as expected), only once and settings should be saved/loaded.

**Comment by webron** [comment]
We no longer offer this functionality.
