### ISSUE TITLE
twitter example : YAML Syntax Error

### ISSUE THREAD

**Issue by eugene-g** [swagger-api/swagger-editor#1023]
#### How to reproduce
- Go to http://editor.swagger.io/
- File -> Open Example -> twitter.yaml
#### Result

✖ YAML Syntax Error
Duplicated mapping key at line 338, column 3: /statuses/oembed: ^

**Comment by saharj** [comment]
Yes, we are aware of this issue. There is probably a syntax error in the code as the error message says. We will review is very soon.

**Comment by nplatis** [comment]
This seems to be working correctly on version 2.10.5 of the editor.

**Comment by eugene-g** [comment]
@nplatis, confirmed. Thanks!
