### ISSUE TITLE
$ref to path is returning an 'Unknown Error'

### ISSUE THREAD

**Issue by zeiphon** [swagger-api/swagger-editor#1024]
Looking at the swagger specification I'm unable to tell - are `$ref`s allowed for entire `path` elements?
For example, see the following YAML:

``` yaml

---
swagger: '2.0'
info:
  version: 1.0.0
  title: Test Api
  description: |
    #### This is the documentation for the Test API.
schemes:
  - http
host: test.com
basePath: /api
paths:
  /my-actual-path/:
    $ref: '#/paths/x-mypath'

  x-mypath:
    get:
      description: HELLO
      responses:
        200:
          description: Response test
          schema:
            type: object
            properties:
              id:
                type: integer
```

Swagger-editor returns an 'Unknown Error': `Cannot read property 'consumes' of undefined`.
This swagger validator appears to think that the above YAML is valid: http://bigstickcarpet.com/swagger-parser/www/index.html 
but I am unsure if this validator is being overly lenient.

**Comment by saharj** [comment]
This is not supported with Sway.

**Comment by zeiphon** [comment]
Should this issue be moved to Sway? It seems like this used to be allowed (along with incorrectly allowing  the HTTP verb body to be a $ref): https://github.com/swagger-api/swagger-editor/issues/756

**Comment by saharj** [comment]
Yes, please open an issue in Sway repo and link it here.

**Comment by zeiphon** [comment]
I've opened this issue for Sway: https://github.com/apigee-127/sway/issues/92

**Comment by webron** [comment]
This should no longer be an issue in the new editor.
