### ISSUE TITLE
Hosting Swagger Editor in Own Domain

### ISSUE THREAD

**Issue by annatara1** [swagger-api/swagger-editor#1026]
**Swagger File**

``` yaml
 # paste your swagger document here
```
- Version: Swagger editor version 2.10.3
- Browser/OS: Google Chrome/Linux Mint 17.3

**Issue**

I am currently trying to follow the approach outlined in the page below to host the swagger editor in my own domain. 

 https://github.com/swagger-api/swagger-editor/blob/master/docs/cors.md

I ran the npm install and npm run build. Once I had the dist folder, I added the swagger-editor directory to my domain statically. When I try and open localhost:8880/index.html, I get the following error from the bundle.js file: 

bundle.js:169 Failed to load defaults.json from /index.html/config/defaults.json(anonymous function) 

With the entire trace being: 

bundle.js:50 GET http://localhost:8880/index.html/config/defaults.json 404 (Not Found)send @ bundle.js:50ajax @ bundle.js:49ht.(anonymous function) @ bundle.js:49getJSON @ bundle.js:49(anonymous function) @ bundle.js:169c @ bundle.js:48g @ bundle.js:48
bundle.js:169 Failed to load defaults.json from /index.html/config/defaults.json(anonymous function) @ bundle.js:169A @ bundle.js:48fireWith @ bundle.js:48i @ bundle.js:49(anonymous function) @ bundle.js:50
bundle.js:169 Object {readyState: 4, responseText: "{"timestamp":1469652314908,"status":404,"error":"N…Found","path":"/index.html/config/defaults.json"}", responseJSON: Object, status: 404, statusText: "Not Found"}(anonymous function) @ bundle.js:169A @ bundle.js:48fireWith @ bundle.js:48i @ bundle.js:49(anonymous function) @ bundle.js:50
Failed to parse SourceMap: http://localhost:8880/dist/bundle.js.map

Please let me know if I am doing something wrong! Thanks!

**Comment by saharj** [comment]
```
bundle.js:169 Failed to load defaults.json from /index.html/config/defaults.json(anonymous function)
```
When you visit the editor path, your server should not add `index.html` to path. That's the problem.

**Comment by neolf** [comment]
@annatara1  try https://github.com/swagger-api/swagger-editor/pull/1086
I remove the 'index.html' from pathname,so it work good.

**Comment by neolf** [comment]
@saharj sometime we con't config welcomefile, Only index.html can be browsed.

**Comment by webron** [comment]
I assume this issue is no longer relevant. Please reopen if it is.

**Comment by fredcsfaria** [comment]
Hi,

I have the same issue with index.html in path. 
Could anybody give more detailed instructions to suppress the "index.html" of pathname ?
  Sorry, but I am new for this stuff.

**Comment by ArtemSkokCompeat** [comment]
I have the same issue with swager-editor 2.10.5:
Failed to load defaults.json from /C:/projects/swagger-editor/index.html/config/defaults.json
