### ISSUE TITLE
Export editor theme

### ISSUE THREAD

**Issue by deecewan** [swagger-api/swagger-editor#1027]
I'm looking to find the theme that is used to on-the-fly generate the docs in the editor.  It is by far the best looking swagger theme I've found.

Ideally, a static HTML download would be great, but I'm planning on serving it from an express-based server, so that could work, too.

I'm not sure why it's not available as one of the Generate options, as it looks far, far better than the existing static HTML options, and far better than swagger-ui.

**Comment by saharj** [comment]
Please see #664
