### ISSUE TITLE
provide yaml-worker to ace editor

### ISSUE THREAD

**Issue by the-santosh** [swagger-api/swagger-editor#1029]
Hi @mohsen1 and @saharj, thanks for the swagger editor. I have been searching for yaml-worker (validator) for ace editor and I found that you have implemented it as a part of swagger editor. It will be great help if you could raise a pull request to merge yaml-worker to ace, so that, it will get available by default with ace.

**Comment by saharj** [comment]
The worker we've is simply a wrapper around yaml-js and js-yaml. It's very specific to this project.
