### ISSUE TITLE
Disable Google Analytics

### ISSUE THREAD

**Issue by ChristianKniep** [swagger-api/swagger-editor#1030]
- Version: 2.10.1
- Browser/OS: Chrome

**Issue**
I would like to disable Google Analytics, as I want to be able to not care about the paranoia of my peers.

Am I able to do that?

**Comment by saharj** [comment]
If you are using the config object you can't disable it but you can always remove the code if you have a clone. 

We need to disable GA when the value for analytics is null.

**Comment by mikelohmann** [comment]
+1

**Comment by webron** [comment]
This should no longer be an issue with the new editor.
