### ISSUE TITLE
gh-pages hosted swagger-editor doesn't get updated bundle.js

### ISSUE THREAD

**Issue by gitms12** [swagger-api/swagger-editor#1031]
Hi,

I'm hosting a swagger-editor on a gh-pages branch which works quite fine (don't know whether this is important). 

However. I did some changes to html templates, e.g. the preferences.html, ran npm run build and checked in the dist files. My changes are present in the bundle.js but the browser doesn't got them when loading the editor even after a few times clearing browser data and cache and so on.

Is there somethin I have to consider in additon? I'm not very familiar with the webpack thing.

Thanks

**Comment by saharj** [comment]
There is a npm script for pushing to gh-pages branch:

```
npm run gh-pages
```

That should build and deploy to GitHub Pages.

**Comment by gitms12** [comment]
Thansk for your answer. I didn't spot that target. I think my problem was a hickup in the browser anyway.
