### ISSUE TITLE
allOf sensitive to property order

### ISSUE THREAD

**Issue by bbbush** [swagger-api/swagger-editor#1041]
**Swagger File**

https://gist.github.com/bbbush/b387f3490fd734b76e896de8383eed9d/raw

**Issue**

It seems when in one "allOf", another "allOf" is used, the expansion fails. But if the inner one has been expanded once, then the external one could succeed?

**Comment by saharj** [comment]
I'm not sure if I understand this issue correctly.
I've added a recursive allOf resolution method [see here](https://github.com/swagger-api/swagger-editor/blob/a349dc09d6358f9c4b07cc32d0fb9136d0ee64b6/scripts/services/resolve.js). Maybe it's that service that doesn't resolve this specific issue correctly .

**Comment by saharj** [comment]
I see the issue now. It's a bug in JSON Schema View.

**Comment by saharj** [comment]
In `definitions/body-bad/p2`, the second item of `allOf` is a schema with just a title, so Swagger shows it as a schema with just a title. This is an invalid issue.
