### ISSUE TITLE
index.html should be supported in pathname

### ISSUE THREAD

**Issue by centromere** [swagger-api/swagger-editor#1043]
I want to host the editor on Amazon S3, but unfortunately in `scripts/bootstrap.js` there is no check to see if the path is `.../index.html`. As a result, it tries to fetch `.../index.html/config/defaults.json` which obviously fails.

**Comment by saharj** [comment]
this is an invalid request. It’s not our fault that Amazon S3 adds `index.html` to path.

**Comment by centromere** [comment]
I added the following to `scripts/bootstrap.js` and it completely fixed the issue:

```javascript
if (_.endsWith(pathname, '/index.html')) {
  pathname = pathname.substring(0, pathname.lastIndexOf("/"));
}
```
