### ISSUE TITLE
How to define a map in swaggger documentation using json /yaml

### ISSUE THREAD

**Issue by cshar7** [swagger-api/swagger-editor#1045]
**Swagger File**

```yaml
 # paste your swagger document here
```

* Version: 
* Browser/OS: 

**Issue**

**Comment by cshar7** [comment]
For Example  i have to define a below schema - 

"relatedCategories": {
        "All Accessories": [{
            "name": "Luggage",
            "url": "/webapp/wcs/stores/servlet/en/marksandspencer/l/men/all-accessories/luggage",
            "identifier": "SubCategory_1328543",
            "isPrimaryCategory": false
        }],
        "Luggage": [{
            "name": "Hard Suitcases",
            "url": "/webapp/wcs/stores/servlet/en/marksandspencer/l/men/luggage/hard-suitcases",
            "identifier": "SubCategory_1318283",
            "isPrimaryCategory": false
        }]
}

**Comment by cshar7** [comment]
Can someone please help me in this.. i am blocked since many days in this. I cant find out the sample of defining a map.

**Comment by fehguy** [comment]
You really have to give details if you want help.  This isn't a forensics panel

**Comment by cshar7** [comment]
thanks for reply.

I want to document schema like below in the swagger either in json or yaml format.

"**relatedCategories**": {
"dynamicKey1": [{
"name": "Luggage",
"identifier": "SubCategory_1328543",
"isPrimaryCategory": false
}],
"dynamicKey2": [{
"name": "Hard Suitcases",
"identifier": "SubCategory_1318283",
"isPrimaryCategory": false
}]
}


Here  - relatedCategories is the name of my map in the format of dynamic key names which will be string and its value will be a list .

**Comment by webron** [comment]
```yaml
MyUnknownObject:
  type: object
  properties:
    name:
      type: string
    identifier:
      type: string
    isPrimaryCategory:
      type: boolean


RelatedCategories:
  type: object
  additionalProperties:
    $ref: '#/definitions/MyUnknownObject'
```

**Comment by cshar7** [comment]
Thanks. 

i understood tht for map we will use the object. but this map will have key value pair. where keys will be dynamic. so still the above format of schema will work for me ???

**Comment by cshar7** [comment]
Also with the schema i will  generate the models . i think it will genearte  "RelatedCategories" as an object and then type casting will be done to make it as a MAP.

**Comment by fehguy** [comment]
@cshar7 please read up on how JSON schema works.  What @webron showed defines `RelatedCategories` as an object, which has keys with the value `MyUnknownObject`.  That's what `additionalProperties` means.

**Comment by soumava28** [comment]
I know it's a bit late to answer, but anyone viewing this , can refer to this article:
Link: [](https://swagger.io/docs/specification/data-models/dictionaries/)
Section : Dictionaries, HashMaps and Associative Arrays

**Comment by swatishikha** [comment]
> I know it's a bit late to answer, but anyone viewing this , can refer to this article:
> [Article Link](https://swagger.io/docs/specification/data-models/dictionaries/)
> 
> You should get a complete picture!

Amazing, Just looking for this and there are so many wrong answers available. Thanks a lot
