### ISSUE TITLE
Can't edit file in Swagger editor 

### ISSUE THREAD

**Issue by solo-framework** [swagger-api/swagger-editor#1046]
**Swagger File**
- Version: 2.0
- Browser/OS: Firefox 48/Linux Mint 

**Issue**
When i edited a file firefox crashed. After that the editor shows a file but disallows edit it

Console log:

```
Warn: could not find module util
bundle.js (line 151)

"NetworkError: 404 Not Found - http://editor.swagger.io/mode-php.js"
mode-php.js

Warn: could not find module util
a21d96a...rker.js (line 1)

TypeError: i.transformAction is not a function


bundle.js (line 136, col 30791)
```

**Comment by saharj** [comment]
Please clear up your `localStorage` and then try again. This may solve the issue.
