### ISSUE TITLE
2.10.3 doesn't resolve recursive references

### ISSUE THREAD

**Issue by ralfhandl** [swagger-api/swagger-editor#1052]
People have Friends, so the Person schema references itself: https://raw.githubusercontent.com/ralfhandl/odata/master/TripPin.openapi.json 

With version 2.10.1 this recursion was resolved one level deep and then stopped, which was fine: `Person` is visualized, and only `Friends` is an array of `undefined`
![swagger-editor-2 10 1](https://cloud.githubusercontent.com/assets/951576/17664143/52d1f274-62f2-11e6-991c-1f84ed2ad6b9.PNG)

With version 2.10.3 the recursion is not resolved at all: `Person` itself is now `undefined`
![swagger-editor-2 10 3](https://cloud.githubusercontent.com/assets/951576/17664150/586430da-62f2-11e6-9fe6-656b7d1629fb.PNG)

Please restore the friendlier 2.10.1 behavior.

Thanks in advance
Ralf

**Comment by saharj** [comment]
Yes, this is a known issue with json-refs dependency. Please see this issue: https://github.com/swagger-api/swagger-editor/issues/1005#issuecomment-232859440

**Comment by saharj** [comment]
Follow this issue here: https://github.com/whitlockjc/json-refs/issues/91
