### ISSUE TITLE
allOf in paths to split paths into multiple files

### ISSUE THREAD

**Issue by BabuGiri** [swagger-api/swagger-editor#1055]
**Swagger File**

```json
{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Test swagger"
  },
  "paths":{
    "allOf":[
    {"$ref":"pathset.json"}
    {"$ref":"pathset2.json"}
    ]
  }
}
```

* Version: 2.10.3
* Browser/OS: Chrome

**Issue**
looks like allOf is not allowed to be used in paths to refer from multiple files is this intentional or a feature yet to be supported?

**Comment by webron** [comment]
The spec doesn't support it, so the editor doesn't as well. For reuse guidelines, please check https://github.com/OAI/OpenAPI-Specification/blob/master/guidelines/REUSE.md.
