### ISSUE TITLE
Navigation arrows on editor pane search box need swapping over

### ISSUE THREAD

**Issue by jpduffield** [swagger-api/swagger-editor#1057]
* Version: 2.10.3
* Browser/OS: Chrome/Windows 7

In the editor pane, the navigation arrows on the search box are the wrong way round. (The down arrow searches upwards and vice-versa.)

**Comment by saharj** [comment]
Do you mean this search box?

<img width="584" alt="screen shot 2016-08-25 at 3 05 35 pm" src="https://cloud.githubusercontent.com/assets/1468463/17987573/700fca24-6ad5-11e6-9454-91745406f6d3.png">

I can't reproduce it on Chrome. Can you give me more details please?

**Comment by jpduffield** [comment]
Yes, that search box. 
I've retested, and I don't think there is a bug here. You can put this one down to user error. 

I think I was confused by the way the UI highlights search terms. It seems all instances of your search term are highlighted (have a box round them), except for the currently selected one. This only became evident when I retested with a common term that appeared multiple times in the currently visible block of code. 

But... if your search term only ever appears twice in the visible block (as it did in my original case), it can be misleading.  In this case, you have a box highlighting one word on screen, and naturally assume (if you aren't very familiar with this UI) that the highlighted word is the currently selected instance. The navigation arrows will then appear to be mismapped, as you expect them to move the box to the previous/next instance. 

On closer inspection the current instance is subtly highlighted (has a dark grey background instead of black), but that isn't very visible, and wasn't obvious until I looked for it.
