### ISSUE TITLE
Contributing link broken in the README

### ISSUE THREAD

**Issue by vix633** [swagger-api/swagger-editor#1060]
**Issue**
Contributing link is broken! [https://github.com/swagger-api/swagger-editor/blob/master/CONTRIBUTING.md](url)

**Comment by webron** [comment]
Where do you see that link that you think it's broken?

**Comment by vix633** [comment]
In the Readme at the root of this repo.

**Comment by saharj** [comment]
I just fixed this in https://github.com/swagger-api/swagger-editor/commit/4f1bd208e5af1e5810c4d7360d4fc2ac11a2069d
