### ISSUE TITLE
Error in documentation leads visitor down endless paths of broken code

### ISSUE THREAD

**Issue by davidnewcomb** [swagger-api/swagger-editor#1062]
On page:
http://swagger.io/swagger-editor/

Section "Importing your Swagger document"
The link `http://editor.swagger.io/#/?import=http://generator.wordnik.com/online/api/swagger.yaml` forwards to `http://editor.swagger.io/#/` but the *Generate Server->Spring* produces code that doesn't work.

The link `http://generator.wordnik.com/online/api/swagger.yaml` is broken.

I think the link should probably point to `http://generator.swagger.io/api/swagger.yaml` but when you download the *Generate Server->Spring* you get code that doesn't even build.

There is an error in the documentation here. When you fix it please can you make sure the yaml file you are referencing works.

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger.io#130
