### ISSUE TITLE
refresh swagger-editor to see file changes made in another editor

### ISSUE THREAD

**Issue by flenniken** [swagger-api/swagger-editor#1065]
Is it possible to edit my swagger.yaml file in my own editor then refresh the browser to get the swagger-editor to reload and see the new info?

What I tried was running swagger-editor in a docker container and my web app in another docker container both on localhost on two different ports. I have my swagger.yaml exposed at localhost:32768/swagger.yaml and the get request has caching disabled.

When I edit the file and refresh, the swagger-editor it does not reload the url.  I must use menu > File > Import URL ... each time.

Is there a better way to do this?

**Comment by saharj** [comment]
Unfortunately the answer is "No". Swagger editor is a client side only app and it does not care about the server status.

**Comment by FeepingCreature** [comment]
Just ran into this problem. Why can't Swagger just remember the last-used URL and reload it on request, maybe with a button? Or just always reload the URL if the file in the editor window is unchanged?
