### ISSUE TITLE
Swagger response referencing

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-editor#1067]
_From @simar15 on September 19, 2016 21:36_

Hi I am working with Swagger version 2.10.3

I need to create reference file for http responses, (400,401,404) which produce the same result for all the methods, hence better to reference than to create redundant block of code.

```
responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              _id:
                $ref: '#/definitions/Id'
              _links:
                type: object
                properties:
                  curies:
                    $ref: '#/definitions/Curies'
                  self:
                    $ref: '#/definitions/Self'
              name:
                type: string
                description: The name of the category.
        
          $ref: '#/definitions/responses'
```

response 200 is different for different methods.  

and this is what I have under definitions:
```
definitions:

  responses:
    type: object
    properties:
      '400':
       type: string
       default: Bad Request.
```

but I get the error

```
✖ Swagger Error
Not a valid response definition
Jump to line 103
Details
 Object
```

Any help with this would be really appreciated.

When reporting a bug, please provide the following details:
- swagger-ui version
- a swagger file reproducing the issue

_Copied from original issue: swagger-api/swagger-ui#2412_

**Comment by saharj** [comment]
You probably have a typo or bad schema in one of your schemas. From what you gave us, it looks okay. 

I made this simple Swagger from your snippet and it works:


```yaml
---
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /:
    get:
      responses:
        200:
          $ref: "#/responses/200"
          
responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              _id:
                $ref: '#/definitions/Id'
              _links:
                type: object
                properties:
                  curies:
                    $ref: '#/definitions/Curies'
                  self:
                    $ref: '#/definitions/Self'
              name:
                type: string
                description: The name of the category.
definitions:
  Id:
    type: string
  Curies:
    type: string
  Self:
    type: string
```

**Comment by simar15** [comment]
Thanks @saharj, yes I got the same solution working, I was making a mistake of referencing all the generic responses together, but I think you have to reference them individually.
