### ISSUE TITLE
editor don't support sogou chinese input method  

### ISSUE THREAD

**Issue by joy-jingwei** [swagger-api/swagger-editor#1071]
when I am typing chinese with sogou input method which is a very popular input method in china, I found the text in editor go wrong.

**Comment by saharj** [comment]
This is an issue with Ace. You can follow the issue [here](https://github.com/ajaxorg/ace/issues/3027) .

**Comment by thkdog** [comment]
The ace related issue seemed to be resolved, when the editor will be updated ? It's really a huge problem for Chinese develops to use, besides the online editor website is really really slow and sometimes unavailable in China.

**Comment by webron** [comment]
This should no longer be an issue with the new editor.
