### ISSUE TITLE
Embedding Swagger Editor

### ISSUE THREAD

**Issue by sathomps** [swagger-api/swagger-editor#1072]
Besides using iframes, is it possible to bundle the editor in an AngularJS application?  I'm currently using angular 1.5 along with webpack, gulp, and browserify.  

Thanks

**Comment by saharj** [comment]
We suggest iFrame as editor has a router. However if you would like to do it differently, you can look into [app.js](https://github.com/swagger-api/swagger-editor/blob/master/scripts/app.js) file.
