### ISSUE TITLE
Trouble with 'inheritance' example

### ISSUE THREAD

**Issue by bielsk** [swagger-api/swagger-editor#1073]
**Swagger File**

``` yaml
swagger: '2.0'
info:
  title: blah
  description: blah
  version: 2.0.0
paths:
  /:
    get:
      operationId: getPets
      produces:
        - application/json
      responses:
        '200':
          description: All pets successfully retured
          schema:
            $ref: '#/definitions/Pet'
    post:
      operationId: createPet
      produces:
        - application/json
      parameters:
        - name: pet
          in: body
          required: 'true'
          schema:
            $ref: '#/definitions/Pet'
      responses:
        '201':
          description: Pet successfully created.
definitions:
  Pet:
    type: object
    discriminator: petType
    properties:
      name:
        type: string
      petType:
        type: string
    required:
      - name
      - petType
  Cat:
    description: A representation of a cat
    allOf:
      - $ref: '#/definitions/Pet'
      - type: object
        properties:
          huntingSkill:
            type: string
            description: The measured skill for hunting
            default: lazy
            enum:
              - clueless
              - lazy
              - adventurous
              - aggressive
        required:
          - huntingSkill
  Dog:
    description: A representation of a dog
    allOf:
      - $ref: '#/definitions/Pet'
      - type: object
        properties:
          packSize:
            type: integer
            format: int32
            description: the size of the pack the dog is from
            default: 0
            minimum: 0
        required:
          - packSize
```
- Version: 2.10.3
- Browser/OS: Firefox 45.4.0/Windows 7 64 bit

**Issue**
I'd like to use inheritance per the Petstore example to POST or GET a pet type of either Cat or Dog depending on the value of petType that gets POSTed or returned. Swagger editor is currently reporting a 'Not a valid parameter definition' for my POST operation at line 29, corresponding to 'parameters':

Details
Object
code: "ONE_OF_MISSING"
params: Array [0]
message: "Not a valid parameter definition"
path: Array [5]
schemaId: "http://swagger.io/v2/schema.json#"
inner: Array [2]
level: 900
type: "Swagger Error"
description: "Not a valid parameter definition"
lineNumber: 29

I can't figure it out; it's like it doesn't recognize the definition of the Pet parent object. Is there something wrong with my syntax or can I simply not do what I'm trying to do?

**Comment by webron** [comment]
You're getting the error not because of the inheritance but because you quoted the `required` value, making it a string instead of boolean. Remove the quotes around `true` and the error will go away.

**Comment by bielsk** [comment]
Wow, thanks, I looked at the document over and over and didn't notice that mistake. Now the editor gives me these two warnings and tells me that Cat and Dog are undefined:

⚠ Swagger Warning

Definition is not used: #/definitions/Cat
Jump to line 63
Details
Object
⚠ Swagger Warning

Definition is not used: #/definitions/Dog
Jump to line 90
Details
Object

How can I get Swagger editor to recognize the definition of Cat and Dog, or is this only something that can be done at run time?

**Comment by webron** [comment]
Just ignore those warnings. The editor at the moment can't recognize inheritance, but that doens't affect the spec.

**Comment by bielsk** [comment]
Do you happen to know if the Swagger UI recognizes inheritance? Or are consumers left with just reading the raw json/yaml file to understand the semantics?

**Comment by webron** [comment]
Swagger UI will not display it as inheritance, but will also not show you warning/error.

**Comment by bielsk** [comment]
Do you happen to know if there are existing issues/feature requests open for Swagger UI and/or Swagger Editor to support inheritance that I can follow?

**Comment by cmhakkim** [comment]
```
swagger: "2.0"

info:
  title: allOf required
  description: allOf required bug example
  version: 0.0.1

schemes:
  - http

consumes:
  - application/json
produces:
  - application/json

definitions:

  Foo:
    type: object
    properties:
      fauna:
        type: string
      flora:
        type: string
      fungi:
        type: string

  Bar:
    type: object

  Awol:
    type: object
    allOf:
      - $ref: "#/definitions/Foo"
      - $ref: "#/definitions/Bar"
      - properties:
          xxx:
            type: string
            format: date
          yyy:
            type: integer
          zzz:
            type: boolean
      - required:
          - xxx

paths:

  /awol:
    put:
      operationId: setAwol
      summary: Set Awol
      parameters:
        - name: awol
          in: body
          required: true
          description: Awol
          schema:
            $ref: "#/definitions/Awol"
      responses:
        201:
          description: Awol set
          schema:
            $ref: "#/definitions/Awol"
```

Produces:
```
Swagger Error
Missing required property definition: xxx
Jump to line 35
Details
 Object
code:  "OBJECT_MISSING_REQUIRED_PROPERTY_DEFINITION"
message:  "Missing required property definition: xxx"
 path: Array [4]
level: 900
type:  "Swagger Error"
description:  "Missing required property definition: xxx"
lineNumber: 35
```

Some other tools, e.g. go-swagger's validator, accepts this.

This is a bit of an annoyance.

**Comment by saharj** [comment]
@cmhakkim Your YAML is not valid. Changing the `Awol` inside the `definition` will fix your problem. See below:
```
Awol:
    type: object
    allOf:
      - $ref: "#/definitions/Foo"
      - $ref: "#/definitions/Bar"
    properties:
      xxx:
        type: string
        format: date
      yyy:
        type: integer
      zzz:
        type: boolean
    required:
      - xxx
```

**Comment by ifreecarve** [comment]
For those of you squinting to find the difference, it is the `properties` line:

bad:

```yaml
    allOf:
      - $ref: "#/definitions/Foo"
      - $ref: "#/definitions/Bar"
      - properties:
```

good:

```yaml
    allOf:
      - $ref: "#/definitions/Foo"
      - $ref: "#/definitions/Bar"
    properties:
```

The swagger documentation is not very clear on how to properly do inheritance.  Or at least, there were no examples that worked in the online editor as of a month or so ago.
