### ISSUE TITLE
not supporting Swift 3.0 

### ISSUE THREAD

**Issue by gsujathap** [swagger-api/swagger-editor#1076]
while migrating to swift 3.0 swagger files generating errors. Please resolve this issue.
I have attached list of errors
![screen shot 2016-09-28 at 10 51 19 am](https://cloud.githubusercontent.com/assets/16931145/18901550/97294032-8569-11e6-8abc-a60249b2419d.png)

**Comment by saharj** [comment]
This issue was moved to swagger-api/swagger-codegen#3885
