### ISSUE TITLE
Feature request: Add support for json/yaml conversion

### ISSUE THREAD

**Issue by wienczny** [swagger-api/swagger-editor#1078]
Please add support for a toggle button that converts the input from json to yaml or from yaml to json.

**Comment by webron** [comment]
The editor is intended for YAML editing. If you want the JSON, you'd need to download as JSON from the menu.

**Comment by wienczny** [comment]
I'm using http://springfox.io to generate my swagger spec for some projects. They currently only support json output (see https://github.com/springfox/springfox/issues/651). The editor works with json because yaml is a superset of json.
When you copy a one line json into the editor and try to debug errors in the spec this is really hard. For me there are two solutions:

1. Format json
2. Convert json to yaml

I prefer reading yaml ;-)

**Comment by webron** [comment]
I'm not going to go into the inaccuracy of that statement. What we should do is convert on import to YAML, but not have a constant toggle button.

**Comment by heinrichj** [comment]
Maybe I got this wrong, but your source is a json spec and you want yaml in the editor? There is a functiona already:
Use _File => Paste json_ This validates you json input and then puts the content into the editor as yaml. If you want it back to json format just download it as json file as webron suggested.
