### ISSUE TITLE
Please update dockerhub image

### ISSUE THREAD

**Issue by nikmash** [swagger-api/swagger-editor#1079]
Please update the dockerhub image it would be greatly appreciated! I would prefer to continue using the official image rather than pushing my own to my own registry. I think travis CI is broken if it's supposed to push the image to dockerhub.

**Comment by nikmash** [comment]
Also I think theres some value in putting the build step into the Dockerfile definition because then when there are small changes that need to occur I can just use the docker image on dockerhub as a base and then extend it with my overrides. For example this change: 19e40422e14883a9000b3856729518559fe9671d
I want that change in docker hub so I should easily be able to create my own Dockerfile as the following.
`FROM swaggerapi/swagger-editor

COPY ./defaults.json /editor/config/

RUN npm run prebuild
RUN npm run build`

But I'm not able to due to the fact that the docker container does not have the build step. I guess if travis CI was pushing docker images to the hub then this would not be an issue.

**Comment by saharj** [comment]
I know nothing about Docker. If you'd like to make a PR, it's much appreciated.
@fehguy what do you think about this?

**Comment by nikmash** [comment]
@saharj I cannot push a new image to dockerhub since I do not have your credentials and that would be a great quick fix that would be greatly appreciated. I can create a PR to change the way the Dockerfile works as well although it may not be a good idea because Travis CI runs `npm run prebuild` and `npm run build`. It seem your Travis CI builds are failing on a lot of commands such as the one that pushes to dockerhub and also the one that does anything npm related.

**Comment by nikmash** [comment]
Last build on Travis CI: https://travis-ci.org/swagger-api/swagger-editor/builds/162477916

The last couple lines:
```
The command "if [ $DOCKER_HUB_USERNAME ]; then docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD && docker build -t $DOCKER_IMAGE_NAME . && if [ ! -z "$TRAVIS_TAG" ]; then docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG; docker push $DOCKER_IMAGE_NAME; fi; fi" exited with 0.
```

Seems to be failing on one of these commands after the build step.

**Comment by fehguy** [comment]
I'm looking into this

**Comment by fehguy** [comment]
We are only pushing tagged releases, not from master.  Last release was [Jul-14](https://github.com/swagger-api/swagger-editor/releases)

**Comment by nikmash** [comment]
@fehguy I didn't realize that. Is there a timeline on when you guys will be releasing? Really could use that commit.

**Comment by nikmash** [comment]
@fehguy any idea on when you guys will be releasing?

**Comment by saharj** [comment]
@nikmash There will be a new release soon.

**Comment by saharj** [comment]
We have now published a new release.
