### ISSUE TITLE
swagger-editor/node_modules/eslint/lib/api.js didn't return a function  @ multi app

### ISSUE THREAD

**Issue by echampy** [swagger-api/swagger-editor#1081]
- Version:swagger-editor@2.10.3
- Browser/OS: Firefox ESR 45.4.0

**Issue**
environment: RHEL 6

I have installed swagger-editor via github and got several errors ENOENT during the installation; I have manually downloaded eslint via "npm install eslint" under .../swagger-editor.
When start the editor via "npm start" , I get this error:
`ERROR in Loader /home/champy/swagger-editor/node_modules/eslint/lib/api.js didn't return a function
 @ multi app`

Don't understand this error. Thanks for any help, I am stuck

**Comment by echampy** [comment]
api.js does exist in the above directory; here is the content
`/**
 * @fileoverview Expose out ESLint and CLI to require.
 * @author Ian Christian Myers
 */

"use strict";

module.exports = {
    linter: require("./eslint"),
    CLIEngine: require("./cli-engine"),
    RuleTester: require("./testers/rule-tester"),
    SourceCode: require("./util/source-code")
};
`

**Comment by saharj** [comment]
As you can see in TravisCI everything is passing in master. I guess your npm installation didn't work well.

Try removing your `node_modules` folder and starting over.

**Comment by urrvesh** [comment]
Please install **eslint-loader** using **npm i eslint-loader** or **yarn add eslint-loader**
