### ISSUE TITLE
multiple $ref under items

### ISSUE THREAD

**Issue by simar15** [swagger-api/swagger-editor#1082]
Hi, 
I could not find a similar issue

```
 dpf_templates:
        type: array
        items:
          $ref: '#/definitions/Dpf_template_VCF'
          $ref: '#/definitions/Dpf_template_Json'

definitions:
  Dpf_template_VCF:



  Dpf_template_Json:

```
- 2.2.5: 
- Browser/OS: 

Is this possible? Swagger Ui gives me an error when running this.
Any help would be really appreciated. Thanks.

**Comment by saharj** [comment]
Instead of adding them both, it's better if you use `allof`.
```
dpf_templates:
  type:
    allOf:
      - $ref: '#/definitions/Dpf_template_VCF'
      - $ref: '#/definitions/Dpf_template_Json'
  
definitions:
  Dpf_template_VCF:
  
  
  Dpf_template_Json:
```

**Comment by simar15** [comment]
@saharj , thaks for the prompt reply,
Still does not work,

![image](https://cloud.githubusercontent.com/assets/13056996/19173642/9ca3b036-8bdd-11e6-86a5-7da9dbcd948a.png)

UI shows this:

![image](https://cloud.githubusercontent.com/assets/13056996/19173654/b80074e0-8bdd-11e6-93a3-f8fd2da2b59d.png)

Also, I should mention more about schema.

```
paths:
  /dpf_templates:
    get:
      description: >
         tags:
        responses:
          '200':
        description: OK
        schema:
          $ref: '#/definitions/Dpf_Tepmlates'
```
which further references it from definitions:

```
definitions:
  Dpf_Tepmlates:
    type: object
    properties:
      _links:
        type: object
        properties:
          curies:
            type: array
            items:
              $ref: _hal.yaml#/Curie
          self:
            $ref: _hal.yaml#/Self
      dpf_templates:
        type:
          allof:
            - $ref: '#/definitions/Dpf_template_VCF'
            - $ref: '#/definitions/Dpf_template_Json'

 Dpf_template_VCF:

Dpf_template_Json:
```

**Comment by fehguy** [comment]
Your `allOf` syntax is wrong, and you spelled `allOf` wrong (computers are very picky about this stuff)

```yaml
definitions:
  foo:
    allOf:
    - $ref: '#/definitions/bar'
    - $ref: '#/definitions/baz'
  bar:
    properties:
      bar:
        type: string
  baz:
    properties:
      bar:
        type: string
```

**Comment by tony-gutierrez** [comment]
What about:
```
definitions:
  allOf:
  - $ref: '#/externalDefinitions/bar'
  - $ref: '#/externalDefinitions/baz'
```

This works in swaggerui, but fails in redoc, fails in the online validator, and fails in the swagger editor.

**Comment by webron** [comment]
You can't use `allOf` directly under `definitions` - it's invalid by the spec.

**Comment by tony-gutierrez** [comment]
Any suggestions on how to include a list of definitions from 2 separate files? Why does swagger ui allow it and load the lists from both files fine?

**Comment by webron** [comment]
It's a bug in swagger-ui (or rather swagger-js) - it will try to interpret `allOf` (and other keywords) in places they're not allowed.

There's no way to include a list of definitions from 2 separate files (or even one file for that matter), but I'm not really seeing the need for it either.

**Comment by webron** [comment]
Yeah, what you're doing there is defining a model called `allOf`, not exactly what you want.

Just reference the external models from where they are needed.

**Comment by tony-gutierrez** [comment]
That wouldn't list them at the bottom of swagger-ui.

I liked the fact that it wouldn't list models that were included from a separate file, as it let you easily hide sub-models (pieces that are reused, but not standalone models).

**Comment by webron** [comment]
That indeed wouldn't list them. You can file a request to have an option to list all models, including referenced ones. Right now, to make it work, you'd need to 'redefine' them individually under `definitions` by creating a model for each and referencing the external files.

**Comment by tony-gutierrez** [comment]
I guess this is the only way (re-write every include):
```
definitions:

  config:
    $ref: 'models.yml#/shared/config'
  incomingMessage:
    $ref: 'models.yml#/shared/incomingMessage'

  newMessage:
```

This seems really weird.

**Comment by webron** [comment]
I agree, but if you want them to appear in the models, right now it's the only way.

**Comment by tony-gutierrez** [comment]
Doing this seems to generate a lot of superfluous warnings:

```
Swagger Warning
Extra JSON Reference properties will be ignored: title
Jump to line XXX
```

There is no "title" in the code to be ignored..

**Comment by webron** [comment]
Can't help without actually seeing the definition(s) and we're polluting this issue already...

**Comment by tony-gutierrez** [comment]
It doesnt seem to have anything to do with the definition. I guess its creating some virtual "title" attribute whenever I do a ref, and then ignoring it. This is in Editor2 (the only one that supports multiple files) so maybe its just and old bug. Thanks for your help.
