### ISSUE TITLE
Swagger Editor Not Passing Authorization Header Key

### ISSUE THREAD

**Issue by Mithun-Hegde** [swagger-api/swagger-editor#1083]
Hi i am new to swagger. While testing i am passing authorization api key . But in response i am getting 400 Error. 
When i inject Authorization key from third party tool its working perfectly. I checked from chrome developer tool also its not passing authorization api key.

securityDefinitions:
  UserSecurity:
    type: apiKey
    name: Authorization
    in: header
security: 
        - UserSecurity: []

Can anyone please guide me.

**Comment by saharj** [comment]
This is probably a CORS issue.

**Comment by Mithun-Hegde** [comment]
@saharj Thank u so much .. The issue got resolved.
