### ISSUE TITLE
Document generation logic

### ISSUE THREAD

**Issue by bjdash** [swagger-api/swagger-editor#1085]
I am working on a project where I will be parsing a json spec file and show documentation in the application and wanted to take reference from Swagger. What I understood is the parsed spec is stored in $rootScope.specs and the doc is generated with **Builder.buildDocs(latest)** which intern is calling **SwayWorker.run**. From there I sort of lost track of the flow (because its using posrMessage). Where can I find the logic for generating the parsed spec along with errors and warnings? Which file contains the actual login for the conversion?

**Comment by webron** [comment]
Closing as an old ticket. Please reopen if needed.
