### ISSUE TITLE
How to add Notes in Swagger Editor ?

### ISSUE THREAD

**Issue by Mithun-Hegde** [swagger-api/swagger-editor#1087]
Hi actually i have similar condition description for most of the parameter which is not fit in parameter description because its huge. So i want to add notes in swagger editor and link it into conditional description. Is it to possible add ? Please let me know.

**Comment by webron** [comment]
I'm afraid you can't reference descriptions.

**Comment by Mithun-Hegde** [comment]
K thanQ @webron
