### ISSUE TITLE
allowEmptyValues in formData not working

### ISSUE THREAD

**Issue by anuvak** [swagger-api/swagger-editor#1094]
Hi,

I am new to swagger and I want to send empty values using swagger specification. For that i am using allowEmptyValues: true. my swagger code is as follows
```
        - name: 'p[1]'
          in: formData
          description: Document Type
          type: number
          allowEmptyValue: true
        - name: 'p[2]'
          in: formData
          description: Document Number
          type: string
          allowEmptyValue: true
        - name: 'p[3]'
          in: formData
          description: Document Part
          allowEmptyValue: true
          type: number
```

According to the allowEmptyValues property It sets the ability to pass empty-valued parameters. This is valid only for either query or formData parameters and allows you to send a parameter with a name only or an empty value. but i am not getting the name of parameter in requested url.

`curl -X POST --header 'Content-Type: multipart/form-data' --header 'Accept: application/json' -F k=bGVlZGFwaXVzZXI6OmxlZWRhcGl1**-F  -F  -F  -F  -F  -F  -F  -F  -F  -F  -F  -F  -F**   '`
but i am not getting the name of the parameter in the url .

Any help would be appreciated ...

**Comment by webron** [comment]
This should no longer be an issue with the new editor.
