### ISSUE TITLE
Default type of definitions containing "allOf" resolves to "undefined"

### ISSUE THREAD

**Issue by Kitanotori** [swagger-api/swagger-editor#1099]
# Reproduce:

https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/yaml/petstore-expanded.yaml
# Solution

Treat definitions containing "allOf" as "object".

**Comment by saharj** [comment]
Would you please tell me what you expect to see and what you get instead?

**Comment by Kitanotori** [comment]
As it says in the topic, I get "undefined", whereas in the case of other objects the UI doesn't show anything. You can easily see by trying the example I linked.

**Comment by stephanebachelier** [comment]
It's related to #476

**Comment by saharj** [comment]
@Kitanotori It seems this issue is somehow related to another one, so I'm going to close this. You can follow more about the issue there.
