### ISSUE TITLE
Swagger-Editor doesn't start on Heroku

### ISSUE THREAD

**Issue by jeffprestes** [swagger-api/swagger-editor#1100]
At Swagger-Editor documentation, it says to run it at custom port just:

```
PORT=xx
```

As in Heroku the port number is random I've tried to put this statement at start script:

```
"start": "PORT=$PORT  npm start"
```

But I got this error from Heroku:

```
npm ERR! Failed at the swagger-editor@2.10.3 start script 'PORT=$PORT  npm start'.
```

I could put this statement in the Swagger-Editor

```
app.listen((process.env.PORT || 8080));
```

 but I couldn't find where in the Swagger-Editor code is defined the port 8080.

Could somebody help me out?

Thanks in advance!

**Comment by BadPirate** [comment]
*BUMP* I'm having a similar issue, in my case it's hitting a memory error on unpacking.  Is there a light weight way to launch it?  Can Webpack be turned off?

**Comment by webron** [comment]
This should no longer be an issue with the new editor.
