### ISSUE TITLE
'#' character is not encoded at the url

### ISSUE THREAD

**Issue by yangjunsss** [swagger-api/swagger-editor#1101]
docker@default:~/postgresql$ docker images
REPOSITORY                                   TAG                 IMAGE ID            CREATED             SIZE
swaggerapi/swagger-editor          latest              bb4e117192fb        2 weeks ago         108.2 MB

I use the container(imageID:bb4e117192fb) to run the swagger editor for local and the url '#' character is not encoded.

yaml:

``` yaml
  /user/{name}:
    get:
      tags:
        - User
      parameters:
        - name: name
          in: path
          type: string
          required: true
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              ret_code:
                $ref: '#/definitions/ret_code'
              user:
                $ref: '#/definitions/user'
```

The url I set is 'GET http://api.xxx.com/user/yangjunsss@xxx.com#user1 HTTP/1.1'
But the real request is:

```
Request URL:http://api.xxx.com/user/yangjunsss@xxx.com
Request Method:GET
Status Code:200 OK
Remote Address:127.0.0.1:80
Response Headers
view source

```

When I try to encode manually, I got 404 error

```
URL:http://api.xxx.com/user/yangjunsss@xxx.com%23user1
Request Method:GET
Status Code:404 Not Found
Remote Address:127.0.0.1:80
```

**Comment by saharj** [comment]
Do you type the `#` or does the editor put it in the URL?

**Comment by webron** [comment]
Closing due to lack of response.
