### ISSUE TITLE
Saving Import onto Server

### ISSUE THREAD

**Issue by joynben** [swagger-api/swagger-editor#1102]
Need help in saving yaml file to server where swagger-editor is hosted.  Here are the changes made in default configuration file

"useBackendForStorage": true,
 "backendEndpoint": "/editor/spec",       "useYamlBackend": true,

/editor is where swagger-editor files are and spec directory is created as backend to hold files

When IMPORT is clicked after file selection, swagger-gui editor shows SERVER CONNECTION ERROR.

NGINX log shows PUT /editor/spec HTTP/1.1" 409 578 "http://localhost/editor/".

Anyone ran into similar issue or has advise on how to resolve?

**Comment by taylk808** [comment]
I figured it out and able to have backend to save file.
However, all the files being imported is called spec and overwriting each other, is there a way to take the name of file client import and save it as that name?  ie, user uploads SampleA.yaml, server will save it as SampleA.yaml?

**Comment by webron** [comment]
This is currently not supported with the new editor.
