### ISSUE TITLE
Error/help in heading

### ISSUE THREAD

**Issue by GlauberF** [swagger-api/swagger-editor#1110]
*Error/help in heading*

**change heading**

I'm working with the local editor, when I export the heading it defaults.
![g1](https://cloud.githubusercontent.com/assets/11314585/20214803/822e2fca-a7f7-11e6-92fd-ff79902a5617.png)

I want to change and leave the name by module, for example yours.
![g2](https://cloud.githubusercontent.com/assets/11314585/20214842/bc8412c0-a7f7-11e6-9724-72ddcc43cfee.png)

**How do I change and leave the same as yours?**

**Comment by webron** [comment]
This is swagger-ui and not swagger-editor, and you opened the ticket there as well.
