### ISSUE TITLE
invalid json definition gets validated with no errors

### ISSUE THREAD

**Issue by lucamaf** [swagger-api/swagger-editor#1111]
**Swagger File**

```yaml
 # paste your swagger document here
```

* Version: swagger2.0
* Browser/OS: Chrome 54, Windows 10

**Issue**
described in the subject.
attached you can find the invalid swagger definition (error on line 61).
[usos.json.txt](https://github.com/swagger-api/swagger-editor/files/589069/usos.json.txt)

**Comment by webron** [comment]
The editor is meant to be used for editing YAML files and not JSON files, so producing errors on invalid JSON is out of scope.
