### ISSUE TITLE
Cannot save JSON entered in the Parameters - Edit JSON text box

### ISSUE THREAD

**Issue by MMJM** [swagger-api/swagger-editor#1115]
**Swagger File**

```
swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    post:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: nameJSON
          in: body
          description: The name of the person to whom to say hello
          required: true
          schema:
            $ref: "#/definitions/Hello"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
 
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Hello:
    type: object
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
```

* Version: 
* Browser/OS: 
Chrome Windows 10
**Issue**

I can't for the life of me get the Edit JSON button on a parameter to Save the JSON and pass it in to the request.

![image](https://cloud.githubusercontent.com/assets/16725454/20373431/96f06d72-acbd-11e6-8285-e36eaff98e4d.png)

**Comment by buddiz** [comment]
Same issue here =) Forced to use Postman or similar tools to try this route of my API...
@MMJM : have you solved the issue yet ? Any advice to me ?

Happy holidays !

**Comment by BrOrlandi** [comment]
Same problem here!

**Comment by liuzhongshu** [comment]
Same problem

**Comment by bojanbjelic** [comment]
same problem!

**Comment by dhirajataws** [comment]
same problem. can we use any previous version ?

**Comment by HodGreeley** [comment]
This looks like an issue with setting the JSONEditor options.  Currently specifying a body parameter fails the check that labels the schema as "loose".  See `isLooseJSONSchema` in json-schema.js.

If you explicitly add `additionalProperties: true` to the spec, it will save the body.  However it also enables the  "Object Properties" button.  If I recall, this was not the previous behavior.

One hack is to set `disable_properties: true` in `looseOptions`.  That lets you set turn on additional properties while suppressing the other button.

Tried a couple of things for a real fix but haven't figured it all out.

**Comment by webron** [comment]
This should no longer be an issue with the new editor.

**Comment by JougyStyle** [comment]
Thanks !

I'll have a look today to confirm :-)
Was using postman instead - but it has limits (especially to expose quality docs to the world ;^))
