### ISSUE TITLE
problem with zh-cn

### ISSUE THREAD

**Issue by xuerge** [swagger-api/swagger-editor#1116]
* Version: 2.0
* Browser/OS: chrome

**Issue**
can't input with zh-cn

**Comment by xuerge** [comment]
![9a3a084b-33d1-46d7-9875-0662acd7f496](https://cloud.githubusercontent.com/assets/3351360/20374270/71aab6cc-acb2-11e6-8445-80843b1a5207.png)

**Comment by webron** [comment]
This should no longer be an issue with the new editor.
