### ISSUE TITLE
Editor crashes on duplicate double quotes

### ISSUE THREAD

**Issue by Tobias4872** [swagger-api/swagger-editor#1118]
**Swagger File**

```yaml
definitions:
  NameEntity:
    ..
  NamedRelation:
    ..
  Site:
    description: The site entity
    allOf:
      - $ref: "#/definitions/NamedEntity"
      - type: object
        properties:
          publisher:
            $ref: "#/definitions/NamedRelation"
```

* Version: 2.10.3
* Browser/OS: 54.0.2840.71 (64-bit) on OSX El Capitan 10.11.6

**Issue**

Please see the snippet above which works fine, but if I accidently add a second double quote into the second $ref value like this

```yaml
definitions:
  NameEntity:
    ..
  NamedRelation:
    ..
  Site:
    description: The site entity
    allOf:
      - $ref: "#/definitions/NamedEntity"
      - type: object
        properties:
          publisher:
            $ref: ""#/definitions/NamedRelation"
```

the editor will crash.

Let me know if you have more questions.

Tobias.

**Comment by fehguy** [comment]
Thanks, this is a known issue and we have a fix that should get in shortly.

**Comment by webron** [comment]
This should no longer be an issue with the new editor.
