### ISSUE TITLE
Transitive $ref are resolved relative to the wrong file

### ISSUE THREAD

**Issue by anthomps** [swagger-api/swagger-editor#1119]
* Version: 2.10.3
* Browser/OS: Mac OS X - Safari

**Issue**

I have a specification that's split as follows

```
apis/
     api.json
model/
     part1.json
     part2.json
```
Inside api.json:

"$ref": "/model/part1.json"

Inside part1.json:

"$ref": "/model/part2.json"

Assume this is all hosted on www.example.com. I set the editor "Pointer Resolution Base Path" preference to http://www.example.com

Now I observe the following - 

1. The first ref resolves correctly - excellent!
/model/part1.json successfully resolves to http://www.example.com/model/part1.json

2. The second ref is resolved relative to part1.json, that is

/model/part2.json incorrectly resolves to http://www.example.com/model/model/part2.json

I verified this by looking in the web server access.log. It is giving a 404 for the URI as it's incorrect.

I believe this is incorrect. Relative $ref starting with / should resolve relative to the doc root (www.example.com/), right?

**Comment by webron** [comment]
Yeah. It'd really help if you can provide the actual example you use though.

**Comment by anthomps** [comment]
To be clear, it's the JSON files you want, right?

They're proprietary but I'll try to boil it down to a minimal example that exhibits the problem that I can share.

**Comment by webron** [comment]
Yeah, the JSON files. If it makes it easier, you can email me directly instead of attaching here, but a minimal reproducing example would work great as well.

**Comment by anthomps** [comment]
[minAPI.txt](https://github.com/swagger-api/swagger-editor/files/598885/minAPI.txt)
[minimal.txt](https://github.com/swagger-api/swagger-editor/files/598887/minimal.txt)
[nested.txt](https://github.com/swagger-api/swagger-editor/files/598888/nested.txt)

Here's an example. I had to change the filename extensions to .txt to get this to let me upload them, so please change back to .json. Create 2 folders, apis and model and drop them in the natural places and you should get an undefined error for Nested.

 To fix it, all you have to do is change the line in minimal.json to be           

"$ref": "./nested.json#/Nested" instead of           "$ref": "/model/nested.json#/Nested"

**Comment by anthomps** [comment]
This is what I see in the access log when it fails

127.0.0.1 - - [17/Nov/2016:20:52:20 -0500] "GET /model/model/nested.json HTTP/1.1" 404 169 "http://127.0.0.1:8080/dist/c096fa5e289976e1a791.worker.js" "Mozilla/5.0  (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.8 (KHTML, like Gecko) Version/9.1.3 Safari/601.7.8"

**Comment by webron** [comment]
This should no longer be an issue with the new editor.
