### ISSUE TITLE
Accept a query parameter for disabling the editor pane 

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-editor#112]
When user visits the editor with `?docsonly=true` query param, only render docs pane and hide editor pane

**Comment by erikvanzijst** [comment]
Did this get implemented?

Or to put it differently; is there a way to use the editor as a regular viewer, without editing features? I like the editor a lot better than swagger-ui and would love to be able to use it for our public facing doco.

**Comment by mohsen1** [comment]
@erikvanzijst for now you can build a custom editor with a branding.css that hides the editor pane and the top menu bar. Please read the [configuration guide](https://github.com/swagger-api/swagger-editor/blob/master/docs/config.md)

**Comment by erikvanzijst** [comment]
Ok, that'll work for now. Thanks.

**Comment by mattaylor** [comment]
Please reconsider adding this as a standard query param option. Many cases where folks don't want or are not able to run their own custom local builds.
