### ISSUE TITLE
Does required only support strings?

### ISSUE THREAD

**Issue by DelightedD0D** [swagger-api/swagger-editor#1125]
**Swagger File**

```yaml
definitions:
  # input object definitions 
  Notification:
    type: object
    required: [body,details]
    properties:
      id:
        type: string
        description: Unique identifier representing a specific row in the database
      icon: 
        type: string
        description: The name of the icon to use see /icons. defaults to wrench
      color:
        type: string
        description: The color to use in the notification template
      title: 
        type: string
        description: A title for the notification 
      subTitle:
        type: string
        description: A sub-title for the notification
      createdDate:
        type: string
        description: The date the row was added to the database 
      body:
          $ref: '#/definitions/BodyObject'
      details:
        type: array
        items:
          $ref: '#/definitions/DetailObject'
      appendix:
        type: array
        items:
          $ref: '#/definitions/AppendixObject'
      footer:
          $ref: '#/definitions/FooterObject'
  
  BodyObject:
        type: object
        required: [summary]
        properties:
          summaryTitle:
            type: string
            description: Header text to appear above the notification body
          summary:
            type: string
            description: A short summary for this notification
          description:
            type: string
            description: A more lengthy description for the notification
          closing:
            type: string
            description: A closing comment
  
  DetailObject:
    type: object
    properties:
      label:
        type: string
        description: Text that will act as a label for this detail item 
      value:
        type: string
        description: The text to show for this detail
      highlighted:
        type: boolean
        description: Whether or not the detail item should be highlighted in the template
  
  AppendixObject:
    type: object
    properties:
      type:
        type: string
        description: "The type of display to use: list or  table"
      value:
        type: string
        description: The text to show for this detail
      highlighted:
        type: boolean
        description: Whether or not the detail item should be highlighted in the template
        
  FooterObject:
    type: object
    properties:
      link:
        type: object
        description: "The type of display to use: list or  table"
        properties:
          text:
            type: string
            description: The text to display for the link
          url:
            type: string
            description: The url for the link
  
```

* Version: 2.0
* Browser/OS: Mac, Chrome

**Issue**

Basically, I want to make `Notification.id`, `Notification.body`, and `Notification.details` required.  

Im using `required: [id,body,details]` but only `Notification.id` actually renders as required. Does `required` only support strings?

![screenshot at nov 26 23-38-30](https://cloud.githubusercontent.com/assets/8271955/20645883/8532e314-b431-11e6-895d-30da0500c014.png)

**Comment by fehguy** [comment]
Yes, you can only use strings for the required array, and they should reference existing, available property names.

**Comment by DelightedD0D** [comment]
@fehguy  so you cant make a property required if the property contains a boolean, array, or object?? That seems, well odd, No?

**Comment by fehguy** [comment]
That's not quite what I'm saying.  You would declare the `required` fields inside your object.  So for example:

```yaml
User:
  required:
  - id  # id is required
  - address # the address object is required, but we don't specify _here_ what is required in the object itself
  properties:
    id:
      type: string
    address:
      type: object
      required:
      - street # street property is required
      properties:
        street:
          type: string
```

So think of the `required` attribute as having "no object depth".  It only applies to properties in the current hierarchical scope.  If you want to look into an object property, you would define it there, like I did in the address object

**Comment by DelightedD0D** [comment]
@fehguy gotcha, ok, yeah that's what Im doing now, that does work to a degree but it requires the user expand the nested object to know if any of it's properties are required, I was hoping there was a way to indicate that the object itself was required so the user would know to expand the object. Oh well, thank you for clarifying, at least I know to stop fighting with it lol :)

**Comment by DelightedD0D** [comment]
@fehguy Any chance we can make this an improvement request? Maybe show an orange start next to nested objects that contain required properties?

**Comment by fehguy** [comment]
We can't change the syntax for the `required` field because it's straight from JSON schema.  But possibly improve the display.  Can you please explain more?

**Comment by DelightedD0D** [comment]
@fehguy Sure. 

Consider the below definition. In the *Notification* model, the properties `title` and `body.summary` have been marked as required. However, if a user looks at Swagger UI, it looks like *only* the `title` property is required:

![screenshot at nov 30 11-08-41](https://cloud.githubusercontent.com/assets/8271955/20762917/aa3aa886-b6ed-11e6-945b-dcea2b1493a9.png)

Only if the user expands the `body` object do they then see that `body.summary` is also required and even then, it's not entirely clear. Is `body.summary` *always* required, or is `body.summary` only required *if* a `body` property is provided? 

![screenshot at nov 30 11-13-20](https://cloud.githubusercontent.com/assets/8271955/20763042/1c9ae080-b6ee-11e6-8e17-d0e32f9bff11.png)


Of course, the "try operation" understands they are both required and enforces that, but for someone just reading the docs, it's a bit ambiguous.

Personally, I would like to see the UI respect the rule `required: [body, title]` and show the `<span class="required">*</span>` next to the the *collapsed*  `body` property itself like this:

![screenshot at nov 30 11-21-33](https://cloud.githubusercontent.com/assets/8271955/20763457/b76571b0-b6ef-11e6-879d-e240a2541b08.png)


Then, if the user expands `body`, they would see which specific properties *it* must provide:

![screenshot at nov 30 11-28-30](https://cloud.githubusercontent.com/assets/8271955/20763583/40ca37b0-b6f0-11e6-8476-05f56340c59c.png)


```

swagger: '2.0'
info:
  version: "1.0.0"
  title: Some API 
host: homestead.local
basePath: /api/v1
schemes:
  - http 
consumes:
  - application/json
produces:
  - application/json 
paths:
  /notifications: 
    post:
      # Describe this verb here. Note: you can use markdown
      consumes:
        - application/json
      description: Some cool endpoint
      parameters:
        - name: body
          in: body
          description: description
          required: false
          schema:
            $ref: '#/definitions/Notification'
              
      responses: 
        200:
          description: Successful response
          schema: 
           type: object  
           properties:
             success:
               type: boolean   
definitions: 
  Notification:
    type: object
    required: [body, title]
    properties:
      title: 
        type: string  
      body:
        title: ""
        required: [summary]
        type: object
        properties:
          summaryTitle:
            type: string 
          summary:
            type: string 
          description:
            type: string 
          closing:
            type: string 
            default: TIMESTAMP 
```
