### ISSUE TITLE
Cannot type anything in the editor : Uncaught TypeError: i.transformAction is not a function.

### ISSUE THREAD

**Issue by CurosMJ** [swagger-api/swagger-editor#1126]
**Swagger File**
There's no point in providing the file, I tried to create a new file and type within it, it still doesnt work.

```yaml
 # paste your swagger document here
```

* Version: 2.10.3
* Browser/OS: Chrome/Ubuntu 14.04 (Using editor.swagger.io, not local)

**Issue**
I am unable to type/edit/backspace anything in the editor, and opening dev console shows this exception happening everytime I hit keyboard:

Uncaught TypeError: i.transformAction is not a function at index.js line 11989

**Comment by khjohnson1972** [comment]
I had the same issue. In Firefox I used Dev Tools to clear "Local Storage." This fixed the issue, but took some digging. I also lost my editor settings, but I am OK with that. I was running an older version of Swagger Editor and installed the latest release. This may have cause an issue with Local Storage.

**Comment by CurosMJ** [comment]
For me, clearing cookies and storage made it work. 

And, I remember setting Mode in the Preferences > Editor settings to JSON and this recreated the issue for me.

**Comment by saharj** [comment]
Do you still have this issue?

**Comment by khjohnson1972** [comment]
@saharj - I don't have the issue after clearing my local storage. Thanks
