### ISSUE TITLE
Unhelpful and suspect error "instance failed to match at least one required schema among 2"

### ISSUE THREAD

**Issue by readnotify** [swagger-api/swagger-editor#1127]
The UI is simply displaying that error - google suggests that the payload carrying that error has significantly more detail, except the UI is not rendering any of it: there needs to be a way to see the entire error, not just this small description.

And, on the subject of the error itself: it suddenly started today, I don't think it's correct - all my backed-up YML produces the same error now, but none of them had errors when I backed them up last week.

... and on the subject of the error wording: that is a totally useless description. I have no idea whatsoever what it might mean, or what it's referring to, or why. This is a textbook example of "how never to write an error message". Please find what issued that error, and adjust it to include something useful that we can find/reference/understand!

**Comment by webron** [comment]
Unfortunately, the error messages are produced by a third party tool that does JSON Schema validation. These error messages are indeed not overly useful, especially if you don't know Swagger's JSON Schema (which you shouldn't really have to).

We're working on something that will greatly improve this, but it'll take a bit before it's out.

**Comment by webron** [comment]
This should no longer be an issue with the new editor.
