### ISSUE TITLE
`defaults.editorOptions` not used by default.

### ISSUE THREAD

**Issue by Parakleta** [swagger-api/swagger-editor#1129]
It appears the `defaults.editorOptions` is currently only used by the `resetSettings` function, but not by the `loadEditorSettings` function.  I think [scripts/services/editor.js#L161](https://github.com/swagger-api/swagger-editor/blob/5fbffc77b643d4459ce310c1e2c150e8ab2fd93d/scripts/services/editor.js#L161) should probably read:

```js
    options = options || editorOptions || {theme: defaultTheme};
```

**Comment by webron** [comment]
This is no longer relevant with the new editor.
