### ISSUE TITLE
Auto-hidden Scroll bars

### ISSUE THREAD

**Issue by jwest-apigee** [swagger-api/swagger-editor#113]
If possible it would be nice to have auto-hidden scroll bars that appear when you scroll.  For example, this file: https://github.com/apigee-127/usergrid-swagger/blob/master/UserGrid.yaml is quite long and takes lots of scrolling to move around in.

**Comment by mohsen1** [comment]
Now that you can change the theme, its easy to choose a higher contrast theme.
