### ISSUE TITLE
I cannot either download the edited file nor copy the edited file.

### ISSUE THREAD

**Issue by zhang8473** [swagger-api/swagger-editor#1130]
**Swagger File**

```yaml
 # paste your swagger document here
```

* Version: 
latest
* Browser/OS: 
Google Chrome Version 54.0.2840.100 (64-bit)
Ubuntu 15.04 native web browser

**Issue**
I cannot either download the edited file nor copy the edited file.

**Comment by webron** [comment]
Are you running your own instance or using http://editor.swagger.io?

**Comment by zhang8473** [comment]
on  http://editor.swagger.io

**Comment by webron** [comment]
Try refreshing your browser and download it then. You shouldn't lose your work.

**Comment by zhang8473** [comment]
I even reopened the chrome. I can see my work is there but I just cannot export my work. 

I am using Ubuntu 15.04

**Comment by webron** [comment]
Try selecting all, and then 'ctrl+c' to copy.

**Comment by zhang8473** [comment]
ctrl+C seems work some times but not all the time. Now at least I got my work copied out.

**Comment by kellyfj** [comment]
Occurs for me too
```
$ grep version package.json 
    "mversion": "^1.10.1",
  "version": "2.10.4"
```
Chrome Version 54.0.2840.98 (64-bit)
Mac OS/X: 10.10.5

**Comment by webron** [comment]
This should no longer be an issue with the new editor.
