### ISSUE TITLE
Error on array response example

### ISSUE THREAD

**Issue by marshfire** [swagger-api/swagger-editor#1134]
**Swagger File**

```yaml
 # paste your swagger document here
paths:
  /api/trackers:
    get:
      description: |
        Get known trackers.
      responses:
        200:
          description: Successful response
          schema:
            title: TrackerIDs
            type: array
            items:
              type: string
          examples:
            - '00:0a:95:9d:68:16'
            - '00:0a:95:9d:68:33'
```

* Version: 2.10.3
* Browser/OS: Chrome 54, Ubuntu 16.04 LTS

**Issue**
When I define an array of strings as a response value and I create an example for it I get a Swagger Error "Not a valid response definition". The example is rendered anyway.

In Swagger UI it works without failures.

**Comment by hkosova** [comment]
The error is valid. When using `examples` at the response level, each example needs to be identified by its MIME type:

      responses:
        200:
          description: Successful response
          schema:
            ...
          examples:
            application/json:
              - '00:0a:95:9d:68:16'
              - '00:0a:95:9d:68:33'

Relevant piece of spec:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#exampleObject

Or you can add an `example` at the schema level (note it's `example` and not `examples`):

        200:
          description: Successful response
          schema:
            title: TrackerIDs
            type: array
            items:
              type: string
            example:
              - '00:0a:95:9d:68:16'
              - '00:0a:95:9d:68:33'
