### ISSUE TITLE
Help in Free Form query string paramete

### ISSUE THREAD

**Issue by MohamadrezaGolabshekar** [swagger-api/swagger-editor#1135]
Hi,
I have a url like this  “ http://192.168.1.144:7000/api/v1/buckets.json?query[0][title][like]=test1&query[0][title][not]=test2 “
i want to create json for swagger that support key value parameters that can manage key and value 
i use this parameter 

	"query" : {
            "name": "query",
            "in": "query",
            "description": "this is query.",
            "required": false,
            "type": "array",
            "items" : {
              "type" : "string"
            },
            "format": "string",
            "collectionFormat" : "multi"
        }
but this config create url like this “ http://192.168.1.144:7000/api/v1/buckets.json?query=test1&query=test2 “
in this url i can not manage keys 
@saharj @webron Do you have idea to resolve this issue?
Thank you.

**Comment by webron** [comment]
The spec itself doesn't support associative arrays like that. You can define `query[0][title][like]` explicitly, but you cannot define it as something dynamic that will be supplied by the user.

**Comment by MohamadrezaGolabshekar** [comment]
Thank you ;)
