### ISSUE TITLE
C# 2.0 client CodeGen Authentication issue 

### ISSUE THREAD

**Issue by HarprasadShukla** [swagger-api/swagger-editor#1137]
Hi Team,
I have generated C#2.0 client code using swagger editor. It is working fine without Authentication but when applying UID/PWD it is failing "Unauthorized access denied". Can i get C# client code generated with authentication UID/PWD code with unit test cased. How to pass authentication unit test cases and what are places code changes required in configuration.cs file.

Regards,
Harprasad    
 

**Swagger File**

```yaml
 # paste your swagger document here
```

* Version: 
* Browser/OS: 

**Issue**

**Comment by HarprasadShukla** [comment]
I need quick solution please reply ASAP if possible or share the contact number to explain issue directly.

**Comment by chrisdudley** [comment]
Since you say your issue is about generating client code, you likely want to raise it here: https://github.com/swagger-api/swagger-codegen

**Comment by webron** [comment]
As said, please open the ticket on the codegen project.

**Comment by HarprasadShukla** [comment]
We are consuming web API in .net application so generated swagger C# 2.0 client code but missing to pass  Header details Authentication in c# generated code. Without Authentication API responding correctly but when applying UID/PWD in c# generated code it is returning authorization denied. Could you please provide some sample to authenticate/Authorize web API generated code by Swagger C# client code. Just we can pass UID/PWD in config file based on different environment hosted API?
Do let me know in case further clarification required.

**Comment by HarprasadShukla** [comment]
Could you please redirect right team. I created new request based on suggestion.

**Comment by webron** [comment]
@HarprasadShukla you need to open the ticket on the swagger-codegen project, as mentioned above.

**Comment by HarprasadShukla** [comment]
Team,

I raised couple of ticket GitHub and raised issue as per your email but 
still waiting response. I emailed to SmartBeans team. Please direct ticket 
to right team incase still in different root. I raised 3 more ticket fro 
same.

Looping to Micheal.

Regards,
Harprasad
