### ISSUE TITLE
Multiple tags for same path breaks tag listing on the preview ui

### ISSUE THREAD

**Issue by NeoElit** [swagger-api/swagger-editor#1138]
I'm using the default.yaml example provided with swagger-editor itself to tryout. I want to add multiple tags to the same path. I'm adding something like following.
```yaml
 tags:
        - Products
        - Data
```
However, it causes each tag to break into separate lines separated by horizontal line in the preview.
![issue](https://cloud.githubusercontent.com/assets/14013159/21314509/85774fec-c61d-11e6-987d-11e005586ae8.png)
Is this the actual behaviour or is it a bug?

* Version: swagger: '2.0'
* Browser/OS: Firefox on Ubuntu 16.04LTS

**Comment by webron** [comment]
That looks like a bug.

**Comment by saharj** [comment]
This looks like a normal behavior. For example see the Instagram API. However, I'm not sure why it shows `1` in front of `Data`

**Comment by webron** [comment]
This is no longer an issue with the new editor.

**Comment by raxit65535** [comment]
This quite old thread, but I am facing this issue again..
If I have multiple tags inside swagger.yaml then I see same endpoint description twice. (once under each tag)
I have generated the swagger.yaml using go-swagger auto generation tool.
https://goswagger.io/use/spec/route.html

Any suggestion?

<img width="319" alt="Screen Shot 2021-03-03 at 6 05 49 PM" src="https://user-images.githubusercontent.com/21283893/109899697-19130380-7c4b-11eb-9dfe-51fc6f0d2423.png">
<img width="682" alt="Screen Shot 2021-03-03 at 6 09 06 PM" src="https://user-images.githubusercontent.com/21283893/109900021-8d4da700-7c4b-11eb-880b-d6d773638083.png">
