### ISSUE TITLE
force user to write his error codes in a referenced way

### ISSUE THREAD

**Issue by michel19** [swagger-api/swagger-editor#1139]
i need the user to write his error codes in this way only:
```
ErrorModel: 
      required: [ code, message],
      properties: 
        code: 
          type: integer,
          format: int32
        ,
        message: 
          type: string
```
And not this way :
` "404":
          description: User not found`
What should i change and where?

**Comment by webron** [comment]
Question is not clear...

**Comment by michel19** [comment]
the user that rights a yaml code inside the editor can even write the error codes and messages in $ref and point it to a definition so that the error messages are unified, or he can gibe it a code and a description for every API randomly. In my case, i prefer to have a unified error codes. 
So i need to know where to change in the code so the user will get a syntax error in case he used the second way and gave random code errors.

**Comment by webron** [comment]
The editor is not customizeable this way. This is done via validation which is based on either the JSON Schema or an additional specialized validation library. You can change the JSON Schema used or add an additional check in the other library, which you'd also need to fork an change.
