### ISSUE TITLE
Can't change editor mode from yaml

### ISSUE THREAD

**Issue by tristansokol** [swagger-api/swagger-editor#1140]
* Version: Version 2.10.3
* Browser/OS: Chrome/Mac

**Issue**
http://editor.swagger.io/#/ - > preferences - > Editor Settings -> Mode
Selecting anything other than yaml seems to not work. Appears to try to load new js files that cannot be found. 
 `http://editor.swagger.io/mode-json.js Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by webron** [comment]
This is not an issue. We might try to remove that menu option. The editor is intended for YAML editing only.
