### ISSUE TITLE
Add SSL support to hosted editor

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-editor#1148]
This means moving away from the github pages, but it may make sense.  Currently the editor is only available online (at least here) with a non-SSL transport.

**Comment by mohsen1** [comment]
Since all of editor output is just a bunch of static files, uploading to S3 would be the simplest solution. Although publishing to DockerHub and running it using Docker in production have the benefit of keeping the DockerHub image up to date.

**Comment by fehguy** [comment]
Yes, also publishing to docker has the added benefit of flexing the docker build.  Just did this on swagger-ui as well.

**Comment by webron** [comment]
We no longer use github pages.
