### ISSUE TITLE
Cannot find module 'webpack'

### ISSUE THREAD

**Issue by mickyd** [swagger-api/swagger-editor#1150]
Following #671 who said:

>chrisdudley commented on Sep 30, 2015
>As per the docs:

>git clone https://github.com/swagger-api/swagger-editor.git
>cd swagger-editor
>npm start

...i tried that just now and got:

> swagger-editor@2.10.4 start D:\development\git\3rd Party\swagger-editor
> node server.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\development\git\3rd Party\swagger-editor\server.js:3:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! swagger-editor@2.10.4 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swagger-editor@2.10.4 start script 'node server.js'.
npm ERR! This is most likely a problem with the swagger-editor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs swagger-editor
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls swagger-editor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\development\git\3rd Party\swagger-editor\npm-debug.log

[npm-debug.zip](https://github.com/swagger-api/swagger-editor/files/693132/npm-debug.zip)

**Comment by AbuJunayd** [comment]
I have exactly the same error.

**Comment by jonajgs** [comment]
only run, `npm link webpack`

**Comment by webron** [comment]
This is no longer an issue with the new editor.
