### ISSUE TITLE
Response ERROR Server not found or an error occurred

### ISSUE THREAD

**Issue by pradeepYogesh** [swagger-api/swagger-editor#1151]
Hi I am new to swagger framework, and I tried writing sample yml file for the api hostel from my local server using cherrypy.
I am running local swagger editor in the http://192.168.10.62:8081/ and cherrypy in  http://127.0.0.1:8080
I have enabled cross-origin call in cherrypy but still i get **Response
ERROR Server not found or an error occurred**   from Iam sending the request to server using swagger-editor

I have attached the screen-shot of my swagger-editor and cherrypy code.
Please help me
![screenshot from 2017-01-10 17 41 45](https://cloud.githubusercontent.com/assets/23195420/21805905/a5b91b28-d75c-11e6-9058-f91250a88a8a.png)
![screenshot from 2017-01-10 17 45 35](https://cloud.githubusercontent.com/assets/23195420/21805906/a5bd0fe4-d75c-11e6-9035-8f3240d04e55.png)
![screenshot from 2017-01-10 17 46 50](https://cloud.githubusercontent.com/assets/23195420/21805920/ccf1cd98-d75c-11e6-98fa-3385549e6e39.png)

 

**Swagger File**

```yaml
 # paste your swagger document here
```

* Version: 
* Browser/OS: 

**Issue**

**Comment by webron** [comment]
Can you check your browser's network console to see what request and response you get from that action?

**Comment by pradeepYogesh** [comment]
I had opened the browser console window . It says 
XMLHttpRequest cannot load http://127.0.0.1:8080/returnTestJason/?key=japan. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8081' is therefore not allowed access.

But I am getting request to my cherrypy localhost server .. I have attached the screen shot of the console,cherrypy code with logs which I got in the server console.
Please look into this issue.

PS: Am I doing it correctly. I want to write swagger yml for existing REST api . So Is it correct way to start ie Write a yml file to some dummy api launched in your local browser and then generate the client and server code from the yaml file.
Or IS THERE ANY OTHER WAY? PLEASE LET ME KNOW AND I DONT WANT TO USE ANY FRAMEWORKS LIKE JAX-RS etc which supports it through anootations etc


![screenshot from 2017-01-11 08 50 48](https://cloud.githubusercontent.com/assets/23195420/21834487/78a0a6cc-d7db-11e6-90fe-080d04bce014.png)
![screenshot from 2017-01-11 08 51 59](https://cloud.githubusercontent.com/assets/23195420/21834488/78a3d52c-d7db-11e6-8d7c-dbb106a42103.png)
![screenshot from 2017-01-11 08 52 10](https://cloud.githubusercontent.com/assets/23195420/21834489/78a40a7e-d7db-11e6-8ba6-7a180bdf5475.png)

**Comment by webron** [comment]
That's why I wanted to see the network tab, not the console... :)

**Comment by pradeepYogesh** [comment]
Its CORS issue. My browser was blocking cors requests. So closing the issue.

**Comment by kuo000** [comment]
Hi @pradeepYogesh,

I'm facing exactly the same issue using Chrome. Do you mind sharing how you fixed the problem? Any browser settings I should change.

Thanks.
