### ISSUE TITLE
Posting body as text/plain not working

### ISSUE THREAD

**Issue by DjLeChuck** [swagger-api/swagger-editor#1153]
**Swagger File**

```yaml
---
swagger: "2.0"
info:
  title: "API"
  version: "1.0.0"
host: localhost:10010
basePath: /users
schemes:
  - "http"
produces:
  - "application/json"
paths:
  '/{email}/password':
    post:
      consumes:
        - "text/plain"
      parameters:
        - name: "email"
          in: "path"
          required: true
          type: "string"
          format: "email"
        - name: "body"
          in: "body"
          required: true
          schema:
            type: "string"
            format: "password"
      responses:
        '204':
          description: "Success"
```

* Version: 2.10.3
* Browser/OS: Chrome 55.0.2883.87 / Windows 10

**Issue**
Posting data in body with a text/plain Content-Type is not supported, no value is sent so `req.swagger.params.body.value` is undefined.
If I try with Postman for example it works the value is in `req.swagger.params.body.value`

**Comment by webron** [comment]
Yup, confirmed as a bug.

**Comment by 0xC0DEBA5E** [comment]
I discovered the same issue. I accidentally posted it to swagger-ui at first:

When Content-Type is set to `text/plain` or `text/plain; charset=utf-8`:
- the Content-Type header of the request is missing. 
- there is no way to include plain-text in the request as the normal param-input values are ignored.

Also, when you don't select anything, there is an empty `Content-Type:`-Header in the request, which could lead to unexpected results.

Suggestion: Add a `<input type="text" ... />` for the content of the request (instead of parameter input tags), when Content-Type is set to  an "unsupported" Mime-Type.
```yaml
# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.0"
  title: Person

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /person:
    # This is a HTTP operation
    post:
      # Describe this verb here. Note: you can use markdown
      description: |
        Create new `Person`
      # This is array of GET operation parameters:
      
      consumes:
        - 'text/plain; charset=utf-8'
        - 'application/json'
      
      parameters:
        # An example parameter that is in query and is required
        -
          name: name
          in: body
          description: Size of array
          required: true
          schema:
            type: string
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            type: string
```
P.S.: I'm using `v2.10.4` of the swagger-editor.

**Comment by 0xC0DEBA5E** [comment]
I think `getRequestBody()` in [swagger-editor/blob/master/scripts/controllers/tryoperation.js](https://github.com/swagger-api/swagger-editor/blob/master/scripts/controllers/tryoperation.js) might be the problem. It returns null, if `contentType` is not one of the cases handled by the if- and else-if statements.

**Comment by TokenJan** [comment]
Is this issue solved or not. I still receive a null object when `text/plain` format is sent in the request body? @0xC0DEBA5E I took your suggestion and it still didn't work. It seems that I cannot receive any other format except `application/json`.

**Comment by webron** [comment]
@TokenJan with which version of swagger-editor did you try it with?

**Comment by TokenJan** [comment]
@webron Actually, I'm using the swagger-ui with version 2.2.10

**Comment by TokenJan** [comment]
@webron Actually, I'm using swagger-ui with version 2.2.10.
following is the yaml file i used
```yaml
paths:
  /runbooks:
    post:
      description: Create a new runbook
      operationId: createRunbook
      tags:
        - runbooks
      consumes:
        - application/json
        - text/plain
      produces:
        - application/json
      parameters:
        - name: publish
          in: query
          description: Define to publish new runbook directly
          required: false
          type: boolean
          allowEmptyValue: false
        - name: runbook
          in: body
          description: Values to change in a runbook
          required: true
          schema:
            type: string
```
after I make a request in `text/plain`, I do have `content-type` value, but the `body` object is empty. It seems that it only works with the request in `application/json`.

**Comment by TokenJan** [comment]
@webron Sorry to confuse you, actually it's not a bug, only my mistake. forget to parse the body as text.

**Comment by webron** [comment]
This is no longer an issue with the new editor.

**Comment by kamil-kielczewski** [comment]
I use [this](https://stackoverflow.com/a/48413161/860099)

 *     consumes={"multipart/form-data"},
 *     produces={"text/plain, application/json"},
