### ISSUE TITLE
Could not enter

### ISSUE THREAD

**Issue by kudorori** [swagger-api/swagger-editor#1154]
**Swagger File**

```yaml
 # paste your swagger document here
```

* Version:  2.0
* Browser/OS:  Google Chrome 55.0.2883.95 / macOS Sierra

**Issue**

I'm using **OpenVanilla input** in **Chrome** Swagger Editor, Could not enter

**Comment by fehguy** [comment]
what does that mean?

**Comment by kudorori** [comment]
I can not normally use my input method input

我無法正常使用我的輸入法輸入

**Comment by atdiff** [comment]
I'm also unable to use the online editor in Chrome.  I can't enter data in the text area at all.  It shows an error in the console about not finding the util and json mode modules

**Comment by webron** [comment]
This is no longer an issue with the new editor.
