### ISSUE TITLE
yaml validation in the editor that returns an error with a red x sign 

### ISSUE THREAD

**Issue by michel-el-hajj** [swagger-api/swagger-editor#1155]
* Version: *
* Browser/OS: *

How can i get the validator that runs on every change and returns the red x sign in case of a typo or a bad indentation etc....

**Comment by webron** [comment]
Hmm, what?

**Comment by michel-el-hajj** [comment]
in the swagger editor where you write your code using YAML, there is a syntax parser i guess or a validator that works on every change(deleted a letter, wrote a letter). In case of a syntax error or a bad indentation, a red error sign appears on the left side and on mouse over you get the error message. I need it in my project so where do i find it in your code?

**Comment by webron** [comment]
Closing as an old question. Please reopen if still relevant.

**Comment by drewish** [comment]
I think the idea is how would you reuse the validations in an external program. This is one of the few ones I've seen that cites the line number with the problem. Most other libraries just cite the issues.
