### ISSUE TITLE
Adding $ref in formData parameter of type array

### ISSUE THREAD

**Issue by Furkanzmc** [swagger-api/swagger-editor#1156]
**Swagger File**

```yaml
swagger: "2.0"
info:
  version: "1.0.0"
  title: minimal
  description: News Articles ftw
paths:
  /users:
    get:
      parameters:
        - name: graduation_school
          in: formData
          description: The school the translator graduated from
          required: false
          type: array
          items:
            $ref: '#/definitions/bar'

      responses:
        200:
          description:  hello world
          schema:
            $ref: '#/definitions/foo'
definitions:
  foo:
    type: array
    items:
      $ref: '#/definitions/bar'
  bar:
    properties:
      bar:
        type: string
```

* Version: 2.10.3
* Browser/OS: Chrome 55.0.2883.87

**Issue**

That YAML file is rendered correctly on the right pane and I can set the parameter's value using the [online editor](editor.swagger.io) but it gives the `Not a valid parameter definition` error.

**Comment by fehguy** [comment]
You'll have to in-line the $ref for right now.  A fix is on the way, but it's a major redo, not a simple update

**Comment by Furkanzmc** [comment]
I'm sorry, I'm pretty new to Swagger. What do you mean by `in-line the $ref`?

**Comment by fehguy** [comment]
no problem.  Just change from this:

```yaml
      parameters:
        - name: graduation_school
          in: formData
          description: The school the translator graduated from
          required: false
          type: array
          items:
            $ref: '#/definitions/bar'
```

to this:

```yaml
      parameters:
        - name: graduation_school
          in: formData
          description: The school the translator graduated from
          required: false
          type: array
          items:
            type: string
```

**Comment by Furkanzmc** [comment]
Thank you so much for your help. I really appreciate the quick response.
I'm closing the issue since you explained it all.

**Comment by edgarjs** [comment]
has the fix been published yet? I'm having the same issue but I'm not sure how could I represent a more complex object (not a string) in-line?

```yaml
definitions:
  bar:
    properties:
      bar:
        type: string
      baz:
        type: integer
```

thanks

**Comment by webron** [comment]
@edgarjs not sure what you're asking. Complex types are not supported with formData parameters. If it's not related to that, please open a new ticket.

**Comment by arthurmelo88** [comment]
Explained ? this is a work around, not a solution ... 
Im facing the same thing right now
Swagger 2.0 can create c# client codes but cant reference formData parameters.
openAI 3.0 can reference formData parameters but wont generate c# client codes... frustrating
