### ISSUE TITLE
Enhancing Swagger Editor based on the Version 3.0 Language Specification

### ISSUE THREAD

**Issue by stevendearborn** [swagger-api/swagger-editor#1157]
**Swagger File**

```yaml
 # paste your swagger document here
```

* Version: 
* Browser/OS: 

**Issue**

**Comment by stevendearborn** [comment]
I noticed that version 3.0 of the now Open API specification, formerly known as Swagger has been released.  Are thre any plans on improving the Swagger Editor based upon the changes in the language specification?

**Comment by webron** [comment]
It wasn't released. It's going to take a few more months. When the time comes, we'll support it.

**Comment by stevendearborn** [comment]
Thanks.  I reviewed the specification again and noticed it was not released yet.  Some of the proposed improvements are verbose and redundant.  The "servers" feature: the ability of the user to select the destination of their API request is one I hear as feedback all of the time. I have other comments that would be better to place on the specification feedback site.  I will close this issue.
