### ISSUE TITLE
Cannot read property 'parameters' of null

### ISSUE THREAD

**Issue by sushmitanad** [swagger-api/swagger-editor#1160]
wanted to convert the attached yaml file to c# object, using "http://editor.swagger.io/#/". But getting below error. The same yaml is valid in 'n' other editors.
**Swagger File**

```yaml
 swagger: "2.0"
info:
 version: "1.0.0"
 title: "Swagger YAML Dummy Domain Model"
paths:
 /Hello:
 /ORG:
   userID: "xyz.abcd@udsfkjed.com"
   authenticated: "yes"
   regioName: "East US"
   locationID: 121212
   authorizationLevel: 1 #Admin privileges
   pendingBills:
    - billName: "fire alert"
      amountDue: 80
      dueDate: "12/3/2017"
    - billName: "electricity alert"
      amountDue: 0
      dueDate: "12/12/2018"
```

* Version: 2.0
* Browser/OS: chrome/win10

**Issue**
Unknown Error
Cannot read property 'parameters' of null
Jump to line

Details
 Object
message:  "Cannot read property 'parameters' of null"
code:  "UNCAUGHT_SWAY_WORKER_ERROR"
level: 900
type:  "Unknown Error"
description:  "Cannot read property 'parameters' of null"

**Comment by webron** [comment]
It's a valid YAML maybe, but it's not a valid Swagger specification.
