### ISSUE TITLE
Online editor not allowing text entry

### ISSUE THREAD

**Issue by atdiff** [swagger-api/swagger-editor#1164]
* Browser:  Chrome Version 55.0.2883.87 m
**Issue**
I'm unable to enter text into the editor.  Looking at the Chrome dev tools, in the console, the following errors appear:
- Warn: could not find module util
- GET http://editor.swagger.io/mode-json.js
- Uncaught TypeError: i.transformAction is not a function
This renders the editor unusable.

**Comment by BabuGiri** [comment]
i am also using same chrome browser and seeing this issue, is this problem with chrome. any help on how to resolve this error is greatly appreciated.

Thank you.

**Comment by Geam** [comment]
Same as atdiff and I've got a 404 on http://editor.swagger.io/mode-json.js

**Comment by saharj** [comment]
Unfortunately, I'm not able to reproduce the issue. Please clean up your cache and local storage and try again.

**Comment by atdiff** [comment]
Clearing storage in Chrome cleared up the text entry problem. Thanks @saharj for the suggestion
