### ISSUE TITLE
Custom Header not working

### ISSUE THREAD

**Issue by adheep** [swagger-api/swagger-editor#1167]
**Swagger File**

```yaml
swagger: '2.0'
info:
  version: '1.0.0'
  title: ABC - Rating API
  description: Get rates for the ABC Travel plans
  contact:
    name: Adheep M
    email: adheep_m@solartis.net
host: 127.1.1.12:8080
basePath: /Droo/serv
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /FireEventV2:
    post:
      description: Get Rates for the given input
      operationId: addPet
      produces:
        - application/json
      parameters:
        - name: Token
          in: header
          description: Authentication Token
          required: true
          type: string
          format: string
        - name: EventName
          in: header
          description: Name of the event to be invoked
          required: true
          type: string
          format: string
        - name: Rating
          in: body
          description: Rating content
          required: true
          schema:
            $ref: '#/definitions/customer'
      responses:
        '200':
          description: pet response
          schema:
            $ref: '#/definitions/pet'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  customer:
    type: object
    required:
     - ServiceRequestDetail
    properties:
      EndClientUserUniqueSessionId:
        type: string
      EndClientUserBrowserSessionId:
        type: string
      EndClientUserBrowserInformation:
        type: string
      PaaSClientIPAddress:
        type: string
      ClientUniqueRequestID:
        type: string
      ServiceRequestDetail:
        type: object
        required:
          - OwnerId
          - RegionCode
          - Token
          - ServiceRequestVersion
          - ServiceResponseVersion
        properties:
          ServiceRequestVersion:
            type: string
          ServiceResponseVersion:
            type: string
          OwnerId:
            type: string
          ResponseType:
            type: string
          RegionCode:
            type: string
          Token:
            type: string
          UserName:
            type: string
          LanguageCode:
            type: string
          BrowserIp:
            type: string
      QuoteInformation:
        type: object
        required:
          - ProducerCode
          - OwnerId
          - PlanName
          - PlanCode
          - StateCode
          - EventName
        properties:
          ProducerCode:
            type: string
          OwnerId:
            type: string
          DepartureDate:
            type: string
          ReturnDate:
            type: string
          DepositDate:
            type: string
          PolicyEffectiveDate:
            type: string
          PlanName:
            type: string
            enum: ["AP","CP","PR","Annual"]
          PlanCode:
            type: string
            enum: ["1","2","3","4"]
          TripCancellationCoverage:
            type: string
            enum: ["","With Trip Cancellation","With Trip Cancellation for Any Reason"]
          DestinationCountry:
            type: string
          StateCode:
            type: string
          QuoteType:
            type: string
          EventName:
            type: string
          TravelerList:
            type: array
            items:
              required:
                - TravelerDOB
                - TravelCost
              properties:
                TravelerDOB:
                  type: string
                TravelCost:
                  type: string
  pet:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      tag:
        type: string
  errorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
```

* Version: 2.0
* Browser/OS: Firefox/Windows

**Issue**
I am evaluating Swagger for REST API documentation and facing issues with custom Header configuration.
The API that I am testing against expects 2 custom http headers "Token" and "EventName". So I added the following configuration under "parameters"

- name: Token
          in: header
          description: Authentication Token
          required: true
          type: string
          format: string
        - name: EventName
          in: header
          description: Name of the event to be invoked
          required: true
          type: string
          format: string

When I use the "Try this operation" button I can see the configured headers in the panel

POST http://127.1.1.12:8080/Droo/srv/FEv2 HTTP/1.1
Host: 127.1.1.12
Accept: application/json
Accept-Encoding: gzip,deflate,sdch
Accept-Language: en-US,en;q=0.8,fa;q=0.6,sv;q=0.4
Cache-Control: no-cache
Connection: keep-alive
Origin: http://editor.swagger.io
Referer: http://editor.swagger.io/
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0
**Token: Test
EventName: Test**
Content-Length: 564
Content-Type: application/json

But when I post it from editor.swagger.io, below are the list of headers received by the server. Notice the custom headers are missing

Origin  http://editor.swagger.io
Accept  text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Access-Control-Request-Method  POST
Access-Control-Request-Headers  content-type,eventname,token
User-Agent  Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0
Connection  keep-alive
Host  27.251.229.77:8080
Accept-Language  en,ta;q=0.5
Accept-Encoding  gzip, deflate

Any suggestion or help is much appreciated.

**Comment by webron** [comment]
That sounds like something from your side is dropping the headers, especially if you see them being sent in the request.

**Comment by adheep** [comment]
I apologize for late reply, I figured out what was going wrong and was able to fix it
I would like to explain the issue in detail and close it

Fix in simple words: Add "CORS" fix to your server

Fix explanation in detail:
To understand the reason why the headers were missing on the original POST request, we need to understand how the browser behaves during a CORS fix.

Issue 1:
Take chrome for example, when you try to make a CORS call from swagger or any site it will first make a HTTP "OPTIONS" call. Only few may be aware of "OPTIONS" HTTP type apart from POST, GET, PUT and DELETE.

This OPTIONS call will be made to the HOST site and it will expect a "200" response with "Access-Control-Allow-Origin" in the header with the full qualified URL of the Client site from which the CORS call was originated.

To fix this you handle it on the REST API by defining a new Method to handle OPTIONS call and always return successful 200 response and make sure the HTTP response contains "Access-Control-Allow-Orgin" header.

Or you can do this fix at much higher level like the Application Server or Load Balancer level. 
My application server JBoss EAP 7 is load balanced by Apache Load Balancer and hence I added the following configuration in the Apache configuration. By doing this I don't have to worry about the response CORS headers and how to handle OPTIONS call in my API. Following are the configuration

    # Always set these headers.
    Header always set Access-Control-Allow-Origin "https://[full-hostname]"
    Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
    Header always set Access-Control-Max-Age "1000"
    Header always set Access-Control-Allow-Headers "x-requested-with, Content-Type, origin, authorization, accept, client-security-token"
     
    # Added a rewrite to respond with a 200 SUCCESS on every OPTIONS request.
    RewriteEngine On
    RewriteCond %{REQUEST_METHOD} OPTIONS
    RewriteRule ^(.*)$ $1 [R=200,L]

**Issue 2:**
The above configuration fixed the CORS issue by handling the OPTIONS call but still the headers was missing out on the actual POST call

So added my two custom headers to the "Access-Control-Allow-Headers"

Header always set Access-Control-Allow-Headers "x-requested-with, Content-Type, origin, authorization, accept, client-security-token, **Token**, **EventName**"

And successfully the Headers started coming in the HTTP Request
