### ISSUE TITLE
Add empty lines in the end of editors

### ISSUE THREAD

**Issue by NikitaKharkov** [swagger-api/swagger-editor#1169]
I'm always annoyed about missing these empty lines. I always have to add empty strings and then I finish I have to delete them. So fix it please for comfortable editing. Thanks!

**Comment by webron** [comment]
Not really sure what you're referring to... can you explain?

**Comment by NikitaKharkov** [comment]
Sure! 
![image](https://cloud.githubusercontent.com/assets/19974632/22641024/c74f924c-ec5d-11e6-887c-59d6ba0df082.png)
In the end of editor I have to add empty lines and after editing delete them to have a norm file. It's a little fix, but it will be more comfortable to work with these lines.

**Comment by webron** [comment]
Thanks, that explains it. At what point would you expect this behavior though? There's no explicit save action in the editor (it auto-saves with every change) so when would those be removed?

**Comment by NikitaKharkov** [comment]
I suggest you either add empty lines in the end (in above example you see numbers of lines, so just remove them (I think 30 line will be enough) and leave the empty space - more acceptable variant) or when I export file remove empty lines in the start and end of file.
Here is the example:
![image](https://cloud.githubusercontent.com/assets/19974632/22689600/5c3eaae6-ed3a-11e6-89a2-d782b0433f2b.png)

It's a little fix I know

**Comment by webron** [comment]
Knowing the audience of the tool, adding empty lines (with or without line numbers) would be confusing to a lot of our users, so I don't see us doing that.

Removing the extra lines on download is something that makes more sense.

**Comment by NikitaKharkov** [comment]
Ok, its a norm variant too. If you open any more less popular editor you will see these empty lines.
But Ok, I just writed about it, its not a bug, so I suggest to close the issue.
