### ISSUE TITLE
Try-out in docs do not work, if 'type: object' is omitted

### ISSUE THREAD

**Issue by djamalouch** [swagger-api/swagger-editor#1170]
**Swagger File**

```yaml
swagger: '2.0'
info:
  version: 1.0.0
  title: API
  description: API description
host: localhost:10010
basePath: /
schemes:
  - http
  - https
produces:
  - application/json
consumes:
  - application/json
paths:
  /customers:
    post:
      description: Customer post description
      parameters:
        - name: data
          in: body
          description: Customer data.
          required: true
          schema:
            type: object
            properties:
              blub:
                # if commented out, the Try-Out function in the documentation does not work as expected
                #type: object
                properties:
                  foo:
                    type: string
                  bar:
                    type: number
      responses:
        '202':
          description: Customer response description
```

* Version: 2.10.3
* Browser/OS: Chrome, Windows 10

**Issue**
If the line `type: object` line is commented out, I can't fill in the fields in the try out section of the documentation. See attached images.
![failure](https://cloud.githubusercontent.com/assets/17527960/22618096/c72e3abe-ead4-11e6-8cf9-9d0982d74eae.png)
![ok](https://cloud.githubusercontent.com/assets/17527960/22618097/c74c98ce-ead4-11e6-8c8f-df03461f0f2e.png)

**Comment by webron** [comment]
While the behavior should be more user-friendly and allow it, you should know that you actually need to specify that the type is object.

Contrary to common belief, the type is not inferred from having `properties` define. If you don't define it's of type object, it means that it can also be a string, integer, boolean, array and so on.

**Comment by djamalouch** [comment]
Thanks for the clarification. I did not stumble across that information anywhere. And searching for the terms "type", "object" and "required" in the specification did not help as well. Google wasn't of help as well.

I think that is a serious flaw from a user perspective of an otherwise great software. I almost switched to another Rest Api specification framework and just gave Swagger a last try. The editor or some lint like software should really show that the type is always required.

**Comment by webron** [comment]
Keep in mind - it's _not_ required. It just means something different than you'd expect. That's just how JSON Schema works, and is beyond our control in Swagger.

We're releasing a new version soon that will warn the user about these things though, hopefully will help in educating the users.

**Comment by djamalouch** [comment]
Alright, I'm looking forward to use the next version. Thanks a lot for the clarification.
