### ISSUE TITLE
Feature request: make it a real desktop app

### ISSUE THREAD

**Issue by samvv** [swagger-api/swagger-editor#1171]
A has already been pointed out in #796, it is relatively easy to embed the editor in node-webkit. In my eyes, this would make it a lot easier to work with than having to manually download and install all dependencies. It might be a minor thing, but I think it would greatly ease the developer experience.

Any thoughts on this? I might be able to provide a pull request which does just that.

**Comment by webron** [comment]
Thanks for the offer, @samvv.

We are approaching the release of a major update in the upcoming weeks - one such that would make the efforts in making this change needlessly pointless. I'd suggest waiting for the new release, re-evaluate the need for it, and if still needed, we'd consider your suggestion (and even accept a PR! :smile:).

**Comment by samvv** [comment]
Ok, thanks 😄 I'll be looking forward to it. I'll close this issue for now.
