### ISSUE TITLE
Multiple errors from Chrome

### ISSUE THREAD

**Issue by grosch** [swagger-api/swagger-editor#1177]
* Version: Whatever is currently at editor.swagger.io
* Browser/OS: Chrome version 55.0.2883.95 (64-bit) / macOS Sierra Version 10.12.3

**Issue**

When I open my YAML in Safari it works without issue.  When I open it in Chrome I am getting all these errors and the "editor" area does not accept any keyboard input.

[editor.swagger.io-1486716027086.txt](https://github.com/swagger-api/swagger-editor/files/766099/editor.swagger.io-1486716027086.txt)

**Comment by adheep** [comment]
Could you please share your Swgger configuration or YAML file?

**Comment by grosch** [comment]
If you can give me an email address I'll send it to you, but I don't want to post it here, no.

**Comment by saharj** [comment]
@grosch Sorry for any inconvenience. Until we fix the issue, please clean your local storage and cache, and try again.

**Comment by grosch** [comment]
@saharj That seems to have resolved the issue, thanks.
