### ISSUE TITLE
Unable to specify array of differing types

### ISSUE THREAD

**Issue by grosch** [swagger-api/swagger-editor#1178]
* Version: editor.swagger.io
* Browser/OS: Chrome on mac 10.12.3

**Issue**

I need a way to be able to specify that an array has distinct types.  Note this is *not* a request for @anyOf or its kin.

My API method returns an array of exactly two elements.  The first element is an integer, and the second element is a string.    That's completely valid JSON, which is the Content-Type returned from the method, but swagger seems to provide no way to document that.

**Comment by webron** [comment]
It's a completely valid JSON, but the spec doesn't support a representation of it. There's nothing we can do about it.
