### ISSUE TITLE
File -> Download doesn't download a file

### ISSUE THREAD

**Issue by grosch** [swagger-api/swagger-editor#1179]
* Version: editor.swagger.io
* Browser/OS: Safari 10.0.3 on mac Sierra 10.12.3

**Issue**

When I choose File -> Download JSON it's not actually doing a file download, it's just opening a new tab with the contents of the JSON.  That's a huge pain as I'm now involved with copy/paste that buffer, then going to my terminal window and pasting that into a new document.  With a very large document, like I'm working with, that's a long iteration each time I make a change.   If it actually downloaded a file that's fast, and then I can just scp that file over to the remote system where the .json file needs to live.

**Comment by webron** [comment]
This is a Safari specific issue, which we need to resolve. It works fine on other browsers.

**Comment by grosch** [comment]
If you fix #1177 then I won't care about this one any longer :)

**Comment by webron** [comment]
Sure. We'll get right on it. Sorry for the inconvenience.

**Comment by grosch** [comment]
@webron Clearing the cache, as someone suggested in #1177 worked, which lets me now download directly since it works well in Chrome.
