### ISSUE TITLE
Swagger editor does not appear to allow array of objects

### ISSUE THREAD

**Issue by choran** [swagger-api/swagger-editor#1180]
**Issue**
I can create an unstructured object to allow users to add a json object to the API.
I do this using 'additionalProperties: true' and it appears to work fine. I get a drop down menu and select object and can edit the json. So that is working fine.
But when I try and create an array of these objects I run into problems. I can select the object from the drop down but cannot see any option to edit the json object. It is always empty. 
Is it possible to have an array of simple, user defined, json objects in swagger?

**Swagger File**

```yaml
 definitions:
  user:
    type: object
    properties:
      user_id:
        type: string
      email:
        type: string
      name:
        type: string
      test_object: 
          additionalProperties: true
      array_of_objects:
        type: array
        items: 
          $ref: '#/definitions/item'
  item:
      additionalProperties: 
```

* Version: v2.10.4
* Browser/OS: chrome and firefox

**Comment by webron** [comment]
That small line contains quite a few errors, with regard to JSON Schema and the Swagger spec.
The proper way to represent what you want would be:
```yaml
item:
  type: object
```

I cannot guarantee the editor supports this type of input though, but it's worth a shot.

**Comment by choran** [comment]
Thanks for the response. No, your right, for some reason it does not seem to support that type of input. I assumed it would work via
```
  item:
    type: object
```
but this give me no option to edit the object so its always an empty object. I tried different combinations, even for the basic object, of the above format and it didnt work. I found it strange since it is a fairly basic structure to support.
Do you know why the editor would not be able to support the way you described? Is it a version issue? Does this mean that swagger does not support sending a user defined json object as part of the request body? (i.e. one where the key and value are defined by the user)
thanks again

**Comment by choran** [comment]
Below is a picture of the issue. I can select any type other than object in the array and it works, sting, int ... they are all fine. But when I select object I dont see any "Edit JSON" button or "Object Properties" button. So it looks like an empty object in the array. It works fine for the object above where you can see the two buttons. But not when it is part of an array. I am new to swagger so it may be simple mistake on my side but I have tried lots of other options and still get the same issue

<img width="548" alt="array_object_example" src="https://cloud.githubusercontent.com/assets/15954251/22853633/c5a2c924-f053-11e6-938f-e8826a124d71.png">

**Comment by bpedro** [comment]
Hi @choran 

There seems to be a bug with the Swagger Editor related to nested objects with `additionalProperties`. The following definition should render a way to define the `additionalProperties` but instead renders the same UI as the one you describe:

```
swagger: '2.0'
info:
  version: 1.0.0
  title: Test client defined input
  description: Array of client defined objects
host: 'localhost'
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    post:
      description: Test
      parameters:
        - name: item
          in: body
          required: true
          schema:
            $ref: '#/definitions/UserModel'
      responses:
        '200':
          description: response
definitions:
  UserModel:
    type: object
    properties:
      user_id:
        type: string
      email:
        type: string
      name:
        type: string
      client_defined:
        $ref: '#/definitions/ClientDefinedObjectModel'
  ClientDefinedObjectModel:
    type: array
    items:
      type: object
      additionalProperties: true
```

If we use a single object, i.e. not inside an array, it works fine. Here's the YAML for a single object (no array).

```
swagger: '2.0'
info:
  version: 1.0.0
  title: Test client defined input
  description: Array of client defined objects
host: 'localhost'
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    post:
      description: Test
      parameters:
        - name: item
          in: body
          required: true
          schema:
            $ref: '#/definitions/UserModel'
      responses:
        '200':
          description: response
definitions:
  UserModel:
    type: object
    properties:
      user_id:
        type: string
      email:
        type: string
      name:
        type: string
      client_defined:
        $ref: '#/definitions/ClientDefinedObjectModel'
  ClientDefinedObjectModel:
    type: object
    additionalProperties: true
```

And here's the screenshot where you can define as many properties as you want:

<img width="551" alt="screenshot 2017-02-12 17 49 58" src="https://cloud.githubusercontent.com/assets/56472/22864116/b4c627c4-f14b-11e6-92f8-611d2c4db2d5.png">

I believe this only seems to be affecting the Swagger editor, not the swagger parser itself.

**Comment by choran** [comment]
Hi @bpedro 
Thanks for the response. Yeah, it is strange even editing the JSON from the above example to add an array directly causes the same issue. I just used additionalProperties as the only way I could see of creating an unstructured object. Is there another way to create an unstructured object that might allow the creation of an array of those objects? I wasn't sure if there was? For the body I am trying to re-create it has to have an array of objects for one of the parameters. So I was trying to see if there was any other way of achieving this or, like you said, this is a bug preventing the creation of any array of object?
Thanks again for the response.

**Comment by webron** [comment]
@choran to be honest, the editor wasn't really intended as a documentation tool but more for quick testing. Since sending arbitrary objects is not so common, we didn't tackle all edge cases (though we should have). It should work fine in swagger-ui.

That said, we're working on a major update at the moment, so I don't foresee this being fixed in the current version. I'm hoping it'll work out-of-the-box with the next update, but if not, it'll be easier for us to handle.

**Comment by grosch** [comment]
@webron Really?  I assumed the editor WAS meant to be the documentation tool.  What should I be using instead?  I use the editor to get it looking right and then save the produced JSON to somewhere that swagger-ui reads.

**Comment by fehguy** [comment]
The editor is an editor. The UI is a UI and is used for viewing and documenting.  it has confused some people but we have separated the concerns intentionally.

**Comment by bpedro** [comment]
Hi @choran 

I think your approach is the correct one (using `additionalProperties`). The fact that the Swagger Editor doesn't support doesn't mean that it's not working.

Can you shed some light here @fehguy ?

Thanks!

**Comment by webron** [comment]
The approach is right, but the spec actually doesn't support `additionalProperties: true`. You can use `additionalProperties: {}` as an equivalent alternative.

**Comment by bpedro** [comment]
@webron Not according to the JSON Schema spec (see http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.18).

According to it, and I quote, "The value of "additionalProperties" MUST be a boolean or a schema."

Does the Swagger spec follow something different?

**Comment by webron** [comment]
Yes, when I said 'the spec actually doesn't support...' I meant the Swagger spec.

**Comment by webron** [comment]
This is no longer an issue with the new editor.
