### ISSUE TITLE
Date formatter behaving weird

### ISSUE THREAD

**Issue by adheep** [swagger-api/swagger-editor#1181]
**Swagger File**

```yaml
swagger: '2.0'
info:
  version: '1.0.0'
  title: Travel Insurance - Rating API
  description: Get rates for the Starr Assist Travel plans
  contact:
    name: Adheep M
    email: adheep_m@solartis.net
basePath: /service
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /testMe:
    post:
      description: Sample Input
      operationId: Sample
      produces:
        - application/json
      parameters:
        - name: Sample
          in: body
          description: Rating content
          required: true
          schema:
            $ref: '#/definitions/Sample_Request'
      responses:
        '200':
          description: Success Response
          schema:
            $ref: '#/definitions/Sample_Response'
definitions:
  Sample_Request:
    type: object
    properties:
      InputDate:
        type: string
        format: date
  Sample_Response:
    type: object
```
* Version: 2.0
* Browser/OS: Chrome/Firefox in Windows 10 

**Issue 1**
In Chrome when defining a property's format as date, the browser automatically show datepicker. Try typing the date 03/03/2017 or any other date.

![screenshot 356](https://cloud.githubusercontent.com/assets/1218707/22874886/8d5c2ee2-f1ee-11e6-9249-7cd72d708a23.png)

I was not able to type in the desired date anyway, but a quick workaround is you can use the datepicker and you will have to get used to selecting date from datepicker (which is not the most user friendly datepicker out there)

**Issue 2**
The date picker is not visible in Firefox browser, not sure if this a known issue.
![screenshot 355](https://cloud.githubusercontent.com/assets/1218707/22874917/b2ea4446-f1ee-11e6-95f5-1ce5eb2a5d09.png)

**Issue 3**
Not sure if this is a bug or I am missing something here.
In Chrome browser when I select a date from the default datepicker, the date format is "mm/dd/YYYY" eg, 03/15/2017

But when the JSON is constructed the format is rendered as "YYYY-mm-dd" eg. 2017-03-15

![screenshot 353](https://cloud.githubusercontent.com/assets/1218707/22874991/1cf227be-f1ef-11e6-8533-d3699cc6fb1a.png)

Any help or suggestion is much appreciated, thanks in advance.

**Comment by webron** [comment]
This is no longer an issue with the new editor.
