### ISSUE TITLE
When $ref used with a url; it shows undefined in swagger-editor.

### ISSUE THREAD

**Issue by sanjay-ng** [swagger-api/swagger-editor#1183]
Hi, When I refer a json schema on swagger-editor which is in another json file. it shows undefined (attached image below marked red), Can you please help resolve this issue?
Thank you in advance.

**Example, please paste it on the swagger-editor below code: (removed spaces for compact view**)

{	"swagger": "2.0", "info": { "version": "1.0.0", "title": "Sites" }, "path": {}, "definitions": { "A1": { "title": "A1", "type": "object", "description": "", "properties": { "a2": { "type": "array", "items": { "title": "A2", "type": "object", "description": "", "properties": { "$ref": "http://localhost/swagger-editor/Json/id.json#/definitions/ids" } }, "x-tag": 11, "description": "some comments" }	} }	} }

**Save the below json in file named "id.json" under folder named "json" (removed spaces for compact view)**

{ "swagger": "2.0", "info": { "version": "1.0.0", "title": "id" }, "paths": { }, "definitions": { "ids": { "type": "object", "properties": { "items": { "title": "IDS", "type": "object", "description": "", "properties": { "id": { "type": "string", "x-tag": 11, "description": "Specifies a mandatory id" }, "name": { "type": "string", "x-tag": 12, "description": "Specifies the name" }, "description": { "type": "string", "x-tag": 13, "description": "Specifies some description" }, "config": { "type": "array", "items": { "$ref": "http://localhost/swagger-editor/Json/id.json#/definitions/properties/Config" }, "x-tag": 11, "description": "Specifies list of configured items in the System." } } } } }, "Config": { "title": "SomeConfig", "type": "object", "description": "", "properties": { "identifiers": { "type": "object", "properties": { "$ref": "http://localhost/swagger-editor/Json/id.json#/definitions/properties/Identifiers" }, "x-tag": 11, "description": "Specifies identifier" }, "algorithmName": { "type": "string", "x-tag": 13, "description": "Specifies algorithm names" }, "State": { "type": "boolean", "x-tag": 14, "description": "if set to true , indicates that is enabled" } } }, "Identifiers": { "title": "SomeIdentifiers", "type": "object", "description": "This will be used to identify", "properties": { "id": { "type": "string", "x-tag": 11, "description": "Specifies a mandatory identifier to uniquely represent" }, "name": { "type": "string", "x-tag": 12, "description": "Specifies the name" }, "description": { "type": "string", "x-tag": 13, "description": "Specifies some description" }, "state": { "type": "object", "properties": { "$ref": "http://localhost/swagger-editor/Json/id.json#/definitions/properties/AState" }, "x-tag": 31, "description": "Specifies the status" } } }, "AState": { "title": "AnalyticState", "type": "object", "description": "Specifies the states of Analytics", "properties": { "id": { "type": "string", "x-tag": 11, "description": "Specifies a mandatory identifier" } } } }

You'll notice that for a2(A2) it shows **"undefined"** on right pane of swagger-editior. The json has nested $ref's which also it must resolve. but it doesn't.

* chrome/Windows7: 

**Issue**
![image](https://cloud.githubusercontent.com/assets/25607348/22918095/8af85886-f2ae-11e6-9d9b-85c2ffc214d2.png)

**Comment by webron** [comment]
Are you hosting the second file somehow?

**Comment by sanjay-ng** [comment]
On same server where swagger is hosted

**Comment by webron** [comment]
If you open http://localhost/swagger-editor/Json/id.json in your browser you see the file?

**Comment by sanjay-ng** [comment]
Yes, I can see the whole json

**Comment by sanjay-ng** [comment]
And, suppose a json has nested $ref's then it cannot resolve the nested ones.

**Comment by sanjay-ng** [comment]
![image](https://cloud.githubusercontent.com/assets/25607348/23131754/3a8d2a22-f7b1-11e6-8251-5922a20e5a99.png)

![image](https://cloud.githubusercontent.com/assets/25607348/23131510/3ffd5848-f7b0-11e6-9a7e-38b4d7a13754.png)

If you see above identifier & relation has $ref again (nested) which is not able to resolve in swagger-editor. The second image is for identifer which is  looking for object, enum or array but here it's $ref....

**Comment by webron** [comment]
This is no longer an issue with the new editor.
