### ISSUE TITLE
Not a Valid Parameter Definition - Many Errors, yaml attached

### ISSUE THREAD

**Issue by windswept321** [swagger-api/swagger-editor#1185]
My yaml file gives a lot of errors in the online editor for reasons I can't seem to figure out.
Attached is a simplified version.
[swaggeryaml.yaml.zip](https://github.com/swagger-api/swagger-editor/files/779127/swaggeryaml.yaml.zip)

**Comment by webron** [comment]
I'm guessing you intended your `page_no` and `result_per_page` to be query parameters (so you need to change the `in` value).

If they are path, then they have to be required, and you need to put them in the path as well.

**Comment by windswept321** [comment]
That was the problem! 
Thanks very much.
