### ISSUE TITLE
Operation PUT or PATCH send empty objects and arrays instead of 'nothing'

### ISSUE THREAD

**Issue by ClementVidal** [swagger-api/swagger-editor#1187]
**Swagger File**

```yaml
swagger: "2.0"
info:
  version: "0.0.1"
  title: test
host: localhost:10010
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

paths:
  /test:
    x-swagger-router-controller: user
    patch:
      description: Test
      operationId: test
      parameters:
        - name: testParam
          in: body
          description: The new user
          required: false
          schema:
            $ref: "#/definitions/Test"      
      responses:
        "201":
          description: Created
        "403":
          description: Forbidden
    
definitions:
  Test:
    type: object
    properties:
      attr:
        type: string
        description: ""
      attrArray:
        type: array
        description: ""
        items:
          type: string
      attrObj:
        type: object
        description: ""          
        properties:
          attr:
            type: string
```

* Version: 2.10.4
* Browser/OS: Chrome/Ubuntu

**Issue**

When using this swagger spec within the swagger editor, if a leave every fields empty on the testParam parameter, when clicking on *Send request*, the PATCH request contain this JSON object:
 ```
{
  "attrArray": [],
  "attrObj": {}
}
 ```
Instead of *nothing* (null/undefined)

This lead to two problems:
* This makes impossible to merge incoming data with existing one ( using Object.assign() )
* This do not allow to make difference between empty object/array and object/array that are NOT provided in the incoming PATCH request.

Things are much more flexible in swagger-ui (http://petstore.swagger.io/) has we can directly input json objects by hand, there is no GUI input like in swagger-editor.

I think it could be great to have a config option to disable the GUI input style and replace it by a simple textarea.

What's your opinions about that ?
I'm i missing something ?

**Comment by webron** [comment]
This will change soon.

**Comment by ClementVidal** [comment]
Do you have any plan or roadmap ?
I already fork the project to investigate that.
Is it worth the price?

**Comment by webron** [comment]
I don't know :)

We're going to have a new version within a few weeks pushed out, but it's going to be in a beta status as it's a major (major) update.

**Comment by ClementVidal** [comment]
Damn, that sound interseting, can i be part of the beta ?

**Comment by webron** [comment]
It's going to be a public beta.

**Comment by webron** [comment]
This is no longer an issue with the new editor.
