### ISSUE TITLE
Swagger Editor Code Examine not work

### ISSUE THREAD

**Issue by a240277805** [swagger-api/swagger-editor#1189]
**Swagger File**

```yaml
 # paste your swagger document here
```

* Version: 
   swagger: '2.0'
* Browser/OS: 
    chrome
**Issue**
    the  code is  running good  but today i manage it there is no Smart tips.and i try to open an example code without smart tips either . I dont konw  why, please  help .

**Comment by a240277805** [comment]
I open an example in Swagger editor but there is no  smart tips either.

**Comment by webron** [comment]
Not sure what this means.
