### ISSUE TITLE
wrong path for default.json

### ISSUE THREAD

**Issue by HansHammel** [swagger-api/swagger-editor#1192]
Swagger release 2.10.5 on windows

for me default.json is loaded as https://localhost:3443/vendors/swagger-editor/index.html/config/defaults.json which is obviously wrong.

fixed it by editing bundle.js applied this change:
a=window.location.pathname;
=>
a=window.location.pathname.substring(0, window.location.pathname.lastIndexOf("/") + 1);

**Comment by webron** [comment]
This is no longer an issue with the new editor.
