### ISSUE TITLE
https issues with default.json and defaults.json.guide.js

### ISSUE THREAD

**Issue by HansHammel** [swagger-api/swagger-editor#1193]
swagger-editor release 2.10.5, windows 10, chrome

when served via https the references in  default.json and defaults.json.guide.js cause a mixed content error.

please fix this by removing the protocol like:
"servers": "http://generator.swagger.io/api/gen/servers",
=>
"servers": "//generator.swagger.io/api/gen/servers",
etc.

**Comment by fehguy** [comment]
I think you're talking about the online generator and self-hosted editor.  You can host yourself if you need it in different scheme.

**Comment by HansHammel** [comment]
Just fix the bug. https://github.com/swagger-api/swagger-editor/blob/master/config/defaults.json
