### ISSUE TITLE
Import URL

### ISSUE THREAD

**Issue by confuser** [swagger-api/swagger-editor#1195]
It used to be possible to import a swagger doc directly from the URL. This seems to have broken over the past couple of days.

http://editor.swagger.io/#/?import=https://urlToSwaggerFile

Instead of loading the file from the URL, it displays either the default (Uber), or the last document that was edited (pulled from localStorage).

File -> Import URL seems unaffected, and still works as expected.

**Comment by webron** [comment]
@saharj - can you take a look?

**Comment by yvele** [comment]
Same problem for me, this isn't working anymore

```
http://editor.swagger.io/#/?import=https://foo.bar.com/foo
```

My document is CORS compatible and is in JSON format

Using Chrome on Mac OSX

**Comment by confuser** [comment]
Any movement on this @saharj @webron ?

**Comment by saharj** [comment]
This issue should be fixed now.

**Comment by ivanfmartinez** [comment]
Does not work with current online editor neither with 3.0.10 hosted in the same hostname from the import url.

**Comment by webron** [comment]
@ivanfmartinez seems working for me. If it still doesn't work for you, please file a new ticket and provide more details such as your browser.
