### ISSUE TITLE
2.10.5 release is still 2.10.3

### ISSUE THREAD

**Issue by meeech** [swagger-api/swagger-editor#1198]
Download from https://github.com/swagger-api/swagger-editor/releases - Latest Release button or swagger-editor.zip seems to give 2.10.3 version (when running, i check Help > About) and it identifies as 2.10.3

Can also see the file names in the dist folder are the same between 2.10.3 and 2.10.5 release. 2.10.4 seems fine.

**Comment by webron** [comment]
@saharj - can you look in to that?

**Comment by saharj** [comment]
Sorry for the mistake. It should be fixed now
