### ISSUE TITLE
Editor does not respond to keypresses

### ISSUE THREAD

**Issue by cniles** [swagger-api/swagger-editor#1201]
**Swagger File**

```yaml
 # Any
```

* Version: 2.10.4
* Browser/OS: Google Chrome	56.0.2924.87 (Official Build) (64-bit), iOS Darwin

After starting the editor (either from the swagger online editor or a local node server), I am unable to enter text into the editor panel.  The editor does not appear to be accepting keyboard input.  Restarting chrome and the editor server do not resolve this issue; ~~no workaround available.~~

Clear cache resolves this issue

**Comment by webron** [comment]
Try clearing your cache. It _will_ remove existing work you have.

**Comment by cniles** [comment]
Thanks, that fixes it.

**Comment by webron** [comment]
Awesome, thanks for the update.
