### ISSUE TITLE
response content within Raw tab incorrect at the first line

### ISSUE THREAD

**Issue by towertop** [swagger-api/swagger-editor#1205]
* Version: 2.10.5
* Browser/OS:  Chrome/Windows 8

**Issue**
Within "Try this Operation" section, the response content displayed in "Raw" tab is always mixed with some code. It looks as:

![image](https://cloud.githubusercontent.com/assets/1001699/23695738/9d6b2a24-041b-11e7-84fa-cd711c61c0d9.png)

The first line of HTTP response is:
```
HTTP/1.1 function (t){var e;if(t)if(c)y.always(t[y.status]);else for(e in t)C[e]=[C[e],t[e]];return this} 
```
 
And this piece code can be found in the javascrip file bundle.js . I didn't see the same problem in 2.10.4 just before I upgrading editor from npm locally.

**Comment by webron** [comment]
This is no longer an issue with the new editor.
