### ISSUE TITLE
Saving a YAML file from swagger editor in Chrome 

### ISSUE THREAD

**Issue by abstractnew** [swagger-api/swagger-editor#1206]
**Swagger File**

```yaml
 # paste your swagger document here
```

* Version: 56.0.2924.87
* Browser/OS: Chrome 

**Issue**
Using the online swagger editor there seems to be an issue saving the yaml file. 
Scenario:
- Load swagger editor http://editor.swagger.io/#!/
- It shows a default YAML (say for e.g the uber API)
- Delete the example and type in your own YAML
- When clicking on File->Download YAML it saves the original example that was loaded and not the changes

**Comment by isamauny** [comment]
Same happens with Download as JSON. Even if you say New File and replace the contents by your own, Download as JSON downloads the Uber API description.

**Comment by webron** [comment]
This is no longer an issue with the new editor.

**Comment by Pilarbrist** [comment]
When I need save it only allow save in Yaml? where is this file on my mac
