### ISSUE TITLE
Duplicated mapping key - The same endpoint but different method

### ISSUE THREAD

**Issue by Caltalys** [swagger-api/swagger-editor#1207]
**Swagger File**

```yaml
 # paste your swagger document here
```

* Version: 2.10.5
* Browser/OS: Chrome 56.0.2924.87

**Issue**
"Duplicated mapping key.." when having some endpoint with the same name but different method, Example:
GET /me
POST /me

I thinks this is very regularly in RESTful API design

**Comment by webron** [comment]
It is. You just need to define the GET and POST under the same `/me`.

**Comment by Caltalys** [comment]
I understood, thanks you very much.
