### ISSUE TITLE
Local editor POSTs to generator.swagger.io

### ISSUE THREAD

**Issue by bardware** [swagger-api/swagger-editor#1208]
I downloaded the `swagger-editor` release and set up my local apache to serve it. It came as a surprise: when I click "Generate Client" => html2 my data is posted to your server `generator.swagger.io` that eventually served the pretty html file in a zip. 
Is it possible for me to set up my own server doing this conversion?
I know of `swagger-codegen-cli`. I can call a JAVA.jar-file and have my client generated. I wonder if it's possible purely locally from within the editor.

**Comment by fehguy** [comment]
Yes, you can configure the editor and run your own generator.  Take a look at the configuration for the editor.
