### ISSUE TITLE
Missing required property definition while using allOf with requried and properties

### ISSUE THREAD

**Issue by nemenemsrouge** [swagger-api/swagger-editor#1212]
**Swagger File**

```yaml
---
  swagger: "2.0"
  info: 
    version: "1.0.0"
    title: "test API"
    description: "Handle all internals requests to back-office."

  host: "test.api.com"
  basePath: "/v2"
  schemes: 
    - "https"
  consumes: 
    - "application/json"
  produces: 
    - "application/json"

  paths:
    /foo:
      post: 
        summary: "Create a foo"
        parameters:
          - 
            name: "bar"
            in: "body"
            required: true
            schema: 
              allOf: 
                - 
                  required: 
                    - "req1"
                    - "req2"
                    - "req3"
                    - "req4"
                - 
                  properties: 
                    req1:
                      type: "string"
                      format: "uuid"
                - 
                  $ref: "#/definitions/Foo"

        responses: 
          201: 
            description: "The created foo"

  definitions:
    Foo:
      type: "object"
      properties: 
        req2:
          type: "string"

        req3:
          type: "string"

        req4:
          type: "string"

        opt1:
          type: "string"

        opt2:
          type: "string"
```

* Version: 51.0.1 (32 bits)
* Browser/OS: Firefox

**Issue**

Using this YAML file throw these errors

![swag](https://cloud.githubusercontent.com/assets/6534850/23798468/16339b32-05a5-11e7-9346-454f2a9f8d20.png)

Other validating tools are ok...

![term](https://cloud.githubusercontent.com/assets/6534850/23798492/340f7504-05a5-11e7-9e3a-b18ce93f0052.png)

**Comment by gbangban** [comment]
Running into the same issue here.

**Comment by fehguy** [comment]
Looks great on the 3.x editor version:

https://editor.swagger.io/

![image](https://cloud.githubusercontent.com/assets/249413/25200934/096ee03a-2505-11e7-9b8b-c91fa7fe65e6.png)

**Comment by gbangban** [comment]
The 3.0 editor is great, but there's still widespread use of the 2.0 editor and UI. 

I ended up pulling the properties out of the array. I.e.

              - properties: 
                  req1:
                    type: "string"
                    format: "uuid"

to 
                properties: 
                  req1:
                    type: "string"
                    format: "uuid"


That will fix the parsing for the req1 property, but it will not fix the rest of the properties of the parent model.  I'm not sure if the spec supports that level of composition, but you can pull those requirements down to the implementing model for a working spec.

Grazie for the quick response.

**Comment by fehguy** [comment]
Hi, as we have limited resources, our efforts are focused on the new version, which will allow us to support the next specification. If someone can create a PR for the 2.x series, with tests, we can certainly get it in.

**Comment by gbangban** [comment]
Good on my end.  

I appreciate all the work you folks are doing!

**Comment by nemenemsrouge** [comment]
This issue makes me wonder, what is the validation library used in swagger editor?

I test some complex swagger files with
- swagger-client
- swagger-tools 
- swagger editor

and these 3 tools don't spot the same validation errors...

**Comment by webron** [comment]
@nemenemsrouge the editor uses its own validation mechanism. It's a combination of JSON Schema validation and manual validations.

**Comment by nemenemsrouge** [comment]
Thx @webron. Good point to know...

It would be nice to have a exhaustive validation library (for CI or things like like this)
Existent libraries are all behaving differently...

Maybe sharing the validation system as a small standalone project could be a good idea?

**Comment by webron** [comment]
At the moment we have no plans on extracting the validation as a standalone library.
