### ISSUE TITLE
Circular Dependencies in Swagger cause editor to hang.

### ISSUE THREAD

**Issue by dimitertodorov** [swagger-api/swagger-editor#1213]
Please see my swagger Here:
https://gist.github.com/dimitertodorov/c4b5e4e7020c97f8ab34e2460403688e

* Version:  master
* Browser/OS: chrome/osx

**Issue**
Circular dependencies seem to be freezing swagger-editor.
The JSON passes validation against 2.0 schema.
This problem also occurs with swagger-ui.

If I remove the circular dependencies, it loads fine.

**Comment by webron** [comment]
This is no longer an issue with the new editor.

**Comment by hugobarona** [comment]
Hi there, this is still an issue for me, using this spec: [https://github.com/hugobarona/OpenApiSpecification/blob/master/circular_reference_swagger2_spec.yaml](url). Could you please have a look? I am trying to finalize the spec and i am not able to use the editor to validate it. thanks
