### ISSUE TITLE
too many Deprecated package

### ISSUE THREAD

**Issue by ericdai** [swagger-api/swagger-editor#1215]
suggest update the npm install package

**Comment by ericdai** [comment]
npm WARN deprecated css-list@0.1.3: Deprecated.
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm

**Comment by ericdai** [comment]
ERROR in ./scripts/directives/collapsewhen.js

C:\working\swagger-editor\scripts\directives\collapsewhen.js
   1:14  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   2:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   3:53  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   4:39  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   5:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   6:11  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   7:19  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   8:53  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   9:25  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  10:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  11:33  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  12:50  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  13:49  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  14:32  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  15:39  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  16:33  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  17:9   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  18:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  19:37  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  20:32  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  21:37  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  22:35  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  23:32  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  24:33  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  25:24  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  26:8   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  27:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  28:55  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  29:19  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  30:37  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  31:34  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  32:29  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  33:45  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  34:21  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  35:17  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  36:34  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  37:48  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  38:21  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  39:10  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  40:10  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  41:6   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  42:5   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  43:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

✖ 43 problems (43 errors, 0 warnings)

I have windows 10 OS and node 7.6 installed

**Comment by webron** [comment]
Should no longer be relevant in 3.X.
