### ISSUE TITLE
Date & datetime with specified format

### ISSUE THREAD

**Issue by gwynjudd** [swagger-api/swagger-editor#1225]
My web API has date and datetime values with a specified format like this "1975-12-10 12:11:20". The datetime values are formatted as local time without timezone information. I'm not really sure how to put this into the swagger. This is what I have so far, but I'm not sure it's right. In any case, the swagger editor doesn't show my expected format for the values:

    stdRecordStamp_PutData:
      description: stdRecordStamp_PutData
      properties:
        WhenAdd:
          format: date-time
          description: WhenAdd
          pattern: '\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}'
          type: string

![image](https://cloud.githubusercontent.com/assets/314188/24179816/6da91cc8-0f16-11e7-83cf-fc480d5ed3d0.png)

**Comment by webron** [comment]
Combining `format` and `pattern` can be contradicting itself. `date-time` has a very specific structure and it's not what you want. Drop the `format`, keep the `pattern`, and you're good to go.

**Comment by gwynjudd** [comment]
thanks

**Comment by rycler** [comment]
why was this closed? Specifying a pattern seems really useful.

**Comment by webron** [comment]
@rycler date-time has a specific format, you can't change it. If you need to have a specific format, use `pattern` to specify it instead.

**Comment by rycler** [comment]
@webron We use swagger to build serverside controller and model. date-time is becomes jodatime in java. Everythingis mapped correctly, however too many dates are accepted as valid. 

example:
input "2016-10-31T01:30" (no seconds, should fail)
output "2016-10-31T01:30:00.000Z" (seconds appended)

If I could use date-time and also a regex pattern, this wouldn't be an issue...

**Comment by webron** [comment]
@rycler I'm guessing when you say you use swagger to build the serverside controller, you're referring to swagger-codegen. If that's the case, then the bug is in the codegen as it should interpret `date-time` as being able to accept noly the `output` sample you provided. If that's not the case, then the bug should be opened on the codegen where that restriction should be added.

**Comment by wolfvik** [comment]
I am using swashbuckle with my api written in C#. For properties with datetime type, it generates the following json:
```
        "uploadingTime": {
          "format": "date-time",
          "description": "Gets or sets uploading time",
          "type": "string"
        }
```
Is there an way to set the date-time format for all properties with "format":"date-time", maybe in swagger ui?

**Comment by falt86** [comment]
Adding comment here for future googlers: In Swashbuckler, just add this line to .EnableSwagger(c => );

   c.MapType<DateTime>(() => new Swashbuckle.Swagger.Schema { type = "string", pattern = DateTimeFormatter.DateTimeFormat });

**Comment by EmirMa** [comment]
Hi Brother,
.NET Core 3.0 using Swashbuckle.AspNetCore;
Add "c.MapType(() => new Swashbuckle.Swagger.Schema { type = "string", pattern = DateTimeFormatter.DateTimeFormat });"  in Startup.cs, it's error.
Setting Demo:
 public void ConfigureServices(IServiceCollection services)
{
  services.AddSwaggerGen(c =>
    { 
        c.SwaggerDoc("v1", new OpenApiInfo { Title = "Hua", Version = "v1" });
       c.MapType(() => new Swashbuckle.Swagger.Schema { type = "string", pattern = DateTimeFormatter.DateTimeFormat });
    }
}

Error Message:
Error Code	CS0411	Cannot read the usage from deduce method "SwaggerGenOptionsExtensions. MapType < T > (SwaggerGenOptions, Func < OpenApiSchema >)" the type of the parameter.Try to specify type parameters explicitly.

**Comment by bonyjose** [comment]
services.AddSwaggerGen(options => {
                options.AddSecurityDefinition("oauth2", new OpenApiSecurityScheme
                {
                    Description = "Standard Authorization header using the Bearer scheme (\"bearer {token}\")",
                    In = ParameterLocation.Header,
                    Name = "Authorization",
                    Type = SecuritySchemeType.ApiKey
                });
                options.OperationFilter<SecurityRequirementsOperationFilter>();
                options.MapType<DateTime>(() => new OpenApiSchema { Type = "string", Format = "date" });
                
            });

Something like this worked for me, in .net 6 asp core api.
