### ISSUE TITLE
Why the preview result on the right does not show the default value of parameters?

### ISSUE THREAD

**Issue by chace0120** [swagger-api/swagger-editor#1226]
In my api, i want to set the default value for some parameters, but i can't find the default value in the preview result on the right side of swagger-editor.

Why the swagger-editor's preview can not show default value but swagger-ui can do this?

**Comment by webron** [comment]
Which version of the editor are you using?

**Comment by chace0120** [comment]
I upgraded the editor's version to 3.0.0 yesterday, but the preview result was still without default value of the parameter.

**Comment by chace0120** [comment]
Sorry for my carelessness, i think that is the reason about explorer's cache. I cleared the cache and found that the editor's UI changed.

**Comment by webron** [comment]
A bit confused - after clearing the cache, do you still see the issue?

**Comment by chace0120** [comment]
No, i mean that i can see the new UI, and i click the button - "Try it out", then the default value is here.

![image](https://cloud.githubusercontent.com/assets/7875492/24229930/3827e466-0fb7-11e7-9546-1c1417bb5bf7.png)
![image](https://cloud.githubusercontent.com/assets/7875492/24229935/4db11c80-0fb7-11e7-958f-34a269aee28b.png)

Actually i think this is not very convenient for me. I want to see the default value to be shown here like this:

![image](https://cloud.githubusercontent.com/assets/7875492/24230022/d9ab0bc4-0fb7-11e7-93d4-c59e895ff043.png)

**Comment by webron** [comment]
Yes, we're aware of the issue. We're working on improving the layout of the parameters and the information that's being displayed.

**Comment by chace0120** [comment]
Anyway thank u very much for your replies.

**Comment by webron** [comment]
Closing in favor of https://github.com/swagger-api/swagger-ui/issues/2773.
