### ISSUE TITLE
Unable to embed the swagger editor to a div element

### ISSUE THREAD

**Issue by hemikak** [swagger-api/swagger-editor#1231]
Hi All,

swagger-editor version : 3.0.1

I am trying to embed to the swagger editor to a div element. I have added the swagger editor as a dependency to my package.json and ran `npm install`.

I am using AMD and trying to import the editor to js file as follows :
`define('swagger-editor'],
   function(SwaggerEditor) { ... } 
`

When I am trying to start up using webpack, I get this error. Any idea ?

`WARNING in ./\~/yaml-js/lib/yaml.js
require.extensions is not supported by webpack. Use a loader instead.
 @ ./\~/swagger-ui/dist/swagger-ui.js 1:405-423 3:27086-27104
 @ ./\~/swagger-editor/dist/swagger-editor.js
 @ ./js/ballerina/views/swagger-view.js
 @ ./js/ballerina/views/ballerina-file-editor.js
 @ ./js/ballerina/views/module.js
 @ ./js/ballerina/module.js
 @ ./js/tab/file-tab.js
 @ ./js/tab/file-tab-list.js
 @ ./js/main.js
 @ ./index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./index.js

WARNING in ./\~/yaml-js/lib/yaml.js
require.extensions is not supported by webpack. Use a loader instead.
 @ ./\~/swagger-ui/dist/swagger-ui.js 1:405-423 3:27086-27104
 @ ./\~/swagger-editor/dist/swagger-editor.js
 @ ./js/ballerina/views/swagger-view.js
 @ ./js/ballerina/views/ballerina-file-editor.js
 @ ./js/ballerina/views/module.js
 @ ./js/ballerina/module.js
 @ ./js/tab/file-tab.js
 @ ./js/tab/file-tab-list.js
 @ ./js/main.js
 @ ./index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./index.js

WARNING in ./\~/yaml-js/lib/yaml.js
require.extensions is not supported by webpack. Use a loader instead.
 @ ./\~/swagger-ui/dist/swagger-ui.js 1:405-423 3:27086-27104
 @ ./\~/swagger-editor/dist/swagger-editor.js
 @ ./js/ballerina/views/swagger-view.js
 @ ./js/ballerina/views/ballerina-file-editor.js
 @ ./js/ballerina/views/module.js
 @ ./js/ballerina/module.js
 @ ./js/tab/file-tab.js
 @ ./js/tab/file-tab-list.js
 @ ./js/main.js
 @ ./index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./index.js

WARNING in ./\~/ace-builds/src-noconflict/ace.js
84:36-43 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./\~/yaml-js/lib/yaml.js
256:40-47 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

ERROR in ./\~/swagger-editor/dist/swagger-editor.js
Module not found: Error: Can't resolve 'deepmerge' in '/Users/hemikakodikara/ballerina/dev/08/composer/modules/web/node_modules/swagger-editor/dist'
 @ ./\~/swagger-editor/dist/swagger-editor.js 1:99-119 1:2195-2215
 @ ./js/ballerina/views/swagger-view.js
 @ ./js/ballerina/views/ballerina-file-editor.js
 @ ./js/ballerina/views/module.js
 @ ./js/ballerina/module.js
 @ ./js/tab/file-tab.js
 @ ./js/tab/file-tab-list.js
 @ ./js/main.js
 @ ./index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./index.js

ERROR in ./\~/swagger-editor/dist/swagger-editor.js
Module not found: Error: Can't resolve 'react-ace' in '/Users/hemikakodikara/ballerina/dev/08/composer/modules/web/node_modules/swagger-editor/dist'
 @ ./\~/swagger-editor/dist/swagger-editor.js 1:142-162 1:10776-10796
 @ ./js/ballerina/views/swagger-view.js
 @ ./js/ballerina/views/ballerina-file-editor.js
 @ ./js/ballerina/views/module.js
 @ ./js/ballerina/module.js
 @ ./js/tab/file-tab.js
 @ ./js/tab/file-tab-list.js
 @ ./js/main.js
 @ ./index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./index.js

ERROR in ./\~/react-dom/lib/ReactDOMNullInputValuePropHook.js
Module not found: Error: Can't resolve 'react/lib/ReactComponentTreeHook' in '/Users/hemikakodikara/ballerina/dev/08/composer/modules/web/node_modules/react-dom/lib'
 @ ./\~/react-dom/lib/ReactDOMNullInputValuePropHook.js 13:29-72
 @ ./\~/react-dom/lib/ReactDOM.js
 @ ./\~/react-dom/index.js
 @ ./\~/swagger-ui/dist/swagger-ui.js
 @ ./\~/swagger-editor/dist/swagger-editor.js
 @ ./js/ballerina/views/swagger-view.js
 @ ./js/ballerina/views/ballerina-file-editor.js
 @ ./js/ballerina/views/module.js
 @ ./js/ballerina/module.js
 @ ./js/tab/file-tab.js
 @ ./js/tab/file-tab-list.js
 @ ./js/main.js
 @ ./index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./index.js

ERROR in ./\~/react-dom/lib/ReactDOMUnknownPropertyHook.js
Module not found: Error: Can't resolve 'react/lib/ReactComponentTreeHook' in '/Users/hemikakodikara/ballerina/dev/08/composer/modules/web/node_modules/react-dom/lib'
 @ ./\~/react-dom/lib/ReactDOMUnknownPropertyHook.js 15:29-72
 @ ./\~/react-dom/lib/ReactDOM.js
 @ ./\~/react-dom/index.js
 @ ./\~/swagger-ui/dist/swagger-ui.js
 @ ./\~/swagger-editor/dist/swagger-editor.js
 @ ./js/ballerina/views/swagger-view.js
 @ ./js/ballerina/views/ballerina-file-editor.js
 @ ./js/ballerina/views/module.js
 @ ./js/ballerina/module.js
 @ ./js/tab/file-tab.js
 @ ./js/tab/file-tab-list.js
 @ ./js/main.js
 @ ./index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./index.js

ERROR in ./\~/react-dom/lib/ReactDOMInvalidARIAHook.js
Module not found: Error: Can't resolve 'react/lib/ReactComponentTreeHook' in '/Users/hemikakodikara/ballerina/dev/08/composer/modules/web/node_modules/react-dom/lib'
 @ ./\~/react-dom/lib/ReactDOMInvalidARIAHook.js 14:29-72
 @ ./\~/react-dom/lib/ReactDOM.js
 @ ./\~/react-dom/index.js
 @ ./\~/swagger-ui/dist/swagger-ui.js
 @ ./\~/swagger-editor/dist/swagger-editor.js
 @ ./js/ballerina/views/swagger-view.js
 @ ./js/ballerina/views/ballerina-file-editor.js
 @ ./js/ballerina/views/module.js
 @ ./js/ballerina/module.js
 @ ./js/tab/file-tab.js
 @ ./js/tab/file-tab-list.js
 @ ./js/main.js
 @ ./index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./index.js

ERROR in ./\~/react-dom/lib/ReactDebugTool.js
Module not found: Error: Can't resolve 'react/lib/ReactComponentTreeHook' in '/Users/hemikakodikara/ballerina/dev/08/composer/modules/web/node_modules/react-dom/lib'
 @ ./\~/react-dom/lib/ReactDebugTool.js 16:29-72
 @ ./\~/react-dom/lib/ReactInstrumentation.js
 @ ./\~/react-dom/lib/ReactDOM.js
 @ ./\~/react-dom/index.js
 @ ./\~/swagger-ui/dist/swagger-ui.js
 @ ./\~/swagger-editor/dist/swagger-editor.js
 @ ./js/ballerina/views/swagger-view.js
 @ ./js/ballerina/views/ballerina-file-editor.js
 @ ./js/ballerina/views/module.js
 @ ./js/ballerina/module.js
 @ ./js/tab/file-tab.js
 @ ./js/tab/file-tab-list.js
 @ ./js/main.js
 @ ./index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./index.js

ERROR in ./\~/react-dom/lib/ReactChildReconciler.js
Module not found: Error: Can't resolve 'react/lib/ReactComponentTreeHook' in '/Users/hemikakodikara/ballerina/dev/08/composer/modules/web/node_modules/react-dom/lib'
 @ ./\~/react-dom/lib/ReactChildReconciler.js 29:27-70 37:31-74
 @ ./\~/react-dom/lib/ReactMultiChild.js
 @ ./\~/react-dom/lib/ReactDOMComponent.js
 @ ./\~/react-dom/lib/ReactDefaultInjection.js
 @ ./\~/react-dom/lib/ReactDOM.js
 @ ./\~/react-dom/index.js
 @ ./\~/swagger-ui/dist/swagger-ui.js
 @ ./\~/swagger-editor/dist/swagger-editor.js
 @ ./js/ballerina/views/swagger-view.js
 @ ./js/ballerina/views/ballerina-file-editor.js
 @ ./js/ballerina/views/module.js
 @ ./js/ballerina/module.js
 @ ./js/tab/file-tab.js
 @ ./js/tab/file-tab-list.js
 @ ./js/main.js
 @ ./index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./index.js

ERROR in ./\~/react-dom/lib/flattenChildren.js
Module not found: Error: Can't resolve 'react/lib/ReactComponentTreeHook' in '/Users/hemikakodikara/ballerina/dev/08/composer/modules/web/node_modules/react-dom/lib'
 @ ./\~/react-dom/lib/flattenChildren.js 26:27-70 42:33-76
 @ ./\~/react-dom/lib/ReactMultiChild.js
 @ ./\~/react-dom/lib/ReactDOMComponent.js
 @ ./\~/react-dom/lib/ReactDefaultInjection.js
 @ ./\~/react-dom/lib/ReactDOM.js
 @ ./\~/react-dom/index.js
 @ ./\~/swagger-ui/dist/swagger-ui.js
 @ ./\~/swagger-editor/dist/swagger-editor.js
 @ ./js/ballerina/views/swagger-view.js
 @ ./js/ballerina/views/ballerina-file-editor.js
 @ ./js/ballerina/views/module.js
 @ ./js/ballerina/module.js
 @ ./js/tab/file-tab.js
 @ ./js/tab/file-tab-list.js
 @ ./js/main.js
 @ ./index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./index.js

ERROR in ./\~/react-dom/lib/checkReactTypeSpec.js
Module not found: Error: Can't resolve 'react/lib/ReactComponentTreeHook' in '/Users/hemikakodikara/ballerina/dev/08/composer/modules/web/node_modules/react-dom/lib'
 @ ./\~/react-dom/lib/checkReactTypeSpec.js 29:27-70 71:37-80
 @ ./\~/react-dom/lib/ReactCompositeComponent.js
 @ ./\~/react-dom/lib/instantiateReactComponent.js
 @ ./\~/react-dom/lib/ReactMount.js
 @ ./\~/react-dom/lib/ReactDOM.js
 @ ./\~/react-dom/index.js
 @ ./\~/swagger-ui/dist/swagger-ui.js
 @ ./\~/swagger-editor/dist/swagger-editor.js
 @ ./js/ballerina/views/swagger-view.js
 @ ./js/ballerina/views/ballerina-file-editor.js
 @ ./js/ballerina/views/module.js
 @ ./js/ballerina/module.js
 @ ./js/tab/file-tab.js
 @ ./js/tab/file-tab-list.js
 @ ./js/main.js
 @ ./index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./index.js`

**Comment by shockey** [comment]
Hi @hemikak, apologies for the delayed response.

I have a hunch that npm may have installed a bad version of React (or a related library), which would be our fault. Can you share your output of `npm ls`?

**Comment by webron** [comment]
Closing due to lack of response. Please reopen if needed.
