### ISSUE TITLE
swagger-editor-bundle file is not in npm

### ISSUE THREAD

**Issue by roonyh** [swagger-api/swagger-editor#1235]
[swagger-editor-bundle.js](https://github.com/swagger-api/swagger-editor/blob/master/dist/swagger-editor-bundle.js) is not in npm. We use npm to get the rest of our front-end dependencies. Will be great if this file is npm as well.

**Comment by roonyh** [comment]
Hi, Is there any reason this file is not published? If its there, I can use webpack script-loader to load it. I can avoid committing it to my source code. Please consider including it. Thanks!

**Comment by shockey** [comment]
Hi,

We don't currently publish bundle files to npm, because npm will install Swagger-Editor's dependencies when the package is installed. You should be able to find all Swagger-Editor's dependencies in `node_modules` after doing an `npm install`.

You mentioned you're using Webpack- I'd expect Webpack to handle the bundling of Swagger-Editor's dependencies for you. Can you show me how you're using Swagger-Editor?

Consuming a bundle installed via npm strikes me as odd- but I may not be considering every use case.

@bodnia, @ponelat, @bn: your input is welcome here

**Comment by ponelat** [comment]
@roonyh the bundle is for using it inside a `<script>` tag.
Please use `swagger-editor.js` instead, which has commonjs module support.

There are some peer dependencies you'd need to add to your package.json as well... but unfortunately, we don't have them explicitly set inside `package.json` for structural reasons.

@shockey if you have a list of those peer dependecies, perhaps we should put them in the README?

**Comment by roonyh** [comment]
@shockey @ponelat Putting it in a `<script>` tag is exactly what I want to do. But I don't want to manually download the bundle file and put it in my source control. If I do that everytime I need to update it I will have to do it manually again.

Webpack along with npm can help save this trouble. There is a specific webpack loader to create script tags and put js files in it. See [script-loader](https://github.com/webpack-contrib/script-loader). So I can do,
~~~javascript
import 'script-loader!swagger-editor/dist/swagger-editor.bundle.js' // or the correct path
~~~
and the script tag is created for me!

This saves me the trouble of updating swagger editor manually, since npm takes care of it and the trouble of keeping it in source control.

Further its absolutely normal to install client side dependancies via npm. Npm is not only for node.js packages. To quote [this post](http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging) from npm blog,

> 
> 1. “npm is only for CommonJS!”
> 
> Not true. npm would like to be the package manager for JavaScript, so if it’s JavaScript related, the npm registry is a good place to put it. Node.js provides a CommonJS-esque module environment, but npm has no feelings on the matter.
> 
> 2. “npm is only for server-side JavaScript!”
> 
> Also not true. Your package can contain anything, whether it’s ES6, client-side JS, or even HTML and CSS. These are things that naturally turn up alongside JavaScript, so put them in there.

**Comment by shockey** [comment]
My core concern with providing the bundle files in the npm module is that everyone will end up downloading dependencies twice: once when npm pulls down `swagger-editor-bundle.js`, and again when npm installs dependencies to `node_modules`.

As mentioned in swagger-api/swagger-ui#2758, one best-of-both-worlds solution is to publish a separate package with no dependencies listed in `package.json` that includes the bundle.

**Comment by roonyh** [comment]
> My core concern with providing the bundle files in the npm module is that everyone will end up downloading dependencies twice
I understand. But is that a huge problem? Since this is something that happens in the build time.

A seperate package sounds great to me! I was thinking about that as a solution as well. I think you can automate the publishing of this package so there will be no additional maintenance overhead.

**Comment by webron** [comment]
Related to https://github.com/swagger-api/swagger-ui/issues/2758.

**Comment by shockey** [comment]
Fixed in 9e25440.

@roonyh, feel free to open another ticket if you have any more to share about your use case. Thanks for your input here, and thanks for using Swagger!

**Comment by shockey** [comment]
Oh, also- it's available on npm as `swagger-editor-dist` 😄

**Comment by roonyh** [comment]
> Oh, also- it's available on npm as swagger-editor-dist :smile:
Awesome!! This works for me. thanks much!
