### ISSUE TITLE
Problem displaying response model containing array of objects in XML

### ISSUE THREAD

**Issue by pratikpai** [swagger-api/swagger-editor#1240]
I am using swagger UI for my API documentation. I am facing issues while trying to display my response object model.

Appending below the api swagger json output:

`{
  "swagger": "2.0",
  "info": {
    "description": "Test endpoints.",
    "version": "v1",
    "title": "Rest API"
  },
  "host": "www.test.com",
  "basePath": "/v1",
  "tags": [
    {
      "name": "File Transfer",
      "description": "Api calls"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/services": {
      "get": {
        "tags": [
          "File Transfer"
        ],
        "summary": "Get transfer services list",
        "description": "List of services",
        "operationId": "getServicesList",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/xml"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "string"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "Content-Type": {
                "type": "string",
                "description": "application/xml"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ErrorResponse": {
      "type": "object",
      "properties": {
        "errors": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/error"
          }
        },
        "traceId": {
          "type": "string",
          "example": "f59c89b8-4e90-4d3a-ad44-99543d8d0697",
          "description": "traceId"
        }
      }
    },
    "error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "example": "InvalidRequestBody",
          "description": "error code"
        },
        "description": {
          "type": "string",
          "example": "The data in the request body was not found or is invalid.",
          "description": "Human readable message meant details decription of error cause"
        },
        "details": {
          "type": "string",
          "example": "The request contained missing or invalid data in body.",
          "description": "Human readable description of this error code - always the same."
        }
      }
    }
  }
}`

While displaying the response model in XML format. It displays it as below:
`<?xml version="1.0"?>
<ErrorResponse>
  <errors>
    <code>InvalidRequestBody</code>
    <description>The data in the request body was not found or is invalid.</description>
    <details>The request contained missing or invalid data in body.</details>
  </errors>
  <traceId>f59c89b8-4e90-4d3a-ad44-99543d8d0697</traceId>
</ErrorResponse>`

Expected:
`<?xml version="1.0"?>
<ErrorResponse>
  <errors>
    <error>
      <code>InvalidRequestBody</code>
      <description>The data in the request body was not found or is invalid.</description>
      <details>The request contained missing or invalid data in body.</details>
    </error>
  </errors>
  <traceId>f59c89b8-4e90-4d3a-ad44-99543d8d0697</traceId>
</ErrorResponse>`

Which has a missing child <error> node. Is there a way using which I can tackle this?

**Comment by webron** [comment]
You need to use the following spec:
```json
{
  "swagger": "2.0",
  "info": {
    "description": "Test endpoints.",
    "version": "v1",
    "title": "Rest API"
  },
  "host": "www.test.com",
  "basePath": "/v1",
  "tags": [
    {
      "name": "File Transfer",
      "description": "Api calls"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/services": {
      "get": {
        "tags": [
          "File Transfer"
        ],
        "summary": "Get transfer services list",
        "description": "List of services",
        "operationId": "getServicesList",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/xml"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "string"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "Content-Type": {
                "type": "string",
                "description": "application/xml"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ErrorResponse": {
      "type": "object",
      "properties": {
        "errors": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/error"
          },
          "xml": {
          	"wrapped": true

          }
        },
        "traceId": {
          "type": "string",
          "example": "f59c89b8-4e90-4d3a-ad44-99543d8d0697",
          "description": "traceId"
        }
      }
    },
    "error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "example": "InvalidRequestBody",
          "description": "error code"
        },
        "description": {
          "type": "string",
          "example": "The data in the request body was not found or is invalid.",
          "description": "Human readable message meant details decription of error cause"
        },
        "details": {
          "type": "string",
          "example": "The request contained missing or invalid data in body.",
          "description": "Human readable description of this error code - always the same."
        }
      },
      "xml": { "name": "error"}
    }
  }
}
```

**Comment by pratikpai** [comment]
Thank you very much Ron! I tried it by hand editing the json and it worked :).

I forgot to mention that I am using Springfox for generating the swagger json. Is there any attribute or annotation that would help me generate xml wrapped property?

Below is my response model:

`@ApiModel(value = "ErrorResponse")
public class ErrorResponse {

    private List<ErrorObject> errors;
    private String traceId;
    
    @ApiModelProperty
    public List<ErrorObject> getErrors() {
        return errors;
    }

    public void setErrors(List<ErrorObject> errors) {
        this.errors = errors;
    }

    @ApiModelProperty(value = "traceId", example = "f59c89b8-4e90-4d3a-ad44-99543d8d0697")
    public String getTraceId() {
        return traceId;
    }

    public void setTraceId(String traceId) {
        this.traceId = traceId;
    }

}

@ApiModel(value = "error")
public class ErrorObject {
    
    private String code;
    private String description;
    private String details;
    
    @ApiModelProperty(value = "error code", example = "InvalidRequestBody")
    public String getCode() {
        return code;
    }
    public void setCode(String code) {
        this.code = code;
    }
    
    @ApiModelProperty(value = "Human readable message meant details decription of error cause", example = "The data in the request body was not found or is invalid.")
    public String getDescription() {
        return description;
    }
    public void setDescription(String description) {
        this.description = description;
    }
    
    @ApiModelProperty(value = "Human readable description of this error code - always the same.", example = "The request contained missing or invalid data in body.")
    public String getDetails() {
        return details;
    }
    public void setDetails(String details) {
        this.details = details;
    }
}
`

**Comment by webron** [comment]
That's something you need to ask the Springfox people.
