### ISSUE TITLE
Schema HTTPS does not working

### ISSUE THREAD

**Issue by twawszczak** [swagger-api/swagger-editor#1242]
When i set:

schemes:
- "https"

in my config file, the "Try it out" request goes to "http", not "https". :/ (version 3.0.2, the newest)

**Comment by spurin** [comment]
Seeing the same issue

**Comment by partounian** [comment]
Just to note I am also having this issue, I'm running the docker container.

**Comment by webron** [comment]
Closing in favor of https://github.com/swagger-api/swagger-ui/issues/2906.
