### ISSUE TITLE
Swagger-Editor V3 Safari Support

### ISSUE THREAD

**Issue by ApigeeCorky** [swagger-api/swagger-editor#1243]
Getting an error when running the Swagger-editor version 3 using Safari version 10.0 on MacOS (Sierra).  Same with MacOS El Capitan (9.0).    Error received in console after running npm start (screen shot below)

[Error] TypeError: Object.values is not a function. (In 'Object.values(n)', 'Object.values' is undefined)
	s (swagger-editor-bundle.js:92:14009)

Chrome and Firefox load fine.  Is there anything special needed to support Safari?

![safariswaggereditor](https://cloud.githubusercontent.com/assets/18214890/24425502/b20f422a-13c1-11e7-9e17-527e17d9259c.png)

**Comment by webron** [comment]
See #1232.
