### ISSUE TITLE
Swagger Editor V3 - Safari Support

### ISSUE THREAD

**Issue by ApigeeCorky** [swagger-api/swagger-editor#1244]
Rebuilding the latest per issue [1232](https://github.com/swagger-api/swagger-editor/issues/1232)....Using MacOS Sierra, Safari 10.  The editor now displays and works on initial load by typing changes to the spec, but it is very easy for the swagger spec display pane to stop working and stop responding.  After loading the editor with the default spec....highlight the entire spec in the editor, delete the contents of the editor, and the console throws an error and the display pane no longer responds to content changes in the editor.  (same behavior works fine in chrome and firefox).

Steps to recreate:
Rebuild per issue 1232
Load in safari
Command-A -> Command X to highlight and cut all content out of the editor
Error thrown in javascript console
type anything in the editor, display pane does not respond

![speceditor-safari2](https://cloud.githubusercontent.com/assets/18214890/24462257/c50f1248-1460-11e7-8197-1c46a550634b.png)

**Comment by webron** [comment]
Issue confirmed. Not sure it's related to Safari though, I've seen similar things in other browsers. We'll need to investigate.

**Comment by twawszczak** [comment]
Same problems occurs in other browsers. (for example Chrome)

**Comment by shockey** [comment]
This should be working again when we release new versions of Swagger-UI and Swagger-Editor on Friday. 🍻

**Comment by shockey** [comment]
Confirmed working for me; releasing version with a fix now.

Please reopen if the problem persists.
