### ISSUE TITLE
referenced files not accessible when authorization key required

### ISSUE THREAD

**Issue by karux** [swagger-api/swagger-editor#1248]
When referencing private domain files on swaggerhub, an authorization key is required. How do I specify the authorization key in the swagger editor?

All external references to the domain definition behind the authorization check are inaccessible and display as swagger errors. 

Reference could not be resolved: https://api.swaggerhub.com/domains/foo/2.0.0#/definitions/Cart

**Comment by webron** [comment]
@karux you can't do that with the OSS Editor. If you want to make it work, you'd need to introduce code changes and manage it locally. Is this what you're after?

**Comment by webron** [comment]
Closing for lack of response.
