### ISSUE TITLE
Parameters' name with "_" not properly mapped in Angular2 typescript client

### ISSUE THREAD

**Issue by basygit** [swagger-api/swagger-editor#1249]
This bug is both online on http://editor.swagger.io/#!/, than into the "http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/2.2.2/swagger-codegen-cli-2.2.2.jar"

![capture](https://cloud.githubusercontent.com/assets/26896343/24651229/5b545ed6-192d-11e7-943e-d4b6eb6003d5.PNG)

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger-codegen#5322
