### ISSUE TITLE
Swagger editor will not run in Kali linux

### ISSUE THREAD

**Issue by ITGSean** [swagger-api/swagger-editor#1252]
Hi I am getting these errors when running swagger editor in Kali 2016:

kali-fresh:/opt/swagger-editor# npm start

> swagger-editor@3.0.3 prestart /opt/swagger-editor
> npm install

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN eslint-config-standard@6.2.1 requires a peer of eslint@>=3.8.1 but none was installed.
npm WARN eslint-config-standard-jsx@3.2.0 requires a peer of eslint@>=3.0.0 but none was installed.
npm WARN eslint-plugin-standard@2.0.1 requires a peer of eslint@>=3.0.0 but none was installed.
npm WARN react-addons-perf@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm WARN react-addons-shallow-compare@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm WARN react-object-inspector@0.2.1 requires a peer of react@^0.14.0 but none was installed.

> swagger-editor@3.0.3 start /opt/swagger-editor
> npm-run-all --parallel serve-static open-static

sh: 1: npm-run-all: not found

npm ERR! Linux 4.9.0-kali3-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! swagger-editor@3.0.3 start: `npm-run-all --parallel serve-static open-static`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the swagger-editor@3.0.3 start script 'npm-run-all --parallel serve-static open-static'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the swagger-editor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all --parallel serve-static open-static
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs swagger-editor
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls swagger-editor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/swagger-editor/npm-debug.log

[npm-debug.zip](https://github.com/swagger-api/swagger-editor/files/895710/npm-debug.zip)

**Comment by webron** [comment]
Please check the README and the prerequisites. You need to run it with node 6.
