### ISSUE TITLE
Concurrent modifications to an API definition

### ISSUE THREAD

**Issue by lcofre** [swagger-api/swagger-editor#1253]
I am running the editor on a local network, so all the team can access it:
swagger project edit -s /path/to/the/api/project -p 8888 --host 0.0.0.0

Every modification on the editor overwrites the API definition, so concurrent modifications will overwrite the one from the other user.

Are there plans to manage user concurrency?

Thanks for this great project.

**Comment by webron** [comment]
The project is intended for single user only, we currently don't have plans changing that.
