### ISSUE TITLE
Path parameter should get escaped

### ISSUE THREAD

**Issue by kPshi** [swagger-api/swagger-editor#1254]
When defining a path parameter like
```yaml
  /v1/config/{key}:
    get:
      produces: ["application/json"]
      parameters:
        - name: key
          type: string
          in: path
          required: true
      responses:
        "200":
          schema:
            type: object
            properties:
              key:
                type: string
              value:
                type: string
```
And try it via the editor's WUI with a key containg a slash, e.g. "foo/bar" then it is sent as is resulting in
```GET http://127.0.0.1:8889/v1/config/foo/bar```
while the parameter should be escaped resulting in
```GET http://127.0.0.1:8889/v1/config/foo%2Fbar```

**Comment by webron** [comment]
@kPshi - which version of swagger-editor do you use?

**Comment by kPshi** [comment]
Version 2.10.5

**Comment by webron** [comment]
Try the latest version - it should be fixed there.

**Comment by kPshi** [comment]
Works. Great! :-)

**Comment by webron** [comment]
Great :)
