### ISSUE TITLE
Is there an way to validate swagger.yaml online?

### ISSUE THREAD

**Issue by wy65701436** [swagger-api/swagger-editor#1260]
I know this url can validate json, but not yaml. http://online.swagger.io/validator/debug?url=your_url
My requirement is that I want to get the status of my yaml file, success or fail. Appreciate if you can help.

**Comment by fehguy** [comment]
try this?

http://online.swagger.io/validator/debug?url=http://petstore.swagger.io/v2/swagger.yaml

**Comment by wy65701436** [comment]
tried it, but get {"messages":["malformed or unreadable swagger supplied"],"schemaValidationMessages":[{"level":"error","domain":"validation","keyword":"type","message":"instance type (string) does not match any allowed primitive type (allowed: [\"object\"])","schema":{"loadingURI":"#","pointer":""},"instance":{"pointer":""}}]}

**Comment by wy65701436** [comment]
my file locates at github.

**Comment by fehguy** [comment]
http://online.swagger.io/validator/debug?url=https://raw.githubusercontent.com/swagger-api/swagger-parser/master/modules/swagger-parser/src/test/resources/sampleWithMinimumValues.yaml

It works fine.  Maybe the issue is your spec is bad?

**Comment by wy65701436** [comment]
but, I tried to copy the content to the online http://editor.swagger.io, get the message "Processed with no error". Any idea?

**Comment by webron** [comment]
Is the github file public?

**Comment by wy65701436** [comment]
yes, it is. 

You can view it at: https://github.com/vmware/harbor/blob/master/docs/swagger.yaml

**Comment by webron** [comment]
Is there any chance you're passing the direct github url to the validator and not the raw? (https://raw.githubusercontent.com/vmware/harbor/master/docs/swagger.yaml)

**Comment by wy65701436** [comment]
I want to leverage the online checker into our CI process to ensure the success of our yaml file.
Can you help to tell how can covert the direct github url to the raw?

**Comment by wy65701436** [comment]
@webron, got you. Tried with the direct github url, it worked fine with my yaml.

I will close this issue. thanks for all your support.
