### ISSUE TITLE
404 when trying to "learn more about CORS"

### ISSUE THREAD

**Issue by SuperMarioLand** [swagger-api/swagger-editor#1261]
On the on-line hosted version of swagger-editor

http://editor.swagger.io/#!/

set your host to be localhost:7080 for example

the "Learn more" link is down when refering to CORS

⚠️ This is a cross-origin call. Make sure the server at localhost:7080 accepts GET requests from editor.swagger.io. Learn more

![image](https://cloud.githubusercontent.com/assets/27024089/24813905/ccda9120-1b9d-11e7-9736-62994d6c42b7.png)

EDIT: Currently points to:

https://github.com/swagger-api/swagger-editor/blob/master/docs/cors.md

**Comment by webron** [comment]
Thank you for pointing that out. In the mean time, the link to the document is https://github.com/swagger-api/swagger-editor/blob/2.x/docs/cors.md.

**Comment by webron** [comment]
We're not going to fix this issue.

**Comment by bf4** [comment]
@webron would you mind clarifying what you mean by not fixing the issue? Do you mean there won't be such a link in the future, there won't be such docs in the future, or the link will always be broken?

**Comment by webron** [comment]
The link will be broken. It only exists in the 2.X version and doesn't exist in the 3.X version. We're not going to release a new 2.X version unless we find something insanely critical.

**Comment by bf4** [comment]
@webron Thanks so much for the quick and helpful reply and also all the work you do :)
