### ISSUE TITLE
Allow multiline for body parameters in Try it out

### ISSUE THREAD

**Issue by lcofre** [swagger-api/swagger-editor#1267]
This is a definition example:
```
swagger: "2.0"
info:
  title: API
  version: 1.0.0
host: localhost:10010
basePath: /users
schemes:
  - http
paths:
  /destination/path:
    post:
      consumes:
        - text/plain
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: string
      responses:
        204:
          description: OK
```

On the preview, pressing Try it out shows the parameter called "body" as an html input tag. Can you use a textarea instead, to allow multiline?

**Comment by shockey** [comment]
closing; we use a `<textarea>` now:

<img src='https://shipusercontent.com/762af43ddbd38d3a542198ca6915207b/Pasted%20Image%203.png' title='Pasted Image 3.png' width=1792>


thanks @lcofre!
