### ISSUE TITLE
Crash, lost work in progress

### ISSUE THREAD

**Issue by brodney** [swagger-api/swagger-editor#1268]
Thanks.

**Comment by webron** [comment]
@brodney we'd love to help, but really need more details.
Which editor did you use? OS? Browser? What crashed? The browser? The editor tab?

**Comment by brodney** [comment]
Pardon my initial frustration, I lost a good bit of work. Redid it, even better now.

The online editor in Safari locked up and appears to be locking up pretty frequently now. Activity Monitor reported several threads each around 20% utilization.

Additionally it gets stuck (pinwheel) when I make changes to the file and it attempts to parse to display the documentation. When that happens it won't update the error message even when fixed or change.

**Comment by webron** [comment]
Thanks for the details. We recently released a new version of the editor, but that's not available online yet (soon). Can you try running the editor from a clone of this repo? You only need to open the index.html file at the root, no build required.

**Comment by brodney** [comment]
Sure which branch?

**Comment by webron** [comment]
Just master.

**Comment by brodney** [comment]
Couple bugs for you:
1. Open file seems broken. I select the file through the file chooser dial go, then click "Open File" and the dialog areas are highlighted by nothing happens. Ignore the filename, I tried it with an actual yaml file, the file in the screenshot is to obscure the filename I was using.
<img width="492" alt="screen shot 2017-04-13 at 15 12 29" src="https://cloud.githubusercontent.com/assets/1307780/25020273/a4b845a8-205b-11e7-96d8-47667be6536f.png">

2. When typing in the editor, the autocomplete seems over-eager. I'm seeing letters show up in the editor twice. It's fairly frequent, definitely not just typing mistakes.

No crash or performance issues I'm seeing though 👍 . The error reporting seems much much faster to show up and disappear, and hasn't hung as I tried adding a new object type and using it here or there. I'll use this for now and report back if anything happens again.

**Comment by webron** [comment]
Thanks for the feedback, @brodney. You mentioned you use Safari - which version of Safari? Would you mind testing the file opening with a different browser too?

**Comment by brodney** [comment]
10.0.3 on Sierra. No issue opening on chrome.

**Comment by webron** [comment]
Thanks for your patience and checking things, @brodney. I really appreciate the help.

If you don't mind, could you open a separate ticket for one of the two issues you mentioned [here](https://github.com/swagger-api/swagger-editor/issues/1268#issuecomment-293995735). It's easier to handle isolated issues, and I normally prefer users to open the tickets so they get notified about the progress properly.

**Comment by shockey** [comment]
The bugs mentioned upthread appear to have been fixed a while ago, so I'm going to close this ticket.

Thanks for the report, @brodney! Please ping if you're still experiencing any of these issues.
