### ISSUE TITLE
how to configure generate client or server in Swagger Editor

### ISSUE THREAD

**Issue by jangilOh51** [swagger-api/swagger-editor#1272]
Hi 

I install Swagger editor 3.0.4
when I see Swagger editor online , "http://editor.swagger.io/#!/" , I see "generate server/client".
but I can't find "generate server/client" in My Swagger editor.

Could you help me how to configure the feature?

My Install Step 
1. npm install -g http-server
2. download swagger editor 3.0.4
3. http-server swagger-editor

**Comment by webron** [comment]
See [known issues](https://github.com/swagger-api/swagger-editor#known-issues).
