### ISSUE TITLE
Provide an extension mechanism

### ISSUE THREAD

**Issue by DavidBiesack** [swagger-api/swagger-editor#1275]
Please provide a defined, supported way to extend swagger-editor such as adding new menus and menu items and actions to run for them. For example, we have built a tool which processes x-sas-traits extension syntax to generate OpenAPI definition constructs. We have a REST service which accepts an OpenAPI definition body, transforms it, and returns it and we use this to replace the YAML in the editor with generated code. But keeping the extensions in sync with code changes is hard. We would like to include menus for OpenAPI code snippets, etc.

We would also like an extension point so we can add warning/error messages to the editor when we run a separate OpenAPI document validation tool (a separate REST service).

A document on configuring (what can I change in index.html, for example) would also be very useful - i.e. how to use an alternate swagger-validator-badge to check the syntax/structure?

**Comment by fehguy** [comment]
@DavidBiesack we have done so--in the 3.x version, you can extend the editor very easily.  Please take a look at how the new code is structured, and you can now implement plugins to add additional logic on the existing editor.

**Comment by DavidBiesack** [comment]
Thanks, @feyguy - I look forward to some doc on how to add extensions... preferably with an example. (Being able to manage  two+ codebases -- clone from github and the local extensions/plugins -- is important.) a Developing.md page would help. I'd prefer to leave this ticket open until some doc exists.

**Comment by fehguy** [comment]
Sure thing and yes, docs are needed.

**Comment by shockey** [comment]
Closing; we have [Customization docs](https://github.com/swagger-api/swagger-ui/tree/master/docs/customization) now!
