### ISSUE TITLE
Treat literals vs parameters in the otherwise equivalent paths as different paths

### ISSUE THREAD

**Issue by michkhol** [swagger-api/swagger-editor#1276]
Currently version 2.10.5 treats those two paths as equivalent:
`/search/{myncbi-id}/citations`
`/search/{myncbi-id}/{search-id}`
But the spec treats them as different: [https://github.com/OAI/OpenAPI-Specification/issues/1048](https://github.com/OAI/OpenAPI-Specification/issues/1048) and Swagger-UI seems to support it too.

**Comment by shockey** [comment]
@webron, this is `2.x` 😄 

I've added a unit test to the 3.x series to prevent a regression there. 

Unassigning myself.

**Comment by webron** [comment]
@shockey huh. Didn't notice, thanks.

@michkhol this is something we won't fix in the 2.x branch, so please use the 3.x one.
