### ISSUE TITLE
Packaging options

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-editor#1277]
Right now, we are packaging the entire component--with top bar--in a single bundle.  This works great for the editor.swagger.io, but for someone who wants to reuse the component, they probably won't want the top bar.

I suggest that the top bar lives in _html_ and **not** in the bundle.  Then, we can modify and customize the top bar (and let others do the same) without rebuilding it.

**Comment by shockey** [comment]
We can (should) mirror what we're doing in UI - provide the top bar and other assorted things for standalone use in a plugin.

**Comment by shockey** [comment]
Work being done here: https://github.com/shockey/swagger-editor/tree/ft/standalone-preset

Having an issue with the build process - going to fix some other things and circle back.
