### ISSUE TITLE
Swagger Online Editor

### ISSUE THREAD

**Issue by Jeevanchathuranga** [swagger-api/swagger-editor#1280]
we cant see generate server,generate client,new file,open example and other features in onlline Swagger editor. Yesterday it was there. 

http://editor.swagger.io/#!/

**Comment by nuwansanjeewa** [comment]
same issue is there any solution generate client app

**Comment by webron** [comment]
The online editor has a way to revert to the older editor until we implement the code generation calls in it. Unfortunately, there's an issue with the older editor being hosted, but we'll fix that issue later today.

In the meantime, you can always use the codegen directly, or the online generator at http://generator.swagger.io/.

**Comment by orientzc** [comment]
and the same issue is there with docker(swaggerapi/swagger-editor:latest).

**Comment by nuwansanjeewa** [comment]
need to generate c# client app . how can i do it .still we can not generate client app

**Comment by webron** [comment]
You can switch back to the old editor (link works now), or you can use the generator directly, as mentioned above.

**Comment by nuwansanjeewa** [comment]
could you give old editor link ?

**Comment by webron** [comment]
editor2.swagger.io (link is in the current editor).

**Comment by nuwansanjeewa** [comment]
but this is not working.i think url is not correct

**Comment by webron** [comment]
It works for me. We just updated the DNS so it might take some time to get to you. Also, you might want to clear your DNS cache and try again.

**Comment by nuwansanjeewa** [comment]
now it's working.thanks
