### ISSUE TITLE
ERR_NAME_NOT_RESOLVED editor2.swagger.io

### ISSUE THREAD

**Issue by bobvanluijt** [swagger-api/swagger-editor#1283]
When clicking: "Switch back to previous editor" the error: "ERR_NAME_NOT_RESOLVED" shows.

Replicate: http://editor2.swagger.io/

<img width="434" alt="screen shot 2017-04-20 at 15 10 57" src="https://cloud.githubusercontent.com/assets/5509162/25232461/a868e628-25db-11e7-9656-7a6cb84e61d6.png">

**Comment by webron** [comment]
It's accessible now.
