### ISSUE TITLE
New errors not sure if it is okay to ignore...

### ISSUE THREAD

**Issue by j-kamal** [swagger-api/swagger-editor#1284]
In previous versions, didnt see these errors

- Semantic error - Query strings in paths are not allowed.
- Resolver error - Could not resolve reference because of: Tried to resolve a relative URL, without having a basePath.

**Comment by webron** [comment]
We've made *a lot* of changes to the validation in the editor. They include more cases, and we've tried to provide clearer messages to help you with authorizing a spec.

The first error is real - you cannot have query strings in the path.

The second one, I haven't seen before, so difficult for me to say. If you can share your spec, I could look into it.

**Comment by j-kamal** [comment]
Thanks for the response @webron 
Indeed Resolver error was a miss in previous version, there was # missing for $ref which I had fixed it...
IMHO ...usage of Query strings should be a warning rather than error...

**Comment by webron** [comment]
The spec doesn't support it, so it's an error. It's an invalid definition. Warnings are things that are recommended to look at, but you don't have to 'fix' them. This error, you do.
