### ISSUE TITLE
allOf in definitions duplicate difinitions

### ISSUE THREAD

**Issue by ssamooilov** [swagger-api/swagger-editor#1288]
swagger editor version: 3.0.6 
```
swagger: '2.0'
info:
  version: 1.0.0
  title: API
paths: {}
definitions:
  Foo:
    type: object
    properties:
      name:
        type: string
  Bar:
    allOf:
      - $ref: '#/definitions/Foo'
```
![image](https://cloud.githubusercontent.com/assets/16803176/25263996/e632c48a-268d-11e7-8882-c794eafffcfe.png)

**Comment by webron** [comment]
Related to https://github.com/swagger-api/swagger-ui/issues/2946.

**Comment by shockey** [comment]
This appears to be fixed: 

![image](https://user-images.githubusercontent.com/680248/28812929-e892dacc-764b-11e7-9f40-2f04a50f8961.png)

I know we fixed this in the UI a short time ago - I can't find the relevant PR at the moment.

Closing!
