### ISSUE TITLE
Schema HTTPS still does not working

### ISSUE THREAD

**Issue by twawszczak** [swagger-api/swagger-editor#1293]
In latest version (3.0.6) the issue #1242 still occurs.  :(( (in swagger ui it is ok, so it is a problem with only editor)

**Comment by webron** [comment]
@shockey - this seems to be a repeating issue, that fixes that get into swagger-ui, don't get into the swagger-editor release.

**Comment by shockey** [comment]
This was an oversight on my part - when I built swagger-editor for 3.0.7 release, I had a stale `swagger-ui` version in my `node_modules`.

@twawszczak, I'll cut a new release with the new stuff in it 😄
