### ISSUE TITLE
Problem with HTTPS still occurs

### ISSUE THREAD

**Issue by twawszczak** [swagger-api/swagger-editor#1297]
#1293 - unfortunately, i have updated editor to 3.0.7 version and https still does not working! Please check it before closing issue - you have closed issues just two times (#1293, #1242) and the problem is still current.

**Comment by MBurchard** [comment]
I also have an issue, that might be https related.  
With the 3.0.7 release I can not try the requests any more. There simply nothing happens and there is also no error message.  
With version 2.10.5 the same yaml file works like a charm,
My yaml file is on the local pc, the service is a remote service...

**Comment by webron** [comment]
Just tried it and it works as expected. If you have an issue, please share the spec for us to reproduce.

**Comment by shockey** [comment]
Working for me as well - @twawszczak @MBurchard, sharing specs we can test with will help us get this fixed.

**Comment by MBurchard** [comment]
This is not that easy, because the service we work against is internal and can only be reached using VPN.
I'll try to prepare something and post it here...

**Comment by MBurchard** [comment]
I found the problematic element in my OpenAPI specification:

      - in: query
        name: grant_type
        type: string
        description: the ... typically set to password
        required: true
        enum:
        - password

If the grant_type has no enum, it works fine...  
With the enum the execute button simply does nothing...  No Errors in the console... Nothing...

**Comment by webron** [comment]
@MBurchard that's due to https://github.com/swagger-api/swagger-ui/issues/2841.

**Comment by twawszczak** [comment]
@shockey my mistake :/, you can close this issue.
