### ISSUE TITLE
Extract validation code as a standalone library

### ISSUE THREAD

**Issue by nemenemsrouge** [swagger-api/swagger-editor#1301]
I think the swagger-editor validation is really good and accurate and different validation tools are not equals in behavior

I personally tested swagger-cli and swagger-tools but they all spot different patterns.

So it would be nice to have a well maintained (with the help of the community) an exhaustive validation and official validation library and maybe it should start from the one you use in the editor app.

**Comment by webron** [comment]
Thank you for the suggestion, but at the moment this is outside of the capacity of what we can do.
