### ISSUE TITLE
Swagger-editor should not reject multiple template parameters in a single URI segment

### ISSUE THREAD

**Issue by michaelkourlas** [swagger-api/swagger-editor#1303]
Version: 3.x (http://editor.swagger.io/#/)

It looks like swagger-editor now rejects any path that contains multiple template parameters in a single URI segment (see Assertion 6 in https://github.com/swagger-api/swagger-editor/blob/master/src/plugins/validation/semantic-validators/validators/paths.js).

This means that specs like the following now fail validation:
```json
{
  "info": {
    "title": "Sample",
    "version": "0.1.0"
  },
  "paths": {
    "/path/{param1},{param2}": {
      "get": {
        "parameters": [
          {
            "description": "The first parameter.",
            "in": "path",
            "name": "param1",
            "required": true,
            "type": "string"
          },
          {
            "description": "The second parameter.",
            "in": "path",
            "name": "param2",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "default": {
            "description": "Some response."
          }
        },
        "summary": "Some operation."
      }
    }
  },
  "swagger": "2.0"
}
```

Why are such paths now considered illegal, though? The Swagger spec does not seem to bar a single URI segment from containing multiple template parameters. Moreover, the sample specification above still passes validation when used in the older version of swagger-editor or using validator-badge.

**Comment by webron** [comment]
That's a bug. I believe we made the wrong assertion at the time.

**Comment by corleonis** [comment]
I have similar problem, in my case I have following path: `"/path/resource.{format}"` where format in my case is `json` or `xml`. That used to work with the old editor. So +1 from me.

**Comment by kkoumantaros** [comment]
We have a similar issue the editor complains about this " /projects/{PROJECT}/topics/{TOPIC}:modifyAcl"  with the following message _"Semantic error at paths./projects/{PROJECT}/subscriptions/{SUBSCRIPTION}:modifyAcl
Partial path templating is not allowed."_   
and this blocks the rendering of the speck with the rather generic Invalid Spec.

**Comment by shockey** [comment]
@kkoumantaros Semantic validation should not be blocking the rendering. Can you check for an error message in your browser console?

**Comment by kkoumantaros** [comment]
@shockey Chrome gives me the following errors 


Resolver errorMaximum call stack size exceeded

swagger-ui-bundle.js:34456 RangeError
(anonymous) @ swagger-ui-bundle.js:34456
swagger-ui-bundle.js:9557 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at xe (swagger-ui-bundle.js:9557)
    at pe.__ensureOwner (swagger-ui-bundle.js:10792)
    at Ze.__ensureOwner (swagger-ui-bundle.js:10792)
    at Ze.pe.asMutable (swagger-ui-bundle.js:10792)
    at Ze.pe.withMutations (swagger-ui-bundle.js:10792)
    at Ze (swagger-ui-bundle.js:9557)
    at n.toOrderedMap (swagger-ui-bundle.js:10792)
    at a (swagger-ui-bundle.js:28754)
    at swagger-ui-bundle.js:9557
    at I.__iterate (swagger-ui-bundle.js:9557)

**Comment by shockey** [comment]
@kkoumantaros I think you're experiencing a different problem. Can you open a new ticket and provide a copy of the spec that's giving you trouble, so we can look into it?

**Comment by jorgefeitosa2012** [comment]
Also, returns the same message if I put:

/country/{code}.json

Semantic error at paths./country/{code}.json
Partial path templating is not allowed.

Is there any way to swagger insert automatically the .json instead of using as a param {format}?

**Comment by michaelkourlas** [comment]
@shockey, do you have an ETA for when this will be fixed? Anything I can do to help? For example, would a PR that simply removed the problematic validator be acceptable?

**Comment by shockey** [comment]
@michaelkourlas, apologies, no ETA from me - we have a sizeable backlog of issues, so it's hard to predict.

I chatted with @webron and we settled on removing the partial path templating validator. A PR that does so would be much appreciated 😄  feel free to ping me if you need any pointers!
