### ISSUE TITLE
Unable to run server from my System.

### ISSUE THREAD

**Issue by Karthik45** [swagger-api/swagger-editor#1304]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'bugs', 'user-service-apis' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 silly fetchPackageMetaData user-service-apis
5 silly fetchNamedPackageData user-service-apis
6 silly mapToRegistry name user-service-apis
7 silly mapToRegistry using default registry
8 silly mapToRegistry registry https://registry.npmjs.org/
9 silly mapToRegistry uri https://registry.npmjs.org/user-service-apis
10 verbose request uri https://registry.npmjs.org/user-service-apis
11 verbose request no auth needed
12 info attempt registry request try #1 at 11:50:46 AM
13 verbose request id 0ac4a05f9ae6f1a7
14 http request GET https://registry.npmjs.org/user-service-apis
15 http 404 https://registry.npmjs.org/user-service-apis
16 verbose headers { 'content-type': 'application/json',
16 verbose headers   'cache-control': 'max-age=0',
16 verbose headers   'content-length': '2',
16 verbose headers   'accept-ranges': 'bytes',
16 verbose headers   date: 'Thu, 27 Apr 2017 06:20:48 GMT',
16 verbose headers   via: '1.1 varnish',
16 verbose headers   age: '0',
16 verbose headers   connection: 'keep-alive',
16 verbose headers   'x-served-by': 'cache-sin18021-SIN',
16 verbose headers   'x-cache': 'MISS',
16 verbose headers   'x-cache-hits': '0',
16 verbose headers   'x-timer': 'S1493274048.527411,VS0,VE941',
16 verbose headers   vary: 'Accept-Encoding' }
17 silly get cb [ 404,
17 silly get   { 'content-type': 'application/json',
17 silly get     'cache-control': 'max-age=0',
17 silly get     'content-length': '2',
17 silly get     'accept-ranges': 'bytes',
17 silly get     date: 'Thu, 27 Apr 2017 06:20:48 GMT',
17 silly get     via: '1.1 varnish',
17 silly get     age: '0',
17 silly get     connection: 'keep-alive',
17 silly get     'x-served-by': 'cache-sin18021-SIN',
17 silly get     'x-cache': 'MISS',
17 silly get     'x-cache-hits': '0',
17 silly get     'x-timer': 'S1493274048.527411,VS0,VE941',
17 silly get     vary: 'Accept-Encoding' } ]
18 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/user-service-apis
18 silly fetchPackageMetaData     at makeError (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:264:12)
18 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:242:14)
18 silly fetchPackageMetaData     at Request._callback (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:172:14)
18 silly fetchPackageMetaData     at Request.self.callback (/usr/share/npm/node_modules/request/request.js:198:22)
18 silly fetchPackageMetaData     at emitTwo (events.js:87:13)
18 silly fetchPackageMetaData     at Request.emit (events.js:172:7)
18 silly fetchPackageMetaData     at Request.<anonymous> (/usr/share/npm/node_modules/request/request.js:1082:10)
18 silly fetchPackageMetaData     at emitOne (events.js:82:20)
18 silly fetchPackageMetaData     at Request.emit (events.js:169:7)
18 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/share/npm/node_modules/request/request.js:1009:12)
18 silly fetchPackageMetaData  error for user-service-apis { [Error: Registry returned 404 for GET on https://registry.npmjs.org/user-service-apis] pkgid: 'user-service-apis', statusCode: 404, code: 'E404' }
19 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/user-service-apis
19 verbose stack     at makeError (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:264:12)
19 verbose stack     at CachingRegistryClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:242:14)
19 verbose stack     at Request._callback (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:172:14)
19 verbose stack     at Request.self.callback (/usr/share/npm/node_modules/request/request.js:198:22)
19 verbose stack     at emitTwo (events.js:87:13)
19 verbose stack     at Request.emit (events.js:172:7)
19 verbose stack     at Request.<anonymous> (/usr/share/npm/node_modules/request/request.js:1082:10)
19 verbose stack     at emitOne (events.js:82:20)
19 verbose stack     at Request.emit (events.js:169:7)
19 verbose stack     at IncomingMessage.<anonymous> (/usr/share/npm/node_modules/request/request.js:1009:12)
20 verbose statusCode 404
21 verbose pkgid user-service-apis
22 verbose cwd /home/karthik/Downloads/nodejs-server-server
23 error Linux 4.8.0-41-generic
24 error argv "/usr/bin/nodejs" "/usr/bin/npm" "bugs" "user-service-apis"
25 error node v4.2.6
26 error npm  v3.5.2
27 error code E404
28 error 404 Registry returned 404 for GET on https://registry.npmjs.org/user-service-apis
29 error 404
30 error 404 'user-service-apis' is not in the npm registry.
31 error 404 You should bug the author to publish it (or use the name yourself!)
32 error 404 Note that you can also install from a
33 error 404 tarball, folder, http url, or git url.
34 verbose exit [ 1, true ]

**Comment by webron** [comment]
Check the [prerequisites](https://github.com/swagger-api/swagger-editor#prerequisites). Also, you don't need to build it to run it locally - check the README.
