### ISSUE TITLE
Comment for a $ref in definition fires a semantic error.

### ISSUE THREAD

**Issue by Cooker-Monster** [swagger-api/swagger-editor#1305]
New editor defines "Sibling values are not allowed alongside a $ref." as a Semantic Error as the previous one defined it as a Warning. 

I think that put a comment for a $ref is not a semantic error.
Rolling back as warning could be nice (in fact, allowing comment on $ref without warning won't offend me).

**Comment by shockey** [comment]
Can't reproduce this.

I tried this, and only got a resolver error for the non-existent path:

```
swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Petstore"
host: "petstore.swagger.io"
basePath: "/v2"
schemes:
- "http"
paths:
  /:
    # hello, this is a comment
    $ref: "#/some/path"
```

@Cooker-Monster, can you provide a test spec for this?

**Comment by webron** [comment]
@shockey 

```yaml
swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Petstore"
host: "petstore.swagger.io"
basePath: "/v2"
schemes:
- "http"
paths:
  /:
    get:
      responses:
        200:
          $ref: '#/responses/test'
          schema:
            type: string
          
responses:
  test:
    description: hello
```

**Comment by shockey** [comment]
Alright, I read this wrong 😄 

Fixing.

**Comment by Cooker-Monster** [comment]
Fast & efficient => congrats !!!

**Comment by matthieugeerebaert** [comment]
It seems that current online swagger editor is not up to date ? 

![image](https://user-images.githubusercontent.com/3653040/34834541-828b63e8-f6f2-11e7-8ea4-dba1d96e0aa9.png)

**Comment by shockey** [comment]
@matthieugeerebaert, it’s up to date 😄 that error looks valid, you can’t have any other values alongside a $ref, because $ref works by replacing itself and everything on its level with the data it is pointing at.

see https://github.com/swagger-api/swagger-editor/issues/1184 for more context on this.

**Comment by matthieugeerebaert** [comment]
Oups sorry ! I read this issue too quickly, it's only about comment, thought it was a general issue that semantic "Sibling values are not allowed alongside a $ref" should only be warning. And yes #1184 is my current problem. We have hundred of swaggers with attribute description and definition description :( Having now those "Error" is a major problem, I was trying to find honorable workaround :) Sorry for my bad interpretation Shockey ;)

**Comment by matthieugeerebaert** [comment]
Hey so using comment instead of description might be a good workaround, thank you !

**Comment by shockey** [comment]
@matthieugeerebaert no problem!

I just realized that our new validation system is actually reporting this as an error again, so there was something to fix here after all 😄

**Comment by matthieugeerebaert** [comment]
Thank you Shockey, perfect !

**Comment by scara** [comment]
Hi @shockey,
is there any progress here?

TIA,
Matteo

**Comment by shockey** [comment]
hi @scara, this is fixed!

**Comment by scara** [comment]
TNX @shockey for the follow up!
Didn't try by myself before your last comment.

Everything looks OK now: a gently warning is fired in the editor while nothing appears in the viewer pane.
