### ISSUE TITLE
"Generate Client" -> "C# .NET 2.0" adds redundant subclass get/set methods from superclass, that hide superclass implementation

### ISSUE THREAD

**Issue by patrickoshaughnessey** [swagger-api/swagger-editor#1310]
If you create a subclass of an object using the 'allOf' mechanism, then generate the C# 2.0 code, you end up with getters/setters generated in both the superclass and subclass for the superclass's properties. An older version of the editor used to properly generate only the superclass methods.

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger-codegen#5524
