### ISSUE TITLE
Feature request: Disable live autocomplete if it’s affecting the main thread

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-editor#1311]
- Disable as-you-type autocomplete if it takes more than 100ms.
- When disabled, keep an eye on the performance of manually-triggered autocomplete, and if that falls below 100ms, re-enable the live autocomplete.

**Comment by ponelat** [comment]
We have a plugin, that can disable live autocomplete. It doesn't do the timeout thing ( ie: if longer than 200ms, or something ). Its just a config you can toggle with configsActions.toggle('editorLiveAutocomplete'). @shockey ping if you'd like to know MOAR.

**Comment by shockey** [comment]
Implemented 🎉
