### ISSUE TITLE
Open Redirect & Possible XSS - No HTML Encoding

### ISSUE THREAD

**Issue by QuduSEC** [swagger-api/swagger-editor#1312]
If we describe the method as follows (See **description** of operationId "AddPet"):

[https://gist.github.com/QuduSEC/0733bed7b04ee9bda893894a428835a1](https://gist.github.com/QuduSEC/0733bed7b04ee9bda893894a428835a1)

And expand this operation in the UI, then there will be a Redirect to /evil

Testing in Chrome Version 58.0.3029.81 / FF ignores the redirect, but does not render

P.S. Add to the README email to send security bugs privately

**Comment by webron** [comment]
Thanks for the report @QuduSEC. As you suggested, we'll add the email. In general it's just security@swagger.io.

**Comment by shockey** [comment]
This appears to have been solved in https://github.com/swagger-api/swagger-ui/pull/3165 - I can't reproduce it now.

I've added security contact information to the READMEs for UI and Editor.

Closing - thanks @QuduSEC!
