### ISSUE TITLE
Custom auto-complete

### ISSUE THREAD

**Issue by lpalash** [swagger-api/swagger-editor#1317]
I am trying to add auto-complete feature to the Editor for demo project purpose. I would like to have custom auto suggestions plugin for specific context in a swagger file. i.e. I am doing external rest api call to get the list of suggestions and push that to the auto complete list of suggestions inside editor. 
I can retrieve the list from external provider on editor component load, but I need to share the state between components/modules (Editor and autosuggest-apis.js/keyword-helpers.js). 

What is the right approach to get the state (api call response object) to autosuggest plugin?

Thanks!

**Comment by shockey** [comment]
@lpalash, a new interface for making autosuggest plugins just landed in master via https://github.com/swagger-api/swagger-editor/pull/1367.

I'm going to rope in @ponelat, since he contributed the feature. Josh, I think you have a custom autosuggest plugin that's grabbing from a remote server, can you provide some pointers on implementing that?

**Comment by ponelat** [comment]
You can copy one of the autosuggester plugins... here is a skeleton, just drop this into a your list of plugins... you can add state to `system` via actions and reducers. Which will be accessible here.

```javascript
export default function EditorAutosuggestCustomPlugin() {
  return {
    statePlugins: {
      editor: {
        wrapActions: {
          addAutosuggestionCompleters: (ori, system) => (context) => {
            // Remember to concat this onto the existing autocompleters ( assuming you want that )
            return ori(context).concat([{
              getCompletions(editor, session, pos, prefix, cb) {

                // Get path within spec... expensive, be careful 
                const path = system.fn.getPathForPosition({ pos, prefix, editorValue: editor.getValue(), AST: system.fn.AST})

                if(path[0] === 'definitions') {
                  // Cool, we're under definitions
                }

                // Can be async...
                setTimeout(() => {
                  const suggestions = [{
                    score: 100,
                    meta: 'on the right side',
                    snippet: 'this will be added, as-is, with snippet functionality', 
                    caption: 'match on this'
                  }]

                  // Always fire the callback.
                  cb(null, suggestions)

                }, 100)
              }
            }])
          }
        }
      }
    }
  }
}
```

@shockey this is for you too, hopefully something to add to the docs...

**Comment by lpalash** [comment]
Nice. Will pull the latest changes and follow your example.
Thank you both for the support, I am closing the request.
