### ISSUE TITLE
Merging swagger-ui and swagger-editor

### ISSUE THREAD

**Issue by jaydreyer** [swagger-api/swagger-editor#1318]
I see in the 3.0 release notes that I should be able to link my customized swagger-ui into the editor, which would be awesome.

Here's what I've done:
1. Customized swagger-ui locally using plug-ins, etc.
2. Run `npm link` from the swagger-ui folder
3. Installed swagger-editor
4. Ran `npm link swagger-ui` in the swagger-editor folder
5. Ran `npm run build` in swagger-editor folder

I'm not seeing my swagger-ui changes in swagger-editor. I'm assuming I'm missing something, or did the npm link incorrectly. Any ideas?

**Comment by jaydreyer** [comment]
Here's some more info based on what I can find:

It appears the npm link worked - when I look at the node-module folder for swagger editor, there's now basically a link to a swagger-ui folder. Within there are only two js files in a dist folder - swagger-ui.js and swagger-ui.js.map.

This is interesting because when I was working on swagger-ui and fine-tuning the info section, I used all of the .js files EXCEPT swagger-ui in my site. That includes the css. So, swagger-ui-bundle, swagger-ui-standalone-preset, etc.

For fun I copied all of the files in my dist folder from swagger-ui into the linked folder, but it didn't have much effect other than changing the color of the title. The things I added to the info section aren't appearing.

That's all I've been able to figure out so far. My swagger-ui integration into our developer portal looks great, based on the changes I made. I just haven't been able to get those same changes into swagger-editor. I feel like I'm very close, though.

**Comment by shockey** [comment]
Hey @jaydreyer! 

First, I'll say that while I'm excited to see customized uses of the UI and Editor, it would be better if you customized things by passing in plugins to the Editor constructor. You can modify UI and Editor components by doing so!

Beyond that, I see a couple things here:
1. A missing step here is an `npm run build` in your UI directory. Editor's build process uses UI as a module, so it expects something already built, regardless of which UI file you're consuming. Running build in your UI shoud put your changes into UI's `dist` directory.
2. Based on your second message, I'm not 100% sure that the `npm link` took. Take a look at my output below, and use it to compare with what you're seeing:

```
# kyle in ~/swagger/editor on git:master ● [18:56:50]

→ ls ~/swagger/ui/dist
favicon-16x16.png                   oauth2-redirect.html                swagger-ui-standalone-preset.js     swagger-ui.css.map
favicon-32x32.png                   swagger-ui-bundle.js                swagger-ui-standalone-preset.js.map swagger-ui.js
index.html                          swagger-ui-bundle.js.map            swagger-ui.css                      swagger-ui.js.map

→ ls node_modules/swagger-ui 
LICENSE      README.md    dist         node_modules package.json

→ ls node_modules/swagger-ui/dist
swagger-ui.css     swagger-ui.css.map swagger-ui.js      swagger-ui.js.map

→ npm link ../ui
/Users/kyle/.nvm/versions/node/v6.9.0/lib/node_modules/swagger-ui -> /Users/kyle/swagger/ui
/Users/kyle/swagger/editor/node_modules/swagger-ui -> /Users/kyle/.nvm/versions/node/v6.9.0/lib/node_modules/swagger-ui -> /Users/kyle/swagger/ui

→ ls node_modules/swagger-ui     
Dockerfile                        make-webpack-config.js            test
LICENSE                           nginx.conf                        webpack-dist-bundle.config.js
README.md                         node_modules                      webpack-dist-standalone.config.js
build-tools                       package.json                      webpack-dist.config.js
composer.json                     snapcraft.yaml                    webpack-hot-dev-server.config.js
dev-helpers                       src                               webpack-watch.config.js
dist                              swagger-config.yaml               webpack.check.js
docker-run.sh                     swagger-ui-dist-package           webpack.config.js

→ ls ~/swagger/ui/    
Dockerfile                        dist                              snapcraft.yaml                    webpack-dist-standalone.config.js
LICENSE                           docker-run.sh                     src                               webpack-dist.config.js
README.md                         make-webpack-config.js            swagger-config.yaml               webpack-hot-dev-server.config.js
build-tools                       nginx.conf                        swagger-ui-dist-package           webpack-watch.config.js
composer.json                     node_modules                      test                              webpack.check.js
dev-helpers                       package.json                      webpack-dist-bundle.config.js     webpack.config.js
```

Note that I'm using the shortcut for npm link, Cmd+F `You may also shortcut the two steps in one` on the [npm link docs](https://docs.npmjs.com/cli/link) for more info.

The takeaway is that after the link, my `editor/node_modules/swagger-ui` directory mirrors my main UI directory that I linked to, which looks entirely different from the prior folder of dist files.

Hopefully this is helpful. Let me know!

**Comment by jaydreyer** [comment]
Thanks, @shockey!

Well, you were right on the `npm link` not being correct. I re-did that and now mine shows up just like yours. Any changes to swagger-ui on my end are reflected in the node_modules/swagger-ui folder.

I have been doing `npm run build` in both swagger-ui and swagger-editor, so it's not that. I left that out of my steps above, but I've been doing that.

It's still not showing my swagger-ui changes, however. I'm going to give up for tonight and try some more things in the morning.  At least I know the `npm link` is working correctly now.

**Comment by jaydreyer** [comment]
I still can't get the plugin I created for swagger-ui (that shows up in swagger-ui) to appear in swagger-editor. I see it in the npm linked node module, so the code is there. It just doesn't render in editor. Any other suggestions? Maybe a setting somewhere or something?

Also, I want to double check that using swagger-ui 3.0.7 and swagger-editor 3.0.9 should not cause this problem, correct?

**Comment by shockey** [comment]
@jaydreyer, where/how are you pulling your UI plugin into the UI?

[Swagger-Editor passes its own options to the Swagger-UI constructor](https://github.com/swagger-api/swagger-editor/blob/master/src/index.js#L37), which means your plugin may be placed in a spot that executes when Swagger-UI is being run directly, but not as a module.

**Comment by jaydreyer** [comment]
In src/standalone/index.js

```
import StandaloneLayout from "./layout"
import "../style/main.scss"

import TopbarPlugin from "plugins/topbar"
import Info from "plugins/info"

// the Standalone preset

let preset = [
  TopbarPlugin, Info, 
  () => {
    return {
      components: { StandaloneLayout }
    }
  }
]

module.exports = preset
```

**Comment by shockey** [comment]
Yep, so the Standalone preset gets used when you do things like `npm run dev`, or use the `dist/index.html` file - but it is _not_ called when UI is used as a module 😄  There's no way you would've known that, though, because it's not documented yet.

You can either:
1. move your plugin file(s) to your Editor repo, and pass your Info plugin in when you call the Editor constructor function.
2. add your plugin to the UI core [here](https://github.com/swagger-api/swagger-ui/blob/master/src/core/index.js#L38) - i don't suggest this, it may cause pain in the future if you need to update.

**Comment by jaydreyer** [comment]
Great. I went with option #1. That was pretty easy since I had already built it for swagger-ui. Having to keep them in sync will be a nuisance, but not too bad, all things considered.

Thanks again for your help! Now on to custom validation. I just can't make it easy on myself! ;-)

**Comment by shockey** [comment]
Awesome! Good luck 😄 

I'm closing this, feel free to reply if you need it reopened.
