### ISSUE TITLE
Repo commits and editor.swagger.io site

### ISSUE THREAD

**Issue by gsi-delmo** [swagger-api/swagger-editor#1328]
Are commits pushed to the repository (master) automatically deployed on editor.swagger.io site?

**Comment by webron** [comment]
No. There's a manual process that deploys to editor.swagger.io, _and_ we do it only after releases - so what's deployed is not `master` but a tagged version. 

At the moment, we make a release every Friday, so the delay in fixes isn't that long.

**Comment by gsi-delmo** [comment]
thx!
