### ISSUE TITLE
Support file Drag&Drop

### ISSUE THREAD

**Issue by haizaar** [swagger-api/swagger-editor#1330]
In version 2 of the editor I could drag & drop a file from explorer (or Ubuntu Nautilus) into editor's browser window.
This is a very handy feature for my workflow, since I prefer to write yamls in a dedicated text editor (vim) and validate them in the swagger editor. Validation usually takes several tries and drag&drop makes importing a breeze - much faster than through Import menu of swagger editor.

It will be great to see this feature back in the new swagger editor.

**Comment by rrberry** [comment]
Yes, this was a big step backward in usability. I use a similar workflow and rely on the editor for validation. Please support drag and drop!

**Comment by webron** [comment]
We're not dismissing the benefits of this feature, but we just don't have the capacity to implement it. If anyone wants to give a fix a go, and submit a PR, we'll be sure to review it as soon as possible.
