### ISSUE TITLE
Link to error line

### ISSUE THREAD

**Issue by haizaar** [swagger-api/swagger-editor#1331]
In swagger editor 2.x, errors contained a link that scrolled editor to the problematic line number. In version 3.x we just have an error messages. When you have 2k+ lines file it's quite a hindrance.

2.0:
![image](https://cloud.githubusercontent.com/assets/58201/26052056/eacab6c8-396c-11e7-98af-e46fc1cba737.png)

3.0:
![image](https://cloud.githubusercontent.com/assets/58201/26052076/f83991f8-396c-11e7-92b0-d873c2b7a98f.png)

**Comment by webron** [comment]
They're gone again, @shockey. Gone again.

**Comment by shockey** [comment]
Fixed by https://github.com/swagger-api/swagger-ui/pull/3106.

Fixes will be released Friday 🎉
