### ISSUE TITLE
Invalid JSON is valid Swagger

### ISSUE THREAD

**Issue by g-may** [swagger-api/swagger-editor#1339]
This happens at least in the cases shown here. I found this because I had left a comma on the final element of an array.
![image](https://cloud.githubusercontent.com/assets/8353836/26382559/0a344f9e-3ffb-11e7-9c03-da2ae544045e.png)

There should be an error thrown for invalid JSON:
![image](https://cloud.githubusercontent.com/assets/8353836/26382487/847a3300-3ffa-11e7-8f6b-416011409b03.png)

**Comment by fehguy** [comment]
well the editor is yaml-only.  So the whole thing should be marked as invalid!!!  Switch to YAML, please.
