### ISSUE TITLE
Documentation for swagger-editor 3?

### ISSUE THREAD

**Issue by moon0326** [swagger-api/swagger-editor#1345]
Hi,

I'm trying to use swagger-editor with a backend to save changes back to file to avoid copy/paste or downloading the content as json or yaml.

I could do it with swagger-editor 2 by looking at https://github.com/swagger-api/swagger-node/blob/master/lib/commands/project/swagger_editor.js

Is there a way to do the same in swagger-editor 3?

**Comment by webron** [comment]
This is a duplicate of #1241 - but currently we have no immediate plans on implementing it.

**Comment by moon0326** [comment]
Thank you Ron.
