### ISSUE TITLE
Semantic error for "type: file" Parameters and proper "consumes"

### ISSUE THREAD

**Issue by nicolo-scarpa-freelands-it** [swagger-api/swagger-editor#1347]
Even if the API-wide "consumes" has "multipart/form-data", semantic errors are being shown for Endpoints and Operations with "type: file" parameters. 

> **Semantic error at paths./files.parameters.0**
Operations with Parameters of "type: file" must include "multipart/form-data" in their "consumes" property

> **Semantic error at paths./files.post.parameters.0**
Operations with Parameters of "type: file" must include "multipart/form-data" in their "consumes" property

See [swagger.yaml.zip](https://github.com/swagger-api/swagger-editor/files/1041788/swagger.yaml.zip).

**Comment by shockey** [comment]
Fixed in #1517 😄
