### ISSUE TITLE
Swagger editor v3 description key has a XSS vulnerability

### ISSUE THREAD

**Issue by amrtgaber** [swagger-api/swagger-editor#1348]
## Swagger-ui version
3.x
 
## Vulnerability details
The description field is not guarded against arbitrary javascript execution. Any YAML file can trigger the vulnerability, whether it's imported from url or copied and pasted directly in the editor. Here is an example YAML file that does so:
 
```YAML
swagger: '2.0'
info:
  version: "0.0.1"
  title: Example Title
  description: <img src=x onerror="alert('all your base are belong to us')">
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
```
 
## Security risk
This opens a vector for general [cross-site scripting attacks](https://www.owasp.org/index.php/Cross-site_Scripting_%28XSS%29) that easily expose sensitive information which can be remotely shared with the attacker (among several other types of risks).
 
## Notes
I tested this vulnerability on http://editor.swagger.io/# by copying and pasting the above YAML file and saw the alert pop up. I hope this helps, let me know if I made a mistake. Also, seems Swagger editor version 2 had to contend with a similar issue: #908.

**Comment by attritionorg** [comment]
Looks like http://seclists.org/bugtraq/2016/May/15 on first glance, which was apparently fixed in the past.

**Comment by webron** [comment]
Thanks for reporting. This is an issue with swagger-ui. Moving there for further treatment.

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger-ui#3163
