### ISSUE TITLE
Using Swagger-Editor 3 offline

### ISSUE THREAD

**Issue by yuricamara** [swagger-api/swagger-editor#1350]
Hi,

I would like to use it in my computer as I did with a previous version.  I downloaded it but I could use only with PetStore example.

Could it be possible?

**Comment by webron** [comment]
There's no difference. You can use it offline just as before. Not sure what's missing for you. You can edit any spec in it.

**Comment by shockey** [comment]
I'm able to open Swagger-Editor locally without an internet connection - everything except the Generate menu works, since that requires talking to the generator.swagger.io API.

What's not working for you?

**Comment by yuricamara** [comment]
Sorry! My fault. It works now.
