### ISSUE TITLE
JSON imported from URL is not converted to YAML

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-editor#1354]
swaggerEditor: "3.0.10/gb2e3da6-dirty", swaggerUi: "3.0.9/ga068f78"

When we use "File > Import URL" to import any JSON spec, e.g. http://petstore.swagger.io/v2/swagger.json, the spec is imported as JSON.

Expected result: The spec is auto-converted to YAML, like in Editor v2.

**Comment by webron** [comment]
@hkosova Thanks for reporting, I'd noticed that too.
