### ISSUE TITLE
Tag Object description not respecting multi-line literals in swagger-editor

### ISSUE THREAD

**Issue by derekdecesare** [swagger-api/swagger-editor#1356]
We cannot incorporate line breaks into the description field for tags.  All other description fields respect markdown and multi-line literals.  This is really hampering readability of our tags for the APIs.

Example:

tags:
  - name: item
    description: | 
      To Do - Create a tag for each resource in your api and tag the operations that relate to that resource. 
      Provide the documentation for the resource in the description of the tag.  
      The following views are supported by this resource. 
      - complete, includes all fields.
      - summary, includes only id, descriptor, name and description. 
      - otherView, includes only id, primaryCategory and secondaryCategories.

**Comment by webron** [comment]
Moving this to swagger-ui as this is a rendering issue.

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger-ui#3208
