### ISSUE TITLE
Specify multiple response reasons

### ISSUE THREAD

**Issue by grosch** [swagger-api/swagger-editor#1359]
My method can return a 412 if no properties are passed in (technically they're all optional but you gotta pass in at least one), OR if the passed in property failed to parse.   So my normal response is like so:

    responses:
      '204':
        description: The Calendar event was updated.
      '412':
        $ref: '#/responses/NoPatchParameters'

How do I now show that there's also another reason to return a 412, with a different description than the one from that ref?

**Comment by webron** [comment]
You can't. The spec only allows you to describe one data type/description per response.

**Comment by grosch** [comment]
Seems pretty limiting.  Methods frequently will throw an exception for a number of reasons.  So I'm limited to just saying "Something failed"?  That's kinda bad.

**Comment by webron** [comment]
The next version of the spec will allow more flexibility. However, if you depend on the http error code as the differentiator, defining multiple potential responses won't help other than documentation, for which you can use the description field now anyway.
