### ISSUE TITLE
Define custom type formats

### ISSUE THREAD

**Issue by grosch** [swagger-api/swagger-editor#1360]
Is there any way to specify a custom type?  A large number of my parameters are a UUID and I'm not seeing anything explicit for that.  I'd like to somehow define a UUID format for string where it also knows a default example value for a UUID.

I'd like to do something like:

    CustomType:
      uuid:
        parentType: string
        examples: 
          application/json: "71b4702f-ed9f-48f6-b77f-d4dda03ea01b"

**Comment by hkosova** [comment]
Some tools support `format: uuid`:
```
type: string
format: uuid
```
[`format`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types) is an open-valued property so you can specify any `format` provided that the tools support that. See also https://github.com/OAI/OpenAPI-Specification/issues/607#issuecomment-200441431.
