### ISSUE TITLE
Swagger 2.0 does not support null types

### ISSUE THREAD

**Issue by grosch** [swagger-api/swagger-editor#1364]
I'm getting the below error.  Pointing to issue 229 isn't so helpful any longer as it's HUGE.  I ended up discovering the issue was that I had "example: null" on one of my properties.  Ignoring you should absolutely support that, can you fix this so it tells us what line or what object the issue came from?

resolver.js:842 Uncaught TypeError: Swagger 2.0 does not support null types ([object Object]).  See https://github.com/swagger-api/swagger-spec/issues/229.
    at module.exports.Resolver.resolveAllOf (resolver.js:842)
    at module.exports.Resolver.resolveAllOf (resolver.js:845)
    at module.exports.Resolver.resolveAllOf (resolver.js:845)
    at module.exports.Resolver.resolveAllOf (resolver.js:845)
    at module.exports.Resolver.finish (resolver.js:508)
    at resolver.js:329
    at module.exports.Resolver.resolve (resolver.js:413)
    at response (client.js:239)
    at responseInterceptor (http.js:79)
    at obj.on.response (http.js:98)
Resolver.resolveAllOf	@	resolver.js:842
Resolver.resolveAllOf	@	resolver.js:845
Resolver.resolveAllOf	@	resolver.js:845
Resolver.resolveAllOf	@	resolver.js:845
Resolver.finish	@	resolver.js:508
(anonymous)	@	resolver.js:329
Resolver.resolve	@	resolver.js:413
response	@	client.js:239
responseInterceptor	@	http.js:79
obj.on.response	@	http.js:98
(anonymous)	@	http.js:362
Request.callback	@	client.js:692
(anonymous)	@	client.js:514
Emitter.emit	@	index.js:133
xhr.onreadystatechange	@	client.js:772
﻿

​

**Comment by webron** [comment]
2.0 will never support `null` as it's fixed. 3.0 of the spec already added support for it, and we'll enable it as we develop 3.0 compliance.

As for the validation itself, that's something we can take care of, but not the highest priority at the moment.

**Comment by LasneF** [comment]
what about closing this ticket , as soon as you mention it is not part of the spec .

**Comment by jsamr** [comment]
@webron I think that ticket should be closed.
