### ISSUE TITLE
Remove instance methods, not supported by IE11

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-editor#1370]
In order to depend on the upcoming swagger-ui release, which removes babel-polyfill. We need to ensure swagger-editor does not implicictly rely on instance method ( which won't be supported with the new babel-plugin-transform-runtime ).

Quick look shows me at least `[].findIndex`. I don't think it'll be much more than that.

Related to https://github.com/swagger-api/swagger-ui/pull/2959

**Comment by shockey** [comment]
There's a few `Object.values` references as well: https://github.com/swagger-api/swagger-editor/search?utf8=%E2%9C%93&q=%22Object.values%22&type=

**Comment by ponelat** [comment]
yeah... but I don't think their instance methods. They should be static members of `Object`. Not sure about them...

**Comment by shockey** [comment]
@ponelat you're right, but `Object.values` is an ES2017 feature (currently in [stage 4](https://github.com/tc39/proposal-object-values-entries)).

> Automatically requires babel-runtime/core-js and maps ES6 static methods and built-ins.
>
> [transform-runtime docs](https://babeljs.io/docs/plugins/transform-runtime/#technical-details)

Sounds like `Object.values` may not be covered by transform-runtime.

**Comment by ponelat** [comment]
aha!
So we can either import it ourselves via core-js, or just use lodash :grimacing:

**Comment by shockey** [comment]
Everything seems to be working well since I merged https://github.com/swagger-api/swagger-editor/pull/1386.

Closing 👍
