### ISSUE TITLE
Babel-polyfill error

### ISSUE THREAD

**Issue by jaydreyer** [swagger-api/swagger-editor#1373]
My site is using both swagger-ui and trying to use swagger-editor. The swagger-ui piece is working fine, but when I go to the editor page, I get an error saying "only one instance of babel-polyfill is allowed".

The page I'm calling is using swagger-editor-bundle.js. Running it via `npm run dev` works fine, but adding it to my site (angular, btw) causes the error.

Any suggestions?

**Comment by jaydreyer** [comment]
Just to add a bit more info, it's definitely due to both running. Here is a section of my index.html:
```
  <script src="components/swagger-ui/swagger-ui-bundle.js"></script>
  <script src="components/swagger-ui/swagger-ui-standalone-preset.js"></script>
  <script src="components/swagger-editor/swagger-editor-bundle.js"></script>
```
If I comment out or remove the swagger-ui ones, swagger-editor works. If I move the swagger-editor line above the swagger-ui ones, the swagger-ui ones return the babel-polyfill error.

**Comment by ponelat** [comment]
Yeah for some reason babel-polyfill is only allowed once on the page. It adds polyfills like Promise, Set, etc.

Anywho, they don't seem to be fixing/changing that in babel-polyfill, so we're currently moving to use the recommended approach of using babel-plugin-transform-runtime. 

You can follow that over here https://github.com/swagger-api/swagger-ui/pull/2959 - its being actively worked on, so given a couple of days, it might get merged - and this issue will likely just _disappear_. ( we live in hope :) )

In the meantime, if you're using a bundler (browserify, rollup, webpack, etc ) you don't need to include the whole swagger-editor-bundle, you just need the plugins it exports.
See https://github.com/swagger-api/swagger-editor/blob/master/src/index.js for what its actully doing under the hood. Ie: swagger-editor is just a few plugins on top of swagger-ui.

**Comment by shockey** [comment]
Just merged https://github.com/swagger-api/swagger-ui/pull/2959 😄

**Comment by ponelat** [comment]
Still need to ensure swagger-editor works, and cut a release ( likely end of week ).
But we're on track! :grin:

**Comment by jaydreyer** [comment]
Cool. I'll hold off until the releases are updated.

**Comment by shockey** [comment]
@jaydreyer, you should be able to use Swagger-Editor without any babel-polyfill issues now.

Let us know if you're having any lingering issues.

Thanks for the report!
