### ISSUE TITLE
OPENAPI Problem 

### ISSUE THREAD

**Issue by dipak84patel** [swagger-api/swagger-editor#1374]
I am having problem with my OPENAPI spec file. I am trying to call an exposed url to 'GET' an id but every time i port forward the service to my local and then try to send request through API document my connection is refused. I would appreciate any help. The id that i am expecting would be in JSON format. Below is my spec file -

`openapi: "3.0.0"
info:
  version: 1.0.0
  title:  Id Generator
servers:
 url: http://www.someurl.com
paths:
  /posts:
    get:
      summary: Get Id
      operationId: id
      tags:
        - posts
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
              $ref: "#/definition/Post"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
              $ref: "#/definition/Error"

definition:
    Post:
    type: object 
    properties:
        id:
          type: string
    Error:
      properties:
        id:
          type: string
         

`

Since i am pasting my yaml file it might not be indented properly. But i am not getting any indentation error in visual studio code.

**Comment by webron** [comment]
We do not support OpenAPI 3.0.0 yet. It's not even released.
