### ISSUE TITLE
CORS "Learn more" link leads to 404

### ISSUE THREAD

**Issue by code-surfer** [swagger-api/swagger-editor#1377]
In the freshly installed swagger editor started from a freshly created project, the "Learn more" link in the "This is a cross-origin call. [...]" line points to https://github.com/swagger-api/swagger-editor/blob/master/docs/cors.md
This gets me to a 404 page.
`swagger -V` outputs 0.7.5

**Comment by webron** [comment]
See #1261.

**Comment by code-surfer** [comment]
Okay, I checked for a prior report for this bug, but I only saw the open issues...

**Comment by eastwoodwang** [comment]
upgrade to 3.x and the CORS issue is fiexed, thanks a lot.
