### ISSUE TITLE
Code generation is not working

### ISSUE THREAD

**Issue by gerasimos** [swagger-api/swagger-editor#1378]
Hello,

I am trying both the live editor.swagger.io and the latest docker image. In both cases, when I select "Generate Server" or "Generate Client", nothing happens (docker runs on OSX).

Thanks,
gerasimos

**Comment by webron** [comment]
The online one works for me. Which browser+version do you use?
Can you share the API definition you have?

**Comment by gerasimos** [comment]
Hello,

I am using latest Safari on OSX. It's not a matter of API definition, as I am trying with the pet sample,

**Comment by gerasimos** [comment]
The problem is in Safari. It works in Firefox.

**Comment by mugbya** [comment]
newest
Code generation server is not working  on https://editor.swagger.io/ , but It's ok  on https://editor2.swagger.io/
