### ISSUE TITLE
Delay in errors being shown.

### ISSUE THREAD

**Issue by hemikak** [swagger-api/swagger-editor#1379]
Hi, 

Currently when editing in the ace editor, if we update the YAML text and make a mistake, the annotations on the editor takes 1200 milliseconds to show in the gutter[1]. 

Is it possible to remove this delay ?

Or is there a function to provide an YAML swagger or a JSON swagger text and check if it has errors ?

I have the swagger editor instance with me.
`this._swaggerEditor = SwaggerEditorBundle({
            dom_id: `#${swaggerElementID}`,
        });`

[1] - https://github.com/swagger-api/swagger-editor/blob/master/src/plugins/validation/helpers.js#L42

Regards,
Hemika

**Comment by webron** [comment]
There's always going to be a trade off when it comes to performance vs the time errors are displayed. Lowering the delay would work for smaller definitions, not so much for larger ones.

**Comment by hemikak** [comment]
@webron Agreed!, My main concern is to find errors when the YAML is modified. Was thinking of using the ace editor annotation to check for errors.

is there a function to provide an YAML swagger or a JSON swagger text and check if it has errors ?

I have the swagger editor instance with me.
this._swaggerEditor = SwaggerEditorBundle({ dom_id:#${swaggerElementID}, });

**Comment by shockey** [comment]
Hi @hemikak!

> Currently when editing in the ace editor, if we update the YAML text and make a mistake, the annotations on the editor takes 1200 milliseconds to show in the gutter. Is it possible to remove this delay ?

It's not currently. I'd be open to adding an Editor setting for this, but for the moment it's always 1200ms. Pull requests are welcome 😄 

> is there a function to provide an YAML swagger or a JSON swagger text and check if it has errors?

You can't attach to the validation system that's built into the Editor, directly. 

However, you may want to check out the Swagger Validator Badge service: https://github.com/swagger-api/validator-badge

You can send your spec to the service's `/validator/debug` endpoint and get back validation information about your spec, It's not the same validation system that powers the Editor, but the two validation systems cover a lot of the same cases.

Let me know if this helps. Thanks for using Swagger!

**Comment by hemikak** [comment]
Hi @shockey ,,

Thanks for the information.

Regards,
Hemika
