### ISSUE TITLE
Setting the 'example' key in a path parameter works but triggers a schema validation error

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-editor#1382]
_From @RoyHP on May 29, 2017 2:53_

The 'example' key works just fine on body parameters and also works on path parameters. But when used on a path parameter, it shows a schema validation error at the top

(because "example" key is missing on pathParameterSubSchema from OpenAPI? https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v2.0/schema.json#L810).

But if it's going to be supported for body parameters without generating an error, it should do the same for path parameters, no?

![screen shot 2017-05-28 at 10 54 23 pm](https://cloud.githubusercontent.com/assets/1066439/26535154/ad5075c6-43f8-11e7-8c5d-faa47c565d7d.png)
```json
"parameters": [{
	"name": "taskId",
	"in": "path",
	"required": true,
	"type": "string",
	"example": "592b435cc139ec01009aa1e6"
}],
```
![screen shot 2017-05-28 at 10 59 13 pm](https://cloud.githubusercontent.com/assets/1066439/26535213/500b8544-43f9-11e7-8aaf-2758f3cceb3f.png)

_Copied from original issue: swagger-api/swagger-ui#3145_

**Comment by webron** [comment]
@RoyHP are you seeing the validation error when using swagger-ui directly or when using swagger-editor?

**Comment by webron** [comment]
_From @RoyHP on June 27, 2017 16:22_

@webron I see this on the online editor [http://editor.swagger.io/](http://editor.swagger.io/)

**Comment by webron** [comment]
Not sure why I moved the ticket here, but... 

@RoyHP - the 2.0 spec doesn't support examples for non-body parameters.

**Comment by shockey** [comment]
This sounds invalid/wontfix? Closing.
