### ISSUE TITLE
Unable to print full page

### ISSUE THREAD

**Issue by cproof** [swagger-api/swagger-editor#1383]
Hi,

the new Swagger Editor version is great, we're using it at our organisation to design a new interface specification in the OpenAPI standard.

However, since we're using only OpenAPI für both the technical documentation as well as the process documentation, we need to be able to print the result to distribute it to the non-technical members.

Unfortunately, bug #594 seems to have reverted with the 3.0 release, as only the first page is shown. Additionally, since it is not possible to adjust the proportions of the editor/the html, it is not possible print only the resulting html as suggested in https://stackoverflow.com/a/41257222

Is there a workaround, or will this be fixed in the upcoming version?
Is there some sort of print-stylesheet that one can adjust?
Is there a way to export the resulting HTML (including styling?)

Attached you find a screenshot of the problem (print preview in Chrome)

![printing_openapi](https://user-images.githubusercontent.com/4948782/27640110-a016ad98-5c18-11e7-896b-5cc924015d1c.PNG)

**Comment by webron** [comment]
Now that swagger-editor is based on swagger-ui, this is an unimplemented feature in swagger-ui. You can follow up on the request [here](https://github.com/swagger-api/swagger-ui/issues/2756). That said, at the moment, it will not be included unless there's a community contribution as it's not high on our priorities.

**Comment by cproof** [comment]
Thank you for referring me to the swagger-ui issue, I will try to contribute there.

However, the described problem that only one page is printed and that the html preview and the editor area are sharing the page seems to be a swagger-editor related problem.

**Comment by cproof** [comment]
Adding this code to the ```<head>``` fixes the problem (tested in current versions of Firefox and Chrome).

```html
<style media="print">
.SplitPane {
	position: relative !important;
	display: block !important;
}

.Pane1, .topbar {
	display: none;
}

.Pane2 {
	overflow-y: auto;
	width: 100% !important;
}
</style>
```

This is a bit of a "hack", but works fine for me.
