### ISSUE TITLE
Unencoded Chars in the Parameters Description Field are not handled correctly

### ISSUE THREAD

**Issue by pjm16** [swagger-api/swagger-editor#1385]
Hi, I parsed a message (attached doc.txt) with <> chars in the parameter description field. The description field is cut short at the first char.

If I use encoding (EncodedDoc.txt) eg &gt; then the parameters field parses fine. It even converts them back to <> chars.

Both versions work in the 2.10.5 build

[Doc.txt](https://github.com/swagger-api/swagger-editor/files/1109828/Doc.txt)
[EncodedDoc.txt](https://github.com/swagger-api/swagger-editor/files/1109829/EncodedDoc.txt)

![image](https://user-images.githubusercontent.com/29760363/27654932-94879d36-5c11-11e7-9aed-40ba232d8d90.png)

**Comment by webron** [comment]
It's actually handled correctly. Description fields use markdown, which means that the `<script>` portion is treated as HTML, specifically, an opening tag. You'd need to escape it in order for it to render properly.

**Comment by pjm16** [comment]
hi Webron thanks for your response. I hadn't considered we were rendering HTML rather than plain text.  We'll escape our descriptions as you've suggested

**Comment by webron** [comment]
No problem. Please reopen if there's still an issue.
