### ISSUE TITLE
I got some error when run npm i

### ISSUE THREAD

**Issue by wenkchan** [swagger-api/swagger-editor#1389]
1712 silly fetchPackageMetaData                                                                      ^
1713 warn optional SKIPPING OPTIONAL DEPENDENCY: webpack-dev-server@1.14.0 (node_modules/webpack-dev-server):
1714 warn optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of input at 1:83600
1714 warn optional SKIPPING OPTIONAL DEPENDENCY: :"^2.0.0-beta5","pug-loader":"^2.3.0","should":"^11.1.0","sinon":"^1.
1714 warn optional SKIPPING OPTIONAL DEPENDENCY:                                                                      ^
1715 verbose stack SyntaxError: Unexpected end of input at 1:3970
1715 verbose stack loose-envify":"^1.1.0","object-assign":"^4.1.0","prop-types":"^15.5.6
1715 verbose stack                                                                      ^
1715 verbose stack     at SyntaxError (native)
1715 verbose stack     at Object.parseJSON (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/node_modules/jju/lib/parse.js:745:13)
1715 verbose stack     at parse (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/index.js:10:13)
1715 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
1715 verbose stack     at process._tickCallback (internal/process/next_tick.js:109:7)
1716 verbose cwd /Users/Wenk.Chan/Java/swagger-editor-3.0.13
1717 verbose Darwin 16.3.0
1718 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
1719 verbose node v6.11.0
1720 verbose npm  v5.0.4
1721 error Unexpected end of input at 1:3970
1721 error loose-envify":"^1.1.0","object-assign":"^4.1.0","prop-types":"^15.5.6
1721 error

**Comment by shockey** [comment]
@wenkchan, I need the following info:

- Your OS
- Your `node -v`
- Your `npm -v`

Thanks!

**Comment by fvillanueva** [comment]
- Install latest Node version, npm including in Node

- Execute in CLI  or Mac or Windows or Linux `npm start`
:+1:

**Comment by shockey** [comment]
@fvillanueva, are you having this problem as well? If so, I'd appreciate you providing your exact Node/npm versions and OS you're using as well.

**Comment by fvillanueva** [comment]
i am use :

- Node `node  v8.1.2`

- Npm ` npm 5.0.3`
When executed swagger, I don´t have problem, we are use swagger local server on Windows (7 , +) and other developer´s execute for macOS, the unic problem was the proxy. and after other changes on Swagger for adapted, for Hierarchies for REST services oriented SOA, like Rest services for task, utilitaries, entities.

**Comment by shockey** [comment]
@fvillanueva, I'm a bit confused - are you saying you don't have a problem running the project now? Can this issue be closed?

**Comment by shockey** [comment]
@wenkchan, are you still having issues? Still need some more information from you.

**Comment by wenkchan** [comment]
sorry, I am busy lately.miss the notification. already solve it ,thanks

**Comment by webron** [comment]
Thanks for the update.
