### ISSUE TITLE
Inherited model name and description ignored in the documentation

### ISSUE THREAD

**Issue by prakashguru** [swagger-api/swagger-editor#1392]
I have a yaml definition where a model "OrderEx" inherited using allOf from "Order". And the OrderEx is used as model for an api. The problem is the documentation shows name and description of the Order model (base) instead of OrderEx. 

![image](https://user-images.githubusercontent.com/11089125/27866511-4736750e-61b4-11e7-821e-a1be90ef25a1.png)

Am I doing something wrong? The yaml definition attached.

[buggy.txt](https://github.com/swagger-api/swagger-editor/files/1124767/buggy.txt)

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger-ui#3342
