### ISSUE TITLE
Schema error for valid YAML - upload multiple files

### ISSUE THREAD

**Issue by naXa777** [swagger-api/swagger-editor#1393]
My Spring controller accepts a list of files as parameter. This **valid** YAML is converted from JSON generated by [SpringFox ](http://springfox.github.io/springfox/) from the Spring controller:

```
paths:
  /test/user/demoIssue:
    post:
      tags:
        - test-controller
      summary: Schema error demo
      operationId: schemaErrorDemoUsingPOST
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: files
          in: formData
          description: file attachments
          required: false
          type: array
          items:
            type: file
          collectionFormat: multi
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response'
```

And when pasted to [online swagger editor](http://editor.swagger.io/) it gives me schema error:

> Schema error at paths./test/user/demoIssue.post.parameters[0]
> is not exactly one from <#/definitions/parameter>,<#/definitions/jsonReference>

If I change `file` to `string` the error is gone, so I suppose it's somehow connected to these lines:
```
          items:
            type: file
```

**Comment by webron** [comment]
It's a valid YAML, it's not a valid API definition. You can't have an array of files, it's not supported by the spec.
