### ISSUE TITLE
Show a better error when paths are not formatted correctly

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-editor#1394]
In the editor, we currently show this error message when a path does not start with a `/`:

![image](https://user-images.githubusercontent.com/249413/27921800-ce26bc3a-622d-11e7-8ae0-bfec0bea1c02.png)

This can be reproduced by any simple definition, like such:

![image](https://user-images.githubusercontent.com/249413/27921828-df30214c-622d-11e7-91fd-5db8566525af.png)

Since we know exactly what is wrong in this case, it would be much better for end users if we told them that the path didn't follow the expected structure, which begins with a `/`.

**Comment by shockey** [comment]
Easy fix, but I'm holding on this pending #1517, which should be merged this week.

**Comment by shockey** [comment]
A sample definition for this:

```yaml
openapi: "3.0.0"
info:
  version: "#1394"
  title: "bug #1394"
paths:
  myPath:
    get:
      responses:
        '200':
          description: OK
```

**Comment by shockey** [comment]
I've opened a pull request (#1985) that will close this issue.

Here's what Swagger Editor reports with my changes:

```
Structural error at paths
should only have path names that start with `/`
```
