### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by chenliping972385283** [swagger-api/swagger-editor#1397]
Hey,i occured a proplem ,that says:
      Fetch API cannot load http://localhost:8888/clpssh/register/addUser.do. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://xxxx:3001' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
I can linked my local Idea ,but when response values,that encounter this problem.
the following is my *.yaml
swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8888"
basePath: "/clpssh"
tags:
- name: "register"
  description: ""
  externalDocs:
    description: ""
    url: "http://localhost:8888"
schemes:
- "http"
paths:
   /register/addUser.do:
    post:
      tags:
      - "register"
      summary: "Create user"
      description: "This can only be done by the logged in user."
      operationId: "createUser"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "formData"
        name: "username"
        description: "Created user object"
        required: true
        type: "string"
      - in: "formData"
        name: "password"
        description: "Created user object"
        required: true
        type: "string"
      responses:
        default:
          description: "successful operation"
        200:
          description: "successful operation"
          schema: "#/definitions/ApiResponse"
definitions:
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      data:
        type: "object"
      message:
        type: "string"

and server response 

Code | Details
-- | --
Undocumented | TypeError: Failed to fetch

what should i set other variable?thanks.

**Comment by chenliping972385283** [comment]
i have resolved。

**Comment by lavenpillay** [comment]
Hi. How was this resolved ?

**Comment by xiaonizi-github** [comment]
@lavenpillay   set the request's mode to 'no-cors' to fetch the resource with CORS disabled. i change the code in my project.

**Comment by lavenpillay** [comment]
@xiaonizi-github Great, thanks !
非常感谢你

**Comment by marcocamacho** [comment]
@xiaonizi-github and @lavenpillay , where did you set the 'no-cors' (what file)?

**Comment by kritika0205** [comment]
Hi @xiaonizi-github  where did you set the "no-cors"? Please help I am getting unable to fetch whenever I try to execute the API in swagger UI OAS 3.0.0

**Comment by lavenpillay** [comment]
@kritika0205 
Hi there,

1. CORS cannot easily be "disabled" for security reasons. Under certain conditions, CORS will be in use.
Read this to understand when you can leave it out (basically when FE and BE are on same server):
https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/cors.md

2. If you are also coding the REST services, then you can do something along the lines of this (this is from an ExpressJS app):
_Note : This allows all incoming requests from any domain, so if your needs require more security, restrict this to both (a) Individual endpoints, and allowing only trusted API Consumer domains._
```
app.use(function (req, res, next) {
		res.header("Access-Control-Allow-Origin", "*");
		res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
		next();
	});
```
