### ISSUE TITLE
Using reserved swagger keywords as property name. 

### ISSUE THREAD

**Issue by vkrisju12096** [swagger-api/swagger-editor#1400]
When am trying to use the reserved keyword **properties** as a property name in the Animal model, UI doesn't show anything about the properties. Below you can find swagger as well as Output UI also.

<img width="415" alt="screen shot 2017-07-12 at 2 03 16 pm" src="https://user-images.githubusercontent.com/26120576/28132482-edd74130-670a-11e7-8c73-6b6fb4267bed.png">

****      
UI:
****
<img width="356" alt="screen shot 2017-07-12 at 1 48 48 pm" src="https://user-images.githubusercontent.com/26120576/28131743-dee6aa28-6708-11e7-9bef-e7c608a9f9cc.png">

But if I change that Animal model property name properties to some other name like prop. Then it is working.

<img width="313" alt="screen shot 2017-07-12 at 2 04 43 pm" src="https://user-images.githubusercontent.com/26120576/28132533-1b0e2768-670b-11e7-90b1-2dcf8d5f680b.png">

<img width="351" alt="screen shot 2017-07-12 at 1 59 40 pm" src="https://user-images.githubusercontent.com/26120576/28132289-5f889bfe-670a-11e7-9665-ee38e10b253b.png">

But I want to use property name as properties only.....
_Any Suggestions???_

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger-ui#3376
