### ISSUE TITLE
the online validator doesn't give the exactly results.

### ISSUE THREAD

**Issue by wy65701436** [swagger-api/swagger-editor#1406]
Can somebody help on this issue?

https://github.com/swagger-api/validator-badge/issues/112

**Comment by webron** [comment]
Please don't cross-post issues, it just makes our lives more difficult.

The issue is with the online validator, the editor validation is correct. You have duplicate paths. Move the operations under the same path and you'd be good.

**Comment by wy65701436** [comment]
Thanks for your response.  I do can modify my swagger file manually to make it good per the error shows in editor.

But I need an automatic way to validate and raise the error rather than I verify it in the editor manually. 

Is it an bug of online validator? If so, could you point me where to post the issue?

**Comment by webron** [comment]
It is a bug in the online validator and you already filed a ticket there.
