### ISSUE TITLE
{"code":1,"type":"error","message":"Unable to build target: Could not generate api file for 'PartsOrder'"}

### ISSUE THREAD

**Issue by jemprince** [swagger-api/swagger-editor#1408]
[codegen.txt](https://github.com/swagger-api/swagger-editor/files/1155271/codegen.txt)

**Comment by jemprince** [comment]
Getting this now on all our swagger codegens..
[codegen2.txt](https://github.com/swagger-api/swagger-editor/files/1155893/codegen2.txt)

{"code":1,"type":"error","message":"Unable to build target: Could not generate api file for 'Default'"}

**Comment by jemprince** [comment]
didn't mean to close that!!

**Comment by rgmills** [comment]
@jemprince This is the same as https://github.com/swagger-api/swagger-codegen/issues/6098 

```
{
            "name": "partNumbers",
            "in": "body",
            "required": true,
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
```

**Comment by webron** [comment]
This is not an issue with the editor. Please file the ticket on the codegen.
