### ISSUE TITLE
First letter of keywords gets duplicated sometimes (ft/oas3)

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-editor#1414]
Version: `ft/oas3` branch, rebuilt manually
Chrome 59 on Windows 7

During input, the first letter of keys and values gets duplicated sometimes -- see the GIF below.

I'm typing `example` for a parameter. The first time, when the path is `/`, everything's OK (no duplicate characters). Then I change the path to `/foo` and type `example` again - and it's entered as `eexam...`

![duplicate-characters](https://user-images.githubusercontent.com/8576823/28460460-dd6929a0-6e1a-11e7-9334-4a31cdf59fe0.gif)

Spec:
```
openapi: 3.0.0
info:
  version: 0.0.0
  title: test

paths:
  /:
    post:
      parameters:
        - in: query
          name: foo
          schema:
            type: boolean
      responses:
        '200':
          description: OK
```

@shockey

**Comment by webron** [comment]
I've seen the issue with the current editor as well, just don't know how to reproduce it.

**Comment by iget-master** [comment]
I'm experiencing this issue too. I was not able to found how to reproduce.

Not sure if it will reproduce everytime, but if I do this:

- Insert some idented text "abc"
- Select "abc" then delete it using backspace
- Type "a" goes fine
- Type "b", the "a" will be repeated, then b will be inserted. The text will look like: "aab"

**Comment by PachowStudios** [comment]
Happens to me anytime I try to type a $ref.

Now I have to type it out in notepad, then paste back to the editor...

**Comment by 0xkalle** [comment]
Also happens to me everytime I type a word. Not only the keywords also the values.

Getting
```
Uncaught TypeError: t.startsWith is not a function
    at i (swagger-editor-bundle.js:1814)
    at swagger-editor-bundle.js:1814
    at o (swagger-editor-bundle.js:1814)
    at i (swagger-editor-bundle.js:124586)
    at getCompletions (swagger-editor-bundle.js:127493)
    at Object.e.getCompletions (swagger-editor-bundle.js:124586)
    at swagger-editor-bundle.js:122410
    at Array.forEach (<anonymous>)
    at c.gatherCompletions (swagger-editor-bundle.js:122410)
    at c.updateCompletions (swagger-editor-bundle.js:122410)
```
using `Chrome Version 61.0.3163.100 (Offizieller Build) (64-Bit)`.

Best Regards,
Kalle

**Comment by jacobrayschwartz** [comment]
Seeing this in the online editor as well

**Comment by iget-master** [comment]
This ridiculous bug is preventing our team using the tool, could someone give attention here?

**Comment by webron** [comment]
In the upcoming weeks we'll be taking a look at the auto-suggest and some other underlying features in the editor - hopefully this will get resolved as part of the process.

**Comment by shockey** [comment]
I have a theory: when our autosuggest code throws an uncaught error, Ace returns the current character as the resolved autosuggest value - so when live autocomplete fires and ends with an error, that buffer is appended to the value under the cursor, and the user sees a repeated character.

**Comment by iget-esoares** [comment]
I'll keep in touch. If occurs again I tell you.

Thank you for the fix!

**Comment by shockey** [comment]
Shipping the new version now - it will be live in about 15 minutes.

Thanks, everyone! Feel free to bump this thread if you run into this issue again.
