### ISSUE TITLE
Generate Client -> Html2 not producing expected output

### ISSUE THREAD

**Issue by smirnair** [swagger-api/swagger-editor#1415]
Hello, 

It was noticed today that the HTML2 client output is not showing up the schema contents. It was working the last time I checked on 7-12-17. I have attached the screen capture from the petstore example.
![swagger bug](https://user-images.githubusercontent.com/24231245/28472759-d1ada7cc-6e0f-11e7-9d14-9640b1f32bb9.png)

FYI, I am using the http://editor2.swagger.io/#!/

Thanks
Smitha.

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger-codegen#6145
