### ISSUE TITLE
How to DISABLE Auto Mocking Plugin of the online editor

### ISSUE THREAD

**Issue by ppKrauss** [swagger-api/swagger-editor#1421]
Impossible to use my server

**Comment by webron** [comment]
There's no mocking plugin in the online editor.

**Comment by ppKrauss** [comment]
Hi @webron , sorry, I am using `swaggerhub.com`, example https://app.swaggerhub.com/help/tools/swaggerhub-editor  with [getfrag/1.0.0](https://app.swaggerhub.com/apis/ppKrauss/getfrag/1.0.0).

Editing my api document, the `host`... When save the editor add a comment in my `host` and include lines with other host and path, the `# Added by API Auto Mocking Plugin` lines... Replace always my editigs by `virtserver.swaggerhub.com`

**Comment by webron** [comment]
Please contact SwaggerHub's support then, this is not related to the OSS tool.
