### ISSUE TITLE
Bug: improperly decoded JSON pointer characters 

### ISSUE THREAD

**Issue by fireproofsocks** [swagger-api/swagger-editor#1430]
I believe I have I ran into a bug when defining some circular references.  Here is my schema (simplified):

```
{
  "paths":
    "/api/menus/{id}" : {
      "get": {
        "responses": {
           "200": {
              "schema": {
                  "type": "object",
                  "description": "Bundle successfully added my schema object here!"
                  ... etc...
              }
           }
        }
      }
    },
    "/api/menus/{id}/tree": {
       "get": {
          "responses": {
             "200": {
                 "description": "OK",
                 "schema": {
                    "$ref": "#/paths/~1api~1menus~1%7Bid%7D/get/responses/200/schema"
                  }
             }
           }
       }
    }
}
```

When I paste it into the Swagger editor, I get an error on this line:
```
    "$ref": "#/paths/~1api~1menus~1%7Bid%7D/get/responses/200/schema"
```
If I manually replace the `%7B` and `%7D` to `{` and `}` respectively, the error goes away:

```
    "$ref": "#/paths/~1api~1menus~1{id}/get/responses/200/schema"
```

I had originally thought this might have been an error with the dereferencer, but after some discussion in its issue tracker, it seems like the error might not be in the encoding of special characters to create the pointer, but in the Swagger Editor's _decoding_ of the characters. 

See https://github.com/BigstickCarpet/json-schema-ref-parser/issues/44

**Comment by hkosova** [comment]
Your example works fine in Swagger Editor 3.5.6, so this seems to have been fixed.

cc @shockey 

![json-pointer](https://user-images.githubusercontent.com/8576823/40472224-80e960f0-5f41-11e8-9702-4b749d8da49b.png)

**Comment by shockey** [comment]
Thanks @hkosova - closing as fixed!
