### ISSUE TITLE
Editor - Import file UI

### ISSUE THREAD

**Issue by boyfox** [swagger-api/swagger-editor#1436]
![screen shot 2017-07-28 at 5 49 29 pm](https://user-images.githubusercontent.com/3168694/28762361-4dbb65ae-75cf-11e7-9199-bbc7ad19218e.png)

**Comment by webron** [comment]
?

**Comment by hkosova** [comment]
Duplicate of #1413?

**Comment by shockey** [comment]
Closing as a duplicate of #1413.
