### ISSUE TITLE
Root element name is missing in HTML client

### ISSUE THREAD

**Issue by cftsgit** [swagger-api/swagger-editor#1438]
Steps

1. Upload .yaml file which is having root element.
2. Generate HTML client
3. Find root element in html

root element name is missing.

Note : Generating client as HTML2.

**Comment by webron** [comment]
What do you mean by 'root element'?

**Comment by cftsgit** [comment]
Hi,

    Please refer attached Image for example purpose. In first image (yaml jpg) root elment is coming but after generating html2 client it is not coming in .html file. 


![yaml](https://user-images.githubusercontent.com/30591220/29168561-055806ca-7ded-11e7-93ba-95fa1fb10a1b.JPG)
![html](https://user-images.githubusercontent.com/30591220/29168562-055ca626-7ded-11e7-9afa-fd95f2379163.JPG)

**Comment by webron** [comment]
It's just how the template is built. If you'd like to see it changed, please submit a ticket to [swagger-codegen](https://github.com/swagger-api/swagger-codegen) and consider submitting a PR.
