### ISSUE TITLE
OAS 3.0: Duplicate validation errors

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-editor#1441]
Version: http://editor.swagger.io, 3.1.0/g66e6130-dirty

Spec:
```
openapi: 3.0.0
info:
  version: '1.0'
  title: httpbin

paths:
  /status/{statusCode}:
    get:
      summary: Returns the specified HTTP status code
      parameters:
        - name: statusCode
          in: path
          required: yes
          description: The status code to return.
          schema:
            type: integer
      responses:
        default:
          description: A response with the requested status code.
```

The only error here is `required: yes` (should be `required: true`), but the editor shows 35 (!) validation errors, most of them duplicates.

> **Schema error at paths['/status/{statusCode}'].get.parameters[0]**
> should match exactly one schema in oneOf
> Jump to line 11
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0]**
> should have required property 'examples'
> missingProperty: examples
> Jump to line 11
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0]**
> should have required property 'examples'
> missingProperty: examples
> Jump to line 11
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0]**
> should have required property 'examples'
> missingProperty: examples
> Jump to line 11
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0]**
> should have required property 'examples'
> missingProperty: examples
> Jump to line 11
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0]**
> should match exactly one schema in oneOf
> Jump to line 11
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0]**
> should match exactly one schema in oneOf
> Jump to line 11
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0]**
> should NOT have additional properties
> additionalProperty: schema
> Jump to line 11
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0]**
> should have required property 'content'
> missingProperty: content
> Jump to line 11
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0]**
> should NOT have additional properties
> additionalProperty: schema
> Jump to line 11
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0]**
> should have required property 'content'
> missingProperty: content
> Jump to line 11
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0]**
> should match exactly one schema in oneOf
> Jump to line 11
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0]**
> should match exactly one schema in oneOf
> Jump to line 11
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0]**
> should have required property '$ref'
> missingProperty: $ref
> Jump to line 11
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0]**
> should match exactly one schema in oneOf
> Jump to line 11
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0].in**
> should be equal to one of the allowed values
> allowedValues: query
> Jump to line 12
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0].in**
> should be equal to one of the allowed values
> allowedValues: header
> Jump to line 12
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0].in**
> should be equal to one of the allowed values
> allowedValues: cookie
> Jump to line 12
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0].in**
> should be equal to one of the allowed values
> allowedValues: query
> Jump to line 12
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0].in**
> should be equal to one of the allowed values
> allowedValues: header
> Jump to line 12
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0].in**
> should be equal to one of the allowed values
> allowedValues: cookie
> Jump to line 12
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0].in**
> should be equal to one of the allowed values
> allowedValues: query,header,cookie
> Jump to line 12
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0].required**
> should be boolean
> Jump to line 13
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0].required**
> should be equal to one of the allowed values
> allowedValues: true
> Jump to line 13
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0].required**
> should be boolean
> Jump to line 13
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0].required**
> should be boolean
> Jump to line 13
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0].required**
> should be boolean
> Jump to line 13
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0].required**
> should be boolean
> Jump to line 13
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0].required**
> should be equal to one of the allowed values
> allowedValues: true
> Jump to line 13
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0].required**
> should be boolean
> Jump to line 13
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0].required**
> should be boolean
> Jump to line 13
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0].required**
> should be boolean
> Jump to line 13
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0].required**
> should be boolean
> Jump to line 13
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0].required**
> should be equal to one of the allowed values
> allowedValues: true
> Jump to line 13
> 
> **Schema error at paths['/status/{statusCode}'].get.parameters[0].required**
> should be boolean
> Jump to line 13

**Comment by webron** [comment]
Thanks @hkosova. This seems to be true if other properties are wrong too. Tried changing the `in` value to `monkey` - same effect.
