### ISSUE TITLE
Response schema no longer shown

### ISSUE THREAD

**Issue by tyrjo** [swagger-api/swagger-editor#1444]
Some recent change removed the in-line display of response object schema in the description.  Please restore this, without being the see the object data in-line it is very difficult to use the editor to understand the API.

For example, the 200 response from /pet/{petId} now only shows "successful operation" in the description when the actual response is

200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Pet"

**Comment by reznik789** [comment]
This issue related to 
https://github.com/swagger-api/swagger-ui/issues/3480

**Comment by webron** [comment]
Yup, closing as a duplicate of https://github.com/swagger-api/swagger-ui/issues/3489.
