### ISSUE TITLE
OAS 3.0: Enums in server variables trigger validation error

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-editor#1445]
Version: http://editor.swagger.io, 3.1.0/g66e6130-dirty

Server variables with `enum` trigger validation error "should be string".

Spec:
```
openapi: 3.0.0
info:
  version: 0.0.0
  title: test

servers:
  - url: https://{env}.example.com/v2
    variables:
      env:
        default: api
        enum:
          - api
          - api.dev
          - api.staging

paths: {}
```

**Comment by webron** [comment]
@shockey I think this is due to a bug in the JSON Schema I fixed after you took it from the PR. Try to update it first and see if resolves the issue.
