### ISSUE TITLE
OAS 3.0: Add validation error/warning for unquoted status codes

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-editor#1447]
Version: editor.swagger.io, 3.1.0/g66e6130-dirty

According to the [3.0 Specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#user-content-responsesCode), response status codes MUST be enclosed in quotation marks (for example, "200") for compatibility between JSON and YAML.

However, unquoted status codes do not trigger any validation errors/warnings in the editor.

```
openapi: 3.0.0
info:
  version: 0.0.0
  title: test
paths:
  /:
    get:
      responses:
        200:
          description: OK
        500:
          description: Oops
```

**Comment by shockey** [comment]
Not sure this is actionable - JSON, and JavaScript objects themselves, only allow key names to be strings.

Our YAML parser in the Editor casts numerical keys to strings as I would as expect a YAML parser to - as a result, it's impossible to identify what _was_ a number in the resulting JS object. The only way to reliably detect this would be to traverse a YAML AST, which would introduce more overhead to the validators.

Do we know of any cases where using a YAML number breaks tooling?

**Comment by shockey** [comment]
Closing for now, per discussion with @webron. If tooling issues with the keys come up, we will reopen!
