### ISSUE TITLE
References in responses are ignored

### ISSUE THREAD

**Issue by patrickd-** [swagger-api/swagger-editor#1448]
![screenshot from 2017-08-01 15-25-27](https://user-images.githubusercontent.com/2522448/28827416-c65f0930-76cd-11e7-99be-ea53bc71f3d6.png)
From http://editor.swagger.io/

Since a few days the referenced schema is no longer shown in an operations response.

Was this removed on purpose?

**Comment by webron** [comment]
@patrickd- we introduced a fix yesterday, but failed to deploy it. It should be better now, can you give it another try? You might need to hard-reload the page to get the latest version.

**Comment by patrickd-** [comment]
Yay! Works! Thanks a lot!
