### ISSUE TITLE
OAS 3.0: callbacks

### ISSUE THREAD

**Issue by dvh** [swagger-api/swagger-editor#1452]
When adding callbacks as described by the [official example](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/callback-example.yaml), Swagger Editor throws the following error:
```
Schema error at paths['/streams'].post.callbacks['onData']
should NOT have additional properties
additionalProperty: {$request.query.callbackUrl}/data
```
Is this not implemented yet or is the example broken? I am still looking for a working `callbacks` example but unfortunately couldn't find it yet.

**Comment by webron** [comment]
This is due to a bug we have in the released version of the editor that's already fixed in master. You can use master for now, or wait until we make an official release which is planned for EOD today.

**Comment by dvh** [comment]
Great! Thanks and sorry for reporting a known issue 😉

**Comment by webron** [comment]
No worries, better to have duplicates than no reports at all.
