### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by jmarshall0807** [swagger-api/swagger-editor#1458]
I have enabled CORS on my server, but every time I have attempted to run a POST method from the swagger editor (installed using git clone, nmp install, npm start), the preflight OPTIONS request returns a 405 Method Not Allowed error. I have tried changing the response headers multiple times, and found the only thing that worked was to use Fiddler to change the preflight request from an OPTIONS request to a POST request. I have not been able to figure out a way to get the OPTIONS preflight request to return an OK HTTP status Code. Can anyone help? Thanks

**Comment by webron** [comment]
This is more of a question to the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket). Try posting the question there and provide more details on your server.
