### ISSUE TITLE
OAS 3.0: `writeOnly` field ignored in response

### ISSUE THREAD

**Issue by dvh** [swagger-api/swagger-editor#1459]
If I add `readOnly: true` to a property, the property isn't rendered in the example request, which is expected behaviour. However, if I add `writeOnly: true` to a property, the property still gets rendered in the example response. I think this should not be the case.

**Comment by shockey** [comment]
Thanks for the report, @dvh!

We're already tracking this at https://github.com/swagger-api/swagger-ui/issues/3447, so I'm going to close this as a duplicate.
