### ISSUE TITLE
Autocomplete results in double typing 

### ISSUE THREAD

**Issue by MidnightP** [swagger-api/swagger-editor#1468]
When typing in a reference like `#/definitions/TypeModel` the editor attempts to autocomplete a definition which results in double typing. Is there any solution for this? I'm using the latest version `swaggerapi/swagger-editor`.

**Comment by shockey** [comment]
Confirmed:

<img src='https://shipusercontent.com/fa1997a5bc6faacbf97d8dc310614208/Pasted%20Image%201.png' title='Pasted Image 1.png' width=597>

**Comment by tgockel** [comment]
It's unclear if this is related, but the first character of a line often gets repeated in cases where there is a potential completion involved. The double-letter will never happen if I explicitly hit Ctrl+Space, even if autocomplete does not pop up.

**Comment by shockey** [comment]
Closing as a duplicate of #1414, which was fixed by #1544, which will be released tonight :smile: 

Thanks @MidnightP & @tgockel!
