### ISSUE TITLE
The generated codes from editor and codegen are different

### ISSUE THREAD

**Issue by minchao** [swagger-api/swagger-editor#1472]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 2.0
| Which Swagger-Editor version?       | editor.swagger.io
| How did you install Swagger-Editor? | editor.swagger.io
| Which broswer & version?            | Chrome 60.0.3112.101
| Which operating system?             | MacOS

### Demonstration API definition

http://petstore.swagger.io/v2/swagger.json

### Expected Behavior

The generated codes from editor and codegen are the same

### Current Behavior

The generated codes from editor and codegen are different

### Version:

* swagger-editor editor.swagger.io
* swagger-codegen 2.2.3

### Steps to reproduce:

swagger-editor

1. Go to http://editor.swagger.io/
2. Generate client > php

```
## Documentation For Models

 - [ApiResponse](docs/Model/ApiResponse.md)
 - [Body](docs/Model/Body.md)
 - [Body1](docs/Model/Body1.md)
 - [Body2](docs/Model/Body2.md)
 - [Body3](docs/Model/Body3.md)
 - [Body4](docs/Model/Body4.md)
 - [Body5](docs/Model/Body5.md)
 - [Category](docs/Model/Category.md)
 - [InlineResponse200](docs/Model/InlineResponse200.md)
 - [InlineResponse2001](docs/Model/InlineResponse2001.md)
 - [InlineResponse2002](docs/Model/InlineResponse2002.md)
 - [InlineResponse2003](docs/Model/InlineResponse2003.md)
 - [Order](docs/Model/Order.md)
 - [Pet](docs/Model/Pet.md)
 - [PetCategory](docs/Model/PetCategory.md)
 - [PetTags](docs/Model/PetTags.md)
 - [Tag](docs/Model/Tag.md)
 - [User](docs/Model/User.md)
```

swagger-codegen

1. Go to https://generator.swagger.io/
2. clients > POST /gen/clients/{language}
3. Try it out > Select language: php > Execute
4. Download the client file

```
## Documentation For Models

 - [ApiResponse](docs/Model/ApiResponse.md)
 - [Category](docs/Model/Category.md)
 - [Order](docs/Model/Order.md)
 - [Pet](docs/Model/Pet.md)
 - [Tag](docs/Model/Tag.md)
 - [User](docs/Model/User.md)
```

**Comment by shockey** [comment]
This is likely coming from handing the resolved API definition to the generator: https://github.com/swagger-api/swagger-editor/blob/master/src/standalone/topbar/topbar.jsx#L126

@webron, is it safe to pass an unresolved API definition to the generator? I couldn't find any documentation that mentions it. If so, this is an easy fix!

**Comment by webron** [comment]
@minchao - in the above example, what do you have in the editor vs what do you pass to the online generator?

**Comment by minchao** [comment]
@webron Both are the same definition http://petstore.swagger.io/v2/swagger.json

**Comment by webron** [comment]
@shockey yeah, you hit the issue. Should pass the unresolved doc.

**Comment by shockey** [comment]
This should be fixed in master, and released tomorrow 😄 

Thanks for the report @minchao!
