### ISSUE TITLE
No error shown when property of type array has missing items

### ISSUE THREAD

**Issue by john-french** [swagger-api/swagger-editor#1473]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 2.0
| Which Swagger-Editor version?       | 3.0.17
| Which browser & version?            | Chrome 60.0.3112.101 
| Which operating system?             | macOS 10.12.6

### Demonstration API definition

Line 119: https://gist.github.com/john-french/f3fb744b3a86b98998948a09880fbbea

### Expected Behavior

A definition has a property of type array which has no items defined. The editor should show an error, since this isn't valid.

### Current Behavior

No error is shown.

**Comment by FWirtz** [comment]
Just experienced the same issue.
In conjunction with [connexion](https://github.com/zalando/connexion) and the Swagger UI this throws a `Uncaught Type Error: cannot read property $ref of undefined`.
Extremely frustrating and hard to find.
