### ISSUE TITLE
I have one swagger. And a seperate file for definitions. How do I refer this definition inside the swagger? So that the swagger is validated with this definition file.

### ISSUE THREAD

**Issue by kazim060** [swagger-api/swagger-editor#1478]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  
| Which Swagger/OpenAPI version?      |
| Which Swagger-Editor version?       |
| How did you install Swagger-Editor? | 
| Which broswer & version?            |
| Which operating system?             | 

### Demonstration API definition

```yaml
your: "API definition goes here"
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

**Comment by webron** [comment]
You need to host the definitions file and reference it with a full URL.
