### ISSUE TITLE
Documentation update and incorrect error message

### ISSUE THREAD

**Issue by maclonghorn** [swagger-api/swagger-editor#1481]
In swagger-editor I have been getting the following:
```
Schema error 
should NOT have additional properties
additionalProperty: openapi
```
This message is incorrect.  I was using `openapi: "3.0"` similar to the former `swagger: "2.0"`.  When I changed it to `openapi: "3.0.0"` it validated.

The docs are not clear that `openapi` MUST be `3.x.x`.

**Comment by shockey** [comment]
Hi @maclonghorn!

We're following the OpenAPI specification here:

> The OpenAPI Specification is versioned using Semantic Versioning 2.0.0 (semver) and follows the semver specification.
>
> https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#versions

Semantic Versioning, in turn, says:

> A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and MUST NOT contain leading zeroes. X is the major version, Y is the minor version, and Z is the patch version. Each element MUST increase numerically. For instance: 1.9.0 -> 1.10.0 -> 1.11.0.
>
> http://semver.org/spec/v2.0.0.html#spec-item-2

---

That being said, that's an easy thing to overlook. I'd be open to a note in the README pointing this potential hangup out - @webron, any thoughts?

**Comment by maclonghorn** [comment]
Yeah, after I reread everything, i could see the language here and there, but ideally something like this would be in the Description for the `openapi` field:
```
Version MUST be of the form A.B.C
```

Also, the error message really needs to reflect the real problem.  It says that `openapi` field is not allowed.  What it SHOULD say is something like:
```
openapi field is not a valid semantic format
```
This is probably more important than fixing the documentation.

**Comment by webron** [comment]
I don't think the spec needs to be updated. Semver is very common these days (for better or worse) and we try to not replicate information that's provided in other specifications where possible, but rather link to them.

As for the validation error - the validation defaults to Swagger 2.0 when it doesn't recognize the `openapi` field - that's the differntiator.

**Comment by maclonghorn** [comment]
OK.  Still, I would propose the validation error needs to be corrected.  `openapi` is not an additional property....it's valid.  It's just that the value isn't formatted correctly.

**Comment by shockey** [comment]
Closing, as we now display a helpful message in this case:

<img width="1457" alt="image" src="https://user-images.githubusercontent.com/680248/55440285-fd34ed80-555b-11e9-9485-42c945535511.png">
