### ISSUE TITLE
YAML import strips out comments

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-editor#1483]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 2.0
| Which Swagger-Editor version?       | 3.1.5
| How did you install Swagger-Editor? | Using online editor http://editor.swagger.io
| Which browser & version?            | Chrome 60, Firefox 55
| Which operating system?             | Windows 7

### Demonstration API definition
https://raw.githubusercontent.com/swagger-api/swagger-editor/2.x/spec-files/guide.yaml

Steps to reproduce:
1. In the editor, select **File > Import URL**.
2. Import the URL above.

### Configuration (browser query string, constructor, config.yaml)
N/a

### Expected Behavior
YAML `# comments` are preserved in the imported spec.

### Current Behavior
YAML comments are stripped from the imported spec.

### Workaround
Paste the YAML into the editor instead of using file import.

### Context
Editor 2.x (http://editor2.swagger.io) does not have this issue - it was fixed in #697 and #753.

**Comment by merlos** [comment]
Pretty annoying behavior.  Also applies to openAPI 3.0.0 yaml files.

Comments in YAML help API maintainers to keep track of todo things, visually separate related areas, add notes which are not relevant for API users but for API doc maintainer.

This bug should have a higher priority.
