### ISSUE TITLE
Validation message when oneOf fails for example(s)

### ISSUE THREAD

**Issue by joeljons** [swagger-api/swagger-editor#1489]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |   ¯\\_(ツ)_/¯
| Which Swagger/OpenAPI version?      |  OAS3
| Which Swagger-Editor version?       | 3.1.6
| How did you install Swagger-Editor? | -
| Which broswer & version?            | Chrome
| Which operating system?             |  Windows

### Demonstration API definition

```yaml
openapi: 3.0.0
info:
  version: "validation"
  title: Spec with both example and examples
paths:
  /myPath:
    get:
      responses:
        '200':
          description: OK
          content:
            text/plain:
              example: sample response
              examples:
                foo:
                  value: anonther response
```

### Expected Behavior
One error message that states that I can't have both `example` and `examples` in `paths['/myPath'].get.responses['200'].content['text/plain']`

### Current Behavior
Three error messages there neither one of them nails the error description.

**Comment by shockey** [comment]
I've opened a pull request (#1985) that will close this issue.

Here's what Swagger Editor reports with my changes:

```
Structural error at [...]200.content.text/plain
should not have both `example` and `examples`, as they are mutually exclusive
```
