### ISSUE TITLE
Blurry text in autocompletion in Chrome 61 on Windows

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-editor#1491]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 2.0
| Which Swagger-Editor version?       | 3.1.7
| How did you install Swagger-Editor? | http://editor.swagger.io
| Which browser & version?            | Chrome 61, 64-bit
| Which operating system?             | Windows 7, 64-bit

### Issue Description

![Chrome blurry image](https://user-images.githubusercontent.com/8576823/30341005-27e06bf4-97fd-11e7-9adb-c094cde7712f.png)

The bold text in the autocompletion popup is blurry. This text uses `text-shadow`:

```css
.ace_editor.ace_autocomplete .ace_completion-highlight {
  color: #000;
  text-shadow: 0 0 0.01em;
}
```
The problem exists in Chrome 61, but not in Chrome 60 and Firefox.

### Expected Behavior
Text is sharp.

### Current Behavior
Text is blurry.

### Possible Solution
Maybe override the styles for `.ace_editor.ace_autocomplete .ace_completion-highlight` to use `font-weight: bold` instead of `text-shadow`? I'm not an expert though.

**Comment by shockey** [comment]
@hkosova, I'm not seeing this in Chrome 63:

**<img src='https://shipusercontent.com/a3e42ecc54687bfc98ee1c1e40feac76/Pasted%20Image%201.png' title='Pasted Image 1.png' width=432>**

Closing; let me know if this is in error!
