### ISSUE TITLE
Regression with allOf when generating client (>= 3.1.6)

### ISSUE THREAD

**Issue by tagliala** [swagger-api/swagger-editor#1497]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 2.0
| Which Swagger-Editor version?       | 3.1.6+
| How did you install Swagger-Editor? | editor.swagger.io
| Which broswer & version?            | Chrome 60.0.3112.113
| Which operating system?             |  macOS Sierra 10.12.6

### Demonstration API definition
```yaml
swagger: "2.0"
info:
  description: "allOf issue demonstration"
  version: "1.0.0"
  title: "Swagger allOf regression"
host: "example.com"
schemes:
- "http"
paths:
  /rides:
    post:
      tags:
      - "rides"
      summary: "Add a new ride"
      description: ""
      operationId: "addRide"
      parameters:
      - in: "body"
        name: "body"
        description: "Ride object"
        required: true
        schema:
          allOf:
            - $ref: "#/definitions/Ride"
      responses:
        405:
          description: "Invalid input"
definitions:
  Ride:
    type: "object"
    required:
    - "from"
    - "to"
    properties:
      id:
        type: "integer"
        format: "int64"
      from:
        type: "string"
        example: "London"
      to:
        type: "string"
        example: "Manchester"
```

### Configuration (browser query string, constructor, config.yaml)
N / A

### Expected Behavior
1. Click on "Generate Client"
2. Select a target language
3. Documentation is generated and downloaded

### Current Behavior
1. Click on "Generate Client"
2. Select a target language
3. Nothing happens

Browser's development console error: 
```
POST https://generator.swagger.io/api/gen/clients/html2 400 (Bad Request)
swagger-editor-standalone-preset.js:1 Uncaught (in promise) Error: Bad Request
    at swagger-editor-standalone-preset.js:1
    at <anonymous>
(anonymous) @ swagger-editor-standalone-preset.js:1
Promise rejected (async)
r.downloadGeneratedFile @ swagger-editor-standalone-preset.js:1
n @ swagger-editor-bundle.js:103
s @ swagger-editor-bundle.js:103
a @ swagger-editor-bundle.js:103
f @ swagger-editor-bundle.js:103
m @ swagger-editor-bundle.js:103
r @ swagger-editor-bundle.js:103
processEventQueue @ swagger-editor-bundle.js:103
n @ swagger-editor-bundle.js:117
handleTopLevel @ swagger-editor-bundle.js:117
o @ swagger-editor-bundle.js:119
perform @ swagger-editor-bundle.js:103
batchedUpdates @ swagger-editor-bundle.js:119
o @ swagger-editor-bundle.js:103
dispatchEvent @ swagger-editor-bundle.js:119
```

Response:
```
{"code":1,"type":"error","message":"Unable to build target: Could not process operation:\n  Tag: rides\n  Operation: addRide\n  Resource: post /rides\n  Definitions: {Ride=io.swagger.models.ModelImpl@c32f7a5d}\n  Exception: null"}
```

### Possible Solution
Something changed between version 3.1.5 and 3.1.6

Lines generating the issue are:
```yml
          schema:
            allOf:
              - $ref: '#/definitions/Ride'
```

Of course, if I remove `allOf:` such as:

```yml
          schema:
            $ref: '#/definitions/Ride'
```

documentation will be generated successfully

### Context
I'm using an endpoint which *could* create multiple objects. In the simplified example above, let's imagine that I need an extra boolean attribute "round_trip", which creates two rides, inverting `from` and `to` fields.

```yml
          schema:
            allOf:
              - $ref: '#/definitions/Ride'
              - type: object
                properties:
                  round_trip:
                    description: Create another ride with inverted `from` and `to` fields
                    type: boolean
                    default: false
                    example: false
```

**Comment by webron** [comment]
The online codegen hasn't been updated in at least 2 months. What has changed though, is the resolution of references as they are sent to the codegen from the editor.

@shockey could that be the reason for this?

**Comment by tagliala** [comment]
Hi @webron.

I edited the first post.

I'm still able to generate docs with 3.1.5 and 3.1.4

I'm not able to generate docs with >= 3.1.6

**Comment by webron** [comment]
Thanks. I suspect this is because we now no longer send the resolved spec to the generator, as that produced other issues with the generated code (and it's the right approach). 

We'll wait for @shockey's confirmation, but if that's the case, then the issue should move to swagger-codegen.

**Comment by shockey** [comment]
Thanks for the spec, @tagliala! It helped me test this quickly.

@webron, I agree with your assessment. The only recent change to the codegen interface is moving away from sending the resolved spec.

However.... something isn't quite lining up 🤔 The change to the codegen interface on our side, went live as part of 3.1.7: https://github.com/swagger-api/swagger-editor/compare/v3.1.6...v3.1.7.

Version 3.1.6 had no changes to the codegen interface: https://github.com/swagger-api/swagger-editor/compare/v3.1.5...v3.1.6

I tested the example spec in 3.1.6, and it generated a JavaScript client correctly. 3.1.7 did not.

It looks like codegen is complaining:

```
Unable to build target: Could not process operation:↵  Tag: rides↵  Operation: addRide↵  Resource: post /rides↵  Definitions: {Ride=io.swagger.models.ModelImpl@4c0887cd}↵  Exception: null
```

That being said... I think this should be kicked over to swagger-codegen 😄

**Comment by webron** [comment]
Yup. @tagliala, please reopen the ticket on swagger-codegen and provide the relevant details there.

**Comment by tagliala** [comment]
@webron done, thanks. Please take a look there if I'm missing something.

I can confirm I was able to generate docs in 3.1.6, maybe yesterday I didn't refresh the page or didn't clear browser cache after loading the 3.1.6 version of the editor 🤷‍♂️

**Comment by tagliala** [comment]
Didn't get any answer / label at swagger-api/swagger-codegen#6519
