### ISSUE TITLE
OAS 3.0: schema inheritance overwrites $ref definition

### ISSUE THREAD

**Issue by andig** [swagger-api/swagger-editor#1498]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  bug
| Which Swagger/OpenAPI version?      | 3.0.0
| Which Swagger-Editor version?       | master
| How did you install Swagger-Editor? | npm + swaggerhub
| Which broswer & version?            |safari 10.1.2
| Which operating system?             | OSX

### Demonstration API definition

```yaml
    paths:
      /entity.json:
        get:
          tags:
            - entity
          summary: List of public entities
          operationId: listPublicEntities
          responses:
            '200':
              description: successful operation
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/EntityListResponse'
            '400':
              description: invalid operation
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ExceptionResponse'

    components:
      schemas:
        Response:
          type: object
          properties:
            version:
              type: string
              
        ExceptionResponse:
          $ref: '#/components/schemas/Response'
    #      type: object
          properties:
            exception:
              $ref: '#/components/schemas/Exception'

        EntityListResponse:
          $ref: '#/components/schemas/Response'
    #      type: object
          properties:
            entities:
              type: array
              items: 
                $ref: '#/components/schemas/Entity'

        Exception:
          type: object
          properties:
            message:
              type: string
            type:
              type: string
            code:
              type: integer

        Entity:
          type: object
          properties:
            uuid:
              type: string
            type:
              type: string
            title:
              type: string
            active:
              type: boolean

```

### Expected Behavior

`EntityListResponse` and `ExceptionResponse` should inherit `version` field from `Response`. `EntityListResponse` for HTTP 200 OK should not show any exception properties, but rather `Entity` properties.

### Current Behavior

`EntityListResponse` for 200 OK example shows in the editor as exception:

    {
      "version": "string",
      "exception": {
        "message": "string",
        "type": "string",
        "code": 0
      }
    }

**Comment by andig** [comment]
Invalid. Should use `allOf` instead. Might still be beneficial if editor raised an error?

**Comment by webron** [comment]
It should produce a validation warning that anything other than the $ref will be ignored.

**Comment by hungnd** [comment]
Sorry of OT,

How do you guys get source that support openapi 3.0? 
I tried checking out master, branch v/3.1.10, tags v3.1.* After run, all of them don't support openapi 3.0 and throw out error

> Schema error 
> should NOT have additional properties 
> additionalProperty: openapi

**Comment by shockey** [comment]
@hungnd, make sure your openapi property is `openapi: "3.0.0". If that doesn't solve your problem, feel free to open a new issue and we'll help out there.

**Comment by hungnd** [comment]
@shockey thank for your response. I wrote `openapi: "**3.0**"`then it caused that error. 
I don't want to open a new issue before I sure it's a bug or just my mistake. Thank you again. Problem solved!

**Comment by shockey** [comment]
Closing, we produce validation warnings for this now:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/680248/41265977-cc77dba2-6da9-11e8-8226-08c346834cca.png">
