### ISSUE TITLE
OAS 3.0: parameters should be array?

### ISSUE THREAD

**Issue by andig** [swagger-api/swagger-editor#1499]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  bug
| Which Swagger/OpenAPI version?      |3.0.0
| Which Swagger-Editor version?       |master
| How did you install Swagger-Editor? | npm

### Demonstration API definition

```yaml
    /channel.json:
      get:
        tags:
          - channel
        summary: List of public channels
        description: Similar to list of entities, but returns only entities of type Channel.
        operationId: getPublicChannels
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ChannelListResponse'
          '400':
            $ref: '#/components/responses/ErrorResponse'
      post:
        tags:
          - channel
        summary: Create channel
        description: Create channel with given properties.
        operationId: createChannel
        parameters:
          title:
            name: title
            in: query
            required: true
```

### Expected Behavior

This definition should imho work as its similar to https://github.com/OAI/OpenAPI-Specification/blob/3.0.0-rc0/versions/3.0.md#parameterObject

### Current Behavior

Error message: `parameters` should be an array.

Changing the `title` definition to `- title` changes the error:

    Should not have additional properties. Additional property: title

**Comment by webron** [comment]
Should be:
```yaml
      parameters:
        - name: title
          in: query
          required: true
```

Please refer to our documentation about how to write API definitions - https://swagger.io/docs/specification/describing-parameters

In the future, provide full API definitions and not snippets as it makes it more difficult to support.
