### ISSUE TITLE
Using $ref in request body schema hides defined example 

### ISSUE THREAD

**Issue by gerbsen** [swagger-api/swagger-editor#1501]
hello, currently it's not possible to define an example for a request body if I reference another object. only default/null values are shown as example.

This can be seen here: (example is empty since no properties defined for Configuration)
```
openapi: 3.0.0
info:
  description: what a description
  version: 1.0.0
  title: API Docs
servers:
  - url: 'https://some.url.net'
paths:
  /some/path:
    post:
      summary: THis is a summary
      description: This should be a long description...
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Configuration'
            example:
              sources:
              - id: '1'
                lat: 52.450411
                lng: 13.43755
      responses:
        '200':
          description: Totally cool
          
components:
  schemas:
    Configuration:
      type: object
```
![screenshot 2017-09-21 13 49 51](https://user-images.githubusercontent.com/1186245/30694350-e0ffe7ea-9ed3-11e7-99c5-c300dcebe32d.png)

If we change this to that:
```
openapi: 3.0.0
info:
  description: what a description
  version: 1.0.0
  title: API Docs
servers:
  - url: 'https://some.url.net'
paths:
  /some/path:
    post:
      summary: THis is a summary
      description: This should be a long description...
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Configuration'
      responses:
        '200':
          description: Totally cool
          
components:
  schemas:
    Configuration:
      type: object
      example:
        sources:
        - id: '1'
          lat: 52.450411
          lng: 13.43755
```
![screenshot 2017-09-21 13 49 38](https://user-images.githubusercontent.com/1186245/30694364-f0634a1a-9ed3-11e7-819b-3311e7c0eb94.png)

Then this works as expected, but forces me to use one example for all requests, I also validated this against another OpenAPI Viewer (Koumoul).

Hope this get's fixed soon.
Thanks, Daniel

**Comment by hkosova** [comment]
Swagger UI does not currently display the `example` and `examples` defined under `content.<media-type>` - see https://github.com/swagger-api/swagger-ui/issues/3437.

**Comment by gerbsen** [comment]
This is not a really a workaround since I have to use the same example everywhere :(

**Comment by lociko** [comment]
Any news about it?

**Comment by shockey** [comment]
This should be fixed now 😄
