### ISSUE TITLE
XML code examples invisible in swagger-editor 

### ISSUE THREAD

**Issue by tbarsballe** [swagger-api/swagger-editor#1502]
When writing a markdown description, which contains a code block with XML content, the xml tags are invisible when rendered.

Displaying the same API doc using swagger-ui, the XML tags are rendered normally.

| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 2.0
| Which Swagger-Editor version?       | Current version hosted at https://editor.swagger.io/
| How did you install Swagger-Editor? | N/A
| Which broswer & version?            | Chrome 60.0.3
| Which operating system?             | macOS Sierra 10.12.6

### Demonstration API definition

API definition: https://gist.github.com/tbarsballe/bb135cd6f65b1341bd4184f003ca8f4d

Example of the issue:
![screen shot 2017-09-20 at 4 11 59 pm](https://user-images.githubusercontent.com/9271497/30671950-77ac42d0-9e1e-11e7-8868-57c0608c166c.png)

### Configuration (browser query string, constructor, config.yaml)

N/A (Default Confuguration)

### Expected Behavior

XML examples should be fully rendered

### Current Behavior

XML Examples are not fully rendered

### Possible Solution

I presume there is some form of HTML sanitization being applied to the editor contents before it gets rendered in swagger-ui. It seems that this sanitization is a bit overzealous.

### Context

Caused a bunch of wasted time trying to fix an API definition that was not actually wrong.

**Comment by tbarsballe** [comment]
I can reproduce the same issue running swagger-editor locally (latest master).

**Comment by shockey** [comment]
From @tbarsballe, in the related UI issue:

> UPDATE: For me, this only seems to occur when using editor.swagger.io. When using swager-ui standalone, everything displays fine.

My first guess would be that there's some CSS being used in the standalone versions that cause the problem 🤔

**Comment by tbarsballe** [comment]
Inspecting the html of the preview gives this:

<img width="643" alt="screen shot 2017-09-22 at 3 20 33 pm" src="https://user-images.githubusercontent.com/9271497/30766401-ac2f079a-9fa9-11e7-8b93-0ab236b25aa4.png">

So it does seem that the HTML tags are actually getting removed, not hidden (So probably not a CSS issue)

**Comment by webron** [comment]
@owenconti maybe you can look into this one as well.

**Comment by owenconti** [comment]
So I can confirm this is due to the Markdown sanitization. My "fix" is to remove the sanitization altogether. However, it was obviously put there for a reason (probably because of this issue: https://github.com/swagger-api/swagger-ui/issues/3163) - but when I remove it, I cannot reproduce that issue.

So it may be safe to remove sanitization altogether. If anyone knows of other XSS vulnerabilities that *should* be present when **not** sanitizing, please let me know so I can test against them.

**Comment by webron** [comment]
Hmm, I don't think we can take away the sanitization due to the XSS vulnerabilities. Can you check with @shockey about it?
