### ISSUE TITLE
Validation error oauth2RedirectUri configuration is not passed

### ISSUE THREAD

**Issue by JRozborska** [swagger-api/swagger-editor#1503]
When Swagger is deployed with authentication type: "ACCESSCODE" or "IMPLICIT" OAuth 2.0 authorization is failing on Swagger Editor with the following error:
`validation error
oauth2RedirectUri configuration is not passed. Oauth2 authorization cannot be performed.`

Authorization works without any problem on Swagger UI.

Regards,
Julita Rozborska

**Comment by webron** [comment]
Can you provide an API definition that reproduces the issue?

**Comment by webron** [comment]
On second thought, I'm going to close the issue. Please file a new ticket and follow the issue template. We need more details to be able to address it and the questions are available in the template.
