### ISSUE TITLE
| Which Swagger/OpenAPI version?  

### ISSUE THREAD

**Issue by ts9111** [swagger-api/swagger-editor#1508]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  
| Which Swagger/OpenAPI version?      |
| Which Swagger-Editor version?       |
| How did you install Swagger-Editor? | 
| Which broswer & version?            |
| Which operating system?             | 

### Demonstration API definition

```yaml
your: "API definition goes here"
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

**Comment by webron** [comment]
Assuming this has been opened by mistake.

**Comment by ts9111** [comment]
can you help me fix it, i will pay you $,
Please contact me back via email stbleo@gmail.com, or icq 662620581, thanks you
