### ISSUE TITLE
Several "Non-body parameters require a 'type' property." errors on a valid (!?) API definition.

### ISSUE THREAD

**Issue by nickshoe** [swagger-api/swagger-editor#1525]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 2.0
| Which Swagger-Editor version?       | Current (Couldn't find it)
| How did you install Swagger-Editor? | Online service (https://editor.swagger.io)
| Which broswer & version?            | Google Chrome 61.0.3163.100
| Which operating system?             | macOS Sierra 10.12.6

### Demonstration API definition

https://gist.github.com/nickshoe/0769a2ca3ac64ccc4e7521be5c6aef3c

### Configuration (browser query string, constructor, config.yaml)

No configuration file, used online service: https://editor.swagger.io 

### Expected Behavior

The API definition seems to be valid according to my knowledge/experience and these third party tools:
* APIgator: https://www.apigator.io
* Swagger 2.0 Parser (and validator): http://bigstickcarpet.com/swagger-parser/www/index.html

### Current Behavior

After having pasted the definition in the editor, several "Non-body parameters require a 'type' property." errors show up. The majority of errors marks, on the left side of the editor, seems to be unrelated to the code corresponding to their positions.

### Possible Solution

It sounds obvious but, if the bug is confirmed, it should reside in the part of the code which handles the validation of OpenAPI 2.0 definitions.
If the validator addresses this situation correctly, it will lead to a "pristine" documentation on the right side of the editor.

### Context

I'm trying to validate my API definition and getting a documentation without errors/warnings.

**Comment by shockey** [comment]
Thanks for the report, @nickshoe!

We have a pretty significant validation PR waiting in the wings (#1517). I have a hunch that the new validation selector system will allow for more precise targeting of parameter validation.

`#/definitions/Context Object/properties` contains a property named `parameters`, which is incorrectly triggering parameter validation. You're seeing many errors due to the fact that we validate `$ref`'d objects at each point that they are used.

This is part of a larger issue, #1343.

**Comment by shockey** [comment]
I managed to find a simple way to fix this 😄 

I'll merge the PR in a moment, and the fix should be released on Friday. If you urgently need the new build, you can clone the project and cut your own build. 

FWIW, with this fix, your definition validates with no errors - just a few warnings about siblings of `$ref` values!

**Comment by nickshoe** [comment]
@shockey glad to hear that. I'll be waiting for the PR.

As I can't change the property name I'll leave the API definition alone.
Thank you for your fast and precise response!

Cheers

**Comment by nickshoe** [comment]
@shockey are you kidding me!? 😮 

Super!

**Comment by nickshoe** [comment]
Hi @shockey, just tested the online version and it perfectly works.

Thank you!

**Comment by shockey** [comment]
![](https://media.giphy.com/media/s2qXK8wAvkHTO/giphy.gif)

No problem! Thanks for reporting the issue.
