### ISSUE TITLE
Extensions not being ignored properly by editor

### ISSUE THREAD

**Issue by alasdairhurst** [swagger-api/swagger-editor#1527]
As you will see with the provided evil, but valid swagger, there a number of things done incorrectly due to extensions not being properly ignored and being parsed as things like paths or responses.
editor.swagger.io parses and validates the swagger, but shows things like "x-an-extension-fake-path" as paths rather than ignoring them as they are extensions.
editor2.swagger.io fails to even parse the swagger document as it tries to read extensions as a variety of different object types instead of ignoring them
(for example the following error seems to be due to trying to read path.consumes from an extension which is null or a primative.
```
✖ Unknown Error
Cannot read property 'consumes' of undefined
```

| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  bug
| Which Swagger/OpenAPI version?      | 2.0
| Which Swagger-Editor version?       | editor.swagger.io and editor2.swagger.io as of 13/10/2017
| Which browser & version?            | chrome 61
| Which operating system?             | windows 10

### Demonstration API definition
https://gist.github.com/alasdairhurst/a1073a85d3df4bc800e143a4d31dd168

### Expected Behavior

Swagger document is parsed correctly. Extensions are not displayed as paths, responses or any other type of object.

### Current Behavior

extensions are not ignored by whatever is parsing the swagger, and the UI displays extensions as paths.

### Possible Solution

Extensions should be ignored in every location that they are allowed. They should not be parsed as, or show up as parameters, paths, responses and any other types of object.
The provided swagger document should parse correctly and not display and extensions. It should also display all parameters and paths as expected.
### Context

Tried to make a swagger for my own project which would allow project developers to find issues with the way swagger is handled. Instead, found issues with the official tools.

**Comment by webron** [comment]
@alasdairhurst thanks for opening the ticket, it's very helpful. Mind reopening it on swagger-ui? The rendering is controlled there.

**Comment by alasdairhurst** [comment]
@webron will do.  I wasn't sure where a lot of the validation/parsing was done so it may have had some effect in the editor too.

**Comment by webron** [comment]
Thanks. Since for now, this is mostly a rendering issue, it's definitely a UI issue.
