### ISSUE TITLE
OAS 3.0, Arrays as query parameter throws TypeError

### ISSUE THREAD

**Issue by anderejd** [swagger-api/swagger-editor#1530]
I'm trying to learn OpenAPI 3.0 and the Swagger editor by using this example:
https://github.com/OAI/OpenAPI-Specification/blob/99cfcba0cfd533a2814970f845433493a9c74312/examples/v3.0/petstore-expanded.yaml

Array as query parameter does not seem to work in the first path example `/pets`.
When I don't provide anything in the `tags` input field it seem to work (the loading indicator flashes briefly) and there is a 404 (I guess the example service does not exist). But when trying to use the `tags` input field there is no http request being dispatched and instead this exception in the javascript console:
`TypeError: i.count is not a function [Learn More] swagger-editor-bundle.js:1:29639`

![image](https://user-images.githubusercontent.com/3704611/31791954-b16c4f5c-b51a-11e7-98a7-c1a75db6430e.png)

**Comment by webron** [comment]
@shockey - looks like it doesn't render the array entry as an array, unlike with OAS2.

**Comment by shockey** [comment]
Fixed!

Thanks for the report, @anderejd.
