### ISSUE TITLE
Import definitions from another API using Online Swagger Editor

### ISSUE THREAD

**Issue by dantebarba** [swagger-api/swagger-editor#1531]
I can't manage to import Swagger definitions from another (same API version) swagger project on the Swagger Online editor. For example, I have a PetStore API and a GroceryStore API. Both have some definitions in common such as Cashier. How can I reference this common definition from GroceryStore to PetStore. Im using Swagger 2.0, is it possible. Thanks.

**Comment by webron** [comment]
You can have references to external files, but those would only work if those files are hosted. You can't edit multiple files with the editor.

**Comment by shockey** [comment]
Here's some docs that cover how to make remote references in Swagger/OpenAPI: https://swagger.io/docs/specification/using-ref/

**Comment by dantebarba** [comment]
@webron I'm currently using the online editor and there is no way to reference external files. I'm switching to the local editor, and I will push my project on github so I can reference yaml files directly.

**Comment by dantebarba** [comment]
I managed to reference from the online editor using absolute path for example: `$ref: "https://raw.githubusercontent.com/....../commons.json#/definitions/Error"`

Using the online editor I can't clone my github project and use relative paths to resolve the definitions. How can I use the editor (online or offline) and step into the project root folder?. 

Is there any way to have something like this: $ref: "commons/commons.json#/definitions/Error" and the editor being able to resolve it.

**Comment by webron** [comment]
@dantebarba are you using the online editor at http://editor.swagger.io or do you use swaggerhub.com?

**Comment by dantebarba** [comment]
Swaggerhub. I contacted support and they recommended to use domains. I added my common definitions in my domain, I reference them, try to  push to github, but fails. Support said that they will look into, looks  like a bug on the integration.

**Comment by webron** [comment]
Okay, in that case, please continue using the SwaggerHub's support for any further issues with it. They use modified versions of the open source version and are better equipped to provide you with the answers you'd need.
