### ISSUE TITLE
Suppor references from an external file

### ISSUE THREAD

**Issue by CsatariGergely** [swagger-api/swagger-editor#1534]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Feature reques
| Which Swagger/OpenAPI version?      | Version 2
| Which Swagger-Editor version?       | 
| How did you install Swagger-Editor? |  with npm
| Which broswer & version?            | Firefox
| Which operating system?             | Fedora 25

### Demonstration API definition

Described in https://github.com/OAI/OpenAPI-Specification/tree/master/examples/v2.0/json/petstore-separate/spec

### Configuration (browser query string, constructor, config.yaml)

N/A

### Expected Behavior

In case of references external to the main file the additional files should be also interpreted and the references should work.

### Current Behavior

No external references followed. 

### Possible Solution

This could be achieved in two alternative ways:

1. A zip file is uploaded with all the referred files. The zipfile is then unzipped with its directory structure and interpreted by swagger-editor
2. All referred files are made available by the uploader and a base url is provided for every upload. Swagger-editor loads the files from the provided url.

I would prefer the first approach, but woudl be very happy with the 2nd also.   

### Context

I store the definiton files in a Git repo, but not the merged file. Now I need to create a merged file with json-refs and feed that to swagger-tools. This is an extra step in our workflow and makes the autometic rendering of our json files via swagger-editor on the server impossible.

**Comment by webron** [comment]
The Editor is intended to be used with a single file. You can still use references, but they'd have to be fully qualified URLs and not relative ones.

We might implement a way to set a base URL for references, but it won't be soon.

**Comment by hkosova** [comment]
Related: https://github.com/swagger-api/swagger-editor/issues/1409

**Comment by stevendearborn** [comment]
This worked in Swagger 2.x editor. Why not implement/migrate the same feature to OpenAPI 3.0?

How do we get existing teams to move to 3.0 without resolving all external references?

**Comment by webron** [comment]
@stevendearborn it sounds like you're confusing the versions of the tool with the versions of the spec.

**Comment by carldunham** [comment]
Nor can people building new APIs in OpenAPI 3.0 use the Swagger Editor to edit them, if we use external references.

**Comment by webron** [comment]
Closing this in favor of #1409.
