### ISSUE TITLE
editor crashes upon loading code.

### ISSUE THREAD

**Issue by iplayfast** [swagger-api/swagger-editor#1541]
attached file, was only renamed api_v4.json.txt from api-v4.json no other changes.
[api_v4.json.txt](https://github.com/swagger-api/swagger-editor/files/1428716/api_v4.json.txt)

| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  bug
| Which Swagger/OpenAPI version?      |One at https://editor.swagger.io and Oct 30'th github code compiled locally.
| Which Swagger-Editor version?       |
| How did you install Swagger-Editor? | npm start
| Which broswer & version?            | chrome Version 60.0.3112.78 (Official Build) (64-bit), Opera 38.0.2220.41
| Which operating system?             | lInux mint 18

### Demonstration API definition
Load the attached file, editor becomes locked up.

**Comment by webron** [comment]
Thanks for the report - this is another example of https://github.com/swagger-api/swagger-ui/issues/1919. Please add a comment there with the attached file so we can have that as a reference.
