### ISSUE TITLE
Accept header in requests not updated after replacing content.<media-type> in code

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-editor#1543]
If this is a UI issue and not an Editor issue, let me know.

| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 3.0
| Which Swagger-Editor version?       | 3.1.13 (UI 3.4.2)
| How did you install Swagger-Editor? | http://editor.swagger.io
| Which broswer & version?            | Chrome 62
| Which operating system?             | Windows 7

### Demonstration API definition
```yaml
openapi: 3.0.0
info:
  version: 0.0.0
  title: test
servers:
  - url: http://httpbin.org

paths:
  /get:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json: {}
```

### Steps to Repoduce
1. Open the Editor and paste the spec above.

2. In the UI, expand the operation.

3. In the editor, replace `application/json` with `application/xml`.
=> Note that the content type combobox in the UI now shows "application/xml" - OK.

4. Try it out.

### Expected Behavior
Request is sent with `accept: application/xml`.

### Current Behavior
Request is sent with `accept: application/json`.

### Context
The UI lags behind the code updates.

![content-type](https://user-images.githubusercontent.com/8576823/32230871-238efd84-be65-11e7-91c5-eb33172dab80.gif)

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger-ui#3853
