### ISSUE TITLE
Add suport for generating python2 flask stubs

### ISSUE THREAD

**Issue by jonDel** [swagger-api/swagger-editor#1551]
<!Thanks for filing an issue 😄 ! Before you submit, please read the following:

Search open/closed issues before submitting since someone might have asked the same thing before!

Issues on GitHub are only related to problems of Swagger-Editor itself. We'll try to offer support
here for your use case, but we can't offer help with projects that use Swagger-UI indirectly,
like Springfox or swagger-node.

If your issue has to do with the right-hand side of the Editor, you're likely talking about
Swagger-UI. Please file your issue there instead: https://github.com/swagger-api/swagger-ui/issues/new

Likewise, we can't accept features or bugs within the Swagger/OpenAPI specifications themselves,
or anything that violates the specifications.

-->

Add suport for generating python2 flask stubs

| Feature request |  
| Swagger 2.0 |
| Swagger-Editor version 3.x |
| Swagger-Editor online http://editor.swagger.io/  and Docker last official version | 

### Expected Behavior
Generate python flask stub server for python2 and python3, not only python3

### Current Behavior
There is no option to switch from python3 to python2, only hard-coded python3

### Possible Solution
Split the option python-flask to 2 options:  python3-flask and python2-flask, linking each option to its corresponding swagger-codegen cli command:
python3: https://github.com/swagger-api/swagger-codegen/wiki/Server-stub-generator-HOWTO#python-flask-connexion
python2:  https://github.com/swagger-api/swagger-codegen/wiki/Server-stub-generator-HOWTO#python2-flask-connexion

### Context
Generating stub server for python2-flask

**Comment by shockey** [comment]
Hi @jonDel, thanks for the request!

The menu items aren't controlled by the Editor itself - we fetch a list of available clients and servers from the Generator service: http://petstore.swagger.io/?url=https://generator.swagger.io/api/swagger.json

@webron, where should this request live?

**Comment by webron** [comment]
https://github.com/swagger-api/swagger-codegen

**Comment by shockey** [comment]
Closing, as this is a Codegen issue.

@jonDel, feel free to re-file this at the repository @webron mentioned.

**Comment by zmlcc** [comment]
@webron  @shockey 

If call https://generator.swagger.io/api/gen/servers/python-flask with POST payload 
```
{
  "options": {
    "supportPython2": true
  },
  "spec": {
   __SPEC_DATA__
  }
}    
```
it gives  python2-flask stubs

so the Editor could control  generating python2 or python3 code .  
I suggest add the "**python2-flask**" option for python2 case

**Comment by shockey** [comment]
@zmlcc, in the Editor we're just listing the server generators provided by `GET /gen/servers`, so IMO it's on the Codegen project to list the generators they use correctly - feel free to open a ticket there!
