### ISSUE TITLE
Problems with Basic Authentication

### ISSUE THREAD

**Issue by hopeSSL** [swagger-api/swagger-editor#1555]
Hi everybody,

I am having some problems to test my API in "Swagger - Editor".
When I test the URL in HttpRequester client with my authentication data ,this return me the next information

![imagen](https://user-images.githubusercontent.com/33484658/32547514-ed1140c2-c482-11e7-8343-22cd3abffadd.jpg)

The response would be

200 OK
Access-Control-Allow-Origin:  *
Content-Length:  10567
Content-Type:  application/json
Date:  Wed, 08 Nov 2017 10:43:03 GMT
Server:  Microsoft-IIS/8.5
WWW-Authenticate:  Basic realm="www.xxxxxxxxxxx.com"
X-Powered-By:  PHP/7.0.9, ASP.NET

Therefore, the response is OK. However, if I test the same URL in "Swagger -Editor"  with basic authentication where I put the same data that used in HttpRequester , I receive the following error

![imagen2](https://user-images.githubusercontent.com/33484658/32547748-cb377a74-c483-11e7-9760-1e2e8dbbb7f5.PNG)

Could someone help me to solve this problem?
Thanks in advance.

**Comment by webron** [comment]
Most likely you need to enable CORS in your server. Take a look at https://github.com/swagger-api/swagger-ui#cors-support.

**Comment by hopeSSL** [comment]
Thanks for your early answer. But , I have already enabled CORS in my server IIS7 in this way

<?xml version="1.0" encoding="utf-8"?>
<configuration>
 <system.webServer>
   <httpProtocol>
     <customHeaders>
       <add name="Access-Control-Allow-Origin" value="*" />
     </customHeaders>
   </httpProtocol>
 </system.webServer>
</configuration>

This code is in the web.config file and other requests work, except basic authentication

**Comment by webron** [comment]
That's only one header out of 3. You're missing `Access-Control-Allow-Methods` and `Access-Control-Allow-Headers`.

**Comment by hopeSSL** [comment]
Thanks again. This is my web.config file

![captura](https://user-images.githubusercontent.com/33484658/32578030-07817914-c4dc-11e7-8fb9-db1b2c64457c.PNG)

However, it doesn't work in swagger -editor

**Comment by webron** [comment]
Take a look at the browser's network console. Also, which browser do you use?

**Comment by hopeSSL** [comment]
I use Google Chrome and Mozilla Firefox, but it doesn't work to any.
Which exact characteristics do I look at the browser's network console?

Thanks

**Comment by webron** [comment]
The actual requests being sent when you execute the call + the responses.

**Comment by hopeSSL** [comment]
I execute swagger editor in the same way that the second image of my first entry at Chrome and Mozilla. I don

**Comment by webron** [comment]
Okay, but I need to see the network console, not just the result in the editor.

**Comment by shockey** [comment]
> This code is in the web.config file and other requests work, except basic authentication

We see this sometimes, where CORS headers are not attached to HTTP responses with errors. Please make sure that the `Access-Control` headers are present if your server is sending back a 401 Unauthorized for the authorization 😄

**Comment by hopeSSL** [comment]
Hi,
This is the result in the editor when I execute the call about basic authentication

![captura](https://user-images.githubusercontent.com/33484658/32594114-fa03c2a2-c52a-11e7-95c7-0f0ce11968fc.PNG)

Thanks

**Comment by hopeSSL** [comment]
Hi,

This is the result of the request in the network console

![captura](https://user-images.githubusercontent.com/33484658/32594450-5f86c556-c52c-11e7-9ece-9875b32fb909.PNG)

Thanks,

**Comment by webron** [comment]
Looking for something that looks more like this: 
<img width="1920" alt="screen shot 2017-11-09 at 12 05 09" src="https://user-images.githubusercontent.com/241629/32627114-43ad39a4-c546-11e7-871e-9f318226a6c5.png">

**Comment by hopeSSL** [comment]
I'm sorry. But I don't know how to find this information. Could you tell me where I  can see it in browser?

Thanks

**Comment by webron** [comment]
Assuming Firefox, Tools->Web Developer->Network.
In Chrome, View->Developer->Developer Tools, and switch to the Network tab.

You should execute the API calls only after you have the Network console open.

**Comment by hopeSSL** [comment]
![imagen](https://user-images.githubusercontent.com/33484658/32636808-b2f7b3aa-c5b6-11e7-9ccb-e6d3ca20281b.png)

**Comment by webron** [comment]
Thanks, that explains it. For some reason, your web server requires authentication for OPTION calls, but it shouldn't. You need to disable that.

**Comment by hopeSSL** [comment]
Ok, I have already found a solution. I capture the method OPTION in my API and in this moment executes the next code:

```
if ($method == "OPTIONS")
{
     header("HTTP/1.1 202 Aceppted");  
     return true;
}				

```

In this way,  the flow continues and executes the method requested: GET, POST,PUT or DELETE

Thanks so much for your help

**Comment by webron** [comment]
Great, happy to hear you got it sorted out.
