### ISSUE TITLE
Java codegen artifact does not build if items array contains {} in object definition

### ISSUE THREAD

**Issue by kylos101** [swagger-api/swagger-editor#1556]
The Java codegen artifact does not build if the definition of the items array is {}, but it does pass validation.

| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |   bug
| Which Swagger/OpenAPI version?      |   2.0
| Which Swagger-Editor version?       |  editor.swagger.io
| How did you install Swagger-Editor? |  n/a
| Which broswer & version?            | Chrome 62
| Which operating system?             | Windows 7 

### Demonstration API definition
In swagger editor, using your petstore demo, change line 670 to {} (an empty object), click on Generate Client > Java, then try "mvn install", it should fail building.

### Expected Behavior
A warning or an error in Swagger Editor.
No ability to generate a client until the spec is "valid".

### Current Behavior
No warning or error is displayed.
I am able to Generate the Java client.
The Java client cannot build, this is because class members lack type info.

```Java  
  @SerializedName("photoUrls")
  private  photoUrls = ; // see here how photoUrls lacks a type definition?
```

### Possible Solution
If this is a valid condition in some circumstances for certain clients, display a warning.
If this is not a valid condition ever, display an error and prevent.
Disable generate client if an error is present.

### Context
I shared my YAML with a coworker (it didn't have any errors).
They tried generating a Java client, and were unable to build it.

**Comment by webron** [comment]
Thanks for the report. Issues regarding code generation should be opened against https://github.com/swagger-api/swagger-codegen.

**Comment by kylos101** [comment]
@webron No prob! Quick question, is it possible this bug impacts both codegen and editor? For example, it would have been ideal for Editor to show an error. If it had shown an error, we never would have tried exporting the client.

**Comment by webron** [comment]
Generally speaking, yes, a bug can impact both. That said, an empty items object is not wrong.

**Comment by kylos101** [comment]
Understood, thanks a lot, Ron. Have a good one.
