### ISSUE TITLE
Support: how to response array with json

### ISSUE THREAD

**Issue by bruceforlearn** [swagger-api/swagger-editor#1557]
Hello @shockey 
First thanks for your help 
I want to write a API respond which response a array as blow:
but I get respond is :
[
  ""
]
could you please help me again?

definitions:
  DeviceArray:
    type: array
    items:
      type:  string
    example:
      - {"DeviceID": 103609131103,"NetworkName": "nzp-20007-gnd-rt-01","RelativeName": "NZP-20007-GND-RT-01.PST.SYTECNMS.NET","Type": null}
      - {"DeviceID": 105621398103,"NetworkName": "nzp-20007-gnd-as-01","RelativeName": "NZP-20007-GND-AS-01.PST.SYTECNMS.NET","Type": null}
      - {"DeviceID": 122403148102,"NetworkName": null,"RelativeName": "BEAS/U_NTU_001","Type": "NTU"}
      - {"DeviceID": 165002297102,"NetworkName": null,"RelativeName": "BEAS/G_HSNS SDP_001","Type": "Alcatel MSAP"}
      - {"DeviceID": 165002320102,"NetworkName": "10.6.194.126","RelativeName": "BEAS/G_ONEA1424X_001","Type": "OneAccess IAD/Router"}
      - {"DeviceID": 160885080102,"NetworkName": null,"RelativeName": "BEAS/U_CISCO_1921_001","Type": "Cisco Packet Switch"}

**Comment by webron** [comment]
For general questions on how to use the spec, please use the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket).
