### ISSUE TITLE
Editor is unable to resolve http $ref

### ISSUE THREAD

**Issue by dylan-colaco** [swagger-api/swagger-editor#1561]
My YAML file contains some definitions in files hosted remotely(on S3), referenced using $ref: 'https://s3.amazonaws.com...." . My swagger-codegen eclipse plugin is able to resolve these and generate models, but the online swagger editor says "Reference could not be resolved"

**Comment by webron** [comment]
Is this when rendering the definition or when trying to generate code from it through the editor?

**Comment by dylan-colaco** [comment]
When rendering the definition

**Comment by dylan-colaco** [comment]
correction: both

**Comment by webron** [comment]
The rendering is probably due to CORS - https://github.com/swagger-api/swagger-ui#cors-support

**Comment by dylan-colaco** [comment]
I've enabled CORS on S3, now the documentation renders properly even for referenced definitions on the older editor(http://editor2.swagger.io/), but when generating the json, it keeps the reference to the remote yaml instead of converting the definitions into json, and model generations is failing with a 500 error. The newer one(http://editor.swagger.io/) throws an error "Resolver error at definitions...." "Could not resolve reference because of: Could not resolve pointer: "

**Comment by webron** [comment]
What do you mean by "generating the json"?

**Comment by shockey** [comment]
@dylan-colaco, can you provide a copy of (or link to) your definition? Without it, all we can do is speculate about what the problem is.

**Comment by dylan-colaco** [comment]
@webron, by generate json, I mean file>download json on the swagger editor.

@shockey 
I've reduced my definition to the bare minimum to demonstrate the issue: https://gist.github.com/dylan-colaco/9a8791fa5c77f41d1eb8aea388f10d87

**Comment by webron** [comment]
It sounds like you expect the editor to dereference the remote references when you download as JSON (or YAML) - that's something the editor doesn't do (and won't). The download option simply gives you a file copy of what you have in the editor, and will convert it if needed to YAML or JSON.

As a side note, your referenced definitions have mistakes in them. They seem to use internal references that don't exist.

**Comment by dylan-colaco** [comment]
@webron 
ok. The multi-file-swagger utility seems to do this, so I guess I will continue to use that and paste the generated json to verify. Thanks for clarifying.

**Comment by webron** [comment]
Is there any other pending issue or can the ticket be closed?

**Comment by dylan-colaco** [comment]
Please close it

Thanks
