### ISSUE TITLE
swagger 2.0 response issue ?

### ISSUE THREAD

**Issue by bruceforlearn** [swagger-api/swagger-editor#1563]
Hello Everyone,

I write a API at swagger 2.0 and no error exist 

but I download it as nodejs and run 

the /Assurance/v1/Place/20416436103/Customer/1-7MWK-3013/Devices/ respond is :  [
    ""
]

what is wrong with it ?

**Comment by bruceforlearn** [comment]
swagger: "2.0"
info:
  version: 1.0.0
  title: title
  description: description
  termsOfService: terms
host: localhost:8090
paths:
  /Assurance/v1/Place/20416436103/Customer/1-7MWK-3013/Devices/:
    get:
      produces:
        - application/json
      responses:
        '200':
          description: Ok
          schema:
            type: array
            items:
              $ref: '#/definitions/DeviceArray'
  /assurance/v1/Customer123/places:
    get:
      produces:
        - application/json
      responses:
        '200':
          description: Ok
          schema:
            type: array
            items:
              $ref: '#/definitions/TAMplaces'
  /Assurance/v1/Devices/165002320102:
    get:
      produces:
        - application/json
      responses:
        '200':
          description: Ok
          schema:
            type: array
            items:
              $ref: '#/definitions/DeviceDetails'
  /assurance/v1/Ports/PortID123/rfs:
    get:
      produces:
        - application/json
      responses:
        '200':
          description: Ok
          schema:
            type: array
            items:
              $ref: '#/definitions/PortDetailsRFS'
              
  /fileUpload:
    post:
      x-swagger-router-controller: TestController
      operationId: uploadFile
      consumes:
        - application/x-www-form-urlencoded 
      parameters:
        - in: formData
          name: theFile
          type: string
        - in: formData
          name: stringMetadata
          type: string
        - in: formData
          name: intMetadata
          type: integer
          format: int32
      responses:
        200:
          description: the stringMetadata passed in
          schema:
            type: string
definitions:
  DeviceArray:
    type: array
    x-swagger-router-model: io.swagger.test.models.DeviceArray
    items:
      type: object
      properties:
        DebiceID:
          type: string
        NetworkName:
          type: string
        RelativeName:
          type: string
        Type:
          type: string
    example:
      - DeviceID: 105621398103
        NetworkName: nzp-20007-gnd-as-01
        RelativeName: NZP-20007-GND-AS-01.PST.SYTECNMS.NET
        Type: null
      - DeviceID: 1036091311033
        NetworkName: nzp-20007-gnd-rt-01
        RelativeName: nzp-20007-gnd-RT-01
        Type: NTU
      - DeviceID: 122403148102
        NetworkName: null
        RelativeName: BEAS\/U_NTU_001
        Type: null
      - DeviceID: 165002297102
        NetworkName: null
        RelativeName: BEAS/G_HSNS SDP_001
        Type: Alcatel MSAP
      - DeviceID: 165002320102
        NetworkName: 10.6.194.126
        RelativeName: BEAS/G_ONEA1424X_001
        Type: OneAccess IAD/Router
      - DeviceID: 160885080102
        NetworkName: null
        RelativeName: BEAS/U_CISCO_1921_001
        Type: Cisco Packet Switch
  TAMplaces:
    type: object
    x-swagger-router-model: io.swagger.test.models.TAMplace
    required:
      - placeId
    properties:
          placeId:
            type: integer
          name:
            type: string
          relativeName:
            type: string
          fullName:
            type: string
          alias1:
            type: string
          alias2:
            type: string
          description:
            type: string
          address:
            type: string
          address1:
            type: string
          address2:
            type: string
          address3:
            type: string
          xcoordinate:
            type: string
          ycoordinate:
            type: string
          geographicType:
            type: string
          geographicgridType:
            type: string
          geographicZcoord:
            type: string
          geographicLocationId:
            type: string
          localAddress:
            type: string
          localAddress1:
            type: string
          localAddress2:
            type: string
          localAddress3:
            type: string
          townCity:
            type: string
          localDescription:
            type: string
          placeType:
            type: string
            example: Customer Site
          sourceSys:
            type: integer
            example: 101
  DeviceDetails:
    type: object
    x-swagger-router-model: io.swagger.test.models.DeviceDetails
    required:
      - DeviceID
    properties:
        DeviceID:
          type: integer
          example: 165002320102
        name:
          type: string
          example: BEAS/G_ONEA1424X_001
        networkName:
          type: string
        description:
          type: string
        type:
          type: string
        subType:
          type: string
        location:
          type: integer
        Ports:
          items:
            properties:
              portId:
                type: integer
                example: 165002321102
              name:
                type: string
                example: DSL-LINE
              relativename:
                type: string
              RFS:
                items:
                  properties:
                    circuitid:
                      type: integer
                    name:
                      type: string
                    designation:
                      type: string
                      example: SHA0002665
                    a-deviceid:
                      type: integer
                      example: 146308807102
                    a-portid:
                      type: integer
                      example: 153079974102
                    z-deviceid:
                      type: integer
                    z-portid:
                      type: integer
                    description:
                      type: string
                    Numbers:
                      items:
                        properties:
                          Name:
                            type: integer
                          Value:
                            type: string
                        type: object
                      type: array
                  type: object
                type: array
            type: object
          type: array
  PortDetailsRFS:
    type: object
    x-swagger-router-model: io.swagger.test.models.PortDetailsRFS
    required:
      - deviceid
    properties:
        deviceid:
          type: integer
        name:
          type: string
        networkName:
          type: string
        description:
          type: string
        type:
          type: string
        subType:
          type: string
        location:
          type: integer
        Ports:
          items:
            properties:
              portId:
                type: integer
              name:
                type: string
              relativename:
                type: string
              RFS:
                items:
                  properties:
                    circuitid:
                      type: integer
                    name:
                      type: string
                    designation:
                      type: string
                    a-deviceid:
                      type: integer
                    a-portid:
                      type: integer
                    z-deviceid:
                      type: integer
                    z-portid:
                      type: integer
                    description:
                      type: string
                    Numbers:
                      items:
                        properties:
                          Name:
                            type: integer
                          Value:
                            type: string
                        type: object
                      type: array
                  type: object
                type: array
              Numbers:
                items:
                  properties:
                    Name:
                      type: integer
                    Value:
                      type: string
                  type: object
                type: array
            type: object
          type: array

**Comment by bruceforlearn** [comment]
could you please help ?

thank you

**Comment by webron** [comment]
This is not an issue with the editor. If you're using the generator to generate the code, file the ticket with that project. If you're using it directly within a different project, open it with that one instead.
