### ISSUE TITLE
CsharpDotNet2 Generator Doesn't Add Argument Default Values

### ISSUE THREAD

**Issue by protegesolutions** [swagger-api/swagger-editor#1567]
Generating C#.NET client code using the online Swagger Editor fails to insert "= null" for arguments not marked "required: true". The standard/old(?) csharp generator behaves as expected.

| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 2
| Which Swagger-Editor version?       | Not displayed
| How did you install Swagger-Editor? | Didn't - web version
| Which browser & version?            | Firefox 56.0.1 64bit
| Which operating system?             | Windows 7 Pro 64

### Demonstration API definition

```
https://gist.github.com/protegesolutions/2447f5c614f3d2f248925191c0533abc
```

### Configuration (browser query string, constructor, config.yaml)

Not applicable - browser version.

### Expected Behavior
Where call arguments do not have "required: true" the resulting c#.NET client code should have "= null" included, eg public Something GetSomething(int? offset = null, int? limit = null).
### Current Behavior
The CsharpDotNet2 generator doesn't do this while the csharp one does. Even adding "default: null" or whatever doesn't add the default values.
### Possible Solution
I guess the CsharpDotNet2 generator needs some work.
### Context
Without this, the generated client code requires ALL arguments for call to be specified which is laborious and messy. With default values, only the non-default arguments need to be provided.

**Comment by webron** [comment]
Please file the ticket on swagger-codegen.
