### ISSUE TITLE
Examples in swagger file are not included in html/html2 document 

### ISSUE THREAD

**Issue by MSourabh17** [swagger-api/swagger-editor#1581]
I have written my swagger file in yaml with examples for all parameters in request body as well as in responses.
When i generated client by html/html2 , it only shows datatypes of all parameters like string, integer etc.
It does not shows sample examples of parameters .
Is there any way to include the sample examples with datatypes as well in swagger documentation

**Comment by shockey** [comment]
Hi @MSourabh17! Thanks for the report.

The `Generate Server`/`Generate Client` options are powered by Swagger-Codegen, so you should file an issue with them: https://github.com/swagger-api/swagger-codegen/issues
