### ISSUE TITLE
View issue - The nested objects are now hidden for some cases (in object definitions and example section of i/o parameters to the methods)

### ISSUE THREAD

**Issue by B-Piyush** [swagger-api/swagger-editor#1585]
Looks like the 'online swagger editor' got some updates recently which are causing issue with the view section. 
The nested objects are now hidden for some cases (in object definitions and example section of i/o parameters to the methods). It used to show all objects properly in previous versions.

Attached are before and after screenshots of same yaml file.

Methods - I/O Example section - before
![before1](https://user-images.githubusercontent.com/34345576/33727588-79a216a4-db46-11e7-9fa7-7be6c000bd5a.JPG)

Example section - after
![after1](https://user-images.githubusercontent.com/34345576/33727601-821f4ea0-db46-11e7-9de1-9aa61062426f.JPG)

Models - Before
![before2](https://user-images.githubusercontent.com/34345576/33727608-87d7ff90-db46-11e7-8e4b-fca3200a6fc2.JPG)

Models - After
![after2](https://user-images.githubusercontent.com/34345576/33727615-8ccfbc7c-db46-11e7-9a8a-08c653742398.JPG)

Please advise and fix.

**Comment by B-Piyush** [comment]
Tried browsers Edge, Chrome & Firefox - issue persists. 
Screenshots are from firefox.

**Comment by webron** [comment]
I've asked you to follow the issue template when filing the ticket here because we need that information. Which version of the editor do you use? We'd also need an API definition that reproduces the issue.

**Comment by B-Piyush** [comment]
Not sure how to find the version of the editor. I m accessing it using the link provided on the swagger.io
swagger.io -> Tools -> Swagger Tools -> Swagger Editor -> Online Editor

https://editor.swagger.io//?_ga=2.208870036.729951174.1512659382-1712861624.1508257906#/


Attached zip has the source API.
[eTransferReceiver_v0.02.zip](https://github.com/swagger-api/swagger-editor/files/1539958/eTransferReceiver_v0.02.zip)

**Comment by B-Piyush** [comment]
The UI is now correctly displaying the nested object references and I/o examples.

Thanks webron, shockey & team for quick resolution. Appreciate your help.
