### ISSUE TITLE
arbitrary line wrapping and change of block scalar indicators (by default?)

### ISSUE THREAD

**Issue by jfeltesse-mdsol** [swagger-api/swagger-editor#1586]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  bug
| Which Swagger/OpenAPI version?      | 2
| Which Swagger-Editor version?       | 3.1.18
| How did you install Swagger-Editor? | git
| Which browser & version?            | FF 58.0b9
| Which operating system?             | macOS

### Demonstration API definition
```yaml
x-test: |-
  hello
  there

x-test2: >-
  hello
  again

x-test3: |-
   word word word word word word word word word word word word word word word word word word word word word word word
   word word word word word word word word word word word word word word word word word word word word word word word

x-test4: >-
   word word word word word word word word word word word word word word word word word word word word word word word
   word word word word word word word word word word word word word word word word word word word word word word word

swagger: '2.0'
info:
  version: '1'
  title: test

paths: {}
```
↓↓↓↓↓↓
![screen shot 2017-12-08 at 12 47 05 pm](https://user-images.githubusercontent.com/13656490/33750501-b0446d2a-dc17-11e7-8ddd-49d6e374b59d.png)

### Configuration (browser query string, constructor, config.yaml)
none

### Expected Behavior
When importing a file it should not modify the contents of strings and preserve the block scalar indicator of my choosing, regardless of the line length.

### Current Behavior
`|-`:
- short lines: it doesn't do anything special, 🙆‍♂️ 
- lines above 80 characters: it replaces `|-` by `>-`, introduces new lines in the content to wrap the lines within 80 characters and adds more new lines in the content to fit the rules imposed by `>-` 🙅‍♂️
 
`>-`:
- short lines: it inlines them 🤔 🙅‍♂️ 
- lines above 80 characters: it introduces new lines in the content to wrap the lines within 80 characters 🙅‍♂️ 

### Possible Solution
- wrapping: don't impose a 80 characters limit. It's pretty much standard by now to code with a limit of 120 chars, and in any case it's not the job of the editor to dictate a style guide.
- indicator: just leave it alone like it does with short lines.

### Context
We're trying to standardize the way we write our OpenAPI spec files across our organization. We settled with 120 chars-long lines and with using the `|-` indicator, not `|` or `>`/`>-`.
Every time someones uses the swagger-editor to do even the slightest change, it will change the content as described above, making for a lot of unrelated and uncalled for changes.

I don't know if these can be configured in any way but even if they were, the defaults should be changed to doing nothing because the same problem would happen if people use the online editor instead of a local, customized version.

**Comment by shockey** [comment]
Fixed! As of #1967 we no longer meddle with imported YAML content at all.
