### ISSUE TITLE
Fields of format time or date default to "string"

### ISSUE THREAD

**Issue by nkolban** [swagger-api/swagger-editor#1588]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 3.0.1
| Which Swagger-Editor version?       | Online as of date of post
| How did you install Swagger-Editor? |  Online
| Which broswer & version?            | Chrome 63.0.3239.84
| Which operating system?             |  Windows 10

### Demonstration API definition

https://gist.github.com/nkolban/fd6aa143ed10af5446fd2950c849e503

### Configuration (browser query string, constructor, config.yaml)
Not applicable

### Expected Behavior

Here is the example model produced for the operation:

```
{
  "action": "start",
  "params": {
    "input1": {
      "decimalField": 0,
      "boField": {
        "fieldA": "string",
        "fileB": 0,
        "fieldC": true,
        "anotherBO": {
          "x": "string",
          "y": "string",
          "z": "string"
        },
        "fieldD": [
          "string"
        ]
      },
      "booleanField": true,
      "integerField": 0,
      "timeField": "string",
      "dateField": "string",
      "anyField": "string",
      "stringField": "string"
    }
  }
}
```

Note the fields called `timeField` and `dateField`.  These are defined in the JSON Schema as:

```
       timeField:
          type: string
          format: time
        dateField:
          type: string
          format: date
```

What I was expecting was that the example fields would be generated as [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format strings and not the word `string`.

For example,

```
...
      "timeField": "2017-12-09T18:14:01Z",
      "dateField": "2017-12-09",
...
```

### Current Behavior
See above.

### Possible Solution
Detect that the field is a date or time format field and generate a default ISO 8601  string based on current time.

### Context
Am generating OpenAPI descriptions by interrogating existing servers.  Goal is  for end user to query server which generates OpenAPI which is then copied into Swagger editor for testing.  Generated sample data for the payload of the request should not be the word `string`.

**Comment by webron** [comment]
A few things here. `time` is not a recognized format in OAS and as such, will not affect the rendering. It might be added at some point in the future to the OAS format registry, but there's no formal work on that yet.

`date` _is_ a recognized format which would have the format `YYYY-MM-DD` according to the spec. While compliant with ISO 8601, it doesn't mean that's the exact format you'd expect. You are right that the examples should render that more appropriately. 

@shockey can elaborate more on this, but there might be a way to extend the UI to render user-created formats based on their needs. If that were the case, you'd have to create your own plug-in and run it locally to use.

**Comment by nkolban** [comment]
Thank you sir.  I had misread the `time` property ... what I mean to use was `date-time` which does appear to be exposed by OAS.

**Comment by hkosova** [comment]
Closing as implemented - Swagger UI 3.20.0+ and Swagger Editor 3.6.16+ generate date/time examples for both `format: date` and `format: date-time`.

![Date/time property examples in Swagger UI](https://user-images.githubusercontent.com/8576823/62865765-f5f6cb00-bd17-11e9-8ea8-2d92a18f9fcd.png)

**Comment by opendba** [comment]
Latest Swagger Editor correctly generates example values for fields of type date-time or date as describer.  However it still does not correctly show such fields from examples provided in swagger schema (or openapi schema).

![image](https://user-images.githubusercontent.com/6765564/69984815-a6e0da00-1542-11ea-9b07-56a4e0025d52.png)

**Comment by hkosova** [comment]
@opendba you need to add quotes around the example values:
```yaml
example:
  timeField: '2019-03-02T18:16:14.243Z'
  dateField: '2019-12-02'
  stringField: abcdef
```
Without the quotes, these values are parsed as [YAML timestamps](https://yaml.org/type/timestamp.html) which are different from strings.

**Comment by opendba** [comment]
Thank you very much. Everything works as expected!
