### ISSUE TITLE
$ref in parameters is not properly detected, and flagged as error

### ISSUE THREAD

**Issue by weppos** [swagger-api/swagger-editor#1600]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 3.0
| Which Swagger-Editor version?       | 3.1.20 and 3.2.0
| How did you install Swagger-Editor? | git clone + npm start
| Which broswer & version?            | Chrome 63
| Which operating system?             | MacOS

### Demonstration API definition

```yaml
openapi: 3.0.0
info:
  title: DNSimple API
  version: 2.0.0
  contact:
    name: DNSimple Support
    email: support@dnsimple.com
    url: 'https://dnsimple.com/contact'
  description: >-
    [DNSimple](https://dnsimple.com) provides DNS hosting and domain registration that is simple and friendly.
  termsOfService: 'https://dnsimple.com/terms'
externalDocs:
  url: 'https://developer.dnsimple.com'
servers:
  - url: 'https://api.dnsimple.com/v2'
    description: DNSimple Production API
    variables: {}
paths:
  '/{account}/domains':
    summary: Operations on domain collections.
    parameters:
      - $ref: '#/components/parameters/Account'
    get:
      description: List domains in the account.
      parameters:
        - $ref: '#/components/parameters/Account'
      operationId: listDomains
      tags:
        - domains
      responses:
        '200':
          description: >-
            Depending on how you are authenticated you will see all the accounts
            you have access to or the account you used to authenticate.
components:
  parameters:
    Account:
      name: account
      in: path
      required: true
      description: The account id
      schema:
        type: integer
    Domain:
      name: domain
      in: path
      required: true
      description: The domain name or id
      schema:
        type: string
```

### Configuration (browser query string, constructor, config.yaml)

all default, no query string

### Expected Behavior

There should be no validation error for the `{account}` parameter.

### Current Behavior

<img width="604" alt="screen shot 2017-12-26 at 5 08 45 pm" src="https://user-images.githubusercontent.com/5387/34360293-7717af2a-ea5f-11e7-8cb2-69e63fe60905.png">

```
Semantic error at paths./{account}/domains
Declared path parameter "account" needs to be defined as a path parameter at either the path or operation level
```

### Context

According to the specs, an item in the `parameters` collection can be either a Parameter Object or Reference object.
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#fixed-fields-7

However, if we use the Parameter Object itself, it works:

```
      parameters:
      -  name: account
          in: path
          required: true
          description: The account id
          schema:
            type: integer
```

If we use a reference, it doesn't:

```
      parameters:
        - $ref: '#/components/parameters/Account'
```

and instead a validation error is shown.

**Comment by shockey** [comment]
OpenAPI 3.0 definitions shouldn't be subject to semantic validation yet (cc swagger-api/swagger-editor#1599), so this is a bug!

**Comment by shockey** [comment]
Hi @weppos! I've released `swagger-editor@3.2.1` which includes a fix for this bug.

Thanks for the report!

**Comment by weppos** [comment]
Thanks @shockey! I confirm it works great now.

**Comment by alexander-frolov** [comment]
Hi @shockey,

It appears that the issue is fixed for OAS 3.0.0, but still exists for OAS 2.0. It worked with no problems some time ago.

**Comment by shockey** [comment]
Hey @alexander-frolov, can you provide a sample API definition that demonstrates this issue?

**Comment by alexander-frolov** [comment]
Sure, here is a quick example:

```yml
swagger: '2.0'

info:
  version: '1.0.0'
  title: Test API
  description: Just a test API.

paths:
  /test/{id}:
    parameters:
      - $ref: '#/parameters/id'

    get:
      operationId: getTest
      summary: Get Test by Id
      responses:
        '200':
          description: OK - The request is successful.
          schema:
            type: string

parameters:
  id:
    name: id
    type: string
    description: The identifier of the test.
    in: path
    required: true
```

**Comment by shockey** [comment]
Thanks! I was looking into this last week actually - the $ref is causing a problem with our new validation system. This should be fixed soon!

**Comment by scara** [comment]
Hi @shockey,
any ETA?

TIA,
Matteo

**Comment by scara** [comment]
TNX for your reply! 👍
Apologies: I didn't look at the releases yet, just looked here.
