### ISSUE TITLE
Swagger editor chokes on regex `\Z`

### ISSUE THREAD

**Issue by axnsan12** [swagger-api/swagger-editor#1601]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 2.0
| Which Swagger-Editor version?       | editor.swagger.io
| How did you install Swagger-Editor? | i did not
| Which broswer & version?            | any
| Which operating system?             | any

### Demonstration API definition

```yaml
swagger: '2.0'
info:
  title: Snippets API
  version: v1
paths:
  /articles/:
    get:
      responses:
        '200':
          description: ''
          schema:
            required:
              - count
              - results
            type: object
            properties:
              slug:
                type: string
                format: slug
                pattern: '^[-a-zA-Z0-9_]+\Z'
```

### Configuration (browser query string, constructor, config.yaml)
N/A

### Expected Behavior
No validation errors

### Current Behavior
```
Schema error at paths['/articles/'].get.responses['200'].schema.properties['slug'].pattern
should match format "regex"
format: regex
Jump to line 20
```

### Context
swagger-validator does not seem to have a problem with this - the badge on my spec is green just fine.

**Comment by shockey** [comment]
Hi @axnsan12!

The [OpenAPI](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#properties) and [JSONSchema](https://github.com/json-schema/json-schema/wiki/Pattern#valid-values) specifications both indicate that they use JavaScript's regex dialect, as defined by the ECMA 262 specification for the language. ECMA says:

> It is a Syntax Error if FlagText of RegularExpressionLiteral contains any code points other than "g", "i", "m", "u", or "y", or if it contains the same code point more than once.
>
> [ref](https://tc39.github.io/ecma262/#sec-primary-expression-regular-expression-literals-static-semantics-early-errors)

So Swagger-Editor is more correct than Swagger-Validator actually :smile: 

The Swagger/OpenAPI 2.0 specification is no longer being worked on, so this is the law of the land... however, if you'd like to suggest that the OpenAPI 3.0 specification be changed to accommodate a wider regex vocabulary, you can open an issue over at [the OpenAPI Specification repository](https://github.com/OAI/OpenAPI-Specification).

**Comment by axnsan12** [comment]
Hmh, yes, it seems this details has eluded me 😄 

Well, I guess I will have to adapt my regexes then. 

I don't think supporting more complicated regex flavors would be a good idea from a code geneartion perspective (lowest common denominator and all that), so this can be closed.

**Comment by shockey** [comment]
> I guess I will have to adapt my regexes then

Sounds like fun :wink: 

Thanks for the report, glad we got this resolved. Closing!

**Comment by axnsan12** [comment]
By the way, for what it's worth, the original regex is still a valid javascript regex, just with unexpected semantics:

```
>> re = /^[-a-zA-Z0-9_]+\Z/
/^[-a-zA-Z0-9_]+\Z/
>> "this-is-a-slug".match(re)
null
>> "this-is-a-slugZ".match(re)
Array [ "this-is-a-slugZ" ]
```

i.e. the `\Z` is just interpreted as a redundantly escaped `Z`.

**Comment by shockey** [comment]
Hmm, yeah, you're right. I looked at the original regex wrong and was reading it as `/Z`, my apologies!

Looking at this again now.

**Comment by shockey** [comment]
So this is interesting... We use AJV for validating API definitions against a JSONSchema for each version of the OpenAPI specification we support (2.0 and 3.0). 

In their regex validator, they specifically mark regular expressions that end in `\Z` as invalid: https://github.com/epoberezkin/ajv/commit/08e87c1f30025918e04b44c36bdef61d3bafa188

I've [reached out on their Gitter channel](https://gitter.im/ajv-validator/ajv?at=5a43dc8ee43a7a150cafcdb2) for an answer to why this is being done - so stay tuned!

**Comment by axnsan12** [comment]
\Z in more advanced regex flavors has the meaning of "end-of-input anchor" (as opposed to `$` which is end of line in multi-line mode) - https://www.regular-expressions.info/anchors.html

JavaScript regexes do not support this usage, so my guess would be that they want to prevent confusion caused by `\Z` suddenly matching a literal `Z` instead of end of input, since there is usually no reason you would have an escaped Z when you really mean Z. Which I guess would be right, it did catch my error which was exactly that (I was directly printing a python regex into a swagger spec).

**Comment by axnsan12** [comment]
So in short `\Z` is *techincally* a valid regex, but probably *invalid* from the point of view of what the user intended, which is probably the reasoning for that error.

**Comment by shockey** [comment]
Yep, looks like that's the answer, see the JSONSchema JavaScript test suite: https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/master/tests/draft7/optional/ecmascript-regex.json

That being said, I do think we should add a semantic validator for this case, since the current error message is (clearly) not helpful.
