### ISSUE TITLE
Semantic error for "in: formData" Parameters and proper "consumes"

### ISSUE THREAD

**Issue by elasti-ron** [swagger-api/swagger-editor#1611]
a 'consumes' property is defined as required in the top level, but editor shows error:

> Semantic error at paths./path1.post
> Operations with Parameters of "in: formData" must include "application/x-www-form-urlencoded" or "multipart/form-data" in their "consumes" property
> 

| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      |2.0
| Which Swagger-Editor version?       |latest online version
| How did you install Swagger-Editor? | using http://editor.swagger.io/#
| Which broswer & version?            | chrome 63.0.3239.84
| Which operating system?             | macOS 10.13.2

### Demonstration API definition

```yaml
swagger: '2.0'
info:
  title: 'Demonstration of "consumes" problem'
  version: v1
basePath: /
consumes:
  - application/x-www-form-urlencoded
  - multipart/form-data
paths:
  /path1:
    post:
      parameters:
        - name: param1
          type: string
          in: formData   
      responses:
        '200':
          description: ok
```

### Expected Behavior

Error should not be displayed

### Current Behavior

Error is displayed even though the swagger definition is valid

**Comment by elasti-ron** [comment]
![swagger-error-screenshot](https://user-images.githubusercontent.com/23432602/34480639-4d9bd9bc-efb6-11e7-842c-9e04d343ece8.png)

**Comment by shockey** [comment]
Thank is fixed, thanks @elasti-ron!

**Comment by gildniy** [comment]
Here the consumes is not set to the proper "paths./path1.post", but on the parent of it!

**Comment by elasti-ron** [comment]
@gildniy the Swagger Object definition in the [swagger 2.0 spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#swagger-object) states 'consumes' in the top level object as:

> A list of MIME types the APIs can consume. This is global to all APIs but can be overridden on specific API calls. Value MUST be as described under Mime Types.

If my understanding of the specification is correct, then the value for 'consumes' on the top-level object applies to all paths in the document.

**Comment by elasti-ron** [comment]
@shockey - thanks for fixing this earlier.  It is now happening again.  As I cannot reopen this issue, I've opened a new one (#1684).

**Comment by shockey** [comment]
fixed (again!), thanks for the heads up @elasti-ron!
