### ISSUE TITLE
GOTO link not working in the Swagger Editor

### ISSUE THREAD

**Issue by tnjohansson** [swagger-api/swagger-editor#1613]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 3.0.0
| Which Swagger-Editor version?       | Latest online editor
| How did you install Swagger-Editor? | Online
| Which broswer & version?            | Chrome Version 63.0.3239.108
| Which operating system?             | Windows 10

### Expected Behavior

When clicking on the GOTO link (the black arrow) it should take me to the corresponding line in the spec.

![image](https://user-images.githubusercontent.com/10422956/34480891-f2571508-efa6-11e7-8590-afd26533d8d3.png)

### Current Behavior
Clicking on the link does nothing and the editor remains in the same position as before clicking on the link (i.e. the editor does not jump to the corresponding line in the spec). 

Try with the following spec 

``` json
openapi: 3.0.0
info:
  title: Test
  version: v0
paths:
  /ping:
    get:
      operationId: ping1
      description: Test
      responses:
        '200':
          description: OK
  /ping2:
    get:
      operationId: ping2
      description: Test
      responses:
        '200':
          description: OK   
  /ping3:
    get:
      operationId: ping3
      description: Test
      responses:
        '200':
          description: OK     
  /ping4:
    get:
      operationId: ping4
      description: Test
      responses:
        '200':
          description: OK     
  /ping5:
    get:
      operationId: ping5
      description: Test
      responses:
        '200':
          description: OK     
  /ping6:
    get:
      operationId: ping6
      description: Test
      responses:
        '200':
          description: OK 
```

**Comment by shockey** [comment]
Confirmed, getting a TypeError:

```js
TypeError: path should be an array of strings
    at Object.getLineNumberForPath
```

This may be related to the recent specPath changes.

**Comment by shockey** [comment]
Fixed.

Thanks, @tnjohansson!
