### ISSUE TITLE
输入法不兼容

### ISSUE THREAD

**Issue by killkohon** [swagger-api/swagger-editor#1616]
当你在编辑API，需要输入中文时，例如：编辑description，用输入法输入键盘字符，键盘字符会直接出现在文档里，再按空格键，对应的中文也会出现在文档里，我不得不回到前面去将那些不要的键盘字符删除。

**Comment by shockey** [comment]
Hi @killkohon!

Unfortunately, all tickets need to be in English. Please open a new ticket in English if you're able to :smile:
