### ISSUE TITLE
Sample code generation for C# with customized template.. no demo for it!!!

### ISSUE THREAD

**Issue by rafiqips5** [swagger-api/swagger-editor#1618]
We need sample code generation for our own template and how to create the template for C#.

1. Bug or feature request?    
 bug 

2. Which Swagger-Editor version?     
2.2.3

 3. How did you install Swagger-Editor? |
downloaded the jar file

 4. Which browser & version?       
all browser    
 
 5.Which operating system?      
windows 10        

followed the below steps for sample.
### Demonstration API definition
Step 1 : 

java -jar swagger-codegen-cli.jar generate -i http://petstore.swagger.io/v2/swagger.json -l php -o "D:\SwaggerAPI"

java -jar swagger-codegen-cli.jar generate -i http://localhost:51148/swagger/docs/v1 -l csharp -o "D:\SwaggerAPI"

Step 2 :

java -jar swagger-codegen-cli.jar help generate

step 3 :

java -jar swagger-codegen-cli.jar config-help -l php

step 4: 

browse and save it where you download the code @ step 1 to available at one folder.

 http://petstore.swagger.io/v2/swagger.json 
  
 Step 5 :
 
java -jar swagger-codegen-cli.jar generate -i http://petstore.swagger.io/v2/swagger.json -l csharp -o "D:\SwaggerAPI"

we have followed the below url 

https://github.com/swagger-api/swagger-codegen

from here ,cant able to understand .

https://github.com/swagger-api/swagger-codegen#making-your-own-codegen-modules

**Comment by shockey** [comment]
Hi @rafiqips5, please open this ticket in the swagger-codegen project!
