### ISSUE TITLE
springBoot with swagger - Failed to instantiate [java.util.List]: Specified class is an interface

### ISSUE THREAD

**Issue by RadMK** [swagger-api/swagger-editor#1621]
Using springfox-swagger2(2.7.0) with springboot(1.5.8). Below is my swagger spec for one of the RestService.
/employee/empAccess:
    post:
      tags:
      - "empAccess"
      summary: "Emp Access"
      description: ""
      operationId: "empAccess"
      consumes:
      - "application/json"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "employeeList"
        description: "Emp List"
        required: true
        schema:
          type: array
          items:
            $ref: "#/definitions/Employee"
      responses:
        200:
          description: "successful operation"
This generates the Api method with method argument as follows
@Valid @RequestBody List<Employee> employeeList
Issue : When i hit the service with List of Employees(json). It gives following error.
**"org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.util.List]: Specified class is an interface"**
.How to generate ArrayList instead of List. I understand that it isnt possible through swagger spec. Any alternatives?

**Comment by shockey** [comment]
Hi @RadMK! 

This is not a Swagger-Editor issue - please open this issue in the Springfox repo 😄
