### ISSUE TITLE
Edit api spec in swagger-ui?

### ISSUE THREAD

**Issue by zongzhaowei** [swagger-api/swagger-editor#1631]
I know that may be beyond your scope. This project (swagger-editor) is already good to use. 
I'm wondering if we can edit api spec in swagger-ui. just click, fill, "+" or so. Since in swagger-ui, we can view all the defined api spec. If all the aspect on the ui can be editable, may be more easier then remembering all yml tags.

**Comment by shockey** [comment]
This is technically possible, but would be a pretty heavy change of Swagger-UI.

Given Swagger-UI's new plugin system, maybe this is something that could sit on top of it!

**Comment by shockey** [comment]
Closing in favor of https://github.com/swagger-api/swagger-editor/issues/1824
