### ISSUE TITLE
Incorrect validation message for unique operationId

### ISSUE THREAD

**Issue by jemerald** [swagger-api/swagger-editor#1632]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 2
| Which Swagger-Editor version?       | 3.2.4
| How did you install Swagger-Editor? | Using swagger-editor-dist with express, also reproducible in editor.swagger.io
| Which broswer & version?            | Latest Chrome
| Which operating system?             | Windows

### Demonstration API definition

```yaml
swagger: '2.0'
info:
  version: v3
  title: test
basePath: /v1
paths:
  /:
    post:
      responses:
        200:
          description: Successful response
    get:
      operationId: myId2
      responses:
        200:
          description: Successful response
```

### Expected Behavior

No validation error

### Current Behavior

Semantic error at paths./.get.operationId
Operations must have unique operationIds.
Jump to line 13

### Possible Solution

Added some logging to `src/plugins/validate-semantic/validators/operations.js` shows that `__originalOperationId` for both methods are set to "myId2"

Probably caused by this line?
https://github.com/swagger-api/swagger-js/blob/master/src/helpers.js#L161

### Test to be added to catch the bug

Add the following test to `test/plugins/validate-semantic/operations.js`

```
    it("should not return an error when only some operationId is defined without collisions", () => {
      const spec = {
        paths: {
          "/": {
            get: {
            },
            post: {
              operationId: "myId2"
            }
          }
        }
      }

      return expectNoErrors(spec)
    })
```

**Comment by shockey** [comment]
Fixed by #1221.

**Comment by jemerald** [comment]
@shockey thanks for merging the PR. However the latest swagger-editor-dist@3.2.5 still has this problem. Perhaps the published version didn't include the swagger-client changes?

**Comment by shockey** [comment]
@jemerald we held off on a Swagger-Editor release last Friday since it (a) had a special release last Wednesday, and (b) has no new source changes since v3.2.5.

We will cut a new release on Friday that includes the updated Swagger-Client version. If this is severely impacting your workflow, just let me know and I can run a release to get this out faster.

**Comment by jemerald** [comment]
@shockey thanks for the quick response. Friday release is fine. 👍

**Comment by rahulsaini** [comment]
Hi @shockey , Is this fixed in the Swagger Online Editor (as of April 16 2018) ?  I am putting in a JSON file in the editor and get this error for this snippet : 
**Errors**
Semantic error at paths./searchdynamic/substtype.get.operationId
Operations must have unique operationIds.
Jump to line 175
Semantic error at paths./searchdynamic/atch.get.operationId
Operations must have unique operationIds.
Jump to line 220

**/searchdynamic/substtype**:
    get:
      tags:
        - **getModifiedTerms**
       operationId: **getModifiedTerms**

**/searchdynamic/atch**:
    get:
      tags:
        - **getModifiedTerms**
       operationId: **getModifiedTerms**

**Comment by jemerald** [comment]
@rahulsaini the bug was fixed, but your spec is actually invalid as it indeed has duplicate operationId - `getModifiedTerms` on two methods.

This bug is about the editor showing validation error when there is NO duplicate operationId in the spec.

**Comment by rahulsaini** [comment]
OK , How do I go about modeling this then. 

The URL differs at substtype and atch , which are different terms for which different URL get constructed by the application:
**GET http://my.webserviceprovider.com/eutct/searchdynamic/substtype/getModifiedTerms  (gets all modified term data for term - substancetype
GET http://my.webserviceprovider.com/eutct/searchdynamic/atch/getModifiedTerms - gets all modified term data for term - atch**

Any suggestions for this in Swagger 2.0 ?

**Comment by jemerald** [comment]
@rahulsaini the operationId has nothing to do with the path of your API.

See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operation-object

For what you want to achieve, you need to put it into the path, e,g. `/searchdynamic/substtype/getModifiedTerms:`
