### ISSUE TITLE
On online editor, when using Chinese input method, it will  suddenly select all.

### ISSUE THREAD

**Issue by OwenLittleWhite** [swagger-api/swagger-editor#1636]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  
| Which Swagger/OpenAPI version?      |
| Which Swagger-Editor version?       |
| How did you install Swagger-Editor? | online swagger-editor
| Which broswer & version?            | chrome
| Which operating system?             | windows10

### Demonstration API definition

```yaml
your: "API definition goes here"
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!
