### ISSUE TITLE
routing should be in routes/web.php for generated Lumen server stub

### ISSUE THREAD

**Issue by qcarduinoyun** [swagger-api/swagger-editor#1643]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 2.x
| Which Swagger-Editor version?       | 3.0
| How did you install Swagger-Editor? | download and unzip locally
| Which broswer & version?            | chrome 63.0
| Which operating system?             | Windows 7 x64

### Demonstration API definition

any API doc in yaml/json format, including default PetStore example.

### Configuration (browser query string, constructor, config.yaml)

nothing special and not related with browser config

### Expected Behavior

Ever since Lumen 5.3+ (my framework: Lumen 5.5), the routing has been moved to routes\web.php.
Please refer to: 
https://lumen.laravel.com/docs/5.3/routing#basic-routing

### Current Behavior

The generated Lumen server stub put all routing in lib\app\Http\routes.php.
This works for Lumen 5.2 and older version. Please refer to:
https://lumen.laravel.com/docs/5.2/routing#basic-routing

### Possible Solution

Follow Lumen 5.3+ routing spec. I'd say it's safe to move all routing to routes\web.php.

### Context

Trying to use auto-generated Lumen server stub in my project. Manual moving/copy the routing
file is a pain for automated deployment.

**Comment by shockey** [comment]
Hi @qcarduinoyun! 

The server stub generation actually happens in [Swagger-Codegen](https://github.com/swagger-api/swagger-codegen) - you should refile this issue there 😄
