### ISSUE TITLE
New error:  Cannot read property 'modifiers' of undefined

### ISSUE THREAD

**Issue by MartinDelVecchio** [swagger-api/swagger-editor#1661]
The online Swagger Editor (https://editor.swagger.io/) is now giving me an error on what it had previously accepted as OK.  In Chrome 63:

    Cannot read property 'modifiers' of undefined

In Firefox 58:

    e is undefined

In Edge 41:

    Unable to get property 'modifiers' of undefined or null reference

The API operation in my YAML returns type DataObjectsArray, which is an array of DataObject.

When I change the API to return just a single DataObject, the error goes away.

In addition, when I change the definition of the 'modifiers' property in the 'DataModifiers' object to be a reference to '#/definitions/DataModifier' instead of '#/definitions/DataModifiers', the error goes away.

In addition, when I installed swagger-ui locally and loaded it up, no errors were reported.

And finally, when I switch to the old editor (http://editor2.swagger.io/#!/), the same YAML is accepted without error

| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 2.0
| Which Swagger-Editor version?       | Online (https://editor.swagger.io/)
| How did you install Swagger-Editor? | Online
| Which broswer & version?            | Chrome 63, Firefox 58, Edge 41
| Which operating system?             | Windows 10

### Demonstration API definition

```yaml
swagger: '2.0'
info:
  title: Company API
  description: Company API
  contact:
    name: Company
    url: https://www.company.com
    email: info@company.com
  version: v1
host: api.company.com
basePath: /api/v1
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /path1:
    get:
      summary: Get some data
      operationId: get
      responses:
        200:
          description: Got some data
          schema:
            $ref: '#/definitions/DataObjectArray'

definitions:
  DataObject:
    type: object
    properties:
      modifiers:
        $ref: '#/definitions/DataModifiers'
    title: A data object

  DataObjectArray:
    type: array
    description: An array of objects
    items:
      $ref: '#/definitions/DataObject'

  DataModifier:
    type: object
    properties:
      prop1:
        type: string
    title: Data Modifier

  DataModifiers:
    type: array
    items:
      $ref: '#/definitions/DataModifier'
```

### Configuration (browser query string, constructor, config.yaml)

N/A

### Expected Behavior

I believe this Swagger is valid, so I expect the online Swagger Editor to say so.  Until about a week or two ago, it did.  But now it complains.

### Current Behavior

The online Swagger Editor now gives errors (described above) when validating this swagger.

### Context

Trying to give a valid Swagger to customers, who validate it via the online Swagger Editor.

**Comment by shockey** [comment]
This is _probably_ an issue with some recent changes we've made to the resolver - investigating!

**Comment by MartinDelVecchio** [comment]
Thanks!

**Comment by shockey** [comment]
@MartinDelVecchio, I just managed to confirm the bug and write a failing test case in Swagger-Client for it based on the API definition you provided, thanks!

The problem is indeed in the $ref resolver. There's some specific interaction in the resolution between the definitions you have defining that's causing a not-yet-available subtree of the resolved data to be accessed (hence "undefined").

Stay tuned for a fix! In the meantime, you can work around this by ordering your models in order of inheritance, from highest to lowest:

```yaml
paths:
  /path1:
    get:
      summary: Get some data
      operationId: get
      responses:
        '200':
          description: Got some data
          schema:
            $ref: '#/definitions/DataObjectArray'
definitions:
  DataModifier:
    type: object
    properties:
      prop1:
        type: string
    title: Data Modifier
  DataModifiers:
    type: array
    items:
      $ref: '#/definitions/DataModifier'
  DataObject:
    type: object
    properties:
      modifiers:
        $ref: '#/definitions/DataModifiers'
    title: A data object
  DataObjectArray:
    type: array
    description: An array of objects
    items:
      $ref: '#/definitions/DataObject'
```

To be clear: this ordering is _not_ required in the normal flow of things (since object key order is not guaranteed in JS), but while we get this pinned down you can sidestep it :smile:

**Comment by shockey** [comment]
@MartinDelVecchio - this is fixed! thanks for the report!
