### ISSUE TITLE
anyOf / oneOf not supported but (allOf well supported) with use of additionalProperties:false

### ISSUE THREAD

**Issue by xiaoPierre** [swagger-api/swagger-editor#1667]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 2.0
| Which Swagger-Editor version?       | Online (https://editor.swagger.io/)
| How did you install Swagger-Editor? |  Online (https://editor.swagger.io/)
| Which broswer & version?            | Chrome v63
| Which operating system?             | Windows

### Demonstration API definition

```yaml
swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  description: A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /something:
    get:
      operationId: findPets
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
      responses:
        "200":
          description: pet response
          schema:
            type: array
            items:
              $ref: '#/definitions/Thing'
definitions:
  Thing: 
    anyOf:
      - required:
        - name
      - required:
        - tag
    properties:
      name:
        type: string
      tag:
        type: string
    type: object
    additionalProperties: false
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

### Expected Behavior

No error, same behavior as for allOf.

### Current Behavior

when it is allOf : no error
when it if anyOf / oneOf : error

### Possible Solution

No idea

### Context

Personal project.

**Comment by hkosova** [comment]
`oneOf` and `anyOf` are not supported in OpenAPI 2.0. These keywords were introduced in OpenAPI 3.0.

As a workaround, you can use `minProperties: 1` to indicate that a `Thing` must have at least 1 property:
```yaml
definitions:
  Thing: 
    type: object
    properties:
      name:
        type: string
      tag:
        type: string
    minProperties: 1
```
