### ISSUE TITLE
URL reference throwing a Resolver Error: Type error

### ISSUE THREAD

**Issue by jennaprice** [swagger-api/swagger-editor#1668]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  bug
| Which Swagger/OpenAPI version?      | 3
| Which Swagger-Editor version?       | 3.2.8
| How did you install Swagger-Editor? | I downloaded the zip file and ran it from command line
| Which browser & version?            | Chrome and Safari
| Which operating system?             |  Mac Os 10.13

### Demonstration API definition

```yaml
openapi: 3.0.0

info:
  description: |
    My description
  version: "1.0.0"
  title: Ryngly
  #termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@mycompany.com
  #license:
    #name: Apache 2.0
    #url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - description: Production Server
    url: https://api.mycomapny.com/v1
  - description: Development Server
    url: https://mycompany.com/our-api/v1
tags:
  - name: API Credentials
    description: Allows management of API credentials
    #externalDocs:
      #description: Find out more
      #url: 'http://swagger.io'

paths:
  /activity:
    #I have verified that I can reach this path from my browser
    #I tried just using the fiel path, they are in the same folder also had an error so I hosted it because per you documentation a url is best way to specify a path
    $ref: http://localhost:2224/swagger/docs/activityShort.yaml
    
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

### Expected Behavior

I cannot reference a file anywhere. I need a concrete way to reference any file: yaml, json, hosted, locally 

### Current Behavior

Errors
Hide
Resolver error at paths./activity.$ref
Could not resolve reference because of: Type error
Jump to line 30
### Possible Solution

I want this documentation to work: https://swagger.io/docs/specification/using-ref/
### Context

I have literally spent two days trying to any useful form of includes. I have looked at tons of stuff.

**Comment by shockey** [comment]
Hi @jennaprice!

I tried replacing your $ref with the Petstore document:

```yaml
paths:
  /activity:
    #I have verified that I can reach this path from my browser
    #I tried just using the fiel path, they are in the same folder also had an error so I hosted it because per you documentation a url is best way to specify a path
    $ref: http://petstore.swagger.io/v2/swagger.yaml
```

and it works as expected, so I'm inclined this has something to do with the content of the referenced file, or how it's being served.

Some requests:
- Can you share the YAML file you're referencing? If it's private, you can email it to me (email in profile)
- Can you share how you're serving it over HTTP (what server)?
- Can you share a screenshot of the network request that fetches the YAML file as shown in your browser Dev Tools?

Thanks!

**Comment by jennaprice** [comment]
@shockey I sent an email with some files and some screenshots.

**Comment by shockey** [comment]
Closing - I'll continue to help out in our email thread, @jennaprice!
