### ISSUE TITLE
Swagger Editor cannot generate HTML Client code

### ISSUE THREAD

**Issue by gauravojha** [swagger-api/swagger-editor#1673]
Hi,

I just opened up the sample PetStore (simple) example, and without any changes, tried to generate the HTML client code. But it throws an error 500 "something bad happened.". 

**Steps to Reproduce**

1. Open the PetStore (simple) example on the [editor](http://editor2.swagger.io/#!/). Just a note, I tried to do the same on the older editor page as well, but it just doesnt generate anything.
2. Try to Generate Client > HTML

**Result**
![image](https://user-images.githubusercontent.com/10114860/36130564-6a086250-103b-11e8-9953-ac40d009edec.png)

**Expected Result**
Should generate the Client Code

**Update**
swagger-codegen installed through brew seems to be working fine on the same YAML I have.

**Comment by jasjon** [comment]
This seems to be a general issue with the 'generate' feature.  there is a 500 error on the http://generator.swagger.io/api/gen endpoint
I'm pretty sure it was working a couple of days ago

**Comment by webron** [comment]
This was a temporary issue with the online generator which is now resolved.

**Comment by wmfairuz** [comment]
Still an issue today
