### ISSUE TITLE
Proxy generation does no longer trigger zip-file

### ISSUE THREAD

**Issue by wyzec** [swagger-api/swagger-editor#1674]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | The online tool
| Which Swagger-Editor version?       | The online tool
| How did you install Swagger-Editor? | N/A
| Which broswer & version?            | Chrome, Version 64.0.3282.140 (latest) or Firefox 58 (latest) or Internet explorer 11
| Which operating system?             | Windows 7 Enterprise

### Demonstration API definition
1. Browse to http://editor.swagger.io/ or http://editor2.swagger.io/#!/
2. Do not change default yaml sample code (other valid code gives same trouble though).
3. Click either 'Generate Server' or 'Generate Client' dropdown.
4. Click on any target.

### Expected Behavior
A zip to be generated and prompted to downloaded.

### Current Behavior
* Using http://editor2.swagger.io/#!/:
A dialog is shown the info:
Code Generator Error
something bad happened
Details:
 Object
code: 500
type:  "unknown"
message:  "something bad happened"

* Using http://editor.swagger.io/:
Nothing at all happens.

### Possible Solution
No idea, the online version has worked on my computer and browser before, latest attempted in April 2017.

### Context
Cannot facilitate any proxy generation functionality at all. A member in our group has installed the tool locally - but experiences EXACTLY the same result.

**Comment by webron** [comment]
This was a temporary issue with the online generator which is now resolved.
