### ISSUE TITLE
swagger editor code generation is not working for java

### ISSUE THREAD

**Issue by nkesarwani7** [swagger-api/swagger-editor#1675]
Hello

i'm trying to generate my code using editor (editor.swagger.io and editor2.swagger.io) for any client , but both are not working. Please check the screenshot. 

![untitled](https://user-images.githubusercontent.com/36442754/36147976-4abc3f3e-10e0-11e8-86e0-f38997ed1b8a.png)

expected result:
Should generate any client.

Thank You
Neeraj

**Comment by nkesarwani7** [comment]
it was working yesterday, but today its showing this 500 error...

**Comment by fgrande** [comment]
Same problem here, trying to generate PHP Client code....

**Comment by jglisson** [comment]
Not  working for .NET either. I opened an issue that apparently was deleted because I didn't follow the huge template. I don't have time to write a book for you. Simply, when you try to generate any server or client, you get a 500 error.

**Comment by jglisson** [comment]
...it's working now.

**Comment by nkesarwani7** [comment]
yes
