### ISSUE TITLE
editor.swagger.io  does not generate coide anymore

### ISSUE THREAD

**Issue by Vadiml1024** [swagger-api/swagger-editor#1676]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 2.0
| Which Swagger-Editor version?       | https://editor.swagger.io
| How did you install Swagger-Editor? | i used the above url
| Which broswer & version?            | Firefox 58.0.2
| Which operating system?             | Ubuntu 16.04

### Demonstration API definition

```yaml
---
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /:
    get:
      responses:
        200:
          description: OK

```

**Comment by webron** [comment]
This was a temporary issue with the online generator which is now resolved.
