### ISSUE TITLE
Request Body Examples Do Not Work With Nested Schemas

### ISSUE THREAD

**Issue by AMcManigal** [swagger-api/swagger-editor#1678]
It appears that nested schemas do not work for examples in the request body.

| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug 
| Which Swagger/OpenAPI version?      | OpenAPI 3.0
| Which Swagger-Editor version?       | Current https://editor.swagger.io/
| How did you install Swagger-Editor? | Did not install
| Which browser & version?            | Chrome 64.0.3282.140
| Which operating system?             | MacOS Sierra 

### Demonstration API definition

Consider a definition where the example is placed in the schema definition. Things work as expected.
https://gist.github.com/AMcManigal/a2e5f2c5e949b0b491670d8d2b0cf9f9

From the documentation I should be able to place this in the request body. However, when I do so it no longer works.
https://gist.github.com/AMcManigal/9d79130890fbba70bd37c4d7b80d4067

### Configuration (browser query string, constructor, config.yaml)
I'm using the service at https://editor.swagger.io/ so there are no special configurations.

### Expected Behavior

I would expect the implementations in both Gists to have the result included in the screenshot.
<img width="719" alt="screen shot 2018-02-14 at 4 47 00 pm" src="https://user-images.githubusercontent.com/1545624/36229971-e48749bc-11a6-11e8-8565-f9e21b32071a.png">

### Current Behavior

What happens instead is the non-working implementation displays the example values from the schema definitions.
<img width="765" alt="screen shot 2018-02-14 at 4 50 22 pm" src="https://user-images.githubusercontent.com/1545624/36230057-3a1ed3c2-11a7-11e8-992c-8bdd2b285cdd.png">

### Context

Since placing the examples in the request body is the only way to do multiple examples I think this is pretty crucial functionality to fix.

**Comment by hkosova** [comment]
Support for `content.<media-type>.example(s)` is not available yet. This is being tracked in the Swagger UI repository at https://github.com/swagger-api/swagger-ui/issues/3437 and PR https://github.com/swagger-api/swagger-ui/pull/4092.

**Comment by AMcManigal** [comment]
Overlooked it. Thanks!
