### ISSUE TITLE
I want swagger-editor to be hosted inside Eclipse che workspace. 

### ISSUE THREAD

**Issue by maviss385** [swagger-api/swagger-editor#1680]
So , I have Eclipse che-6.0.0-M2 installed on my VM .
I copied source code of swagger-editor-master onto my machine "172.30.65.142" and I have changed dockerfile - 
{

FROM eclipse/stack-base:debian
#Above eclipse/stack-base contains : jdk 1.8.0 ,git 2.1.4
EXPOSE 4403 8000 8080 9876 22

LABEL che:server:8080:ref=tomcat8 che:server:8080:protocol=http che:server:8000:ref=tomcat8-debug che:server:8000:protocol=http che:server:9876:ref=codeserver che:server:9876:protocol=http

ENV MAVEN_VERSION=3.3.9 \
    JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64 \
    TOMCAT_HOME=/home/user/tomcat8 \
    TERM=xterm
ENV M2_HOME=/home/user/apache-maven-$MAVEN_VERSION
ENV PATH=$JAVA_HOME/bin:$M2_HOME/bin:$PATH

RUN mkdir /home/user/tomcat8 /home/user/apache-maven-$MAVEN_VERSION && \
    wget -qO- "http://apache.ip-connect.vn.ua/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz" | tar -zx --strip-components=1 -C /home/user/apache-maven-$MAVEN_VERSION/ && \
    wget -qO- "http://archive.apache.org/dist/tomcat/tomcat-8/v8.0.24/bin/apache-tomcat-8.0.24.tar.gz" | tar -zx --strip-components=1 -C /home/user/tomcat8 && \
    rm -rf /home/user/tomcat8/webapps/* && \
    echo "export MAVEN_OPTS=\$JAVA_OPTS" >> /home/user/.bashrc && \
    sudo chgrp -R 0 ~/tomcat8 && \
    sudo chmod -R g+rwX ~/tomcat8
    
RUN sudo apt-get update && \
    sudo apt-get -y install build-essential libkrb5-dev gcc make ruby-full rubygems debian-keyring python2.7 && \
    sudo gem install --no-rdoc --no-ri sass -v 3.4.22 && \
    sudo apt-get -y install ruby-compass && \
    sudo apt-get clean && \
    sudo apt-get -y autoremove && \
    sudo apt-get -y clean && \
    sudo rm -rf /var/lib/apt/lists/* 

RUN wget -qO- https://deb.nodesource.com/setup_7.x | sudo -E bash -
RUN sudo apt update && sudo apt -y install nodejs

EXPOSE 1337 3000 4200 5000 9000 8003
RUN  sudo npm install --unsafe-perm -g gulp bower grunt grunt-cli yeoman-generator yo generator-angular generator-karma generator-webapp

COPY /swagger-editor-master/ /app/swagger-editor-master
RUN sudo chmod -R 777 /app/swagger-editor-master
WORKDIR /app
EXPOSE 3000

// CMD ["sh", "/usr/share/nginx/docker-run.sh"]

}

AND THEN I RUN>> docker build -t swagger-editor  [// to copy swagger-editor to eclipse che stack-base]

I have tagged swagger-editor source code to 'swagger-editor'  name  on eclipse che stack .
then created a stack and tagged dev-machine to 'swagger-editor'[ it will create workspace with tagged image of swagger-editor]
then i created a workspace and run commands in its terminal as - 
user@3a44b24ec711:/app/swagger-editor-master$ npm startapp/swagger-editor-master $$ npm start
**output** :-  
![output](https://user-images.githubusercontent.com/16989050/36523491-c68234fa-17c7-11e8-9dc9-aa5dde0bb7ca.png)

**Expected output** :- swagger-editor should be hosted on "http://172.30.65.142:3001" which my host machine but it is not coming. All other URLs generated says : "This site can’t be reached"

Now , if I run "npm start" on my Machine i.e 172.30.65.142 , swagger-editor gets hosted .
Same is not working inside eclipse che workspace.

Can you provide a way out?

**Comment by shockey** [comment]
Hi @maviss385, unfortunately we're not going to be able to help here - this sounds like it has more to do with Docker and Eclipse than Swagger-Editor itself.

Best of luck getting it working!
