### ISSUE TITLE
#1611 has returned (Semantic error for "in: formData" Parameters when 'consumes' is specified at the root object)

### ISSUE THREAD

**Issue by elasti-ron** [swagger-api/swagger-editor#1684]
Issue #1611 was fixed, but has now returned.

| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 2.0
| Which Swagger-Editor version?       | latest online version
| How did you install Swagger-Editor? | using (http://editor.swagger.io)
| Which browser & version?            | Chrome 64.0.3282.167
| Which operating system?             | macOS 10.13.3
| Details | See #1611

**Comment by shockey** [comment]
Closing in favor of #1611
