### ISSUE TITLE
Default value from within schema is not showing in the documentation

### ISSUE THREAD

**Issue by brazabr** [swagger-api/swagger-editor#1686]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 3.0.1
| Which Swagger-Editor version?       | current on http://editor.swagger.io
| How did you install Swagger-Editor? | Using from browser
| Which browser & version?            | Chrome x64 64.0.3282.186
| Which operating system?             | Windows 10 x64 1709

### Demonstration API definition

[petstore-expanded-defaultinschema.yaml](https://gist.github.com/brazabr/9f8388d261e86b712e851aa6f5e2934b#file-petstore-expanded-defaultinschema-yaml-L40
)

### Expected Behavior

![image](https://user-images.githubusercontent.com/6144272/36995721-988e1eea-2093-11e8-9cfb-e7a0d80b333e.png)

### Current Behavior

![image](https://user-images.githubusercontent.com/6144272/36995746-a7c89da4-2093-11e8-9f0f-9a4ea1d5f284.png)

### Context

You can achieve the expected behaviour by adding the `default` property in the Parameter Object instead of the `Schema Object` but then OpenAPI 3.0 validation complains that you cannot use `schema` and `default` together. Indeed in the OpenAPI 3.0 specs there is no `default` in the Parameter Object.

**Comment by shockey** [comment]
![Pasted Image 1.png](https://shipusercontent.com/a24b41f16f050612ce7ca785145b9399/Pasted%20Image%201.png)

This was fixed in https://github.com/swagger-api/swagger-ui/pull/4191 :smile:
