### ISSUE TITLE
Swagger 2.0 Reserved Words issue

### ISSUE THREAD

**Issue by MJKhan90** [swagger-api/swagger-editor#1696]
I am currently facing an issue while defining schema definition for open API using Swagger where i am not able to use TEMPLATE keyword word for parameter in schema as it generates empty definition after using TEMPLATE word. I am not able to rectify either its reserved word issue or something fishy with it...Below is the swagger I am using.

    properties:
      FINGER_INDEX:
        properties: {}
        type: string
      Longitude:
        properties: {}
        type: string
      Latitude:
        properties: {}
        type: string
      IsTranslate:
        properties: {}
        type: string
      **FINGERS_TEMPLATE:**
        properties: {}
        type: string
    additionalProperties: true

Is there any way to use reserved words in Swager2.0 
Thanks..

**Comment by webron** [comment]
Please re-file the ticket following the issue template. The ticket is missing some crucial information for us to be able to offer assistance.
