### ISSUE TITLE
Swagger 2.0 Reserved Words issue

### ISSUE THREAD

**Issue by MJKhan90** [swagger-api/swagger-editor#1698]
I am currently facing an issue while defining schema definition for open API using Swagger where i am not able to use TEMPLATE keyword word for parameter in schema.

| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  feature request
| Which Swagger/OpenAPI version?      | Swagger 2.0 Loopback API
| Which Swagger-Editor version?       | IBM api connect toolkit editor
| How did you install Swagger-Editor? |  I have downloaded through node.js
| Which browser & version?            | chrome
| Which operating system?             | Windows 7

### Demonstration API definition
Swagger generates empty definition after using TEMPLATE word. I am not able to rectify either its reserved word issue or something fishy with it.

```yaml
swagger: '2.0'
info:
  x-ibm-name: openapitest
  title: OpenAPITest
  version: 1.0.0
schemes:
  - https
host: $(catalog.host)
basePath: /openapitest
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientIdHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
      - invoke:
          target-url: $(target-url)$(request.path)
paths:
  /postInfo:
    post:
      responses:
        '200':
          description: 200 OK
      parameters:
        - name: Request
          required: false
          in: body
          schema:
            $ref: '#/definitions/Request'
definitions:
  Request:
    properties:
      RequestData:
        $ref: '#/definitions/RequestData'
    additionalProperties: false
  RequestData:
    properties:
      UserName:
        type: string
      Password:
        properties: {}
        type: string
      Address:
        properties: {}
        type: string
      FINGER_Print:
        properties: {}
        type: string
      FINGER_TEMPLATE:
        properties: {}
        type: string
    additionalProperties: false
tags: []

```

### Expected Behavior
It should generate schema with FINGER_TEMPLATE keyword.
And if I am replacing it with some other property name like FINGER_TMP it is generating perfectly. As you can see below.
{
  "RequestData": {
    "UserName": "Louisa",
    "Password": "povido",
    "Address": "857 Ciroc Pass",
    "FINGER_Print": "timfofe",
    "FINGER_TMP": "fuwu"
  }
}  

### Current Behavior
It is generating empty schema with providing property 'FINGER_TEMPLATE' in schema definition
 "" like this way

**Comment by webron** [comment]
We don't maintain the IBM products and we don't know what version of the editor they provide. We'd need to know the actual version in order to point you in the right direction.

However, checking that API definition in the latest editor version (which you can find at editor.swagger.io) shows the behavior as expected, so it's likely the issue is with whichever version IBM provides you, and the solution would be to upgrade that version.

**Comment by shockey** [comment]
> I have downloaded through node.js

If Loopback installs Swagger-Editor through npm (you can check by seeing if `npm ls | grep swagger-editor` returns anything), running `npm update` should get you the latest version unless Loopback has a tight constraint on acceptable versions.
