### ISSUE TITLE
When typing at http://editor.swagger.io/ using Chinese input method , It occurs that all I have input suddenly disappear

### ISSUE THREAD

**Issue by OwenLittleWhite** [swagger-api/swagger-editor#1699]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 2.0
| Which Swagger-Editor version?       | http://editor.swagger.io/
| How did you install Swagger-Editor? | use online
| Which browser & version?            | Google Chrome 64.0.3282.186
| Which operating system?             | Windows 10.0

### Demonstration API definition

```yaml
swagger: "2.0"
info: 
  version: "0.0.1"
  title: 项目
# during dev, should point to your local machine
host: 192.168.31.226:3005
# Path prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /trade_dates:
    x-swagger-router-controller: collection
    get:
      description: 返回交易日的数组
      parameters:
        - $ref: '#/parameters/count'
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/trade_dates"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

### Context

I am using the online swagger editor to identify there is no error in my documentation. But when I typed some Chinese words, all I have input suddenly disappeared. I lost the work I have done... By the way, in the early day, I mean fourth quarter of last year roughly, there was no such defect.

**Comment by webron** [comment]
@OwenLittleWhite - sorry you're experiencing that. Do you think you can create a short video demonstrating the problem?

**Comment by ealpha** [comment]
i have the same issues , chrome is  65.0.3325.181


![default](https://user-images.githubusercontent.com/76777/37700722-8454f084-2d27-11e8-808b-ad2784e04386.gif)

**Comment by webron** [comment]
@ealpha - interesting! Thanks for sharing the screencast. We'll look into it.

**Comment by shockey** [comment]
I spent quite some time on this today, it appears that the issue is inside of Ace: the Undo stack is being wiped out and then popped from, which wipes the editor out. Not sure of the root cause yet...

**Comment by webron** [comment]
@shockey perhaps the first step would be to file a ticket with Ace?

**Comment by shockey** [comment]
Looks like this was solved by https://github.com/swagger-api/swagger-editor/pull/1744 :smile: 

![](http://g.recordit.co/e3vJl5k00T.gif)
