### ISSUE TITLE
Invalid $refs, do not kick up a validation errors

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-editor#1700]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 2/3
| Which Swagger-Editor version?       | 3.3.1
| How did you install Swagger-Editor? | npm
| Which browser & version?            | Chrome/Firefox
| Which operating system?             | Linux Mint

### Demonstration API definition

```yaml
swagger: "2.0"
info:
  version: demo
  title: demo
  description: demo

paths:
  /one:
    get:
      summary: ok
      description: ok
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Errodd' # <-- No error given.

```

### Expected Behavior
An error indicating that the definition does not exist.

### Current Behavior
There are no validation errors

### Possible Solution
Need to look a pre-fetching $refs, and generate error from that.
Possibly via a config.

### Context
Given large defintions, and the use of 3rd party libs that interact with the defintion ( ie: codegen ) error are pushed downstream. ie: we only know about the error, when we try to run it through codegen.

**Comment by ponelat** [comment]
@webron assgined to you, for input on this. 
a) It is different behaviour from what we had before
b) We may want to delegate this to a button in the editor ( or some such ) to allow the user to decide if they want to validate all $refs.
c) I feel its more a design decision than a bug, but listing as bug due to breaking change.

**Comment by shockey** [comment]
Yep, this is new, due to the new resolver strategy. 

Expanding the option surfaces the error:

![Pasted Image 1.png](https://shipusercontent.com/cd51b5c917a24dab48c962837878c9d1/Pasted%20Image%201.png)

**Comment by webron** [comment]
Yup, this is not good. @shockey - ideas for the options?

This is going to be a struggle with performance vs functionality. I'm not sure adding a button is the right user experience.

**Comment by ponelat** [comment]
As a workaround for now, I'm fully resolving the definition on load. Which obviously removes the cool perf boost we got with lazy loading.

As a side note on that, validation only occurs on updateJsonSpec. Not on resolving a subtree... I'll see if there's a fix. And log a ticket, with an example.

**Comment by webron** [comment]
@ponelat forgot to update the ticket, but we do have some thoughts on a solution, hopefully would be available in this week's release.

**Comment by ponelat** [comment]
thanks @webron @shockey 
I see the PR for the invalide local $refs. 
For my situation I'll need to figure out how/when to validate the whole definition in its entireity.
But I can understand how that might be out of scope for this project.
