### ISSUE TITLE
Provide online editor for OAS 3.0

### ISSUE THREAD

**Issue by melissachang** [swagger-api/swagger-editor#1707]
https://editor.swagger.io/ is very useful for writing Swagger yaml. I need a feature in OAS 3.0 (allow query parameters to be Object type). In https://editor.swagger.io/, I changed `swagger: '2.0'` to `swagger: '3.0'` and I get the error `Schema error at swagger should be equal to one of the allowed values allowedValues: 2.0`.

Would be possible to provide something like https://editor.swagger.io/, but for OAS 3.0?

**Comment by webron** [comment]
OAS3's identifier is `openapi: 3.0.0`. Use that, and it'll work.
