### ISSUE TITLE
code: 500 type:  "unknown" message:  "something bad happened"

### ISSUE THREAD

**Issue by RicardoOzolio** [swagger-api/swagger-editor#1708]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | Swagger 2.0
| Which Swagger-Editor version?       | 2.10.4
| How did you install Swagger-Editor? | using online editor
| Which browser & version?            | Chrome Versão 64.0.3282.186 (Versão oficial) 64 bits
| Which operating system?             | Win 8.1 Pro

### Definition API:
https://github.com/RicardoOzolio/endcorp/blob/master/endcorp.yaml

### Expected Behavior

Documentation generated by clicking 'Generate Client >html2'

### Current Behavior

Always the same error massage happens:

Object
code: 500
type:  "unknown"
message:  "something bad happened"

**Comment by webron** [comment]
Your YAML file contains plenty of errors that you have to fix before the code generation will work. Not sure why you're using version 2.10.4 of the editor really.

**Comment by shockey** [comment]
Closing; we don't offer support for the 2.x Editor. 

Fixing the errors in your document should get the Codegen working correctly!
