### ISSUE TITLE
Relative URL for openIdConnectUrl has errors

### ISSUE THREAD

**Issue by jblazek** [swagger-api/swagger-editor#1709]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 3.0.0
| Which Swagger-Editor version?       | 3.4.1
| How did you install Swagger-Editor? | npm, and hosted swagger.io
| Which browser & version?            | chrome 64.0.3282.186 
| Which operating system?             |  Windows 10 64-bit

### Demonstration API definition

Sample [Gist](https://gist.githubusercontent.com/jblazek/5b7cad3e3ec8002c3bf1a6e80fcc8408/raw/deaca3e01fd401d34dc00a1ababa4ee773463c61/openid-relative-url.yaml)

Using swagger-editor, I'm getting errors when using the example code from [openid](https://swagger.io/docs/specification/authentication/openid-connect-discovery/) 

```yaml
servers:
  - url: https://api.example.com/v2

components:
  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: /.well-known/openid-configuration
```

If I change the `openIdConnectUrl` to be an absolute URL, I don't get issues. 

### Expected Behavior

I would expect the relative URL to be accepted, since the documentation and example say it's allowed.

### Current Behavior

Currently, several errors are displayed

```
Schema error at components.securitySchemes['openId']
should NOT have additional properties
additionalProperty: openIdConnectUrl
Jump to line 25
Schema error at components.securitySchemes['openId'].type
should be equal to one of the allowed values
allowedValues: apiKey, http, oauth2
Jump to line 26
Schema error at components.securitySchemes['openId'].openIdConnectUrl
should match format "url"
format: url
Jump to line 27
```

### Context

I want to use openid connect, but don't want to specify the full URL, since it depends on the servers I have configured.

**Comment by shockey** [comment]
Yeah, this should be allowed. Per the specification:

```
### Relative References in URLs

Unless specified otherwise, all properties that are URLs MAY be relative references
as defined by RFC3986. Relative references are resolved using the URLs defined in 
the Server Object as a Base URI.
```

**Comment by shockey** [comment]
I've opened a pull request (#1985) that will close this issue.

With the changes, Swagger Editor doesn't report any errors about relative URLs.
