### ISSUE TITLE
Import File  JS Error

### ISSUE THREAD

**Issue by liuyikun** [swagger-api/swagger-editor#1714]
![image](https://user-images.githubusercontent.com/10166125/37870855-9bf8b8f4-3012-11e8-9baa-c4cef22814bb.png)

**Comment by jasongonzales23** [comment]
:+1:

**Comment by shockey** [comment]
Fixed via https://github.com/swagger-api/swagger-editor/pull/1715

Release will be on npm, docker hub, and swagger.io shortly.

**Comment by shockey** [comment]
Thanks for the report, @liuyikun!
