### ISSUE TITLE
Open custom yaml spec in swagger editor on startup

### ISSUE THREAD

**Issue by gsamartian** [swagger-api/swagger-editor#1727]
I want to customize the default petstore yaml which gets opened whenever I open swagger editor.

Is there a way to customize it so that I can open a different swagger yaml spec whenever I open swagger editor.

**Comment by shockey** [comment]
Yes!

You can use Swagger-UI config options to load in your own definiton: there's `url` for fetching a remote document, and `spec` for passing in a JavaScript object directly.

More info here: https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#core
