### ISSUE TITLE
Swagger-Editor served over HTTPS can't communicate with the default Petstore server

### ISSUE THREAD

**Issue by rgalanakis** [swagger-api/swagger-editor#1736]
Doing any "Try it out" example, with my own spec/API or the example one provided, errors with this error in Chrome and a minified version in Firefox. The request is successful (or not), and nothing shows in the response area.

| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 3.0 (and 2.0 I think)
| Which Swagger-Editor version?       | 3.5.2 (and website)
| How did you install Swagger-Editor? | On website, and running locally via a git checkout and node
| Which browser & version?            | Chrome 65 and Firefox
| Which operating system?             | OSX

### Demonstration API definition

Try out any endpoint in the demo YAML, such as /pet/findByStatus.

https://editor.swagger.io/#/

Here is a screenshot, look at the bottom.

![screenshot 2018-04-13 17 03 16](https://user-images.githubusercontent.com/1643233/38762051-c41c535c-3f3c-11e8-9008-f16b110c2500.png)

**Comment by shockey** [comment]
Hi @rgalanakis!

This was a regression in the last version of Swagger-Client, and was patched in the current version (see https://github.com/swagger-api/swagger-js/issues/1277). Swagger-Editor uses the Client under the hood to fire requests.

Swagger-Editor has not been updated since that was patched, so the current dist files still surface this problem. Until we release the Editor again (next Friday at the latest), you can pull in the latest Client locally:
- clone Swagger-Editor
- run ‘npm install && npm update’
- run ‘npm run build’ to regenerate the dist files
- open ‘index.html’ in your browser

Let me know if this helps!

**Comment by shockey** [comment]
PS: this error only surfaces when there’s a network error (a refused connection, for example). I’m able to try out the Petstore as I normally would, are you sure you don’t have a proxy or something that would be giving you trouble?

Consider inspecting the Petstore request in your devtools Network tab to see what’s going on across the wire.

**Comment by rgalanakis** [comment]
Oh, you're right- the Petstore examples on the public editor site were blocked because of mixed resource warnings (API is HTTP, the editor site is HTTPS), and the internal API I was testing against didn't have CORS configured right. Two different reasons for network errors. Thanks for the explanation! (PS- I would suggest fixing the HTTP/HTTPS mixed resource warnings so the public demo works again)

**Comment by shockey** [comment]
@rgalanakis, I've raised this issue internally - I'm going to modify this issue so we can track this, since the HTTPS->HTTP request was the original underlying error you were getting.

**Comment by webron** [comment]
Quick update - we're working on changing the way our demos are served (some things have already changed). Hopefully this process will be completed by the end of the week and the issue will be resolved. Thanks for bringing it up.

**Comment by webron** [comment]
Should be fixed now. Thanks for reporting.
