### ISSUE TITLE
Model schema rendering broken in swagger-ui 3.13.2 and 3.13.3

### ISSUE THREAD

**Issue by hn3000** [swagger-api/swagger-editor#1741]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | 2
| Which Swagger-Editor version?       | 3.5.2
| How did you install Swagger-Editor? | editor.swagger.io, local install
| Which browser & version?            | any
| Which operating system?             | any

Model schema is not rendered, only description is shown. This is caused by a bug in swagger-ui 3.13.2 and 3.13.3, see https://github.com/swagger-api/swagger-ui/issues/4426 -- updating swagger-editor to swagger-ui@3.13.4 fixes the problem.

### Context
It makes reading swagger specifications

**Comment by shockey** [comment]
Hi @hn3000! As you mention, this has been fixed in Swagger-UI but Swagger-Editor hasn't picked up the fix yet.

We'll run a release of Swagger-Editor on Friday that will pick up the new Swagger-UI version.

**Comment by webron** [comment]
Released!
