### ISSUE TITLE
Too accommodating to bad indentation in allOf?

### ISSUE THREAD

**Issue by jemerald** [swagger-api/swagger-editor#1749]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug / Question
| Which Swagger/OpenAPI version?      | 2.0
| Which Swagger-Editor version?       | latest
| How did you install Swagger-Editor? | online
| Which browser & version?            | Chrome@latest
| Which operating system?             | Win8

### Demonstration API definition

```yaml
definitions:
  foo:
    description: foo model
    type: object
    properties:
      fooProp:
        description: foo
        type: string

  bar:
    description: bar model
    allOf:
      - $ref: '#/definitions/foo'
      - type: object
    properties:
      barProp:
        description: bar
        type: string
```

### Configuration (browser query string, constructor, config.yaml)

No specific config

### Expected Behavior

Not sure what should be the expected behaviour, as I cannot find explicit wording in Swagger 2.0 spec that forbid such indentation. Is other properties allowed at the same level when using `allOf`?

But I believe the editor is not doing the right thing here being too accommodating. An error or warning should be given.

### Current Behavior

Swagger editor shows the `bar` model with two properties, however when generating code (Java spring) the `barProp` is not generated.

**Comment by webron** [comment]
The definition is actually valid, that's why there's no error or warning.

**Comment by jemerald** [comment]
Oh, really? So it's a bug in codegen for not generating `barProp`?

**Comment by webron** [comment]
It's potentially a bug in the codegen as well, though it does look like the definition is not what you intended it to be (even though it's not technically wrong).

**Comment by jemerald** [comment]
Hmm... I'm a little confused. Examples I see in Swagger 2.0 spec usually have the following structure when using `allOf`:

```
  bar:
    allOf:
      - $ref: '#/definitions/foo'
      - type: object
        description: bar model
        properties:
          barProp:
            description: bar
            type: string
```

The above works as expected in both editor and codegen, so i consider it the correct way when combining model definitions.

When you say

> The definition is actually valid
> the definition is not what you intended it to be (even though it's not technically wrong).

How should the badly indented spec be interpreted according to Swagger 2.0 standard? Does the `bar` model have property `barProp` or not? Currently the editor shown both `fooProp` and `barProp` in the `bar` model, but codegen ignores `barProp`. One of them has to be wrong...

**Comment by webron** [comment]
It's not a question of how it's interpreted by Swagger 2.0 but rather by JSON Schema. To my understanding, the editor is the one parsing it correctly. However, it's a non-intuitive way of representing it, which is why I'd suggest adding the indentation regardless of the correctness.

**Comment by jemerald** [comment]
Thanks for the reply. Although I think it would be nicer if Swagger/OpenAPI standard would impose extra restriction here to prevent bad indentation.

Closing this for now.
