### ISSUE TITLE
I changed a name of controller, but the server and client generated by codegen remain using old name.

### ISSUE THREAD

**Issue by chechecarer** [swagger-api/swagger-editor#1752]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  
| Which Swagger/OpenAPI version?      |
| Which Swagger-Editor version?       |
| How did you install Swagger-Editor? | 
| Which browser & version?            |
| Which operating system?             | 

### Demonstration API definition

```yaml
your: "API definition goes here"
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

**Comment by shockey** [comment]
Hi @chechecarer, I'm closing this since there are little/no details provided in the body of this issue.

We're happy to look into this if you file a new ticket, and fill in the fields in the template.
