### ISSUE TITLE
Can't resolve 'react-ace'

### ISSUE THREAD

**Issue by djfdev** [swagger-api/swagger-editor#1755]
When I use either of the Swagger editor packages (`swagger-editor` or `swagger-editor-dist`), I'm getting a compile error:

```
Module not found: Can't resolve 'react-ace' in '[...]swagger-editor-error-demo/node_modules/swagger-editor/dist'
```

| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             | Bug
| Which Swagger/OpenAPI version?      | 
| Which Swagger-Editor version?       | 3.5.5
| How did you install Swagger-Editor? | npm
| Which browser & version?            | Chrome 65
| Which operating system?             | High Sierra

### Demonstration API definition

Here's an app created with `create-react-app` that does nothing but import the module:

https://github.com/djfdev/swagger-editor-error-demo

### Expected Behavior

I should be able to import the module without error.

### Current Behavior

Webpack fails to resolve the `react-ace` module when including Swagger editor.

### Possible Solution

It looks like `react-ace` is listed as a devDependency of `swagger-editor` when perhaps it should be a regular dependency? I believe this prevents it from including that module when running `npm install swagger-editor`.

Edit: I solved this by manually editing my installed version of `swagger-editor` to list `react-ace` as a devDependency and reinstalling from inside of that folder.

### Context

Previously I had included the source code for Swagger editor in my repository, but I'm now moving it to npm.

**Comment by shockey** [comment]
Yeah, this is a bug.

[Looks like this has been in since 3.0.0](https://github.com/swagger-api/swagger-editor/blame/master/package.json#L113), I'm absolutely shocked that this hasn't come up before now.

**Comment by shockey** [comment]
@djfdev, a fix for this will go live on Friday! Sorry for the trouble.
