### ISSUE TITLE
Unable to generate clients or servers when references include local paths

### ISSUE THREAD

**Issue by nitinguptadr-dori** [swagger-api/swagger-editor#1771]
### Q&A (please complete the following information)
 - OS: MAC OS
 - Browser: CHROME
 - Version: Version 66.0.3359.181 (Official Build) (64-bit)
 - Method of installation: Local and online
 - Swagger-Editor version: Version 2.10.4 and latest online
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-Editor configuration options:
```js
SwaggerEditor({
  // your config options here
})
```

```
?yourQueryStringConfig
```

### Describe the bug you're encountering
When I try to generate any client or server from my yaml file, I am unable to download anything. I get "something bad happened" error (500). This does not happen when I feed the editor a flat yaml file. Currently my yaml files have paths that look like this:

paths:
  /predict:
    post:
      parameters:
        - name: params
          in: body
          description: Internal request parameters
          schema:
            $ref: "http://localhost:8081/mlcdefs.yaml#/definitions/IntPredictReq"
      responses:
        '200':
          description: predict response.
          schema:
            $ref: "http://localhost:8081/apidefs.yaml#/definitions/PredictRsp"

If I use a flat yaml file with definitions defined locally (see below), then no issues:
paths:
  /predict:
    post:
      parameters:
        - name: params
          in: body
          description: Internal request parameters
          schema:
            $ref: "#/definitions/IntPredictReq"
      responses:
        '200':
          description: predict response.
          schema:
            $ref: "#/definitions/PredictRsp"

Note that I started up a local http-server in order to access the files:
http-server --cors -p 8081 -c-1

Please advise on what to do here.

**Comment by hkosova** [comment]
That's because Swagger Editor uses the online version of the Codegen at https://generator.swagger.io. The online version cannot resolve localhost paths. The solution is, as you correctly noted, to use the command-line codegen.

**Comment by nitinguptadr-dori** [comment]
Thanks for the quick feedback.
