### ISSUE TITLE
Unable to generate html client

### ISSUE THREAD

**Issue by AnandHirekatur** [swagger-api/swagger-editor#1773]
I am getting this exception when I try to generate a html client from http://editor2.swagger.io. I don't have this issue with any other target.
Code Generator Error
Unable to build target: null
Details:
 Object
code: 1
type:  "error"
message:  "Unable to build target: null"

**Comment by shockey** [comment]
Hi @AnandHirekatur, please file an issue with the Codegen project about this: https://github.com/swagger-api/swagger-codegen/issues/new

Thanks!
