### ISSUE TITLE
Codegen broken for OAS 3.0

### ISSUE THREAD

**Issue by jemerald** [swagger-api/swagger-editor#1774]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Chrome
 - Version: latest
 - Method of installation: online
 - Swagger-Editor version: latest online
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

none specific

### Describe the bug you're encountering

When loading OpenAPI 3.0 spec, the editor failed to load 
https://generator3.swagger.io/api/generator.json

This is because the generator swagger JSON have been moved to:
https://generator3.swagger.io/api/swagger.json

### To reproduce...

1. Go to 'editor.swagger.io'
2. Open developer console
3. Paste in any OpenAPI 3.0 spec

**Comment by shockey** [comment]
Thanks @jemerald, there's a pending patch for the Codegen to undo the breaking change that moved the definition 😄

**Comment by protegesolutions** [comment]
@jemerald "Open developer console" - where is this? And can you edit Editor settings?

**Comment by jemerald** [comment]
@protegesolutions by that I mean the developer console of the browser (you can get to it by pressing F12)

**Comment by protegesolutions** [comment]
@jemerald Ah, I see. Thanks. Pity; I was hoping there was a way to change some settings such as _packageName_ or _targetFramework_. In the end I had to change over to using online Swagger Generator via a small utility. BTW, this seems much more robust than Editor.
