### ISSUE TITLE
Can't generate server/client : TypeError: Cannot read property 'generate1' of undefined

### ISSUE THREAD

**Issue by zybjcdl** [swagger-api/swagger-editor#1776]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: last, through http://editor.swagger.io/
 - Method of installation: n/a ,directly through  http://editor.swagger.io/
 - Swagger-Editor version:latest
 - Swagger/OpenAPI version: OpenAPI 3.0.0

### Content & configuration
A very simple swagger yml:

openapi: 3.0.0
info:
  title: TEST
  description: API endpoints for Phase I integration.
  version: '0.1'
paths:
  /test:
    post:
      summary: test
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
      responses:
        '201':
          description: success

### Describe the bug you're encountering
I can't generate server or generate client. 
It will report:
TypeError: Cannot read property 'generate1' of undefined
    at r.downloadGeneratedFile (topbar.jsx:198)
    at Object.i (ReactErrorUtils.js:24)
    at s (EventPluginUtils.js:83)
    at Object.executeDispatchesInOrder (EventPluginUtils.js:106)
    at f (EventPluginHub.js:41)
    at p (EventPluginHub.js:52)
    at Array.forEach (<anonymous>)
    at e.exports (forEachAccumulated.js:22)
    at Object.processEventQueue (EventPluginHub.js:250)
    at ReactEventEmitterMixin.js:15

### To reproduce...
1. Go to 'http://editor.swagger.io/
2. Use the yml content I provided
3. Click on generate server->python flask

### Expected behavior
Could successfully generate server and client

**Comment by hkosova** [comment]
This is likely the same issue as #1774.

**Comment by jemerald** [comment]
Should be working now?

**Comment by zybjcdl** [comment]
Seems there is no python-flask support for openapi:3.0.0. When will it be ready?

**Comment by jemerald** [comment]
@zybjcdl this question should be posted to https://github.com/swagger-api/swagger-codegen

**Comment by shockey** [comment]
It looks like the Codegen service is sending back an error - please file an issue with that project, since that's a bug on their side 😄

**Comment by zybjcdl** [comment]
Thanks all ,I have submit an issue in https://github.com/swagger-api/swagger-codegen
