### ISSUE TITLE
Dash inserted in filename for editor for python

### ISSUE THREAD

**Issue by nitinguptadr-dori** [swagger-api/swagger-editor#1777]
### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-Editor version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-Editor configuration options:
```js
SwaggerEditor({
  // your config options here
})
```

```
?yourQueryStringConfig
```

### Describe the bug you're encountering

When you generate a client or a server for python, the zip file generated has dashes (i.e. python-flask-server-generated). This causes a problem when I unzip and try to import that path in my python code. I need to rename the folder to python_flask_server from python-flask-server. For example:
Fails:
import python-flask-server.swagger_server.models

Passes:
import python_flask_server.swagger_server.models

Suggest renaming the zip file and folder name to underscores.

**Comment by shockey** [comment]
Hey @nitinguptadr-dori,

The Codegen project dictates the file names that we'll save the zip as - please file an issue over there.

Thanks!
