### ISSUE TITLE
how to change the source code to load a local swagger.json file in default

### ISSUE THREAD

**Issue by herozeng** [swagger-api/swagger-editor#1779]
### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-Editor version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-Editor configuration options:
```js
SwaggerEditor({
  // your config options here
})
```

```
?yourQueryStringConfig
```

**Comment by herozeng** [comment]
I am using default configuration in windows

**Comment by shockey** [comment]
@herozeng you can use the [`url` configuration option](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#core) to load a definition 😄

**Comment by herozeng** [comment]
const defaults = {
  dom_id: "#swagger-editor", // eslint-disable-line camelcase, we have this prop for legacy reasons.
  layout: "EditorLayout",
  presets: [
    SwaggerUI.presets.apis
  ],
  plugins: Object.values(plugins),
  components: {
    EditorLayout
  },
  showExtensions: true,
  swagger2GeneratorUrl: "https://generator.swagger.io/api/swagger.json",
  oas3GeneratorUrl: "https://generator3.swagger.io/api/generator.json"
}


This the default config in swagger-editor,how to change the config to load swagger json ,can u give an example? thx

**Comment by amithad** [comment]
Hey - Did you find a solution?

**Comment by ZivotJeKrasny** [comment]
Just like @shockey said ;). Parametr what are you looking for is `url`. Eg: `localhost:8080/?url=<CUSTOM_SPEC>
