### ISSUE TITLE
No validation for empty object

### ISSUE THREAD

**Issue by kumariannu** [swagger-api/swagger-editor#1788]
### Q&A (please complete the following information)
 - OS: [Window]
 - Browser: [chrome]
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-Editor version: [e.g. 2.0]
 - Swagger/OpenAPI version: [Swagger 2.0]

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.0"
  title: Empty Object Path

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /persons:
    # This is a HTTP operation
    {}
```
![image](https://user-images.githubusercontent.com/24291353/41283513-69ff4fc2-6e54-11e8-8eac-df3d1cefcbb8.png)

Swagger-Editor configuration options:
```js
SwaggerEditor({
 https://editor2.swagger.io/#!/
})
```

```
Empty JSON Object
```

### Describe the bug you're encountering
I am trying to create empty object with swagger 2.0 and its allowing me to create it without providing any validation. Can you please help me how to overcome this issue.
### To reproduce...

1. Go to 'https://editor2.swagger.io/#!/'
2. Remove lines after 12 line number and add empty paranthesis on line 12 as:"{}" after paths:
3. See on right side of screen- No error message is displayed.
4. See error as "No error message displayed and its allowing empty object without providing any validation"

### Expected behavior
Error message should come as validation failed.

### Screenshots
![image](https://user-images.githubusercontent.com/24291353/41284014-c400dac6-6e55-11e8-8204-ee54e46ae1d4.png)

### Additional context or thoughts
The same thing is repeated if provide empty object on line 16
![image](https://user-images.githubusercontent.com/24291353/41284069-e93f2b6c-6e55-11e8-9326-0043378b1485.png)

**Comment by shockey** [comment]
Hi @kumariannu,

We're no longer supporting the 2.x series of the UI, you should upgrade to v3 😄 

Thanks for the report, though!

**Comment by kumariannu** [comment]
Hi @shockey,

This problem continues in version 3 as well. Kindly find the screenshot for the same.
![image](https://user-images.githubusercontent.com/24291353/41332167-62e53ec6-6efa-11e8-9f9a-291012533e96.png)

Regards,
Annu

**Comment by shockey** [comment]
@kumariannu, this is legal in OpenAPI 2.0 and 3.0: both specifications say `A Path Item object may be empty` (citation [2.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#path-item-object), [3.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#pathItemObject)), to support the security filtering feature.

So the lack of validation here is correct 😄 nonetheless, thank you for filing an issue! Reports are always appreciated.
