### ISSUE TITLE
Use an external editor

### ISSUE THREAD

**Issue by fleimgruber** [swagger-api/swagger-editor#1794]
### Q&A (please complete the following information)
 - OS:
 - Browser:
 - Version:
 - Method of installation: docker
 - Swagger-Editor version: latest from dockerhub
 - Swagger/OpenAPI version: OpenAPI 3.0

 ### Content & configuration

### Is your feature request related to a problem?
I am so used to my editor and its YAML mode.

### Describe the solution you'd like
Have the YAML file in the swagger-editor be updated automatically by a POST request to the swagger-editor server with the YAML markup as the requestBody. A local process could make that POST request e.g. whenever the local file changes.

**Comment by shockey** [comment]
@fleimgruber, this is out of scope for Swagger Editor, but there are some projects that do something like this. 

Check out [swagger-ui-watcher](https://github.com/moon0326/swagger-ui-watcher)!

**Comment by fleimgruber** [comment]
@shockey thanks for the pointer!
