### ISSUE TITLE
Within an OperationObject, a ParametersObject doesn't accept in: path as a valid location

### ISSUE THREAD

**Issue by ChristineBoersen** [swagger-api/swagger-editor#1797]
### Q&A (please complete the following information)
 - Method of installation: Public hosted Testing
 - Swagger-Editor version: Public hosted @ https://editor.swagger.io
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.1
info:
  title: Foo OpenApi Spec
  version: 1.0.0
servers:
  - url: 'https://localhost/BasePath'
paths:
  '/Account/{id}':
    get:
      description: |-
      operationId: Account1
      parameters:
        - name: id
          in: path
          allowEmptyValue: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: |-
```

Swagger-Editor configuration options:
n/a - using editor.swagger.io as a validator

### Describe the bug you're encountering
Validation error of OpenApi schema - within an OperationObject, a ParametersObject doesn't accept in: **path** as a valid location

### To reproduce...
1. Paste the above YAML into the editor on editor.swagger.io
2. Read the Errors on the right side

### Expected behavior
No validation Errors and for "path" to be an acceptable "in" location

### Screenshots

![image](https://user-images.githubusercontent.com/13676509/41487950-ad17285a-70b8-11e8-868f-521babf39201.png)

**Comment by shockey** [comment]
Keeping this around as a validation enhancement - the messaging here 

As is with most of these issues, the problem lies in the JSON Schema validator not being smart enough to make guesses about which `anyOf` a user intended, and instead complaining about not matching the `anyOf` itself... which is not useful.

**Comment by shockey** [comment]
I've opened a pull request (#1985) that will close this issue.

Here's what Swagger Editor reports with my changes:

```
Structural error at […]get.parameters.0
should have required property 'required'
missingProperty: required
```
