### ISSUE TITLE
There are 3 pairs of query parameters and Each of them is optional.

### ISSUE THREAD

**Issue by thesageinpilani** [swagger-api/swagger-editor#1800]
I want to specify a GET request and we can use only one set in 3 sets at any point of time. How can i achieve this? 

https://github.com/OAI/OpenAPI-Specification/issues/706

I have the same issue as the above. Is any new feature added on this? can you guys please update me on this? Thank you 😀

PS: This has to be testable in dredd. Thank you 😀

**Comment by shockey** [comment]
@thesageinpilani, this concept isn't directly supported by the specification, but OpenAPI does have `form` and `explode` for parameters, so you could use it to define "sets" of parameters.

More here: https://github.com/OAI/OpenAPI-Specification/issues/256#issuecomment-370538097
