### ISSUE TITLE
Code generation does not work for OpenAPI 3.0

### ISSUE THREAD

**Issue by mauricedoepke** [swagger-api/swagger-editor#1801]
If I am pasting the [example ](https://swagger.io/docs/specification/basic-structure/) from the documentation into the editor and try to generate code the Server responds with:

{"code":500,"message":"There was an error processing your request. It has been logged (ID: 9cd9201fffcf9050)"}

I tried it with multiple client/server languages and different browsers.

**Comment by shockey** [comment]
@marcellodesales, this is a Swagger Codegen issue, please file an issue here: https://github.com/swagger-api/swagger-codegen/issues/new

Thanks!

**Comment by marcellodesales** [comment]
@shockey I think you intended to let @mauricedoepke know 👍

**Comment by shockey** [comment]
@marcellodesales 🤦‍♂️  thanks! GitHub autocomplete strikes again...
