### ISSUE TITLE
Issue with curl -X URL

### ISSUE THREAD

**Issue by SureshKarunamoorthy** [swagger-api/swagger-editor#1803]
Hi Team,

In https://editor.swagger.io/#, when u click on "Try It Out" and click on "Execute".
Curl command is getting executed. Request(POST,GET..) header in curl command has double quotes around url. Due to this it always throws forbidden.

Ex:
curl -X POST "https://tryNew/api/v1/OnboardDevice" -H "accept: application/json" -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImtleS1pZC0xIn0.eyJqdGkiOiI4ODlmMjdkYWEyNDM0Yjk1-4" -H "Content-Type: application/json" -d "{ \"deviceMessageTypeGuid\": \"string\", \"Guid\": \"string\", \"data\": \"string\", \"Id\": \"string\", \"status\": \"string\", \"onboardingOrigin\": \"string\"}"

In above example, POST url ("https://tryNew/api/v1/OnboardDevice" )was covered with double quotes.
Due to this it always throws 403 code. 

BR,
Suresh

**Comment by delim29** [comment]
it should be a CORS problem。
you can set header in your service like this:
res.setHeader('Access-Control-Allow-Origin', '*');
res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, UPDATE, DELETE, OPTIONS');
res.setHeader('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept, Authorization');

and,your service can get the Authorization header?

**Comment by delim29** [comment]
if your service can get then  Authorization header , please look issue #1802 , help me to get it.

**Comment by SureshKarunamoorthy** [comment]
Hi,

I am directly writing swagger spec using https://editor.swagger.io/ not through code.

{
  "swagger": "2.0",
  "info": {
    "description": "API definitions for the Connected Goods.",
    "version": "3.0.0",
    "title": "Connected Gooods API"
  },
  "host": "tryNew.com",
  "basePath": "/api/v1",
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "tags": [
    {
      "name": "Device API",
      "description": "API's for Device Onboard and Delete."
    }
  ],
  "paths": {
    "/OnboardDevice": {
      "post": {
        "tags": [
          "Device API"
        ],
        "security": [
          {
            "Bearer": []
          }
        ],
        "summary": "Onboard Device",
        "description": "This API is used for onboarding devices.",
        "operationId": "onboardDeviceUsingPOST",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "Device Info",
            "description": "Device related information.",
            "required": true,
            "schema": {
              "$ref": "#/definitions/OnboardDeviceInfo"
            }
          }
        ],
        "responses": {
          "201": {
            "description": " Device succesfully onboarded.Where status in response returns success",
            "schema": {
              "$ref": "#/definitions/OnboardDeviceSuccess"
            }
          },
          "400": {
            "description": "The input data you have provided is not valid."
          },
          "403": {
            "description": "Access denied. You don't have the required permissions to access this resource."
          },
          "500": {
            "description": "Unexpected error occurred, please contact Connected Goods admin."
          }
        }
      }
    },

**Comment by shockey** [comment]
@SureshKarunamoorthy, are you getting the 403 in Swagger UI, or when you run the curl command in a terminal?

**Comment by SureshKarunamoorthy** [comment]
Hi,

I am getting the 403 in Swagger UI.i.e while clicking "Try it Out" and "Execute".

**Comment by SureshKarunamoorthy** [comment]
Hi @delim29,

You are correct . issue is with CORS header.
Can you please help me to setup the CORS header through swagger editor in the form of json/yaml?

BR,
Suresh

**Comment by delim29** [comment]
hi , @SureshKarunamoorthy 
please look at #1802  ,i had solved the problem.

**Comment by shockey** [comment]
Closing; sounds like a fix was found. 

@SureshKarunamoorthy, if this is still an issue, let me know and I'll reopen this ticket!
