### ISSUE TITLE
Issue: Read only properties cannot be marked as required by a schema.

### ISSUE THREAD

**Issue by WAvdBeek** [swagger-api/swagger-editor#1807]
### Q&A (please complete the following information)
 - OS: [windows 10]
 - Browser: [chrome]
 - Version: [e.g. 22]
 - Method of installation: [website: http://editor.swagger.io/#]
 - Swagger-Editor version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

when using the (json) swagger2.0 file the editor gives the following error.
my opinion is that this is not an error 

Errors
Hide
Semantic error at definitions.yyyy.required.0
Read only properties cannot be marked as required by a schema.
Jump to line 48

Example Swagger/OpenAPI definition:
{
  "swagger": "2.0",
  "info": {
    "title": "error ",
    "version" : "bla"
  },
  "schemes": ["http"],
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "paths": {
    "/xxx" : {
      "get": {
         "parameters": [
          {"$ref": "#/parameters/interface"}
        ],
        "responses": {
            "200": {
              "description" : "",
              "x-example":
                {
                  "memorysize"   : 120.5
                }
                ,
              "schema": { "$ref": "#/definitions/yyyy" }
            }
        }
      }
    }
  },
  "parameters": {
    "interface" : {
      "in" : "query",
      "name" : "if",
      "type" : "string",
      "enum" : ["xxx", "yyy"]
    }
  },
  "definitions": {
    "yyyy" : {
      "properties": {
        "mysize" :
                {
          "readOnly": true,
          "type": "number"
        }
      }
        ,"type" : "object"
      ,"required": ["mysize"]
      
    }
  }
}

### To reproduce...

1. load example in http://editor.swagger.io/#

### Expected behavior
not an error

**Comment by hkosova** [comment]
The error is valid. According to the OpenAPI 2.0 specification:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#user-content-schemaReadOnly

> Properties marked as `readOnly` being `true` SHOULD NOT be in the `required` list of the defined schema.

This restriction was removed in OpenAPI 3.0.

**Comment by shockey** [comment]
Closing; sounds like this is invalid.

Thanks for the report, @WAvdBeek!
