### ISSUE TITLE
Confusing error message "should NOT be valid" caused by empty responses

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-editor#1808]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Chrome 67
 - Method of installation: http://editor.swagger.io
 - Swagger-Editor version: 3.6.0
 - Swagger/OpenAPI version: 2.0, 3.0

### Example Swagger/OpenAPI definition
2.0:
```yaml
swagger: "2.0"
info:
  version: 0.0.0
  title: test
paths:
  /foo:
    get:
      responses: {}
```
3.0:
```yaml
openapi: 3.0.1
info:
  version: 0.0.0
  title: test
paths:
  /foo:
    get:
      responses: {}
```

### Describe the bug you're encountering
The `response: {}` line causes two validation errors:

1. should NOT have less than 1 properties
2. should NOT be valid

The second error does not make sense.

### Expected behavior
No "should NOT be valid" error.

### Screenshots
![error](https://user-images.githubusercontent.com/8576823/42096806-0cbede0e-7bbf-11e8-99b3-28f7e8a09e18.png)

**Comment by shockey** [comment]
Gotta love schema validation

**Comment by shockey** [comment]
I've opened a pull request (#1985) that will close this issue.

Here's what Swagger Editor reports with my changes:

```
"Structural error at paths./foo.get.responses
should define at least one response"
```
