### ISSUE TITLE
import - quotes for names and strings

### ISSUE THREAD

**Issue by Seavert** [swagger-api/swagger-editor#1810]
### Is your feature request related to a problem?
Example in #1809.
Import JSON definition creates quotes for names of object properties or string elements of array which are key words: y, yes, n, no, (probably other). Presense of both quoted and simple names makes readability worse.
### Describe the solution you'd like
If object/array has such property/string - add quotes for all of his properties/strings.

**Comment by shockey** [comment]
Hey @Seavert!

JSON->YAML parsing is handled by [`jsYaml.safeLoad`](https://github.com/nodeca/js-yaml#safeload-string---options-). If you'd like to see this, please open a ticket (or a PR!) there, and we'll adopt the change here in Swagger Editor 😄
