### ISSUE TITLE
Swagger editor parameters component does not load for parameter described with `content` not `schema`

### ISSUE THREAD

**Issue by baseten** [swagger-api/swagger-editor#1815]
- OS: macOS v10.12.6
 - Browser: Chrome
 - Version: 67.0.3396.99 (Official Build) (64-bit)
 - Method of installation: Web editor
 - Swagger-Editor version: Current web editor (can't see version?)
 - Swagger/OpenAPI version: OpenAPI 3.0.0

### Content & configuration
Parameters component gives error message: `Could not render this component, see the console.` Console reports: `Cannot read property 'get' of undefined`. There are no syntax errors reported in the editor or any obvious problems with the API spec.

![screen shot 2018-07-03 at 12 19 13](https://user-images.githubusercontent.com/1300909/42217030-9d0c03f2-7ebb-11e8-93f2-5f08bb61dda6.png)

![screen shot 2018-07-03 at 12 20 16](https://user-images.githubusercontent.com/1300909/42217032-9eb8391e-7ebb-11e8-9c1c-d225bd2ad43a.png)

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  title: Example parameter bug
  version: 0.0.1
servers:
  - url: https://base-url.com/
paths:
  /test:
    get:
      summary: An endpoint
      description: An endpoint description
      parameters:
        - in: query
          name: filters
          description: JSON object describing filters
          content:
            application/json:
              schema:
                type: object
                properties:
                  foo:
                    type: integer
                  bar:
                    type: integer
                  baz:
                    type: array
                    items:
                      type: integer
      responses:
        200:
          description: An example response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
```

### Describe the bug you're encountering
The parameters component appears not to work with a complex parameter where the schema is defined under `content -> application/json`. It works correctly when a `schema` key is present directly under the parameter specification.

### To reproduce...

1. Go to [http://editor.swagger.io/](http://editor.swagger.io/)
2. Paste in above YAML file
3. Click on `GET /test` endpoint

### Expected behavior
I expected to see the parameters component display information about my JSON URL parameter

**Comment by hkosova** [comment]
Thanks for the report! This issue is already being tracked in https://github.com/swagger-api/swagger-ui/issues/4442.

**Comment by shockey** [comment]
Closing as a duplicate 😄

**Comment by ksac1** [comment]
What is the solution for this problem?

**Comment by ksac1** [comment]
The solution to the problem : "😱 Could not render this component, see the console." in Swagger Open API 3 can be resolved by following the link: https://swagger.io/docs/specification/describing-parameters/
