### ISSUE TITLE
Petstore does not define 200 response for delete, but backend still response with this status

### ISSUE THREAD

**Issue by KES777** [swagger-api/swagger-editor#1816]
### Q&A (please complete the following information)
 - OS: linux mint
 - Browser: FF
 - Version: 60
 - Method of installation: online
 - Swagger-Editor version: latest

### Content & configuration
Default petstore available at https://editor.swagger.io/
`

Swagger-Editor configuration options:
default

### Describe the bug you're encountering
Schema does not define 200 OK responses for delete requests, but backend reply with them.

### To reproduce...

1. Go to https://editor.swagger.io/
2. Click on DELETE /pet/{petId}
3. try it out
4. fill ID for pet: 2
5. execute

![delete1](https://user-images.githubusercontent.com/799021/42266984-855a2ca0-7f80-11e8-80a9-35c57192917c.jpg)

### Expected behavior
I do not know what I should see. Because that endpoint define only two responses:
```
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"
```

### Screenshots
![delete1](https://user-images.githubusercontent.com/799021/42266860-3ae08e12-7f80-11e8-894d-31da50096d6f.jpg)

### Additional context or thoughts

Maybe default 501 Not impolemented response should be defined at schema?
when server tries to reply with not defined status

This is possible if payload validation is done by proxy server and the actual backend knows nothing about schema.

**Comment by hkosova** [comment]
[OpenAPI Specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responses-object) says that the `responses` section does not need to cover ALL possible responses, so the missing definition for the 200 response does not make the Petstore spec invalid or the backend non-compliant.

**Comment by KES777** [comment]
>However, it is expected from the documentation to cover a successful operation response and any known errors.

As we can see neither `successful operation response`, neither `default` response are not covered.

**Comment by hkosova** [comment]
@KES777 you're right, I missed that part.

@webron thoughts?

**Comment by KES777** [comment]
1. The validator/editor non-compliant. It should warn about schema is invalid.
![delete1](https://user-images.githubusercontent.com/799021/42282853-78a8eb74-7fb0-11e8-93af-1d468f714a6c.jpg)

2. For cases when success and known errors are defined at schema, but response does not match the OpenAPI specification MUST define default behavior for payload validator.

I suppose that at this case the backend (or proxy which validates pass through data against schema) MUST response with `501 Not implemented` because the catched response is not implemented in schema.

Maye I wrong, but I see the schema as protector for unexpected data to come in/come out.

Also in our validator we respond with '400 Bad request' if request is not valid against the schema. Even if `400` is not described as valid response for target path.

**Comment by webron** [comment]
> The Responses Object MUST contain at least one response code, and it SHOULD be the response for a successful operation call.

That's the key sentence. SHOULD is not MUST. It's a recommendation, but failing to meet it does not invalidate anything. As such, changing the validation does not make sense. We really only need to make sure that there's at least one response defined.

As for the pet store itself, we're working on a new updated version of it, and hoping to tackle these things in it - however, these changes will not come into effect in the current version.

**Comment by shockey** [comment]
> Maye I wrong, but I see the schema as protector for unexpected data to come in/come out.

You're correct, but Swagger Editor validates the static content of your schema, not the live responses from your server. If you'd like to prevent any functionality that isn't described in the schema, you should do this server-side. Swagger Editor has no way to control what your server sends back.

I'm going to close this out, since as @hkosova and @webron have mentioned, the specification doesn't disallow partial coverage of possible responses. Thanks for the report!

**Comment by KES777** [comment]
OK.

but this is not mine server. This is `petstore` server.
![delete1](https://user-images.githubusercontent.com/799021/42491280-e61df7a6-841c-11e8-8f45-dc21ecfaa053.jpg)
