### ISSUE TITLE
Semantic error when using http trace with OpenAPI 3.0

### ISSUE THREAD

**Issue by mdegel** [swagger-api/swagger-editor#1817]
### Q&A (please complete the following information)
 - OS: Ubuntu 18.04
 - Browser: Chromium
 - Version: 66.0
 - Method of installation: Online Editor / Docker
 - Swagger-Editor version: 3.6.2
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
Default Swagger Editor available at https://editor.swagger.io/
_or_
Default Swagger 3.6.2 available via Docker

### OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  version: v1.0
  title: Trivial API
  description: Contains a trivial api
paths:
  '/some/api/{id}':
    trace:
      summary: An API method
      description: Does something.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID to identify a something.
      responses:
        '200':
          description: 'Some 200 OK'
```

### Describe the bug you're encountering
Swagger Editor shows the following error:
```
Errors
Semantic error at paths./some/api/{id}
Declared path parameter "id" needs to be defined as a path parameter at either the path or operation level
Jump to line 7
```

### To reproduce...

1. Go to https://editor.swagger.io/
2. Paste above OpenAPI definition
3. See error

### Expected behavior
I would expect the Swagger Editor to complain about the unknown HTTP TRACE instead of causing misleading errors.
**_Edit:_**
After checking the spec again it seems like the Editor should support HTTP TRACE (see https://swagger.io/docs/specification/paths-and-operations/). However a more meaningful warning for other (not allowed) HTTP methods would be helpful.

**Comment by shockey** [comment]
@mdegel, you're correct, TRACE is supported. This is a logical error in our validator - it wasn't looking at trace operations when enumerating which operations in a path define a path parameter.
