### ISSUE TITLE
No JSON-to-YAML conversion prompt when pasting JSON

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-editor#1818]
### Q&A (please complete the following information)
 - OS: Windows 7
 - Browser: Chrome 67
 - Method of installation: http://editor.swagger.io
 - Swagger-Editor version: 3.6.1, 3.6.2
 - Swagger/OpenAPI version: 2.0, 3.0

### Describe the bug you're encountering
Pasting JSON into the Editor no longer prompts to convert it to YAML. This worked in 3.6.0 but seems to have been broken in 3.6.1.

### Steps to reproduce
1. Copy this to the clipboard:
   ```
   {"foo": "bar"}
   ```
2. Open the Swagger Editor.
3. `Ctrl+A` then `Ctrl+V`.

### Expected behavior
"Would you like to convert your JSON into YAML?"

### Expected behavior
No conversion prompt.

**Comment by hkosova** [comment]
This should be fixed by PR https://github.com/swagger-api/swagger-editor/pull/1819

**Comment by shockey** [comment]
Indeed - #1819 fixed this. Thanks @hkosova!
