### ISSUE TITLE
Schema error at components.headers should NOT have additional properties

### ISSUE THREAD

**Issue by hellsius** [swagger-api/swagger-editor#1827]
### Q&A (please complete the following information)
 - OS: n/a
 - Browser: n/a
 - Version: n/a
 - Method of installation: cloned master and launched it through index.html
 - Swagger-Editor version: master
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
using default configuration

Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  title: Demo
  version: 0.0.1

paths:
  /demo:
    post:
      parameters: 
        - $ref: '#/components/headers/test'
        - $ref: '#/components/headers/demo'
        - $ref: '#/components/parameters/demo'
      responses:
        '200':
          description: response
          headers:
            'Test-Header':
              $ref: '#/components/headers/test'
            'Demo-Header':
              $ref: '#/components/headers/demo'
            'Demo-Parameter-Header':
              $ref: '#/components/parameters/demo'
            


components:
  headers:
    test:
      in: header
      name: Test-Header
      schema:
        type: string
        format: date
      description: test hader
      example: '2018-01-01'
    demo:
      #in: header
      #name: Demo-Header
      schema:
        type: string
        format: date
      description: demo header
      example: '2018-01-01'
      
  parameters:
    demo:
      in: header
      name: Demo-Parameter-Header
      schema:
        type: string
        format: date
      description: demo parameter header
      example: '2018-01-01'
```

### Screenshots
![example](https://user-images.githubusercontent.com/5901408/42519248-17a39ebc-8453-11e8-8afa-0d21726dac74.jpg)

### How can we help?
The editor is showing validation error that parameters in the `components.headers` part should not contain `in` and `name` definitions. However, if you remove those definitions from the parameter the request header is no longer displayed correctly (see the picture).

Is this a bug or there is a different approach to refer to the header parameters or I misunderstood the purpose of the `components.headers`?

One additional note, if you add same header parameters containing `name` and `in` definitions to `components.parameters` sections, then the validator does not display any errors.

**Comment by hkosova** [comment]
Unlike parameters, response headers do not have the `in` and `name` attributes - because they are implied from other things. As explained in the OpenAPI Specification:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#headerObject

> **Header Object**
> The Header Object follows the structure of the [Parameter Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#parameterObject) with the following changes:
> 1. `name` MUST NOT be specified, it is given in the corresponding `headers` map.
> 2. `in` MUST NOT be specified, it is implicitly in `header`.
> ...

**Comment by hellsius** [comment]
@hkosova Thanks for the explanation.
