### ISSUE TITLE
"should be an array" error caused by misspelled "type" values

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-editor#1832]
### Q&A (please complete the following information)
 - OS: Windows 7
 - Browser: Chrome 67
 - Method of installation: http://editor.swagger.io
 - Swagger-Editor version: 3.6.3
 - Swagger/OpenAPI version: 2.0

### Example Swagger/OpenAPI definition:
```yaml
swagger: '2.0'
info:
  title: test
  version: 0.0.0
paths: {}

definitions:
  Model1:
    type: int
```

### Describe the bug you're encountering
A misspelled `type` value triggers an odd error

> should be array

### Expected behavior
No "should be array" error.

### Screenshots
![image](https://user-images.githubusercontent.com/8576823/42638557-a1b83582-85f6-11e8-85b5-526f0df1435e.png)

**Comment by shockey** [comment]
I've opened a pull request (#1985) that will close this issue.

Here's what Swagger Editor reports with my changes:

```
Structural error at definitions.Model1.type
should be equal to one of the allowed values
allowedValues: array, boolean, integer, null, number, object, string
```

**Comment by hkosova** [comment]
@shockey 
>allowedValues: ..., null, ...

`type` cannot be `null` in OAS.

**Comment by shockey** [comment]
@hkosova, do you have a citation for that?

I'm seeing that OAS 2.0 indicates `Schema.type` as ["taken directly from the [JSON Schema draft-04] definition and follow the same specifications"](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema-object). 

JSON Schema, in turn, defines [seven primitive types](https://tools.ietf.org/html/draft-zyp-json-schema-04#section-3.5), including `null`.

Clarification would be a big help here. Thanks!

**Comment by hkosova** [comment]
@shockey In case of OAS2, it's not mentioned in the OpenAPI Specification explicitly, but @webron explained later that `type: null` is not supported
https://github.com/OAI/OpenAPI-Specification/issues/229#issuecomment-115379297

> **@webron** commented on Jun 25, 2015:
> `null` is not a valid type as it is [not listed](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types) in the spec. ... There's no full compliance with JSON Schema, and while the spec defers to JSON Schema in some sections, it also imposes limitations on others. If you feel there needs to be extra clarification on `null` not being usable anywhere, I'll be happy to clarify it in the spec itself.

**Comment by hkosova** [comment]
Interesting... The [official OAS2 schema](https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v2.0/schema.json#L1015-L1017) imports the `Schema.type` definition from the JSON Schema schema

```
        "type": {
          "$ref": "http://json-schema.org/draft-04/schema#/properties/type"
        },
```
and the JSON Schema schema uses
```
    "definitions": {
        ...
        "simpleTypes": {
            "enum": [ "array", "boolean", "integer", "null", "number", "object", "string" ]
        },
        ...
        "type": {
            "anyOf": [
                { "$ref": "#/definitions/simpleTypes" },
                ...
            ]
        },
```
meaning the OAS2 schema does indeed (sort of) allow `type: null`.

Which might be an oversight of the part of OAS spec authors because other places in the OAS2 schema (e.g. [`queryParameterSubSchema.type`](https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v2.0/schema.json#L656-L665)) list the possible `type` values explicitly and there's no `null` type there.

@webron could you please clarify this?

**Comment by webron** [comment]
`null` is not supported. The validation JSON Schema is not the source of truth. No `null`.
