### ISSUE TITLE
Authorize form does not replace URL variables

### ISSUE THREAD

**Issue by chrif** [swagger-api/swagger-editor#1837]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: Chrome
 - Version: 67
 - Method of installation: docker hub
 - Swagger-Editor version: 3.6.3
 - Swagger/OpenAPI version: 3.0.1

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.1
info:
  version: 1.0.0
  title: Swagger Petstore
paths:
  /pets:
    get:
      summary: List all pets
      responses:
        '200':
          description: A paged array of pets
servers:
  - url: 'http://{client}.domain.com/api'
    variables:
      client:
        default: acme
components:
  securitySchemes:
    login:
      type: oauth2
      flows:
        password:
          tokenUrl: oauth/v2/token
```
### Describe the bug you're encountering
Authorize form does not replace URL variables:
![image](https://user-images.githubusercontent.com/1298013/42779798-7481e36c-890f-11e8-9571-716ca37ecff9.png)

It instead makes a call to:
`http://%7Bclient%7D.domain.com/api`

![image](https://user-images.githubusercontent.com/1298013/42779739-4bd90bd4-890f-11e8-8e96-672d8f130778.png)

**Comment by shockey** [comment]
This issue was moved to swagger-api/swagger-ui#4740
