### ISSUE TITLE
source generation: discriminator ignored, properties flattened.

### ISSUE THREAD

**Issue by AlexeyNezhdanovGardena** [swagger-api/swagger-editor#1838]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: Chrome, also tried command line.
 - Version: 67
 - Method of installation: use online; download and run jar
 - Swagger-Editor version: no idea
 - Swagger/OpenAPI version:  OpenAPI 3.0

### Content & configuration
I am trying to generate a java source code that would automatically distinguish between object types that are defined as anyOf with discriminator. 

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  version: 0.1.0
  title: Example
paths:
  /a-path:
    get:
      responses:
        '200':
          description: example
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
components:
  schemas:
    Response:
      type: array
      items:
        $ref: '#/components/schemas/AnyPet'
    AnyPet:
      anyOf:
        - $ref: '#/components/schemas/Cat'
        - $ref: '#/components/schemas/Dog'
        - $ref: '#/components/schemas/Lizard'
    Pet:
      type: object
      required:
      - pet_type
      properties:
        pet_type:
          type: string
      discriminator:
        propertyName: pet_type
        mapping:
          cachorro: Dog
    Cat:
      allOf:
      - $ref: '#/components/schemas/Pet'
      - type: object
        # all other properties specific to a `Cat`
        properties:
          name:
            type: string
    Dog:
      allOf:
      - $ref: '#/components/schemas/Pet'
      - type: object
        # all other properties specific to a `Dog`
        properties:
          bark:
            type: string
    Lizard:
      allOf:
      - $ref: '#/components/schemas/Pet'
      - type: object
        # all other properties specific to a `Lizard`
        properties:
          lovesRocks:
            type: boolean
```

### Describe the bug you're encountering
The discriminator field gets totally ignored, it is not even present in the source code. The "AnyPet" object that I defined comes back as a fuse between the three which is not the intention.

### To reproduce...

Please generate the "Java Client" from the yaml file above and examine the AnyPet class.

### Expected behavior
A source that would return a list of AnyPet objects from which Cat or Dog or Lizard could be retrieved.
A list of Pet objects would be even better.

### Additional context or thoughts

I have an impression now that this part is just not implemented. Am I right?

**Comment by hkosova** [comment]
Code generation is done by [Swagger Codegen](https://github.com/swagger-api/swagger-codegen). Please open an issue in the Swagger Codegen repository https://github.com/swagger-api/swagger-codegen/issues.

**Comment by shockey** [comment]
Closing, as this is a Codegen issue 😄

**Comment by shockey** [comment]
This issue was moved to swagger-api/swagger-codegen#8441
