### ISSUE TITLE
Swagger Editor introduce field "More information: https://helloreverb.com"

### ISSUE THREAD

**Issue by vicmunoz** [swagger-api/swagger-editor#1842]
Hi,

It seems a custom implementation has been commited into main tree. To reproduce the bug is simple:
- Pick Pet Store json sample or any other (http://petstore.swagger.io/v2/swagger.json)
- Copy paste to online editor (http://editor.swagger.io/)
- Generate Client -> HTML
- Open index.html and it displays a field with "More information: https://helloreverb.com" just after info-description:

![helloreverb](https://user-images.githubusercontent.com/6018850/42941569-78c3a53c-8b5d-11e8-997a-d453464f0a5f.PNG)

As I've check, reproduced in online editor and in last docker image.

Regards,

**Comment by vicmunoz** [comment]
I've attempted with last docker image, and is hitting too.

**Comment by shockey** [comment]
Hey @vicmunoz! Thanks for the report.

Looks like this is a default in the Swagger Codegen generator:

https://github.com/swagger-api/swagger-codegen/blob/3b3f2d2fd633d2bcc1cb10dca74d15bba08dfd14/modules/swagger-codegen/src/test/java/io/swagger/codegen/options/StaticHtmlOptionsProvider.java#L26-L40

FWIW, Reverb is the company behind the original Swagger specification (cc @fehguy! your marks remain!).

I'm going to close this here since Swagger Editor isn't responsible for the field - consider opening this over at Swagger Codegen 😄

**Comment by ndjensen** [comment]
@vicmunoz, did you open an issue with Swagger Codegen?  If so, can you link to it?

**Comment by justinb26** [comment]
For anyone else coming across this thread: supplying a value for:
```
info:
  contact:
    - url: https://some.url
```
will replace this.

**Comment by JohnBoncek** [comment]
I don't want either of these contact things and if they have to be included, as seems the case, I want them to be obviously non-operative.  I was able to make the URL non-operative in a fairly obvious way by using about:blank.  Is there a similar way to make the e-mail address non-operative and obviously so?  I could make one up, like nobody@nowhere.com, but is there a better way?

**Comment by shockey** [comment]
As previously mentioned, references to Reverb are coming from Swagger Codegen. Please open an issue there

**Comment by shockey** [comment]
> I don't want either of these contact things and if they have to be included, as seems the case...

@JohnBoncek, per [the spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#infoObject), `info.contact` is _not_ required. IMO, it's a bug that the Codegen is injecting default values there when you don't provide them.

As mentioned before, the code causing this does not live in Swagger Editor, so you'll need to open an issue (or even better, a PR) in Swagger Codegen to get this fixed: http://github.com/swagger-api/swagger-codegen/

---

🔒 Locking as this isn't actionable for Swagger Editor.
