### ISSUE TITLE
Content-Disposition filename ignored still

### ISSUE THREAD

**Issue by andrej-vasilj** [swagger-api/swagger-editor#1861]
Hey guys, I've seen that there was a resolved issue regarding this a while back, but for some reason I just can't get file downloads to use the proper filename as defined by the Content-Disposition header.

So to summarize, I have a Django server that serves a file download upon GET request. It specifies 'application/octet-stream' as the Content-Type, it specifies the Content-Length and for Content-Disposition it specifies 'attachment; filename=test.zip'.

From the swagger editor when I test this end point I see that it generates the 'Download file' link and I can successfully download the file, but the filename is an auto-generated one and not 'test.zip'.

I'm running swagger-editor from the latest Docker image.

 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: Version 67.0.3396.99 (Official Build) (64-bit)
 - Method of installation: Docker (latest image)
 - Swagger-Editor version: latest
 - Swagger/OpenAPI version: Swagger 2.0

**Comment by andrej-vasilj** [comment]
Oh wow, that worked perfectly! I never would have thought of that myself, but in hindsight it makes a lot of sense. Thanks a lot for the quick support!

For anyone else who happens to be using Django, you can use the django-cors-headers library and add the following in your settings file:

CORS_EXPOSE_HEADERS = (
    'Content-Disposition',
)

**Comment by shockey** [comment]
@andrej-vasilj, awesome! thanks for sharing the solution as well 😄
