### ISSUE TITLE
hosted instance: Mixed content error when doing "generate server" over HTTPS.

### ISSUE THREAD

**Issue by mnagel** [swagger-api/swagger-editor#1862]
### Q&A (please complete the following information)
 - OS: Ubuntu 18.04
 - Browser: Chromium
 - Version: Version 68.0.3440.75 
 - Method of installation: Hosted
 - Swagger-Editor version: current/not shown in UI
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration
n/a

### Describe the bug you're encountering
Mixed content error when doing "generate server".

### To reproduce...

1. Go to https://editor.swagger.io/
2. Click on generate server -> python-flask
3. See that nothing happens
4. Open developer console
```
Mixed Content: The page at 'https://editor.swagger.io/' was loaded over HTTPS, but requested an insecure resource 'http://generator.swagger.io/api/gen/download/36fe8200-97ad-45dc-9110-0bcdcab3df75'. This request has been blocked; the content must be served over HTTPS.
Topbar.n.handleResponse @ topbar.jsx:236
```

### Expected behavior
download of zip with server code

### Additional context or thoughts
does not happen if using http://editor.swagger.io/

**Comment by shockey** [comment]
This is a Codegen issue, but we have the ability to work around it here.
