### ISSUE TITLE
No autocompletion for OAS3 responses

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-editor#1863]
### Q&A (please complete the following information)
 - OS: Windows 7
 - Browser: Chrome, Firefox latest
 - Method of installation: http://editor.swagger.io
 - Swagger-Editor version: 3.6.6
 - Swagger/OpenAPI version: 3.0

### Content & configuration
Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.1
info:
  title: test
  version: 0.0.0
paths:
  /foo:
    get:
      responses:
        # No autocompletion below "responses" :(
        '200':
          description: OK
```

### Describe the bug you're encountering
Autocompletion is not working inside the operation `responses` section in OpenAPI 3.0 specs.

Autocompletion for responses works fine in OpenAPI 2.0 specs.
Autocompletion also works fine in other places in OpenAPI 3.0 specs - e.g. inside `info`, `components` or `paths./foo.get`.

### To reproduce...
1. Paste the spec above to the editor.
2. Put the cursor directly under `description`.
3. Press <kbd>Ctrl</kbd>+<kbd>Space</kbd>.
Expected: Autocompletion popup appears.
Actual: No autocompletion popup.
4. Start typing `content` or `headers`.
Expected: Autocompletion popup appears.
Actual: No autocompletion popup.

### Screenshots
![response-autocompletion-oas3](https://user-images.githubusercontent.com/8576823/44024808-0c618942-9ef7-11e8-9b31-7044f281e19a.gif)

Autocompletion for responses works fine in OpenAPI 2.0 specs:
![response-autocompletion-oas2](https://user-images.githubusercontent.com/8576823/44024845-1fc1a030-9ef7-11e8-9b9f-c535734b78b9.gif)

**Comment by Respecttt** [comment]
Hello! i don't no but right now i have same problem too. Maybe do you know who can help fix it in Swagger-editor? Thank you
