### ISSUE TITLE
No syntax highlight for JSON files on Swagger Editor

### ISSUE THREAD

**Issue by ispmarin** [swagger-api/swagger-editor#1864]
### Q&A (please complete the following information)
 - OS: Debian Stable
 - Browser: firefox
 - Version: 61
 - Method of installation: tar.gz
 - Swagger-Editor version: latest git master
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
Standard configuration

Example Swagger/OpenAPI definition:
```json
{
  "openapi": "3.0.0"
}
```

### Describe the bug you're encountering
There is no syntax highlight when editing JSON.
### To reproduce...

1. Paste JSON OpenAPI definition

### Expected behavior
Syntax Highlight similar to YAML on JSON files

**Comment by shockey** [comment]
Hi @ispmarin!

As the README mentions:

> Swagger Editor lets you edit Swagger API specifications in YAML inside your browser and to preview documentations in real time. 

Swagger Editor is built to support YAML. Although JSON works (since YAML is a superset of JSON), we don't officially support it. That said, thanks for filing an issue!

Closing, as this is out of Swagger Editor's scope.
