### ISSUE TITLE
Lock version of API

### ISSUE THREAD

**Issue by froodley** [swagger-api/swagger-editor#1869]
We have had issues where editors inadvertently edited and saved old versions of an API, destroying history and confusing all.  Would love a feature to lock a version (or all versions) of an API.

**Comment by shockey** [comment]
@froodley, I'm going to close this out since there's very little context on what you're doing, how you're doing it, and what version you're using.

Please open a new issue, and follow the provided template - feel free to tag me in it so I see it!
