### ISSUE TITLE
Generated CURL seems wrong for mime/multipart uploads that have JSON parts - missing 'type=' option, wrong quotes. 

### ISSUE THREAD

**Issue by dvelitchkov** [swagger-api/swagger-editor#1871]
Running swagger editor from docker container, no customizations. 

### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: 68.0.3440.106
 - Method of installation: docker
 - Swagger-Editor version: latest
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: '3.0.0'
info:
  title: "Foo"
  version: 1.0.0
  
servers:
  - url: https://foo/v1/api
    
paths:
  /upload/:
    post:
      tags:
      - "upload"
      operationId: "upload"

      requestBody:
        required: true
        content: 
          multipart/form-data: # Media type
            schema:
              type: object
              properties: # Request parts
                file:
                  type: string
                  format: binary
                options:
                  type: object
                  properties:
                    some_array:
                      type: array
                      items:
                        type: string
                    max_bar:
                      type: integer
                      default: 300
                    
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties: 
                  foo:
                    type: string
```

### Describe the bug you're encountering
The generated CURL looks like this:
```sh
curl -X POST "https://foo/v1/api/upload/" -H "accept: application/json" -H "Content-Type: multipart/form-data" -F "options={ "some_array": [ "string" ], "max_bar": 0 }" -F "myfile=@bla;type=application/zip"
```

### Expected behavior
I think there are two issues here:

1. The "type=" option tha specifies the content-type for the "options" part is missing - I feel it should be "application/json", since that is the default for "objects". The "type=" option is actually present for the "myfile" part, which is great. 

2. The quotes for the "options" part need to be single quotes, e.g. `-F 'options={ "some_array": [ "string" ], "max_bar": 0 }'`, not `-F "options={ "some_array": [ "string" ], "max_bar": 0 }"`, as having double-quotes everywhere will just cause the shell to strip them. 

### Additional context or thoughts
The full correct curl should be:

```sh
curl -X POST "https://foo/v1/api/upload/" -H "accept: application/json" -H "Content-Type: multipart/form-data" -F 'options={ "some_array": [ "string" ], "max_bar": 0 };type=application/json' -F "myfile=@bla;type=application/zip"
```

**Comment by shockey** [comment]
This issue was moved to swagger-api/swagger-ui#4826
