### ISSUE TITLE
Lock API versions

### ISSUE THREAD

**Issue by froodley** [swagger-api/swagger-editor#1872]
### Content & configuration

Swagger/OpenAPI definition:
 ```yaml
 N/A / Proprietary
 ```

### Is your feature request related to a problem?
Our editors sometimes accidentally edit and save changes to an old version of an API in SwaggerHub editor.  This changes history and confuses people.

### Describe the solution you'd like
Ability to lock API version so changes cannot be saved.  Ability to lock all versions.  Role-based permission to unlock versions.

### Describe alternatives you've considered
We do check these in to our local VCS but when there is a difference between VCS and SwaggerHub it is very difficult to figure out what happened when and by whom.

**Comment by froodley** [comment]
@shockey Tagged with re: https://github.com/swagger-api/swagger-editor/issues/1869

**Comment by shockey** [comment]
@froodley, please direct this request to SmartBear's support: https://support.smartbear.com/message/?prod=SwaggerHub

Sorry to redirect you again, but Swagger Editor is a different codebase (and team) from SwaggerHub, so we can't handle requests for it here 😄
