### ISSUE TITLE
Angularjs: no declaration file (.d.ts) for "swagger-editor" / try npm i @types/swagger-editor 

### ISSUE THREAD

**Issue by Mathata** [swagger-api/swagger-editor#1875]
### Q&A (please complete the following information)
 - OS: [macOS]
 - Method of installation: [e.g. npm]
 - Swagger-Editor version: [e.g. 3]

Hi,

i downloaded the swagger-editor with npm (as well as some dependencies), but when trying to import it into my app.component.ts with
import { SwaggerEditorBundle, SwaggerEditorStandalonePreset } from 'swagger-editor';

it says no declaration file for swagger-editor found, try npm install @types/swagger-editor or declare a d.ts file. First one gives me a 404. Does anyone know what to do, why I get this "error" ?

Thx in advance

**Comment by shockey** [comment]
Hi @Mathata, this is a TypeScript problem See this issue for ways to solve it: https://github.com/Microsoft/TypeScript/issues/15031

Let me know if this gets you unstuck!

**Comment by Mathata** [comment]
Hi, thx for the answer. I switched to Express/ Bootstrap (still did not work in my case) and copied index.html and the dist package 1:1. Still I experience the Error that SwaggerEditorBundle is not defined when using 

window.onload = function() {
    // Build a system
    const editor = SwaggerEditorBundle({
..

seems there is still a problem fetching the dist/swagger-editor-bundle.js :(

**Comment by shockey** [comment]
Hmm, that’s no good. Is there a way for me to see the code you’re working with? Much easier to pinpoint the problem that way.

**Comment by Mathata** [comment]
the old code I don‘t have any more. Thx nonetheless!

**Comment by shockey** [comment]
Ok! Closing as resolved.
