### ISSUE TITLE
Try It Out GET request: OPTIONS returns 200 but Server Response is Undocumented/TypeError: Failed to fetch

### ISSUE THREAD

**Issue by tunecrew** [swagger-api/swagger-editor#1878]
**Env:**
Swagger Editor in Swagger Hub - Routing request via browser
Browser - Chrome 68.0.3440.106 on MacOS
Openapi - 3.0.1
API endpoint is Django Rest Framework running locally @ `https://localhost:8443` w/ a self-signed certificate (that is accepted by the browser)
django-cors-headers is installed with `CORS_ORIGIN_ALLOW_ALL = True` set
The API endpoint requires an authorization: {token} header with a custom JWT

Trying a simple GET request from TRY IT OUT -> EXECUTE results in the following in the network console:

**General**
> Request URL: https://localhost:8443/v1/userprofile
> Request Method: OPTIONS
> Status Code: 200 OK
> Remote Address: [::1]:8443
> Referrer Policy: no-referrer-when-downgrade

**Response Headers**
> Access-Control-Allow-Headers: accept, accept-encoding, authorization, content-type, dnt, origin, user-agent, x-csrftoken, x-requested-with
> Access-Control-Allow-Methods: DELETE, GET, OPTIONS, PATCH, POST, PUT
> Access-Control-Allow-Origin: *
> Access-Control-Max-Age: 86400
> Content-Length: 0
> Content-Type: text/html; charset=utf-8
> Vary: Origin

**Request Headers**
> Provisional headers are shown
> Access-Control-Request-Headers: authorization
> Access-Control-Request-Method: GET
> DNT: 1
> Origin: https://app.swaggerhub.com
> Referer: https://app.swaggerhub.com/apis/remetrik/remetrik-api/1.0.0
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Server Response**
> Undocumented / TypeError: Failed to fetch

Then nothing else happens (no subsequent GET request)

If I cut and paste the Curl command (and insert -k to ignore the ssl cert) I get the response I'm expecting from the API

Same thing if I run Swagger Editor locally from the docker image.

So this seems like a CORS issue but I'm at a loss as to why - what's misconfigured here?

**Comment by shockey** [comment]
@tunecrew, can you check your browser console for error messages after attempting the request?

**Comment by tunecrew** [comment]
@shockey oh good call should have included that also - console error is:

> Failed to load https://localhost:8443/v1/userprofile: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'https://app.swaggerhub.com' is therefore not allowed access.

Definitely do not understand this message

**Comment by tunecrew** [comment]
@hkosova thank you got it to work - had not seen the separate doc page for Hub vs Editor.
