### ISSUE TITLE
json array/list of objects in html2 generated report response schema

### ISSUE THREAD

**Issue by LorenzoTesta** [swagger-api/swagger-editor#1891]
### To reproduce...

1. Go to 'https://editor.swagger.io/'
2. Click on 'Generate Client'
2. Click on 'html2'
4. Open the index.html file
5. Go to 'findPetsByStatus'
6. Go in the 200 Response schema
7. See the error

### Expected behavior
See an array of objects

**Comment by shockey** [comment]
This issue was moved to swagger-api/swagger-codegen#8796
