### ISSUE TITLE
npm install Webpack and eslint peer dependency issue

### ISSUE THREAD

**Issue by flynnmattson** [swagger-api/swagger-editor#1895]
### Q&A
 - OS: macOS
 - Browser: chrome
 - Version: N/A
 - Method of installation: normal installation directions
 - Swagger-Editor version: 3.6.11 (master branch)
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
Just tried following normal setup instructions:
- cloned code to computer locally
- ran "npm install" and returns these peer dependency warnings:

npm WARN eslint-config-standard@6.2.1 requires a peer of eslint@>=3.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-standard-jsx@3.2.0 requires a peer of eslint@>=3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-standard@2.0.1 requires a peer of eslint@>=3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN expose-loader@0.7.5 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN schema-utils@0.4.5 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-server@2.11.3 requires a peer of webpack@^2.2.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN uglifyjs-webpack-plugin@1.2.7 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN The package deepmerge is included as both a dev and production dependency.

Webpack and eslint are dependencies in the package.json but neither are high enough versions for these other packages. I tried changing the version numbers but it only causes more problems.

- ran "npm run dev" and received these errors on the browser console at http://0.0.0.:3200/
![screen shot 2018-10-04 at 3 59 04 pm](https://user-images.githubusercontent.com/12478032/46507653-755d6900-c7ee-11e8-9e0a-aa643f48adf5.png)

- ran "npm run build" and received these errors:

ERROR in swagger-editor-standalone-preset.js from UglifyJs
Import statement may only appear at top level [./src/standalone/index.js:1,0][swagger-editor-standalone-preset.js:2435,1]

ERROR in swagger-editor.js from UglifyJs
Import statement may only appear at top level [./src/index.js:1,0][swagger-editor.js:2435,1]

ERROR in swagger-editor-bundle.js from UglifyJs
Import statement may only appear at top level [./src/index.js:1,0][swagger-editor-bundle.js:2435,1]

Let me know if you need any further details

**Comment by shockey** [comment]
@flynnmattson, what npm version are you using?

**Comment by flynnmattson** [comment]
@shockey I'm using node 9.8.0 and npm 5.6.0

I just updated npm to 6.4.1 and still the same issue.

**Comment by shockey** [comment]
@flynnmattson, I'm not seeing these peerDependency warnings, just the deepmerge one:

```sh
➜  npm -v
6.1.0
➜  git clone git@github.com:swagger-api/swagger-editor.git editor
Cloning into 'editor'...
remote: Enumerating objects: 33810, done.
remote: Total 33810 (delta 0), reused 0 (delta 0), pack-reused 33810
Receiving objects: 100% (33810/33810), 206.43 MiB | 2.69 MiB/s, done.
Resolving deltas: 100% (19110/19110), done.
➜  cd editor
➜  npm i

> fsevents@1.2.4 install /private/tmp/editor/node_modules/fsevents
> node install

[fsevents] Success: "/private/tmp/editor/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> iltorb@1.3.10 install /private/tmp/editor/node_modules/iltorb
> detect-libc prebuild-install || node-gyp rebuild


> cypress@3.1.0 postinstall /private/tmp/editor/node_modules/cypress
> node index.js --exec install


Cypress 3.1.0 is already installed in /Users/kyle/Library/Caches/Cypress/3.1.0


> react-ace@4.4.0 postinstall /private/tmp/editor/node_modules/react-ace
> opencollective postinstall


                        Thanks for installing react-ace 🙏
                 Please consider donating to our open collective
                        to help us maintain this package.

                            Number of contributors: 77
                               Number of backers: 5
                              Annual budget: US$ 26
                             Current balance: US$ 63

         👉  Donate: https://opencollective.com/react-ace/donate

npm WARN The package deepmerge is included as both a dev and production dependency.

added 1996 packages from 1707 contributors and audited 17402 packages in 28.266s
found 26 vulnerabilities (12 low, 6 moderate, 6 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by flynnmattson** [comment]
@shockey The first time you run "npm install" the peer dependency warnings aren't shown but after running it again you'll see them appear. Even after installing all of the node_modules once you'll still see the other errors after running "npm run dev" or "npm run build"

**Comment by shockey** [comment]
Okay, I see it now, thanks.

Looks like we have some version mismatches among dependencies (though everything seems to work anyways).. we need to move to the following:
- `eslint@3`
- `webpack@2`
- `extract-text-webpack-plugin@2`

Additionally, `deepmerge` needs to be removed from `devDependencies`.

**Comment by flynnmattson** [comment]
Yeah, the current build runs great for me, its just if I want to make any sort of changes to the source. Thank you for taking a look!

**Comment by tim-lai** [comment]
Closing, as outdated. Feel free to create a new issue if necessary, thanks!
