### ISSUE TITLE
String example reference to a components/examples/ELEMENT trigger an error but render ok

### ISSUE THREAD

**Issue by TrustworthySystems** [swagger-api/swagger-editor#1905]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Firefox Quantum
 - Version: 61.0.2 (64-bit)
 - Method of installation: download from master branch *as zip file* at https://github.com/swagger-api/swagger-editor commit: a7a7189de14fe4bac77208c0506a0c3ee0b740bd, local installation *(just unpack and run the index.html inside)*
 - Swagger-Editor version: **release: v3.6.15** as the commit said
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0

info:
  title: API test with Examples
  version: 0.0.1

servers:
  - url: https://api.example.com/
    description: example server

paths:
  /v1/tos:
    get:
      summary: Terms of service
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                type: string
              example:
                $ref: "#/components/examples/tos"
        default:
          description: Unexpected error

components:
  examples:
      tos: |-
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="UTF-8" />
            <title>Terms of service</title>
          </head>
          <body>
            <h1 class="title">Terms of service</h1>
            <div class="version">Version 0.0.1</div>
            <div class="authors">
              <span class="author">Yours truly</span>
            </div>
          </body>
        </html>
```

Swagger-Editor configuration options:

***No option or configuration used, just plain default values.***
local installation *(just unpack the downloaded zip and run the index.html inside)*

```
No query or interaction done
(not required to reproduce the problem),
just load the YAML file provided.
```

### Describe the "bug" you're encountering (don't know how to classify this strange behavior)
Render is correct but and error is reported, the OpenAPI definition was reduced to a minimum for clarity:
Trying to place a response example in the ***components/example section*** as described in https://swagger.io/docs/specification/adding-examples/ the ***editor report an error*** when the example ***is not an object***, in this case the sample is ***type: string*** because the content is HTML.

The editor render is correct, but reports an error:
```
Errors

Schema error at components.examples['tos']
should be object
Jump to line 29
```

### To reproduce...

1. Go to https://github.com/swagger-api/swagger-editor
1. Make sure you are in **_master_** branch
1. Click on ***Clone or download*** green button
1. Select Download ZIP
1. Unpack ZIP file
1. Go into `swagger-editor-master` directory
1. Run `index.html`
1. In the Swagger menu select: File -> Clear editor
1. Copy provided OpenAPI definition and Paste it in the editor

### Expected behavior
Right side of the editor with the documentation, but it shows and error ***and the correct example!!!***

### Screenshots

_**The Error:**_
![image](https://user-images.githubusercontent.com/20143835/48307952-3e4a4800-e550-11e8-9875-2dcafc07348f.png)

_**The Correct Example Render:**_
![image](https://user-images.githubusercontent.com/20143835/48307979-c7617f00-e550-11e8-9858-f44460923fa6.png)

### Additional context or thoughts

May be this is just a limitation for defining reference to examples others than object, I let you to clarify this. I review many issues but could not find any one like this.

**Comment by shockey** [comment]
Hi @TrustworthySystems!

The validator is correct and the UI is wrong here.

Your example should be written like this:
```yaml
components:
  examples:
      tos:
        value: |-
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="UTF-8" />
              <title>Terms of service</title>
            </head>
            <body>
              <h1 class="title">Terms of service</h1>
              <div class="version">Version 0.0.1</div>
              <div class="authors">
                <span class="author">Yours truly</span>
              </div>
            </body>
          </html>
```

Unfortunately, the UI doesn't handle this correctly. I'll fix that, though 😄

**Comment by TrustworthySystems** [comment]
Thank you very much for the clarification @shockey
