### ISSUE TITLE
"Upload file" popup stays open after import

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-editor#1908]
### Q&A (please complete the following information)
 - OS: Windows 7
 - Browser: Chrome latest
 - Method of installation: http://editor.swagger.io
 - Swagger-Editor version: 3.6.15
 - Swagger/OpenAPI version: any

### Describe the bug you're encountering
When you use the "File > Import File" command to open a local file, click "Upload file" popup stays open after the file was imported. There are no errors in the browser console. Only the "Cancel" and [x] button close the popup.

### To reproduce...

1. Save http://petstore.swagger.io/v2/swagger.yaml to your computer.
2. From the Swagger Editor menu, select "File > Import File".
3. Click "Choose File" and browse for the local YAML file you downloaded.
4. Click "Open file".

### Expected behavior
"Upload file" popup is closed and the selected file is loaded into the editor.

### Actual behavior
The selected file is loaded into the editor, but the "Upload file" popup stays open.

### Workaround
After clicking "Open file" click "Cancel" or [x].

### Screenshots
![upload-file](https://user-images.githubusercontent.com/8576823/48833576-ba346380-ed8c-11e8-8812-253b22e2dfaf.png)

**Comment by shockey** [comment]
Closely related: https://github.com/swagger-api/swagger-editor/issues/1939
