### ISSUE TITLE
Bug in build java client

### ISSUE THREAD

**Issue by MohamedTaher** [swagger-api/swagger-editor#1918]
### Q&A
 - OS: Windows
 - Browser: chrome
 - Version: n/a
 - Method of installation: n/a
 - Swagger-Editor version: app.swaggerhub.com
 - Swagger/OpenAPI version: app.swaggerhub.com

### Describe the bug you're encountering
Today, When I build a Java client using "./gradle build" command then I get this error

> FAILURE: Build failed with an exception.

>* What went wrong:
>A problem occurred configuring root project 'swagger-java-client'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find any matches for com.android.tools.build:gradle:2.3.+ as no versions of com.android.tools.build:gradle are available.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/maven-metadata.xml
         https://jcenter.bintray.com/com/android/tools/build/gradle/
     Required by:
         project :

so, I changed the gradle version from 2.3.+ to  2.3.0 then I run the build command again"./gradle build", and It's working well

note: Before today this bug didn't happen.

### To reproduce...

1. Download a Java client from the website app.swaggerhub.com
2. Extract the WinRAR file
3. run "./gradle build" from PowerShell 

### Expected behavior
get ''BUILD SUCCESSFUL'' message 

### Screenshots
![image](https://user-images.githubusercontent.com/16255446/49816743-33fdb280-fd77-11e8-9551-632393e2ba41.png)

**Comment by shockey** [comment]
Hey @MohamedTaher!

We don't provide support for SwaggerHub usage here - please open a ticket with them: https://support.smartbear.com/swagger-hub/
