### ISSUE TITLE
OAS 3.0 Required inside anyOf

### ISSUE THREAD

**Issue by toxicOctopus** [swagger-api/swagger-editor#1919]
Hello. I think this example should not be valid:

```yaml
openapi: 3.0.1
info:
  title: API
  version: '1'
servers:
  - url: ''
paths:
  /example.json:
    post:
      summary: Example
      requestBody:
        content:
          application/json:
            schema:
              title: Example
              type: object
              required:
                - name
              anyOf:
                - required:
                    - phone
                - required:
                    - email
              properties:
                phone:
                  type: string
                email:
                  type: string
                name:
                  type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: integer
          description: Example
```
Because it works the same as oneOf:
```yaml
openapi: 3.0.1
info:
  title: API
  version: '1'
servers:
  - url: ''
paths:
  /example.json:
    post:
      summary: Example
      requestBody:
        content:
          application/json:
            schema:
              title: Example
              type: object
              required:
                - name
              oneOf:
                - required:
                    - phone
                - required:
                    - email
              properties:
                phone:
                  type: string
                email:
                  type: string
                name:
                  type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: integer
          description: Example
```

**Comment by jdegre** [comment]
not sure i got what you meant exactly by this issue; just to comment that both examples you wrote above, express different presence requirments for phone and email properties.

1st example requires that either phone or email _or both_ properties are present in the request.

2nd example requires that either phone or email _but not both_ properties are present in the request.

**Comment by toxicOctopus** [comment]
> 1st example requires that either phone or email or both properties are present in the 
request.

which equals to "phone or email must be present in the request"

> 2nd example requires that either phone or email but not both properties are present in the request.

why in this case both can't be present in the request? If the property is not in the required it doesn't mean it can't be presented in the request

**Comment by jdegre** [comment]
> why in this case both can't be present in the request? If the property is not in the required it doesn't mean it can't be presented in the request

because that's how oneOf works... if you have both properties present in the request, both branches in the oneOf will be "true", and therefore, the oneOf check will fail, since oneOf requires that only one of the branches is true.

**Comment by toxicOctopus** [comment]
> because that's how oneOf works... if you have both properties present in the request, both branches in the oneOf will be "true", and therefore, the oneOf check will fail, since oneOf requires that only one of the branches is true.

tyvm, issue closed
