### ISSUE TITLE
Try out POST sends OPTIONS

### ISSUE THREAD

**Issue by IceflowRE** [swagger-api/swagger-editor#1921]
### Q&A (please complete the following information)
 - OS: [e.g. ArchLinux]
 - Browser: [e.g. Firefox]
 - Version: [e.g. 64]
 - Method of installation: [e.g. online editor swaggerhub]
 - Swagger/OpenAPI version: [e.g. OpenAPI 3.0]

### Description
Sending an POST request with the Try Out function will send an OPTIONS to the server. Which returns 405. But the POST request will not be sent. Which can be verified over the browser development tools.
(Server was localhost and i use browser query)

**Comment by jdegre** [comment]
Looks like normal [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) behaviour. Before sending POST request to a different server ("different" means a server other than the server in the URL of the page you're accessing), the browser sends OPTIONS and expects to receive Access-Control-Allow-Methods header in the response. If it doesn't, CORS is not allowed, and the real request (POST) is not even sent.

**Comment by IceflowRE** [comment]
It is still not the expected behaviour (at least for me).
Especially if i can define the `OPTIONS` method separately. I want to test the `POST` not `OPTIONS` & `POST`.

**Comment by jdegre** [comment]
What I meant is that what you're seeing is the normal behaviour _of the browser_, enforcing the CORS standard. There is nothing the Swagger tools can do about it: if you test your API from, say, swaggerhub.com, or editor.swagger.io, and your test API server is in a different host, then _your browser_ will trigger CORS enforcement.
