### ISSUE TITLE
No validation error if request body schema references a requestBody component instead of a schema

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-editor#1931]
### Q&A (please complete the following information)
 - OS: Windows 7
 - Browser: Chrome latest
 - Method of installation: http://editor.swagger.io
 - Swagger-Editor version: 3.6.20
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  title: Invalid request body reference
  version: 0.0.0
paths:
  /foo:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/Foo'
      responses:
        '200':
          description: OK

components:
  requestBodies:
    Foo:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Foo'
  schemas:
    Foo:
      type: array
      items:
        type: string
```

### Describe the bug you're encountering
In the definition above, `requestBody.content.<media-type>.schema` references a definition from `#/components/requestBodies/` instead of a schema from `#/components/schemas/`. Syntax validation does not flag this.

### Expected behavior
An error about incorrect reference.

### Actual behavior
No error.

### Additional context or thoughts
The root cause might be related to #1717.

**Comment by shockey** [comment]
Marking as an enhancement, as we don't have $ref path validation at all for OpenAPI 3 yet.
