### ISSUE TITLE
Unable to post request with Path and Body parameters together in a post request.

### ISSUE THREAD

**Issue by adarshpandeyrinku** [swagger-api/swagger-editor#1933]
Hi Team,

While working on Swagger 2.0, I am trying to send parameters in body as well as Path in a single post request. it is reflecting path parameter correctly but body parameters are missing... 

Below is example of my Yaml file:
 
post:
    operationId: TestMe
    consumes:
        -   application/json
    produces:
        -   application/json
    parameters:
        -   name: GroupID
            in: path
            description: Unique identifier of the group.
            required: true
            type: integer
            format: int32
        -   name: myExtId
            in: path
            description: Unique identifier of my extension.
            required: true
            type: string
        -   name: Model
            in: body
            description: testing of body with string parameter.
            type: string
            required: true

**NOTE:** I've tried making all the parameter values as not-required by making **required: false** in every parameter but it didn't work.

I am suspecting swagger 2.0 doesn't allow us to send Body and Path parameters together. If my understanding is correct, is there any workaround we've ?

**Comment by hkosova** [comment]
In the body parameter, replace
```yaml
type: string
```
with
```yaml
schema:
  type: string
```

Everything else is fine - just make sure the indentation is correct.

**Comment by adarshpandeyrinku** [comment]
Hi Thanks for the response, I've even tried with it but forgot to mention previously.

Any other suggestions please ?

**Comment by hkosova** [comment]
Requests with both path and body parameters work fine for me in Chrome on Windows:

![path-body-params](https://user-images.githubusercontent.com/8576823/51478699-3ce19b00-1d9d-11e9-89cc-14f3ed53765e.gif)

Here's the definition that I used:
```yaml
swagger: "2.0"
info:
  title: test
  version: 0.0.0
host: httpbin.org
basePath: /anything
paths:
  /post/{GroupID}/{myExtId}:
    post:
      operationId: TestMe
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: GroupID
          in: path
          description: Unique identifier of the group.
          required: true
          type: integer
          format: int32
        - name: myExtId
          in: path
          description: Unique identifier of my extension.
          required: true
          type: string
        - name: Model
          in: body
          description: testing of body with string parameter.
          schema:
            type: string
          required: true
      responses:
        200:
          description: OK
```

Does the example above work for you?

**Comment by hkosova** [comment]
Also, please provide the following information (as required by the issue template):

* Swagger Editor version (browser dev tools > Console tab > evaluate `versions`)
* Method of installation: [e.g. npm, dist assets, online version at http://editor.swagger.io]
* OS version
* Browser and version
* Your complete YAML/JSON definition (if it's too long, put it in a [gist](https://gist.github.com) and post a link here)
* What do you mean by "body parameters are missing" - are they not displayed in the UI, or are they missing from the generated cURL command, or are they missing in the data that your server receives?

**Comment by adarshpandeyrinku** [comment]
Hi,

I am using visual studio code and node js terminal to generate postman collection using swagger2-postman-generator node package. while I am running the same yaml it is not showing the body parameters in postman rather displaying a message provided for body parameter. Here are the snapshot of my code:

![image](https://user-images.githubusercontent.com/12835237/51480984-87244580-1db8-11e9-83f7-0888adc4a212.png)

![image](https://user-images.githubusercontent.com/12835237/51481106-eb470980-1db8-11e9-8eb2-eae020d2df09.png)

By running the command I can see the json file generated successfully but when I opened it in postman, it is not showing any parameters in body and just showing the description, as this snapshot...

![image](https://user-images.githubusercontent.com/12835237/51481286-850eb680-1db9-11e9-87d5-855eacc84d98.png)

**Comment by hkosova** [comment]
Open a ticket with swagger2-postman-generator and/or Postman instead. These projects are not related to the Swagger Editor in any way.

**Comment by adarshpandeyrinku** [comment]
ok, can you please guide me, in which particular section, i should raise this issue ?
