### ISSUE TITLE
Does auto-complete works only for yaml format?

### ISSUE THREAD

**Issue by arjunballa** [swagger-api/swagger-editor#1937]
I copied petstore-swagger.json content into Swagger Editor https://editor.swagger.io/ checked for suggesting by hitting ctrl+space and I see no suggestions. They work for yaml.

Also, if I start out with empty editor the auto-complete writes yaml code by default. Can I make it json?

I am trying to embed swagger-editor in one of the our pages for inline editing of swagger.json and I don't need top menu (menu items) and right pane (Swagger UI). Are there any configurations I can pass?

**Comment by arjunballa** [comment]
@shockey Auto-complete only works for YAML?

When I  start with empty document on https://editor.swagger.io/ I see OpenAPI 2.0 suggestions only. I don't see OpenAPI 3.0 suggestions. Also I am not able to find documentation on how to open editor in 3.0 or 2.0 or do the switch. Can you please point me to doc?

Also suggestion only work in yaml mode? I don't see json suggestions or json auto completion.

See screenshot which shows Open API 2.0 suggestion. Open API 3.0 should have root property suggestion as "openapi" but I see only "swagger" as root element which is 2.0 property.

![image](https://user-images.githubusercontent.com/613351/52083105-65af2080-2553-11e9-807c-e4145dfc8ab2.png)

auto complete and suggestion only work for yaml.
![image](https://user-images.githubusercontent.com/613351/52083290-e4a45900-2553-11e9-8cae-57bfbe4da8a2.png)

They don't work for JSON.
![image](https://user-images.githubusercontent.com/613351/52083516-7d3ad900-2554-11e9-8ec8-20e1b4d9b4a1.png)

**Comment by shockey** [comment]
> Auto-complete only works for YAML?

@arjunballa correct - Swagger Editor only officially supports editing YAML. We highly encourage editing in YAML (as it's much easier to write by hand) and using the File menu to export to JSON.

> I don't see OpenAPI 3.0 suggestions. Also I am not able to find documentation on how to open editor in 3.0 or 2.0 or do the switch. Can you please point me to doc?

OpenAPI 3.0 suggestions will appear once you start your document with `openapi: "3.0.0"`:

<img width="686" alt="image" src="https://user-images.githubusercontent.com/680248/52309078-a8626580-2964-11e9-9444-64ed09d670c0.png">

Good point on 2.0 autocomplete being the default though - we should be disabling both until a version is indicated by the user.
