### ISSUE TITLE
Make importing file more comfortable

### ISSUE THREAD

**Issue by aivarannamaa** [swagger-api/swagger-editor#1939]
### The problem
Importing a file into Swagger editor requires too many clicks:

* "File menu"
* "import file"
* "Choose file", 
* <working with file dialog>
* "Open file"

### Describe the solution you'd like
Override Ctrl+O shortcut for opening the file dialog. (If browser doesn't allow this, then open the box with "Choose file" button). Start importing right after the file dialog closes (without requiring another click).

### Alternative 
Make "Choose file" button always visible in the toolbar and process import right after file dialog closes.

**Comment by shockey** [comment]
@aivarannamaa, I decided against overriding browser default hotkeys here, but we've eliminated the modal completely so it does take less clicks now 😄

**Comment by aivarannamaa** [comment]
Thanks! :)
