### ISSUE TITLE
Input gets duplicated while typing

### ISSUE THREAD

**Issue by Qwertie-** [swagger-api/swagger-editor#1940]
### Q&A (please complete the following information)
 - OS: Fedora 29
 - Browser: Firefox 65
 - Method of installation: hosted version on swagger hub
 - Swagger-Editor version: Whatever the version running on app.swaggerhub.com is as of opening this issue
 - Swagger/OpenAPI version: OpenAPI 3.0

### Describe the bug you're encountering
While typing I get weird duplication issues
![screenshot from 2019-02-04 20-47-00](https://user-images.githubusercontent.com/6601505/52202493-80b8c200-28be-11e9-824f-551301c33d43.png)
After `servers:` I typed `abc` and this is how it came out

### To reproduce...

I'm not quite sure as I assume this must not happen for most people but it has happened fairly consistently for me just after creating a default template api and starting to input details

### Screenshots
Lots of errors in the console
![screenshot from 2019-02-04 20-42-55](https://user-images.githubusercontent.com/6601505/52202544-afcf3380-28be-11e9-9953-53b27c58fd8d.png)

**Comment by shockey** [comment]
Hi @Qwertie-!

We don't provide support for SwaggerHub in this issue tracker, so I'm going to have to close this out. You can reach SwaggerHub product support [here](https://support.smartbear.com/message/?prod=SwaggerHub).

FWIW, I happen to remember that this was a known issue in SwaggerHub, which was fixed a couple of weeks ago. If you're still seeing this bug even after emptying your cache, I'm confident they'd be very interested in hearing about this.
