### ISSUE TITLE
HTTPS versus HTTP differences in editor

### ISSUE THREAD

**Issue by JerryMWeeks** [swagger-api/swagger-editor#1947]
### Q&A (please complete the following information)
 - OS: [Windows 10 / Azure]
 - Browser: [All (Edge & Chrome tested]
 - Version: [current]
 - Method of installation: [npm - minimal]
 - Swagger-Editor version: [current]
 - Swagger/OpenAPI version: [only what comes with the editor at the moment]

### Content & configuration
If you load Swagger  editor via HTTPS the menu  "File -> New" vanishes (this seems to be the same on your demo instance)
Load via HTTP and the menu "File -> New" returns
This is on exactly the same server, same install.

### Screenshots
http version
![swaggereditor http menu](https://user-images.githubusercontent.com/19207251/52655355-e07d2180-2eeb-11e9-9db6-765729db3c80.png)
https version
![swaggereditor https menu](https://user-images.githubusercontent.com/19207251/52655400-fab6ff80-2eeb-11e9-9079-577a7d06c338.png)

### How can we help?
Can you explain why the menus are different between https and http?

**Comment by shockey** [comment]
Hi @JerryMWeeks, 

The two versions of Swagger Editor you're seeing couldn't be more different - the first is v2, which was retired in 2015, and the second is v3, our current version.

Can you share more about how you're consuming Swagger Editor? npm definitely shouldn't be giving you both version 2 and 3.

**Comment by JerryMWeeks** [comment]
OK, I think my build went like this:
git clone https://github.com/swagger-api/swagger-editor
npm install
npm run build
copy this set of folders into another folder (swagger-editor in my case)
![swaggerfolders](https://user-images.githubusercontent.com/19207251/52784327-aaa37e80-304c-11e9-9e34-55d7598dc7e4.png)
from that folder run http-server
open http://localhost:8080/swagger-editor/
and you have the http menu above (your "old version"?) 
FTP the files minus node_modules to an Azure web app
Run up Azure App-Service-editor followed by Open console and repeat npm install
Add a web.config with this in (plus the usual)
`<staticContent>
            <mimeMap fileExtension=".json" mimeType="application/json" />
            <mimeMap fileExtension=".yaml" mimeType="application/yaml" />
     </staticContent>`
Restart the app
load https://<azure-app-server/swagger-editor
and you get the new menu!
If it helps the index.html file has this:
` <body>
    <div class="total-wrapper" ui-view></div>
    <script src="dist/bundle.js"></script>
    <script src="scripts/branding.js"></script>
</body>`
and the dist folder has the following files:
05/02/2019  13:39         1,432,187 91baf32caa045b74d22e.worker.js
05/02/2019  13:40         8,060,172 91baf32caa045b74d22e.worker.js.map
05/02/2019  13:41           234,019 a21d96a6391866c78f2c.worker.js
05/02/2019  13:41         1,574,289 a21d96a6391866c78f2c.worker.js.map
05/02/2019  13:41         3,002,783 bundle.js
05/02/2019  13:44        15,644,024 bundle.js.map
05/02/2019  13:48        24,247,894 styles.css
05/02/2019  13:48           418,726 styles.css.map

**Comment by JerryMWeeks** [comment]
The view difference is due to **bundle.js** which contains what you call the older menu, including "New" and "Load Example", no idea how I ended up with it.

The newer code uses swagger-editor-bundle.js which doesn't have "Open Example", or "New".

I like the earlier "Open Example" and "New" - it is user friendly, especially when you need to get team members up to speed.
