### ISSUE TITLE
Windows installation fails

### ISSUE THREAD

**Issue by tutosfaciles48** [swagger-api/swagger-editor#1950]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Method of installation: yarn (and also npm)
 - Swagger-Editor version: 3.6.22

### Describe the bug you're encountering
The installation faill each times

### To reproduce...

1. Go to swagger-editor folder
2. Make a _npm i_ or _yarn (install)_

### Additional context or thoughts
[log_yarn_swagger-editor.txt](https://github.com/swagger-api/swagger-editor/files/2876792/log_yarn_swagger-editor.txt)

**Comment by tutosfaciles48** [comment]
I try to edit webpack version in package.json file but it change nothing

**Comment by bkuznetsov** [comment]
Same problem.

**Comment by Callmoon** [comment]
You need a Python 2 version linked in your path variable because the python 3 version has another print function. 
Maybe you will get afterwards a `error MSB4132` which can be resolved by like described in this issue:
https://github.com/chjj/pty.js/issues/60#issuecomment-284125481
