### ISSUE TITLE
Required nested properties in RequestBody not working as expected

### ISSUE THREAD

**Issue by mbianchidev** [swagger-api/swagger-editor#1952]
### Q&A 
 - OS: Window10
 - Browser: Chrome
 - Version: 72
 - Method of installation: Web
 - Swagger-Editor version: https://editor.swagger.io/ < this one
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
Just go on https://editor.swagger.io/ use this yaml and generate an html client ( > generate client > html), open index.html in the .zip file

Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
info:
    title: Example API
    description: Example API specification
    version: 0.0.1
servers:
  - url: https://example/api

paths:
  /secure/oauth/services/v2/Nested:
    post:
      summary: Try nested
      description: Used to post Nested obj
      requestBody:
        required: true
        content:
          application/json:
            schema:
                type: object 
                required:
                - id
                - nestedobj
                properties:
                    id:
                      type: integer
                      description: id of nested obj
                    nestedobj:
                      type: object 
                      required:
                      - field1
                      description: nested object
                      properties:
                        field1:
                          type: string
                        field2:
                          type: string
      responses:
        '200':
          description: Nested object OK
```

### Screenshots
![image](https://user-images.githubusercontent.com/37507190/53160540-725dec00-35c8-11e9-8620-3a344accd51f.png)

### How can we help?
How can I make field1 required and field2 optional in this nested object?
As you can see, this is my html client, and field1 and field2 are both optional, I want field1 to be required. Thanks in advance!

Realted question on stackoverflow:
https://stackoverflow.com/questions/54803837/openapi-required-property-in-nested-objects-not-working

**Comment by mbianchidev** [comment]
`openapi: 3.0.0
info:
    title: GoSign API
    description: GoSign API specification
    version: 4.11.0
servers:
  - url: https://webappcl.gosign.digital/gosign
  - url: https://webapp.gosign.digital/gosign

paths:
  /secure/oauth/services/v2/Nested:
    post:
      summary: Try nested
      description: Used to post Nested obj
      requestBody:
        required: true
        content:
          application/json:
            schema:
                type: object 
                required:
                - id
                - nestedobj
                properties:
                    id:
                      type: integer
                      description: id of nested obj
                    nestedobj:
                      $ref: '#/components/schemas/nestedobj'
      responses:
        '200':
          description: Nested object OK

components:
  schemas:
    element:
      type: object
      required:
      - fieldArray1
      properties:
        fieldArray1:
          type: string
          description: field array
        fieldArray2:
          type: number
    nestedobj:
      type: object
      required:
      - field1
      description: nested object
      properties:
        field1:
          $ref: '#/components/schemas/woah'
        field2:
          type: string
    woah:
      type: object
      required:
      - woahthis
      description: woah this
      properties:
        field3:
          type: array
          items:
            $ref: '#/components/schemas/element'
        woahthis:
          type: number
          description: numeber woah this`

Solved! 
I used components schemas and it's working fine, is this an issue? 
I think it should work both in this way and the way I tried before.

**Comment by mbianchidev** [comment]
Solved!
I used components schemas and it's working fine, is this an issue?
I think it should work both in this way and the way I tried before. 

In this .txt attachment i wrote my solution (couldn't upload .yaml)
[example.txt](https://github.com/swagger-api/swagger-editor/files/2889493/example.txt)

**Comment by shockey** [comment]
Hi @mbianchidev, the generated HTML client you're seeing is coming from [Swagger Codegen](https://github.com/swagger-api/swagger-codegen)! 

The components reference vs direct inclusion behavior definitely seems strange, consider opening a bug over at Codegen. Thanks!

**Comment by mbianchidev** [comment]
Thank you @shockey I opened the issue in the correct project. Thanks for checking my issue 👍
