### ISSUE TITLE
Add support for dynamic context path

### ISSUE THREAD

**Issue by galvo** [swagger-api/swagger-editor#1956]
### Content & configuration
I would like to be able to dynamically change the context path so that when the swagger editor is deployed via docker on environments such as Kubernetes that it can be made available at a path other than "/". Is there currently a way to specify an environmental variable to define the base path?

**Comment by shockey** [comment]
@galvo, there's currently no way to do this within the Swagger UI container itself.

If you need this functionality, the best practice is to sit a request router in front of Swagger UI's container and rewrite URL paths into the container.

**Comment by mrsegen** [comment]
@shockey Would you be able to point in the direction of an example of such a request router?

**Comment by mrsegen** [comment]
The Swagger UI repo has an approach which seemingly just involves lines to [docker/run.sh](https://github.com/swagger-api/swagger-ui/blob/master/docker/run.sh#L4) and [Dockerfile](github.com/swagger-api/swagger-ui/blob/master/Dockerfile). Not sure yet whether it would involve anything additional for Nginx.

I _may_ get to put out a PR for this.

**Comment by mrsegen** [comment]
As is done with Swagger UI, the above PR now allows specification of a BASE_URL. This allows the editor to be served at a different location (e.g. `/swagger-editor`), which can enable this to be served at a single URL routed via a Kubernetes Ingress object.
