### ISSUE TITLE
Potential bug in Resolver introduced in v3.6.24

### ISSUE THREAD

**Issue by jdegre** [swagger-api/swagger-editor#1957]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Tested with Firefox and Chrome
 - Version: 65.0.2 (Firefox) and 72.0.3626.119 (Chrome)
 - Method of installation: Online editor at https://editor.swagger.io
 - Swagger-Editor version: 3.6.24 (was working fine in previous versions)
 - Swagger/OpenAPI version: OpenAPI 3.0.0

Example Swagger/OpenAPI definition:
To reproduce, I have created 3 tiny YAML test files in this repo:
https://github.com/jdegre/5GC_APIs/tree/master/test
(not sure if I should paste the YAML files' content here.... I thought it is easier just to head to the test repo)

### Describe the bug you're encountering
When you expand the POST method, the resolver shows an error, apparently failing to resolve object type "B2", but the window showing the request body ("Example Value") shows that the type was correctly resolved.

### To reproduce...

1. Go to: https://github.com/jdegre/5GC_APIs/tree/master/test
2. Load file test.yaml in the online Swagger Editor, by following the "Test" link in README.md
3. Expand the POST method in the right panel
4. See error "Resolver error at paths./foo.post.responses.201.content.application/json.schema.properties.p1.properties.p1.properties.p1.$ref
Could not resolve reference: Could not resolve pointer: /components/schemas/B2 does not exist in document"

### Expected behavior
No errors should appear since the types are correctly cross-referenced. I have tested this with editor versions 3.6.[20-24], and the problem started in latest version (24)

**Comment by shockey** [comment]
Interesting.

We don't actually change any resolver behavior in v3.6.24, only the way that resolver errors are surfaced.

Indeed, in v3.6.23 this same error is being reported by the resolver, but is being wiped from Swagger UI's error state a few milliseconds after being added:

![](http://g.recordit.co/Aie2aQxaa7.gif)

The only change in v3.6.24 is that the error sticks around and is displayed.

---

I'm going to prioritize this, at least to get eyes on it - this isn't the first time we've looked at nested document resolution problems, but perhaps the additional visibility into the problem that the error message changes give will help triage this.

**Comment by jdegre** [comment]
@shockey, could you please update us on the status of this issue?
seeing it was closed a few days ago, I was hoping the issue to be solved in releases 3.6.25, 26, 27... but all these versions still have the issue.
