### ISSUE TITLE
Unable to render example on response object

### ISSUE THREAD

**Issue by topizio** [swagger-api/swagger-editor#1965]
Hi guys,

I think there's something wrong in the way the examples on response are handled.

### Q&A
 - OS: macOS
 - Browser: chrome
   - Version: 72.0.3626.96
 - Browser: Firefox
   - Version: 66.0
 - Method of installation: npm
 - Swagger-Editor version: 3.6.25
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Given this definition:
```yaml
openapi: 3.0.0
info:
  title: title
  description: description
  version: '0.1'
paths:
  /get:
    summary: summary
    get:
      responses:
        '200':
          description: ref following Open API spec (IGNORED)
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
              examples:
                confirmation-success:
                  $ref: '#/components/examples/confirmation-success'
        '201':
          description: in line following Open API spec (IGNORED)
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
              examples:
                confirmation-success:
                  value: {
                    "myProp": "myValue"
                  }
        '400':
          description: ref having `example` without S (WRONGLY RENDERED)
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
              example:
                confirmation-success:
                  $ref: '#/components/examples/confirmation-success'
        '401':
          description: in line having `example` without S (WRONGLY RENDERED)
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
              example:
                confirmation-success:
                  summary: summary
                  value: {
                    "myProp": "myValue"
                  }
        '402':
          description: in line having `example` without S and no `summary/value` (WRONGLY RENDERED)
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
              example:
                confirmation-success: {
                    "myProp": "myValue"
                }
        '403':
          description: ref having `example` without S and no `example name` (WRONGLY RENDERED)
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
              example:
                $ref: '#/components/examples/confirmation-success'
        '500':
          description: in line having `example` without S and no `example name` (CORRECTLY RENDERED)
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
              example: {
                    "myProp": "myValue"
              }
components:
  schemas:
    SuccessResponse:
      properties:
        myProp:
          type: string
  examples:
    confirmation-success:
      summary: summary
      value: {
        "myProp": "myValue"
      }
```

### To reproduce...

1. Copy/Paste the YAML in the editor
1. Verify the rendered response examples

### Expected behavior
Following specifications, I would expect to correctly  see example for error codes 200 and 201

### Actual behavior
Only error 500 is correctly rendered, even if the way I defined it should be not correct, or at least that's my understanding

### Additional context or thoughts
Examples are not displayed from https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/api-with-examples.yaml. This one use the same syntax of 20x examples

but they are displayed using https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/uspto.yaml. This last one use the same syntax as error 500.

I will open a ticket on https://github.com/OAI/OpenAPI-Specification as well

**Comment by hkosova** [comment]
Support for multiple `examples` is not available yet, this is tracked in https://github.com/swagger-api/swagger-ui/issues/2651.

Singular `example` uses an inline example value (rather than an [Example object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#exampleObject)) that will be rendered as is. `example` does not support`$ref`; the `$ref` key here will be treated as a literal property named `$ref`.

In your spec, 200, 201 and 500 are the correct definitions of examples. 200 and 201 examples will be displayed properly after https://github.com/swagger-api/swagger-ui/issues/2651 is implemented. 4xx examples are technically also valid but they will be rendered as-is, which is different from what you're trying to achieve.

**Comment by topizio** [comment]
Hi @hkosova, thanks for your answer. Then we'll stick to 200 and 201 while waiting that https://github.com/swagger-api/swagger-ui/issues/2651 will be covered.

Have a great day
