### ISSUE TITLE
Object recursion not rendered in SwaggerEditor

### ISSUE THREAD

**Issue by jonwakingup** [swagger-api/swagger-editor#1973]
### Q&A 
 - OS:Windows 10
 - Browser: Firefox
 - Method of installation: Run from web
 - Version: Version used in SwaggerHub at 02/04/2019
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
Open the attached yaml in Swagger Editor
[jon-stewart-Recursion-Issue-1.0.0-oas3-swagger.yaml.txt](https://github.com/swagger-api/swagger-editor/files/3033745/jon-stewart-Recursion-Issue-1.0.0-oas3-swagger.yaml.txt)

### Describe the bug you're encountering
The TreeNode object has a children array that references further TreeNode objects.  

The schema does not mention the data type of the children elements, as per the attached screenshot.
![TreeNode](https://user-images.githubusercontent.com/13063390/55400539-6d3c7700-554e-11e9-9c03-325f23d9b1ab.PNG)

I think it should say that the data type of the child elements is TreeNode.  

The HTML documentation handles this in a nice way - it states that the data type is TreeNode (and provides a link back to the beginning of the object, which I wouldn't expect to the editor to do):

Extract from HTML documentation:
**TreeNode**

  id
  _Integer_ The Id of this tree node 

  children (optional)
  _array[[TreeNode]](.)]_ Array of child objects

### To reproduce...

1. Load the yaml in Swagger editor
2. Open the schema for TreeNode

### Expected behavior
Expect to see the data type of the elements of the children array in the Schema

**Comment by hkosova** [comment]
This issue is tracked here: https://github.com/swagger-api/swagger-ui/issues/3325

**Comment by jonwakingup** [comment]
hkosova - thank you for making the link to the underlying issue.
