### ISSUE TITLE
Build image from Dockerfile and run container (version 2.X)

### ISSUE THREAD

**Issue by sergio-alifano** [swagger-api/swagger-editor#1974]
- Swagger-Editor version: [2.X]
### How can we help?
I'm trying to run version 2.X inside a container. I'm using the Dockerfile in the repo:
```
FROM    mhart/alpine-node
RUN     npm install -g http-server
WORKDIR /editor
ADD     ./ /editor
# The default port of the application
EXPOSE  8080
CMD ["http-server", "--cors", "-p8080", "/editor"]
```

I run the container and the ouput is 
```
Starting up http-server, serving /editor
Available on:
  http://127.0.0.1:8080
  http://172.17.0.2:8080
```
but the page doesn't show anything
```
This site can’t be reached
```

is there something wrong with the Dockerfile or am I missing something?

Thanks.

**Comment by shockey** [comment]
@sergio-alifano, [`EXPOSE`](https://docs.docker.com/engine/reference/builder/#expose) only indicates to Docker that something listens on container port 8080. In order to map container port 8080 to your host machine, you'll need to use docker run's [`-p [hostPort:containerPort]` flag](https://docs.docker.com/v17.09/engine/reference/commandline/run/#publish-or-expose-port--p-expose), like so:

```
➜  docker run -p 3000:8080 swaggerapi/swagger-editor:v2.10.5
Starting up http-server, serving /editor
Available on:
  http://127.0.0.1:8080
  http://172.17.0.2:8080
Hit CTRL-C to stop the server

```

This will make Swagger Editor available on your host machine's port 3000:

```
➜  curl http://127.0.0.1:3000
<!doctype html>
  <head>
    <meta charset="utf-8">
    <title>Swagger Editor</title>
    <meta name="description" content="Swagger Editor">
    <meta name="viewport" content="width=device-width">
    <link rel="icon" type="image/png" href="./images/favicon-32x32.png" sizes="32x32" />
    <link rel="icon" type="image/png" href="./images/favicon-16x16.png" sizes="16x16" />
    <link rel="stylesheet" href="dist/styles.css">
    <link rel="stylesheet" href="styles/branding.css">
  </head>
  <body>
    <div class="total-wrapper" ui-view></div>
    <script src="dist/bundle.js"></script>
    <script src="scripts/branding.js"></script>
</body>
</html>
```

I hope this helps!

**Comment by sergio-alifano** [comment]
@shockey, thanks for checking on this. I did map port 8080 to my hosting machine but I didn't realize that actually the problem was different, i.e. the bundle.js file was not found. I had to update the package.json build from "--production" to "--development" in order to generate that file. 
Everything is working fine now!
