### ISSUE TITLE
Allow resizing plaintext vs HTML pane ratio

### ISSUE THREAD

**Issue by mcandre** [swagger-api/swagger-editor#1981]
Please add a slider so that users can elect to see more of the plaintext, or more of the HTML view, as desired. This really helps on small screens.

**Comment by hkosova** [comment]
Related: #1290

**Comment by shockey** [comment]
The bones for this are in the codebase, left over from the initial development of Swagger Editor 3... we just need to polish it a bit:

https://github.com/swagger-api/swagger-editor/blob/ab67ff86a4b5d5925bc59524b2b81506cb55e820/src/plugins/split-pane-mode/components/split-pane-mode.jsx#L10

**Comment by hkosova** [comment]
Fixed by https://github.com/swagger-api/swagger-editor/pull/1916.
