### ISSUE TITLE
Could not resolve reference: Failed to fetch # How to resolve it?

### ISSUE THREAD

**Issue by unipark00** [swagger-api/swagger-editor#1986]
I'm involved in developing API services on 5G core services.
I referenced the specification documents provided by 3gpp.

I used online editor -- https://editor.swagger.io/

When I loaded the original one, #ref didn't not seem to be found. (see line 29)
![20190416_185310](https://user-images.githubusercontent.com/15682577/56200695-38660f00-607a-11e9-9f90-b30db8de7b4e.png)

There may be other workarounds, just simply, I modified the #ref using the accessible URL.

$ref: 'https://www.3gpp.org/ftp/Specs/archive/OpenAPI/Rel-15/TS29510_Nnrf_NFManagement.yaml#/components/schemas/NFType'

As a reulst, error message was changed, but failed to solve it clearly.
![20190416_185539](https://user-images.githubusercontent.com/15682577/56200942-c80bbd80-607a-11e9-8edb-d0e94f79cb8c.png)

When I reviewed referenced yaml, there seemed no wrong points.
I couldn't why it didn't resolve the #ref.

Could you reivew my problem?

**Comment by jdegre** [comment]
you need to invoke the swagger editor with the "url" query parameter, and pass the raw YAML file in your repo as input. Like this:

https://editor.swagger.io/?url=https://raw.githubusercontent.com/unipark00/nf_services/master/TS29510_Nnrf_NFManagement.yaml

**Comment by unipark00** [comment]
@jdegre Thanks for help ... By using url as parameter, my issue was cleared.
And, I noticed that 3gpp url can't be accessed by CORS issue.

Errors
Hide
 
Fetch errorFailed to fetch https://www.3gpp.org/ftp/Specs/archive/OpenAPI/Rel-15/TS29510_Nnrf_NFDiscovery.yaml
Fetch errorPossible cross-origin (CORS) issue? The URL origin (https://www.3gpp.org) does not match the page (https://petstore.swagger.io). Check the server returns the correct 'Access-Control-Allow-*' headers.

**Comment by Abbey-12** [comment]
Hii,
I'm currently working on developing API services for 5G core services as well, and I'm experiencing a similar issue. It would be great to hear if someone has successfully resolved this problem before. Any assistance or support you can provide would be greatly appreciated.
