### ISSUE TITLE
Modeling generic hashmap of String to a object in swagger 2.0

### ISSUE THREAD

**Issue by venkataratnamteki** [swagger-api/swagger-editor#1993]
0

I am using swagger to generate DTOs in my go client, for existing REST APIs. Request body DTO has a generic hashmap such as:

class MyConfig {
   Map<String, Object> config;
}
Lets say the config as 2 possible keys, value is a different object for each key.

key1 = "_key1", and value1 = "type A"
key2 = "_key2", and value2 = "type B"
I used swagger inspector extension and generated a swagger spec(OAS 2.0) for my API. The yaml file generated is like below:

MyConfig:
    properties:
      _key1:
        $ref: '#/definitions/_A'
      _key2:
        $ref: '#/definitions/_B'
Basically this corresponds to a class of type MyConfig with 2 fields as "key1" and "key2". I dont think this would work if my DTO on server side goes through any change in future, for example, support another key and value in the map.

This doesn't really map to my actual input, which is hashmap.

To me, it looks like , i should model as shown below:

MyConfig:
    properties:
      config:
        type: object
        additionalProperties:
           type: string
           $ref: {} -->(assuming {} represents a generic object)
Is there a support for mentioning generic object in swagger spec? Not sure, which approach is actually better/flexible.

Thanks!
 - OS: macOS
 - Browser: chrome
 - Version: 74
 - Swagger-Editor version: [e.g. 3.10.0]
 - Swagger/OpenAPI version:Swagger 2.0

### How can we help?
How can I model such object which contains a map of string key to any object class?

**Comment by shamingrudeengineers** [comment]
I'm just going to leave this here. https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md

**Comment by hkosova** [comment]
@venkataratnamteki You are almost there, you just need to change the `additionalProperties` type from `type: string` to `type: object`. An object without explicitly defined `properties` means "arbitrary object".
```
MyConfig:
  type: object
  properties:
    config:
      type: object
      additionalProperties:
        type: object
```
