### ISSUE TITLE
can a.yaml use b.yaml definitions？

### ISSUE THREAD

**Issue by kingcr7** [swagger-api/swagger-editor#1994]
My Swagger/OpenAPI version: Swagger 2.0
my question:a.yaml and b.yaml are in same directory,  how can i use objectB in a.yaml?

a.yaml 
  definitions:
    objectA

b.yaml 
  definitions:
    objectB

**Comment by hkosova** [comment]
`$ref` can point to other files, like so:

```yaml
$ref: './b.yaml#/definitions/objectB'
```

However, at this time Swagger Editor does not support resolving relative references. This is tracked #1409.
