### ISSUE TITLE
Please create a MicroProfile option under the "Generate Server" menu

### ISSUE THREAD

**Issue by cealsair** [swagger-api/swagger-editor#2000]
### Content & configuration

This is a new feature request.

### Is your feature request related to a problem?
No, my request is not related to a problem

### Describe the solution you'd like
Under the "Generate Server" menu, I'd like to see an option for generating a MicroProfile server.

### Describe alternatives you've considered
There's no alternative to this.

### Additional context
Thank you.

**Comment by shockey** [comment]
Hi @cealsair, the Generate Server menu content comes from Swagger Codegen, please open an issue there 😄 https://github.com/swagger-api/swagger-codegen
