### ISSUE TITLE
Travis integration for this repo is broken

### ISSUE THREAD

**Issue by kikmak42** [swagger-api/swagger-editor#2003]
The travis.yml file is missing and the last build on travis was 9 months ago.

![image](https://user-images.githubusercontent.com/645401/59580728-eda35a80-90ef-11e9-8efe-a9af96634988.png)

**Comment by shockey** [comment]
This is intentional 😄 we switched over to a Jenkins instance last year, which builds and provides GitHub status checks for pull requests and commits to master:

* http://jenkins.swagger.io/job/oss-swagger-editor-pr/
* http://jenkins.swagger.io/job/oss-swagger-editor-master/

**Comment by kikmak42** [comment]
@shockey ok, then the ReadMe badge to Travis should be removed and updated to the Jenkins one
