### ISSUE TITLE
enum : swagger editor automatically adds single quotes to enum string value "Y"

### ISSUE THREAD

**Issue by KurtCoppens** [swagger-api/swagger-editor#2006]
An example :
        - name: periodUnit
          in: query
          description: The requested rate period unit
          required: true
          type: string
          enum:
            - Y
            - M
            - D
            - W
Swagger editor converts Y to 'Y' after saving the file : 
        - name: periodUnit
          in: query
          description: The requested rate period unit
          required: true
          type: string
          enum:
            - **'Y'**
            - M
            - D
            - W

**Comment by hkosova** [comment]
Some YAML parsers treat the strings `y Y n N yes no on off` (and some others) as [boolean values](https://yaml.org/type/bool.html). Adding quotes around `Y` enforces the string type and will help avoid parsing issues in other OpenAPI-related tools.

**Comment by KurtCoppens** [comment]
Dear Helena,

Thank you for your clear answer.

Kind regards,

Kurt Coppens  |  dev engineer
API @ Scale squad  |  IT Omnichannel Foundation |  BNP Paribas Fortis SA/NV
Teleworking on Friday
T +32 (0)2 228 05 61 | kurt.coppens@bnpparibasfortis.com<mailto:kurt.coppens@bnpparibasfortis.com>
Kreupelenstraat / Rue des boiteux 10, MARAIS building 1st floor, Summer area, 1MA1E, 1000 Brussels

**Comment by KurtCoppens** [comment]
Dear Helena,
Thank you for your clear answer.
Kurt

**Comment by shockey** [comment]
this sounds resolved -- closing!
