### ISSUE TITLE
I am getting 'Parser error end of the stream or a document separator is expected Jump to line 4 ' error .

### ISSUE THREAD

**Issue by ankitbhu16** [swagger-api/swagger-editor#2010]
This is system status API
    Call this api passing period and get back its features
    --
 tags:
      - system status API
      parameters:
        - name: start_time
        in: query
        type: string
        format: date-time
        required: false
        description: convert the time into epoch format
        - name: end_time
        in: query
        format: date-time
        type: string
        description: convert the time into epoch format
        - name: period
        in: query
        description: observation period
        type: string
        default: 'ONE-WEEK'
      responses:
        500:
          description: There is an internal API-server problem
        200:
          description: successful operation
        204:
          description: data not available
        400:
          description: bad request
        404:
          description: address service is not available

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!
