### ISSUE TITLE
 require.extensions is not supported by webpack. Use a loader instead.

### ISSUE THREAD

**Issue by susie886** [swagger-api/swagger-editor#2019]
WARNING in ./~/yaml-js/lib/yaml.js
    require.extensions is not supported by webpack. Use a loader instead.
    
    WARNING in ./~/yaml-js/lib/yaml.js
    require.extensions is not supported by webpack. Use a loader instead.
    
    WARNING in ./~/yaml-js/lib/yaml.js
    require.extensions is not supported by webpack. Use a loader instead.
    
    WARNING in ./~/yaml-js/lib/yaml.js
    Critical dependencies:
    256:40-47 require function is used in a way in which dependencies cannot be statically extracted
     @ ./~/yaml-js/lib/yaml.js 256:40-47

**Comment by SnirShechter** [comment]
Same here.

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!

**Comment by ajitkayastha** [comment]
import React, { Component } from "react";
import SwaggerEditor, { plugins } from "swagger-editor";
import "swagger-editor/dist/swagger-editor.css";
export class SwaggerDoc extends Component {
  componentDidMount() {
    window.editor = SwaggerEditor({
      dom_id: "#swagger-editor",
      layout: "EditorLayout",
      plugins: Object.values(plugins),
      oas3GeneratorUrl: "../../docs/openapi.json",
    });
  }
  render() {
    return <div id="swagger-editor"></div>;
  }
}

export default SwaggerDoc;
---------
---------
Compiled with warnings.

./node_modules/yaml-js/lib/yaml.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/yaml-js/lib/yaml.js
require.extensions is not supported by webpack. Use a loader instead.

./node_modules/yaml-js/lib/yaml.js
require.extensions is not supported by webpack. Use a loader instead.

./node_modules/yaml-js/lib/yaml.js
require.extensions is not supported by webpack. Use a loader instead.

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
