### ISSUE TITLE
swagger-tools ui udpates are not creating controlloers

### ISSUE THREAD

**Issue by jaasritha** [swagger-api/swagger-editor#2023]
Hi There, 

Sorry for being silly, I'm just learning this node js with swagger. I have installed swagger-tools. 

swagger project edit

opens up swagger UI in browser. I'm updating/adding new APIs. Once I see the message on the top right corner that all changes are saved then I close it and 

swagger project start

Now here swagger.yaml file is updated with newly added APIs but there are no controller files created as part of my newly added APIs. 

if we use editor.swagger.io then there is option to generate node-js server project which creates all 
required controller files etc. 

If I fallow swagger-tools with node js its not working as expected. 

Below are the version details: 
  "swagger-tools": "0.10.4"

**Comment by hkosova** [comment]
This repository is for Swagger Editor, not for swagger-tools. Please open an issue in the proper repository, either
https://github.com/swagger-api/swagger-node
or
https://github.com/apigee-127/swagger-tools
