### ISSUE TITLE
Basic Authentication With Swagger Authorization header is not sent with the request

### ISSUE THREAD

**Issue by dheerajthodupunoori** [swagger-api/swagger-editor#2027]
### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-Editor version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-Editor configuration options:
```js
SwaggerEditor({
  // your config options here
})
```

```
?yourQueryStringConfig
```

**Comment by dheerajthodupunoori** [comment]
services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info { Title = "Swagger Demo", Version = "v1" });

                c.AddSecurityDefinition("Basic", new BasicAuthScheme()
                {
                    Description = "Basic Authentication to user this Service.",
                    Type = "basic"
                });
                c.OperationFilter<SecurityRequirementsOperationFilter>();

                c.DocumentFilter<SwaggerSecurityRequirementsDocumentFilter>();

                //c.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>> { { "basic", new string[] { } } });
            });




The above is the configuration for my swagger

**Comment by dheerajthodupunoori** [comment]
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }
            app.UseAuthentication();
            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "Swagger Demo");
                c.RoutePrefix = string.Empty;
            });
            app.UseHttpsRedirection();
            app.UseMvc();
        }

**Comment by dheerajthodupunoori** [comment]
but when i click on authorize after entering the credentials , the authorization  key is not found in  request headers

**Comment by hkosova** [comment]
The issue is with your Swashbuckle configuration, not Swagger UI. Please open an issue in the Swashbuckle repository to get help with Swashbuckle configuration:
https://github.com/domaindrivendev/Swashbuckle
https://github.com/domaindrivendev/Swashbuckle.AspNetCore

From the looks of it, you probably need to uncomment the `c.AddSecurityRequirement` line.
