### ISSUE TITLE
Semantic errors with using consumes property and multipart/form-data

### ISSUE THREAD

**Issue by JakeRoper4** [swagger-api/swagger-editor#2042]
Hello all,

I've been creating some Web API's recently that uses the `multipart/form-data` data type, and haved specc'ed these within OpenAPI 3 before. However, I'm trying to spec out the same type of endpoint within a Swagger 2.0 version of a spec, and I seem to be getting some errors when trying to write it.

![image](https://user-images.githubusercontent.com/54897068/64257895-1e8c7200-cf1e-11e9-8ff8-563ae14966f2.png)

 - OS: Windows
 - Browser: Chrome
 - Version: 76
 - Swagger-Editor version: Whatever version is currently live on `editor.swagger.io`
 - Swagger/OpenAPI version: Swagger 2.0

I've laid out the part of the spec that I was writing into it's own, so I can keep it separate. This snippet is displayed below. As far as I'm aware, I'm satisfying any conditions that it requires of me, with having a consumes property within one of my operations which is an array.

```
swagger: '2.0'
info:
  title: Service
  description: Description
  version: 1.0.0
host: Api
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  '/a/{aId}/b/{bId}/c':
    post:
      consumes:
        - multipart/form-data
      description: Gets the results of user for a lesson with a given id.
      responses:
        '200':
          description: '200'
        '400':
          description: '400'
        '401':
          description: '401'
        '403':
          description: '403'
        '404':
          description: '404'
    parameters:
      - name: Origin
        in: header
        description: Origin
        required: true
        type: string
      - name: Authorization
        in: header
        description: Bearer token
        required: true
        type: string
      - name: aId
        in: path
        description: A Id
        required: true
        type: string
        format: guid
      - name: bId
        in: path
        description: B Id
        required: true
        type: string
        format: guid
      - name: fileContent
        in: formData
        description: The byte array of the file to be uploaded
        required: true
        type: file
      - name: Date
        in: formData
        description: Date of the awarded c
        required: true
        type: string
        format: date-time
```

**Comment by webron** [comment]
Looks like it's an indentation problem (YAML is sensitive like that).

Right now, your parameters are defined under the path and not the operation, whereas your `consumes` is defined under the operation. You can either move the `consumes` to the path level or move the parameters to the operation level, depending on what makes sense for your use case.

**Comment by JakeRoper4** [comment]
> Looks like it's an indentation problem (YAML is sensitive like that).
> 
> Right now, your parameters are defined under the path and not the operation, whereas your `consumes` is defined under the operation. You can either move the `consumes` to the path level or move the parameters to the operation level, depending on what makes sense for your use case.

Thanks @webron for the quick response. I have now made changes to my spec in relation to your suggestions, and the errors have now disappeared. Thanks once again :)
