### ISSUE TITLE
Query parameters in URL

### ISSUE THREAD

**Issue by kritiagrawal09** [swagger-api/swagger-editor#2047]
Hi Team

I see in documentation that query parameters in Swagger editor is not accepted in the URL. We have a requirement where the payload differs based on the query parameter. Please suggest how do we handle such cases.

**Comment by hkosova** [comment]
@kritiagrawal09 Here are the corresponding feature requests in the OpenAPI Specification repository:
[Proposal: Querystring in Path Specification](https://github.com/OAI/OpenAPI-Specification/issues/164)
[Accommodate legacy APIs by allowing query parameters in the path](https://github.com/OAI/OpenAPI-Specification/issues/123)

**Comment by shockey** [comment]
Closing; this sounds like a spec issue, not a tooling one 🙂
