### ISSUE TITLE
Semantic validator messaging for sibling keys alongside `$ref` should be better

### ISSUE THREAD

**Issue by shockey** [swagger-api/swagger-editor#2048]
##### OpenAPI 3.0: 
```yaml
openapi: 3.0.0
components:
  schemas:
    A:
      type: object
    B:
      $ref: "#/components/schemas/A"
      description: "Hello there"
```

##### Swagger 2.0

```yaml
swagger: "2.0"
definitions:
  A:
    type: object
  B:
    $ref: "#/definitions/A"
    description: "Hello there"
```

### To reproduce...

1. Paste one on the example documents into the Editor
2. Observe the warnings that appear in the Editor's left-hand gutter:

> Sibling values are not allowed alongside $ref

### Expected behavior

The following message:

> Sibling values alongside $refs are ignored. 
> To add properties to a $ref, wrap the $ref into allOf, or move the extra properties into the referenced definition (if applicable).

### Additional context or thoughts

The validator's source is here: 

https://github.com/swagger-api/swagger-editor/blob/550b9263f44e11e6e15f4a88d599f172a296bc2a/src/plugins/validate-semantic/validators/2and3/refs.js#L20

There are also some corresponding tests that will need to be updated.

(This item was created from @hkosova's "Editor Validation Ideas" document.)

**Comment by hkosova** [comment]
Implemented in Swagger Editor 3.7.0+. 🎉
