### ISSUE TITLE
Path parameter validation should be smart about improper casing

### ISSUE THREAD

**Issue by shockey** [swagger-api/swagger-editor#2049]
##### OpenAPI 3.0: 
```yaml
openapi: 3.0.1
paths:
  /{myParam}:
    get:
      parameters:
      - name: myparam
        in: path
        required: true
        schema: 
          type: string
      responses:
        200:
          description: OK
```

##### Swagger 2.0

```yaml
swagger: "2.0"
paths:
  /{myParam}:
    get:
      parameters:
      - name: myparam
        in: path
        required: true
        type: string
      responses:
        200:
          description: OK
```

### To reproduce...

1. Paste one on the example documents into the Editor
2. Observe the warnings that appear in the Editor's error readout

> Declared path parameter "myParam" needs to be defined as a path parameter at either the path or operation level

### Expected behavior

The existing message is fine for most cases, but if the only difference between the parameter fragment in the URL and the parameter that exists is a difference is casing, we should generate a more intelligent error:

> Parameter names are case-sensitive. The parameter named Petid does not match the case used in the path /pets/{petId}.

JavaScript's `String.prototype.toLowerCase`, e.g. `"petId".toLowerCase() === "petid".toLowerCase()`, is a cheap way to figure out if casing is the only difference between two strings.

### Additional context or thoughts

This validator's source is here: 

https://github.com/swagger-api/swagger-editor/blob/550b9263f44e11e6e15f4a88d599f172a296bc2a/src/plugins/validate-semantic/validators/2and3/paths.js#L50

We'll need new tests for this new functionality. There's an existing suite within this `describe` block:

https://github.com/swagger-api/swagger-editor/blob/550b9263f44e11e6e15f4a88d599f172a296bc2a/test/unit/plugins/validate-semantic/2and3/paths.js#L79

(This item was created from @hkosova's "Editor Validation Ideas" document.)

**Comment by hkosova** [comment]
Implemented in Swagger Editor 3.7.0. 🎉
