### ISSUE TITLE
Swagger on Docker runs Swagger UI instead of Swagger editor

### ISSUE THREAD

**Issue by Matimath** [swagger-api/swagger-editor#2050]
I run swagger editor via docker. Unfortunately after opening localhost on my browser the result is not like the online swagger editor. Instead I get Petstore demo. How to "open" new file and turn on editing options (like in online editor)?
I have found some answers on the internet on how can I put my custom openAPI there but not how to turn on the editor.

**Comment by webron** [comment]
Are you sure you're running the Swagger Editor image and not the Swagger UI one?

**Comment by Matimath** [comment]
It worked when I pulled from docker hub instead of docker build from the repo.
