### ISSUE TITLE
Generate to PDF or DOCX file

### ISSUE THREAD

**Issue by smile-h** [swagger-api/swagger-editor#2053]
# Briefly what I want
I want to export the generated documentation to a PDF or docx file.

# The long story WHY I want it
<details><summary>SHOW</summary>
<p>
This question was created by me because I was faced with an interesting situation in the current project. We, I mean my team, generate documentation using swagger, more precisely Springfox. Our analysts and clients want to generate a pdf or doc file by API with a clear description. I found an open source project [swagger2markup](https://github.com/Swagger2Markup/swagger2markup), where I can do it without any problems, BUT it causes me some discomfort. You know, it looks wierd when the API was changed, and your analyst wants to update the documentation for the client, and you should throw away the current task and do something with it.

My first solution: I generated a PDF when the analyst asked me. This decision quickly tired me.

My second solution: I launched a small server with a page where you can generate pdf yourself. Already better. But I still need to update the json API file.
</p>
</details>

# Solution
I will use:

- swagger-editor
- swagger2markup (I do not want to develop new functionality for creating a PDF file. I would like to get this from swagger2markup)

I guess, it will look something like this:

![Example](https://raw.githubusercontent.com/smile-h/bit-pit/master/Screen%20Shot%202019-09-29%20at%2012.03.33%20am.png)

I think it would be nice to see something like export to a pdf or doc file in the swagger editor. I really don't know if this will be popular or necessary ... I hope you tell me that.
I will be to hear other ideas or suggestions and I will be very grateful if I did it myself.

P.S. I appologise for my English =)

**Comment by webron** [comment]
Hi @smile-h - thanks for the ticket. I imagine you're asking if this functionality makes sense, and whether we'd like it to be part of the core Swagger Editor implementation.

Generally speaking, sure, the functionality makes sense if that's what you need, although it should serve you, not your end users. That said, it's not a functionality we see as part of the Editor. It's hard to encourage the use of PDFs for API documentation when there are better alternatives out there, and your suggestion would also make the editor larger by adding additional dependencies.

This could be a good candidate for a plugin functionality though that people could add to their own editor if they want to.

**Comment by smile-h** [comment]
Hi @webron . Thanks for the answer! I completely agree with you.
Then I am going to create a plugin for swagger-editor that will generate a PDF file or a file with some other extensions.

**Comment by shockey** [comment]
Closing as resolved — @smile-h, keep us posted on how this PDF plugin goes!
