### ISSUE TITLE
Should the npm-run-all and http-server devDependencies be moved to dependencies?

### ISSUE THREAD

**Issue by voodoomsr** [swagger-api/swagger-editor#2056]
Hi all, 
I just cloned the repo, i'm only interested in creating the specification of an API I'm writing, so I removed the devDependencies after wasting several minutes to solve peerDependencies conflicts they originated.

What I find out is that to execute the editor at least you require two devDependencies:
  "npm-run-all": "^4.1.3",
  "http-server": "^0.11.1"
Probably different versions would also work. They are used in the start and serve-static scripts.

Shouldn't those dependencies be moved to the dependencies group in package.json?
I'm just starting with node so maybe I'm confusing the usage of these dependencies groups.

**Comment by shockey** [comment]
Hi @voodoomsr! The way we have it set up now is the convention for JavaScript modules: production dependencies are the ones you need if you're consuming [the `swagger-editor` module](https://www.npmjs.com/package/swagger-editor) that this repository creates, and development dependencies are the ones you need if you're working with a local copy of the Swagger Editor repository.

Here are some docs about this: [Specifying dependencies and devDependencies in a `package.json` file (npmjs.com)](https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file)

Hope this helps!
