### ISSUE TITLE
Constraints not honored for the example requests

### ISSUE THREAD

**Issue by MeFisto94** [swagger-api/swagger-editor#2058]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Firefox
 - Version: 69
 - Method of installation: editor.swagger.io
 - Swagger-Editor version: Whatever is live
 - Swagger/OpenAPI version: see above

### Content & configuration
```json
"requestBody": {
 "content": {
  "application/json": {
    "schema": {
      "type": "object",
        "properties": {
          "players": {
            "type": "integer",
            "minimum": 1,
            "maximum": 10
           },
           "required": [
             "players"
            ]
          }
        }
      },
   }
}
```

### Describe the bug you're encountering
In the API Examples which are recommended by Swagger, minimum/maximum aren't honored but "0" is always used instead

### To reproduce...

1. Import any definition containing constraints
2. See the examples being wrong.

### Expected behavior
The values being either random between min and max or simply just the minimum value.

### Screenshots
![grafik](https://user-images.githubusercontent.com/12577813/66790266-56101600-eeef-11e9-80b6-14cda4752c4e.png)
![grafik](https://user-images.githubusercontent.com/12577813/66790274-60321480-eeef-11e9-8bda-c6319365e0ca.png)

### Additional context or thoughts
I didn't test if this only happens for the non-exclusive variants and/or only when using Open API 3.0 instead of Swagger 2 (I hope this issue still is relevant as the project doesn't complain upon loading OAI3 files)

**Comment by hkosova** [comment]
Thanks for the report! This issue is tracked in https://github.com/swagger-api/swagger-ui/issues/5216. Closing as a duplicate.
