### ISSUE TITLE
Have a fold/unfold all button for the paths

### ISSUE THREAD

**Issue by garyee** [swagger-api/swagger-editor#2061]
### Content & configuration

Our swagger file has over 3000 lines and the number of paths is fairly big. Therefore it would be great to have a fold/ unfold all button on top of all the paths. Or maybe like with the models, have a close group button, or both.

**Comment by garyee** [comment]
In the UI.

**Comment by webron** [comment]
Thanks for the clarification. This is a Swagger UI issue and not an Editor one.

Generally speaking, you do have collapse/expand in operations under a specific tag, so assuming your paths are well organized, that should take the load off some of it. 

If you feel more is needed, please file a ticket in Swagger UI and follow the issue template to provide the details. An example would be very useful..
