### ISSUE TITLE
swagger request body - undefined

### ISSUE THREAD

**Issue by cotnic** [swagger-api/swagger-editor#2064]
In our .yaml file we've defined an endpoint that accepts a request body that we've defined in .xsd schema.

We generate a POJO out of the .xsd schema and would like to use that in our swagger/openAPI endpoint. Is that possible?

If not is it possible to define in swagger to use the request body as HttpServletRequest ?

**Comment by webron** [comment]
This question doesn't seem related to the editor but more of a general question. Please use our [Community Forums](https://community.smartbear.com/t5/Swagger-Open-Source-Tools/bd-p/SwaggerOSTools) for such questions.
