### ISSUE TITLE
`$ref` not fully supported

### ISSUE THREAD

**Issue by AppTeam-HolyAG** [swagger-api/swagger-editor#2067]
**Updated**

### Q&A (please complete the following information)
 - OS: macOS
 - Browser: Safari
 - Version: 3.24.0
 - Method of installation:  npm, local host
 - Swagger-Editor version: 3.24.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

*EDIT:*
I figured, the fragment must be an _absolute_ JSON Pointer. So, a leading slash is actually required: `#/User`. So, issuing an error for `#User` is correct in Swagger Editor.

Yaml Snippet: 
```yaml
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: 'Schemas/User.yaml/#/User'. 
```

### Describe the bug you're encountering

External document will not be resolved.

### To reproduce...
always 

### Expected behavior

According JSON Schema, the value of  a `$ref` is a URI, URI reference, URI template or a JSON pointer. 

The referenced external document should be found. The right pane in the Swagger Editor should represent the content of the external documents.

### Additional context or thoughts

According JSON Schema, the value of `$ref` is a URI, URI reference, URI template or a json pointer. However it seems, Swagger Editor only accepts a URI fragment which only specifies items within the document. That is, it seems Swagger Editor cannot reference JSON defined outside this document.

In case the `$ref` value is a "Relative Uniform Resource Locator" (see [RFC 3986](https://tools.ietf.org/html/rfc3986)), it may not be a fully specified URI. A relative URI may require a "base URI" in order to be fully resolved into a URI.

Thus, Swagger Editor should ensure that this base URI can be 
a) implicitly deduced from the current document, and
b) explicitly set via a configuration

Maybe I am missing something, but I could not find this feature, i.e. defining the base URI, in this version.

**Comment by hkosova** [comment]
Swagger Editor 3.x currently supports absolute $refs (i.e. `$ref: 'https://...'`) and local JSON pointers (i.e. `$ref: '#/components/schemas/Foo'`).

Support for relative references is not available yet, please follow #1409 for updates.
