### ISSUE TITLE
Swagger2.0 doc can not be completely converted into OpenAPI3.0

### ISSUE THREAD

**Issue by chenmeng111** [swagger-api/swagger-editor#2075]
![image](https://user-images.githubusercontent.com/29196565/69126901-323e8200-0ae4-11ea-89bb-5ca248e18cd4.png)

**Comment by webron** [comment]
@chenmeng111 Please file a new issue following our issue template. We won't be able to help without getting the basic detailed asked in the template.

**Comment by hkosova** [comment]
@webron I reproduced the issue and filed it here: https://github.com/swagger-api/swagger-parser/issues/1261
