### ISSUE TITLE
minItems not being respected in auto-generated example value

### ISSUE THREAD

**Issue by hhromic** [swagger-api/swagger-editor#2076]
### Q&A (please complete the following information)
 - OS: Docker container in Linux
 - Browser: Chrome
 - Version: Version 78.0.3904.97 (Official Build) (64-bit)
 - Method of installation: Official Docker image
 - Swagger-Editor version: `latest` tag in Docker Hub
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

**Example OpenAPI definition:**
```yaml
openapi: 3.0.2
info:
  title: 'Test'
  version: 1.0.0

paths:
  /test:
    get:
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
                minItems: 3
                maxItems: 5
```

### Describe the bug you're encountering

The Swagger Editor is ignoring the `minItems` attribute of an `array`-type response when auto-generating example values. Currently, only one item is being generated regardless of the `minItems` declaration in the schema.

### To reproduce...

1. Create a new API specification
2. Copy/paste the minimum example in this issue
3. Refer to the right-panel with the API preview
4. Open the `/test` endpoint path and verify the example value being generated for the response

### Expected behavior

Auto-generated example value showing at least `minItems` elements in the array. For the example in this issue, it should be showing something like this: `[0, 0, 0]`.

### Screenshots

![image](https://user-images.githubusercontent.com/5802993/69361496-82544a80-0c84-11ea-94a4-cb4c54a413cf.png)

**Comment by hhromic** [comment]
Just verified it also happens in the live Swagger Editor: http://editor.swagger.io/

**Comment by GregNed** [comment]
Got the same issue. It makes one have to manually add the missing values which slows down the work. Any updates on the issue?

**Comment by hhromic** [comment]
Thanks @GregNed for reminding me of this issue.

I can confirm that both, the `latest` [Docker image](https://hub.docker.com/r/swaggerapi/swagger-editor/) and the [online version](http://editor.swagger.io/) of the Swagger Editor both seem to have fixed the issue:

![image](https://user-images.githubusercontent.com/5802993/131262558-00137e24-7a53-49bf-855a-dc2256361560.png)

I can also confirm that the `latest` [Docker Image](https://hub.docker.com/r/swaggerapi/swagger-ui/) of the Swagger UI also is fixed 👍 

@GregNed maybe try updating your local Swagger component to latest?

**Comment by GregNed** [comment]
@hhromic Alright, let's close it then. I'm using it via the Connexion lib for Python. I guess they just haven't updated their dependencies yet.

**Comment by hhromic** [comment]
@GregNed looks like you are not alone: https://github.com/zalando/connexion/issues/1412
And looks like a PR to update Swagger UI is already proposed so I guess you just have to wait :)
