### ISSUE TITLE
Request to generate JavaScript Client Code not working

### ISSUE THREAD

**Issue by JPiPipeline** [swagger-api/swagger-editor#2080]
Error reported in Chrome Developer Tools:

javascript:1 POST https://generator.swagger.io/api/gen/clients/javascript 500 (Request failed.)

**Comment by hkosova** [comment]
Code generation is powered by the [Swagger Codegen](https://github.com/swagger-api/swagger-codegen) project. There is an issue with OAS3 JavaScript client codegen - https://github.com/swagger-api/swagger-codegen/issues/9909. Please follow that issue for updates.
