### ISSUE TITLE
The "Generate Server" functionality of the editor doesn't work for NodeJS

### ISSUE THREAD

**Issue by paulito-bandito** [swagger-api/swagger-editor#2086]
Hi all, 

I'm generating a NodeJs server with the Swagger UI, and I'm seeing three errors: 

A.) it seems that the middleware folder isn't getting copied and compiled over to the dist folder. B.) The `index.js` file in root isn't pointing at the right file.
C.) The `index.js` file isn't pointing at the correct port.  

Steps to recreate:

Open https://editor.swagger.io/
Use the command Edit > Convert to YAML
Use the command Edit > Convert to Open API 2
Use the command Generate Server > nodejs-server
Unzip the file it gave you with the previous command
Run npm start which will build and try to run the server which will bonk on this particular error mentioned.

Here's the Stackoverflow question for more context which I outlined how to fix it in the short-term:

https://stackoverflow.com/questions/59648179/swagger-3-0-1-server-generator

**Comment by hkosova** [comment]
Editor's code generation functionality uses [Swagger Codegen](https://github.com/swagger-api/swagger-codegen). Please open an issue in the Codegen repository instead:
https://github.com/swagger-api/swagger-codegen/issues
