### ISSUE TITLE
Add support for Clojure EDN OpenAPI file

### ISSUE THREAD

**Issue by peter-the-grate** [swagger-api/swagger-editor#2088]
### Content & configuration
N/A

### Is your feature request related to a problem?
As a user, I would like to use Clojure edn as a data spec file so that my productivity can be improved. https://github.com/edn-format/edn

### Describe the solution you'd like
I would like to interact with the editor with Clojure's edn file format. https://github.com/edn-format/edn

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by webron** [comment]
I'm sorry, but this is going to be out of scope for that. We're focused on supporting what the OpenAPI allows, and this is not part of it.
