### ISSUE TITLE
conflict with specification in requestBody

### ISSUE THREAD

**Issue by mitch-kyle** [swagger-api/swagger-editor#2089]
### Q&A (please complete the following information)
 - OS: gnu/linux
 - Browser: firefox
 - Version: 71
 - Method of installation: webapp
 - Swagger-Editor version: unknown (current on editor.swagger.io)
 - Swagger/OpenAPI version: 3.0.0

Example Swagger/OpenAPI definition:
```yaml
paths:
  '/foo':
    post:
      requestBody:
        content:
          application/json:
            schema:
              required: []
              type: object
      responses:
        '200':
          description: "foo"
openapi: 3.0.0
info:
  version: 1.0.0
  title: Issue Example
```

Swagger-Editor configuration options:
default on editor.swagger.io

### Describe the bug you're encountering
the editor gives the warning that 'required' on the schema for a
requestBody should be non-empty. I don't see that stated anywhere in the
specification.

### To reproduce...

1. load the given YAML
2. observe the errors

### Expected behavior
No error message is shown as the specification makes no such assertion

**Comment by hkosova** [comment]
OpenAPI 3.0 [Schema Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#schemaObject) is based on JSON Schema draft 5, which says the following about `required`:

https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-5.15

> This array MUST have at least one element.

<br/>

The next version of the spec - OpenAPI 3.1 - will use the latest JSON Schema draft 2019-09 which allows empty `required` list.
