### ISSUE TITLE
Swagger Editor does not load in IE11

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-editor#2090]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Internet Explorer 11.535.18362.0, update Versions: 11.0.165 (KB4530677)
 - Method of installation: https://editor.swagger.io
 - Swagger-Editor version: 3.8.0
 - Swagger/OpenAPI version: n/a

### Describe the bug you're encountering
The [documentation](https://github.com/swagger-api/swagger-editor/#browser-support) claims that
> Swagger Editor works in the latest versions of Chrome, Safari, Firefox, Edge and IE11.

but the editor does not actually work in IE 11 - it does not load.

Console errors:
```
SCRIPT1010: Expected identifier
swagger-editor-bundle.js (138,324938)

SCRIPT5009: 'SwaggerEditorBundle' is undefined
editor.swagger.io (53,5)
```

### Screenshots
![Swagger Editor in IE 11](https://user-images.githubusercontent.com/8576823/72722124-a7830d80-3b8e-11ea-8e7a-ec6102bf596f.png)

### Additional context or thoughts
If Swagger Editor does not actually support IE11 anymore, documentation should be updated accordingly.

**Comment by webron** [comment]
Solved :)

**Comment by epiphanizer** [comment]
Heyyy! I didn't get the error message, but this thread certainly helped me look to open my project in Chrome, where everything "just worked."

Thank you!
