### ISSUE TITLE
OAS3 requestBody $ref format validation is overzealous, gives false positives

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-editor#2096]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome latest
 - Method of installation: https://editor.swagger.io
 - Swagger-Editor version: 3.8.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.2
info:
  title: requestBody $ref test
  version: 1.0.0
paths:
  /foo:
    post:
      requestBody:
        $ref: 'https://httpbin.org/anything/foo.yaml'
      responses:
        '200':
          description: ok
```

### Describe the bug you're encountering

https://github.com/swagger-api/swagger-editor/blob/master/src/plugins/validate-semantic/validators/oas3/refs.js

The `validateOAS3RefsForRequestBodiesReferenceRequestBodyPositions` function here is buggy. It expects that the `requestBody.$ref` path contains the `#/...` part, and that the `#/...` part contains either the `requestBodies` or `requestBody` segment. This is not necessarily the case. For example, a `$ref` may point to an external file with no `#/...` part.

I think the logic should be changed to something like:
```
if ($ref value begins with '#/components'
    and
    $ref value does not begin with '#/components/requestBodies/')
then error
otherwise no error
```
(This is just an example; this doesn't account for the rare/edge cases listed below.)

### Expected behavior
The definition above should not produce errors in the editor.

### Additional context or thoughts
In the context of `requestBody`, the following `$ref` paths are valid:

1\)
```yaml
$ref: '#/components/requestBodies/addPetBody'
```

2\) Any external `$ref` is semantically valid here. There's no way to tell from the `$ref` path alone whether or not such a `$ref` points to a RequestBody Object.
```yaml
$ref: 'addPetBody.yaml'

$ref: './components.yaml#/path/to/some/node'

$ref: 'https://example.com'

$ref: 'https://example.com/file.yaml#/requestBody1'

$ref: 'https://example.com/file.yaml#/components/addPetBody'

$ref: 'https://example.com/file.yaml#/components/requestBodies/addPetBody'

$ref: 'https://example.com/file.yaml#/components/requestBodies/group1/addPetBody'

$ref: 'https://example.com/file.yaml#/requestBodies/addPetBody'
```

3\) Also valid, but rare/edge cases:
```yaml
# refs directly to the `requestBody` node in other paths and callbacks
$ref: '#/paths/~1foo/post/requestBody'

$ref: '#/components/callbacks/callback1/%7B%24request.body%23~1callbackUrl%7D/post/requestBody'
                                        ^^ {$request.body#/callbackUrl} ^^

$ref: '#/paths/~1sfoo/post/callbacks/callback1/%7B%24request.body%23~1callbackUrl%7D/post/requestBody'


# refs where any of the path nodes is an extension
$ref: '#/x-body1'

$ref: '#/x-extension/addPetBody'

$ref: '#/<any-key-that-allows-extensions>/x-extension/body1'

$ref: '#/components/x-body1'
```

NOT valid:
```yaml
$ref: '#/components/schemas/Pet'

$ref: '#/components/schemas/requestBody'
# a schema named "requestBody" is not actually a Request Body component

$ref: '#/paths/~1foo/post/requestBody/schema'
```

**Comment by shockey** [comment]
@hkosova, I notice that the logic you call for completely removes checking the ref pointer's parent for `requestBody`:

https://github.com/swagger-api/swagger-editor/blob/823d48cb6ad3acceec301c0f3d49b27620440eb1/src/plugins/validate-semantic/validators/oas3/refs.js#L19

... which I absolutely agree on for remote references! however, do you see any value in preserving that for local references? I think that, since we can assume the local document is an OpenAPI document, any local reference whose parent isn't `requestBodies` (in the case of a Component reference) or `requestBody` (in the case of a cross-operation reference) would be invalid, and it'd be useful for us to error in that case.

**Comment by hkosova** [comment]
@shockey 
> removes checking the ref pointer's parent for `requestBody`

That's right - because valid request body $refs can only have `requestBody` as the last node of the `$ref` path; it cannot be a parent node.

```
# Correct
$ref: '#/components/requestBodies/Foo'

$ref: '#/paths/.../post/requestBody'

# Incorrect
$ref: '#/paths/.../post/requestBody/schema'
```
