### ISSUE TITLE
save rendered html?

### ISSUE THREAD

**Issue by jitin-sameer** [swagger-api/swagger-editor#210]
From Swagger Editor, there seems to be no option to save the generated HTML. Am I missing something?

**Comment by mohsen1** [comment]
@SirWellington @jitin-sameer This feature has been added. Click File>Download HTML to get the docs as a stand-alone document

**Comment by rafaferreira** [comment]
I don't see this option, just File > Download (JSON, YAML)

**Comment by mohsen1** [comment]
@rafaferreira Please use Swagger UI for rendering the UI.

**Comment by rafaferreira** [comment]
Hey @mohsen1, thanks for your reply.

But what that means? I'm using http://editor.swagger.io

**Comment by mohsen1** [comment]
Swagger Editor can export your specs JSON. Use that JSON to render your UI using Swagger UI. Read swagger ui docs for more information

**Comment by richmidwinter** [comment]
So the feature hasn't been added?

**Comment by mohsen1** [comment]
This feature was removed

**Comment by richmidwinter** [comment]
Oh. That's a shame.

**Comment by mohsen1** [comment]
Swagger UI is the one for rendering the UI but if you you can "cheat" and serve entire Swagger Editor with a custom CSS that hides editor parts. Learn about configuring Swagger Editor in the [configuration docs](https://github.com/swagger-api/swagger-editor/blob/master/docs/config.md)

**Comment by henrikakselsen** [comment]
Why was the feature removed?

**Comment by kongfujianlong** [comment]
This feature should definitely be supported...why does it get removed....

**Comment by kinduff** [comment]
:+1: on rendering HTML

**Comment by chrisdudley** [comment]
CORS would be an issue on any exported HTML though.

**Comment by sadlerw** [comment]
What about using behind a firewall?  Save as html seems like a necessary feature.

**Comment by unsalted** [comment]
TBH - the UI is missing the aesthetics of the editor - wish I could just grab html from the editor instead ; )
