### ISSUE TITLE
Timeout + CORS error on editor.swagger.io when attempting Code Generation on OAS 3.0 yaml

### ISSUE THREAD

**Issue by vincent-polite** [swagger-api/swagger-editor#2111]
### Q&A (please complete the following information)
 - OS: Windows client
 - Browser: Error happens in Edge and Chrome latest versions
 - Method of installation: using online variant at editor.swagger.io
 - Swagger-Editor version: whatever is live at editor.swagger.io as of 2/27/2020 2:30pm CST
 - Swagger/OpenAPI version: Attempting to parse OAS 3.0 yaml document

### Describe the bug you're encountering
I am attempting to use the Client Code Generation tools; specifically csharp
In the past, whether I used 2.0 or 3.0, the code generation worked, and after a few seconds I would receive a zipped file in the language variant of interest.

Today, I attempted to do this on a new .yaml file received from Equifax for one of their APIs (the file should be attached to this issue)

Apparently the codegen calls a different endpoint depending on whether openAPI 3 or 2 is being used.

When I attempted to parse my file, I received the following error output in the javascript console after a few seconds:

```
2generate:1 POST https://generator3.swagger.io/api/generate 504 (Gateway Time-out)
(index):1 Failed to load https://generator3.swagger.io/api/generate: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://editor.swagger.io' is therefore not allowed access. The response had HTTP status code 504. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
(index):1 Uncaught (in promise) TypeError: Failed to fetch
```

This seems like it could just be a basic timeout, but the CORS references made me wonder if something might be broken on the server configuration.  Any advice on how to tell and who to contact to resolve would be appreciated.

I am happy to download the tools from source and try myself, but I don't want to bury myself in config hell if the online system is supposed to work, but just isn't.

### To reproduce...

1. Navigate to http://editor.swagger.io
2. Load the file attached to the issue
3.  Attempt to use the code generation feature, targeting csharp
4.  wait a few seconds and realize nothing happened, inspect the console and witness the error I reported above.

### Expected behavior
Either a notification that an error has occurred to the client or the actual code generated files (as usual in .zip form).  I'm reporting the issue here as opposed to the codegen project because I do not know the cause of the issue.  Is it my spec being malformed or just too big?  Or is there something actually amiss with the editor/codegen pipeline?
[2020-02-13-efx-interconnect-decisionhub1.1.yaml.txt](https://github.com/swagger-api/swagger-editor/files/4264000/2020-02-13-efx-interconnect-decisionhub1.1.yaml.txt)

**Comment by webron** [comment]
@vincent-polite thanks for filing the issue and providing the definition.

Upon further investigation, it seems this is not a CORS issue and unfortunately the error message in the console is misleading.

For some reason, the online generator is failing to generate the code, which would require further investigation but is not related to the Editor and should be filed directly on the Codegen project.

That said, I'd recommend trying first to use the codegen cli too to generate the code and see if that works.

**Comment by vincent-polite** [comment]
Thanks.  The editor online is generating properly now, so something was kickstarted/fixed.
