### ISSUE TITLE
required can be empty list

### ISSUE THREAD

**Issue by Behoston** [swagger-api/swagger-editor#2113]
### Q&A (please complete the following information)
 - OS: Linux
 - Browser: Firefox
 - Version: doesn't matter
 - Method of installation: editor.swagger.io
 - Swagger-Editor version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration
https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.6.5.3

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.2
info:
  title: Required
  version: bug
paths:
  /here/:
    get:
      description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    readOnly: true
                  name:
                    type: string
                required: []

```

### Describe the bug you're encountering
Swagger editor raise erron when rquired is an empty list. Due to specification, `required` is documented in JSON Schema. JSON Schema tells, that it can be empty list.

### To reproduce...

1. Go to https://editor.swagger.io
2. Paste sample

### Expected behavior
should work with empty list

### Screenshots

![obraz](https://user-images.githubusercontent.com/7823689/75574711-12154c00-5a5f-11ea-938d-8755fc792dd4.png)

**Comment by webron** [comment]
OAS3 uses Draft 4 or Draft 5 of the  JSON Schema, where it states - https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.4.3 (so it cannot be empty).

OAS3.1 (not published yet) will support the latest JSON Schema draft, which is when your example would become valid.

**Comment by Behoston** [comment]
thx for help
