### ISSUE TITLE
readOnly and writeOnly does not work with multipart/form requests

### ISSUE THREAD

**Issue by just-chillin** [swagger-api/swagger-editor#2114]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: chrome
 - Version: 80
 - Method of installation: installer
 - Swagger-Editor version: 3.8
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
 Video:
      type: object
      description: The metadata associated with a video.
      properties:
        title:
          type: string
          description: The name of the video.
        key:
          type: string
          description: >
            The s3 key of the video. 
            The video can be found at https://video.remixapp.net/${key}.mp4
          readOnly: true
          format: uuid
        owner:
          allOf:
            - $ref: '#/components/schemas/User'
            - title: ReadOnlyUser
              readOnly: true
        rawVideo:
          description: The raw base64 encoded binary video data
          type: string
          format: byte
          writeOnly: true
----------------------------------------------------
    /videos:
      put:
        summary: Uploads a video.
        security:
          - UserAction: []
        requestBody:
          required: true
          content:
            multipart/form-data:
              schema:
                  $ref: '#/components/schemas/Video'
              encoding:
                rawVideo:
                  contentType: video/mp4
        responses:
          200:
            description: Upload sucessful
          413:
            description: Video was too large
      get:
        
```

Swagger-Editor configuration options:
The default configuration that comes with swaggerHub

```
?yourQueryStringConfig
```

### Describe the bug you're encountering
When I use multipart/form-data to upload a video object, the readOnly fields appear in the documentation, when they should not.

### To reproduce...

1. Define a POST request with a multipart/form-data body
2. Label some of the properties as readOnly
3. Save the document.
4. Look at the documentation for the POST request.

### Expected behavior
The readOnly fields should be removed from the POST request.

### Screenshots

![image](https://user-images.githubusercontent.com/6798352/75594785-ee023c80-5a57-11ea-94a1-2dca45f2b3c8.png)
![image](https://user-images.githubusercontent.com/6798352/75594833-34579b80-5a58-11ea-88ae-100668636c6f.png)

### Additional Info
- I am working in swaggerhub.
- Also, I have noticed similar issues, but this behavior seems to only occur with multipart/form-data, so I believe that it is a different issue.
- Sorry for not including my entire OpenAPI definition. I'm working in a private repo, so I'd rather not reveal the entire definition if I can.

**Comment by emiliosa** [comment]
I think readOnly applies after you fires POST request, so inside body there will no attributes with readOnly. But also is confusing those attr are enable still inside body before. You can check in https://editor.swagger.io/ for testing the API and reproduces this.

**Comment by tnotheis** [comment]
Any updates on this issue? I'm currently facing the same problem and wonder if there is any solution.

**Comment by emiliosa** [comment]
I think the best workaround is NOT using swagger-ui as a testing tools until it works as it should, use it only for API autogenerate documentation and then use Postman to test your API's.

**Comment by tim-lai** [comment]
This swagger-ui PR should resolve this issue. Feel free to re-open if not. https://github.com/swagger-api/swagger-ui/pull/6490
