### ISSUE TITLE
SwaggerGenerator via EnvironmentVariable

### ISSUE THREAD

**Issue by tsproesser** [swagger-api/swagger-editor#2127]
Right now SwaggerEditor expects the Generator unter https://generator.swagger.io what makes it almost impossible to set up a clean local Docker environment. So please consume a variable setting a custom Generator if defined.

**Comment by tsproesser** [comment]
https://github.com/swagger-api/swagger-editor/blob/master/src/index.js

defaults

**Comment by hkosova** [comment]
Duplicate of #1488.
