### ISSUE TITLE
Editor Swagger is not generating client in the public online version and in localhost

### ISSUE THREAD

**Issue by enriquesalas506** [swagger-api/swagger-editor#2128]
### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-Editor version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-Editor configuration options:
```js
SwaggerEditor({
  // your config options here
})
```

```
?yourQueryStringConfig
```

**Comment by hkosova** [comment]
See https://github.com/swagger-api/swagger-codegen/issues/10140.

**Comment by enriquesalas506** [comment]
Still not generating code in the online version or localhost

**Comment by hkosova** [comment]
@enriquesalas506 Please try again.
