### ISSUE TITLE
allOf to include main object and more array of schemas within it

### ISSUE THREAD

**Issue by sanghviyash** [swagger-api/swagger-editor#2132]
I am trying to return a Posts object with Images and Videos with it.
Posts, Images and Videos are all separate objects.
Posts with Images and Videos associated to it.
I am trying to create a new response in the following way:
```
    PostsResponse:
      allOf:
      - $ref: '#/components/schemas/Post'
      - Images:
        type: array
        items:
          $ref: '#/components/schemas/Image'
      - Videos:
        type: array
        items:
          $ref: '#/components/schemas/Video'
```
While trying to do the above thing following error is thrown

> should NOT have additional properties
> additionalProperty: Images

same error for Videos.

Please help

**Comment by webron** [comment]
Please read documentation about JSON Schema (for example - https://swagger.io/docs/specification/data-models/) to learn how to properly describe models.
