### ISSUE TITLE
Is Swagger Editor self-contained or will it make remote calls to validate documents?

### ISSUE THREAD

**Issue by anno1985** [swagger-api/swagger-editor#2147]
Basically, if I run the editor locally, will it try to phone home/send my Swagger specs anywhere remotely, e.g. to swagger.io, for example in order to validate the file?

**Comment by webron** [comment]
The validation is done internally in the tool (as opposed to Swagger UI). The only thing I can think of is the use of the code generation from the menu. Populating that list does call  a service on swagger.io, but it will not send your definition unless you ask it to actually generate something.

**Comment by hkosova** [comment]
Another thing is the integrated OAS2->OAS3 converter (Edit > Convert to OpenAPI 3 menu command) which also calls a service on swagger.io.

@anno1985 if you want, you can host the [codegen](https://github.com/swagger-api/swagger-codegen/) and [converter](https://github.com/swagger-api/swagger-converter/) services locally and specify their locations using the [configuration options](https://github.com/swagger-api/swagger-editor/blob/master/src/index.js#L54-L56), or you can set those options to `null` to disable the codegen and converter.
