### ISSUE TITLE
The property "entries" in a object schema breaks the editor

### ISSUE THREAD

**Issue by nerdlibfront** [swagger-api/swagger-editor#2154]
### Q&A (please complete the following information)
 - OS: macOS & Ubuntu
 - Browser: chrome
 - Version: 81.0.4044.138
 - Method of installation: docker / https://editor.swagger.io
 - Swagger-Editor version: 3.8.3
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  description: 'test'
  title: 'test'
  version: 1.0.0
paths:
  '/foo':
    get:
      description: 'get something'
      responses:
        '200':
          description: 'All good'
          content:
            application/json:
              schema:
                type: object
                properties:
                  entries: 
                    type: string
```

Swagger-Editor configuration options:
- Default docker container, no special configuration
- or use https://editor.swagger.io, no special configuration

### Describe the bug you're encountering
Document does not load, shows error "Unable to render this definition", probably due to a javascript error:

```
TypeError: e.entries is not a function
    at swagger-ui.js:1
    at $ (swagger-ui.js:1)
    at immutable.js:3016
    at immutable.js:2699
    at it.__iterate (immutable.js:2206)
    at yt.__iterate (immutable.js:2698)
    at n.Ot.n.__iterateUncached (immutable.js:3015)
    at te (immutable.js:604)
    at n.$.__iterate (immutable.js:274)
    at n.forEach (immutable.js:4381)
```

### To reproduce...

1. Go to https://editor.swagger.io
2. Load/Paste the mentioned yaml
3. See the error

### Expected behavior
The document loads without error as it is a valid openapi 3.0.0 document.

### Screenshots
<img width="1680" alt="Screenshot 2020-05-18 at 11 42 45 (2)" src="https://user-images.githubusercontent.com/9337940/82198543-c1deb500-98fc-11ea-9c9b-6c3f02e66934.png">

**Comment by hkosova** [comment]
Thanks for the report! This issue is tracked in https://github.com/swagger-api/swagger-ui/issues/6016 so I'll close this one as a duplicate.

As a workaround please use editor v. 3.8.2, you can download it from the [Releases](https://github.com/swagger-api/swagger-editor/releases) page.
