### ISSUE TITLE
Field name "entries" in a schema causes swagger-editor to fail

### ISSUE THREAD

**Issue by jmmolina796** [swagger-api/swagger-editor#2155]
When I type the field name **entries**, I received a message saying: "Unable to render this definition". 

```yml
paths:
  /pet:
    post:
      summary: "Add a new pet to the store"
      description: ""
      parameters:
      - in: "body"
        name: "body"
        schema:
          $ref: "#/definitions/Pet"
      responses:
        "405":
          description: "Invalid input"
definitions:
  Pet:
    type: "object"
    properties:
      id:
        type: "integer"
      entries:
        type: "array"
        items:
          type: "string"
```
<img width="538" alt="Screen Shot 2020-05-18 at 17 14 21" src="https://user-images.githubusercontent.com/6262461/82264712-0e40e980-992b-11ea-9077-065aa2e02bde.png">

I need to write **entries** as a field since my API requires this name.

If I change **entries** to **entry**, it works as expected.

```yml
paths:
  /pet:
    post:
      summary: "Add a new pet to the store"
      description: ""
      parameters:
      - in: "body"
        name: "body"
        schema:
          $ref: "#/definitions/Pet"
      responses:
        "405":
          description: "Invalid input"
definitions:
  Pet:
    type: "object"
    properties:
      id:
        type: "integer"
      entry:
        type: "array"
        items:
          type: "string"
```

Can someone help me with this problem, why it fails when I use **entries** as a field name?

**Comment by hkosova** [comment]
Thanks for the report! This issue is tracked in https://github.com/swagger-api/swagger-ui/issues/6016 so I'll close this one as a duplicate.

As a workaround please use editor v. 3.8.2, you can download it from the [Releases](https://github.com/swagger-api/swagger-editor/releases) page.
