### ISSUE TITLE
entries property break the generator editor

### ISSUE THREAD

**Issue by kaitos90210** [swagger-api/swagger-editor#2156]
### Q&A (please complete the following information)
 - OS: [e.g. macOS Windows  ALL]
 - Browser: [e.g. chrome, safari, firefox]
 - Version: [latest on 19052020 https://editor.swagger.io/]
 - Method of installation: [e.g. not apply]
 - Swagger-Editor version: [latest on 19052020 https://editor.swagger.io/]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

Example Swagger/OpenAPI definition:
openapi: 3.0.1
info:
...
```yaml
    Addresses:
      type: object
      properties:
        entries:
          type: array
          items:
            $ref: '#/components/schemas/Address'
```

Swagger-Editor configuration options:
```js
SwaggerEditor({
  // your config options here
})
```

```
?yourQueryStringConfig
```

### Describe the bug you're encountering

We have an API with the following component
The parameter `entries` breaks the swagger generator

### To reproduce...

1. Go to https://editor.swagger.io/
2. Click on edit the page
3. Scroll down to any property and rename it to entries

**Comment by kaitos90210** [comment]
![image](https://user-images.githubusercontent.com/1625733/82388402-74b02f80-9a31-11ea-8f0a-32e4614eeca0.png)

**Comment by hkosova** [comment]
Thanks for the report! This issue is tracked in https://github.com/swagger-api/swagger-ui/issues/6016 so I'll close this one as a duplicate.

As a workaround please use editor v. 3.8.2, you can download it from the [Releases](https://github.com/swagger-api/swagger-editor/releases) page.
