### ISSUE TITLE
API updates via REST over http return 200s without updating

### ISSUE THREAD

**Issue by greilly** [swagger-api/swagger-editor#2157]
Using on-prem version 1.23.1-46

When sending a POST request over http, a 200 is returned, but changes are not actually saved.  Changes are only saved when using https.

Example:
1. Make a GET request (either http or https works).  A 200 is returned, with JSON.
```
curl --location --request GET 'https://swagger.se-charter.net/v1/apis/SE-Video/Testing7/1.0.2' \
--header 'Authorization: *****'
```
2. Make a POST request over http.  Use the JSON from step #1, but change something.  A 200 is returned, with the same JSON returned as step #1.
```
curl --location --request POST 'http://swagger.se-charter.net/v1/apis/SE-Video/Testing7' \
--header 'Authorization: *****' \
--header 'Content-Type: application/json' \
--data-raw '{ ... }'
```
3. Re-make the call from step #1; verify that nothing has changed.
4. Re-make the call from step #2, but use https this time.  Verify that a 200 was returned, with no JSON.
5. Re-make the call from step #1; verify that this time, the change as been saved.

Expected behavior:
The POST over http should either save the specified changes or return a non-200 response.

**Comment by hkosova** [comment]
This repository is for the open-source Swagger UI project.

To contact SwaggerHub support, use this link instead:
https://support.smartbear.com/message/?product=SwaggerHub
