### ISSUE TITLE
invalid REST path over http returns a 20

### ISSUE THREAD

**Issue by greilly** [swagger-api/swagger-editor#2158]
Using on-prem version 1.23.1-46

While first using Swaggerhub's REST APIs, I mistakenly made POST requests to an invalid path, http://swagger.se-charter.net/v1/apis/SE-Video/Testing7/1.0.2 (the version number should not be included in POST requests).  The response was a 200, leading me to believe this was valid.  When sending the same request over https, a 405 error is returned. 

Example:
1. Make a POST request over http.  A 200 is returned, with the same JSON returned as when doing a GET to the same endpoint.
```
curl --location --request POST 'http://swagger.se-charter.net/v1/apis/SE-Video/Testing7/1.0.2' \
--header 'Authorization: *****' \
--header 'Content-Type: application/json' \
--data-raw '{ ... }'
```
2. Re-make the call, but use https.  A 405 with the following JSON is returned:
```
{
    "code": 405,
    "message": "HTTP 405 Method Not Allowed"
}
```

Expected behavior:
POST requests over http should have the same functionality as requests over https.  If the desire is for POST requests over http not to work, then an error code should be returned.

**Comment by hkosova** [comment]
This repository is for the open-source Swagger UI project.

To contact SwaggerHub support, use this link instead:
https://support.smartbear.com/message/?product=SwaggerHub
