### ISSUE TITLE
special problem

### ISSUE THREAD

**Issue by zhanglonquan** [swagger-api/swagger-editor#2160]
✖ Unknown Error
ptr must be a JSON Pointer

Jump to line
Details
 Object
message: "ptr must be a JSON Pointer"
code: "UNCAUGHT_SWAY_WORKER_ERROR"
level: 900
type: "Unknown Error"
description: "ptr must be a JSON Pointer"

**Comment by webron** [comment]
Please file a new issue providing all the requested information in the issue template. We can't use the provided information to help.
