### ISSUE TITLE
Can't display complex model with sub objects

### ISSUE THREAD

**Issue by DavidPautet** [swagger-api/swagger-editor#217]
Hi,

I have a complex model with several object inclusions (a tree with around 5 levels of inclusion). I can't manage to display correctly my model using the online editor (http://editor.swagger.io/).

The file is parsed correctly (no errors), no issues in Javascript console.

This complex object is returned by a GET verb and the maximum inclusion in the Response section is 1. Oddly, on the model part below the maximum inclusion level is 2.

I have tried to modify the default sample (by adding for instance an Activities object in Product model) and the problem is reproductible.

Is there a rational behind this ?

Thanks for your help.
David.

![image](https://cloud.githubusercontent.com/assets/6059057/4756776/1f83a114-5ad0-11e4-90d5-3b2114dbdc54.png)
![image](https://cloud.githubusercontent.com/assets/6059057/4756791/45898ffe-5ad0-11e4-9b21-ac0cc7c45d8e.png)
![image](https://cloud.githubusercontent.com/assets/6059057/4756836/a103eef6-5ad0-11e4-9f59-da5832c0037d.png)

**Comment by nitinguptadr-dori** [comment]
Issue still exists in swagger-editor Version 2.10.3

**Comment by nitinguptadr-dori** [comment]
Issue Does not exist in version 3.5.7.  In the 2.10.3 version, it shows up as undefined after 5 levels of depth
