### ISSUE TITLE
Multiple allOf and $ref causing “f is undefined” errors

### ISSUE THREAD

**Issue by yurikhan** [swagger-api/swagger-editor#2170]
### Q&A (please complete the following information)
 - OS: Ubuntu 20.04 but I believe it does not matter
 - Browser: Firefox 76.0.1 (also tried Chromium 83.0.4103.61)
 - Method of installation: n/a
 - Swagger-Editor version: How am I supposed to know? The one that is deployed on editor.swagger.io as of today.
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
swagger: '2.0'
info:
  title: Explore API
  version: 0.0.2
definitions:
  Object:
    type: object
  OptionalIdObject:
    allOf:
      - $ref: '#/definitions/Object'
      - properties:
          id:
            type: string
  RequiredIdObject:
    allOf:
      - $ref: '#/definitions/OptionalIdObject'
      - required:
          - id
  SuccessResponse:
    allOf:
      - {}
      - type: object
        properties:
          data:
            $ref: '#/definitions/RequiredIdObject'
        required:
          - data
paths:
  '/foo':
    put:
      summary: Do something.
      responses:
        '200':
          description: Success.
          schema:
            $ref: '#/definitions/SuccessResponse'

```

Swagger-Editor configuration options: whatever is default on the web site

### Describe the bug you're encountering

Getting multiple `Resolver error` messages.

### To reproduce...

1. Go to https://editor.swagger.io/
2. Click in the editor
3. Select All (Ctrl+A), delete (Del), paste the above snippet
4. Click to expand the `PUT /foo` operation in the right pane
5. See errors: `Resolver error`, `f is undefined`. (On Chromium: `Cannot read property '1' of undefined`.)

As far as I can tell, everything is working as expected, except the errors. The example value is correct. Switching to the Model view lets me expand everything without generating additional errors. The `id` property is there, and it is correctly identified as required.

### Expected behavior

Should not spew errors.

### Additional context or thoughts

* If I inline the `SuccessResponse` definition instead of referencing it under `responses/200/schema`, the issue disappears.
* If I replace the `allOf` in `SuccessResponse` with its second subschema, the issue disappears.
* If I inline the `RequiredIdObject` definition instead of referencing it under `SuccessResponse/allOf/1/properties/data`, the issue disappears.
* If I inline the `OptionalIdObject` definition instead of referencing it under `RequiredIdObject/allOf/0`, the issue persists.
  * However, if I then flatten the two nested `allOf`s, the issue disappears.
* If I inline the `Object` definition instead of referencing it under `OptionalIdObject/allOf/0`, I get fewer error messages, but the issue persists.
* Adding `type: object` to any of the definitions or subschemas does not help. Nor should it matter, because it should propagate across references and `allOf`.

None of these are satisfactory workarounds, because in real life I have multiple operations that have the same response schema `SuccessResponse`, a couple of operations taking `OptionalIdObject` and `RequiredIdObject` as parts of the request body parameters, and all of the object definitions have more properties.

Am I doing something wrong, or is there any reason why it shouldn’t just work?

Do not hesitate to redirect me to the relevant library (swagger-js?)

**Comment by hkosova** [comment]
Looks like the same issue as https://github.com/swagger-api/swagger-ui/issues/5435 and https://github.com/swagger-api/swagger-ui/issues/5820.

**Comment by hkosova** [comment]
This seems to have been fixed in the latest editor version (by PR https://github.com/swagger-api/swagger-js/pull/1783).
