### ISSUE TITLE
Docker commands for local swagger file not working.

### ISSUE THREAD

**Issue by 5t33** [swagger-api/swagger-editor#2177]
### Q&A (please complete the following information)
 - OS: MacOS
 - Browser: Chrome
 - Version:  Chrome version? 83.0.4103.97
 - Method of installation: docker
 - Swagger-Editor version:  v3.11.3
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
Just running this command taken from the readme (with my own port):
```
docker run -d -p 4567:8080 -v $(pwd):/tmp -e SWAGGER_FILE=/tmp/swagger.json swaggerapi/swagger-editor
```

Example Swagger/OpenAPI definition:
```
{
  "openapi": "3.0.0",
  "info": {
     "description": "API for the ArtSpot client.",
     "version": "1.0.0",
     "title": "ArtSpot API",
     "contact": {
        "email": "contact@artspot.io"
     }
  },
  "paths": {
     "/cancelmembership/survey": {
        "post": {
           "summary": "Posts a user cancelation survey",
           "description": "Adds a cancelation survey to the cancelation survey table.",
           "responses": {
              "201": {
                 "description": "Survey created"
              },
              "400": {
                 "description": "invalid input, object invalid"
              },
              "404": {
                 "description": "User does not exist"
              }
           },
           "requestBody": {
              "content": {
                 "application/json": {
                    "schema": {
                       "$ref": "#/components/schemas/CancelationSurvey"
                    }
                 }
              },
              "description": "Survey to add"
           }
        }
     }
  },
  "components": {
     "schemas": {
        "CancelationSurvey": {
           "type": "object",
           "required": [
              "userEmail",
              "radioResponse",
              "formResponse"
           ],
           "properties": {
              "userEmail": {
                 "type": "string",
                 "format": "email",
                 "example": "hello@world.com"
              },
              "radioResponse": {
                 "type": "string",
                 "example": "Too Expensive."
              },
              "formResponse": {
                 "type": "string",
                 "maximum": 2046,
                 "example": "User experience was underwhelming."
              }
           }
        }
     }
  }
}
```

### Describe the bug you're encountering
When using the provided docker command to use a local swagger document, the server still defaults to the petstore API.

### To reproduce...
Run the command pasted above, and visit the web page.

### Expected behavior
Swagger editor will start using the supplied swagger file.

**Comment by evgeniy-khist** [comment]
The merge commit [f93e1ea](https://github.com/swagger-api/swagger-editor/commit/f93e1ea8fce8f8e927310324ee56cfeb172030fb) into master of the PR #2072 contains an error.
In the commit [update index.html per reviewer comment](https://github.com/swagger-api/swagger-editor/pull/2072/commits/400063b7cc1c3ee33258f6e99dd1dae33fa216e5) the line following line were removed:
```
url: "https://petstore.swagger.io/v2/swagger.json",
```

So, the following block in the [docker-run.sh](https://github.com/swagger-api/swagger-editor/blob/v3.11.3/docker-run.sh#L11) is useless:

```
if [[ -f $SWAGGER_FILE ]]; then
  cp -s $SWAGGER_FILE $NGINX_ROOT
  REL_PATH="/$(basename $SWAGGER_FILE)"
  sed -i "s|https://petstore.swagger.io/v2/swagger.json|$REL_PATH|g" $INDEX_FILE
fi
```

`sed` will not replace anything and Pet Store will remain the default API to be opened.

But the [README.md](https://github.com/swagger-api/swagger-editor/blame/v3.11.3/README.md#L75) still states that
```
You can provide your own json or yaml definition file on your host
docker run -d -p 80:8080 -v $(pwd):/tmp -e SWAGGER_FILE=/tmp/swagger.json swaggerapi/swagger-editor
```

**Comment by phsstory** [comment]
Quick workaround, give the runner the target.

DockerFile-Workaround

    FROM swaggerapi/swagger-editor
    RUN sed -i "s|presets:|url:'https://petstore.swagger.io/v2/swagger.json', presets:|g" /usr/share/nginx/html/index.html

`docker build -f ./DockerFile-Workaround . -q | xargs docker run -p 8080:8080 -v $(pwd):/tmp -e SWAGGER_FILE=/tmp/openapi.yaml`

For someone that wants to get a PR together and run the gauntlet the following should work.

docker-run.sh

    if [[ -f $SWAGGER_FILE ]]; then
      cp -s $SWAGGER_FILE $NGINX_ROOT
      REL_PATH="/$(basename $SWAGGER_FILE)"
      sed -i "s|presets:|url:'$REL_PATH', presets:|g" $INDEX_FILE
    fi

**Comment by rahulk94** [comment]
https://github.com/swagger-api/swagger-ui/issues/5383 is a similar issue. You can set the `SWAGGER_JSON` variable instead and achieve the expected result. Also `SWAGGER_JSON` doesn't actually care about JSON or YAML as far as I can tell so the below works fine:

```sh
docker run -p 80:8080 -e SWAGGER_JSON=/api.yaml -v /<absolute_path>/api.yaml:/api.yaml swaggerapi/swagger-ui
```
