### ISSUE TITLE
Multiple Paths Mapped to same operation

### ISSUE THREAD

**Issue by Facedancer1984** [swagger-api/swagger-editor#2184]
Hello.
I have a case when I need to map 2 paths both with GET method on one single operation.
Spring @RequestMapping supports several values for path ( @RequestMapping(
  value = { "/ex/advanced/bars", "/ex/advanced/foos" }, ... )
So I need the same for swagger. 
Using a   $ref:  in yml config doesn't work - it returns compilation failure - method METHOD_NAME is already defined in interface
So what should I do ?

**Comment by hkosova** [comment]
This looks like a question for [Springfox](https://github.com/springfox/springfox) or [Swagger Core](https://github.com/swagger-api/swagger-core/).
