### ISSUE TITLE
Swagger Editor doesn't output HTTP response's Location header

### ISSUE THREAD

**Issue by korygin** [swagger-api/swagger-editor#2191]
When **trying out** an asynchronous operation that returns HTTP 202 (Accepted) response with _Location_ header, it is important to know the value of this header. It appears HTTP Location response headers are ignored by Swagger Editor.

**Comment by hkosova** [comment]
Hi @korygin, do you have a live server for us to test against?

**Comment by korygin** [comment]
Hi Helen,

I don’t have a public instance but it should be easy to simulate locally with an HTTP debugger tool such as Fiddler.

Thanks,

Alex

On Jul 20, 2020, at 02:32, Helen Kosova <notifications@github.com> wrote:

﻿

Hi @korygin<https://github.com/korygin>, do you have a live server for us to test against?

**Comment by hkosova** [comment]
Is this maybe a CORS issue? The browser only exposes a response header to Swagger UI and Swagger Editor if that header is listed in the [`Access-Control-Expose-Headers`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers) response header. Some headers like `Content-Type` and `Content-Length` are exposed by default, whereas other like `Location` need to be explicitly listed in `Access-Control-Expose-Headers`.

See also https://github.com/swagger-api/swagger-ui/issues/3340#issuecomment-313550973 and https://github.com/swagger-api/swagger-ui/issues/4576.

<br/>

I've set up a sample mock server that returns both `Location` and `Access-Control-Expose-Headers: Location`, and the `Location` header appears in "try it out" results as expected:

![Location response header](https://user-images.githubusercontent.com/8576823/87965450-74312500-cac4-11ea-9727-e6e19c44a6b8.png)

**Comment by korygin** [comment]
Yes, that's it. Sorry, configuration issue on our end. Thanks!
