### ISSUE TITLE
 Read-only parameters are  listing under the operation parameters and those are editable 

### ISSUE THREAD

**Issue by SiluniPathirana** [swagger-api/swagger-editor#2192]
I created a simple Swagger spec that has a model with one read-only header property (ex: readonly=true (example: sample)). The form generated for POST operation does not mark the property as read-only and the user is able to change that field:

Please find the sample swagger definition

```
swagger: "2.0"
info:
  version: 0.0.0
  title: Simple API
paths:
  /:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/User"
      x-auth-type: "Application & Application User"
      x-throttling-tier: Unlimited
      parameters:
        - name: sample
          in: query
          required: false
          type: string
    post:
      parameters:
        - name: body
          in: body
          description: description
          schema:
            $ref: "#/definitions/User"
        - name: sample
          in: header
          required: false
          type: string
      responses:
        "200":
          description: OK
      x-auth-type: "Application & Application User"
      x-throttling-tier: Unlimited
definitions:
  User:
    properties:
      name:
        type: string
      createdAt:
        type: string
      sample:
        type: string
        readOnly: true
```

As per swagger OpenAPI Specification [1], ReadOnly properties should not be sent as part of the request but if we check the parameters example for that operation from the API Console, readOnly attributes are being shown and editable

Expected behavior: Does not show read-only parameters in the API console or make it uneditable.

Looking forward to hearing from you
Thanks
[1] https://swagger.io/specification/

**Comment by hkosova** [comment]
What version of Swagger Editor do you use? The latest version (e.g. https://editor.swagger.io) doesn't show `readOnly` properties in request bodies.

![image](https://user-images.githubusercontent.com/8576823/87640974-27f68580-c750-11ea-9ebf-a68efb4860e8.png)

**Comment by SiluniPathirana** [comment]
Could you please check the request header property "sample"

**Comment by hkosova** [comment]
If you mean
```yaml
        - name: sample
          in: header
          required: false
          type: string
```
it's a separate header parameter and is not related in any way to the `sample` property of the `User` schema.
