### ISSUE TITLE
Custom validation

### ISSUE THREAD

**Issue by jaydreyer** [swagger-api/swagger-editor#2194]
Hi all,

I asked a similar question, but it's been three years so I'm assuming some things have changed. Here was the original: https://github.com/swagger-api/swagger-editor/issues/1351

Basically, we have a bunch of extra x- type data in our specs that we validate. We now have our own api based validation API where we send the spec and get back the errors in the response (this is checking against our rules. The editor still handles all of the original validations- we add our errors to yours and display). We are trying to figure out how to integrate this with the editor. Is there documentation I'm missing that explains this? Or is @shockey 's response to my original question still the way to go?

Thanks in advance.

**Comment by jaydreyer** [comment]
Anything?

**Comment by tim-lai** [comment]
@jaydreyer shockey's response to the original question is still the way to go. :)

**Comment by jaydreyer** [comment]
Thanks, @tim-lai
