### ISSUE TITLE
How to determine version being used?

### ISSUE THREAD

**Issue by jaydreyer** [swagger-api/swagger-editor#2195]
Is there a way to see what version of swagger-editor is being used on a site? I was hoping when you click File, there would be an "about" or something. Or maybe the version number printed at the bottom of the screen in a corner. I looked through the source in the developer console in chrome and didn't see it, but totally could be missing it.

**Comment by hkosova** [comment]
Open the browser dev tools, switch to the Console tab and evaluate `versions`.

As for adding the version number to the menu, this is tracked in #1537.

**Comment by jaydreyer** [comment]
Great. Thanks, @hkosova !
