### ISSUE TITLE
Jest: Topbar InsertForm React child warning

### ISSUE THREAD

**Issue by tim-lai** [swagger-api/swagger-editor#2222]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: n/a
 - Version: n/a
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-Editor version: 3.12.0, 3.13.0, likely earlier versions
 - Swagger/OpenAPI version: n/a

### Content & configuration

Visible in Jest unit test 

Not visible in browser in `https://editor.swagger.io` (but there is a different similar console error, re: DropdownMenu)

### Describe the bug you're encountering

```
 PASS  test/unit/standalone/topbar-insert/form-objects.js
  ● Console

    console.error
      Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `InsertForm`. See https://fb.me/react-warning-keys for more information.
          in InsertFormInput (created by InsertForm)
          in InsertForm (created by WrapperComponent)
          in WrapperComponent

      30 |   })
      31 |
    > 32 |   return <div> {formRows} </div>
         |          ^
      33 | }
      34 |
      35 | InsertForm.propTypes = {

      at printWarning (node_modules/fbjs/lib/warning.js:33:15)
      at warning (node_modules/fbjs/lib/warning.js:57:20)
      at validateExplicitKey (node_modules/react/lib/ReactElementValidator.js:102:43)
      at validateChildKeys (node_modules/react/lib/ReactElementValidator.js:122:9)
      at Object.createElement (node_modules/react/lib/ReactElementValidator.js:210:9)
      at InsertForm (src/standalone/topbar-insert/forms/components/InsertForm.jsx:32:10)
      at node_modules/react-dom/lib/ReactCompositeComponent.js:303:16
      at measureLifeCyclePerf (node_modules/react-dom/lib/ReactCompositeComponent.js:73:12)

```

### To reproduce...

1. Run unit test in Jest: `test/unit/standalone/topbar-insert/form-objects.js`
2. all tests pass, but see print errors

### Expected behavior

No console error/warnings.

### Additional context or thoughts

common React list error that should be fixed.

**Comment by kevinsmithwebdev** [comment]
I can grab this.

**Comment by kevinsmithwebdev** [comment]
I'm just looking for some confirmation that's cool. I'm still fairly new to open source and am completely new to the repo so I don't want to step on any toes.

**Comment by tim-lai** [comment]
@kevinsmithwebdev Of course! All contributions are welcome.

**Comment by kevinsmithwebdev** [comment]
Or I guess people just sneak in and take it from you.
