### ISSUE TITLE
Can't edit/preview multiple Swagger docs (even in separate tabs)

### ISSUE THREAD

**Issue by maxlinc** [swagger-api/swagger-editor#223]
I'm guessing the Swagger editor uses something like HTML5 local storage, because it seems to remember my files between visits.

I wanted to edit/preview two related Swagger documents. I'm okay with using two separate browser tabs for this (as opposed to the editor itself having a "workspace" feature for editing multiple Swagger docs), but if I paste a Swagger document into one tab and then a different Swagger document into another tab, the second document overwrites the first when I refresh or preview the first tab.

**Comment by MarqueIV** [comment]
Guess this is dead. It's now 2018 and this issue still persists.
