### ISSUE TITLE
component/examples Value field should not be shown

### ISSUE THREAD

**Issue by paggers** [swagger-api/swagger-editor#2250]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome,
 - Version: 86
 - Method of installation: installer
 - Swagger-Editor version: https://editor.swagger.io/#
 - Swagger/OpenAPI version: OpenAPI 3.0

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.1
info:
  title: bug
  version: 1.0.0
servers:
- url: /v1
paths:
  /endpoint:
    get:
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              examples:
                example1:   # Example 1
                  $ref: '#/components/examples/example1'
components:
  schemas:
    Response:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Example'
      required:
        - items
    Example:
      type: object
      properties:
        entityId:
          type: number
          example: 22222
        entityName:
          type: string
          example: Tier 1
  examples:
    example1:
      value:
        type: TIER
        entityId: 1234
        entityName: tier1
        snapshots: 
          $ref: '#/components/examples/example2'
    example2:
      value:
        execTime: 11111
```

### Describe the bug you're encountering
On editor.swagger.io whenever I reference example2 from another example1 within components.examples scope then I see the "value" field appear for example2.

### To reproduce...
Use the example YAML file in editor.swagger.io

### Expected behavior
example2 wouldn't have a value field, only execTime (depth of 1 instead of 2)

### Screenshots
example2 with value (no error):
[https://imgur.com/veJC0B9](url)

example2 without value (shows error and desired output):
[https://imgur.com/nIdEmkh](url)

### Additional context or thoughts
Whenever I remove the value field I see an error stating "should not have additional properties" yet the UI on the right shows the desired output.

**Comment by hkosova** [comment]
```yaml
  examples:
    example1:
      value:
        type: TIER
        entityId: 1234
        entityName: tier1
        snapshots: 
          $ref: '#/components/examples/example2'   # <------
```
`$ref` cannot be used inside example values themselves. The entire value must be specified inline, like so:

```yaml
  examples:
    example1:
      value:
        type: TIER
        entityId: 1234
        entityName: tier1
        snapshots: 
          execTime: 11111    # <-----
```

The issue here is that Swagger UI/Editor attempts to resolve `$ref` in example values, this issue is tracked here:
https://github.com/swagger-api/swagger-ui/issues/5625

**Comment by hkosova** [comment]
Closing in favor or swagger-api/swagger-ui#5625.
