### ISSUE TITLE
read:pets and write:pets are hardcoded

### ISSUE THREAD

**Issue by fctorial** [swagger-api/swagger-editor#2251]
https://prnt.sc/v94i4u

Example Swagger/OpenAPI definition:
https://gist.github.com/fctorial/76d9d74bc250d54253350448ee147558

### To reproduce...
Go to `editor.swagger.io`, paste the above yaml and click on `Authorize` button.

**Comment by hkosova** [comment]
@fctorial I cannot reproduce the issue in the latest https://editor.swagger.io. Can you check if it's fixed for you too?
