### ISSUE TITLE
Available Authorizations popup is empty

### ISSUE THREAD

**Issue by fctorial** [swagger-api/swagger-editor#2252]
Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.3
info:
  title: API
  description: API
  version: 1.0.0
paths:
  /login:
    post:
      security:
        - token: []
      summary: Get an access token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
      responses:
        200:
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  expires_at:
                    type: string
                    format: date-time
components:
  securitySchemes:
    token:
      type: apiKey
      in: header
      name: Authorization
      description: Access token

```

### Describe the bug you're encountering
Available authorization popup that appears when you click on lock icon is empty even though authentication has been specified for an endpoint.

### To reproduce...
Paste the above yaml in `editor.swagger.io` and click on lock icon of `POST /login` endpoint

### Expected behavior
Specified security schemes should be displayed

### Screenshots
https://prnt.sc/v94phu

**Comment by hkosova** [comment]
@fctorial I cannot reproduce the issue in the latest https://editor.swagger.io. Can you check if it's fixed for you too? If you still see the issue, let us know your browser and OS.

**Comment by Teut2711** [comment]
![image](https://github.com/swagger-api/swagger-editor/assets/40588378/1140635d-89b2-4342-8ac7-047d145e7b6a)
