### ISSUE TITLE
Dynamically adding auth tokens to headers

### ISSUE THREAD

**Issue by carlskii** [swagger-api/swagger-editor#230]
Hi,

My API requires that I first get an auth token by calling an auth method within the API. This returns a token e.g. `1035837f-f452-c474-71d5-ee6b95bf1075`. This token needs to be added to a header `authorization` for all subsequent API calls. e.g. 

I've read through the docs, but its not obvious to me if this can be achieved.

**Comment by skylve** [comment]
Hello,

Any update on this feature ?

**Comment by mohsen1** [comment]
This is done
