### ISSUE TITLE
mock server throwing validation error, even though the structure looks fine in OpenAPI file.

### ISSUE THREAD

**Issue by wadakatu** [swagger-api/swagger-editor#2300]
### Q&A
 - OS: macOS catalina version 10.15.6
 - Browser: Safari and Google Chrome
 - Version: Safari: 14.0 Google Chrome: 87.0.4280.88(Official Build)
 - Method of installation: Docker
 - Swagger-Editor version: latest
 - Swagger/OpenAPI version: Openapi 3.0.3

### Content & configuration

1. Built mock-server using Prism
2. Push try it out -> execute button in swagger-editor
3. be able to see error response. 

Swagger/OpenAPI definition:
```yaml
openapi: 3.0.3
...

paths:
  /pets:
    post:
      operationId: postPet
      tags:
      - pet
      summary: call my pet.
      description:
        call my favorite pet.
      requestBody:
        description:
         give pet's name and pet's age.
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  pet_name:
                    $ref: '#/components/schemas/PetName'
                  pet_age:
                    $ref: '#/components/schemas/PetAge'
              example:
              - pet_name: 'pochi'
                 pet_age: 5
      responses:
        200:
          description: successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                 result:
                  $ref: '#/components/schemas/Result'
        400:
          $ref: '#/components/responses/InvalidErrorResponse'
        403:
          $ref: '#/components/responses/AuthorizationTokenErrorResponse'
        500:
          $ref: '#/components/responses/ExceptionResponse'

...
components:
  schemas:
    PetName:
      title: pet_name
      type: string
      example: pochi

    PetAge:
      title: pet_age
      type: integer
      format: int32
      example: 5
```

### How can we help?

I've created an OpenAPI definition for for my APIs.
Moreover, I built a mock-server using Prism to make sure that what I defined as successful response returns correctly, but all I got have been validation error response.

If I sent the following request to the Prism mock server (line breaks added for readability)

```terminal
curl -X POST "http://hogehoge/swagger-mock/pets"
     -H  "accept: application/json"
     -H  "Authorization: Bearer aaa"
     -H  "Content-Type: application/json"
     -d "[{\"pet_name\":\"pochi\",\"pet_age\":5}]"
```

it returns 400 error response. I assume that the response happens because of structural failure about requestBody's schema and example.

However, I am not sure what the problem is.

Thank you in advance.

**Comment by hkosova** [comment]
It's an issue with Prism not with Swagger Editor.

Open an issue in the Prism repo:
https://github.com/stoplightio/prism
