### ISSUE TITLE
Error when running SwaggerEditorBundle function the second time

### ISSUE THREAD

**Issue by janserlemesf** [swagger-api/swagger-editor#2339]
Hi. I'm using swagger-editor in my Angular Application and I have been some problems.

When I call the SwagerEditorBundle it works on first time.

`SwaggerEditorBundle({
        dom_id: '#swagger-editor',
        layout: 'StandaloneLayout',
        presets: [SwaggerEditorStandalonePreset],
      })`
      
 But when I close my Angular Component and try call again I get the following errors:
 
 `Worker caught an error: Error: schema with key or id "openapi-2.0" already exists
    at P (a1c06d48-879a-4af6-9ab6-789248cee341:2)
    at g.addSchema (a1c06d48-879a-4af6-9ab6-789248cee341:2)
    at t.value (a1c06d48-879a-4af6-9ab6-789248cee341:2)
    at a1c06d48-879a-4af6-9ab6-789248cee341:2
    at a1c06d48-879a-4af6-9ab6-789248cee341:2
    at a1c06d48-879a-4af6-9ab6-789248cee341:2
    at a1c06d48-879a-4af6-9ab6-789248cee341:2`
 
 `ERROR Error: Uncaught (in promise): Error: schema with key or id "openapi-2.0" already exists
Error: schema with key or id "openapi-2.0" already exists
    at t._callbacks.<computed> (swagger-editor-bundle.js:2)
    at i (swagger-editor-bundle.js:2)
    at Worker.<anonymous> (swagger-editor-bundle.js:2)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:27137)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:480)
    at invokeTask (zone-evergreen.js:1621)
    at Worker.globalZoneAwareCallback (zone-evergreen.js:1647)
    at resolvePromise (zone-evergreen.js:798)
    at zone-evergreen.js:705
    at t._callbacks.<computed> (swagger-editor-bundle.js:2)
    at i (swagger-editor-bundle.js:2)
    at Worker.<anonymous> (swagger-editor-bundle.js:2)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:27137)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:480)`
    
    Can you help me? Please.

**Comment by tim-lai** [comment]
Hi, swagger-editor should be instantiated only once. Based on the error message, it appears that swaggere-editor is trying to append a duplicate definition to its original, which will cause a parser error on duplicate keys.

**Comment by janserlemesf** [comment]
Hi, thanks for the answer.
 Is it possible to change the specification without a new instance?

**Comment by hardythaker** [comment]
@janserlemesf - You got any solution for this?

**Comment by rijuvf** [comment]
sorry to post after a long time, i faced same issue in my react application, "Worker caught an error: Error: schema with key or id "openapi-2.0" already exists" , just wondering how to render this second time without any error, thing is after this error the validation is not happening as stated above, it skips some validation. Any input is very helpful.

<img width="593" alt="Screenshot 2021-09-28 at 08 47 00" src="https://user-images.githubusercontent.com/70268136/135036962-a703ca09-bef2-492b-a714-892440944616.png">

**Comment by char0n** [comment]
@rijuvf are you using Angular to integrate SwaggerEditor as well?

**Comment by rijuvf** [comment]
No I am using react @char0n

**Comment by adilorenzodema** [comment]
Hi, I've the same error on Angular:
![image](https://user-images.githubusercontent.com/77487424/163172103-e9dabcdd-ccf2-41ba-bc25-e73366736634.png)

Is there a solution for this?

**Comment by rijuvf** [comment]
havent found any solutions yet, this is really annoying to see, can you open a PR for this, as they suggest?

**Comment by adilorenzodema** [comment]
I opened an issued related this problem, but I haven't nothing answer.

**Comment by adilorenzodema** [comment]
> @rijuvf as I mentioned in [#2339 (comment)](https://github.com/swagger-api/swagger-editor/issues/2339#issuecomment-906961895), we need to terminated all workers and do some cleanup after the editor component is unmounted.
> 
> The cleanup functionality currently doesn't exist in the editor. We'd need to implement it. Feel free to submit a PR.

Sorry, can you view this issue? https://github.com/swagger-api/swagger-editor/issues/3016

**Comment by adilorenzodema** [comment]
> WebWorker API has a way of terminating - https://developer.mozilla.org/en-US/docs/Web/API/Worker/terminate
> 
> We could possibly terminate the worker if the the main component unmounts.

Could help me with this error?

**Comment by char0n** [comment]
I've issued a following [PR](https://github.com/swagger-api/swagger-editor/pull/3577) that exposes worker life-cycle management to the plugin system via `getWorker` and `terminateWorker` redux thunks. Example of using this:

```js
// instantiation
const editor = SwaggerEditorBundle({
  dom_id: '#swagger-editor',
  layout: 'StandaloneLayout',
  presets: [
    SwaggerEditorStandalonePreset
  ],
  queryConfigEnabled: true,
});

// after the SwaggerEditor have been disposed of, terminate the worker manually
editor.jsonSchemaValidatorActions.terminateWorker();
```

Awaiting feedback, if this is sufficient solution for this issue.

**Comment by char0n** [comment]
The change described in https://github.com/swagger-api/swagger-editor/issues/2339#issuecomment-1286716712 realeased in [v4.5.0](https://github.com/swagger-api/swagger-editor/releases/tag/v4.5.0).
