### ISSUE TITLE
In v3.15.0 swagger-ui dep was not bumped to v3.39.0

### ISSUE THREAD

**Issue by mathis-m** [swagger-api/swagger-editor#2341]
According to the [release notes v3.15.0](https://github.com/swagger-api/swagger-editor/releases/tag/v3.15.0) the swagger-ui version was bumped to v3.39.0 but the [package.json](https://github.com/swagger-api/swagger-editor/blob/master/package.json#L91) was not update properly.

**Comment by tim-lai** [comment]
Fixed in [v3.15.2](https://github.com/swagger-api/swagger-editor/releases/tag/v3.15.2)
