### ISSUE TITLE
Info section crashed by relative URLs in info.termsOfService and/or externalDocs.url

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-editor#2357]
The issue seems to be specific to Swagger Editor, I'm not sure if it affects Swagger UI.

### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome latest
 - Method of installation: https://editor.swagger.io
 - Swagger-Editor version: 3.15.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Describe the bug you're encountering
If the API definition contains `info.termsOfService` and/or `externalDocs.url` with a relative URL value, Swagger Editor's UI panel cannot render the "Info" section.

The console error is:
```
TypeError: Failed to construct 'URL': Invalid base URL
    at lt (swagger-ui-es-bundle.js:2)
    at r.value (swagger-ui-es-bundle.js:2)
    at r.D.t.render (swagger-ui-es-bundle.js:2)
    at u._renderValidatedComponentWithoutOwnerOrContext (swagger-ui-es-bundle.js:2)
    at u._renderValidatedComponent (swagger-ui-es-bundle.js:2)
    at u.performInitialMount (swagger-ui-es-bundle.js:2)
    at u.mountComponent (swagger-ui-es-bundle.js:2)
    at Object.mountComponent (swagger-ui-es-bundle.js:2)
    at J.mountChildren (swagger-ui-es-bundle.js:2)
    at J._createInitialChildren (swagger-ui-es-bundle.js:2)
```

### To reproduce...
1. Go to https://editor.swagger.io.
2. Delete the default spec and paste the following instead:
```yaml
openapi: 3.0.3
info:
  title: TOS
  version: 1.0.0
  termsOfService: /tos
externalDocs:
  url: /docs
paths: {}

# Uncommenting these lines fixes the issue
# servers:
#   - url: https://example.com
```

### Expected behavior
API info section should be rendered properly.

The Editor should probably use its own URL as the base URL for resolving relative URLs in the spec.

### Screenshots

![image](https://user-images.githubusercontent.com/8576823/104294929-e2cdc900-54d0-11eb-8518-6e4840e469de.png)

**Comment by tim-lai** [comment]
This is also a problem in swagger-ui@3.40.0. Loading the sample yaml results in same error. Original ticket uses swagger-ui@3.39.0

**Comment by tim-lai** [comment]
Closing ticket and moving to: https://github.com/swagger-api/swagger-ui/issues/6863
