### ISSUE TITLE
two equivalent forms of any type end up to different preview

### ISSUE THREAD

**Issue by zimtsui** [swagger-api/swagger-editor#2416]
according to [docs](https://swagger.io/docs/specification/data-models/data-types/#any), 

```yaml
components:
    schemas:
        JsonValue1:
            nullable: true
            anyOf:
            - type: string
            - type: number
            - type: integer
            - type: boolean
            - type: array
              items: {}
            - type: object
```

and

```yaml
components:
    schemas:
        JsonValue2:
            nullable: true
```

are equivalent.

but when `JsonValue1` and `JsonValue2` are properties of another object, their preview differ.

see this example:

```yaml
openapi: 3.0.1
info:
    title: Bug
    version: 0.0.1
paths:
    /1:
        get:
            responses:
                200:
                    description: '1'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ValueAndTime1'
    /2:
        get:
            responses:
                200:
                    description: '2'
                    content: 
                        application/json: 
                            schema: 
                                $ref: '#/components/schemas/ValueAndTime2'
components:
    schemas:
        UnixTime:
            type: integer
            format: int64
        JsonValue1:
            nullable: true
            anyOf:
            - type: string
            - type: number
            - type: integer
            - type: boolean
            - type: array
              items: {}
            - type: object
        JsonValue2:
            nullable: true
        ValueAndTime1:
            type: object
            properties:
                value: 
                    $ref: '#/components/schemas/JsonValue1'
                time: 
                    $ref: '#/components/schemas/UnixTime'
        ValueAndTime2:
            type: object
            properties:
                value: 
                    $ref: '#/components/schemas/JsonValue2'
                time: 
                    $ref: '#/components/schemas/UnixTime'
```

copy it to [https://editor.swagger.io/](https://editor.swagger.io/), and see their *Example Value* of the responses.

one is:

```json
{
  "value": "string",
  "time": 0
}
```

the other one is:

```json
{
  "time": 0
}
```

**Comment by tim-lai** [comment]
This is a swagger-ui issue. At the minimum, it is probably incorrect assumption to default to the first `anyOf` type. fyi @mathis-m

**Comment by mathis-m** [comment]
@tim-lai is this really a bug?
Was this working before? 
I think the proper solution for this would be to default to type to string if not defined. This would result in a stable behavior too. 
https://github.com/swagger-api/swagger-ui/blob/master/src/core/plugins/samples/fn.js#L192

**Comment by mathis-m** [comment]
another option would be to resolve this kind of shorthand definition in swagger-js. @tim-lai what would be the correct place of integrating this?

**Comment by tim-lai** [comment]
@mathis-m petstore3.swagger.io is behind on versions (and I put in a request to get it updated a ~week ago). This issue is reproducible on editor.swagger.io and current local swagger-ui@3.45.1. 

![se-2416](https://user-images.githubusercontent.com/12902658/112395816-56076e80-8cbc-11eb-8108-b8c29cc1e7c3.png)

I think for the example value, I agree we should at least give a hint of `anyOf`. For this specific case, the proposed string `Can be any value - string, number, boolean, array or object` works, though we might as well handle the `anyOf` subset. For simplicity, I would keep the hint as a string value.

For the schema viewer, it's a separate issue, but agree it should get looked at as well.

**Comment by mathis-m** [comment]
@tim-lai actually I meant to integrate the proposed string into the schema viewer not in the sample value.
Rather then creating a new sample value case I would propose to just infer the type as string and let the generator continue like it did before. AS we already infer type for some cases this sounds like a consistent way to integrate it.

**Comment by mathis-m** [comment]
> @mathis-m petstore3.swagger.io is behind on versions (and I put in a request to get it updated a ~week ago). This issue is reproducible on editor.swagger.io and current local swagger-ui@3.45.1.

yep just wanted to show the different behavior for:
```yaml
components:
  schemas:
    AnyValue:
      anyOf:
        - type: string
        - type: number
        - type: integer
        - type: boolean
        - type: array
          items: {}
        - type: object
```
3.30.0:
no type => no sample
anyOf => no sample

some versions later I added anyOf support
no type => no sample
anyOf  => anyOf[0]
https://github.com/swagger-api/swagger-ui/pull/7117:
no type => anyOf[0]
anyOf  => anyOf[0]
