### ISSUE TITLE
Incorrectly old tagged version v3.16.6 on dockerhub when latest release is v3.15.9

### ISSUE THREAD

**Issue by dlouzan** [swagger-api/swagger-editor#2501]
### Describe the bug you're encountering
There is a tagged version `v3.16.6` on the official docker hub https://hub.docker.com/r/swaggerapi/swagger-editor that does not correspond to any released version (latest release as of today is `v3.15.9`). According to dockerhub this was created 2 years ago (!) (see screenshot below).

We are using [renovatebot](https://github.com/renovatebot/renovate) for automating our dependencies update and this tricked us into deploying an apparently very old, unsupported version. I don't even know which code is in that version actually.

### Expected behavior
My understanding is that this tag should be deleted.

### Screenshots
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/223870/110959313-da1d3600-834d-11eb-9101-cc64842352c7.png">

### Additional context or thoughts
Wonder if this is an oversight on CI or a supply-chain attack? Hopefully we haven't deployed hacked code 😅

**Comment by tim-lai** [comment]
@dlouzan Thanks for the report! The incorrect old tagged version has been removed.

**Comment by dlouzan** [comment]
@tim-lai I'm assuming then this was an oversight, thanks for the fix!
