### ISSUE TITLE
Enum not showing a select field

### ISSUE THREAD

**Issue by DannyBen** [swagger-api/swagger-editor#256]
I am not sure if I should post this duplicate issue or not. I also posted it as an [issue on the swagger-ui repo](https://github.com/swagger-api/swagger-ui/issues/736).

It is [my understanding](http://stackoverflow.com/questions/27050635/swagger-ui-parameter-as-list-instead-of-text-input/27058161) that the code below should produce a select field of values to choose from. Right now it generates a text field.

	paths:
	  /users:
	    get:
	      parameters:
	        - name: status
	          in: query
	          type: string
	          enum:
	            - online
	            - offline

**Comment by calfzhou** [comment]
+1 ~

**Comment by ethaizone** [comment]
+1

**Comment by mohsen1** [comment]
Should get fixed by #384
