### ISSUE TITLE
Is it possible to run client generation via swagger editor in offline mode?

### ISSUE THREAD

**Issue by thomaslprr** [swagger-api/swagger-editor#2668]
### Q&A 
 - OS: macOS
 - Browser: chrome
 - Method of installation: Docker
 - Swagger-Editor version: last
 - Swagger/OpenAPI version: Swagger 2.0 

### How can we help?
I would like to deploy swagger-editor-dist via Docker but can't find any indication on the commands to do so?
Is it possible and if so how? 

Because the problem with classic swagger-editor is that it requires an internet connection to generate the client. 
I would like to be able to use the services of swagger editor (client generation) without a connection and preferably using docker.

Thank you very much in advance,
Respectfully

**Comment by tim-lai** [comment]
Hi, it is not possible for Swagger Editor to run client generation without an internet connection. The generator is a standalone http service.
