### ISSUE TITLE
Generate Server isn't working

### ISSUE THREAD

**Issue by ashutoshpanda31** [swagger-api/swagger-editor#2674]
Hey! So I was working with Swagger Editor, and I loaded in a YAML file, however, when I clicked "Generate Server," and clicked in "Spring"(as I am using spring boot), it didn't do anything! 
![image](https://user-images.githubusercontent.com/85246117/121298480-cd56a280-c8a8-11eb-8336-6dfaea8f7528.png)

As you see in the image, it wasn't even even a link. My colleagues also tried it from their end, but they were experiencing the same issue. Please take a look, thank you!

**Comment by tim-lai** [comment]
Hi, the generator server -> spring works for me, via https://editor.swagger.io. The visual UI captured in the screenshot is valid, i.e. what I see/saw.

**Comment by AbelRuol** [comment]
You can download a .zip but its an empty/invalid one.

**Comment by clauslor** [comment]
+1

> You can download a .zip but its an empty/invalid one.

**Comment by Cantasura** [comment]
this also happens to (mostly) every client generated zip file.
zip files have a size of 1KB

**Comment by jdforjan** [comment]
This is still not working for generating client or server

**Comment by stephen-mi11er** [comment]
Same issue. This is a critical bug!

**Comment by 44215341** [comment]
Please solve it as soon as possible

**Comment by andy380743909** [comment]
> You can download a .zip but its an empty/invalid one.

+1

**Comment by Cantasura** [comment]
Any updates?

**Comment by tim-lai** [comment]
I just tried this again, with a definition with a validation error... still able to download a `spring-server-generated.zip` (12KB). Note that I was not behind any firewalls for this test. If you are still having trouble, please provide additional information, including reproduceable steps and the OpenAPI definition that you are using. Thanks.

**Comment by tim-lai** [comment]
Ok, another update. I tried using an OpenAPI 2.0 definition, now I can reproduce the `spring-server-generated.zip`! Appears to be an OpenAPI 2.x generator issue.

**Comment by tim-lai** [comment]
Another update... this appears to have been an infrastructure issue, and should now be resolved. I was able to download generated versions for both OpenApi 2.x and 3.0 definitions for both servers and clients. Going to close both #2674 and #2679.

**Comment by Cantasura** [comment]
Tried it with my yaml. Wokrs again.
Thank you very much for fixing :)
