### ISSUE TITLE
Javascript error when empty paths object in OpenAPI description

### ISSUE THREAD

**Issue by jdegre** [swagger-api/swagger-editor#2681]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Firefox 
 - Version: 89.0.1
 - Method of installation: Online (https://editor.swagger.io)
 - Swagger-Editor version: 3.16.3
 - Swagger/OpenAPI version: OpenAPI 3.0.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  title: test
  version: 1.0.0
paths: {}
components:
  schemas:
    test:
      type: object
```

### Describe the bug you're encountering
The browser's development console shows the following error:

![imagen](https://user-images.githubusercontent.com/31138976/122559125-35428100-d03f-11eb-84f3-e989226bb297.png)

### To reproduce...

1. Go to https://editor.swagger.io
2. Paste the OpenAPI description shown above (**_note that the error does not show up yet_**; at this point, the OpenAPI description is rendered correctly on the right pane of the editor)
3. **_Load again the Swagger Editor_** (e.g. hit F5 in the browser))
4. See error in browser's console

### Expected behavior
No errors should show up on the console

**Comment by hkosova** [comment]
This is probably the same issue as #2099.

**Comment by hkosova** [comment]
This was [fixed](https://github.com/swagger-api/swagger-editor/pull/2843) in Swagger Editor [v. 4.0.2](https://github.com/swagger-api/swagger-editor/releases/tag/v4.0.2).
