### ISSUE TITLE
Scroll into-view operation that is being edited currently 

### ISSUE THREAD

**Issue by earth2marsh** [swagger-api/swagger-editor#27]
When I'm working on the summary of a method, I can't see it unless I expand and navigate to the detail view in the html. Ideally, the html knows where you are in the YAML and updates it automatically.

Example:
![phonics](https://cloud.githubusercontent.com/assets/54582/2931281/6de8dbce-d7a1-11e3-86f9-06b9332113a7.png)

**Comment by webron** [comment]
Closing as a very old ticket. Please open a new one if still relevant.
