### ISSUE TITLE
Relative url for openid does not use server url

### ISSUE THREAD

**Issue by dkwakkel** [swagger-api/swagger-editor#2767]
### Q&A (please complete the following information)
 - OS: [windows]
 - Browser: [chrome]
 - Version: 93.0.4577.63 (Official Build) (32-bit)
 - Method of installation: https://editor.swagger.io/# 
 - Swagger-Editor version: 3.52.0
 - Swagger/OpenAPI version: [OpenAPI 3.0.3]

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.3
info:
  title: Test
  version: 1.0.0
servers:
  - url: https://api.example.com/v2
security:
  - openId: []
paths:
  /:
    get:
      tags:
        - Content
      responses:
        '200':
          description: All services of Content Storage Service
components:
  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: /.well-known/openid-configuration
```

### Describe the bug you're encountering
Relative url is not resolved as documented in 'Relative Discovery URL' here: https://swagger.io/docs/specification/authentication/openid-connect-discovery/
(above sample is a working one from the documentation of above url)

### To reproduce...

1. Load above example in https://editor.swagger.io/#. 
2. Watch request (with fiddler or browser debugger) for well-known 
3. It will go to:  https://editor.swagger.io/.well-known/openid-configuration

### Expected behavior
Expected: https://api.example.com/.well-known/openid-configuration

**Comment by char0n** [comment]
Hi @dkwakkel,

Can you please report this issue directly on https://github.com/swagger-api/swagger-ui, and we're going to deal with it there. Swagger-Editor just renders SwaggerUI in the editor window. 

Thanks!

**Comment by dkwakkel** [comment]
Done: https://github.com/swagger-api/swagger-ui/issues/7485
