### ISSUE TITLE
Authorization header should not be shown in UI

### ISSUE THREAD

**Issue by dkwakkel** [swagger-api/swagger-editor#2768]
### Q&A (please complete the following information)
 - OS: [windows]
 - Browser: [chrome]
 - Version: 93.0.4577.63 (Official Build) (32-bit)
 - Method of installation: https://editor.swagger.io/# 
 - Swagger-Editor version: 3.52.0
 - Swagger/OpenAPI version: [OpenAPI 3.0.3]

### Content & configuration

Example Swagger/OpenAPI definition:
```
openapi: 3.0.3
info:
  title: Test
  version: 1.0.0
servers:
  - url: https://api.example.com/v2
security:
  - openId: []
paths:
  /:
    get:
      tags:
        - Content
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        '200':
          description: All services of Content Storage Service
components:
  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: /.well-known/openid-configuration
```

### Describe the bug you're encountering
Authorization header is shown in UI, while I expect not as documented in '4.8.12.2 Fixed Fields ' section here: https://spec.openapis.org/oas/v3.1.0:

_If in is "header" and the name field is "Accept", "Content-Type" or "Authorization", the parameter definition SHALL be ignored._

### To reproduce...

1. Load above example in https://editor.swagger.io/#. 
2. Open the GET method: it shows an Authorization header

### Expected behavior
No Authorization header is shown

I am not sure I interpret the spec the right way. Problem I run into is that because there is an openid security definition, after login with it still the authorization header is shown and mandatory to fill while this header will be filed / used by the openid token. I worked around it for now to add 'Parameter(hidden=true)' in the java code by which the 'Authorization' header no longer is generated in the openid spec.

**Comment by char0n** [comment]
Hi @dkwakkel,

Can you please report this issue directly on https://github.com/swagger-api/swagger-ui, and we're going to deal with it there. Swagger-Editor just renders SwaggerUI in the editor window. 

Thanks!

**Comment by dkwakkel** [comment]
Done: https://github.com/swagger-api/swagger-ui/issues/7486
