### ISSUE TITLE
Is generated code licensed under the Apache License 2.0?

### ISSUE THREAD

**Issue by tibco-jufernan** [swagger-api/swagger-editor#2774]
### How can we help?

Hi all, quick question: is code generated by the Swagger Editor licensed under the Apache License 2.0? Is it licensed at all?

For example, if I go to [https://editor.swagger.io/](https://editor.swagger.io/), paste in some YAML that I've written, and generate a server/client, how is the code that's downloaded licensed?

**Comment by hkosova** [comment]
Code generation is done by [Swagger Codegen](https://github.com/swagger-api/swagger-codegen/). Here's what it says about the code license:

https://github.com/swagger-api/swagger-codegen/#license-information-on-generated-code

> * Generated code is intentionally _not_ subject to the parent project [Swagger Codegen] license [Apache 2.0]
> 
> When code is generated from this project [Swagger Codegen], it shall be considered AS IS and owned by the user of the software. There are no warranties--expressed or implied--for generated code. You can do what you wish with it, and once generated, the code is your responsibility and subject to the licensing terms that you deem appropriate.

**Comment by tibco-jufernan** [comment]
Thank you for clearing this up!
