### ISSUE TITLE
Swagger Editor page becomes unresponsive when the file is larger

### ISSUE THREAD

**Issue by SanduDS** [swagger-api/swagger-editor#2778]
### Q&A (please complete the following information)
 - OS: Ubuntu
 - Browser: chrome
 - Version: latest
 - Method of installation: npm
 - Swagger-Editor version: 3.16.3
 - Swagger/OpenAPI version: Swagger 2.0
### Content & configuration

Example Swagger/OpenAPI definition:

https://assets.zuora.com/zuora-documentation/swagger3_collect.yaml

### Describe the bug you're encountering
When converting from swagger 2.0 to openAPI 3.0.0, the web page becomes unresponsive and finally, it is crashed.

### To reproduce...

1. Go to https://assets.zuora.com/zuora-documentation/swagger3_collect.yaml
2. Download the file
3. Try to convert from 2.0 to openapi 3.0.0

### Expected behavior
conversion from swagger 2.0 to openapi 3.0.0

**Comment by char0n** [comment]
@SanduDS,

I'm not sure I understand.

The file https://assets.zuora.com/zuora-documentation/swagger3_collect.yaml contains OAS 3.0 definition.

What do you mean by `Try to convert from 2.0 to openapi 3.0.0`?

**Comment by SanduDS** [comment]
Closing as this is already fixed

**Comment by murisfurder** [comment]
No it isn't 
try opening the Redfish openapi definition and watch the editor choke on itself

really makes the whole thing useless

**Comment by char0n** [comment]
@murisfurder I've just tried https://opendev.org/airship/go-redfish/raw/branch/master/spec/openapi.yaml on https://editor.swagger.io/ and https://editor-next.swagger.io/ and was unable to reproduce. Can you please specify more details? Thanks

**Comment by murisfurder** [comment]
The schema you used is an outdated broken version without annotations

Please use the correct normative version included in DSP8010	2023.3
