### ISSUE TITLE
OAS3: Tags containing description and ExternalDocs should be aligned differently.

### ISSUE THREAD

**Issue by wmeijers** [swagger-api/swagger-editor#2865]
If I have a Tags definition containing descriptive text and an ExternalDocs section like so (sorry for the Dutch text):

![image](https://user-images.githubusercontent.com/14923836/148769462-245d25c0-e8f3-4da6-8480-4f2e1cb6a0d1.png)

This results in a rendering that is very hard to read since all fields are displayed on the same line, resulting in a very narrow text column:

![image](https://user-images.githubusercontent.com/14923836/148769250-ecb14291-2f4c-4f56-84fe-974fa5c3e3e0.png)

Readability can be improved by putting the ExternalDocs info on a separate line **below** the description. 

Regards,
Wouter Meijers

**Comment by hkosova** [comment]
Hi @wmeijers, thanks for the feedback. This issue is tracked in https://github.com/swagger-api/swagger-ui/issues/7305 so I'll close this one as a duplicate. Please follow the linked issue for status updates.
