### ISSUE TITLE
Alignment issue editor.swagger.io

### ISSUE THREAD

**Issue by arthur-edsn** [swagger-api/swagger-editor#2872]
- OS: Windows 10
 - Browser: Chrome 
 - Version: 97.0.4692.71
 - Method of installation: Website editor.swagger.io
 - Swagger-Editor version: Unknown
 - Swagger/OpenAPI version: 3.0.3

### Example Swagger/OpenAPI definition:
```yaml
{
.......
"tags": [
    {
      "name": "powerGeneratingModules",
      "description": "Een installatie waarin primaire energie wordt omgezet in elektrische energie en die bestaat uit één of meerdere elektriciteitsproductie-eenheden die via één aansluitpunt met een netwerk zijn verbonden",
      "externalDocs": {
        "description": "Artikel 2 bullet10",
        "url": "https://eur-lex.europa.eu/"
      }
    }
........
}
```

### Steps to reproduce the behavior:
1. Go to editor.swagger.io
2. Paste a openAPI schema with tags containing a long name, long description (with an externalDocs object containing a description and a long URL)
3. If asked to transform to YAML, choose 'no'
4. The tags.description is shown compressed (see attached image):

![swagger](https://user-images.githubusercontent.com/46195281/150096629-0cee7e6d-b1b4-4776-b420-c89ddecdfc46.png)

### Expected behavior
1. Go to editor.swagger.io
2. Paste a openAPI schema with tags containing a long name, long description (with an externalDocs object containing a description and a long URL)
3. If asked to transform to YAML, choose 'no'
4. The formatting of the tags section is as follows (proposal)

![image](https://user-images.githubusercontent.com/46195281/150099217-02e167e0-172e-4af0-bf69-a5f15c44d5d2.png)

### Additional context or thoughts
In the proposal image the link is shown as HTML link, or as plain text description + plain text url

**Comment by hkosova** [comment]
Hi @arthur-edsn, thanks for the feedback. This issue with tag description formatting is tracked in swagger-api/swagger-ui#7305 so I'll close this one as a duplicate. Please feel free to add your design proposal to the linked issue.
