### ISSUE TITLE
Response schema with type "file" throws error

### ISSUE THREAD

**Issue by newmanw** [swagger-api/swagger-editor#292]
If I am reading this correctly:

https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#responseObject

This should be valid right:

```yaml
 /pets/{id}.zip:
    get:
      description: Returns a zip file of pets
      operationId: getPetArchiveById
      produces:
        - application/zip
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        "200":
          description: form response
          schema:
            type: file
```

Throws a validation error on type: file for schema.

**Comment by webron** [comment]
That's a known issue (for me) and it's not related to the editor, it's related to swagger-spec. There's no open issue there about it there, but it's on my to-do list of fixes.

**Comment by newmanw** [comment]
Cool thanks @webron.

**Comment by webron** [comment]
For tidiness, you should probably open an issue on swagger-spec and track it from there. I doubt I'll remember updating here when it is fixed. Of course, you can reference from there to this issue.
