### ISSUE TITLE
Fail opening the application after fixing some install issues

### ISSUE THREAD

**Issue by Urik** [swagger-api/swagger-editor#296]
I'm using Windows 7 Pro, in English. I cloned the repo, did npm start, and got some EEXIST errors. After deleting those files in npm-cache I did npm start, and got 
>> Loading "imagemin.js" tasks...ERROR
>> Error: Cannot find module 'imagemin-gifsicle'
After an npm install imagemin-gifsicle and npm start I got 
Loading "imagemin.js" tasks...ERROR
>> Error: Cannot find module 'imagemin-gifsicle'

I did npm install imagemin-gifsicle, and the application seems to boot up successfully. However, the browser window remains blank after it's opened, and in the console I get these JS errors:

>> Failed to load resource: the server responded with a status of 404 (Not Found): at YAML.js, line 44
Uncaught Error: [$injector:nomod] Module 'schemaForm' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.2/$injector/nomod?p0=schemaForm

>> Uncaught Error: [$injector:modulerr] Failed to instantiate module PhonicsApp due to:
Error: [$injector:modulerr] Failed to instantiate module schemaForm due to:
Error: [$injector:nomod] Module 'schemaForm' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.2/$injector/nomod?p0=schemaForm
    at http://127.0.0.1:9000/bower_components/angular/angular.js:80:12
    at http://127.0.0.1:9000/bower_components/angular/angular.js:1764:17
    at ensure (http://127.0.0.1:9000/bower_components/angular/angular.js:1688:38)
    at module (http://127.0.0.1:9000/bower_components/angular/angular.js:1762:14)
    at http://127.0.0.1:9000/bower_components/angular/angular.js:4030:22
    at forEach (http://127.0.0.1:9000/bower_components/angular/angular.js:339:20)
    at loadModules (http://127.0.0.1:9000/bower_components/angular/angular.js:4014:5)
    at http://127.0.0.1:9000/bower_components/angular/angular.js:4031:40
    at forEach (http://127.0.0.1:9000/bower_components/angular/angular.js:339:20)
    at loadModules (http://127.0.0.1:9000/bower_components/angular/angular.js:4014:5)
http://errors.angularjs.org/1.3.2/$injector/modulerr?p0=schemaForm&p1=Error…2F%2F127.0.0.1%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A4014%3A5)
    at http://127.0.0.1:9000/bower_components/angular/angular.js:80:12
    at http://127.0.0.1:9000/bower_components/angular/angular.js:4053:15
    at forEach (http://127.0.0.1:9000/bower_components/angular/angular.js:339:20)
    at loadModules (http://127.0.0.1:9000/bower_components/angular/angular.js:4014:5)
    at http://127.0.0.1:9000/bower_components/angular/angular.js:4031:40
    at forEach (http://127.0.0.1:9000/bower_components/angular/angular.js:339:20)
    at loadModules (http://127.0.0.1:9000/bower_components/angular/angular.js:4014:5)
    at createInjector (http://127.0.0.1:9000/bower_components/angular/angular.js:3940:11)
    at doBootstrap (http://127.0.0.1:9000/bower_components/angular/angular.js:1451:20)
    at Object.bootstrap (http://127.0.0.1:9000/bower_components/angular/angular.js:1472:12)
http://errors.angularjs.org/1.3.2/$injector/modulerr?p0=PhonicsApp&p1=Error…F%2F127.0.0.1%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A1472%3A12)

Thank you.

**Comment by mohsen1** [comment]
It seems like schemaForm module pushed a version that lacks non-minified code that we use in this project. Please use version `0.7.6` to fix this issue. I'll lock those versions down

**Comment by Urik** [comment]
Thanks Moshe. Sorry for bothering you but I have searched for ways to do it without success, even searched for the word schemaForm in all the project files without finding where the dependencie's download instructions are located. Could you please point me to the location in order to fix it?

**Comment by gtinjr** [comment]
I am having the same error. I am using latest code from master tree.

Uncaught Error: [$injector:modulerr] Failed to instantiate module PhonicsApp due to:
Error: [$injector:modulerr] Failed to instantiate module schemaForm due to:
Error: [$injector:nomod] Module 'schemaForm' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.


I noticed that bower.json already points  to version ~0.7.6 for angular-schema-form.  here is the line from the file

    "angular-schema-form": "~0.7.6"

**Comment by mohsen1** [comment]
Please manually install `angular-schema-form@0.7.6` for now. I'll fix it.

    bower i angular-schema-form@0.7.6

**Comment by gtinjr** [comment]
This did not fix the problem
If I run 
     bower i angular-schema-form#0.7.6
It asks to resolve the following dependency

    1) objectpath#~1.0.4 which resolved to 1.0.5 and is required by angular-schema-form#0.7.6
    2) objectpath#~1.1.0 which resolved to 1.1.0 and is required by Phonics, angular-schema-form#0.7.8Prefix the choice with ! to persist it to bower.json

If I choose 1 I get the following error:
[objectpath: Unable to find suitable version for objectpath]
  code: 'ECONFLICT',
  name: 'objectpath',

If I choose 2 I get the error I was getting before 

Uncaught Error: [$injector:modulerr] Failed to instantiate module PhonicsApp due to:
Error: [$injector:modulerr] Failed to instantiate module schemaForm due to:

**Comment by mohsen1** [comment]
It's a bug in recent push of `angular-schema-form`. I've asked them to push the missing file back. It will get fixed when they push a fixed version.

**Comment by mohsen1** [comment]
Meanwhile you can update your bower json to explicitly use `0.7.6`. No `~`

**Comment by gtinjr** [comment]
Ok, rm node_modules
change bower.json
angular-schema-form to 0.7.6
change bower.json
objectpatch to ~1.0.4
npm start
then it works

Thx

**Comment by mingfang** [comment]
+1

**Comment by mingfang** [comment]
confirmed fixed. Thank you!
