### ISSUE TITLE
Add / fix documentation

### ISSUE THREAD

**Issue by x2b** [swagger-api/swagger-editor#298]
I have been trying to work with the editor for an hour now and I have failed miserably... I noticed the following problems, you seem to be aware of at least a couple of them:

- There is no documentation regarding what constitutes a "number". Is this a (signed) floating point ?!
- There is no example on how to specify path parameters (it should be /path/#{parameter}:)
- The entire section on "Definitions Object"s is missing, in particular I would like to build definitions with references, i.e. A type "Request" consists of two types "Header" which in turn consist of... I don't know if that is possible but I do know that with a broken API documentation I am not likely to find out.
- The error messages displayed in the editor are not exactly helpful, for instance there is no reference to a line number in the editor

On http://swagger.io/ you *prominently* guide potential users of your software to a website which looks to be in early beta stage. If you had no working backend (and if you commented on the state of the website) this would be adequate but in your case I think it just serves to annoy people needlessly. I would suggest that you take some kind of action...

I am referring to the documentation found at https://github.com/reverb/swagger-spec/blob/master/versions/2.0.md#schemaObject

**Comment by webron** [comment]
The spec itself documents the primitive [data types](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#data-types) as taken from the JSON Schema definition. This in return directs to http://json-schema.org/latest/json-schema-core.html#anchor8 which clearly states the definition of 'number'.

There are several examples included in the editor, some of which contain examples for path parameters (such as the petstore-full).

In the same sample you can see the `Definitions Object` is functional and holds samples for complex objects, including ones that rely on definitions of other objects.

As far as I can see, the error gives you a reference to the line number in the editor, and in fact it is a hyperlink to the relevant line:
![screenshot 2015-01-20 14 57 46](https://cloud.githubusercontent.com/assets/241629/5817464/d05d7706-a0b4-11e4-8a68-c374483f4ab2.png)

You may have mixed your comments as some can be taken to both the spec and the editor. If the points are regarding the spec itself, it would be better to open an issue on the spec's repository. I'm in the process of adding the examples there.

Yes, the software is still under development, especially the support for Swagger 2.0. Nobody is trying to "annoy" anyone. We prefer to make the progress transparent and available to the general public. The tickets people open help us immensely in the development process and sometimes helps us focus our efforts in areas that are more important.

**Comment by x2b** [comment]
Curious, error messages look quite different on my system:

![screen](https://cloud.githubusercontent.com/assets/1513479/5853349/1949d170-a223-11e4-8dc2-754bd0bd844a.png)

**Comment by webron** [comment]
Are you on the latest master version?

**Comment by x2b** [comment]
ok, works now
