### ISSUE TITLE
POST call in https://editor.swagger.io/ keeps on loading...  V4.2.0

### ISSUE THREAD

**Issue by gireeshpolaki** [swagger-api/swagger-editor#2981]
### Q&A ( POST and PUT requests keeping on loading and does not return anything) in V4.2.0 release
 - OS: [WIndows 10]
 - Browser: [chrome]
 - Version: [99]
 - Method of installation: editor.swagger.io
 - Swagger/OpenAPI version: [OpenAPI 3.0]

Steps to reproduce:

open https://editor.swagger.io/ in your browser
open the POST pet accordion
click on "Try it out"
click on "execute"
when you open the browser console, you can see the error message:
TypeError: zt.isPlainObject is not a function
....
swagger-ui-es-bundle-core.js:1:414793

![image](https://user-images.githubusercontent.com/56142222/159649514-5262959b-8710-40a1-b8b0-4c695e7ba279.png)
![image](https://user-images.githubusercontent.com/56142222/159649547-6720ea55-7e1c-4050-983c-6e74b5cb559e.png)

I think this was fixed under swagger-ui repo. Request you to update the swagger-editor as well and initiate a release

**Comment by hkosova** [comment]
Hi @gireeshpolaki, this issue is tracked here:
https://github.com/swagger-api/swagger-ui/issues/7907

Closing as a duplicate.
