### ISSUE TITLE
does the editor supports object inheritance and composition?

### ISSUE THREAD

**Issue by gtinjr** [swagger-api/swagger-editor#300]
I am trying to have a response object inherit from another object.  Is extends keyword supported? if not is there any way to do something similar as described below?

.i.e.
<code>
definitions:
   User:
       properties:
            id:
                type: integer
                format: int64
           name:
                type: string

    UserApplication:
       $extends: '#/definitions/User'
       properties:
            enabled:
                  type: boolean
</code>

**Comment by mohsen1** [comment]
Swagger uses JSON Schema for those objects. JSON Schema [supports extending](http://spacetelescope.github.io/understanding-json-schema/structuring.html#extending) if you want.

**Comment by webron** [comment]
Swagger has its own way to support inheritance, and it's not the one mentioned in the given snippet.
I'm currently working on modifying the spec with clearer examples of what it should look like.

**Comment by gtinjr** [comment]
do you have a quick yaml code snippet that shows how this works? thx

**Comment by webron** [comment]
Unfortunately, not at the moment, no. Hopefully in a few days.
