### ISSUE TITLE
Worker caught an error: Error: schema with key or id "openapi-2.0" already exists

### ISSUE THREAD

**Issue by adilorenzodema** [swagger-api/swagger-editor#3016]
### Content & configuration

Swagger/OpenAPI definition:
I use two valid Yaml files. If you want I can insert it.

### Is your feature request related to a problem?
Yes, it is related to https://github.com/swagger-api/swagger-editor/issues/2339

![image](https://user-images.githubusercontent.com/77487424/163175596-c442a436-7e30-4f81-84ed-74e2c0db1066.png)

### Describe the solution you'd like
It's possible create a clean SwaggerEditorBundle instance function, in order to call it on 'ngOnDestroy' angular function?

**Comment by rijuvf** [comment]
Yes , thanks for creating this, hope for a quicker solution

**Comment by NetanelCohenDev** [comment]
i got the same error how can i fix this?

**Comment by MrKarlsonCloud** [comment]
Yes if author **add** this in their code, we can control worker and finish him in unmount steps

![image](https://user-images.githubusercontent.com/43963099/195874465-92556321-abe0-4151-8f3d-8324adfd1c19.png)

**Comment by char0n** [comment]
I've issued a following [PR](https://github.com/swagger-api/swagger-editor/pull/3577) that exposes worker life-cycle management to the plugin system via `getWorker` and `terminateWorker` redux thunks. Example of using this:

```js
// instantiation
const editor = SwaggerEditorBundle({
  dom_id: '#swagger-editor',
  layout: 'StandaloneLayout',
  presets: [
    SwaggerEditorStandalonePreset
  ],
  queryConfigEnabled: true,
});

// after the SwaggerEditor have been disposed of, terminate the worker manually
editor.jsonSchemaValidatorActions.terminateWorker();
```

Awaiting feedback, if this is sufficient solution for this issue.

**Comment by MrKarlsonCloud** [comment]
It will be perfect @char0n thank you :D

**Comment by Dilo07** [comment]
is it resolve in new version v4.4.4 release?

**Comment by char0n** [comment]
@Dilo07 no, I've issued this PR an hour ago and I'm currently awaiting feedback. Will merge (if I have some feedback that this will help resolve the issue) and release during Monday.

**Comment by Dilo07** [comment]
ok, I'm waiting for you to test the fix release.

**Comment by char0n** [comment]
The change described in https://github.com/swagger-api/swagger-editor/issues/3016#issuecomment-1286716347 released in [v4.5.0](https://github.com/swagger-api/swagger-editor/releases/tag/v4.5.0).

**Comment by Dilo07** [comment]
Now it's fine, thanks!

**Comment by vishalkrishna511** [comment]
![image](https://github.com/swagger-api/swagger-editor/assets/121876940/4d854541-47fd-4599-8d64-1fc40131e865)

facing this issue @char0n
