### ISSUE TITLE
Missing "Convert to OpenAPI 3" command in the online editor https://editor.swagger.io

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-editor#3055]
### Q&A (please complete the following information)
 - OS: Windows 8.1
 - Browser: Chrome, Firefox latest
 - Method of installation: https://editor.swagger.io
 - Swagger-Editor version: 4.2.7
 - Swagger/OpenAPI version: OpenAPI 2.0

### Describe the bug you're encountering
https://editor.swagger.io used to have the "Convert to OpenAPI 3" command in the "Edit" menu when the currently edited spec was OAS2. This command is not there anymore.

This might be a side effect of PRs https://github.com/swagger-api/swagger-editor/pull/3013 and/or https://github.com/swagger-api/swagger-editor/pull/3049.

### To reproduce...
1. Open https://editor.swagger.io in an incognito tab (so that the default Petstore OAS2 spec is loaded).
2. Open the "Edit" menu.

### Actual behavior
The "Edit" menu is missing the "Convert to OpenAPI 3" command.

### Expected behavior
The "Edit" menu contains the "Convert to OpenAPI 3" command.

![](https://i.stack.imgur.com/TF6fT.png)

**Comment by daliborfilus** [comment]
I had to go back to tag v4.2.4 for this to appear.

**Comment by phil-warner** [comment]
Interim options are offered here: https://stackoverflow.com/questions/59749513/how-to-convert-openapi-2-0-to-openapi-3-0
