### ISSUE TITLE
OData path parameter - '$' dollar sign

### ISSUE THREAD

**Issue by espray** [swagger-api/swagger-editor#308]
I am documenting my OData endpoint.  When I defined the OData query options the '$'(dollar sign) character in the parameter name is getting url encoded.
 
```
paths:
  /foo:
    get:
      summary: Load object
      description: Get object by its identifier
      parameters:
        - name: $filter
          in: query
          type: string
      responses:
        200:
          description: object loaded
```

The above definition produces the below url when i click 'Try this option'
`GET https://api.foobar.com/foo?%24filter=Name+eq+'Milk' HTTP/1.1`

The '$' is "reversed" but valid.
http://tools.ietf.org/html/rfc3986#section-2

Also '$' are used in OData specification, see: http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part2-url-conventions.html

**Comment by mohsen1** [comment]
There might be some backend that expect query string to be encoded.

Note to self: If anyone faced an issue with encoded query params an opened an issue here, we can have a boolean option for decode/encode query string
