### ISSUE TITLE
Problems in stored authentication

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-editor#311]
When change a security the stored authentication remains unchanged

**Comment by iflamed** [comment]
is it has been fixed by commit 59f783f609bb7eec67a8c38776c9e2966370485d ?

**Comment by mohsen1** [comment]
@iflamed no. That is a different issue.

**Comment by iflamed** [comment]
I change the security value of api_key , the stored authentication changed also. It seem to be fixed. Is there anything wrong?

**Comment by mohsen1** [comment]
Steps to reproduce:

1. open security example
2. authenticate `internalApiKey`
3. rename ` internalApiKey` to something else
4. rename back `internalApiKey` to it's original name

Notice that the Security is authenticated already

**Comment by iflamed** [comment]
@mohsen1 I have reproduced it. But i don't think it is a bug, it's a feature. How do you think?

**Comment by mohsen1** [comment]
Well, int that case it looks like a bug and a feature at the same time! But try this instead:

1. Authenticate  `internalApiKey`
2. Change the `name` property of `internalApiKey`
3. Use  `internalApiKey` in **Try Operation**. 

See the name has not changed. Because we cached the security

**Comment by iflamed** [comment]
Yes, I got it. Could you assign this issue to me?

**Comment by mohsen1** [comment]
Github won't allow me to do that. If you want to fix it, go for it!

**Comment by iflamed** [comment]
OK，i will work on it.

发自 刘兵 的 iPhone
