### ISSUE TITLE
Misspelling backendHelathCheckTimeout?

### ISSUE THREAD

**Issue by ejohansson** [swagger-api/swagger-editor#313]
`backendHelathCheckTimeout` should probably be `backendHealthCheckTimeout`

https://github.com/swagger-api/swagger-editor/blob/master/app/config/default.json.guide.js#L78

https://github.com/swagger-api/swagger-editor/blob/master/app/config/defaults.json#L23

**Comment by mohsen1** [comment]
Oops! 😱
Could you please fix it and send a pull request.
