### ISSUE TITLE
Can't build on OSX 10.9

### ISSUE THREAD

**Issue by stefankendall** [swagger-api/swagger-editor#316]
```
  SOLINK_MODULE(target) Release/validation.node: Finished
npm ERR! cb() never called!

npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.17
npm ERR! code ELIFECYCLE
npm ERR! swagger-editor-src@2.8.2 prestart: `npm install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the swagger-editor-src@2.8.2 prestart script 'npm install'.
npm ERR! This is most likely a problem with the swagger-editor-src package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install
```

**Comment by mikemalloyapigee** [comment]
I doubt this is an issue with the exact OSX version you are using.  I tried this yesterday and it worked fine for me.  I'll try again right now to see if I can repro this.

**Comment by mohsen1** [comment]
Could you paste entire npm log file here?

**Comment by mikemalloyapigee** [comment]
I just did a clean install and npm start and it worked for me.  I'm on Yosemite, but I don't think that should make any difference.  So the problem is likely to do with something in your environment.  I'm sure we'll figure it out.

**Comment by stefankendall** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.1.17
3 info using node@v0.10.35
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart swagger-editor-src@2.8.2
7 verbose unsafe-perm in lifecycle true
8 info swagger-editor-src@2.8.2 Failed to exec prestart script
9 verbose stack Error: swagger-editor-src@2.8.2 prestart: `npm install`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:212:16)
9 verbose stack     at EventEmitter.emit (events.js:98:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:98:17)
9 verbose stack     at maybeClose (child_process.js:766:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
10 verbose pkgid swagger-editor-src@2.8.2
11 verbose cwd /Users/a554173/work/swagger-editor
12 error Darwin 13.4.0
13 error argv "node" "/usr/local/bin/npm" "start"
14 error node v0.10.35
15 error npm  v2.1.17
16 error code ELIFECYCLE
17 error swagger-editor-src@2.8.2 prestart: `npm install`
17 error Exit status 1
18 error Failed at the swagger-editor-src@2.8.2 prestart script 'npm install'.
18 error This is most likely a problem with the swagger-editor-src package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm install
18 error You can get their info via:
18 error     npm owner ls swagger-editor-src
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]


I just jumped to 10.9 since this machine can't be updated to 10.10 until probably sometime mid year or later, and this has caused me repeated problems with dev tools. It's always my first assumption of fault at this point :P.

**Comment by mohsen1** [comment]
I see you're using npm version 2. Please try installing npm version 1 and see if that helps. This is not reproducible on my side. 


```
npm i -g npm@1
```

**Comment by prabhatjha** [comment]
I ran into problem building with npm 2.1.5 as well but I got a different
error. Regardless we need to fix it so that it runs with latest npm.

On Fri, Jan 30, 2015 at 12:56 PM, Mohsen Azimi <notifications@github.com>
wrote:

> I see you're using npm version 2. Please try installing npm version 1 and
> see if that helps. This is not reproducible on my side.
>
> npm i -g npm@1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swagger-api/swagger-editor/issues/316#issuecomment-72268858>
> .
>



-- 
Cheers,
Prabhat
---------------------------
Help spread www.eejot.org

**Comment by mohsen1** [comment]
I was able to build successfully with **`npm@2.4.1`**. Please re-open if you're still experiencing this.
