### ISSUE TITLE
New release doesn't support Yaml's Merge Key Language-Independent Type "<<:"

### ISSUE THREAD

**Issue by karamThebian** [swagger-api/swagger-editor#3164]
whenever we try to use the <<: operator, swagger editor returns :
Structural error at components.schemas.AddressObject.properties.AddressID
should NOT have additional properties
additionalProperty: <<

![image](https://user-images.githubusercontent.com/72201226/174039581-140c237d-8537-425e-9dee-1a70c5172895.png)

**Comment by Jeffersus** [comment]
Same thing here, except that in addition it's complaining of duplicate mapping keys when using multiple merge keys on the same object.

![image](https://user-images.githubusercontent.com/8485740/174858011-a60d3462-cd02-4ff3-8028-1542d3145171.png)

I've changed the property names for pasting the example but this spec has not changed in a while and it was working properly on Swagger Editor before.

Please note that it's working fine when I use this [Swagger Viewer](https://chrome.google.com/webstore/detail/swagger-viewer/nfmkaonpdmaglhjjlggfhlndofdldfag?hl=en) chrome extension, which is probably using an older version of Swagger Editor.

**Comment by mateuslopesnascimentodomgen** [comment]
Unfortunately, I'm having the same issue here.
![image](https://user-images.githubusercontent.com/95855978/174859192-6fcb4511-790c-417f-a420-167daea4ff69.png)

**Comment by karamThebian** [comment]
I had to downgrade back to swagger editor v 4.2.7 inorder to run my application...

**Comment by char0n** [comment]
I'm closing this, please reopen if you need guidance for migrating out of `Merge Key Language-Independent Type for YAML™ Version 1.1`.
