### ISSUE TITLE
SwaggerEditor@next: error while hovering over references

### ISSUE THREAD

**Issue by char0n** [swagger-api/swagger-editor#3184]
Reported by @ben-smartbear 

![image](https://user-images.githubusercontent.com/193286/175551354-721c509b-f430-44a8-8b42-ffd181e0db12.png)

**Comment by frantuma** [comment]
@char0n this seems not to be anymore reproducible, would close if ok

**Comment by char0n** [comment]
@frantuma sure If not reproducible we can close it.
