### ISSUE TITLE
Error when pasting JSON

### ISSUE THREAD

**Issue by CMClay** [swagger-api/swagger-editor#320]
![screen shot 2015-02-02 at 3 45 27 pm](https://cloud.githubusercontent.com/assets/6610263/6011602/9dfde852-aaf2-11e4-9a84-44deb58e9efe.png)

**Comment by mohsen1** [comment]
It's because empty string is invalid JSON. It can print prettier errors for sure. Pull requests are welcome!

**Comment by CMClay** [comment]
When I paste my JSON, there's no opportunity for me to click on the import button.

**Comment by mohsen1** [comment]
Could you paste your JSON here? If it's not valid JSON **Import** button will be disabled. You can check JSON with online tools before pasting there too.

**Comment by mohsen1** [comment]
Also note that Swagger Editor works with JSON too. You don't have to use this if you don't want to convert your Swagger to YAML.

**Comment by CMClay** [comment]
It's not the JSON. My JSON is being validated by swagger-tools. I also tried to paste the simple JSON from the examples provided, still no luck. I was using the site successfully last week.

**Comment by CMClay** [comment]
It works as expected when I paste the JSON directly into the sidebar. It's simply `File -> Paste JSON...` that doesn't seem to work.

**Comment by CMClay** [comment]
:+1:
