### ISSUE TITLE
Remove preceding slash

### ISSUE THREAD

**Issue by lavadiablo** [swagger-api/swagger-editor#321]
As preceding slash is used for config folder and examples folder, it cause trouble when reverse proxy is used.

i.e
http://domain.com/swagger-editor <== access ok
http://domain.com/config/default.json <== after proxy, not working if config folder is not configured
By removing the slash
http://domain.com/swagger-editor/config/default.json <= Can be properly accessed after proxy

The /examples/default.yaml has same isuee

**Comment by mohsen1** [comment]
Makes sense, will do

**Comment by iflamed** [comment]
I'm working on this issue.

**Comment by iflamed** [comment]
this has been fixed by #328, you can close it.
