### ISSUE TITLE
support document sharing with dropbox,google drive,gist etc.

### ISSUE THREAD

**Issue by iflamed** [swagger-api/swagger-editor#324]
After that, we can share the yaml or json file to gist. Or publish the api html file to dropbox or google drive.

If come true, a team collaboration will be more easy on the api document.

Wish the swagger-editor to be the best editor for api writer like the stackeditor for markdown!

**Comment by mohsen1** [comment]
Thanks! We have this in our roadmap. 
This is duplicate of #174
