### ISSUE TITLE
'X-foo' Parameter Object Error

### ISSUE THREAD

**Issue by megan-levy-kr** [swagger-api/swagger-editor#3313]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: Chrome
 - Version: 103.0.5060.114 (Official Build) (x86_64)
 - Method of installation: web browser
 - Swagger-Editor version: Current version on https://editor.swagger.io/ 
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
The following image shows the online Swagger editor for an error that previously did not occur
<img width="827" alt="swagger_io_error_message" src="https://user-images.githubusercontent.com/97686057/181078307-d1a4b13b-f0d6-440f-9b31-2dca4d393c2b.png">

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.1
info:
  title: "Sample Doc"
  version: 1.6.2
security:
  - clientContext:
      - "todo:write"
paths:
  /todo/v1/owners:
    parameters:
      - $ref: "#/components/parameters/x-correlation-id"
    get:
      tags:
        - "Owners"
      summary: "Get owners"
      responses:
        200:
          description: "OK"
  
components:
  securitySchemes:
    clientContext:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: "www.example.com/token"
          scopes:
            todo:write: Provides read and write access
  parameters:
    x-correlation-id:
      in: "header"
      name: "X-Correlation-ID "
      description: "Used to enable tracing through the call stack."
      schema:
        type: "string"
        format: "uuid"
        example: "2db833ca-d336-4eac-8ef8-b136233f6b3f"
    
```

```
?yourQueryStringConfig
```

### Describe the bug you're encountering

x-correlation-id is now being flagged as an error whereas previously the 'x-' was acceptable for the parameter object name
### To reproduce...

1. Go to  editor.swagger.io
2. paste example doc
3. see line 11 for error

### Expected behavior
The parameter object should accept 'x-correlation-id' 

### Additional context or thoughts
Please let me know if theres any further information needed!!

**Comment by char0n** [comment]
Hi @megan-levy-kr,

Thanks for reporting this. I'm looking into this problem just now.

**Comment by char0n** [comment]
PR provided here: https://github.com/swagger-api/swagger-editor/pull/3332

**Comment by char0n** [comment]
The issue was with the semantic validator and how it approaches determining that an object is a `Parameter Object`. According to OpenAPI specifications (version 2.0 and 3.0.x) parameter cannot be mistaken for a vendor extension. I've removed the condition that was checking that and it resolved the problem.

**Comment by char0n** [comment]
Released as https://github.com/swagger-api/swagger-editor/releases/tag/v4.3.0
