### ISSUE TITLE
SwaggerEditor@next: re-add keyboard shortcuts

### ISSUE THREAD

**Issue by tim-lai** [swagger-api/swagger-editor#3316]
### Is your feature request related to a problem?

Keyboard shortcuts got removed in #3241. They should be re-implemented.

### Describe the solution you'd like

Note, we should re-evaluate which fixtures we want to assign to a keyboard shortcut.
Also, ideally, this could be a plugin.

### Additional context

Related: 
#3268 
#3266

**Comment by frantuma** [comment]
closing as not a requirement
