### ISSUE TITLE
SwaggerEditor@next: re-add Jest unit tests

### ISSUE THREAD

**Issue by tim-lai** [swagger-api/swagger-editor#3331]
### Q&A (please complete the following information)
 - Swagger-Editor version: alpha.12

### Describe the bug you're encountering

Jest unit tests got removed in in https://github.com/swagger-api/swagger-editor/pull/3241. They should be re-implemented.

### Additional context or thoughts

At the time of creation, the Jest/TestingLibrary tests were focused on React screen elements. May want to revisit unit test strategy to cover more core functions.

fyi @char0n

**Comment by char0n** [comment]
@tim-lai I would reconsider. It's very complicated to maintain tests written in that fashion and their real value is questionable to me. Couldn't these tests be replaced by simple BDD e2e tests using cypress?

**Comment by tim-lai** [comment]
Migration from Jest to Cypress in the following PRs:
#3350 
#3356 
#3357 
#3361 
#3362 
#3363 
#3368 
#3369 
#3374 
#3375 
#3377 

These PRs collectively increases overall test coverage compared to the original set of Jest tests.
