### ISSUE TITLE
Separate preview into separate model / project

### ISSUE THREAD

**Issue by duncanhall** [swagger-api/swagger-editor#335]
The editor preview is great and seems far more mature than the actual swagger-ui viewer.

Can this be made available as a separate project?

**Comment by iflamed** [comment]
Good idea! The editor preview looks more beautiful the the swagger-ui viewer.

**Comment by webron** [comment]
This is actually going to work the other way around. Instead of supplying two separate project, the intent is to integrate swagger-ui inside the editor and not spawn off an additional project to maintain.

*How* this is going to be done is yet to be determined.

**Comment by duncanhall** [comment]
Completely understand less maintenance is desirable, but it does feel like the work needed to get swagger-ui up to par with the editor preview, is more work than making the editor preview a standalone?

I can commit time to something that enables a fully-featured UI/docs viewer, and my current inclination is to just rip out the editor preview and build from there.

**Comment by webron** [comment]
There are various reasons why we'd want to go on the road of using swagger-ui rather than the current inline viewer. However, we'd be more than happy to get assistance in that direction, including improving what you feel is missing from the ui at the moment.

**Comment by duncanhall** [comment]
The major thing with swagger-ui is just lack of features that are expected to be supported. There's some smaller ones which I believe are being fixed in M2, and some bigger things I'm still coming across (trying to confirm / detail before raising an issue). It seemed that if these were already supported in the editor preview, that would be a good place to build from.

I understand if there's reasons *not* to to go with the editor preview - it's just confuses the issue of where effort is best spent.

**Comment by webron** [comment]
Yup, I completely understand the confusion and apologize for it. FWIW, there are features supported by the UI that are not supported in the editor.

**Comment by mohsen1** [comment]
Swagger UI has a lot of features that Swagger Editor is lacking. For now lets use Swagger UI for rendering the docs. 
I has the same idea and I did put a "export HTML" button in Swagger Editor where it was making a web page that was only the docs. I did revert that feature back (It's here at 4af7d94e569bfee90baca36c61d5a946f272dbe2). 
Main reason for doing so is Swagger Editor preview lacks some key features from Swagger UI (file upload for example) and  codebase of Swagger Editor is too much for just rendering the docs.

@duncanhall @iflamed please don't start a new project for this right now. We will update you if we decided to make a new project so you can be part of it too. For now, lets focus on Swagger UI and Swagger Editor :)

**Comment by duncanhall** [comment]
Ok, thanks for the discussion, I agree we don't want to spread things even thinner. If there are any specific issues in swagger-ui that I can look at, feel free to assign / email me.

**Comment by webron** [comment]
Thanks for the offer to help. Basically, anything under https://github.com/swagger-api/swagger-ui/issues?q=is%3Aopen+is%3Aissue+milestone%3Av2.1-M2 could be handled, and we can provide additional details if required.

That said, if you feel something specific you need is missing, feel free to submit a PR nonetheless. M1 included quite a few community contributions that we didn't necessarily plan on including in that release (for example OAuth2 Access Code flow support).

**Comment by iflamed** [comment]
After the backend is ready,  Swagger-editor will be support the multiple project preview and public sharing or team collaboration.

**Comment by mohsen1** [comment]
@iflamed if you're interested in working on backend part of it checkout the [`backend`](https://github.com/swagger-api/swagger-editor/tree/backend) branch. I'm working on enabling the backend. 
To understand what the final goal is, checkout [anybin](https://github.com/mohsen1/anybin) project:
anybin.herokuapp.com

**Comment by iflamed** [comment]
Ok, I have visited the anybin project before.
