### ISSUE TITLE
The New/Blank Project options are not working? 

### ISSUE THREAD

**Issue by rajrin** [swagger-api/swagger-editor#338]
How do I create a new Swagger specs?

Initially I tried the online editor thought that the File->New is not working because its online so deployed the editor locally but even in that it does not work

Am I missing something or is it a bug or an un-implemented feature.

Best Regards
RS

**Comment by rajrin** [comment]
Played around and found out the way to fix it - in order to enable the File->New/Blank Project
I have set the configuration "useBackendForStorage" : "true" .... by default it is false.

Is it expected?

Now the next one - how do I save the files?

Regards
RS

**Comment by prabhatjha** [comment]
File is automatically saved in local storage of browser. If you want to
download to filesystem, go to File -> Download YAML or File -> Download
JSON.

On Sun, Feb 15, 2015 at 4:44 AM, rajrin <notifications@github.com> wrote:

> Played around and found out the way to fix it - in order to enable the
> File->New/Blank Project
> I have set the configuration "useBackendForStorage" : "true" .... by
> default it is false.
>
> Is it expected?
>
> Now the next one - how do I save the files?
>
> Regards
> RS
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swagger-api/swagger-editor/issues/338#issuecomment-74415982>
> .
>



-- 
Cheers,
Prabhat
---------------------------
Help spread www.eejot.org

**Comment by mohsen1** [comment]
Fixed by 3e298353d694b29ae903fe0599bcc21389dab327
