### ISSUE TITLE
Editor switches produces and consumes in documentation

### ISSUE THREAD

**Issue by bebna** [swagger-api/swagger-editor#340]
Items listed in ``consumes`` array get listed in the Accept select box in the "Try out this operation" form. Select box should have ``produces`` content instead.

**Comment by mohsen1** [comment]
Thanks for this!
There are some house keeping to do. After I did your PR will get deployed to swagger.io

**Comment by bebna** [comment]
Don't worry, was an easy fix with git grep. Just saw it while writing a spec who allows form data next to json and it didn't make sense in the tryout form to fill the HTTP Accept header with multipart/form-data.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   From: Mohsen AzimiSent: Montag, 16. Februar 2015 20:48To: swagger-api/swagger-editorReply To: swagger-api/swagger-editorCc: Armin FasoldSubject: Re: [swagger-editor] Editor switches produces and consumes in documentation (#340)Thanks for this!
There are some house keeping to do. After I did your PR will get deployed to swagger.io 

—Reply to this email directly or view it on GitHub.
