### ISSUE TITLE
suggestion: guided editor mode 

### ISSUE THREAD

**Issue by seriousme** [swagger-api/swagger-editor#343]
Would be nice if besides YAML there would also be a guided editor mode ("designer mode" ?)
This would aid the user in generating/modifying a swagger file without having to know the spec by hart.

I looked around and found [https://github.com/jdorn/json-editor] which auto generates an editor based on JSON schema.
One could feed the json-editor with the  [https://github.com/swagger-api/swagger-spec/blob/master/schemas/v2.0/schema.json]
A demo of the editor can be found at [http://jeremydorn.com/json-editor/]

**Comment by prabhatjha** [comment]
This is one of the most popular feature request.  See https://github.com/swagger-api/swagger-editor/issues/91

**Comment by mohsen1** [comment]
Closing as a duplicate of #91
