### ISSUE TITLE
CORSable URLs processing has a bug

### ISSUE THREAD

**Issue by longbe00** [swagger-api/swagger-editor#351]
Hi, i'm  a programer who I'd like to use Swagger Editor. 
I find a something wrong in your project.
Using Import url doesn't work now.

I think Your project has a bug in fileloader.js .
when CORSable URLs is processing , process check the url. But you made mistake around this code ' if (angular.isString(url) && url.indexOf('http') === 0) {'.

you have to change code  'if (angular.isString(url) && url.indexOf('http') < 0) {'.

thank you

**Comment by mohsen1** [comment]
I just tested import URL and it did work. Note that you need to tab out of input field then click import. I can certainly improve that.

**Comment by mohsen1** [comment]
Made #352 to improve validation

**Comment by longbe00** [comment]
oh, it's my mistake! it did work well. 
thank you for your quick response .
