### ISSUE TITLE
Docker `v4-latest` is mapped to the `v4.0.0-beta.1`

### ISSUE THREAD

**Issue by GAS85** [swagger-api/swagger-editor#3511]
# Docker Tags

`v4-latest` was updated more than year ago. https://registry.hub.docker.com/r/swaggerapi/swagger-editor/tags?page=1&name=v4-latest
And has digest of `v4.0.0-beta.1` https://registry.hub.docker.com/r/swaggerapi/swagger-editor/tags?page=1&name=v4.0.0-beta.1

It shall be currently mapped to the `v4.4.1`.

**Comment by char0n** [comment]
@GAS85 thanks for letting us know. We're looking into it.

**Comment by char0n** [comment]
@GAS85 we discontinued pushing `v4-latest` tag as it was replaced by `latest` (which now points to latest 4.x release instead of latest 3.x release).

Would you be able to use the `latest` tag?

**Comment by GAS85** [comment]
Yes, not a problem for me. But tag `latest` will be move to `v5` sooner or later. So.. logical user expectation is that `v4-latest` been attached to the actual v4 latest 😄  without update to the v5.

**Comment by char0n** [comment]
Jenkings job has been reconfigured, to push the docker image to `v4-latest` tag. Issuing a release now.

**Comment by char0n** [comment]
`v4-latest` successfully updated: https://registry.hub.docker.com/layers/swaggerapi/swagger-editor/v4-latest/images/sha256-d1cd27ca8c315d6d7152a215f80e96f595c09093e01b5d2bc2716fabad7b5d27?context=explore

@GAS85 again thanks for pointing this issue out.
