### ISSUE TITLE
Response with headers not rendered

### ISSUE THREAD

**Issue by suedama06** [swagger-api/swagger-editor#353]
When specifying a response with some headers (here X-Result-Count and X-Total-Count), those headers are not rendered in the editor.

![swagger editor 2015-02-23 18-13-35](https://cloud.githubusercontent.com/assets/8700001/6333646/2339bb84-bb8f-11e4-9c70-8de3e3e651c7.png)

**Comment by mohsen1** [comment]
Duplicate of #268

**Comment by mohsen1** [comment]
Fixed in #268
