### ISSUE TITLE
SwaggerEditor@next: editor-next.swagger.io is not reporting the errors in the specifications

### ISSUE THREAD

**Issue by harishsubramanian2577** [swagger-api/swagger-editor#3567]
Hi,
looks like https://editor-next.swagger.io/ is not reporting the errors in API specification the way https://editor.swagger.io/ is reporting. I tested with a spec that i know has issues with the old and new version. while the old one is reporting the errors, the new one is not reporting them. Please can you check and let me know if I am missing something?

### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-Editor version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-Editor configuration options:
```js
SwaggerEditor({
  // your config options here
})
```

```
?yourQueryStringConfig
```

**Comment by char0n** [comment]
Hi @harishsubramanian2577,

Can you share your spec with us or create a minimal one that so that we can see what errors you reference to?

NOTE: Also keep in mind that OpenAPI support is still not officially supported. We currently work on finalizing support for OpenAPI 3.0.x and during next week we'll address OpenAPI 3.1.0 as well. So **this** might be reason why you're seeing different errors.

**Comment by harishsubramanian2577** [comment]
Hi @char0n ,

Attaching sample OAS spec and screen shot of the validation output in https://editor.swagger.io and https://editor-next.swagger.io/. 

<img width="1791" alt="editor-next swagger io_Screenshot" src="https://user-images.githubusercontent.com/116039895/197244503-3199266e-e5e9-472e-8a54-4d5472e921c0.png">
<img width="1792" alt="editor swagger io_Screenshot" src="https://user-images.githubusercontent.com/116039895/197244523-bdf770cf-174e-4156-9bad-437a953dc07e.png">

[Invalidapi.yaml.zip](https://github.com/swagger-api/swagger-editor/files/9840847/Invalidapi.yaml.zip)

Regards
Harish.S

**Comment by char0n** [comment]
MVP of OpenAPI 3.0.x support has been released in https://github.com/swagger-api/swagger-editor/releases/tag/v5.0.0-alpha.28.

https://editor-next.swagger.io/ is now reporting the error in your definition as well:

![image](https://user-images.githubusercontent.com/193286/200565633-499aa46e-46f0-4eac-a2ed-5efcdeab3d8e.png)

> NOTE that  errors are now placed in bottom-left editor bar, instead of top-right location.

If you find any more inconsistencies, please let us know. Thanks!

**Comment by harishsubramanian2577** [comment]
@char0n , thanks for your response, A question related to the swagger validate utility https://github.com/char0n/swagger-editor-validate . will it work fine if with https://editor-next.swagger.io/ as well or does it need to be updated to work correctly?

**Comment by char0n** [comment]
Hi @harishsubramanian2577,

No the  https://github.com/char0n/swagger-editor-validate will not work with https://editor-next.swagger.io/ URL. I'm already working in new GitHub Action based on https://github.com/swagger-api/apidom which https://editor-next.swagger.io/ uses under the hood. Will ping you when the action will be available.

**Comment by ethicalmohit** [comment]
@char0n When can we expect the editor-next github action?

> Hi @harishsubramanian2577,
> 
> No the https://github.com/char0n/swagger-editor-validate will not work with https://editor-next.swagger.io/ URL. I'm already working in new GitHub Action based on https://github.com/swagger-api/apidom which https://editor-next.swagger.io/ uses under the hood. Will ping you when the action will be available.
