### ISSUE TITLE
Asyn API not supported in editor

### ISSUE THREAD

**Issue by mnomansadiq** [swagger-api/swagger-editor#3572]
I have download and build a latest swagger editor but the editor not recognising async API? Any information when it will be available?

<img width="1531" alt="Screenshot 2022-10-20 at 14 35 37" src="https://user-images.githubusercontent.com/11539579/196950069-2608a83a-b258-4674-b058-1cefa74bb829.png">

**Comment by char0n** [comment]
Hi @mnomansadiq,

SwaggerEditor@next is being developed on [next](https://github.com/swagger-api/swagger-editor/tree/next) branch of this repository.

Cheers.

**Comment by mnomansadiq** [comment]
Great, compilation is little bit different and difficult here for me. Anyhow, so this branch will merge into master in near future and then the Swagger editor will have the capability to use for both Rest and Async API specification?

**Comment by char0n** [comment]
> Great, compilation is little bit different and difficult here for me. Anyhow, so this branch will merge into master in near future and then the Swagger editor will have the capability to use for both Rest and Async API specification?

You don't actually need to compile it. We do release the `next` branch as `swagger-editor@5.0.0-apha.*`. 

For example GitHub release can be found here: https://github.com/swagger-api/swagger-editor/releases/tag/v5.0.0-alpha.27

We also package SwaggerEditor@next  as npm artifacts which are distrubuted via GitHub Packages: https://github.com/swagger-api/swagger-editor/pkgs/npm/swagger-editor/45997911
