### ISSUE TITLE
array elements are not shown in JSON

### ISSUE THREAD

**Issue by vpavlushkov** [swagger-api/swagger-editor#358]
While using editor.swagger.io to document the APIs and I am struggling to describe API response that should generate the following JSON:
```
{
  status: 200,
  result: [
    data1: qwerty,
    data2: qwerty,
    data3: qwerty
  ]
}
```
 To accomplish that, I wrote the following:
```
responses:
        200:
          description: Successful request
          schema:
            required:
              - result
              - status
            properties:
              status:
                description: HTTP header code
                type: integer
              result:
                description: Obtained data array
                type: array
                  required:
                    - data1
                    - data2
                    - data3
                  items:
                    data1:
                      type: string
                      example: qwerty              
                    data2:
                      type: string
                      example: qwerty
                    data3:
                      type: string
                      example: qwerty
``` 
The online editor gives no errors nor warnings. But when I check the response schema and expand the square brackets of "result", I do not see the enclosed elements data1, data2 and data3. However if, instead of simple elements I provide '$ref: "#/definitions/something"', the "something appears inside result.

**Comment by mohsen1** [comment]
`items` itself should be a valid JSON Schema

Your schema should look like this:

```yaml
          schema:
            required:
              - result
              - status
            properties:
              status:
                description: HTTP header code
                type: integer
              result:
                description: Obtained data array
                type: array
                items:
                  type: object
                  description: A data item
                  required:
                    - data1
                    - data2
                    - data3
                  properties:
                    data1:
                      type: string
                      example: qwerty              
                    data2:
                      type: string
                      example: qwerty
                    data3:
                      type: string
                      example: qwerty
```

**Comment by vpavlushkov** [comment]
Thanks for this fast reply. That actually explains why the case with refs inside an array works just fine. However, if I understand it right, your YAML fragment would correspond to JSON structure where inside an array I would have an object containing of three string elements:
```
[
  {
    string,
    string,
    string
  }
]
```
just like mentioned in https://github.com/swagger-api/swagger-editor/issues/339. Is it even possible to built a YAML/JSON construction without wrapping an object around the three string elements?

**Comment by mohsen1** [comment]
I don't understand your questions. Please provide valid JSON that you want to describe with JSON Schema. Your JSON examples are not valid JSON.

For this example:
```json
{
  status: 200,
  result: [
    data1: qwerty,
    data2: qwerty,
    data3: qwerty
  ]
}
```
I assumed your JSON is really this:

```json
{
  "status": 200,
  "result": [
    { "data1": "qwerty"},
    { "data2": "qwerty"},
    { "data3": "qwerty"}
  ]
}
```

**Comment by vpavlushkov** [comment]
Hi,

Playing a little bit with JSON validator and Swagger editor has resolved all further questions that I had. 

Thank your for your help once again!
