### ISSUE TITLE
"Errors" panel doesn't always update when I type

### ISSUE THREAD

**Issue by nickretallack** [swagger-api/swagger-editor#359]
This is really annoying.  Sometimes it will persistently show an error that doesn't make any sense, when the schema is actually valid.

### Steps to reproduce

1) Paste this into your editor:
```yaml
swagger: '2.0'
info:
  title: Example
  version: "1.0.0"
paths:
  /things:
    post:
      parameters:
        - name: body
          in: body
          schema:
            type: string
      responses:
        200:
          description: OK
```

2) Delete this line to make it show an error:
```yaml
            type: string
```

3) Put it back.  The error still shows.
4) Cause a different error by typing some nonsense somewhere
5) Delete your nonsense.  Now all the errors are gone!

**Comment by mohsen1** [comment]
For now, you can refresh the page to get around it. This will get fixed soon.

**Comment by mohsen1** [comment]
For my own reference:

https://github.com/mohsen1/apply-diff/commit/063051cf808f702ccf4023456afea1042a3d6f77 and https://github.com/mohsen1/apply-diff/commit/8e2807c1562325f7c4c1988f9cadeb91b5d1e2ce fixed this
