### ISSUE TITLE
`allOf` inside `definitions` crashes the validator

### ISSUE THREAD

**Issue by nickretallack** [swagger-api/swagger-editor#361]
I'm using this version: 5e73878ed714dae8df9da595321f99a6ccc73275 but it also breaks the editor at http://editor.swagger.io/

```yaml
swagger: '2.0'
info:
  version: "0.0.0"
  title: Example
paths:
  /test:
    get:
      responses:
        200:
          description: OK
definitions:
  Two:
    allOf:
      - $ref: '#/definitions/One' 
      - format: something
  One:
    type: object 
```

Result is:
```
 Uncaught Error: ptr is required
```

It seems to be trying to interpret the second item in the allOf as if it's also a $ref.

**Comment by nickretallack** [comment]
Oddly, this only happens inside of the "definitions" block.  ```allOf``` works fine inside a ```schema``` block.

```yaml
swagger: '2.0'
info:
  version: "0.0.0"
  title: Example
paths:
  /test:
    get:
      responses:
        200:
          description: OK
          schema:
            allOf:
              - $ref: '#/definitions/One' 
              - format: something
definitions:
  One:
    type: object 
```

**Comment by mohsen1** [comment]
`allOf

**Comment by mohsen1** [comment]
`allOf` is not currently supported in [JSON Shema View](https://github.com/mohsen1/json-schema-view). So don't expect it to render anything accurate. 
The editor crash is a bug. I'll look into this

**Comment by nickretallack** [comment]
Another similar document that doesn't cause the error:

```yaml
swagger: '2.0'
info:
  version: "0.0.0"
  title: Example
paths:
  /test:
    get:
      responses:
        200:
          description: OK
definitions:
  Two:
    allOf:
      - $ref: '#/definitions/One' 
      - $ref: '#/definitions/Three'
  One:
    type: object 
  Three:
    format: something
```

This is a suitable workaround for now, since it is pretty much equivalent to the spec I want to write.  It also demonstrates the problem:

```allOf```, when used inside a ```definition```, expects all of its children to be ```$ref```s.

**Comment by nickretallack** [comment]
This schema also crashes the validator:

```yaml
swagger: '2.0'
info:
  version: "0.0.0"
  title: Example
paths:
  /test:
    get:
      responses:
        200:
          description: OK
definitions:
  One:
    type: object
  Two:
    allOf: 
      - $ref: '#/definitions/One'
```

This time it's for a slightly different reason.  This time the error is:

``` Uncaught TypeError: Cannot convert undefined or null to object```

It seems to be expecting ```One``` to have ```properties```.  Adding ```properties``` there fixes it:

```yaml
swagger: '2.0'
info:
  version: "0.0.0"
  title: Example
paths:
  /test:
    get:
      responses:
        200:
          description: OK
definitions:
  One:
    type: object
    properties:
      foo:
        type: string
  Two:
    allOf: 
      - $ref: '#/definitions/One'
 ```

**Comment by mohsen1** [comment]
Follow downstream issue here
https://github.com/apigee-127/swagger-tools/issues/173
