### ISSUE TITLE
Render `format` please

### ISSUE THREAD

**Issue by nickretallack** [swagger-api/swagger-editor#362]
The ```format``` property doesn't show up anywhere in the preview or generated documentation.  However, it is very important!  Could you show it somewhere please?

**Comment by nickretallack** [comment]
Waiting on this I guess: https://github.com/swagger-api/swagger-ui/issues/808

**Comment by mohsen1** [comment]
which format? format of JSON Schema or parameter?

**Comment by nickretallack** [comment]
The parameter.  The one that is siblings with ```type```.

**Comment by mohsen1** [comment]
ok. We will do it
