### ISSUE TITLE
Please add .NET Core client generator.

### ISSUE THREAD

**Issue by Duke4848** [swagger-api/swagger-editor#3622]
On OpenApi website I see there is avaialble csharp-netcore generator and the csharp one available on the https://editor-next.swagger.io/ is deprecated. Can you add it so I can generate .NET Core 6 client?

**Comment by char0n** [comment]
Hi @Duke4848,

Can you maybe elaborate what you mean?

In https://editor-next.swagger.io/ I can see that we can generate clients for `csharp` and `csharp-dotnet2`.

![image](https://user-images.githubusercontent.com/193286/200273802-061f6663-37f3-4506-affe-445459978c7b.png)

Here are all the possible generator values:

> ada, akka-scala, android, apex, bash, clojure, cpprest, csharp, csharp-dotnet2, cwiki, dart, dart-jaguar, dynamic-html, eiffel, elixir, elm, erlang-client, flash, go, groovy, haskell-http-client, html, html2, java, javascript, javascript-closure-angular, jaxrs-cxf-client, jmeter, kotlin, lua, objc, perl, php, powershell, python, qt5cpp, r, ruby, rust, scala, scalaz, swagger, swagger-yaml, swift, swift3, swift4, swift5, tizen, typescript-angular, typescript-angularjs, typescript-aurelia, typescript-fetch, typescript-inversify, typescript-jquery, typescript-node, ue4cpp


> On OpenApi website

Can you provide a link please?

> I see there is avaialble csharp-netcore generator and the csharp one available on the https://editor-next.swagger.io/ is deprecated

By "csharp one" do you mean `csharp` and by "csharp-netcore" do you mean `csharp-dotnet2`? Another question - which one of them is according to you deprecated and where did you find the deprecation notice?

Thanks for clarifications.

**Comment by char0n** [comment]
> Note: code generation capabilities as provided by https://github.com/swagger-api/swagger-codegen

**Comment by char0n** [comment]
Closing as could not gather more information.
