### ISSUE TITLE
SwaggerEditor@next: unescaped autocompletion of references

### ISSUE THREAD

**Issue by char0n** [swagger-api/swagger-editor#3628]
### Q&A (please complete the following information)
 - OS: Linux Mint
 - Browser: Chrome
 - Version: 107.0.5304.87 (Official Build) (64-bit)
 - Method of installation: https://swagger-editor-next.surge.sh/
 - Swagger-Editor version: 
![image](https://user-images.githubusercontent.com/193286/200583732-b6cf5a3e-02b9-46c3-bc8a-2fc9d0a042c5.png)

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.1.0
info:
  title: deref
  version: 1.0.0
servers:
  - description: local
    url: http://localhost:8082/
paths:
  /path/segment1/segment2:
    get:
      operationId: aget
    post:
      operationId: apost
components:
  pathItems: 
    pathItem1:
      $ref: '#/paths//path/segment1/segment2'
```

### Describe the bug you're encountering

When autocompletion of `components.pathItems.pathItem1.$ref` is performed, the `'#/paths//path/segment1/segment2'` will be suggested and inserted. That's **incorrect**, because the text should be inserted in JSON Pointer encoded form: `'#/~1paths~1path~1segment1~1segment2'`. 

> NOTE: also notice that there are **two** un-escaped backslashes instead of one: `'#/paths//path/segment1/segment2'`

### Expected behavior

Suggestion shows unescaped form of the future inserted text, but the insertion will insert properly JSON Pointer encoded text.

### Screenshots

![image](https://user-images.githubusercontent.com/193286/200585735-63029df5-e396-4727-a728-4631896b12e4.png)

### Additional context

Note that `apidom-json-pointer` package contains all the tooling needed to implement this fix: https://github.com/swagger-api/apidom/blob/main/packages/apidom-json-pointer/README.md#escaping

**Comment by ponelat** [comment]
Ran into this as well for `$ref` inside of a Webhook.
![image](https://github.com/swagger-api/swagger-editor/assets/8438485/14c9e326-2304-417d-85d7-23d25b02cdd1)

**Comment by frantuma** [comment]
fixed in https://github.com/swagger-api/apidom/pull/2975
