### ISSUE TITLE
Make keypress debounce configurable from the UI

### ISSUE THREAD

**Issue by nickretallack** [swagger-api/swagger-editor#364]
Typing in the editor is getting slower and slower the larger my spec gets, presumably because of all of the validations it has to do on every keystroke.

Could you debounce this a bit?  When I hit a key, wait a moment before running the validations in case I hit another key and you have to start validating all over again.

**Comment by mohsen1** [comment]
You can click Mode and Disable Live Render to render manually. That will speed things up. 

It's a good idea to make that debounce timeout configurable.

**Comment by tgrant59** [comment]
+1

**Comment by mohsen1** [comment]
Fixed by 5e3fdd9
