### ISSUE TITLE
Running on a server

### ISSUE THREAD

**Issue by Russell-** [swagger-api/swagger-editor#366]
I'm interested in running the swagger-editor on a server so it's available to other members in our group.  Could you tell me if I need the "server" branch for that instead of "master".  I looked at README.md in both branches and they appear to be the same.

Thank you.

Russell

**Comment by mohsen1** [comment]
Ignore the server branch. You can enable server mode in settings but you have to provide your own server that responds to PUT and GET calls.

Here is the settings:
https://github.com/swagger-api/swagger-editor/tree/master/app/config

Here are more docs:
https://github.com/swagger-api/swagger-editor/tree/master/docs

**Comment by Russell-** [comment]
Thanks, Moshen, for the pointers.  I'll research.

Russell
