### ISSUE TITLE
Another URL Import

### ISSUE THREAD

**Issue by WhitneyLand** [swagger-api/swagger-editor#370]
Is this supposed to work?

Import one of the github samples into the swagger editor demo:

http://editor.swagger.io/#/?import=http://raw.githubusercontent.com/swagger-api/swagger-spec/master/examples/v2.0/yaml/petstore-expanded.yaml

**Comment by fehguy** [comment]
I don't know if raw links work with the url import. @mohsen1 ?

**Comment by mohsen1** [comment]
It should work but apparently my service (https://cors-it.herokuapp.com) has problems with CORS stuff. It also goes to sleep if it's not used for a while because it's a free app.

I just learned about https://rawgit.com/  I should replace cors-it with rawgit.

**Comment by fehguy** [comment]
Hang on. I meant "it will not work directly" due to cors. Yes you can use a proxy but that's aa different question

**Comment by mohsen1** [comment]
Swagger Editor proxies import URLs through https://cors-it.herokuapp.com

**Comment by mohsen1** [comment]
This was fixed by https://github.com/mohsen1/cors-it/commit/4687a454e99ba21b166ebb2a698414799f55080d
