### ISSUE TITLE
Support for custom validation

### ISSUE THREAD

**Issue by gituserjava** [swagger-api/swagger-editor#3719]
Hi,

We are looking for validation of Open API spec file with some custom rules defined by our company. We have an API that can take the entire API spec and return validation errors as json. We want to some how integrate this with Swagger editor so that whenever the API spec is edited on Swagger editor we want to display all the validation errors on the right side of the page (similar to display of default validation errors as shown on the screenshot). Our requirement is similar to the one discussed on #1351, please let me know if this is possible and please share if you have any updated documentation around this.

![78C5C938-69CD-42D2-9920-F3867DE7378F](https://user-images.githubusercontent.com/64553468/205160677-7fcb4791-30f1-4671-9b3b-3eda347b25e2.jpeg)

**Comment by gituserjava** [comment]
> Hi,
> 
> We are looking for validation of Open API spec file with some custom rules defined by our company. We have an API that can take the entire API spec and return validation errors as json. We want to some how integrate this with Swagger editor so that whenever the API spec is edited on Swagger editor we want to display all the validation errors on the right side of the page (similar to display of default validation errors as shown on the screenshot). Our requirement is similar to the one discussed on #1351, please let me know if this is possible and please share if you have any updated documentation around this.
> 
> ![78C5C938-69CD-42D2-9920-F3867DE7378F](https://user-images.githubusercontent.com/64553468/205160677-7fcb4791-30f1-4671-9b3b-3eda347b25e2.jpeg)

@shockey , could you please let me know if you have any documentation/reference implementation on this? The steps you mentioned on #1351 and the current code does not match.

**Comment by char0n** [comment]
Hi @gituserjava,

You need to produce editor plugin that conceptually looks and works like this:

```js
    const CustomValidationPlugin = () => {
      return {
        statePlugins: {
          spec: {
            wrapActions: {
              validateSpec: (oriAction, system) => async (payload) => {
                // dispatch original action before doing async calls
                oriAction(payload);

                const { specSelectors, errActions } = system;
                const spec = specSelectors.specStr();
                /**
                 * What you will really do here is to make HTTP call to your remove validation service, e.g.:
                 *
                 * const validationResult = await fetch('https://example.com/validation/error', {
                 *   method: 'POST',
                 *   body: spec,
                 * });
                 *
                 * Let's fake HTTP call here for demonstration purposes and assume your remote validation
                 * service returns validation error in following format.
                 */
                const validationResult = await Promise.resolve([
                  {
                    level: 0,
                    error: 'This is error 1',
                    line: 2,
                  },
                  {
                    level: 2,
                    error: 'This is warning 1',
                    line: 3,
                  },
                ]);
                //transform remote validation errors to internal validation error format
                const source = 'my-custom-remote-validator';
                const specErrBatch = validationResult.map((validationError) => ({
                  source,
                  level: validationError.level === 0 ? 'error' : 'warning',
                  message: validationError.error,
                  line: validationError.line,
                }));
                // clear validation errors from previous validation cycle
                errActions.clear({ source })
                // dispatch remote validation errors to the system
                errActions.newSpecErrBatch(specErrBatch);
              }
            }
          }
        }
      }
    };
```

Then you use the plugin with the editor instance:

```js
const editor = SwaggerEditorBundle({
    dom_id: '#swagger-editor',
    layout: 'StandaloneLayout',
    presets: [
      SwaggerEditorStandalonePreset
    ],
    plugins: [
      CustomValidationPlugin,
    ],
})
window.editor = editor;
```

Hope it resolve your questions.

**Comment by gituserjava** [comment]
Can we hook the custom plugin from outside of swagger editor? That is, can I use swagger editor dist my package.json in my custom node JS application and then some how inveterate the custom plugin. Please advise.
