### ISSUE TITLE
Send request via "Try this operation" shows error with no details

### ISSUE THREAD

**Issue by dannylevenson-ps** [swagger-api/swagger-editor#373]
When I use the "try this operation", the request is built and sent correctly, my Node.js code handles the request and sends the proper response, but the Swagger editor simply shows a green "Error" bar in the response area.  The "Rendered" and "Pretty" tabs look empty and the "Raw" tab shows only HTTP/1.1.  I have verified that my Node.js is building the correct response via test cases, manual examination of curl -i output and using Postman in Chrome.  I have carefully examined my schema definition for the response, and I believe that it correctly describes the actual response data.  How do I determine if this is a bug in the swagger-editor vs a problem in my schema describing the response data?

![image](https://cloud.githubusercontent.com/assets/8557549/6597739/ebb1356e-c7d4-11e4-8f3b-7f189d52d614.png)

**Comment by mohsen1** [comment]
Please open Chrome Developer Tools and select **Network** tab then try this. Examine the XHR call and make sure there is no error in there.

Please note that Swagger Editor is a web app and has [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) limitation. Postman is a packaged Chrome app and does not have CORS limitations.

If you didn't see any errors in Network tab please paste you Swagger specs here so we can help you.

**Comment by dannylevenson-ps** [comment]
Examining the network tab in Chrome makes it look like the response only contains the headers without any body.  However, I am quite certain that the response contains a JSON object in the body and the content-type is application/json; charset=utf-8.  When I use curl -i to issue the same request, I get the following:

HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 1282
ETag: W/"ekK93sn2UZ8QESF9+3OIOQ=="
Date: Wed, 11 Mar 2015 13:52:29 GMT
Connection: keep-alive

{<the expected and properly formed JSON object here>}

**Comment by mohsen1** [comment]
Are you sure your server allows cross-origin calls from `swagger.io` origin? You might need to enable CORS in your server

**Comment by dannylevenson-ps** [comment]
Since I was running swagger-editor and my own application's node server both on localhost, I didn't think I needed to allow CORS.  I turned on the CORS middleware on my application's express server, allowed localhost:9000 and the request from swagger-editor now works correctly.  Thanks.

**Comment by mohsen1** [comment]
Yes, different ports are different origins. This got me once too! :) 

Glad you figured it out
