### ISSUE TITLE
Questions on SemanticValidatorsPlugin

### ISSUE THREAD

**Issue by gituserjava** [swagger-api/swagger-editor#3733]
I created a custom constant to perform custom validations. Could you please let me know below?

1. How do i get access to "jsSpec" in custom actions?
2. How do I return errorActions?

````

export const validateMySpec= () => sys => {
   //Step 1: Get the API spec here. How to get it?
   //Step 2: Validate spec -- custom logic
   //Step 3: Populate errors
    const errors = []
    errors.push({
      level: "error",
      message: "We can do something with this, array.",
      path: "schema.path"
    })

    sys.errActions.newSpecErr(errors)

    //Step 4: Return errActions
}

````

**Comment by char0n** [comment]
Hi @gituserjava,

You need to produce editor plugin that conceptually looks and works like this:

```js
   // this semantic validator plugin validates if Schema Object is not array
    const CustomSemanticValidationPlugin = () => {
      return {
        statePlugins: {
          validate: {
            actions: {
              validate2And3SchemaIsNotAnArray: () => async (system) => {
                const errors = []
                const schemas = await system.validateSelectors.allSchemas();

                schemas.forEach(node => {
                  if (Array.isArray(node.node)) {
                    errors.push({
                      level: "error",
                      message: "Schema Object cannot be array",
                      path: node.path // it'll figure out the line # from this
                    })
                  }
                });

                return errors;
              }
            },
          }
        }
      }
    };
```

Now the naming of the action is important:
- actions starting with `validate2And3` will apply for OpenAPI 2 and 3
- actions starting with `validateOAS3` will apply for OpenAPI 3
- actions starting with `validate` will apply for OpenAPI 2

Examples how to actually create validation logic are here: https://github.com/swagger-api/swagger-editor/tree/3e1e5264d0c15edc28474fdf84701ddb5dc61053/src/plugins/validate-semantic/validators

The list of available selectors is available here: https://github.com/swagger-api/swagger-editor/blob/a98ed912526469ea9f0fa93c1184372bc1356ebe/src/plugins/validate-semantic/selectors.js#L1

Then you use the plugin with the editor instance:

```js
const editor = SwaggerEditorBundle({
    dom_id: '#swagger-editor',
    layout: 'StandaloneLayout',
    presets: [
      SwaggerEditorStandalonePreset
    ],
    plugins: [
      CustomValidationPlugin,
    ],
})
window.editor = editor;
```

Hope it resolve your questions.

**Comment by boulbababenjabeur** [comment]
@char0n 
hi i am actually doing my graduate project i want to add some custom semantic validator to swagger editor project i created custom validator function and imported it to the SemanticValidatorsPlugin then build the project but it dosent read the validator can you give me instruction how to to that?
this is my custom validator :
export const validate2And3Custom = sys => {
  return sys.validateSelectors
    .allInfos()
    .then(nodes => {
      return nodes.reduce((acc, node) => {
        const value = node.node;

        if (value.version !== '2.0' && value.version !== '3.0.0') {
          acc.push({
            level: 'error',
            message: `Unsupported Swagger version: ${value.version}`,
            path: [...node.path, 'version']
          });
        }

        return acc;
      }, []);
    });
};

**Comment by char0n** [comment]
Hi @boulbababenjabeur,

Please have a look at https://github.com/swagger-api/swagger-editor/issues/3719#issuecomment-1361338217; might help a lot.
