### ISSUE TITLE
Code Generator Error

### ISSUE THREAD

**Issue by alvineflore** [swagger-api/swagger-editor#374]
Unable to build target: A target generation was attempted, but no files were created!

Details:
Object
code: 1
type: "error"
message: "Unable to build target: A target generation was attempted, but no files were created!"

**Comment by webron** [comment]
Can you provide us with more details so we can try and find the problem?

**Comment by mohsen1** [comment]
Please paste your YAML here

**Comment by raviles** [comment]
This happens with the default demo yaml and attempting to generate a swagger client at http://editor.swagger.io/#/

**Comment by mohsen1** [comment]
Please follow this issue here: https://github.com/swagger-api/swagger-codegen/issues/520

**Comment by alvineflore** [comment]
here is my YAML:
swagger: "2.0"
info:
  title: Vairified API
  description: Social network to check your information
  version: 1.0.0
host: vairified.com
schemes:
  - https
basePath: /api
produces:
  - swagger-docs/json
paths:
  /wakis:
    post:
      summary: This method adds waki 
      
      description: "The endpoint returns informations about user *Vairified API* operations. The response include user profile and"
      parameters:
        - name: wakiid
          description: User identifier
          in: query
          required: true
          type: integer
        - name: firstname
          in: query
          required: true
          type: string
        - name: lastname
          in: query
          required: true
          type: string
        - name: email
          in: query
          required: true
          type: string
        - name: username
          in: query
          required: true
          type: string
        - name: slug
          in: query
          required: true
          type: string
        - name: photo
          in: query
          required: true
          type: string
        - name: password
          in: query
          required: true
          type: string
        - name: phone
          in: query
          required: true
          type: string
        - name: city
          in: query
          required: true
          type: string
        - name: country
          in: query
          required: true
          type: string
        - name: lang
          in: query
          required: true
          type: string
        - name: verify
          in: query
          required: true
          type: boolean
        - name: role
          in: query
          required: true
          type: integer
        - name: created
          in: query
          required: true
          type: string
        - name: modified
          in: query
          required: true
          type: string
        - name: civility
          in: query
          required: true
          type: boolean
      tags:
        - wakis
      responses:
        200:
          description: The user was successfully created.
 
    put:
      summary: This method allows to modify information of waki
      description: The endpoint of this method returns an array contain details about one user
      parameters:
        - name: wakiid
          description: User identifier
          type: integer
          in: query
          required: true
        
      tags:
        - wakis
      responses:
        200:
          description: Profile information for a user
          schema:
            $ref: "#/definitions/show_Profile"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
  
    delete:
      summary: This method is used to delete wakis into  database
      description: This method remove one or more waki in Vairified API database
      parameters:
        - name: wakiid
          description: User identifier
          in: query
          required: true
          type: integer
      tags:
        - wakis
      responses:
        "200":
          description: waki has been remove
  
  /wakis/posts:
    get:
      summary: Get posts of waki
      description: The endpoint of this method return all the Posts of one waki using wakiid in table posts 
      parameters:
         - name: wakiid
           description: User identifier
           in: query
           required: true
           type: integer
      tags:
        - wakis
      responses:
        200:
          description: array of posts
          schema: 
            $ref: "#/definitions/show_post"
  /waki/groups:
    get:
      summary: Get group a waki belongs to
      description: The endpoint of this method return all the groups were waki belongs to using wakiid in table groups 
      parameters:
         - name: wakiid
           description: User identifier
           in: query
           required: true
           type: integer
      tags:
        - wakis
      responses:
        200:
          description: array of groups
          schema: 
            $ref: "#/definitions/show_groups" 
  /waki/tag:
    get:
      summary: Get tags of waki
      description: The endpoint of this method return all the tags of waki, using wakiid in table tags 
      parameters:
         - name: wakiid
           description: User identifier
           in: query
           required: true
           type: integer
      tags:
        - wakis
      responses:
        200:
          description: array of tag
          schema: 
            $ref: "#/definitions/show_tag"
  /waki/experience:
    get:
      summary: Get experiences of waki
      description: The endpoint of this method return all the experiences of waki, using wakiid in table experiences 
      parameters:
         - name: wakiid
           description: User identifier
           in: query
           required: true
           type: integer
      tags:
        - wakis
      responses:
        200:
          description: array of experiences
          schema: 
            $ref: "#/definitions/show_tag"
  /Posts:
    post:
      summary: This method adds Posts into database
      description: The endpoint returns add post of user in database of Varified API
      parameters:
        - name: post_id
          description: post identifier
          in: query
          required: true
          type: integer
        - name: post_content
          description: post content
          in: query
          required: true
          type: string
        - name: wisappid
          in: query
          required: true
          type: integer
        - name: post_time_response
          in: query
          required: true
          type: string
        - name: post_image
          in: query
          required: true
          type: string
        - name: post_date
          in: query
          required: true
          type: string
        - name: post_lang
          in: query
          required: true
          type: string
        - name: nb_bookmarks
          in: query
          required: true
          type: integer
        - name: wakiid
          in: query
          required: true
          type: integer
        - name: groupe_id
          in: query
          required: true
          type: integer
        - name: post_type
          in: query
          required: true
          type: integer
        - name: status
          in: query
          required: true
          type: boolean
      tags:
        - Posts
      responses:
        "200":
          description: posts has been add successfully
  
    put:
      summary: This method allows to modify Posts
      description: The endpoint of this method returns an array contain details about Posts
      parameters:
        - name: wakiid
          description: waki identifier
          in: query
          required: true
          type: integer
        - name: groupe_id
          description: group identifier
          in: query
          required: true
          type: integer
        - name: post_id
          description: post identifier
          in: query
          required: true
          type: integer
      tags:
        - Posts
      responses:
        "200":
          description: Posts  details
          schema:
            $ref: "#/definitions/show_post"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
  
    delete:
      summary: This method is used to delete Posts into database
      description: This method remove one or more Posts in Vairified API database
      parameters:
        - name: post_id
          description: Posts identifier
          in: query
          required: true
          type: integer
      tags:
        - Posts
      responses:
        "200":
          description: Posts has been remove
  /groups:
    post:
      summary: Add group in Vairified API
      description: This method will add a new group in vairified API
      parameters:
        - name: group_id
          type: integer
          in: query
          required: true
        - name: groupe_name
          in: query
          required: true
          type: string
        - name: groupe_image
          in: query
          required: true
          type: string
        - name: groupe_description
          in: query
          required: true
          type: string
        - name: groupe_slug
          in: query
          required: true
          type: string
        - name: location
          in: query
          required: true
          type: string
        - name: type
          in: query
          required: true
          type: boolean
        - name: created
          in: query
          required: true
          type: string
        - name: nb_online_member
          in: query
          required: true
          type: integer
        - name: invited_send
          in: query
          required: true
          type: boolean
        - name: wakiid
          description: waki identifier
          in: query
          required: true
          type: integer
      tags:
        - groups
      responses:
        "200":
          description: group has been add successfully
  
    put:
      summary: This method allows to modify group
      description: Show details about a group
      parameters:
        - name: group_id
          in: query
          required: true
          type: integer
      tags:
        - groups
      responses:
        "200":
          description: Group details
          schema:
            $ref: "#/definitions/show_groups"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
  
    delete:
      summary: This method is used to delete groups into database
      description: This method remove one or more groups in Vairified API database
      parameters:
        - name: group_id
          description: groups identifier
          in: query
          required: true
          type: integer
      tags:
        - groups
      responses:
        "200":
          description: groups has been remove

  /tag:
    post:
      summary: Add a new tag
      description: This method add a new Center of interest in Vairified API database
      parameters:
        - name: tag_id
          in: query
          required: true
          type: integer
        - name: tag_name
          in: query
          required: true
          type: string
        - name: slug
          in: query
          required: true
          type: string
      tags:
        - tag
      responses:
        "200":
          description: tag has been add successfully
  
    put:
      summary: This method allows to modify tags
      description: This method display Center of interest in Vairified API database
      parameters:
        - name: tag_id
          in: query
          required: true
          type: integer
      tags:
        - tag
      responses:
        "200":
          description: tag details
          schema:
            $ref: "#/definitions/show_tag"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
  
    delete:
      summary: This method is used to delete tag into database
      description: This method remove one or more tag in Vairified API database
      parameters:
        - name: tag_id
          description: tag identifier
          in: query
          required: true
          type: integer
      tags:
        - tag
      responses:
        "200":
          description: tag has been remove
  
  /experience:
    post:
      summary: This method adds experience into database
      description: The endpoint of this add a new experience into Vairified API database
      parameters:
        - name: experience_id
          in: query
          required: true
          type: integer
        - name: experience
          in: query
          required: true
          type: string
        - name: created
          in: query
          required: true
          type: string
        - name: wakiid
          in: query
          required: true
          type: integer
        - name: nb_endorsments
          in: query
          required: true
          type: integer
        - name: status
          in: query
          required: true
          type: boolean
        - name: modified
          in: query
          required: true
          type: string
        - name: experiencescategory_id
          in: query
          required: true
          type: integer
        - name: position
          in: query
          required: true
          type: integer
      tags:
        - experience
      responses:
        "200":
          description: experience has been add successfully
  
    put:
      summary: This method allows to modify experience
      description: This method display experiences of a user
      parameters:
        - name: experience_id
          in: query
          required: true
          type: integer
        - name: wakiid
          in: query
          required: true
          type: integer
      tags:
        - experience
      responses:
        "200":
          description: experience detais
          schema:
            $ref: "#/definitions/show_experiences"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
  
    delete:
      summary: This method is used to delete experience into database
      description: This method remove one or more experience in Vairified API database
      parameters:
        - name: experience_id
          description: experience identifier
          in: query
          required: true
          type: integer
      tags:
        - experience
      responses:
        "200":
          description: experience has been remove
definitions:
  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
  show_Profile:
    properties:
      username:
        description: "User's name on vairified"
        type: string
      photo:
        type: string
        description: Image URL of the Vairified user.
      email:
        type: string
        description: Email address of the Vairified user.
      phone:
        description: Phone number of the Vairified user.
        type: string
      country:
        description: Country of the Vairified user.
        type: string
      city:
        description: City of the Vairified user.
        type: string
      lang:
        description: Language of the Vairified user.
        type: string
  show_post:
    properties:
      post_content:
        description: Post content
        type: string
      post_time_response:
        description: response time to a post
        type: string
      post_image:
        description: post image
        type: string
      post_date:
        description: post date
        type: string
      post_lang:
        description: post language
        type: string
      nb_bookmarks:
        description: bookmarks number
        type: integer
      post_type:
        description: post type
        type: integer
      status:
        description: post status
        type: boolean
  show_groups:
    properties:
      groupe_name:
        description: group name
        type: string
      groupe_image:
        description: group image
        type: string
      groupe_description:
        description: group specification
        type: string
      groupe_slug:
        description: group slug
        type: string
      location:
        description: group location
        type: string
      type:
        description: group type
        type: boolean
      created:
        description: group date created
        type: string
      nb_online_member:
        description: number of member online
        type: integer
      invited_send:
        description: send invitations
        type: boolean
  show_tag:
    properties:
      tag_name:
        description: tag name
        type: string
      slug:
        description: tag slug
        type: string
  show_experiences:
    properties:
      experience:
        description: experience specification
        type: string
      created:
        description: date of created experience
        type: string
      nb_endorsments:
        description: number endorsments
        type: integer
      status:
        description: "experience status if it's validated or not"
        type: boolean
      modified:
        description: experience modified date
        type: string
      position:
        description: experience position
        type: integer

**Comment by fehguy** [comment]
Two things.

First, you are probably getting the error when choosing `swagger` from the generate client menu.  That option is really intended for converting swagger specifications from 1.x to 2.0 and downloading the JSON representation.  For the editor's sake, it's really not even needed.  We'll hide it.

Second, there was one defect when generating java clients from your spec.  That's been fixed.

If you see issues in the code generation, please open them here:

https://github.com/swagger-api/swagger-codegen
