### ISSUE TITLE
Incorrect parse of block scalars

### ISSUE THREAD

**Issue by pfebolo** [swagger-api/swagger-editor#375]
Particularly in the description fields, not implemented scalar blocks. It would be interesting to use the command | to interpret carriage returns, I leave an example in YAML and an alternative that I use today.

Hack with HTML
```yaml
paths:
  /ordenesdeproducto:
    post:
      tags:
        - Default
      summary: Crea orden de producto.
      description: <pre>
        Crea una orden de venta de productos. <br>
        Los datos obligatorios son los siguientes<br>
        · codCanal<br>
        · codUsuario<br>
        · identificadorRecurso<br>
        · marcaDescuentoDeSaldo<br>
        · Items (al menos un item)<br>
        &emsp;· codProducto</pre>
```

YAML Pure
```yaml
paths:
  /ordenesdeproducto:
    post:
      tags:
        - Default
      summary: Crea orden de producto.
      description: |
        Crea una orden de venta de productos.
        Los datos obligatorios son los siguientes
        · codCanal
        · codUsuario
        · identificadorRecurso
        · marcaDescuentoDeSaldo
        · Items (al menos un item)
          · codProducto
```

**Comment by mohsen1** [comment]
I'm not sure if fully understand your requirement. Could you please explain what is your end goal?

**Comment by pfebolo** [comment]
My goal is to have descriptions in multiple lines, paragraphs with simil tables, etc. In YAML this is possible with the | (verical bar) tag. This tag is not properly parsed by the editor simply does not recognize the line break.  To workarround the problem, I use the HTML tag \<br\>. 

Example
```
paths:
  /ordenesdeproducto:
    post:
      tags:
        - Default
      summary: Crea orden de producto.
      description: |
        Crea una orden de venta de productos.
        Los datos obligatorios son los siguientes.
        Linea 3.
        Linea 4.

```
Result in|
------------ 
### Description

Crea una orden de venta de productos. Los datos obligatorios son los siguientes. Linea 3. Linea 4.



my wish|
------------ 

### Description

Crea una orden de venta de productos.
Los datos obligatorios son los siguientes.
Linea 3.
Linea 4.



regards

**Comment by mohsen1** [comment]
Swagger descriptions are Github flavored Markdown. In this Markdown you need two line breaks for a line break in resulting HTML.

Try this:

```yaml
---
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
  description: |
    # Title
    Crea una orden de venta de productos.
    
    Los datos obligatorios son los siguientes.
paths:
  /:
    get:
      responses:
        200:
          description: OK

```

**Comment by pfebolo** [comment]
Always learn something new, finally the trick was to finish the lines with 2 or more spaces.  
Thank you very much.

**Comment by mohsen1** [comment]
You're welcome! 👍
