### ISSUE TITLE
Exclude library from webpack

### ISSUE THREAD

**Issue by gituserjava** [swagger-api/swagger-editor#3751]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: 08.0.5359.124
 - Method of installation: npm install
 - Swagger-Editor version: 4.6.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
I am looking for a way to exclude a library from bundling with webpack. Is that possible with swagger-editor? I am referring to below which is present in _config-builder.js. If i need to exclude a library from bundling where should it go in the below code?

````
      externals: includeDependencies
        ? {
            esprima: "esprima"
          }
        : ({ request }, cb) => {
            // webpack injects some stuff into the resulting file,
            // these libs need to be pulled in to keep that working.
            var exceptionsForWebpack = ["ieee754", "base64-js"]
            if (
              nodeModules.indexOf(request) !== -1 ||
              exceptionsForWebpack.indexOf(request) !== -1
            ) {
              cb(null, "commonjs " + request)
              return
            }
            cb()
          },
````

**Comment by gituserjava** [comment]
@char0n , I tried to use `externals` (in dev.babel.js) with `__non_webpack_require__` (in my JS file) and it did not work.

The third party libraries are not included in webpack, but at the same time they are not available to use and when opening swagger editor and I get below console error. Please advise.

````

Uncaught ReferenceError: require is not defined 
at . /src/plugins/customcode/index.js (index.js:4:1)
at options.factory (react refresh: 6:1)
at webpack require (bootstrap: 24:1)
at fn (hot module replacement: 62:1)
at options.factory (react refresh:6:1)
at webpack require (bootstrap: 24:1)
at webpack exec (is-plain-object.ms:34:1)
at is-plain-object.mjs: 34:1
at webpackJsonpCallback (jsonp chunk loading:523:1)

````

**Comment by gituserjava** [comment]
@char0n , did you get a chance to look into this?

related : #3752

**Comment by gituserjava** [comment]
Any clue on this?

**Comment by char0n** [comment]
Hi @gituserjava,

> I am looking for a way to exclude a library from bundling with webpack. Is that possible with swagger-editor? 

Nope, you cannot exclude libraries, you can only replace them by either using [externals](https://webpack.js.org/configuration/externals/#externals) or [resolve.fallback](https://webpack.js.org/configuration/resolve/#resolvefallback).

> @char0n , I tried to use externals (in dev.babel.js) with __non_webpack_require__ (in my JS file) and it did not work.
>
>The third party libraries are not included in webpack, but at the same time they are not available to use and when  opening swagger editor and I get below console error. Please advise.

This is they way how `externals` is supposed to work.  I've already answered it in https://github.com/swagger-api/swagger-editor/issues/3752#issuecomment-1465933240


What you need to do is to amend our `externals function`. I'll refer you to webpack documentation https://webpack.js.org/configuration/externals/#function
