### ISSUE TITLE
Create swagger-editor-dist from swagger-editor

### ISSUE THREAD

**Issue by gituserjava** [swagger-api/swagger-editor#3759]
I have downloaded `swagger-editor` v4.6.0 and added a custom plugin (for validators). I ran `npm run dev` and I am able to see my changes working locally. I would like to export swagger editor along with my changes as a dependency free module so that it can be served in a server side project. Which command do I need use to create ````swagger-editor-dist```` from ````swagger-editor```` that will include my changes? Could you please advise?

**Comment by char0n** [comment]
HI @gituserjava,

After you'll did your changes you'll run following commands:

```sh
 $ npm run build
```

After that, there will be a `dist/` folder. Inside this folder following dependency free files will be available:

- swagger-editor-bundle.js
- swagger-editor-bundle.js.map
- swagger-editor-standalone-preset.js
- swagger-editor-standalone-preset.js.map
- swagger-editor.css
- swagger-editor.css.map

You will use those dist fragments in following way:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Swagger Editor</title>
  <link href="./swagger-editor.css" rel="stylesheet">
  <style type="text/css">
    body {
      font-family: Roboto, sans-serif;
      font-size: 9px;
      line-height: 1.42857143;
      color: #444;
      margin: 0px;
    }
  </style>
</head>

<body>
<div id="swagger-editor"></div>

<script src="./swagger-editor-bundle.js"> </script>
<script src="./swagger-editor-standalone-preset.js"> </script>
<script>
  window.onload = function () {
    const editor = SwaggerEditorBundle({
      dom_id: '#swagger-editor',
      layout: 'StandaloneLayout',
      presets: [
        SwaggerEditorStandalonePreset,
      ],
      plugins: [
        SwaggerEditorStandalonePreset.plugins.TopbarNewEditorButton,
      ],
      queryConfigEnabled: true,
    });
    window.editor = editor
  }
</script>
</body>

</html>
```
