### ISSUE TITLE
Can't generate code with default value in spec

### ISSUE THREAD

**Issue by andl** [swagger-api/swagger-editor#376]
I can certainly load following spec into editor but got following error when trying to generate jaxrs code. Comment the last line with `default` can fix this.

code: 500
type:  "unknown"
message:  "something bad happened"

```
---
swagger: '2.0'
info:
  version: 1.0.0
  title: test
  description: test
schemes:
  - http
host: example.com
basePath: /test
paths:
  /:
    get:
      responses:
        200:
          description: Echo GET
          schema:
            $ref: '#/definitions/echo'
definitions:
  echo:
    properties:
      id:
        type: integer
        min: 0
        default: 1 # comment this line then code-gen is ok 
```

**Comment by mohsen1** [comment]
This is an issue with Swagger Code Generator. Please follow up this issue over there. You can run the code locally on your machine and potentially fix it.

**Comment by mohsen1** [comment]
This issue was fixed in upstream project.
