### ISSUE TITLE
SwaggerEditor@next: Does not report error for OAS 3.0.0 definition having GET request with body

### ISSUE THREAD

**Issue by kletnoe** [swagger-api/swagger-editor#3768]
### Q&A (please complete the following information)
 - OS: Win10
 - Browser: Chrome
 - Version: Chrome Version 109.0.5414.75 (Official Build) (64-bit)
 - Method of installation: -
 - Swagger-Editor version: -
 - OpenAPI version: 3.0.0

Example OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  title: Sample API
  version: 0.0.1
paths:
  /users:
    get:
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
```

### Describe the bug you're encountering
Old swagger editor reported errors for OAS 3.0.0 definition having GET request with body
New swagger editor does not.

### To reproduce...
1. Open https://editor-next.swagger.io/
2. Paste opanapi definition above.

### Expected behavior
Swagger editor shows error like it was in old editor.
```
Semantic error at paths./users.get.requestBody
GET operations cannot have a requestBody.
```

### Additional context or thoughts
According to https://swagger.io/docs/specification/describing-request-body/
> Differences From OpenAPI 2.0
> GET, DELETE and HEAD are no longer allowed to have request body because it does not have defined semantics as per [RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.3).

**Comment by char0n** [comment]
Hi @kletnoe,

Thanks for raising this issue.

**OpenAPI 3.0.3** states:

> The request body applicable for this operation. The requestBody is only supported in HTTP methods where the HTTP 1.1 specification [RFC7231](https://tools.ietf.org/html/rfc7231#section-4.3.1) has explicitly defined semantics for request bodies. In other cases where the HTTP spec is vague, requestBody SHALL be ignored by consumers.

**OpenAPI 3.1.0** states:

> The request body applicable for this operation. The requestBody is fully supported in HTTP methods where the HTTP 1.1 specification [RFC7231](https://tools.ietf.org/html/rfc7231#section-4.3.1) has explicitly defined semantics for request bodies. In other cases where the HTTP spec is vague (such as [GET](https://tools.ietf.org/html/rfc7231#section-4.3.1), [HEAD](https://tools.ietf.org/html/rfc7231#section-4.3.2) and [DELETE](https://tools.ietf.org/html/rfc7231#section-4.3.5)), requestBody is permitted but does not have well-defined semantics and SHOULD be avoided if possible.


Given all that, our source of truth is https://www.rfc-editor.org/rfc/rfc7231 which has been obsoleted by https://www.rfc-editor.org/rfc/rfc9110 in June 2022.

So let's assume our source of truth is https://www.rfc-editor.org/rfc/rfc9110.


**GET**, **HEAD** and **DELETE** have no generally defined semantics - we will generate error level `WARNING` that the `requestBody` **SHOULD NOT** be used

**PUT**, **POST** and **PATCH** are just fine with with `requestBody`.

**OPTIONS** and **TRACE** have no mention about `requestBody` semantics and we will generate error level `ERROR`  that `requestBody` **MUST NOT** be used


@kletnoe let me know if it make sense.

**Comment by frantuma** [comment]
fixed in https://github.com/swagger-api/apidom/pull/2978
