### ISSUE TITLE
generate nodejs server - desciption on all methods says Operations about pets

### ISSUE THREAD

**Issue by radicaldrew** [swagger-api/swagger-editor#377]
exports.accountGet = {
  'spec': {
    "description" : "Operations about pets",
    "path" : "/account",
    "notes" : "Get all information on your Account",
    "summary" : "get account info",
    "method": "GET",
    "params" : [].concat([]).concat([]).concat([]),

**Comment by fehguy** [comment]
Can you please open this against swagger-codegen?
