### ISSUE TITLE
SwaggerEditor@next: Parameter Object must contain one the following fields: content, schema apilint(5150001)

### ISSUE THREAD

**Issue by congjunhua** [swagger-api/swagger-editor#3791]
### Q&A
 - OS: [macOS]
 - Browser: [chrome]
 - Version: [109.0.5414.87]
 - Method of installation: [web]
 - Swagger-Editor version: [next]
 - Swagger/OpenAPI version: [Swagger 2.0, OpenAPI 3.0]

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
paths:
  /todos:
    get: 
      tags: 
        - todos
      summary: 查询
      parameters: 
        - $ref: '#/components/parameters/offset'

components: 
  parameters: 
    offset:
      name: offset
      in: query
      description: 跳过的数据数
      schema: 
        type: integer
        format: int64
        minimum: 1
```

### Describe the bug you're encountering
```
Parameter Object must contain one the following fields: content, schemaapilint(5150001)
```

### Screenshots
<img width="768" alt="image" src="https://user-images.githubusercontent.com/95909681/215263942-455419b9-4b95-4898-96d2-e96ee3c43bef.png">

**Comment by char0n** [comment]
Hi @congjunhua,

Thanks for the report. I can succesfully reproduce the issue on OpenAPI 3.1.0 definition. OpenAPI 3.0.x definitions are not affected. Bugfix is on the way...

**Comment by char0n** [comment]
Fix provided upstream in ApiDOM: https://github.com/swagger-api/apidom/pull/2545

**Comment by char0n** [comment]
Fix released in https://github.com/swagger-api/swagger-editor/releases/tag/v5.0.0-alpha.47
