### ISSUE TITLE
Docker commands for local swagger file seems not working again

### ISSUE THREAD

**Issue by MingruiZhangW** [swagger-api/swagger-editor#3799]
### Q&A (please complete the following information)
 - OS: Windows - WSL 2 (ubuntu 20.04)
 - Browser: Chrome
 - Version: 109.0.5414.120
 - Method of installation: docker
 - Swagger-Editor version: Latest
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
Similar to this [issue](https://github.com/swagger-api/swagger-editor/issues/2177), by running the following command

```
docker run -d -p 4567:8080 -v $(pwd):/tmp -e SWAGGER_FILE=/tmp/swagger.json swaggerapi/swagger-editor
```

the file does get copied to ```/usr/share/nginx/html/``` and I can see in the ```index.html``` file, the following line is added

```
url: '/swagger.json '
```

but it just won't open it on start.

### Expected behavior
Swagger editor will start using the supplied swagger file.

Thank you!

**Comment by char0n** [comment]
Hi @MingruiZhangW,

Are you trying the docker on  `master` or `next` branch?

**Comment by char0n** [comment]
@MingruiZhangW need a precise version of docker image, otherwise I have to close this issue due to insufficient info.

**Comment by MingruiZhangW** [comment]
Hi, sorry, just tried the master branch again, and now it works

I used ```docker pull swaggerapi/swagger-editor``` to pull the image five days ago, so it should be the image with the tag latest,

but somehow it worked so I will close it for now if I do not have more info
