### ISSUE TITLE
Error when trying to generate clients from yaml

### ISSUE THREAD

**Issue by denodaeus** [swagger-api/swagger-editor#382]
I have an error when trying to export a client (tried both android and java) from my yaml definition.  It's pretty vague:

Unable to build target: A target generation was attempted, but no files were created!

Details:

 Object
code: 1
type:  "error"
message:  "Unable to build target: A target generation was attempted, but no files were created!"

The yaml that i'm using can be seen on this gist:
https://gist.github.com/denodaeus/9f06caa104e992802ae2

Not exactly sure how to go about debugging this.

Thanks!

**Comment by mohsen1** [comment]
Which client you're trying to generate?

**Comment by fehguy** [comment]
Your routes are using ruby-style syntax (I think).  You need to use curly brackets and declare the parameter item in the `parameters` section

**Comment by denodaeus** [comment]
I tried both android and java.
@fehguy, I'll give that a try, but when using the sample app (which is where I derived my yaml), there weren't curly braces around the params, and my export seems to work for both Java and android clients.

**Comment by denodaeus** [comment]
I figured it out.  Basically, line 207 in the gist, I was creating a yaml list for "items", with a $ref to my model.  It seems i needed to drop the "-" declaring an item in the yaml list.

207          - $ref: '#/definitions/PendingConnection'

This was a part of:

      pendingConnections:
        type: array
        items:
          - $ref: '#/definitions/PendingConnection'
        description: users pending connections

Although the validator for the swagger-api editor (which is what I'm trying this out on, great project by the way!) seemed to be fine with it, when exporting a client it would tank out (interestingly enough the server export for nodejs still "worked").

Not sure if there's anything else to do here, but it was unexpected behavior.  Thanks!

**Comment by mohsen1** [comment]
@whitlockjc Don't we validate models (JSON Schema) with JSON Schema meta schema in SwaggerTools? The schema @denodaeus provided doesn't seem valid.

**Comment by whitlockjc** [comment]
While this is valid, I'm sure it's not what was intended by the user.  `items` can be an object or an array: https://github.com/swagger-api/swagger-spec/blob/master/schemas/v2.0/schema.json#L951

**Comment by mohsen1** [comment]
Oh I see. For arrays that can have more than one type of item the `items` can be an array of multiple schemas.

**Comment by webron** [comment]
In Swagger, we only support `items` being an object describing a single option. It's true JSON Schema allows it to be an array of options, we just don't support it.
