### ISSUE TITLE
Allow loose JSON Schemas (additionalProperties: true)

### ISSUE THREAD

**Issue by splendf** [swagger-api/swagger-editor#383]
Hi,

We will have some a field named metadata where the content will be defined by the user app.
<code>metadata : {
"key1" : "value1",
"key2" : "value2",
etc.
}</code>

Each key/value will be defined by the user. So how I can do that in SWAGGER Editor ?

Thx in advance,

**Comment by mohsen1** [comment]
Your schema should be something like this:
```yaml
  metadata:
    additionalProperties: true
```
But the form generator does not support `"additionalProperties": true` where you can add unlimited key/value pairs. For now if you put the request data in `body` you can provide raw json for the request.

I'll replace form generator with [Angular JSON Schema Form](https://github.com/mohsen1/angular-json-schema-form) where it's possible to have `additionalProperties: true`
