### ISSUE TITLE
SwaggerEditor@next: npm install v5.0, npm ERR! 401 Unauthorized 

### ISSUE THREAD

**Issue by Honghe** [swagger-api/swagger-editor#3836]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 - Method of installation: npm install
 - Swagger-Editor version: 5.0 alpha46
 - Swagger/OpenAPI version: OpenAPI 3.0

### Describe the bug you're encountering
After checkout branch `5.0.0 alpha46` and `npm install`, The following bug were encountered:
```
...
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://npm.pkg.github.com/download/@swagger-api/apidom-reference/0.67.0/d665605b839ee021271b621bf837a6095201e107 - authentication token not provided

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\x\AppData\Local\npm-cache\_logs\2023-02-11T16_43_56_985Z-debug-0.log
```

### To reproduce...

1. git checkout next
2. npm install

**Comment by char0n** [comment]
Hi @Honghe,

Please review our local dev setup instructions: https://github.com/swagger-api/swagger-editor/tree/next#development

You'll find your answers there. Cheers.
