### ISSUE TITLE
SwaggerEditor@next: cannot install npm package

### ISSUE THREAD

**Issue by zbigniew-malcherczyk-tg** [swagger-api/swagger-editor#3840]
<img width="875" alt="Screenshot 2023-02-13 at 17 46 53" src="https://user-images.githubusercontent.com/124783578/218519414-c1747b5e-3972-4634-91ab-68c5f140bbe6.png">

The described way of accessing swagger-editor via npm does not work. Even when I add the github token I don't have permission to it.

**Comment by char0n** [comment]
Hi @zbigniew-malcherczyk-tg,

Just this morning I've refreshed our documentation located at: https://github.com/swagger-api/swagger-editor/tree/next#prerequisites

In your case, make sure prerequisites as present in you OS: https://github.com/swagger-api/swagger-editor/blob/next/README.md#prerequisites.

The continue with installation instructions here: https://github.com/swagger-api/swagger-editor/blob/next/README.md#installation

There shouldn't be any issues. 

PS: Hope the docs is a bit clearer now.
