### ISSUE TITLE
Swagger-editor from virtual directory

### ISSUE THREAD

**Issue by doneal1992** [swagger-api/swagger-editor#385]
Is it possible to create a virtual directory in IIS and point it to the swagger-editor folder, and run the swagger editor when you point to that url in your browser?

I am currently trying it, but when I navigate  myurl/swaggereditor, it appears as it will load and then All i end up with is a white screen.

**Comment by mohsen1** [comment]
If you want to edit Swagger files in that folder you need to enable backend and run a server that work as a backend for Swagger Editor.  Please read the docs [here](https://github.com/swagger-api/swagger-editor/blob/master/docs/config.md)
