### ISSUE TITLE
如何批量折叠或展开目录？

### ISSUE THREAD

**Issue by congjunhua** [swagger-api/swagger-editor#3868]
### Q&A (please complete the following information)
 - OS: [macOS]
 - Browser: [chrome]
 - Version: [109.0.5414.87]
 - Method of installation: [web]
 - Swagger-Editor version: [next]
 - Swagger/OpenAPI version: [Swagger 2.0, OpenAPI 3.0]

### How can we help?

打开时默认展开所有目录，有没有办法一键折叠所有目录？

目录很多的情况下，每次打开都要手动依次折叠，很不友好。

**Comment by char0n** [comment]
I'm sorry I'm closing this. Please create an issue in English language.

**Comment by congjunhua** [comment]
> 

When opening, all directories are expanded by default. Is there any way to collapse all directories in one click?

In the case of many directories, I have to manually fold them in turn each time you open them, which is very unfriendly.
