### ISSUE TITLE
Editor not show invliad $ref in definitions

### ISSUE THREAD

**Issue by nvcnvn** [swagger-api/swagger-editor#388]
For example in I have this in definitions area:
```yaml
  InternshipResultModel:
    properties:
      ID:
        type: string
      Opportunity:
          $ref: "#/definitions/OpportunityModel"
      Status:
        type: integer
      Feedback:
        type: string
      Review:
        schema:
          $ref: "#/definitions/ReviewModel"
```
The editor won't show any warrning or error message.
But when I check whit sagger-ui debug (http://online.swagger.io/validator/debug?url=...) I get this message:
```json
[
    {
        "level": "error",
        "domain": "validation",
        "keyword": "additionalProperties",
        "message": "object instance has properties which are not allowed by the schema: [\"schema\"]",
        "schema": {
            "loadingURI": "http://swagger.io/v2/schema.json#",
            "pointer": "/definitions/schema"
        },
        "instance": {
            "pointer": "/definitions/InternshipResultModel/properties/Review"
        }
    }
]
```

**Comment by mohsen1** [comment]
I don't fully understand what the issue is here. Can you paste your full spec or provide a full spec that fully demonstrate the issue?

**Comment by nvcnvn** [comment]
OK, here is the full simple spec that can be use http://pastebin.com/raw.php?i=31dcfEdg and the detail:
Case 1:
* Go to http://editor.swagger.io/#/
* Use "File" > "Paste JSON..."
You can see the spec is all OK.
Case 2:
* Go to http://online.swagger.io/validator/debug?url=http://pastebin.com/raw.php?i=31dcfEdg
Now you see that the spec is invalid.

So I think that swagger-editor bug since it don't give any warnning.

**Comment by mohsen1** [comment]
I see no problem in your spec. It's the validator that doesn't resolve $refs properly. Please follow up this issue [here](https://github.com/swagger-api/validator-badge/issues/16)

**Comment by nvcnvn** [comment]
@mohsen1 I think that not issue of validator but rather issue with editor.
I expect the editor show some error messages.

**Comment by mohsen1** [comment]
Yes editor uses SwaggerTools to check for errors and current SwaggerTools in editor uses an older Swagger schema. It will be fixed by https://github.com/swagger-api/swagger-editor/issues/389
