### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by avril-verhaeghen** [swagger-api/swagger-editor#390]
Hello,

I'm having a build failure while running npm start. 

"Failed at the swagger-editor-src@2.9.2 bower-install script 'bower install'.

Anyone has this too?

**Comment by mohsen1** [comment]
What platform are you running at? (Windows, Linux or Mac)

**Comment by avril-verhaeghen** [comment]
Both Windows7 natively on a laptop and I have also a macbook pro with OS X 10.10.2. Both have the same issue.

**Comment by mohsen1** [comment]
What version of Node are you using?

As you can see [here](https://travis-ci.org/swagger-api/swagger-editor) build is passing so I don't think it's an issue with Swagger Editor itself. 

Please get the latest `master` from Github and try again and let me know if you're still having issues.

**Comment by avril-verhaeghen** [comment]
on my mac v0.10.33, my windows, don't know. The windows is of my job. Don't have access to it at home.

**Comment by mohsen1** [comment]
Could you paste your entire stdout here so we can take a look.

Instead of `npm start` you can also do the following:

```shell
npm install -g bower grunt-cli
npm install
bower install
grunt serve
```
Maybe above commands works for you

**Comment by avril-verhaeghen** [comment]
Hey thanks! It works on Windows now. Not on my Mac for the moment. On my Mac I updated Node and now I'm getting issues with Bower, so nothing to do with Swagger. 

The important thing is that it's running on the Windows machine ;).

**Comment by wangcansun** [comment]
@mohsen1 
not work on centos...

it shows running "watch" task and forever.

`[root@localhost swagger-editor]# PORT=8765 grunt serve
Running "serve" task

Running "clean:server" (clean) task
>> 1 path cleaned.

Running "wiredep:app" (wiredep) task

Running "less:server" (less) task
>> 1 stylesheet created.

Running "autoprefixer:dist" (autoprefixer) task
>> 1 autoprefixed stylesheet created.

Running "connect:livereload" (connect) task
Started connect web server on http://localhost:8765

Running "watch" task
Waiting...`
