### ISSUE TITLE
Empty parameters array in swagger 2.0 spec yields a validation error

### ISSUE THREAD

**Issue by who** [swagger-api/swagger-editor#395]
If you have a HTTP GET path defined with an empty parameters array, the built-in validator will complain.

Here's a yaml block you can use for repro:
```
swagger: '2.0'
info:
  version: "0.0.0"
  title: "My bug repro API"
paths:
  /persons:
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets `Person` objects.
        Optional query param of **size** determines
        size of returned array
      # This is an empty parameters array
      parameters: []
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfPersons
            type: array
            items:
              title: Person
              type: object
              properties:
                name:
                  type: string
                single:
                  type: boolean
```

The validator message contains this:

Array is too short (0), minimum 1
code:  "ARRAY_LENGTH_SHORT"
message:  "Array is too short (0), minimum 1"
 path: Array [4]
0:  "paths"
1:  "/persons"
2:  "get"
3:  "parameters"
description:  "The parameters needed to send a valid API call."
level: 900

It appears this issue is similar to https://github.com/swagger-api/validator-badge/issues/11

**Comment by who** [comment]
After further digging, this is a bug surfaced from the swagger 2.0 spec as it is defined by [apigee-127/swagger-tools](https://github.com/apigee-127/swagger-tools/blob/6803225cb9286e201591b6ab3f2ff8e7533767f4/schemas/2.0/schema.json#L1379).

**Comment by mohsen1** [comment]
The schema has updated to fix this issue. It will get resolved when we update to the latest swagger-tools which has latest schema.

**Comment by mohsen1** [comment]
@whitlockjc I thought you updated the schema in swagger-tools already. Please open a ticket in swagger-tools for updating the schema in the next release and link it to this issue if it's not the case

**Comment by whitlockjc** [comment]
I did not, I've not put any time to swagger-tools due to other projects.  I'll get it fixed tomorrow.

**Comment by who** [comment]
@mohsen1 

It looks like swagger-tools has updated the schema.

**Comment by mohsen1** [comment]
@who it's not published yet. @whitlockjc

**Comment by mohsen1** [comment]
Fix for this is deployed now.

**Comment by who** [comment]
:+1: Thank you!

**Comment by ayushidalmia** [comment]
I still get the error.
https://gist.github.com/ayushidalmia/a903db41ece0071747601e8a64b35007

**Comment by webron** [comment]
That has nothing to do with the topic of this issue.

**Comment by netrounds-oleg-b** [comment]
Getting the same problem. The schema is defined as:
```
TestAgentSchema = {
    'properties': {
        'foo': {
            'maxLength': 100,
            'minLength': 1,
            'type': 'string'
        },
        'bar': {
            'maxLength': 100,
            'minLength': 1,
            'type': 'string'
        }
    },
    'required': [
        'foo',
    ],
    'type': 'object'
}
```
When trying to POST:
```
{
    "foo":"Foo",
    "bar":""
}
```
getting:
![image](https://user-images.githubusercontent.com/10723972/31935471-95f46db8-b8b7-11e7-8288-775ec2bd6f41.png)
