### ISSUE TITLE
 Flickering preview collapse animation in Safari 8.0.5

### ISSUE THREAD

**Issue by ypomortsev** [swagger-api/swagger-editor#397]
[See here](https://www.gfycat.com/ShowyCornyHoiho)

**Comment by mohsen1** [comment]
Hmmm... that's new. Is it happening in Chrome too?

**Comment by illicium** [comment]
Doesn't flicker in Chrome or FF

**Comment by mohsen1** [comment]
Maybe we should use ngAnimate for this instead of class toggling.

**Comment by webron** [comment]
Closing as a very old ticket. Please open a new ticket if still relevant.
