### ISSUE TITLE
Font size changes from default when switching ace theme

### ISSUE THREAD

**Issue by illicium** [swagger-api/swagger-editor#399]
Default settings have an increased font size which is different from the default value in the Settings sidebar. Switching theme resets font size to the one in the Settings sidebar.

[See here](https://gfycat.com/RigidMajesticGardensnake)

**Comment by mohsen1** [comment]
It's because themes have `fontSize` option in them. I think we should listen to `themeWillChange` (if exists) and grab the font size before change and apply it after theme change.
