### ISSUE TITLE
SwaggerEditor@next: false positive in linting JSON Schema

### ISSUE THREAD

**Issue by quizwedge** [swagger-api/swagger-editor#4026]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: Chrome
 - Version: 111.0.5563.110
 - Method of installation: None. This is at https://editor-next.swagger.io/
 - Swagger-UI version: Unknown
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.3
info:
  title: Test
  version: 1.0.0
components:
  schemas:
    ObjectOne:
      type: object
      properties:
        propertyOne:
          type: string
    ObjectTwo:
      type: object
      properties:
        propertyTwo:
          type: string
paths:
  /test:
    post:
      requestBody: 
        content:
          application/json:
            schema: 
              oneOf:
                - $ref: '#/components/schemas/ObjectOne'
                - $ref: '#/components/schemas/ObjectTwo'
        required: true
      responses:
        '204':
          description: Successful operation
```

Swagger-UI configuration options:
None

### Describe the bug you're encountering
The editor shows an error on line 23 saying, "oneOf must be a non-empty array of schemas" but it is an array of schemas.

### To reproduce...

1. Go to https://editor-next.swagger.io/.
2. Enter the YAML above.
3. See error.

### Expected behavior
No errors or warnings.

### Screenshots
<img width="1777" alt="OAS" src="https://user-images.githubusercontent.com/885118/229574422-f397179f-47ac-4b23-a179-92e75bef0a25.png">

**Comment by diegorendon** [comment]
I have the same issue too.

**Comment by jmo927** [comment]
Same issue with anyOf, allOf, and oneOf

**Comment by xdubx** [comment]
Same here.

```
openapi: 3.0.0
servers:
  - url: "http://localhost:3000/api/v1"
    variables: {}
info:
  description: Test
  version: 1.0.0
  title: Test
paths:
  /pets:
    patch:
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Cat'
                - $ref: '#/components/schemas/Dog'
      responses:
        '200':
          description: Updated
components:
  schemas:
    Dog:
      type: object
      properties:
        bark:
          type: boolean
        breed:
          type: string
          enum: [Dingo, Husky, Retriever, Shepherd]
    Cat:
      type: object
      properties:
        hunts:
          type: boolean
        age:
          type: integer

```

Line | Description
-- | --
15 | oneOf must be a non-empty array of schemas


From the example https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/#anyof

**Comment by Brunnn** [comment]
Any updates on this? this is stopping me from using the api-dom validator github action, because my definition is right, but the workflow just throws those "errors"...
```json
"responses": {
  "200": {
      "description": "Ok",
      "content": {
          "application/json": {
              "schema": {
                  "allOf": [
                      {
                          "$ref": "#/components/schemas/CursorPaginationBase"
                      },
                      {
                          "properties": {
                              "data": {
                                  "type": "array",
                                  "items": {
                                      "$ref": "#/components/schemas/ProductResource"
                                  }
                              }
                          },
                          "type": "object"
                      }
                  ]
              }
          }
      }
  },
```
![image](https://github.com/swagger-api/swagger-editor/assets/42523274/791f577a-a4d1-463d-9c64-8d1b67359494)

**Comment by char0n** [comment]
It looks like the main issue is with `allOf`, `oneOf` and `anyOf` keywords. I'll try to see if I can provide a quick bug fix for those.

**Comment by goors** [comment]
This makes problem in generator as well. If there is an error such as this, $ref properties will not be generated (swift5).

For example in some model i have, among other stuff:
```

"Text": {
     "type": "string"
},
"Data": {
    "type": "string"
},
"Level": {
    "nullable": true,
    "oneOf": [
         {
               "$ref": "#/components/schemas/UserAdventureLevel"
         }
     ]
}
```

generator will ignore that $ref and it will only generate properties before or after.

**Comment by char0n** [comment]
@goors, if by `generator` you're referring to the [swagger-codegen](https://github.com/swagger-api/swagger-codegen) please create an issue at that repo.

**Comment by frantuma** [comment]
fixed by https://github.com/swagger-api/apidom/pull/2987

**Comment by Brunnn** [comment]
Is this really fixed? I've tested on https://editor-next.swagger.io/ the example usage of the `oneOf` presented in the [docs](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/):
```yaml
openapi: "3.0.0"
info:
  title: Simple API overview
  version: 2.0.0
paths:
  /pets:
    patch:
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Cat'
                - $ref: '#/components/schemas/Dog'
      responses:
        '200':
          description: Updated
components:
  schemas:
    Dog:
      type: object
      properties:
        bark:
          type: boolean
        breed:
          type: string
          enum: [Dingo, Husky, Retriever, Shepherd]
    Cat:
      type: object
      properties:
        hunts:
          type: boolean
        age:
          type: integer
```
Still giving the same error:
![image](https://github.com/swagger-api/swagger-editor/assets/42523274/6f36c72f-90a0-495c-ac90-d317eae0d935)

**Comment by char0n** [comment]
@Brunnn It's been fixed but haven't been released and deployed yet. ETA for release/deploy today/tommorow.

**Comment by char0n** [comment]
@Brunnn are you able to use api-dom validator github action now?

**Comment by Brunnn** [comment]
Yes, its working perfect now! Thanks @char0n.
