### ISSUE TITLE
npm start in project is not working 

### ISSUE THREAD

**Issue by timecommunication** [swagger-api/swagger-editor#4068]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-Editor version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-Editor configuration options:
```js
SwaggerEditor({
  // your config options here
})
```

```
?yourQueryStringConfig
```

### Describe the bug you're encountering

When use `npm install --save-dev` in project , I got these error:

![屏幕截图 2023-04-27 103349](https://user-images.githubusercontent.com/19165258/234745321-df535792-50f3-4673-b9fd-e478835c423f.png)

![屏幕截图 2023-04-27 103403](https://user-images.githubusercontent.com/19165258/234745325-87f87c02-6207-4be2-8576-1415087a2001.png)

Are there any conflict in upstream ?

**Comment by char0n** [comment]
Hi @timecommunication,

SwaggerEditor@4 is using very old version of react-ace which is officially not compatible with react@17 (which the editor uses as well), but unofficially it's fully compatible. 

To get around this issue, use [--legacy-peer-deps](https://docs.npmjs.com/cli/v9/commands/npm-ci#strict-peer-deps) option while installing dependencies.

```sh
$ npm install --legacy-peer-deps
```

**Comment by timecommunication** [comment]
@char0n 

I tried `npm install --legacy-peer-deps` and `npm audix fix`, it does not work.


![屏幕截图 2023-05-04 155921](https://user-images.githubusercontent.com/19165258/236144886-9f078122-6a1c-41c6-b649-8d9f0d86b51d.png)

**Comment by char0n** [comment]
@timecommunication,

Could you describe in details what you're trying to do? Did you clone this repo and tried to run `npm install`? What Node.js version did you use? I'm not really sure what you're doing. 

SwaggerEditor@4 installs without any issues with `--legacy-peer-deps` option on Node.js >= 16.13.x

**Comment by char0n** [comment]
Hi @Luengonch,

Would you mind issuing a PR and removing the unnecessary `prestart` npm script?
