### ISSUE TITLE
Unable to launch Swagger editor on Windows 8.1

### ISSUE THREAD

**Issue by VenkateshSrini** [swagger-api/swagger-editor#407]
Hi,

I'm unable to launch the Swagger editor on Windows 8.1. I tried these both from Node.js command prompt as well as Git Bash. I have attached the npm log of the same. Please help me in this regard
```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   'C:\\Users\\333478\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.7.1
3 info using node@v0.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart swagger-editor-src@2.9.2
6 verbose unsafe-perm in lifecycle true
7 info swagger-editor-src@2.9.2 Failed to exec prestart script
8 verbose stack Error: swagger-editor-src@2.9.2 prestart: `npm run bower-install`
8 verbose stack Exit status 1
8 verbose stack     at EventEmitter.<anonymous> (C:\Users\333478\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:213:16)
8 verbose stack     at EventEmitter.emit (events.js:110:17)
8 verbose stack     at ChildProcess.<anonymous> (C:\Users\333478\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:14:12)
8 verbose stack     at ChildProcess.emit (events.js:110:17)
8 verbose stack     at maybeClose (child_process.js:1008:16)
8 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
9 verbose pkgid swagger-editor-src@2.9.2
10 verbose cwd E:\Venkatesh_Mob\APIGEE\Documentation\swagger-editor-master
11 error Windows_NT 6.3.9600
12 error argv "node" "C:\\Users\\333478\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
13 error node v0.12.0
14 error npm  v2.7.1
15 error code ELIFECYCLE
16 error swagger-editor-src@2.9.2 prestart: `npm run bower-install`
16 error Exit status 1
17 error Failed at the swagger-editor-src@2.9.2 prestart script 'npm run bower-install'.
17 error This is most likely a problem with the swagger-editor-src package,
17 error not with npm itself.
17 error Tell the author that this fails on your system:
17 error     npm run bower-install
17 error You can get their info via:
17 error     npm owner ls swagger-editor-src
17 error There is likely additional logging output above.
18 verbose exit [ 1, true ]
```

**Comment by mohsen1** [comment]
please do the delete `node_modules` and `app/bower_components`  folders and clean your npm cache (`npm cache clean`) and try again.

**Comment by mohsen1** [comment]
I did investigate this issue. For running in Windows:

* Have `node` and `npm` in your `PATH`
* Have `git` in your `PATH`. Because bower is using git to fetch some of dependencies. If you have **Git Bash** use that for running `npm start`, otherwise make sure you have `git` command working in your CLI
* When you run `npm start` Swagger Editor will make a new build, run the server and launch the browser to open `http://0.0.0.0:8080`. This is for Docker to work properly. In Windows this URL might not work. You can navigate your browser to `http://localhost:8080` or `http://127.0.0.1:8080` to make it work.

**Comment by VenkateshSrini** [comment]
Hi Mohsen,

Sorry for delayed reply. I tried this again today and I'm still unable to install the same. Please see the log below

0 info it worked if it ends with ok
1 verbose cli [ 'e:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'e:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart swagger-editor-src@2.9.2
6 verbose unsafe-perm in lifecycle true
7 info swagger-editor-src@2.9.2 Failed to exec prestart script
8 verbose stack Error: swagger-editor-src@2.9.2 prestart: `npm run bower-install`
8 verbose stack Exit status 1
8 verbose stack     at EventEmitter.<anonymous> (e:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
8 verbose stack     at EventEmitter.emit (events.js:110:17)
8 verbose stack     at ChildProcess.<anonymous> (e:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
8 verbose stack     at ChildProcess.emit (events.js:110:17)
8 verbose stack     at maybeClose (child_process.js:1008:16)
8 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
9 verbose pkgid swagger-editor-src@2.9.2
10 verbose cwd e:\Venkatesh_Mob\APIGEE\Documentation\swagger
11 error Windows_NT 6.3.9600
12 error argv "e:\\Program Files\\nodejs\\node.exe" "e:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
13 error node v0.12.0
14 error npm  v2.5.1
15 error code ELIFECYCLE
16 error swagger-editor-src@2.9.2 prestart: `npm run bower-install`
16 error Exit status 1
17 error Failed at the swagger-editor-src@2.9.2 prestart script 'npm run bower-install'.
17 error This is most likely a problem with the swagger-editor-src package,
17 error not with npm itself.
17 error Tell the author that this fails on your system:
17 error     npm run bower-install
17 error You can get their info via:
17 error     npm owner ls swagger-editor-src
17 error There is likely additional logging output above.
18 verbose exit [ 1, true ]


I have tired all the steps that you have provided. but nothing works :(

**Comment by VenkateshSrini** [comment]
hi Moshen,

I had a doubt saying that it could be because of python 27 dependency. I even installed that. Added that to my PATH Variable in windows and tried  the same. But that also failed. Now the Git is also added to my path variable and that was also not successful. Can you provide some insights here
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   'C:\\Users\\333478\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.8.3
3 info using node@v0.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart swagger-editor-src@2.9.2
6 verbose unsafe-perm in lifecycle true
7 info swagger-editor-src@2.9.2 Failed to exec prestart script
8 verbose stack Error: swagger-editor-src@2.9.2 prestart: `npm run build`
8 verbose stack Exit status 1
8 verbose stack     at EventEmitter.<anonymous> (C:\Users\333478\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:213:16)
8 verbose stack     at EventEmitter.emit (events.js:110:17)
8 verbose stack     at ChildProcess.<anonymous> (C:\Users\333478\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
8 verbose stack     at ChildProcess.emit (events.js:110:17)
8 verbose stack     at maybeClose (child_process.js:1008:16)
8 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
9 verbose pkgid swagger-editor-src@2.9.2
10 verbose cwd E:\Venkatesh_Mob\APIGEE\Documentation\swagger-editor
11 error Windows_NT 6.3.9600
12 error argv "node" "C:\\Users\\333478\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
13 error node v0.12.0
14 error npm  v2.8.3
15 error code ELIFECYCLE
16 error swagger-editor-src@2.9.2 prestart: `npm run build`
16 error Exit status 1
17 error Failed at the swagger-editor-src@2.9.2 prestart script 'npm run build'.
17 error This is most likely a problem with the swagger-editor-src package,
17 error not with npm itself.
17 error Tell the author that this fails on your system:
17 error     npm run build
17 error You can get their info via:
17 error     npm owner ls swagger-editor-src
17 error There is likely additional logging output above.
18 verbose exit [ 1, true ]

**Comment by mohsen1** [comment]
I tried `npm start` on my Windows VM and it worked. I'm not sure why it's not working in your machine but there is a safer way of running `npm start` that doesn't involve a lot of npm script magic.

Please do the following:

1. Delete `node_modules` and `app/bower_component` folders
2. Get the latest in master via Git: `git pull origin master`
3. Run following commands:
  ```
npm i -g bower grunt-cli 
npm i
bower i
grunt build
grunt serve:dist

  ```
