### ISSUE TITLE
nodejs generator : /docs doesnt show all operations

### ISSUE THREAD

**Issue by Cooker-Monster** [swagger-api/swagger-editor#408]
Hi all and thanks for this great job !,
I know that embeded generators are in alpha stage but I have just noticed the following behavior : 
with nodejs generated code, UI (with /docs) shows only the last operation for each path.

for exemple : 
- /pet 
  - GET 
  - PUT 

the unique operation shown will be the PUT
Thx !

**Comment by mohsen1** [comment]
This is a problem in swagger-codegen project. I've moded this issue there (https://github.com/swagger-api/swagger-codegen/issues/652). Please include your entire swagger description there.

**Comment by Cooker-Monster** [comment]
Hi Mohsen,

Sorry !
I thought that generators from editor were embeded (as the generated code
don't looks the same as codegen command line).
Regards,
Arnaud

2015-04-16 19:08 GMT+02:00 Mohsen Azimi <notifications@github.com>:

**Comment by mohsen1** [comment]
Hmmm... Maybe it's already fixed but not yet deployed? @fehguy

**Comment by Cooker-Monster** [comment]
Yes, maybe ...

as editor uses the online generator here (as you know !) :
http://generator.swagger.io/#!/servers/
and this UI have a link which points out this github ref :
https://github.com/swagger-api/swagger-codegen
<https://github.com/wordnik/swagger-generator>I would say that the
differencies would be very small (mainly patches) but what is generated
both sides is very different.

for instance, I have checked dependencies for each one:

- nodejs project generated with editor option:

    - "connect": "^3.2.0",
    - "swagger-tools": "0.8.*"

- nodejs project generated with codegen (java tool command line):

    - "swagger-node-express" : ">= 2.0.x"
    - "connect" : ">= 1.8.x"
    - "cors" : "2.1.1"
    - "express" : "3.x"

And all the code also very different both sides

I'm a little bit dissapointed ...
Sorry.
Regards,
Arnaud




2015-04-16 23:09 GMT+02:00 Mohsen Azimi <notifications@github.com>:

**Comment by mohsen1** [comment]
@Cooker-Monster either way it's an issue in the swagger-codegen please follow up in https://github.com/swagger-api/swagger-codegen/issues/652. Most of codegen stuff is community driven. You might want to adopt node.js codegen and make it great. That will benefit everyone!

**Comment by Cooker-Monster** [comment]
sure !
thx

2015-04-17 0:22 GMT+02:00 Mohsen Azimi <notifications@github.com>:
