### ISSUE TITLE
instagram.yaml got error response

### ISSUE THREAD

**Issue by setiawand** [swagger-api/swagger-editor#409]
dear swagger dev,
i tried instagram.yml but not getting any result, only receive error and undefined Header
already set client_id etc.

did i miss something?

thanks

**Comment by mohsen1** [comment]
* Instagram API example is not yet completed
* From what I understand you're having an issue in "try this operation" and that's probably CORS issue. Read this document https://github.com/swagger-api/swagger-editor/blob/master/docs/cors.md

**Comment by setiawand** [comment]
‎Thanks a lot :)

Sent from my BlackBerry 10 smartphone on the Telkomsel network.
From: Mohsen Azimi
Sent: Friday, 17 April 2015 21:56
To: swagger-api/swagger-editor
Reply To: swagger-api/swagger-editor
Cc: Deni Setiawan
Subject: Re: [swagger-editor] instagram.yaml got error response (#409)


* Instagram API example is not yet completed
* From what I understand you're having an issue in "try this operation" and that's probably CORS issue. Read this document https://github.com/swagger-api/swagger-editor/blob/master/docs/cors.md

---
