### ISSUE TITLE
QUOTED TEXT IN YAML FILE

### ISSUE THREAD

**Issue by BroadbentT** [swagger-api/swagger-editor#4098]
Hi.

I was wondering when we would get the .yaml 'resolved' export functionality, as shown within the new website version?

I am trying to get a file version that is readable by fencer - 'https://github.com/abunuwas/fencer' which likes the text to be quoted within the .yaml file. I can only achieve this via your website version at the moment, would like to be able to achieve that locally as well. 

Thanks.

**Comment by char0n** [comment]
Hi @BroadbentT,

The YAML format that you're interested in is provided for SwaggerEditor via [ApiDOM](https://github.com/swagger-api/apidom). This version of YAML format that ApIDOM produces is valid YAML 1.2 meant for machine (not-human) consumption.

You can achieve the format locally by using ApiDOM:

```sh
$ npm i @swagger-api/apidom-parser-adapter-yaml-1-2 @swagger-api/apidom-core
```

```js
import { toYAML } from '@swagger-api/apidom-core';
import { parse } from '@swagger-api/apidom-parser-adapter-yaml-1-2';

const parseResult = await parse('prop: value');
const yaml = toYAML(parseResult.result);

console.dir(yaml);
```

To speed things up, I suggest you use [js-yaml](https://www.npmjs.com/package/js-yaml) parser:

```js
import { toYAML, ObjectElement } from '@swagger-api/apidom-core';
import YAML from 'js-yaml';

const parseResult  = YAML.load('prop: value');
const apidom = ObjectElement.refract(parseResult);
const yaml = toYAML(apidom);

console.dir(yaml);
```
