### ISSUE TITLE
sudo npm run build failed!

### ISSUE THREAD

**Issue by tlimpanont** [swagger-api/swagger-editor#411]
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@2.7.6
3 info using node@v0.12.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild swagger-editor-src@2.9.2
6 verbose unsafe-perm in lifecycle true
7 info swagger-editor-src@2.9.2 Failed to exec prebuild script
8 verbose stack Error: swagger-editor-src@2.9.2 prebuild: `npm run bower-install`
8 verbose stack Exit status 1
8 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
8 verbose stack     at EventEmitter.emit (events.js:110:17)
8 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
8 verbose stack     at ChildProcess.emit (events.js:110:17)
8 verbose stack     at maybeClose (child_process.js:1008:16)
8 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
9 verbose pkgid swagger-editor-src@2.9.2
10 verbose cwd /home/tlimpanont/Development/swagger-editor-master
11 error Linux 3.13.0-24-generic
12 error argv "node" "/usr/local/bin/npm" "run" "build"
13 error node v0.12.1
14 error npm  v2.7.6
15 error code ELIFECYCLE
16 error swagger-editor-src@2.9.2 prebuild: `npm run bower-install`
16 error Exit status 1
17 error Failed at the swagger-editor-src@2.9.2 prebuild script 'npm run bower-install'.
17 error This is most likely a problem with the swagger-editor-src package,
17 error not with npm itself.
17 error Tell the author that this fails on your system:
17 error     npm run bower-install
17 error You can get their info via:
17 error     npm owner ls swagger-editor-src
17 error There is likely additional logging output above.
18 verbose exit [ 1, true ]

**Comment by mohsen1** [comment]
What operation system you're on? You shouldn't require `sudo`. You can run the following to start from scratch

```
git pull origin master
npm cache clean
rm -rf node_modules app/bower_components
nm i
npm run bower-install
npm run build
```

**Comment by mohsen1** [comment]
Hopefully your issue was resolved. Please comment here if you're still having this issue. I'm closing this ticket.

**Comment by tlimpanont** [comment]
Oh yeah sure, many thanks for the help!
