### ISSUE TITLE
add custom semantic validator to swagger editor project 

### ISSUE THREAD

**Issue by boulbababenjabeur** [swagger-api/swagger-editor#4122]
i  want to add a custom validator in the existing system of swagger editor project  (or modify a current one)
i  added a validator file in src/plugins/validation/semantic-validation/validators   and  imported that function in  SemanticValidatorsPlugin but the project is not reading the file does anyone know a way to apply my modification ?
this is the function i want to add that controls the version of the swagger definition file  

export const myValidator = sys => {
  return sys.validateSelectors
    .allInfos()
    .then(nodes => {
      return nodes.reduce((acc, node) => {
        const value = node.node;

        if (value.version !== '2.0' && value.version !== '3.0.0') {
          acc.push({
            level: 'error',
            message: `Unsupported Swagger version: ${value.version}`,
            path: [...node.path, 'version']
          });
        }

        return acc;
      }, []);
    });
};

**Comment by char0n** [comment]
Hi @boulbababenjabeur,

Please have a look at:

- https://github.com/swagger-api/swagger-editor/issues/3719#issuecomment-1361338217
- https://github.com/swagger-api/swagger-editor/issues/3733#issuecomment-1361466174

This should serve as a documentation how to achieve what you're after.
