### ISSUE TITLE
Response headers undefined reported even when response headers are present

### ISSUE THREAD

**Issue by faseidl** [swagger-api/swagger-editor#414]
When sending a request to an API from the editor, a "headers undefined" error message is displayed (and no response body) even when the headers are present in the response.

The appears to be the same problem discussed in the forum in January:
https://groups.google.com/forum/#!topic/swagger-swaggersocket/pdLne9WHvbo

**Comment by mohsen1** [comment]
Are you making the call cross-origin? Please read the [cors](https://github.com/swagger-api/swagger-editor/blob/master/docs/cors.md) docs and be advised that even if your server is supporting cross-origin calls, cross-origin XHR calls will not have access to all the headers for security reasons.

**Comment by mohsen1** [comment]
It's most likely the CORS issue that is causing this issue. I'm closing this ticket but if you're still having this issue over a CORS-enabled server, please comment here.

**Comment by chmercesmoreira** [comment]
I'm getting the same error, I have already specified in my responses the headers following the cors docs, I'm testing it in the skeleton project (hello world), here is my modification:

hello_world.js:

function hello(req, res) {
...

  // this sends back a JSON response which is a single string
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  res.json(hello);
}

**Comment by webron** [comment]
@chmercesmoreira - can you share the output of `curl -I <path to api>`?

**Comment by chmercesmoreira** [comment]
@webron `curl -I http://127.0.0.1:10010/hello?name=Scott`
```
HTTP/1.1 405 Method Not Allowed
Access-Control-Allow-Origin: *
Allow: GET
Content-Type: application/json
Date: Fri, 22 Jan 2016 22:38:14 GMT
Connection: keep-alive
```

**Comment by webron** [comment]
It looks like your CORS headers are still not set correctly then. You're missing the `Access-Control-Allow-Methods` and `Access-Control-Allow-Headers` headers. 

Check the output of `curl -I http://petstore.swagger.io/v2/pet/1` for example.

**Comment by chmercesmoreira** [comment]
@webron Thank you.
I added the following code snippet in the **app.js** file provided by the skeleton project:
```
'use strict';

var SwaggerRestify = require('swagger-restify-mw');
var restify = require('restify');
var app = restify.createServer();

app.use(
  function crossOrigin(req,res,next){
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "X-Requested-With");
    res.header("Access-Control-Allow-Methods", "GET, POST, DELETE, PUT")
    return next();
  }
);

module.exports = app; // for testing

var config = {
  appRoot: __dirname // required config
};
...
```

Now I'm getting this output for the `curl -I http://127.0.0.1:10010/hello?name=Scott` command:

```
HTTP/1.1 405 Method Not Allowed
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: X-Requested-With
Access-Control-Allow-Methods: GET, POST, DELETE, PUT
Allow: GET
Content-Type: application/json
Date: Sat, 23 Jan 2016 00:02:13 GMT
Connection: keep-alive
```

**Comment by webron** [comment]
I assume it still doesn't work. If you're not any special headers of your own other than the one you added, you'd still want to add `Content-Type` to the list of allowed headers.

**Comment by rajegit** [comment]
@webron , facing the same  problem .How to resolve ?

**Comment by webron** [comment]
@rajegit I have no idea what you're talking about.

**Comment by mohsen1** [comment]
@rajegit is talking about swagger-node. You need to pass correct content type. Browser won't do it.
