### ISSUE TITLE
in: body indicates error

### ISSUE THREAD

**Issue by Fluxxo** [swagger-api/swagger-editor#415]
Open http://editor.swagger.io/#/, load the default content (default.yaml)
Go to line 28, change "query" to "body" -> An error is indicated.
The specification tells me, body should be ok at that point.

**Comment by webron** [comment]
As mentioned in the other issue, you cannot convert query parameters to body parameters seamlessly. Their structure is slightly different as the type of a body parameter is indicated under the schema property.
