### ISSUE TITLE
Try to launch locally fails with NPM

### ISSUE THREAD

**Issue by miguelk5** [swagger-api/swagger-editor#4166]
### Q&A (please complete the following information)
- OS: Ubuntu
- Browser: Chrome
- Version: 23
- Method of installation: docker
- Swagger-Editor version: latest

### Content & configuration
node 16.17.1

### Describe the bug you're encountering
The web application is not able to start

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: react-ace@4.4.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"=17.0.2" from the root project
npm ERR!   peer react@"^17.0.0-0" from @wojtekmaj/enzyme-adapter-react-17@0.8.0
npm ERR!   node_modules/@wojtekmaj/enzyme-adapter-react-17
npm ERR!     dev @wojtekmaj/enzyme-adapter-react-17@"=0.8.0" from the root project
npm ERR!   16 more (@wojtekmaj/enzyme-adapter-utils, boron, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.13.0 || ^0.14.0 || ^15.0.1" from react-ace@4.4.0
npm ERR! node_modules/react-ace
npm ERR!   react-ace@"^4.1.6" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@15.7.0
npm ERR! node_modules/react
npm ERR!   peer react@"^0.13.0 || ^0.14.0 || ^15.0.1" from react-ace@4.4.0
npm ERR!   node_modules/react-ace
npm ERR!     react-ace@"^4.1.6" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/9999/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:

### To reproduce...
nvm use 16.17.1
npm start (under swagger editor folder)

### Expected behavior
whatever else...

**Comment by char0n** [comment]
Hi,

This is easily resolved by running:

```sh
$ npm i --legacy--peer-deps
```

**Comment by char0n** [comment]
Closing as `--legacy--peer-deps` works. SwaggerEditor@4 which is based on `master` branch will be deprecated in future. New editor implementation is being developed in [next](https://github.com/swagger-api/swagger-editor/tree/next) branch and released as SwaggerEditor@5.

**Comment by vkolodrevskiy** [comment]
Fails with the same in master branch for me too, runs ok under next branch.
