### ISSUE TITLE
Is there a way to import a JSON spec from URL ?

### ISSUE THREAD

**Issue by who** [swagger-api/swagger-editor#417]
I often use the "Paste JSON" feature to load an API spec for editing.  

Is there a way to load JSON from a URL, similar to how swagger-ui does it with their `?url=` parameter?

**Comment by mohsen1** [comment]
Please read [here](https://github.com/swagger-api/swagger-editor#importing-your-swagger-document). It's not the most reliable when your json is behind a server without CORS (#370)
