### ISSUE TITLE
Not able to see both Form and Raw tab on Swagger UI documentation

### ISSUE THREAD

**Issue by Nitin77** [swagger-api/swagger-editor#421]
When we are giving parameter type body , I can see two tabs for Request Forms and Raw data to input request details. But when I am using same JSON file for Swagger UI , I am only able to see on tab in Request i.e Raw (to input JSON). How can I see other tab for Forms as well.
![swagger1](https://cloud.githubusercontent.com/assets/9037282/7421769/744c3a02-ef55-11e4-957a-807cf9f7d47b.png)
![swagger2](https://cloud.githubusercontent.com/assets/9037282/7421771/75bacca0-ef55-11e4-8f8e-3a957d9358ad.png)

**Comment by mohsen1** [comment]
SwaggerUI does not generate a from for your request. There is [a pull request](https://github.com/swagger-api/swagger-ui/pull/1088) there for this feature. Please open an issue in SwaggerUI project if you want to discuss this issue. It's not an issue in Swagger Editor.
