### ISSUE TITLE
Generate Server - JAX-RS should have Apache CXF Interface gateway

### ISSUE THREAD

**Issue by KumarGajavalli** [swagger-api/swagger-editor#423]
Generate Server - JAX-RS should have Apache CXF Interface gateway, while it should not have Implementation class by itself. This gives developers seamless ability to be able to generate Apache CXF based JAX-RS Service (rather than presently produced Jersey API based Implementation). 
Assume the application is to go through Agile cycle, and is supposed to have a contract change in future, providing interface in server code to be extended in a different place to write complete service implementation would keep the Server Interface API and Implementation independent.

**Comment by prabhatjha** [comment]
I suggest to open an issue at https://github.com/swagger-api/swagger-codegen . Editor simply uses this.

**Comment by mohsen1** [comment]
Moved to https://github.com/swagger-api/swagger-codegen/issues/714
