### ISSUE TITLE
Install on Win8.1 and winserver 2012 fails

### ISSUE THREAD

**Issue by janraak** [swagger-api/swagger-editor#425]
I attempted several times to install and run the swagger-editor on a variety of machines, without success.

I installed node.js per the instructions.
I obtained the distribution for GIT and run the NPM start command, which ran for some time but consequenlty failing:
```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "d:\\Program Files (x86)\\nodejs\\\\node.exe" "d:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! swagger-editor-src@2.9.2 prebuild: `npm run bower-install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swagger-editor-src@2.9.2 prebuild script 'npm run bower-install'.
npm ERR! This is most likely a problem with the swagger-editor-src package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run bower-install
npm ERR! You can get their info via:
npm ERR!     npm owner ls swagger-editor-src
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Sources\swagger-editor-master\npm-debug.log

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "d:\\Program Files (x86)\\nodejs\\\\node.exe" "d:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! swagger-editor-src@2.9.2 prestart: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swagger-editor-src@2.9.2 prestart script 'npm run build'.
npm ERR! This is most likely a problem with the swagger-editor-src package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls swagger-editor-src
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Sources\swagger-editor-master\npm-debug.log

```

**Comment by janraak** [comment]
Content of npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ 'd:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'd:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink d:\Program Files (x86)\nodejs\\node.exe
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart swagger-editor-src@2.9.2
7 verbose unsafe-perm in lifecycle true
8 info swagger-editor-src@2.9.2 Failed to exec prestart script
9 verbose stack Error: swagger-editor-src@2.9.2 prestart: `npm run build`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (d:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (d:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid swagger-editor-src@2.9.2
11 verbose cwd D:\Sources\swagger-editor-master
12 error Windows_NT 6.3.9600
13 error argv "d:\\Program Files (x86)\\nodejs\\\\node.exe" "d:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v0.12.2
15 error npm  v2.7.4
16 error code ELIFECYCLE
17 error swagger-editor-src@2.9.2 prestart: `npm run build`
17 error Exit status 1
18 error Failed at the swagger-editor-src@2.9.2 prestart script 'npm run build'.
18 error This is most likely a problem with the swagger-editor-src package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm run build
18 error You can get their info via:
18 error     npm owner ls swagger-editor-src
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by mohsen1** [comment]
You can manually install Bower and Grunt and start it with following commands:

```
npm i -g bower grunt-cli
npm i
bower i
grunt serve
```

I'll try to find out what's wrong with Windows scripts.

**Comment by janraak** [comment]
Thx

That worked. How can I changevthe editor to run on all ip adresses?

Kind regards/Met vriendelijke groet

Jan Raak

(Sent from my iPad)

**Comment by mohsen1** [comment]
I don't know about that. Maybe you need to use IIS?

**Comment by mohsen1** [comment]
I tested the latest in my Window VM. I suggest you use Git Bash instead of Windows CLI or make sure you have `git` and `node` in your PATH.

Here is the latest (c848614) running on Windows 8.1

![screen shot 2015-05-07 at 3 43 17 pm](https://cloud.githubusercontent.com/assets/543633/7527438/f52f62a0-f4cf-11e4-9e1b-4fc593b92764.png)
