### ISSUE TITLE
'Try it out' feature can't resolve other containers on the same Docker network (maybe CORS?)

### ISSUE THREAD

**Issue by EvanShaw** [swagger-api/swagger-editor#4268]
### Q&A (please complete the following information)
 - OS: Ubuntu 23.04
 - Browser: chrome
 - Version: 114.0.5735.198
 - Method of installation: Docker
 - Swagger-Editor version: swaggerapi/swagger-editor:latest (v4?)
 - Swagger/OpenAPI version: OpenAPI 3.0.0

### Content & configuration

Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  title: ihtmapps
  description: 'This is the OpenAPI spec for ihtmapps'
  version: 1.0.0
servers:
  -
    url: 'http://web:8080'
    description: Localhost
paths:
  /api/invoice-register:
    post:
      summary: 'Uploads an IR excel'
      description: "Note that uniqueness is not enforced, which means a user could potentially\nupload the same document multiple times, resulting in the expected amount\nof money for an invoice being doubled or tripled."
      operationId: invoiceRegisterUpload
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              required:
                - ircsv
              properties:
                ircsv:
                  description: 'Invoice CSV file'
                  type: string
                  format: binary
              type: object
      responses:
        '200':
          description: 'The data'
```

docker-compose.yml
```yaml
version: '3.9'

services:
  openapi:
    image: swaggerapi/swagger-editor
    container_name: openapi-editor
    networks:
      - stack
    environment:
      SWAGGER_FILE: /tmp/openapi.yaml
    ports:
      - 3555:8080
    volumes:
      - ../src:/tmp
    extra_hosts:
      - "host.docker.internal:host-gateway"
  web:
    image: ihtmapps-webapp-local
    networks:
      - stack
    ports:
      - 7100:8080
  webv2:
    image: ihtmapps-webapp-v2-local
    networks:
      - stack
    ports:
      - 7200:8080

networks:
  stack:
```

Here are the headers I set on the server side:
```
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
```

### Screenshots
Here's the result of 'Try it out':
![Screenshot from 2023-07-11 08-22-03](https://github.com/swagger-api/swagger-editor/assets/6827717/e9703bad-5930-4650-b4c8-c2f5bb26cb71)

And the result in the network tab:
![Screenshot from 2023-07-11 08-23-12](https://github.com/swagger-api/swagger-editor/assets/6827717/207f952c-375c-40fe-8172-a35c468aeaea)

### How can we help?
For some reason, the swagger editor just cannot reach other containers on the same network. When I run the exact same curl command in the screenshot above from within the `webv2` service container, it goes through without any problem. I also tried the host URL `http://host.docker.internal:7100`, but that didn't work either.

Is this a CORS issue? It doesn't seem Docker related to me...
Any help would be appreciated.

**Comment by char0n** [comment]
Yes, this is how it looks like when you hit CORS security limitations.

> When I run the exact same curl command in the screenshot above from within the webv2 service container, it goes through without any problem

Yes, because these tools are not bound with CORS policies, only browser is.


I'recommend you to configure HTTP servers in other containers to be CORS capable.
