### ISSUE TITLE
no Swift!

### ISSUE THREAD

**Issue by misbell** [swagger-api/swagger-editor#427]
I'm working heavily in Swift so while I love the tool...

**Comment by mohsen1** [comment]
Do you mean there is no Swift client code gen? If so, you can use Objective-C client SDK in a Swift code base.

**Comment by misbell** [comment]
Yeah, I knooow. But why not keep it pure Swift?

**Comment by mohsen1** [comment]
Please follow this issue [here](https://github.com/swagger-api/swagger-codegen/issues/new). If you know Swift well enough you should contribute Swift SDK. Most of code-gen is community driven

**Comment by mohsen1** [comment]
Edit: Link to moved issue

**Comment by webron** [comment]
Please follow https://github.com/swagger-api/swagger-codegen/issues/471 instead.
