### ISSUE TITLE
Swagger does not integrate with Micronaut consistently

### ISSUE THREAD

**Issue by roland-lyra** [swagger-api/swagger-editor#4288]
### Q&A (please complete the following information)
 - OS: MacOS Monterey
 - Swagger 3.0

### Content & configuration
  swagger.yml view generation fails inconsistently. Project is in Kotlin using Micronaut, Protobuf and gradle with Intellij IDE. Swagger annotations seem to fail view generation in very unusual ways. Changing the description of a swagger annotation (such as @Tag) will cause a message stating that swagger.yml failed to create. This happens sometimes for some annotations, which makes it very confusing to debug. Some POJOs work fine with the @Schema annotation, but the vast majority don't. 

Gradle configuration:
```
    kapt("io.micronaut.openapi:micronaut-openapi:4.9.2")
    implementation("io.swagger.core.v3:swagger-annotations")
```

### Describe the bug you're encountering
Swagger (3.0) annotations are inconsistent and the majority fails view generation with `warning: Unable to generate swagger.yml: {path}/main/META-INF/swagger/doc.yml - Unknown value true` which doesn't specify what the bug is. A tag such as `@Tag(name = "example 1", description = "example description")` will be fine but if i change one single letter `@Tag(name = "example 2", description = "example description")` (change 1 -> 2) the view will fail to generate. The @Schema annotation that I label some POJOs in my project with also fails on most objects but in a couple specific cases (seemingly random, like with tag) will be fine. 

### Additional context or thoughts
This problem seems completely random but deterministic. For example, one specific string will work for @Tag description and no other description string will work, but it works like this consistently.

**Comment by char0n** [comment]
Hi,

What does `Swagger 3.0` actually represent? SwaggerEditor, SwaggerUI or SwaggerClient?
