### ISSUE TITLE
oneOf must be a non-empty array of schemas

### ISSUE THREAD

**Issue by Skeeve** [swagger-api/swagger-editor#4317]
### Q&A (please complete the following information)

 - OS: macOS
 - Browser: Vivaldi
 - Version: 6.1.3035.100 (Stable channel) (x86_64) 
 - Method of installation: docker, but also tried on https://editor-next.swagger.io
 - Swagger-Editor version: next-v5 I guess
 - Swagger/OpenAPI version: 3.0.3

### Content & configuration

Please find my "stripped down" OpenAPI definition gere:

```yaml
openapi: 3.0.3
info:
  title: Test
  version: "1.2.alpha2"
paths:
  /notifications:
    get:
      summary: Get the current active notifications per brand or sender
      responses:
        '200':
          description: …
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/notifications_sender"
                  - $ref: "#/components/schemas/brand_info"
                  - $ref: "#/components/schemas/just_a_number"
components:
  schemas:
    notifications_sender:
      type: object
      properties:
        amount:
          type: integer
        alert_status:
          type: string
          pattern: ^(OK|WARNING|ALARM)$
      required:
        - amount
        - alert_status
    brand_info:
      type: array
      items:
        type: object
        properties:
          amount:
            type: integer
          alert_status:
            type: string
            pattern: ^(OK|WARNING|ALARM)$
          brand:
            type: string
            minLength: 1
            maxLength: 255
        required:
          - amount
          - brand
    just_a_number:
      type: integer
```

Swagger-Editor configuration options:

Using it OOTB

```
?withCredentials=true
```

### Describe the bug you're encountering

I get the error message:

| Severity | Line | Code | Message |
|---|---|---|---|
|!|14 | 10055 | oneOf must be a non-empty array of schemas |

### To reproduce...

1. Go to https://editor-next.swagger.io
2. Paste my example
3. See error

### Expected behavior

I cannot see what's wrong with my OpeAPI definition

**Comment by Skeeve** [comment]
P.S. Insomnia does not complain, neither does "ReDoc" in VSCode do.

**Comment by Skeeve** [comment]
Seems this is related to #4026

**Comment by char0n** [comment]
Yes, this is duplicated of https://github.com/swagger-api/swagger-editor/issues/4026 which has already been fixed, but now yet released.
