### ISSUE TITLE
Add support for 'deprecated' Operation attribute

### ISSUE THREAD

**Issue by chrisdudley** [swagger-api/swagger-editor#433]
An Operation with 'deprecated' set to true doesn't seem to produce any visual indication in the preview panel that the operation has been deprecated. Can it be added please?

**Comment by mohsen1** [comment]
Should we render it with some visual indication that it's deprecated or should we omit it altogether? 

/cc @fehguy @webron

**Comment by chrisdudley** [comment]
A visual indicator I would have thought.
If someone wanted it omiting then they'd remove it from the swagger doc entirely.

**Comment by who** [comment]
+1 for visual indicator

**Comment by chrisdudley** [comment]
Adding the word 'Deprecated' to the right hand end of the Operation banner would work. Don't think it needs anything more than that really.

**Comment by webron** [comment]
@mohsen1 - I tend to agree with the comments above. Would be better to have the word `Deprecated`.
