### ISSUE TITLE
Local reference not found when using "$defs" in path

### ISSUE THREAD

**Issue by loganmzz** [swagger-api/swagger-editor#4388]
### Q&A
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: https://editor-next.swagger.io/
 - Method of installation: SaaS
 - Swagger-Editor version: https://editor-next.swagger.io/
 - Swagger/OpenAPI version: OpenAPI 3.1.0

### Content & configuration

Example OpenAPI definition:
```yaml
openapi: "3.1.0"

info:
  version: "1.0.0"
  title: "Demo"

components:
  schemas:
    Bar:
      type: object
      properties:
        sub:
          type: object
          $ref: "#/components/schemas/Bar/$defs/named"
      allOf:
      - oneOf:
        - properties:
            id:
              type: string
        - $ref: "#/components/schemas/Bar/$defs/named"
        - $ref: "#/components/schemas/countable"
      $defs:
        named:
          properties:
            name:
              type: string
    countable:
      properties:
        count:
          type: number

```

### Describe the bug you're encountering

When refering to a `$defs` key in `$ref`, a `"local reference not found"` error is raised.

### To reproduce...

See example above.

### Expected behavior

No error.

### Screenshots

N/C

### Additional context or thoughts

N/A

**Comment by mdaneri** [comment]
I never saw $def in any openapi documentation. What is $def?

**Comment by mdaneri** [comment]
Another question 
Why Countable is not a type: object?

**Comment by loganmzz** [comment]
I don't really understand remarks. This is a [MVCE](https://stackoverflow.com/help/minimal-reproducible-example).

And `$defs` is part of JSON Schema: https://json-schema.org/understanding-json-schema/structuring#defs

**Comment by mdaneri** [comment]
I don't see this #defs defined in the default OpenAPI JSON dialect :
https://spec.openapis.org/oas/3.1/dialect/base
You should specify the `jsonSchemaDialect` that supports `#defs`.

The only concern doing that is that I doubt Swagger-Editor supports any JSON dialect other than the default one.

**Comment by loganmzz** [comment]
`$defs` is part of JSON Schema 2020-12 which is default target for OpenAPI 3.1.0

**Comment by mdaneri** [comment]
Thanks today I learn a new thing 👍 
Anyway I tried your definition and works fine with the editor.


![image](https://github.com/swagger-api/swagger-editor/assets/17148649/2fa5346b-09ec-4100-a412-8396b25dd612)

**Comment by loganmzz** [comment]
Looks like it was fixed, may be in some library used by the editor. I close the issue.
