### ISSUE TITLE
Ubuntu 14.04 bower ESUDO         Cannot be run with sudo

### ISSUE THREAD

**Issue by weldpua2008** [swagger-api/swagger-editor#439]
Hi,

My full log is here: http://pastebin.com/t1kwgmy0
    # git clone https://github.com/swagger-api/swagger-editor.git
Cloning into 'swagger-editor'...
root@SwaggerServer:/opt# cd swagger-editor

root@SwaggerServer:/opt/swagger-editor# npm start

> swagger-editor-src@2.9.5 bower-install /opt/swagger-editor
> bower install

bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0

**Comment by mohsen1** [comment]
Why are you running this as root?

**Comment by weldpua2008** [comment]
I run from non-rootuser and got error that I haven't permissions. I run with sudo and got this error

**Comment by mohsen1** [comment]
Glad you figured it out.

**Comment by Escarter** [comment]
bower install --allow-root does it right

**Comment by 331164885** [comment]
@Escarter Nice

**Comment by oneezy** [comment]
this is still irritating to have to use `bower install --allow-root`

Is it possible to set this up properly in a `.config` so we don't have to constantly add `allow-root` ?

I'm using the new `windows linux subsystem` w/ ubuntu 14.04, so I'm fairly new
