### ISSUE TITLE
JsonSerializerOptions instance must specify a TypeInfoResolver setting before being marked as read-only.

### ISSUE THREAD

**Issue by XHAlawa** [swagger-api/swagger-editor#4403]
Hello, I'm facing this issue. 
After I've Updated visual studio to last version "Version 17.8.0 Preview 1.0" 
It was working before the update.
Here is Call Stack And the Exception

`
InvalidOperationException: JsonSerializerOptions instance must specify a TypeInfoResolver setting before being marked as read-only.
System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerOptionsNoTypeInfoResolverSpecified()
System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
System.Text.Json.JsonSerializer.GetTypeInfo<T>(JsonSerializerOptions options)
System.Text.Json.JsonSerializer.Serialize<TValue>(TValue value, JsonSerializerOptions options)
Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.GetIndexArguments()
Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.RespondWithIndexHtml(HttpResponse response)
Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
`

**Comment by Vasim-DigitalNexus** [comment]
Same issue here

**Comment by char0n** [comment]
I'm sorry guys, but I'm closing this as it has probably nothing to do with this repository.

**Comment by AKlaus** [comment]
Linking the most probable  actual issue – dotnet/aspnetcore/issues/49360
