### ISSUE TITLE
Error when using the load/save from backend feature

### ISSUE THREAD

**Issue by tgrant59** [swagger-api/swagger-editor#441]
When using the backend feature I am receiving two errors when rendering the page:
`TypeError: swaggerObject must be an object`=
and 
`Error: ui-ace cannot use an object or an array as a model`

These may be due the the fact that I am unsure of the structure that the editor expects from my backend endpoints. On `GET`, I am returning something like this: 

```javascript
{
  "swagger": "2.0",
  "info": {
    "title": "Swagger Editor Test",
    "description": "The Swagger Editor Test **API** Doc",
    "version": "1.0.0"
  },
  "host": "api.example.com",
  "basePath": "/api/v1/",
  "schemes": ["http"],
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "paths": {
    "/pets": {
      "get": {
        "description": "Returns all pets from the system that the user has access to",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "A list of pets.",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/pet"
              }
            }
          }
        }
      }
    }
  }
}
```

I could not find any documentation on what the backend feature expects, so I'm purely guessing here. I can see from Chrome dev tools that the endpoint is in fact being accessed and is responding correctly with this ^. In the config, useYamlBackend is false.

**Comment by mohsen1** [comment]
Your backend should return pure YAML string in body. It also should expect YAML in body of PUT calls that Editor will make. Look at [Apigee a127](https://github.com/apigee-127/a127) as an example of using backend feature. There is more docs [here](https://github.com/swagger-api/swagger-editor/blob/master/docs/config.md#backends)

**Comment by tgrant59** [comment]
Ah, its working now that i've changed to YAML. So what is the purpose of the useYamlBackend flag in the configuration if it always uses YAML regardless of the setting?

**Comment by mohsen1** [comment]
if `useYamlBackend` is disabled editor will do `JSON.parse` instead of `YAML.load`. Remember JSON is YAML so using passing JSON to `YAML.load` will just work.

**Comment by tgrant59** [comment]
If that is true, why doesn't it work with JSON passed to it?

**Comment by mohsen1** [comment]
Oh I forgot to mention AST builder will fail if you pass JSON instead of YAML.
