### ISSUE TITLE
Feature request: 'no-proxy' or 'direct-import' URL param

### ISSUE THREAD

**Issue by Lucas-C** [swagger-api/swagger-editor#442]
Hello !

First, I love Swagger, thanks for your all your work on this project !

Would it be possible to allow **not** using the the `cors-it` proxy ?
My use case is very simple: I want to display a document from an intranet server, already configured with CORS. Hence the browser can directly access the yaml file, but not the `cors-it` heroku app.

Could it be possible to specify in the URL parameters to bypass this proxy ?

I am going to deploy the `swagger-editor` app on my server for now, but it's a pity to do so whereas a simple parameter could do the trick. And I think other users may face the same issue.

Thanks !

**Comment by webron** [comment]
I believe you can just set https://github.com/swagger-api/swagger-editor/blob/master/app/config/defaults.json#L38 to an empty string, assuming you run it locally.

**Comment by Lucas-C** [comment]
That's the thing: I did not want/needed to run it locally.

**Comment by webron** [comment]
Sorry, I missed part of your original message. I guess it could be on by default and have a setting to disable it.

**Comment by Lucas-C** [comment]
Yes ! That's exactly what I'd want.
Either `&noproxy=true` or replace `import=` by `direct-import=`.

**Comment by mohsen1** [comment]
This is easy to add. We need to add a secondary argument to `FileLoader#importFromUrl` ([here](https://github.com/swagger-api/swagger-editor/blob/master/app/scripts/services/fileloader.js#L42-L50))  to bypass the proxy url construction and pass that argument [here](https://github.com/swagger-api/swagger-editor/blob/master/app/scripts/controllers/importurl.js#L14) when you see `noproxy` query param. 
Please open a PR with those changes if you want it soon.

**Comment by mohsen1** [comment]
This was implemented in https://github.com/swagger-api/swagger-editor/issues/455

**Comment by Lucas-C** [comment]
Thanks !
I was working on it but hadn't the checkbox implemented yet.
Good job !
