### ISSUE TITLE
oneOf not working as expected

### ISSUE THREAD

**Issue by jknapka** [swagger-api/swagger-editor#443]
The spec below was cut and pasted from this issue: https://github.com/swagger-api/swagger-spec/issues/298, but the Swagger editor doesn't like the "oneOf". I have a complex API composed using the Swagger editor back in February 2015, which worked fine at that time. In the current editor it is completely broken because it uses oneOf extensively. Was support for oneOf removed for some reason? If so, how can I adjust my spec to achieve the same effect?

    swagger: '2.0'
    info:
      version: 1.0.0
      title: Overloading example
    paths:
      /:
        get:
          responses:
            200:
              description: Bug?
              oneOf:
                - description: Returns a string
                  schema:
                    type: string
                - description: Returns a number
                  schema:
                    type: integer

**Comment by webron** [comment]
@jknapka - Swagger spec doesn't support `oneOf`...

**Comment by webron** [comment]
What you linked to is a proposal for the *next* version of the Swagger specification. It's not part of it.

**Comment by jknapka** [comment]
OK... Then I apologize for raising this issue. However,  I'm very confused, because when I started using Swagger, back in late February, I needed oneOf and used it, and it worked fine.
