### ISSUE TITLE
swagger-editor failed to compile

### ISSUE THREAD

**Issue by marcodarko** [swagger-api/swagger-editor#4477]
### Q&A (please complete the following information)
 - OS: 13.5.1 (22G90)13.5.1 (22G90)
 - Browser: Chrome
 - Version: Version 117.0.5938.92 
 - Method of installation: npm
 - Swagger-Editor version: 4.11.2
 - Swagger/OpenAPI version:OpenAPI 3.0

### Content & configuration

**Please note that this is also happening with the latest version of Swagger UI, I had uninstall the latest as both give me very similar issues**

Example Swagger/OpenAPI definition:
```
https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/mygene.info/openapi_full.yml
```

Swagger-Editor configuration options:
```js
import SwaggerEditorBundle from "swagger-editor"
const editor = SwaggerEditorBundle({
                url: myUrl,
                dom_id: '#swagger-editor',
                layout: 'StandaloneLayout',
                deeplinking: true,
                presets: [
                    SwaggerEditorStandalonePreset
                ]
            })

          window.editor = editor;
```

```
?yourQueryStringConfig
```

### Describe the bug you're encountering
After upgrading to latest version I see this:
**Failed to compile.

./node_modules/swagger-editor/dist/swagger-editor-es-bundle.js 2:1384193
Module parse failed: Unexpected token (2:1384193)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)**

### Screenshots
<img width="732" alt="Screenshot 2023-10-05 at 11 20 03 AM" src="https://github.com/swagger-api/swagger-editor/assets/23092057/ef56292f-3c34-4098-ae6e-9221c9e48d01">
<img width="1243" alt="Screenshot 2023-10-05 at 11 20 26 AM" src="https://github.com/swagger-api/swagger-editor/assets/23092057/682ca0fa-162c-4fd1-8e8a-1398a2ff50e3">

### Additional context or thoughts
There's also no documentation on the usage of SwaggerEditorBundle, the little documentation there is doesn't go into any detail.

**Comment by char0n** [comment]
Hi @marcodarko,

We now maintain wiki page for different bundlers integration with SwaggerUI: https://github.com/swagger-api/swagger-ui/wiki/Seamless-Integration-with-Bundlers-&-Test-Tools


Would you be able to provide more info about what Node.js and Webpack versions are you using to build the bundle?

**Comment by char0n** [comment]
Closing for insufficient information.

**Comment by dsd601** [comment]
hello @marcodarko,

I got the same issue. Did you resolve your issue? I use node v16.20.0

**Comment by marcodarko** [comment]
@dsd601 the only way I got it to work was withg Node 20> works great now, so I'd recommend you consider upgrading your setup if you can

**Comment by dsd601** [comment]
Okay thanks  @marcodarko 
I'll try

**Comment by dsd601** [comment]
@marcodarko , using v 21.2.0 and still not working, and get the same error
