### ISSUE TITLE
Major performance problems when editing large files

### ISSUE THREAD

**Issue by tgrant59** [swagger-api/swagger-editor#448]
As the size of the file I am editing increases, the performance is really degrading quickly. I am currently editing a 1000 line file, and rendering takes about a second **per character**!!

 I have tried some countermeasures such as reducing the frequency of the backend healthchecks, reducing the frequency of the backend PUT requests, and also disabling live rendering. With all of these measures it still takes about a second to display the character and regain control of the editor.

One possible origin of the performance problems could be the fact that I am getting TONS of warnings in the console. Basically whenever I type a character, I get a warning `failed to refresh line numbers`. Could this be the culprit?

**Comment by mohsen1** [comment]
Well, editor does a lot of work when spec changes. It parses the YAML, lets Swagger Tools walk the tree for issues(which is very expensive) and renders the HTML. I have #368 open for this. If we can move all those processes into different threads(Workers in browser) we can gain a lot of performance boost.

**Comment by tgrant59** [comment]
Some of these don't have to be performed on every character change, like checking for issues with the yaml. This can be made so that only when you stop typing for a few seconds it will parse the tree and try to render it. This would increase performance greatly

**Comment by mohsen1** [comment]
That what we're doing

 https://github.com/swagger-api/swagger-editor/blob/master/app/scripts/controllers/editor.js#L5

That 200ms delay is not configurable. #364 is open for making that configurable from UI level

**Comment by tgrant59** [comment]
Oh great! thanks for that link, I'll just modify the source for my purposes now to solve the problem

**Comment by tgrant59** [comment]
So modifying that delay does do something, but i'm still experiencing quite a big lag when typing.

**Comment by who** [comment]
You may be experiencing a performance degradation due to how AngularJS works with the DOM.  

I created a reproducible spec here: 

http://editor.swagger.io/#/?import=https://gist.githubusercontent.com/who/04292a5b7a93ac9b6e8d/raw/62531ad9e67b8dfccabb2375d0390f922995d962/big_api.yml

**Comment by mohsen1** [comment]
Right, we throttle processing and rendering but we don't throttle Ace `getCompletion` calls. `getCompletions` calls trigger AST composing for getting completions. It is an issue for big files.

**Comment by mohsen1** [comment]
I'm going to explore running `getCompletions` in a worker. Throttling that task hurts user experience in more common cases (smaller specs).

**Comment by tgrant59** [comment]
Maybe allow for throttling of `getCompletions` in configuration, so only people who need it may enable it

**Comment by mohsen1** [comment]
In 2.9.8 performance is more acceptable and there are options to disable heavy operation. Please comment if you still have concerns.

**Comment by DakotaClawson** [comment]
Editing a 13k line document in Swagger editor and really wishing there were a non-browser option. Having the same issue that was initially posted, a solid second of rendering after typing each character.
