### ISSUE TITLE
Allow import of JSON and convert to YAML

### ISSUE THREAD

**Issue by hlship** [swagger-api/swagger-editor#449]
I would very much like it if it were possible to import a URL that provided JSON and have the editor internally convert that to YAML.

Meanwhile, I'll change my framework to produce YAML output (as well as JSON).

**Comment by fehguy** [comment]
You can paste JSON or import a 2.0 URL, I believe JSON format works fine:

![image](https://cloud.githubusercontent.com/assets/249413/7657198/03bce53e-fae5-11e4-8272-94a33cc1df0b.png)

**Comment by hlship** [comment]
When I attempt to import a JSON URL, the button is not enabled.

![swagger_editor](https://cloud.githubusercontent.com/assets/52660/7657527/652d8d44-fae7-11e4-8e65-00fdd7b55439.png)

Mac OS X / Chrome.  Let me try in Firefox.

Nope, same behavior there ... the import button is never enabled.

**Comment by hlship** [comment]
Changing the extension to ".yaml" doesn't help either.  Import button is never enabled.

**Comment by hlship** [comment]
My workflow has been to curl ... | pbcopy, then "Paste JSON..." that works fine.  But it would be easier if I could just Import URL that's JSON (or even YAML).

**Comment by webron** [comment]
Are you using the online editor?

**Comment by mohsen1** [comment]
JSON is a subset of YAML, so if you can import YAML, you can defiantly import JSON too. I just tried importing this URL with success in the online editor:

> https://raw.githubusercontent.com/swagger-api/swagger-spec/master/examples/v2.0/json/petstore-expanded.json

I guess the problem is, you're trying to import from a URL that is not accessible from the service we're using to get around CORS (cors-it.herokuapp.com) because it's hosted in your machine.

**Comment by mohsen1** [comment]
#455 will allow you to get around cors-it when it's implemented.
