### ISSUE TITLE
Allow blank password in HTTP Basic Authentication dialog

### ISSUE THREAD

**Issue by agusgambina** [swagger-api/swagger-editor#450]
Hi,

I am starting with swagger and I love it.

I am doing specs for GetMango. The authentication is with BasicAuth, you have to complete the name and left the password blank.

The problem with the swagger editor is, it doesn't enable the button authorize until you fill both fields.

Maybe it should allow you to authorize while the fields are empty.

Thank you!

**Comment by mohsen1** [comment]
Do you mean your backend's basic auth works without a password? if so, providing any password (a single space) should work, no?
