### ISSUE TITLE
Examples in response object lead to an error

### ISSUE THREAD

**Issue by kbiger** [swagger-api/swagger-editor#452]
If we look at swagger spec here https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#response-object
Response object contains an "examples" object, but swagger-editor does not accept this object. Swagger-editor waits for "examples" object in the "schema" object under the "response".

In fact Swagger-ui is conform to swagger spec, wich create some mistakes and confusions.
With this issue, if we want to use "examples" object in responses, we have to deal with a weird choice: have an error in editor or have the examples object hidden in swagger-ui. 

Could you please make editor conform to swagger spec?

Editor waits for :
```yaml
- responses:
  - "201":
    - description: ""
    - schema : 
      - $ref: "#/definitions/Response"
      - examples:
        - { }
```

UI (and swagger spec) waits for :
```yaml
- responses:
  - "201":
    - description: ""
    - schema :
      - $ref: "#/definitions/Response"
    - examples:
      - {}
```

**Comment by webron** [comment]
@kbiger - if that's your actual YAML, both are invalid.

The editor seems to work well with:

```yaml
      responses:
        201:
          description: ""
          schema :
            $ref: "#/definitions/Response"
          examples: {}
```

**Comment by kbiger** [comment]
@webron 
It's not my actual YAML. "-" comes from markdown mistakes (my bad)
The editor does not work well, I have these message (part of) :
1: Object
code:  "OBJECT_ADDITIONAL_PROPERTIES"
message:  "Additional properties not allowed: examples,schema,description"
 path: Array [5]
0:  "paths"
1:  "/path/{var}/resource"
2:  "post"
3:  "responses"
4:  "201"

If I take your YAML and put another tab-space before "examples" editor is ok, but swagger-ui isn't.

**Comment by webron** [comment]
Which version of the editor do you use?

**Comment by kbiger** [comment]
We use the cloned repo we made the 20 of march 2015.

**Comment by webron** [comment]
The online editor seems to accept it fine. Can you try pulling the latest version?

**Comment by kbiger** [comment]
Got it!
That's the return line which deals to the error.
Our example is a json, so several lines.
How can we do with YAML?

**Comment by webron** [comment]
From http://learnxinyminutes.com/docs/yaml/:

```yaml
literal_block: |
    This entire block of text will be the value of the 'literal_block' key,
    with line breaks being preserved.

    The literal continues until de-dented, and the leading indentation is
    stripped.

        Any lines that are 'more-indented' keep the rest of their indentation -
        these lines will be indented by 4 spaces.
folded_style: >
    This entire block of text will be the value of 'folded_style', but this
    time, all newlines will be replaced with a single space.

    Blank lines, like above, are converted to a newline character.

        'More-indented' lines keep their newlines, too -
        this text will appear over two lines.
```

**Comment by kbiger** [comment]
```yaml
responses:
  201:
    description: ""
    schema :
      $ref: "#/definitions/Response"
    examples: |
      {
        "foo" : "bar"
      }
```
This does not work with both editors (online and ours). I'm sorry

**Comment by danielm64** [comment]
Got the same problem.
As @kbiger I can't manage to set the "examples" text...

**Comment by webron** [comment]
Sorry, my bad. The `examples` property for a response is an object with a map between a mime type and the example itself.

```yaml
      responses:
        default:
          description: "t"
          schema :
            $ref: "#/definitions/Response"
          examples: 
            application/json: |
              {
                "test": "test"
              }
```
works fine.

**Comment by danielm64** [comment]
Yes! Thanks a lot @webron !

**Comment by kbiger** [comment]
Cool! Works fine. Thanks a lot webron.
So it's not a bug, my bad.
