### ISSUE TITLE
deploymentPort is not honored

### ISSUE THREAD

**Issue by DavidBiesack** [swagger-api/swagger-editor#454]
My `swagger-editor/grunt/connect.js` file contains

````
'use strict';

var developmentPort = process.env.PORT || 9000;
var productionPort = 8080;

module.exports = {
  options: {
    port: developmentPort,
    hostname: 'swagger.na.sas.com',
    livereload: 35729
  },
...
````
but when I start

````
    grunt build
    npm start
````
it launches on 8080 instead.

This was working for me before I recently did a 'git pull' to refresh (which I have not done in quite a while)

I cannot use 8080 ; I have other apps that I run on that port.

Has the port configuration moved? I don't see any port configuration in
https://github.com/swagger-api/swagger-editor/blob/master/docs/config.md
except for Docker ports (I'm not using Docker)

thanks

**Comment by mohsen1** [comment]
oh `options` hash is missing `port: developmentPort,`.  Will fix ASAP
