### ISSUE TITLE
Make it optional to use CORS-IT proxy when importing from URL

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-editor#455]
* [x] Add `no-proxy` query parameter for disabling cors-it proxy 
* [x] Add a checkbox in Import URL dialog to enable/disable using cors-it proxy 
* [ ] Add drag and drop for import

Related to: https://github.com/swagger-api/swagger-editor/issues/449

**Comment by who** [comment]
:+1: Love this idea. I have many internally-hosted specs that I would love to import into my internally-hosted swagger-editor.  Would this option also be toggle-able as a URL parameter?

**Comment by mohsen1** [comment]
Yes, we can have a query parameter (in fragment) to disable cors-it.

**Comment by jmccaffrey** [comment]
glad I found this ticket. 
I was having an issue when trying to load a swagger.json file from localhost, entering the url and trying to uncheck the CORS checkbox, and it would never load properly. 

Now that I see I can use this url to get it loaded without the proxy, I'm back in business. http://editor.swagger.io/#/?no-proxy&import=http://localhost:3000/api/json/swagger.json

Thanks for making an awesome thing awesomer!
