### ISSUE TITLE
Headers in response is not allowed

### ISSUE THREAD

**Issue by dejanberic** [swagger-api/swagger-editor#459]
Per swagger 2.0 spec headers in response are allowed.

From documentation: 

Response with headers:
```
{
  "description": "A simple string response",
  "schema": {
    "type": "string"
  },
  "headers": {
    "X-Rate-Limit-Limit": {
      "description": "The number of allowed requests in the current period",
      "type": "integer"
    },
    "X-Rate-Limit-Remaining": {
      "description": "The number of remaining requests in the current period",
      "type": "integer"
    },
    "X-Rate-Limit-Reset": {
      "description": "The number of seconds left in the current period",
      "type": "integer"
    }
  }
}
```

When I paste JSON in editor I get validation error saying that headers is not allowed although it should be.

**Comment by webron** [comment]
Renders fine to me.

**Comment by mohsen1** [comment]
which version Swagger Editor are you using? In previous release we've added response headers rendering feature. It's live at [online editor](http://editor.swagger.io)
