### ISSUE TITLE
allOf compositions still broken

### ISSUE THREAD

**Issue by BobWall23** [swagger-api/swagger-editor#464]
This is referencing the master branch, updated as of this afternoon (May 22, 2015).

Try adding this to the end of the definitions in default.yaml
```
  Base:
    properties:
      f1:
        type: string
      f2:
        type: integer
        format: int32
    required:
    - f1
  I1:
    type: object
    allOf:
      - $ref: '#/definitions/Base'
      - properties:
          f3:
            type: string
```
and add this at the end of `Activities`, after the `history` property:
```
      i1s:
        type: array
        items:
          $ref: '#/definitions/I1'
```
Validation reports the following warning:
`Definition is defined but is not used: #/definitions/I1/allOf/1`

Doesn't seem to matter on the indentation under the `allOf` - changing it to match the documentation in swagger-spec didn't help:
```
  I1:
    type: object
    allOf:
      - $ref: '#/definitions/Base'
      - properties:
          f3:
            type: string
```
produced the same warning

**Comment by mohsen1** [comment]
Was this working with no warning before?

**Comment by BobWall23** [comment]
It was - I had it working today, but I was still having problems with the unused definition warning, so I pulled and then couldn’t restart the server. I checked out a fresh copy of the repo and tried it - same result. I just removed node_modules and app/bower_components - same error.
