### ISSUE TITLE
Accept-Language header parameter ignored in live request

### ISSUE THREAD

**Issue by triccardi-systran** [swagger-api/swagger-editor#470]
```yaml
swagger: '2.0'

info:
  version: "0.0.0"
  title: Accept-Language header parameter ignored in live request

# Describe your paths here
paths:
  /:
    get:
      parameters:
        - name: Accept-Language
          in: header
          type: string
      responses:
        200:
          description: Successful response
```

The `Accept-Language` header parameter is ignored when using the live request feature of the editor: it sends `Accept-Language: en-US,en;q=0.8,fa;q=0.6,sv;q=0.4`.

Other headers are overridden too, see https://github.com/swagger-api/swagger-editor/blob/98794c36b0d1269ef1772562d73f866ed2d30f8c/app/scripts/directives/tryoperation.js#L585-L597

`_.extend()` erases headers from swagger spec with "default" header values.
If we really want the "default" headers to be default values, `_.defaults()` should be used instead.

However, maybe some headers should be overridden instead of just having default value, or maybe not.

**Comment by mohsen1** [comment]
You're right. We should extend `defaultParams`. Will fix this ASAP
