### ISSUE TITLE
Can't omit key/value pair for missing values

### ISSUE THREAD

**Issue by actsasbuffoon** [swagger-api/swagger-editor#473]
I have an optional field with no default value, but it keeps getting included in the request.

```yaml
swagger: "2.0"
info:
  description: Simple example
  version: "1.0.0"
  title: Example
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: 127.0.0.1:8080
schemes:
  - http
paths:
  /items:
    post:
      description: "Test"
      responses:
        200:
          description: "Good"
      parameters:
        - schema:
            "$ref": "#/definitions/Item"
          name: "query"
          in: body
definitions:
  Item:
    type: object
    properties:
      other_thing:
        type: string
      
      # This is the field that I want to omit if it lacks a value. No default is set.
      category_id:
        type: integer

    # It's not in the required attributes list.
    required:
      - other_thing
```

If I hit the "Try this operation" button and don't fill anything in, then this is the JSON payload it presents me with:

```json
{
  "category_id": 0,
  "other_thing": ""
}
```

The problem is that querying with a `category_id` of `0` causes the API to do something completely different than not passing a `category_id`. Since `category_id` isn't required and doesn't have a default value, I'd prefer this payload:

```json
{
  "other_thing": ""
}
```

I tried setting a default of `null`, but Swagger won't accept that. I like that from a strong-typing perspective, but it leaves me further confused about how to avoid passing a `category_id` when the user doesn't set one.

**Comment by mohsen1** [comment]
This is an [upstream issue with JSON Editor[(https://github.com/jdorn/json-editor/issues/406)
