### ISSUE TITLE
Download YAML and JSON are not working

### ISSUE THREAD

**Issue by david-hoyle** [swagger-api/swagger-editor#474]
Just cloned the latest repo and installed. Generate Client(s) works, but Download YAML and Download JSON do not. This seems like the only mechanism you can use to save a file locally/create your own YAML.

**Comment by mohsen1** [comment]
Yes I noticed this issue and fixed it at 5e05323 couple of minutes ago. Please get the latest again

**Comment by david-hoyle** [comment]
Thanks @mohsen1!
