### ISSUE TITLE
An empty array for the security field of an operation object does not remove top-level security declarations.

### ISSUE THREAD

**Issue by kag0** [swagger-api/swagger-editor#475]
An empty array for the security field of an operation object does not remove top-level security declarations.
Rather an empty security section is generated. Also, selecting "try this operation" also gives the options to use the top level security declarations. 

EDIT:
Upon more examination it seems like operations do not inherit the top level security at all. That is, if there are security requirements defined in the "security" field of the swagger object and no "security" field is defined for an operation object then the operation is rendered as having no security fields (no security header). Expected behavior would be that the operation is expressed the same as if it explicitly provided a "security" field identical to the top level "security" field.

**Comment by mohsen1** [comment]
We're *extending* parent values(security or parameters). I'm not sure if we should override parent values when you put empty array in lower levels.
@webron what is the right way to go?

**Comment by webron** [comment]
That's a good question. I know what the spec says but please remind me in a couple of days.

**Comment by kag0** [comment]
@mohsen1 we/you should be overriding the parent values according to spec at https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#operationObject . The security field states "This definition overrides any declared top-level security. To remove a top-level security declaration, an empty array can be used."

**Comment by mohsen1** [comment]
@webron Apparently it's clear that if array is empty we should remove upper level securities also. What should happen if we don't provide an empty array? Should we extend the upper level security array with current array?

**Comment by kag0** [comment]
The spec indicates that operation level security arrays should override top-level security arrays. The top-level security should seemingly only be extended when the operation level does not define a security array.

**Comment by webron** [comment]
Okay, so if the top level security is defined, it is inherited by all operations.

If an operation wants to override it, it can, with an empty array to completely remove it. There's no way to add to it, besides defining everything from the top level and the additional ones at the operation itself.

**Comment by mohsen1** [comment]
@webron is the same behavior for `schemes`, `consumes` and `produces`? If I define empty array in operation level, it overrides the root definitions?

**Comment by webron** [comment]
Yup.

**Comment by mohsen1** [comment]
This is fixed at e746aed
