### ISSUE TITLE
Run behind Apache proxy to adapt the URL

### ISSUE THREAD

**Issue by mbeko** [swagger-api/swagger-editor#477]
I have an Apache server running several services on Debian 7.8 and wanted to add Swagger Editor.

I installed Node.js from the Backports repository and npm with the install script fetched via curl. After adding a `nodejs` user and adapting the port in `grunt/connect.js`, I run `npm start` as that user, so the dependencies are fetched. For those operations, I temporarily enabled internet access for the server, then disabled it again. This worked, I could access the editor at the given port.

Then I changed `connect.js` to listen only on `localhost` and added the following to Apache's virtual host configuration as I did with the other services:
```apacheconf
ProxyPass         /swagger-editor http://localhost:${Swagger Editor port}
ProxyPassReverse  /swagger-editor http://localhost:${Swagger Editor port}
ProxyPassReverse  /swagger-editor http://${host name}:${Swagger Editor port}
```

When trying to access `http://${host name}/swagger-editor` in the browser, only the `index.html` is loaded and Apache's `error.log` shows errors of the kind:
```
File does not exist: /var/www/styles, referer: https://${host name}/swagger-editor 
File does not exist: /var/www/scripts, referer: https://${host name}/swagger-editor 
File does not exist: /var/www/images
```

Apparently, Swagger Editor uses incomplete resource URLs, thus cannot find its files and searches them in Apache's document root `/var/www`. In other services, I can configure a base path or web context to be prepended to the relative URLs but I cannot find it for Swagger Editor.

Do you think this is the cause for the error? Assuming it is, is there a way to specify that base path in a central place?

**Comment by mohsen1** [comment]
Swagger Editor uses relative paths to load it's resources. Maybe you should put a wild card after `http://${host name}/swagger-editor` to allow other resources to load. I don't know much about Apache configs so I don't know how you can do that. If you open the online editor and open up network tab in the browser developer tools you'll see all the files Swagger Editor fetches.

**Comment by mbeko** [comment]
I think the Apache configuration is alright since it works this way with the other web apps (Redmine, Jenkins etc.) on the server. The main difference is that in those apps I can configure a base path, so for Swagger Editor, it would be something like `base = "swagger-editor"`.

This way, all relative URLs could use that value in front of them to address the resources correctly, e.g. `${base}/images/favicon-16x16.png`.

Anyway, thank you for the hint with the online editor, maybe I can manage to find and replace all relative paths. It would be a nice feature to have a central configuration for this as it is common in web apps, but I'm not sure if I can provide a pull request because I don't have much experience with Javascript development.

**Comment by mohsen1** [comment]
All resources use `./styles` or `./scripts` prefix in their URLs. If that helps.

**Comment by mbeko** [comment]
Thanks! I hope I can ignore the requests to http://generator.swagger.io, otherwise I found these prefixes in the online editor:
* `styles`
* `scripts`
* `config`
* `images`

Tomorrow I'll try to search for these in all files in the `dist` folder and add the base path.

**Comment by mohsen1** [comment]
You can disable the code generators. [Docs](https://github.com/swagger-api/swagger-editor/blob/master/docs/config.md)

**Comment by mbeko** [comment]
Alright, it seems to work now except for the example files not being loaded and the URL being strangely rewritten to `http://${host name}/swagger-editor#/`.

There were more prefixes to change, all in all these are:
* `styles`
* `scripts`
* `config`
* `images`
* `templates`
* `spec-files`
* `bower_components`
* `views`

I had to modify the following files:
* `config/defaults.json`
* `index.html`
* `scripts/317074e0.scripts.js`
* `styles/6b0dfbac.main.css`
* `templates/operation.html`
* `views/main.html`
* `views/preview/preview.html`
* `views/header/header.html`

Could you point me to how you would go about making a central option for this? Which config file would best contain this option and how would you replace the variable in all those files with the actual value? With some general orientation, I could implement that, I guess.

**Comment by mohsen1** [comment]
In other static file servers I tried, all relative URLs are working. So it's not something we can fix here. It's probably your Apache configs. As you said, you can find and replace those strings.

**Comment by mbeko** [comment]
Have you used a reverse proxy adding a base path after the domain name in those other servers? This is where the problems start with Apache.

As I mentioned, the Apache config works with other popular web apps and they all provide a central configuration, so one doesn't have to tediously debug, find and replace. And apparently adapting the URLs _is_ fixing the problem, I'd only like to make it more convenient.

Also, this feature would help me a lot while it wouldn't disturb other users who can leave the option by default as `base = ""`.

I don't expect anyone to implement this, I'd only welcome some general guidance because I'm not too familiar with the capabilities of Grunt etc. I imagine that it should be straightforward to read the variable value from a configuration and run a find-and-replace task after copying all to `dist`. I just hope you can tell me the best location of this configuration and the basic structure of such a task. Providing the right manual pages could be enough. Or is it not that easy?

**Comment by mohsen1** [comment]
I hope you figured it out. I'm closing the issue for now. Please feel free to open new issues if you're having other problems.

**Comment by mbeko** [comment]
Well, not really, still digging through Grunt documentation and plugins, but it's OK, then I'll have to do it on my own.

**Comment by mudithae** [comment]
![image](https://user-images.githubusercontent.com/3122431/28823031-554023b8-76d9-11e7-9ff4-baace710eea4.png)

` ProxyPreserveHost On` did the trick for me.

**Comment by mbeko** [comment]
Thanks a lot for sharing your solution, @mudithae!

In the meantime, they started to release the editor as a set of static files to place in `/var/www`. This worked immediately without any further problems, so I stopped bothering with the custom build.

Nevertheless thanks, I will keep it in mind for when I stumble upon such problem again.

**Comment by mpbunch** [comment]
-- Mental Note -- 
ProxyPass               / http://127.0.0.1:81/
The trailing slash is required for assets to load correctly else:
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /css/typography.css.
Reason: DNS lookup failure for: 127.0.0.1:81css
