### ISSUE TITLE
Build 'Aborted due to warnings.' optipng ENOENT in file app/images/favicon-16x16.png

### ISSUE THREAD

**Issue by RobFerguson** [swagger-api/swagger-editor#478]
**Environment:**
OS X Yosemite
node v0.12.4
npm 2.10.1

**Commands:**
```
git clone https://github.com/swagger-api/swagger-editor.git
cd swagger-editor
npm start
```
**npm-debug.log:**
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart swagger-editor-src@2.9.6
7 verbose unsafe-perm in lifecycle true
8 info swagger-editor-src@2.9.6 Failed to exec prestart script
9 verbose stack Error: swagger-editor-src@2.9.6 prestart: `npm run build`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid swagger-editor-src@2.9.6
11 verbose cwd /Users/robferguson/opt/WebStorm/projects/swagger-editor
12 error Darwin 14.3.0
13 error argv "node" "/usr/local/bin/npm" "start"
14 error node v0.12.4
15 error npm  v2.10.1
16 error code ELIFECYCLE
17 error swagger-editor-src@2.9.6 prestart: `npm run build`
17 error Exit status 1
18 error Failed at the swagger-editor-src@2.9.6 prestart script 'npm run build'.
18 error This is most likely a problem with the swagger-editor-src package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm run build
18 error You can get their info via:
18 error     npm owner ls swagger-editor-src
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```
**Aborted due to warnings:**
```
Warning: Running "imagemin:dist" (imagemin) task
Warning: Error: spawn /Users/robferguson/opt/WebStorm/projects/swagger-editor/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng ENOENT in file app/images/favicon-16x16.png Use --force to continue.
```

**Work around:**
npm install -g bower grunt-cli
npm install
bower install
grunt serve

**Comment by mohsen1** [comment]
The build was successful in my attempt in OSX. I have iojs but all Node versions are successfully working in the [CI](https://travis-ci.org/swagger-api/swagger-editor). 

The reference to `app/images/favicon-16x16.png` was changed in index.html in recent commits. I suggest removing all temporary folders (`.tmp` `.grunt`), clean up dependency folders (npm and bower) and get the latest before starting again. You should not have to install bower and grunt. Alos `grunt serve` is not equal to `npm start`. `grunt serve` starts the development mode while `npm start` serves a built version.

**Comment by Robinyo** [comment]
I believe the issue was caused by a recent migration to OS X Yosemite.

What fixed the problem for me was to uninstall then reinstall `node` via `brew`:

    npm cache clean
    brew uninstall --force node
    rm -r /usr/local/lib/node_modules
    brew install node

   'which node' returns `/usr/local/bin/node`

And, to set NODE_PATH in my `.bash_profile`:

    export NODE_PATH=/usr/local/lib/node_modules

Note: `npm` works without `sudo`

**Comment by d-smith** [comment]
I see this problem trying to build the docker image in commit 9e8470d3d3a1dce18696ff90da0c8c85209bedde:

<pre>
    Running "imagemin:dist" (imagemin) task
    Warning: Error: spawn ENOENT in file app/images/favicon-16x16.png Use --force to continue.

    Aborted due to warnings.
<pre>
