### ISSUE TITLE
Swagger Editor show Structural error at openapi for 3.1.0

### ISSUE THREAD

**Issue by Spenhouet** [swagger-api/swagger-editor#4798]
### Q&A (please complete the following information)
 - Swagger-Editor version: Unknown
 - Swagger/OpenAPI version: 3.1.0

### Content & configuration

My Swagger/OpenAPI definition contains the version 3.1.0 as openapi version:

```json
{
    "openapi": "3.1.0",
    "paths": {},
    "info": {
      "title": "Bug Report",
      "version": "1.0.0"
    },
}
```

### Describe the bug you're encountering

When opened in https://editor.swagger.io/, it shows the error:

```text
Structural error at openapi
should match pattern "^3\.0\.\d(-.+)?$"
pattern: ^3\.0\.\d(-.+)?$
Jump to line 2
```

### Expected behavior

Using version 3.1.0 should not yield any validation error.

### Screenshots

![image](https://github.com/swagger-api/swagger-editor/assets/7819068/cea28e7a-bb1e-40b0-a661-e2b4d48c2124)

**Comment by JonhyOliveira** [comment]
I'm having the same issue. I wouldn't mind opening up a fix for this, as it looks like a fairly simple one.

**Comment by hbirkdale** [comment]
Same issue here

**Comment by frankkilcommins** [comment]
The current version of SwaggerEditor (v4) deployed to `https://editor.swagger.io` does not support OAS 3.1. If you're looking for 3.1 support, then please utilize SwaggerEditor (v5) which is deployed to https://editor-next.swagger.io/

**Comment by frankkilcommins** [comment]
@Spenhouet nice spot. Thanks! We've created #4806 for that specific issue. 

**Note:** Only **SwaggerEditor@5** supports [OpenAPI 3.1.0](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md). **SwaggerEditor@4** will not receive OpenAPI 3.1.0 support and is considered legacy at this point. The plan is to continually migrate fully to SwaggerEditor@5 and deprecate the SwaggerEditor@4 in the future, meaning that v5 will eventually be what's deployed to https://editor.swagger.io. 

I'll close this issue as a result and we can track support of the URL query param via #4806

**Comment by martinbonnin** [comment]
> The current version of SwaggerEditor (v4) deployed to https://editor.swagger.io does not support OAS 3.1. If you're looking for 3.1 support, then please utilize SwaggerEditor (v5) which is deployed to https://editor-next.swagger.io/

Isn't 3.1.0 the latest stable version though? Could the logic be updated?

* https://editor.swagger.io/. <= Always point to latest stable version
* https://editor-3-1.swagger.io/
* https://editor-3-0.swagger.io/
* etc...

**Comment by Myslawek** [comment]
> > The current version of SwaggerEditor (v4) deployed to https://editor.swagger.io does not support OAS 3.1. If you're looking for 3.1 support, then please utilize SwaggerEditor (v5) which is deployed to https://editor-next.swagger.io/
> 
> Isn't 3.1.0 the latest stable version though? Could the logic be updated?
> 
>     * https://editor.swagger.io/. <= Always point to latest stable version
> 
>     * https://editor-3-1.swagger.io/
> 
>     * https://editor-3-0.swagger.io/
> 
>     * etc...

Unfortunately it is still the case in 2025. Main editor does not support 3.1.

**Comment by paustint** [comment]
Anyone that finds this: https://editor-next.swagger.io/

**Comment by buddemat** [comment]
> The current version of SwaggerEditor (v4) deployed to `https://editor.swagger.io` does not support OAS 3.1. If you're looking for 3.1 support, then please utilize SwaggerEditor (v5) which is deployed to https://editor-next.swagger.io/

Just a note on this: The [webpage](https://swagger.io/tools/swagger-editor/) that links to SwaggerEditor (v4) states:
```
Design, describe, and document your API on the first open source editor supporting multiple API specifications and serialization formats. The Swagger Editor offers an easy way to get started with the OpenAPI Specification (formerly known as Swagger) as well as the AsyncAPI specification, with support for Swagger 2.0, OpenAPI 3.*, and AsyncAPI 2.* versions.
```
which would suggest to me, that OpenAPI 3.1 is supported. Maybe the text should be changed from `OpenAPI 3.*` to `OpenAPI 3.0` then?
