### ISSUE TITLE
Add support for externalDocs attributes

### ISSUE THREAD

**Issue by chrisdudley** [swagger-api/swagger-editor#480]
The Swagger 2 spec supports an optional 'externalDocs' on several objects:
Swagger, Operation, Tag and Schema.

The externalDocs attribute is an 'externalDocumentationObject' which has a description and a url.
https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#externalDocumentationObject

Is it possible to add support to swagger editor for those please?

**Comment by mohsen1** [comment]
@webron It doesn't make sense to support markdown in description of an external doc. If description of external docs is markdown then it means it can contain a lot of things like tables, headings and so on. 

Maybe it should be plain text instead?

**Comment by mohsen1** [comment]
For example this external doc can be rendered in a simple link:

```yaml
description: Find more info here
url: https://swagger.io
```
```html
<a href="https://swagger.io">Find more info here</a>
```

But if description is a complex markdown document it becomes tricky to render and support all cases

**Comment by chrisdudley** [comment]
For what it's worth plaintext would be good enough for my needs. 
Thanks!

**Comment by webron** [comment]
It's not my place to say whether it makes sense or not. People should use it however they want. If they want to go crazy, let them.

**Comment by mohsen1** [comment]
What is the necessity of having markdown here?

**Comment by webron** [comment]
It's part of the spec. Can't be changed now.
