### ISSUE TITLE
SwaggerEditor@next: v5 not found on NPM registry

### ISSUE THREAD

**Issue by marcodarko** [swagger-api/swagger-editor#4805]
### Q&A (please complete the following information)
 - OS: [e.g. macOS] MacOS
 - Browser: [e.g. chrome, safari] Chrome
 - Version: [e.g. 22] node v20
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-Editor version: [e.g. 3.10.0] 5 beta
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for swagger-editor@5.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

Example Swagger/OpenAPI definition:
N/A

Swagger-Editor configuration options:
N/A

### Describe the bug you're encountering
When installing from the npm registry it says version cannot be found

### To reproduce...

1. nvm i 20
2. nvm use 20
3. npm install swagger-editor@>=5
4. *Error*

### Expected behavior
Successful basic installation

### Screenshots
<img width="646" alt="Screenshot 2024-02-12 at 2 25 05 PM" src="https://github.com/swagger-api/swagger-editor/assets/23092057/3526e1e8-2ff0-4e19-99ae-53153958b461">

**Comment by char0n** [comment]
Hi @marcodarko,

Thanks for noticing this out. I've updated the documentation with the fixed instructions: https://github.com/swagger-api/swagger-editor/pull/4985

`swagger-editor` in `v5` is using `alpha` release channel/tag. To install latest version of swagger-editor v5, use the following command:

```sh
$ npm install swagger-editor@alpha
```

To install specific version of swagger-editor v5, use the following command:

```sh
$ npm install swagger-editor@5.0.0-alpha.93
```
