### ISSUE TITLE
XML Respone with Swagger

### ISSUE THREAD

**Issue by dpatra1** [swagger-api/swagger-editor#485]
Hi,

I am new to Swagger and i have integrated in my Spring boot application to generate the api documentation. Its working fine with two known issue like:

1)  when i am trying to test any API from Swagger UI, i dont have a option to select whether i wanted XML/JSON option. It always gives me the JSON response only .

Also in case of PUT/POST apis i wanted the request payload to  send based upon the users choice like JSON/XML, but i can see only JSON is coming up in the drop down.

I read lots of blog and discussion w.r.t Swagger UI and every where i see its been asked to use consume/produces in the @Apiresponse . I have used them as well but it has no impact at all.

2) Also i have another issue like, i wanted to display some more static information in the Swagger UI w.r.t my application  other than the auto generated API documentation which Swagger is populating after integrating with my application. I tried but un-success to add any static content in the index.html. 

can someone help me getting this issue resolved ?

Thanks,
Deba

**Comment by mohsen1** [comment]
Swagger supports multiple content-types, you need to put them in `produces` array. Please provide your Swagger spec so we can help further.

[Swagger UI](https://github.com/swagger-api/swagger-ui) is a different project, if you're using it open an issue there.

**Comment by dpatra1** [comment]
May be i am wrong the way i have integrated Swagger and Swagger-UI in my application but i am using the produces array as well.

Here is the annotation i have used in one of my Rest web services:
//This is Controller level
@Api(value="/v1", description="This service controller exposes the business banking service API model. \n" + 
		  "service method consumes the bbs data services and repositories.", 
		  			produces = "application/json, application/xml", consumes = "application/json, application/xml")
@RequestMapping (value = "/v1")
@RestController
class ApiController {
.....

//This is Operation level
    @ApiOperation(value = "createCompany", notes = "Create a business banking {@link Company}.", consumes = "application/json, application/xml")
    @ApiResponses(value = {
			@ApiResponse(code = 201, message = "Successfully created a Company"),
			@ApiResponse(code = 409, message = "Unable to create a Company due to some error"),
			@ApiResponse(code = 500, message = "Internal server error")})
    @SuppressWarnings("rawtypes")
	@RequestMapping (method = RequestMethod.POST, value = "/fis/{fiId}/companies")
    public ResponseEntity createCompany(@ApiParam(name = "fiId", value = "ID of the FinancialInstitution associated with the customer", required = true)
    									@PathVariable("fiId") String fiId, 
    									@RequestBody Company company, 
    									HttpServletRequest request, HttpServletResponse response) {
...

Here is the dependency in my pom:
      <dependency>
		    <groupId>com.mangofactory</groupId>
		    <artifactId>swagger-springmvc</artifactId>
		    <version>1.0.2</version>
		</dependency>
		       
		<dependency>
		    <groupId>org.apache.tomcat.embed</groupId>
		    <artifactId>tomcat-embed-jasper</artifactId>
	    	<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.wordnik</groupId>
			<artifactId>swagger-core</artifactId>
			<version>1.5.0-M2</version>
		</dependency>

I am using java 8 with Spring boot to develop micro services.

Let me know if i need to file an issue in Swagger UI or you can help me here with my issues .

Thanks,
Deba

**Comment by mohsen1** [comment]
Please check Swagger-Core and Swagger UI projects in this Github org. This has nothing to do with Swagger Editor.

**Comment by dpatra1** [comment]
Sorry i am not clear . Can you please clearly explain what should i do to get this working ?

I am new to Swagger so may be getting confused with Swagger and Swagger-UI

**Comment by mohsen1** [comment]
Here you go: https://github.com/swagger-api/swagger-core

Read the docs and if you couldn't find the answer, ask in StackOverflow or open an issue. You can also join the IRC channel #swagger

**Comment by dpatra1** [comment]
Thanks
