### ISSUE TITLE
Unable to download JSON or YAML file

### ISSUE THREAD

**Issue by guw** [swagger-api/swagger-editor#487]
I'm running Swagger Editor locally on Mac using today's master. The about info says v2.9.6. If I go to File -> Download YAML or File -> Download JSON nothing happens. There is no pop up, nothing. This is on latest Chrome. It broke after a git pull. 

OS X 10.10.3
Chrome 43.0.2357.124 (64-bit)
node.js v0.12.4

I also tried a fresh clone. Same problem. I don't get the prompt/dialog to store any file.

**Comment by arbuh** [comment]
I have the same issue with v2.9.6. on Mac. So the JSON or YAML download does not work to me: nothing happens after I press the corresponding menu items.

OS X 10.10.3
Safari 8.0.6 or FF 36.0.4
node.js v0.12.4

**Comment by mohsen1** [comment]
It's an issue in the new Angular Bootstrap. `on-toggle` is not being triggered on dropdown menus

**Comment by danielm64** [comment]
Same problem with :

Windows Seven Entreprise SP1
Internet Explorer 11
node.js v0.10.33
swagger-editor 2.9.6 (master downloaded on July 1st)

Same angular issue ?

Works without any pb with navigators:
Firefox 38.0.5
Chrome 43.0.2357.130

**Comment by grosch** [comment]
Still having this issue on 1/27/2017 with latest Safari on mac.
