### ISSUE TITLE
should allow description used with $ref

### ISSUE THREAD

**Issue by calvin2021y** [swagger-api/swagger-editor#4884]
A schema is used in multi location,  each location could be used for different purposes.  so add description to explain should be allowed. 

And for swagger 3.0.3,  the type name is show at the location of $ref,    this is very useful.

for https://editor-next.swagger.io/ with 3.1.0, I can not find type name from the location of $ref,  this is confused.

**Comment by char0n** [comment]
Hi @calvin2021y,

> A schema is used in multi location, each location could be used for different purposes. so add description to explain should be allowed.

I assume you're referring to the OpenAPI 3.0.x [Reference Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#reference-object). The OpenAPI specification is pretty clear about this:

> This object cannot be extended with additional properties and any properties added SHALL be ignored.

You can bypass this limitation by using specification extension fields:

```yaml
components:
  schemas: 
    schema1:
      type: object
      properties:
        prop1:
          $ref: "#/components/schemas/schema2
          x-description: description of the reference
    schema2:
      type: string  
```

OpenAPI 3.1.0, `description` and `summary` fields are allowed inside the Reference Object.

> And for swagger 3.0.3, the type name is show at the location of $ref, this is very useful.
> for https://editor-next.swagger.io/ with 3.1.0, I can not find type name from the location of $ref, this is confused.

This unfortunately I do not understand. Please reopen this issue with further elaboration or examples.

**Comment by calvin2021y** [comment]
>>> This object cannot be extended with additional properties and any properties added SHALL be ignored.

This is unreasonable.

When you reuse M components in a N place, there will be  N*M extra new components need to defined.   it is hard to modify and maintain.
