### ISSUE TITLE
Annotating YAML spec with contextual comments/discussions

### ISSUE THREAD

**Issue by xuanli09** [swagger-api/swagger-editor#489]
In our workflow, we find it useful for multiple people to review and discuss the spec. One of the pain point is having a persistent commenting feature in the editor like Google Doc.  We usually have to store these comments elsewhere. 

Can this enhancement be implemented by making use of the node_id in the AST and attaching a thread to it? Are the node ids deterministically generated each time the YAML is loaded?

**Comment by mohsen1** [comment]
So if I understood it correctly you don't want to have those comments in the YAML itself. As of right now we don't have any plans to introduce Google Docs style commenting system. 

I suggest using comments in the YAML with some specific format or use a vendor extension node like `x-comments` to put in your comments

**Comment by xuanli09** [comment]
Yes that's correct. Usually these are threaded discussions, so it doesn't really feel right to be a comment embedded in the spec.

**Comment by mohsen1** [comment]
I know that would be really nice to have but it's a big item and as of now we don't have any plans to do it. 

I've created [this issue](https://github.com/swagger-api/swagger-editor/issues/490) to help you pointing to specific parts of the specs better. 

I'm closing this issue for now.
