### ISSUE TITLE
Freshly pulled swagger-editor@next is missing react-scripts

### ISSUE THREAD

**Issue by HendrikPetertje** [swagger-api/swagger-editor#4938]
### Q&A (please complete the following information)
 - OS: MacOS Sonoma 14.4.1 (23E224)
 - Browser: does not apply
 - Version: v5.0.0-alpha.92 (and current head of @next branch 0cb98286a18c6403930b6decdf03867f5e3ea1a5) 
 - Method of installation: npm install
 - Swagger-Editor version: v5.0.0-alpha.92 (and current head of @next branch 0cb98286a18c6403930b6decdf03867f5e3ea1a5) 
 - Node v20.11.1

### Content & configuration

I cloned the swagger editor and checked out the next branch, I removed the node_modules folder and did a fresh `npm install` 
after that I tried npm run start (the new start command for the next branch it seems) which resulted in:

```sh
▶ npm run start

> swagger-editor@5.0.0-alpha.92 start
> cross-env DISABLE_ESLINT_PLUGIN=false ENABLE_PROGRESS_PLUGIN=true react-scripts start

node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: spawn react-scripts ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn react-scripts',
  path: 'react-scripts',
  spawnargs: [ 'start' ]
}

Node.js v20.11.1
```

I then ran npm run test, to see if the problem was with the server port assignment or something else:

```sh
▶ npm run test

> swagger-editor@5.0.0-alpha.92 test
> react-scripts test

sh: react-scripts: command not found
```

Upon closer inspection it seems that `node_modules/.bin/react-scripts` is not created on npm install

### Screenshots
![image](https://github.com/swagger-api/swagger-editor/assets/3583395/8009e2e1-d170-43f6-a5db-386adce7a385)
![image](https://github.com/swagger-api/swagger-editor/assets/3583395/22568e3f-2493-42fd-baa1-2b5a54df60bf)

### How can we help?
How do i install all dependencies correctly and start a base development server (or build for that matter) in the new next branch?

**Comment by char0n** [comment]
Hi @HendrikPetertje,

Please have a look at **Setting up** instructions for the `next/v5` branch: https://github.com/swagger-api/swagger-editor/tree/next?tab=readme-ov-file#setting-up

**Comment by krnbr** [comment]
tried the following as per docs:-

 $ git clone https://github.com/swagger-api/swagger-editor.git
 $ cd swagger-editor
 $ git checkout next
 $ git submodule init
 $ git submodule update
 $ npm i
 $ npm start
 
 it is giving error
 
 > cross-env NODE_OPTIONS=--max_old_space_size=4096 ENABLE_PROGRESS_PLUGIN=false DISABLE_ESLINT_PLUGIN=false react-scripts build

node:events:489
      throw er; // Unhandled 'error' event
      ^

Error: spawn react-scripts ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn react-scripts',
  path: 'react-scripts',
  spawnargs: [ 'build' ]
}

**Comment by krnbr** [comment]
Ok, I just googled - used `git submodule update --init --recursive ` 

since I already had initialized the submodule, I had to deleted the content of the create-react-app before running `git submodule update --init --recursive `

**Comment by dani-corie** [comment]
Why is this issue closed when README.md still doesn't show the correct commands needed to run the editor?
