### ISSUE TITLE
Make examplesFolder path relative

### ISSUE THREAD

**Issue by Russell-** [swagger-api/swagger-editor#496]
I need to make the editor available in my local network.  So I cloned it from git and than ran "npm run build".  I then copied what was in the dist directory to the document root of my Apache server under a new context called "swaggereditor".  When I then went to that URL what I see is shown below:

![se](https://cloud.githubusercontent.com/assets/11182689/8165580/8833f090-135f-11e5-8c81-708027d90d73.JPG)

It appears that the default.yaml is not loading correctly.  I noticed that if you change the default.json in the config directory to remove the leading slash from the "examplesFolder" value so it is  "spec-files/" and NOT "/spec-files/" I can see the default.  However, when I look at the HTTP requests I see other 404s as shown in the image below.  These items need to be changed to be able to handle a "context" (i.e. where the contents of the dist directory are not placed in DocumentRoot).

![traffic](https://cloud.githubusercontent.com/assets/11182689/8165614/cfc88dda-135f-11e5-9507-fc524bb34ba4.JPG)

**Comment by Russell-** [comment]
The best way to get to the bottom of this is to install the dist directory in a new folder below "DocumentRoot" of any web server, e.g. in a folder called swaggereditor.  Now press F12 in most browsers (e.g. Chrome, Firefox) so you can see the network traffic and then go to http://hostname/swaggereditor and you should see various 404s.  It would be best to try different operations to make sure all the 404s are fixed.

**Comment by mohsen1** [comment]
You can change the example folder in the configs. See all configuration options [here](https://github.com/swagger-api/swagger-editor/blob/master/docs/config.md)

**Comment by Russell-** [comment]
Yes, I understand I can change the example folder and that is what I did as I explained in my first post.  But there should be no need for someone to change that if they do not change the relative location of the example folder.  I'm copying the whole distribution without any modification.  The only difference is instead of putting the whole distribution under the root of the ApacheServer I'm creating a context called "swaggereditor" and putting  the whole distribution there.  That also results in the other 404's that are shown in red in my second image.  Those also do not use the context.  There may be other instances too.  I've not tried various functions to see what other 404s may also be caused.

**Comment by mohsen1** [comment]
ok, `examplesFolder` [is absolute](https://github.com/swagger-api/swagger-editor/blob/master/app/config/defaults.json#L14) right now. We can change it to be relative

**Comment by Russell-** [comment]
That'll be great!  Thanks!

Please also look at the other two requests that are red / 404 in the second image.  I'm not sure how important they are for the editor to work correctly but the issue there is probably similar.  There may be other places where the same issue arises and it'll be nice for all of these to be addressed.  My initial post should be helpful to get these fixed, assuming you have Apache running.

**Comment by baruahp** [comment]
Hi, 

I copied the dist file into the apache-tomcat-6.0.29 in location bigeye/editor/
When i run this i am getting error as attached (unable to load default.yaml), i am able to open the examples after making changes in the config/defaults.json file as below:

  "examplesFolder": "/spec-files/",
to 
  "examplesFolder": "../../spec-files/",

can anyone help me out to resolve this,

Regards
baruahp

![swagger_issue](https://cloud.githubusercontent.com/assets/2578177/8694276/7846e454-2afb-11e5-8102-62e5081d2d71.png)

**Comment by danielm64** [comment]
see https://github.com/swagger-api/swagger-editor/issues/532

**Comment by Russell-** [comment]
My original title was "dist needs to handle a context".  However, mohsen1 changed that to "Make examplesFolder path relative".  That being the case I would not assume that what appears in the dist folder will work in any place other than at the root of the web-server.  As shown in my screen capture there are various other items which are not found even when I worked around the examples issue.  baruhap, I ended up putting it at the root level by creating a virtual host.

**Comment by mohsen1** [comment]
@baruahp have you tried making your `examplesFolder` a relative path like `./spec-files`?

**Comment by baruahp** [comment]
@mohsen1
ya i tried doing that, if i do so then the examples wont work as attached (echo.yaml 404 Not Found)

In order to remove this error i changed my 
./spec-files 
to 
"examplesFolder": "../../spec-files/", as per #532 

But in the end i ended up with the default.yaml loading problem as i mentioned in my above comment. If you have solution to my problem then please let me know. 

Regards
Baruahp

![swaggers1](https://cloud.githubusercontent.com/assets/2578177/8741879/e08b2764-2c7c-11e5-8969-7b5a15e1d4a6.png)

**Comment by baruahp** [comment]
@Russell- @mohsen1 
Hi.
Here is my final solution which i did to make both default.yaml file and examples to start working,

1) I kept ./spec-files  as it is( as said by mohsen1) 
2) I created one more directory structure like :-  bigeye/editor/spec-files/*yaml files* 
    inside my directory :- bigeye/editor 
    So that the examples should start working.

The 1st change is as per the my 1st comment, i,e,
GET http://localhost:8080/spec-files/default.yaml 404 (Not Found)

The 2nd change as per my 2nd comment, i,e,
GET http://localhost:8080/bigeye/editor/bigeye/editor/spec-files/echo.yaml 404 (Not Found)

Please let me know if you have any other way of handling the both issue by a single solution.

Screenshots:
1) Default loading without GET http://localhost:8080/spec-files/default.yaml 404 (Not Found) error:
![default](https://cloud.githubusercontent.com/assets/2578177/8744142/7e1aa5ee-2c92-11e5-9710-4bab87a0c81f.png)
2) Examples opening without GET http://localhost:8080/bigeye/editor/bigeye/editor/spec-files/echo.yaml 404 (Not Found) error
![echo](https://cloud.githubusercontent.com/assets/2578177/8744171/b4ee5e9e-2c92-11e5-8693-c37d681fd092.png)
Regards
Baruahp
