### ISSUE TITLE
Is it possible to provide Context Path to local Swagger Editor URL

### ISSUE THREAD

**Issue by kattav2** [swagger-api/swagger-editor#497]
Hello,

We have successfully installed Swagger Editor on a local server and this now runs on http://localhost:8080 

What we want is to provide a context path something like http://localhost:8080/apieditor 

Is this possible and do we need to set something in connect.js ?

Thanks,
VK

**Comment by mohsen1** [comment]
You can use [http-server](https://www.npmjs.com/package/http-server) module to serve at a different pathname. You can basically use any server. It might be possible to do it in connect.js, but I'm not sure how?

**Comment by kattav2** [comment]
Thank you @mohsen1 We moved the dist into webapps folder of a tomcat installation and were able to provide a context path for our local swagger editor. Earlier we were starting the editor via 'npm start'. Thanks again!
