### ISSUE TITLE
Misalignment of File Menu

### ISSUE THREAD

**Issue by aniketkudale** [swagger-api/swagger-editor#498]
There is a misalignment of File menu in swagger editor, while running it locally. Tested on Firefox and Chrome.
![swagger](https://cloud.githubusercontent.com/assets/7304008/8200306/c039f8f4-14e0-11e5-87b9-d463e80050c8.png)

**Comment by mohsen1** [comment]
Your probably failed at compiling less files. Do you see the same results in editor.swagger.io?

**Comment by aniketkudale** [comment]
No, but why it failed at compiling

**Comment by mohsen1** [comment]
It can be many things. Please try compiling again and share the logs if it's still not working properly
