### ISSUE TITLE
README should mention how to run on different port

### ISSUE THREAD

**Issue by hangtwenty** [swagger-api/swagger-editor#501]
Following on Issue #454 ... Shouldn't the README suggest using `npm run develop` and/or how to change the port?

**Comment by mohsen1** [comment]
It's a good point. We should at least mention it in [development guide](https://github.com/swagger-api/swagger-editor/blob/master/docs/development.md)

**Comment by hangtwenty** [comment]
Maybe more important is mentioning how to change the port... I kind of thing that should be mentioned in the README, and then `npm run develop` mentioned in the development guide? Does that make sense? Will submit PR if so

**Comment by hangtwenty** [comment]
aha! thank you :)
