### ISSUE TITLE
Collapse all Operations

### ISSUE THREAD

**Issue by chrisdudley** [swagger-api/swagger-editor#502]
Is there a way I can get the preview panel to collapse all Operations?
I'd like to keep all Paths expanded but collapse all the Operations within them.
It makes long APIs (such as the petstore_full) easier to see, otherwise there is a lot of scrolling :-)

If this is not the type of option wanted in the main repos then a pointer to where I could edit my own local copy would be appreciated please. :-)

**Comment by mohsen1** [comment]
This is something we can have. I see the value in implementing it.

**Comment by mohsen1** [comment]
As of bd9e444 this feature has been landed 

![screen shot 2015-09-08 at 6 05 23 pm](https://cloud.githubusercontent.com/assets/543633/9751017/3db541da-5654-11e5-8268-94158404d476.png)

**Comment by shankiesan** [comment]
I'd love to do this but I can't work out how! Can you please explain?

**Comment by shankiesan** [comment]
Oops – got it 
![image](https://cloud.githubusercontent.com/assets/2608862/21190745/c8e2b55c-c21a-11e6-9111-b15e0e9525f6.png)
