### ISSUE TITLE
Menu does not show well

### ISSUE THREAD

**Issue by rantibi** [swagger-api/swagger-editor#504]
Look on the image, this is how Swagger Editor shows after the installation.

![image](https://cloud.githubusercontent.com/assets/6207948/8236349/68717708-15f0-11e5-9eb2-0cfa6ca3a329.png)

**Comment by mohsen1** [comment]
It's very similar to #498. I don't see it on Mac. Apparently it's Windows specific

**Comment by mohsen1** [comment]
@rantibi Can you checkout `less-wiredep` branch and let me know if that fix is working for you?

**Comment by ndupreez** [comment]
Just checked this out. Its on Mac as well (Chrome & FF). Lastest commit:
'''
commit 05ad33d2b006d8db3ef45bc3a6ab023a19a1466b
Author: Mohsen Azimi <msn.azi@gmail.com>
Date:   Wed Jun 17 16:53:06 2015 -0700

    [build] revert 2a75154; There is no need for less includes
'''

**Comment by ndupreez** [comment]
If I revert the last commit (mentioned above) it works fine.

```
git checkout 992212b253ea80752e2a57481c22e745ee6d6f34
```

**Comment by bpytlik** [comment]
I see this on my Mac for Chrome, FF, and Safari. For me using the less-wiredep branch solved the problem.
