### ISSUE TITLE
Running locally with latest code gives imagemin error

### ISSUE THREAD

**Issue by Helmsdown** [swagger-api/swagger-editor#506]
With a fresh clone of master, running "npm start" eventually results in this error:

![image](https://cloud.githubusercontent.com/assets/1689115/8244597/921c7530-15d7-11e5-839d-8f3a6bfac187.png)

It's quite a possible this is an issue that is only happening for me (perhaps there is something weird on my linux box). 

Any help would be appreciated.

**Comment by mohsen1** [comment]
The [CI](https://travis-ci.org/swagger-api/swagger-editor/builds/67434269) is compiling with no issue. I'm guessing it's something on your machine. What version of Node.js are you using?

Just to make sure do a deep clean up:

```
rm -rf node_modules app/bower_components
bower cache clean
npm cache clean
npm start
```

**Comment by mohsen1** [comment]
Hopefully you got this sorted out. Let me know if you're still having issues...

**Comment by netei** [comment]
I also have this issue, I'm behind a proxy but everything is corrrectly setup (http_proxy, https_proxy)

**Comment by mohsen1** [comment]
@netei have you tried removing everything and a starting fresh?

**Comment by mohsen1** [comment]
@netei have you tried removing everything and a starting fresh?

**Comment by Helmsdown** [comment]
When I first encountered the issue I did as you suggest. 

Some interesting things to note, I only got the error on a Red Hat 7 server. I successfully run the build on my mac. I ended up just removing the imagemin command before running the build on the Red Hat 7 server.
