### ISSUE TITLE
Can not clone repository

### ISSUE THREAD

**Issue by rukiliii** [swagger-api/swagger-editor#507]
Hi, 

while trying to clone repo following error occurs:

*Cloning into 'D:\swagger-editor'...*

*fatal: https://github.com/swagger-api/swagger-editor.git/info/refs not valid: is this a git repository?*

What could be the reason?

Many thanks in advance,

Rukiye

**Comment by webron** [comment]
Just clone https://github.com/swagger-api/swagger-editor.git.

**Comment by rukiliii** [comment]
I tried to clone https://github.com/swagger-api/swagger-editor.git. The error describend in my issues was occured during this try

**Comment by mohsen1** [comment]
Maybe try SSH?: `git@github.com:swagger-api/swagger-editor.git`

**Comment by webron** [comment]
Just cloned the repository successfully. This is probably an issue with your git installation. You may be able to contact github's support for further support.

**Comment by rukiliii** [comment]
Unfortunatally i am not able to use SSH...

**Comment by mohsen1** [comment]
You can download directly from releases https://github.com/swagger-api/swagger-editor/releases/tag/v2.9.6
