### ISSUE TITLE
custom content type defined in consumes doesn't shows up in content-type dropdown

### ISSUE THREAD

**Issue by hongyes** [swagger-api/swagger-editor#509]
It seems that the Content-Type dropdown in "Try this operation" template is hard coded with application/json, multipart/form-data and x-www-form-urlencoded. No matter what I put in the consumes, nothing shows up in the dropdown. 

The Accept dropdown works as expected.

**Comment by mohsen1** [comment]
For each of application/json, multipart/form-data and x-www-form-urlencoded we use a different method to encode body of the request. I agree that we should allow other types of consumes but I'm not sure how the body encoding should look like?

What is the consumes value in your API?

**Comment by hongyes** [comment]
The content type is json with custom parameter, like application/json;format=xxx. I more like the experience in swagger UI that it gives a json sample payload and it can be editable and the content type is consistent with what is set in swagger document.
