### ISSUE TITLE
Can't send POST data

### ISSUE THREAD

**Issue by xackobo** [swagger-api/swagger-editor#512]
When I try to send some data via PHP it doesn't arrives to the server but it do with i.e. Postman.

For some reason it's using 'x-www-form-urlencode' not 'application/x-www-form-urlencode'.

Can you solve it?

Thanks!

**Comment by mohsen1** [comment]
Can you share your Swagger spec?

**Comment by xackobo** [comment]
sure!

https://gist.github.com/xackobo/367c15e80108adb8c91f

**Comment by mohsen1** [comment]
It's the same issue as https://github.com/swagger-api/swagger-editor/issues/509. Problem is, we use the `Content-Type` dropdown for choosing encoding method of the body and right now we have 3 predefined encoding methods. If you have a custom encoding method it's going to ignore it.
