### ISSUE TITLE
dev mode cannot run when configure hostname other than localhost

### ISSUE THREAD

**Issue by DavidBiesack** [swagger-api/swagger-editor#513]
I'm trying to run swagger-editor in development mode  locally, but on hostname swagger.na.sas.com instead of just localhost (so that I can share the instance on the network with others) 

I changed `grunt/connect.js` as shown below. This used to work a few weeks
ago, but after pulling the latest source (this morning) and starting with either
````
grunt serve
````
or
````
npm run develop
````
(as per the developer guide) fails - I get a blank window and no editor.

````
var developmentPort = process.env.PORT || 9000;
var productionPort = process.env.PORT || 8080;

module.exports = {
  options: {
    port: developmentPort,
    hostname: 'swagger.na.sas.com',
    livereload: 35729
  },
  livereload: {
    options: {
      open: 'http://swagger.na.sas.com:' + developmentPort,
      port: developmentPort,
      base: [
        '.tmp',
        'app'
      ]
    }
  },
  test: {
    options: {
      port: 9001,
      base: [
        '.tmp',
        'test',
        'app'
      ]
    }
  },
  dist: {
    options: {
      keepalive: true,
      base: 'dist',
      port: productionPort,
      open: true,
      hostname: /^win/.test(process.platform) ? 'localhost' : '0.0.0.0',
      livereload: false
    }
  }
};
````

Reverting  `grunt/connect.js`  to use localhost:9000 works.

Also, running production
```` 
  PORT=9000 npm start
````
works OK on http://swagger.na.sas.com:9000/#/ 

Note how I changed `connect.js` to allow using `PORT` for production, since I need to change that; I already have another service running on 8080

I can get by running production but won't have the reload that development provides (Is that spelled out somewhere - what does livereload provide that is not available in production?)

**Comment by mohsen1** [comment]
The change you've made in `connect.js` is a good change. Please submit a PR with that.

**Comment by DavidBiesack** [comment]
https://github.com/swagger-api/swagger-editor/pull/515

**Comment by DavidBiesack** [comment]
My change to `connect.js` does not fix the problem - I was merely showing what changes I *tried*

the problem still exists that development mode **only** works on localhost and does not work if
I set a hostname (in my case, I used swagger.na.sas.com which is a DNS alias for the host
I'm running this on). prod mode works with a hostname other than localhost but development mode does **not**.

please reopen and investigate
