### ISSUE TITLE
Resizing browser causes editor view state error

### ISSUE THREAD

**Issue by mjhunter** [swagger-api/swagger-editor#514]
If you collapse the preview side so that only the editor is showing and then adjust the browser size, it can be put into an error state that will prevent you from recollapsing it.

Steps to recreate:
1) Collapse the preview side
      - The border now shows that the left side is showing and will not allows the right side to be  compressed
2) Resize the window
     - The collapsed side will reappear but the state dictating which side can be collapsed will not change
3) Try to collapse the left side, but you won't be able to

Workaround:  Refresh the page to correct the state.  Just make sure all of your changes have been changed first.

**Comment by mohsen1** [comment]
This is an issue in UI Layout. I've reported it here https://github.com/angular-ui/ui-layout/issues/100
