### ISSUE TITLE
No way to start the swagger-jaxrs-server

### ISSUE THREAD

**Issue by cosbor11** [swagger-api/swagger-editor#516]
Steps to reproduce: 

1) Enter a valid swagger 2.0 json spec into the editor
2) Go to Generate Server > JaxRS
3) Download zip and unpack
4) Build the project
5) Run the `java -jar swagger-jaxrs-server-1.0.0.jar` command
* ISSUE:  The server doesn't start. Gives this message: 
````
no main manifest attribute, in swagger-jaxrs-server-1.0.0.jar
````

Also, the pom does not reference any MainClass 

Also, there is no README.md or guide to starting this server anywhere.

Ideally, I'd like to start this in a tomcat container, but it looks like it's intended to have an embedded jetty server,   How is this skeleton intended to be used?

-C

**Comment by mohsen1** [comment]
This issue was moved to swagger-api/swagger-codegen#925
