### ISSUE TITLE
Add an option to override `isProduction` flag

### ISSUE THREAD

**Issue by netei** [swagger-api/swagger-editor#518]
Hi,

I'm currently tring to add some feature to the swagger-editor. However, I have to run `npm start` every time I make some change, which makes it very slow to find out if what I did works. 

I saw that you have a `develop` script (eg `npm run develop`), which seems to watch files for changes. However, even if I run both npm start and npm run develop, if I change a file (for example `app/scripts/controllers/header.js` ) and reload the page, the changes don't seem to be in place.

Is they a way to use the non-minified files for development, or what is a good workflow to not have to wait for one minute after each build ?

**Comment by netei** [comment]
It seems that it was also due to the fact that the isProduction flag was testing that the hostname contains `localhost` (here : https://github.com/swagger-api/swagger-editor/blob/master/app/scripts/bootstrap.js#L27), but my hostname is not localhost in my case.

It would make sense to make it configurable without relying on localhost (or at least tell it in the readme, I usually don't host things on localhost directly, even for development)

**Comment by arockstar** [comment]
I would suggest to use ng-constant (npm install grunt-ng-constant) in Gruntfile.js that will create a js file with defined angular constants. Let’s configure ng constans:
```javascript
grunt.initConfig({
ngconstant: {
  options: {
    name: 'config',
    dest: '<application path>/scripts/config.js',
    wrap: '"use strict";\n\n <%= __ngModule %>'
  },
  development: {
    constants: {
      isProduction: false
    }
  },
  production: {
    constants: {
      isProduction: true
    }
  }
}
});
```


Next, we need to add relevant constant to each grunt task:
```javascript
grunt.registerTask('build', [ ... 'ngconstant:production', ... ]);
grunt.registerTask('test-dev', [ ... 'ngconstant:development', ... ]);
```
After it created module with constants (config.js) should be injected into application and we can use it as dependency. 

Here we have an area for thoughts: how to encapsulate needed information (what environment we are currently running) in easier (optimal) way, within minimum number lines of code and operations.

For raw example we can write somewhere in bootstrap.js: isProduction = isProduction || false  and remove isProduction:false in development configuration of ng-constants section.
Or we can define new constant isDevelopment to let us be more flexible in case if other environments will appear in the universe.

**Comment by mohsen1** [comment]
@arockstar that's a good solution. Please make a pull request if you have time.

**Comment by mohsen1** [comment]
Related: https://github.com/swagger-api/swagger-editor/issues/624

**Comment by DSoa** [comment]
Can someone please answer the original question about a good workflow for developing with no minification and other unneeded steps?  I ran `npm run develop` and it does:
- npm run bower-install
- npm install
- bower install

which are not needed.  Then it does a build which runs minify/uglify tasks which I don't need.

It starts up the server, but all font files fail to load.  E.g.,
http://localhost:9000/styles/WOFF/OTF/SourceCodePro-Regular.otf.woff  -> 404

I'm new to grunt and npm, so I don't know where to start to modify the build files, but it would be nice to have faster turnaround and have the fonts work.

**Comment by saharj** [comment]
Now you can use `--production` to start the server in production mode.
