### ISSUE TITLE
Add possible to use editor in multiple tabs (adding 1 option more in config object)

### ISSUE THREAD

**Issue by MrKarlsonCloud** [swagger-api/swagger-editor#5207]
### Content & configuration

Swagger/OpenAPI definition:
 ```yaml
 # your YAML here
 ```

 Swagger-Editor configuration options:
 ```js
 SwaggerEditor({
   layout: 'EditorLayout', // BasicLayout without swagger
    plugins: [BasicLayoutPlugin],
    dom_id: '#swagger-editor',
    docExpansion: 'list',
    localStorageKey: 'swagger-editor-content-UUID', // This field i want to add and use it in /plugins/local-storage/index.js
    defaultModelExpandDepth: false,
    defaultModelsExpandDepth: false,
    swagger2GeneratorUrl: 'https://generator.swagger.io/api/swagger.json',
    oas3GeneratorUrl: 'https://generator3.swagger.io/openapi.json',
    swagger2ConverterUrl: 'https://converter.swagger.io/api/convert'
 })
 ```

 ```
 ?yourQueryStringConfig
 ```

### Is your feature request related to a problem?
I want to open multiple tabs with multiple apis using same aplication.

### Describe the solution you'd like
Put in config object file like "localStorageId" and use it in /plugins/local-storage/index.js Line 2 this is version 4 of plugin
![image](https://github.com/user-attachments/assets/396c1b02-9c4d-433c-9614-ee77e2b920d5)

### Describe alternatives you've considered
Like above

**Comment by ponelat** [comment]
This is a little outside the scope of the project (to support multiple files/browser-tabs/etc). I do appreciate the need, and perhaps you'll consider a plugin for it :)
