### ISSUE TITLE
Error representation

### ISSUE THREAD

**Issue by amirceo** [swagger-api/swagger-editor#5211]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome
 - Version: IDK
 - Method of installation: IDK
 - Swagger-Editor version: IDK
 - Swagger/OpenAPI version: 2

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
# Not related
```

Swagger-Editor configuration options:
```js
SwaggerEditor({
  IDK
})
```

```
IDK
```

### Have some errors in your specification and the close the browser and reopen it the errors disapear

1. Go to Editor
2. See Errors
3. Close Browser
4. Open Browser
5. Errors Are Gone

**Comment by ponelat** [comment]
Going to close, if this issue is important could you please provide more information
