### ISSUE TITLE
Accessing next branch for AsyncAPI specification editting

### ISSUE THREAD

**Issue by thomas-reinke** [swagger-api/swagger-editor#5212]
Hoping I'm just missing something obvious.  I'm trying to use the browser version of swagger-editor in order to be able to edit AsyncAPI YAML specifications.  I have used swagger-editor for OpenAPI with no problems.

My understanding is that the "next" branch of the github repository provided this capability, so what I did was I went to github, cloned the swagger-editor repository, and then, using a command line prompt (this is all Linux),

cd swagger-editor (this is what I cloned from github)
git checkout -b next
git branch (to confirm I was on the "next" branch).

I then proceeded to create a deployable tar file by simply tarring up the entire swagger-editor directory, EXCLUDING the unnecessary .git directory tree.  Deployed the result in /var/www/html on our target development server.

But, when I visit the swagger-editor on the target server via a browser, (e.g. on a locally hosted VM, my URL is http://127.0.0.1/swagger-editor/ ) I am still only able to edit or create OpenAPI specs.   I've confirmed that there is a file that contains the "Try our new Editor" text, but this text is never rendered, and as such, I think I am still only accessing the stock OpenAPI editor capability.

I tried copying what I believe is a valid example AsyncAPI spec, from https://editor-next.swagger.io/ (the Streetlights Kafka API), and the error shown on the right hand pane simply says 

    Unable to render this definition
    The provided definition does not specify a valid version field.
    Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match openapi:3.0.n (for example, openapi: 3.0.0).

which is the same thing that happens if I simply clear the editor and enter as "asyncapi:" as the start of my specification.

What did I miss?

### Q&A (please complete the following information)
 - OS: Linux (Debian 12)
 - Browser: FireFox
 - Version: firefox-esr   115.12.0esr-1~deb12u1
 - Method of installation: git repository
 - Swagger-Editor version: github's "next" branch

**Comment by thomas-reinke** [comment]
I should add - my objective is to have a self-contained specification creation environment I can use that doesn't rely on a network connection, but which I can use locally self-contained on my laptop (with its associated guest OS.  I add this, because as I dive into the actual swagger files, there is a hint that the "new" AsyncAPI editor is only, in fact, a link to https://editor-next.swagger.io.

**Comment by thomas-reinke** [comment]
Additional addendum - I've been able to more or less do what I need by running asyncapi studio liveserver, but it seems like overkill and additional bloat for what I am looking to solve.

**Comment by ponelat** [comment]
Swagger Editor (master) has a `dist` folder that  contains the bundled files, but  Swagger Editor (next) does not, you would need to build the `dist` folder and host those  files.
Here is a link to the docs:  https://github.com/swagger-api/swagger-editor/tree/next?tab=readme-ov-file#installation (for the next version)

And yes, this will support AsyncAPI.

**Comment by thomas-reinke** [comment]
Ok...where I can put out a suggestion that the tool should be pre-built for user consumption?  At end of day - it's just a set of files that get served up to a browser...right? No server side component really involved in the editor (afaik).   

I just want the hammer for my project, but instead I'm having to deal with building the hammer.   I don't want to rent the hammer (https://editor-next.swagger.io), because I need to ensure the hammer still works 2 years from now for me, with my specs.

Here are some of the issue's I've had:

On a fully up to date latest Debian system,

1) Challenged to know if I am following the right steps on all the problems below (time and effort expended) to know who to build a "binary" usable version of the tool from source. Yes, I'm trying to use https://github.com/swagger-api/swagger-editor/tree/next?tab=readme-ov-file#setting-up  (yes that's a me problem...but one I shouldn't need to worry about)

2) The documentation says version of nodejs required is >=20.3.0. Debian 12 (latest) comes with nodejs 18.19.

3) The version of npm required is  >=9.6.7. Debian 12 comes with 9.2

4) Running "npm i" as part of the setup fails with
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: react-ace@4.4.0
npm ERR! Found: react@18.3.1
npm ERR! node_modules/react
npm ERR!   react@">=17 <19" from the root project
npm ERR!   peer react@">=18" from @cfaester/enzyme-adapter-react-18@0.8.0
npm ERR!   node_modules/@cfaester/enzyme-adapter-react-18
npm ERR!     dev @cfaester/enzyme-adapter-react-18@"^0.8.0" from the root project
npm ERR!   14 more (boron, react-copy-to-clipboard, react-debounce-input, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.13.0 || ^0.14.0 || ^15.0.1" from react-ace@4.4.0
npm ERR! node_modules/react-ace
npm ERR!   react-ace@"^4.1.6" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@15.7.0
npm ERR! node_modules/react
npm ERR!   peer react@"^0.13.0 || ^0.14.0 || ^15.0.1" from react-ace@4.4.0
npm ERR!   node_modules/react-ace
npm ERR!     react-ace@"^4.1.6" from the root project

Is swagger-editor-next too new/bleeding edge for may expectations?  The online version suggests not...
