### ISSUE TITLE
Does not recognise numbers above `1e20`: value must be a number

### ISSUE THREAD

**Issue by RobinTail** [swagger-api/swagger-editor#5249]
### Q&A (please complete the following information)
 - OS:  macOS
 - Browser: chrome
 - Version: 130
 - Method of installation: none, online
 - Swagger-Editor version: next, https://editor-next.swagger.io/
 - Swagger/OpenAPI version: 3.1

### Content & configuration

Minimum reproduction:

```yaml
openapi: 3.1.0
info:
  title: Example API
  version: 20.14.3
paths:
  /v1/serialize:
    get:
      operationId: GetV1Serialize
      responses:
        "200":
          description: GET /v1/serialize Positive response
          content:
            application/json:
              schema:
                type: object
                properties:
                  prop:
                    type: number
                    format: double
                    minimum: 1.1e3
                    maximum: 1e21
```

### Describe the bug you're encountering

It says " maximum' value must be a number ", but it is a number.

### Expected behavior

I expect it to handle the range of numbers supported by JS `Number`, which is:

```py
# -Number.MAX_VALUE
-1.7976931348623157e+308
# Number.MAX_VALUE
1.7976931348623157e+308
```

but it's failing already on `1e21`.

### Screenshots

| editor-next | editor |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/01ecab11-d153-41bc-b7c4-f01180cd8dee) | ![image](https://github.com/user-attachments/assets/b4311cb5-e39b-4aef-92c4-f2b3996f5c4c) |
| fails on `1e21`, regardless of OAS version | does not fail even with `1e100500` |

### Additional context or thoughts

- There is no such issue in https://editor.swagger.io/  (seems to be happening only in "next" editor)
- and it does not depend on `openapi` version (setting 3.0 in next editor does not fix it),
- `1e20`, works fine.

**Comment by RobinTail** [comment]
Worth to note that `1e20` seems to be the last level before switching to exponential notation

```py
$ 1e20
100000000000000000000
$ 1e21
1e+21
```

**Comment by ponelat** [comment]
Thanks @RobinTail, we can take a look. I'd be curious what sized number you needed to discover this issue :)

**Comment by RobinTail** [comment]
Thank you @ponelat 
Let's say I need to describe API endpoint that accepts a float number, so that I'd like to inform via the documentation what that number could be. Since the API is Node.js and operates JavaScript engine, the largest safe number is `Number.MAX_VALUE` which is `1.7976931348623157e+308`, and the minimum one would be `-1.7976931348623157e+308` accordingly.

**Comment by char0n** [comment]
Hi @RobinTail,

Fix has been deployed at https://editor-next.swagger.io/. Thank you for the report!
