### ISSUE TITLE
Bad url construction for examples 

### ISSUE THREAD

**Issue by danielm64** [swagger-api/swagger-editor#532]
v2.9.6
Local server

The **Open example** feature doesn't work when server not install at root URI.
My server uses an '/swagger/work/editor/' base URI, this URI is set twice in the URL of examples files as shown below:

![swaggerexamples-badurl](https://cloud.githubusercontent.com/assets/12515281/8550538/74316c8e-24d1-11e5-8a7e-a6b27464d32a.png)

**Comment by mohsen1** [comment]
What is `examplesFolder` settings? See [config docs](https://github.com/swagger-api/swagger-editor/blob/master/docs/config.md) to learn how to change it.

**Comment by danielm64** [comment]
not changed...default settings:
```
"examplesFolder": "spec-files/",
```

**Comment by mohsen1** [comment]
URL construction is happening [here](https://github.com/swagger-api/swagger-editor/blob/master/app/scripts/controllers/openexamples.js#L12-L18). Can you debug it and see why this is happening?

**Comment by danielm64** [comment]
i'll try... not a JS specialist...
How can I build the distribution without js-minification ?

**Comment by mohsen1** [comment]
You can run `grunt serve`

**Comment by mohsen1** [comment]
BTW for your own use case you can specify an absolute URL for `examplesFolder`. Something like `/editor/work/spec-files`

**Comment by danielm64** [comment]
absolute URL doesn't work... now I have my base URI  three times !

![swaggerexamples-badabsoluteurl](https://cloud.githubusercontent.com/assets/12515281/8564704/f4ddf06e-254e-11e5-928c-aa6fe0af6772.png)

(I didn't find how to debug the problem using `grunt serve`: it always starts with an empty base URI...)

**Comment by telasai1** [comment]
Hi danielm64,
change this  "examplesFolder": "spec-files/",

 to 

"examplesFolder": "../../spec-files/",

i hope it will work..

Regards
Iranna

**Comment by danielm64** [comment]
Hi Iranna,

It looks strange but... it works !
For my specific case, I set
```
"examplesFolder": "../../../spec-files/",
```

@mohsen1, I hope   that this bypass will help you to fix the bug...
