### ISSUE TITLE
"pattern" property not allowed in schema

### ISSUE THREAD

**Issue by hamx0r** [swagger-api/swagger-editor#533]
Per docs on [Schema Objects](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#schema-object), one should be able to set a `pattern` property in a schema.  However, the Swagger Editor claims `pattern` is not OneOf the valid properties.  It's possible many of the documented allowed properties may be falsely noted as invalid in the Swagger Editor. 

Here's an example of an Email Address with pattern which I expect to be valid:

     parameters:
        - description: Email Address
          in: query
          pattern: "(?i)^[A-Z0-9._%!#$%&'*+-/=?^_`{|}~()]+@[A-Z0-9]+([.-][A-Z0-9]+)*\\.[A-Z]{2,22}$"
          required: true
          type: string
          name: email

**Comment by mohsen1** [comment]
Your regex is invalid JS regex. 

```js
new RegExp("(?i)^[A-Z0-9._%!#$%&'*+-/=?^_`{|}~()]+@[A-Z0-9]+([.-][A-Z0-9]+)*\\.[A-Z]{2,22}$")
```

This code throws with: 

```
Uncaught SyntaxError: Invalid regular expression: /(?i)^[A-Z0-9._%!#$%&'*+-/=?^_`{|}~()]+@[A-Z0-9]+([.-][A-Z0-9]+)*\.[A-Z]{2,22}$/: Invalid group
```

**Comment by hamx0r** [comment]
Ah, it wasn't clear what flavor of regex was to be used, thought JS syntax seems the most obvious choice.

To future viewer:  Here's a snippet to convert from Python regex to JS.  It will be included in the Pyramid Swagger extension module at some point so that those using Colander with the Email validator or even their own pure-string regex (Python 2.4+) values will get valid Swagger specs:

```python
 m = re.match('\(\?([iLmsux]*)\)(.*)', pattern)
if m is None:
    js_re = '/' + pattern + '/'
else:
    flags = m.group(1)
    js_re = '/' + m.group(2) + '/'
    if 'i' in flags:
        js_re += 'i'
    if 'm' in flags:
        js_re += 'm'
    if 'g' in flags:
        js_re += 's'
parameter['pattern'] = js_re
```
