### ISSUE TITLE
Incorrect missing response error 

### ISSUE THREAD

**Issue by chrisdudley** [swagger-api/swagger-editor#539]
If I use 'paste json' in the online swagger editor with the below JSON then I get an error about "missing required property responses". But its there.
It validates as valid swagger so not sure what I'm doing wrong.

<pre>
{
  "swagger" : "2.0",
  "info" : {
    "version" : "1.0.0",
    "title" : "aTestableAPI"
  },
  "host" : "example.com",
  "basePath" : "/anAPI",
  "paths" : {
    "/lookup" : {
      "get" : {
        "tags" : [ ],
        "summary" : "Lookup",
        "description" : "Lookup",
        "parameters" : [ {
          "default" : "UK",
          "description" : "",
          "name" : "countryCode",
          "type" : "string",
          "required" : true,
          "in" : "query"
        } ],
        "responses" : {
          "200" : {
            "schema" : {
            },
            "description" : "",
            "examples" : {
              "application/json" : {
                "country" : "United Kingdom",
                "population" : "64100000"
              }
            }
          }
        },
        "deprecated" : false,
        "schemes" : [ "https" ],
        "security" : [ {
        } ],
        "consumes" : [ ],
        "produces" : [ "application/json" ]
      }
    }
  },
  "definitions" : {
  },
  "schemes" : [ "https" ],
  "tags" : [ ],
  "securityDefinitions" : {
    "Client ID" : {
      "description" : "",
      "in" : "header",
      "name" : "X-Client-Id",
      "type" : "apiKey"
    }
  },
  "security" : [ {
    "Client ID" : [ ]
  } ]
}
</pre>

**Comment by chrisdudley** [comment]
If I remove the examples element then the problem goes away.
But its valid swagger to have an examples element there so not sure why that would be confusing the parser to mean it could no longer find the responses element.

**Comment by chrisdudley** [comment]
This is the error shown in swagger editor:

 Swagger Error

Missing required property: responses
Jump to line 9
Details
Object
code: "OBJECT_MISSING_REQUIRED_PROPERTY"
message: "Missing required property: responses"
path: Array [3]
0: "paths"
1: "/lookup"
2: "get"
level: 900

**Comment by mohsen1** [comment]
I've seen this before. The correct steps to reproduce: 

1. Paste the JSON
2. "missing response object" error appears 
3. Add a new line in the end of YAML (or any change in YAML), the error goes away

**Comment by chrisdudley** [comment]
Any change I can make to the JSON to fix it so the error doesn't appear in the first place?

**Comment by mohsen1** [comment]
No, it's not about the JSON. See #289 and #540
