### ISSUE TITLE
Referenced arrays aren't displayed correctly in a model

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-editor#541]
_From @bandtank on July 8, 2015 23:10_

How do I get the Images key to not be displayed? I want to use the Images model in many places, but the displayed format is misleading.

![screen shot 2015-07-08 at 5 06 01 pm](https://cloud.githubusercontent.com/assets/1170415/8584434/a5db2a5a-2593-11e5-9cde-c0d20e8022a6.png)

The actual structure is as follows:

`image : { thumbnail: "...", large: "...", etc. }`

But the image above is causing external users to ask me why the object isn't returned like this:

`image : { Image: {thumbnail: "...", large: "...", etc. }}`

How do you reuse a model without displaying it like what's shown in my image? This is how my JSON file looks:

![screen shot 2015-07-08 at 5 10 08 pm](https://cloud.githubusercontent.com/assets/1170415/8584487/3a9a35a0-2594-11e5-9eb7-17703e5ab3c3.png)

_Copied from original issue: swagger-api/swagger-ui#1460_

**Comment by mohsen1** [comment]
If I understood your question correctly.

By this:

```yaml
image:
  type: array
  items: 
    $ref: '#/definitions/Image'
```
You are describing an array of `Image` objects. If you want an array of image object wrapped in a `{Image: image}` wrapper you can do as follow:

```yaml
image:
  type: array
  items: 
    type: object
    properties:
     Image:
       $ref: '#/definitions/Image'
```

**Comment by bandtank** [comment]
Here's a more precise explanation of what I'm trying to do using pictures. image2 is exactly what I want visually, but the YAML is obviously 'wrong' in that it isn't reusing the Image model. In plain words, I want to reuse the Image model, but I don't want the word 'Image' to show up in the documentation as it's shown below. 'image' is an object, not an array of objects.

In this screenshot, image is what I want in terms of code reuse:

![screen shot 2015-07-09 at 11 07 18 am](https://cloud.githubusercontent.com/assets/1170415/8601750/4476909a-262b-11e5-9c8e-061975b878de.png)

In this screenshot, image2 is what I want in terms of documentation visualization:

![screen shot 2015-07-09 at 11 07 06 am](https://cloud.githubusercontent.com/assets/1170415/8601753/4ef803e6-262b-11e5-9153-7894fdd52df9.png)

**Comment by mohsen1** [comment]
Ah I see where the confusion is coming from. The word **Image** in there is not a key, it's the title of your schema. Swagger Editor uses the key in definitions hash to add "title" to your schema. See [examples](http://azimi.me/json-schema-view/demo/demo.html) of the schema-view directive to learn more.

**Comment by bandtank** [comment]
Thanks. I understand now.

**Comment by mohsen1** [comment]
:+1:
