### ISSUE TITLE
Swagger error "Missing required property: responses" keeps needlessly appearing in http://editor.swagger.io/#/

### ISSUE THREAD

**Issue by Jatkins1995** [swagger-api/swagger-editor#543]
The Missing responses error keeps coming up even though it is properly set.  It is fixed just by putting random characters in places where it doesn't affect anything.

Example:  In the basic-auth.yaml example it starts with the error but putting in random characters in the description makes it go away.

**Comment by mohsen1** [comment]
Duplicate of #539
