### ISSUE TITLE
Live Render doesn't update preview when editing a definition

### ISSUE THREAD

**Issue by illicium** [swagger-api/swagger-editor#549]
[Demo](http://www.gfycat.com/MajesticBrilliantCats)

**Comment by dholdren** [comment]
I also have this problem.

**Comment by mohsen1** [comment]
It's a bug for sure but if you get stuck in things like this, just refresh the page...

**Comment by reginald-louis** [comment]
Samething when editing the schema of a reponse.

**Comment by mohsen1** [comment]
This might be an issue in JSON Schema View dependency
