### ISSUE TITLE
ace is not defined

### ISSUE THREAD

**Issue by mpgallage** [swagger-api/swagger-editor#550]
Hello everyone,

This could be a very basic issue.  I'm integrating swagger editor to a grails application. I included all the necessary JS files. But still I get "ace is not defined" error. I included the following JS files.

scripts.js
vendor.js
bower_components/ace-builds/src-nonconflict/*.js

Any idea why I'm still getting this error?

Thanks
Malaka

**Comment by mohsen1** [comment]
Maybe order of the script tags are not right. Ace files should come after vendor.
