### ISSUE TITLE
Setting authentication doesnt affect expanded tryoperations

### ISSUE THREAD

**Issue by chrisdudley** [swagger-api/swagger-editor#551]
If a try operation is expanded before the user clicks the 'Authenticate' button at the top to provide whatever credentials are required, then the security info is not added to the expanded try operation.
Clicking close and then reopening the try operation works and the credentials are picked up.

A possible fix would be to simply collapse all expanded try operations when the Authenticate button is pressed?

**Comment by mohsen1** [comment]
We should be able to make try operation respond to changes in the state of security definitions.

**Comment by webron** [comment]
Should no longer be an issue in 3.X.
