### ISSUE TITLE
Firefox Developer Edition: doing "save link as" on "File > Download as JSON/YAML" doesn't work

### ISSUE THREAD

**Issue by seanpkps** [swagger-api/swagger-editor#553]
This is really useful when working with imported files and saving them back into a project in source control.
It works in Chrome and Safari.

But even then, it would be nice to have a "Save as JSON/YAML..." entry that always asked where you want to save the file, even if the browser downloads everything to the same place.
Similarly, it would be great to have a keyboard shortcut that started the save as dialog at the location of the imported file.

**Comment by mohsen1** [comment]
We are using [`a[download]`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a). It's downloading a `Blob` that is having a URL generated from `window.URL.createObjectURL`. It's generated on the fly. If Firefox can't "save link as" the link it's a firefox bug.

**Comment by seanpkps** [comment]
OK, sounds fine.

**Comment by mohsen1** [comment]
Reported it here: https://bugzilla.mozilla.org/show_bug.cgi?id=1184450
