### ISSUE TITLE
Is there a generator that generates the same output as the editor's live preview?

### ISSUE THREAD

**Issue by cheapsteak** [swagger-api/swagger-editor#555]
The editor's preview looks a lot better than the output of of swagger-ui and the generated HTML client, is there a way of saving that?

**Comment by mohsen1** [comment]
You can use Swagger Editor itself. Just add a little CSS to hide top bar and editor pane and make the preview pane 100% width. Read the [configuration docs](https://github.com/swagger-api/swagger-editor/blob/master/docs/config.md)

**Comment by cheapsteak** [comment]
Thank you, still wish there was a way to have it generate a sharable HTML file that I can add to email attachments but this will do

**Comment by mohsen1** [comment]
Yes, I understand. I've made a [project](https://github.com/mohsen1/swagger-docs) to bring editor style preview for documentation. It's not done and it doesn't have try operation component.
