### ISSUE TITLE
Fix examples

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-editor#558]
Make sure all model definitions have `type: object`.

**Comment by mohsen1** [comment]
JSON Schema does not require `type: object` and it assumes all schemas are object schema by default. Is it a good to have or Swagger wants `type: object` to be specified explicitly?

**Comment by webron** [comment]
Unfortunately, JSON Schema does not assume it and the meaning of it is pretty much 'any'. If you try to validate a string against a a definition with only `properties` and no `type`, it will pass validation.
