### ISSUE TITLE
Make termsOfService clickable link if it contains a URL

### ISSUE THREAD

**Issue by chrisdudley** [swagger-api/swagger-editor#559]
Would it be possible to make any URLs into clickable &lt;a href&gt; links in the termsOfService field?

From the swagger spec's point of view that field is just a string, but could swagger editor parse the content to make it a little more viewer friendly before rendering on screen?

![image](https://cloud.githubusercontent.com/assets/7387884/8725151/9ca92e18-2bca-11e5-9479-329c9668e9d9.png)

**Comment by mohsen1** [comment]
`termsOfService` is not a markdown field. We might be able to linkify it.
