### ISSUE TITLE
Can't specify Content-Type application/vnd.api+json for examples 

### ISSUE THREAD

**Issue by cris7ian** [swagger-api/swagger-editor#560]
I'm using JSON API and my responses MUST have `application/vnd.api+json` as their Content-Type, but the Swagger Editor won't let me use it for my Example Objects.

```YAML
responses:
        # Response code
        200:
          description: Successful response
          schema:
            type: object
            $ref: "#/definitions/User"
          examples:
            application/vnd.api+json:
              - data:
                  title: hello
                  attributes:
                    full_name: John Appleseed
              - data:
                  title: hello
                  attributes:
                    full_name: Mike Appleseed
```

This yields an error even though the operation produces and consumes `application/vnd.api+json`.

```YAML
      produces:
        - application/vnd.api+json
      consumes:
        - application/vnd.api+json
```

This error is prompted:

![screenruler-2dd217a8-e5e9-4a30-b6bb-9b56b8f7a859](https://cloud.githubusercontent.com/assets/2112370/8727775/d67b026c-2be1-11e5-9d47-440251ea103a.png)

Also the server generated code won't add these examples to the operation.

**Comment by webron** [comment]
This is due to a bug with the JSON Schema. I've opened https://github.com/swagger-api/swagger-spec/issues/414 for it.

**Comment by danielm64** [comment]
You'll will then face a render problem on swagger-ui (if you use...) as only 'application/json' examples are rendered...
I shoud have open a swagger-ui issue but didn't take time to... in my case, we have 'application/hal+json' production, I modified ui to support this content type and the JSON stringification for good rendering.

**Comment by mohsen1** [comment]
No longer can reproduce as of bd9e444
