### ISSUE TITLE
"No enum match for: double" error

### ISSUE THREAD

**Issue by HuangShaoTian** [swagger-api/swagger-editor#562]
hi, I define a property for "type": "double", run at Swagger UI all is okay, but the Swagger Editor tips an error that "No enum match for: double", is it a bug?

![code](https://cloud.githubusercontent.com/assets/4961965/8743295/0206f4b8-2ca0-11e5-9e93-23f07edc5c3a.jpg)

![swagger_ui](https://cloud.githubusercontent.com/assets/4961965/8743306/18758976-2ca0-11e5-947f-c91d2c734d24.png)

![editor_error](https://cloud.githubusercontent.com/assets/4961965/8743309/1d8aab9e-2ca0-11e5-8d77-3aa9059271a1.jpg)

**Comment by mohsen1** [comment]
Your spec is invalid. `"type": "double"` is not valid JSON Scehma type.

**Comment by webron** [comment]
You need to use `type: number` and `format: double` for it.
