### ISSUE TITLE
Remove imagemin from build process 

### ISSUE THREAD

**Issue by d-smith** [swagger-api/swagger-editor#564]
The swagger editor cannot be build on machines that have an HTTP proxy between them and the internet (commit 752d4eb6b2e720f7f3ff72c79e32c8fe8b568082)

Before attempting to build swagger I had set http proxy environment variables (http_proxy, https_proxy, HTTP_PROXY, HTTPS_PROXY), set proxy settings via npm config proxy and https-proxy (and the registry too), plus modified .bowerrc to include proxy information.

Even with all the set, the build fails - see the build output

According to some analysis by @jbarrus it appears to be related to this issue

To work around this (also as per @jbarrus), comment out line 13 in grunt/concurrent.js -- this will enable the build to complete successfully and the swagger editor to be served up.

<pre>
'use strict';

module.exports = {
  server: [
    'copy:styles'
  ],
  test: [
    'copy:styles',
  ],
  dist: [
    'copy:ace',
    'copy:styles',
//    'imagemin',
    'svgmin'
  ]
};
</pre>

**Comment by mohsen1** [comment]
`imagemin` has been source of many issues. We don't have a lot of images in this project. Maybe I remove ti altogether...
