### ISSUE TITLE
Copy Ace mode-json file over dist.

### ISSUE THREAD

**Issue by op1ekun** [swagger-api/swagger-editor#565]
I haven't gotten so frustrated for a long time...

Sometimes (it's about 50/50) it doesn't let me edit the file contents. It doesn't matter if I create a new one, import a JSON file (I used json with petstore example). The worse is it happens after you start typing. I'm just starting with swagger and DEMO seems like a right tool to see what I am actually doing. 

There is no indication anywhere that the content is locked, and the website is still responsive I can scroll and click on the generated content on the left side.

I'm using `Chrome` on `Windows Server 2012 R2 Standard 64-bit`.
Chrome version is `43.0.2357.134 m`.

**Comment by chrisdudley** [comment]
I've seen the same, but only in chrome.
It always works in FF.
Chrome debugger shows this error on editor.swagger.io:

Remote Address:185.31.19.133:80
Request URL:http://editor.swagger.io/bower_components/ace-builds/src-noconflict/mode-json.js
Request Method:GET
Status Code:404 Not Found

Which is likely not helping, and might then be causing the knock on effects meaning you can't actually edit content.

**Comment by op1ekun** [comment]
:+1: 

The same here. My bad I didn't check the console.

**Comment by mohsen1** [comment]
Can find steps to reproduce? Without that I don't what to fix.

**Comment by chrisdudley** [comment]
In my case its simple.
Open chrome browser, go to http://editor.swagger.io.
Try and type in the editor panel - it will let you click, but if you bring up the debug tools you'll see you get an exception as soon as you hit a key on the keyboard.
Can't really tell you where since its compiled JS.

**Comment by mohsen1** [comment]
Not happening to me. On Firefox or Chrome. I can type in with no errors in console.

**Comment by chrisdudley** [comment]
Do you get the 404 for the mode_json.js file ?

**Comment by mohsen1** [comment]
Ace's JSON mode module is [here](http://localhost:9000/bower_components/ace-builds/src-noconflict/mode-json.js) and editor had no problem loading it. Try changing the mode to JSON in editor settings. 

Can you screen grab your flow?

**Comment by chrisdudley** [comment]
setting editor mode to yaml means things work and I can type in the editor window.
If i set the mode to JSON (which seems to be the default) then I can't.

![image](https://cloud.githubusercontent.com/assets/7387884/8810366/86772d1e-2fe6-11e5-9c1f-0899ec48a3b4.png)

**Comment by mohsen1** [comment]
I can assume it's GitHub pages not serving the script "sometimes"

**Comment by chrisdudley** [comment]
Seems fairly consistent to me - if I change any browser to use mode: json then I get the 404.
The reason I was seeing it straight away in chrome was that it was defaulting to mode: json.
FF for some reason was defaulting to mode: yaml and so it didnt try to load that file and hence no 404.
If I force it to mode: json then I get the 404.

As yet I can't get it to successfully load that file anywhere:
http://editor.swagger.io/bower_components/ace-builds/src-noconflict/mode-json.js is always a 404.

**Comment by mohsen1** [comment]
I see... issue is [here](https://github.com/swagger-api/swagger-editor/blob/master/grunt/copy.js#L54)

We need to include json mode there also since editor can work in json mode too.
