### ISSUE TITLE
validation error with parameters (data does not match oneof...)

### ISSUE THREAD

**Issue by bandtank** [swagger-api/swagger-editor#567]
I believe I'm having a problem similar to [this](http://stackoverflow.com/questions/30248604/validation-error-data-does-not-match-any-schemas-from-oneof) stackoverflow question, but I can't figure out how to resolve it. The documentation says you only have to use schema if the parameter type is body, which is the only thing I know to try and it didn't seem to work.

Here's my code:

![screen_shot_2015-07-22_at_10_29_13_am](https://cloud.githubusercontent.com/assets/1170415/8831276/86528874-305e-11e5-890d-e32e73571807.png)

Any help would be greatly appreciated.

**Comment by mohsen1** [comment]
I can't tell what's the error from your screenshot. Can you make a minimal Swagger with those parameter and paste it here? 

If you open error details you might get some insights for what's going on exactly.

**Comment by webron** [comment]
There's no `readOnly` property for parameters.

**Comment by bandtank** [comment]
That was an awfully premature close considering it didn't even fix the problem. The problem was the order of the parameters, which isn't made clear in the documentation.

        - in: query
          name: interaction_type
          description: ''
          required: false
          type: string
          enum:
            - ''
            - members_interact
            - announce_only
            - administrative
          default: ''
        - in: query
          name: status
          description: ''
          required: false
          type: string
          enum:
            - participant
            - member
            - leader
          default: participant

That works because default is after enum.

**Comment by mohsen1** [comment]
order of properties shouldn't matter. It's a hash.

**Comment by bandtank** [comment]
I don't know why it wasn't working before, but now the order doesn't seem to matter like you said. I guess I don't know which change fixed it, but it works, so that's good I guess.

**Comment by bandtank** [comment]
Thanks for the help. Forgot that part...
