### ISSUE TITLE
ISO8601 full-date not accepted

### ISSUE THREAD

**Issue by bandtank** [swagger-api/swagger-editor#569]
According to the [spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md) Data Types section, string:date is [defined](http://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#anchor14) as follows: 
`full-date = date-fullyear "-" date-month "-" date-mday`

Why, then, does this not work?
```
- name: relative_to
  in: query
  description: ''
  required: false
  type: string
  format: date
  default: 2015-07-11
```
```
✖ Swagger Error
Not a valid date string: Fri Jul 10 2015 18:00:00 GMT-0600 (MDT)
Jump to line 180
Details
 Object
code:  "INVALID_TYPE"
message:  "Not a valid date string: Fri Jul 10 2015 18:00:00 GMT-0600 (MDT)"
 path: Array [6]
0:  "paths"
1:  "/groups/{id}/meetings"
2:  "get"
3:  "parameters"
4:  "1"
5:  "default"
level: 900
```

Also, why does the error message show the date as July 10th instead of July 11th, which is what I specified? I'm guessing it has something to do with timezones.

**Comment by mohsen1** [comment]
From JSON Schema [§5.23](https://tools.ietf.org/html/draft-zyp-json-schema-03#section-5.23):

```
date-time  This SHOULD be a date in ISO 8601 format of YYYY-MM-
      DDThh:mm:ssZ in UTC time.  This is the recommended form of date/
      timestamp.

   date  This SHOULD be a date in the format of YYYY-MM-DD.  It is
      recommended that you use the "date-time" format instead of "date"
      unless you need to transfer only the date part.

   time  This SHOULD be a time in the format of hh:mm:ss.  It is
      recommended that you use the "date-time" format instead of "time"
      unless you need to transfer only the time part.
```

You probably want to use `date-time` that is in ISO 8601

**Comment by bandtank** [comment]
But date should work based on the spec and that's the type I actually need. It seems like swagger-editor is falsely flagging this as an error based on the spec:

![screen shot 2015-07-24 at 10 07 32 am](https://cloud.githubusercontent.com/assets/1170415/8879033/efd2872a-31eb-11e5-8a26-b3a9c34e7562.png)

And the associated definition of full-date:

![screen shot 2015-07-24 at 10 08 58 am](https://cloud.githubusercontent.com/assets/1170415/8879059/1d4274e0-31ec-11e5-9683-fe282db5239b.png)

**Comment by mohsen1** [comment]
I don't even get the error with your parameter. How did you get the error?

```yaml
---
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /:
    get:
      parameters:
      - name: relative_to
        in: query
        description: ''
        required: false
        type: string
        format: date
        default: 2015-07-11
      responses:
        200:
          description: OK

```

**Comment by bandtank** [comment]
I copied your code verbatim and I got the following error:

![screen shot 2015-07-24 at 10 33 42 am](https://cloud.githubusercontent.com/assets/1170415/8879578/83d06fd4-31ef-11e5-9c7c-789ec26d2044.png)

I'm using Swagger Editor 2.9.6 as part of [swagger_engine](https://github.com/batdevis/swagger_engine) if that helps.

**Comment by mohsen1** [comment]
Ah I see. Schema was updated since 2.9.6 but we haven't published [2.9.7](https://github.com/swagger-api/swagger-editor/milestones/2.9.7) yet.

**Comment by trupti18** [comment]
IS there a solution for this. The latest editor has the same problem.

**Comment by Echeverrya** [comment]
I'm facing the same issue. Is it fixed?

**Comment by shockey** [comment]
I'm going to lock this thread since it applies to a very old version of Swagger Editor.

If you're still experiencing a problem, please open a new issue. Thanks!
