### ISSUE TITLE
Cannot edit swagger on new file on Chrome 

### ISSUE THREAD

**Issue by Steph0** [swagger-api/swagger-editor#570]
Windows 7 entreprise
Chrome : Version 43.0.2357.134 m
url : http://editor.swagger.io/#/

Issue : 
- When I create a new file
- I just try to type something, nothing happen (cannot type, delete or do anything else on text)
- This issue does not happen on Firefox latest version

Error in console (note: code is compressed but not uglifyed) : 
```
Uncaught TypeError: c.getMode(...).transformAction is not a function
remove @ 98f65023.vendor.js:18
b.commands.exec @ 98f65023.vendor.js:17
(anonymous function) @ 98f65023.vendor.js:16
d._emit.d._dispatchEvent @ 98f65023.vendor.js:12
exec @ 98f65023.vendor.js:16
$callKeyboardHandlers @ 98f65023.vendor.js:13
onCommandKey @ 98f65023.vendor.js:13
onCommandKey @ 98f65023.vendor.js:17
d @ 98f65023.vendor.js:12
(anonymous function) @ 98f65023.vendor.js:12
```

**Comment by mohsen1** [comment]
Duplicate of #565

**Comment by mohsen1** [comment]
Fixed by 82a26a6

**Comment by sram54** [comment]
I am unable to edit my Swagger API. I get a message on top right hand corner - Read Only. How do I enable editing?

**Comment by webron** [comment]
@sram54 which version of swagger-editor do you use?

**Comment by joanlofe** [comment]
Only for reference, for those who find this bug, editor is working again if you set Mode: Yaml in Preferences --> Editor settings
