### ISSUE TITLE
Throws if response.description is undefined

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-editor#574]
Try this Swagger:
```yaml
swagger: '2.0'
info:
  version: 0.0.0  
  title: Simple API
paths:  
  /:
    get:
      responses:
        '200':
          # description: OK

```

**Comment by webron** [comment]
wat

**Comment by mohsen1** [comment]
Yes @webron we have to worry about invalid specs in the editor! Editor shouldn't throw even spec is invalid. 

See thrown errors in the browser console.

**Comment by webron** [comment]
I don't see it, but I trust you. I thought you meant that's what's displayed to the user.
