### ISSUE TITLE
using in:body required schema parameters "Data does not match any schemas from 'oneOf'"

### ISSUE THREAD

**Issue by astrodsg** [swagger-api/swagger-editor#577]
I have an endpoint which takes body parameters. I specify a schema for the parameters. Parts of the schema are required, others are not. The problem occurs when I add a "required: true" to any of the body parameters (as shown in the figure)

<img width="1431" alt="screen shot 2015-08-03 at 12 19 03 am" src="https://cloud.githubusercontent.com/assets/4073779/9031811/4a731a88-3975-11e5-8562-b33c64628465.png">

If I remove the "required: true" the error disappears. Not sure why.

**Comment by chrisdudley** [comment]
Add an extra section listing the required properties rather than adding 'required: true' to them individually.
E.g.
<pre>
type: object
required:
- name
properties:
  name:
    type: string
  address:
    $ref: '#/definitions/Address'
  age:
    type: integer
    format: int32
    minimum: 0
</pre>

**Comment by webron** [comment]
@astrodsg - to add to @chrisdudley's comment, what you're adding there is not multiple body parameters but a single body parameter with a model definition. The way required properties are described in models is different than how they are required parameters are defined, and works as @chrisdudley mentioned.

**Comment by astrodsg** [comment]
Thanks! This was not clear from the [specification](http://swagger.io/specification/), probably would be worthwhile to add a description or at least an example.
