### ISSUE TITLE
Swagger Editor Master Issue

### ISSUE THREAD

**Issue by GuptaAmit311** [swagger-api/swagger-editor#582]
What's the difference between swagger Editor and Swagger Editor master package. Actually git clone command is not working on my company’s laptop (may be due to proxy setting). And swagger editor master which I downloaded from gitHub is giving errors with npm start.

**Comment by mohsen1** [comment]
Latest official release is [2.9.6](https://github.com/swagger-api/swagger-editor/releases/tag/v2.9.6). Anything in master is work in progress. You can `git checkout v2.9.6` to go to latest release or download actual compiled version from releases page.

**Comment by GuptaAmit311** [comment]
Thanks for reply. I downloaded swagger editor. But I still got error with npm start.  


C:\Tools\swagger-editor-2.9.6\swagger-editor-2.9.6> npm start

> swagger-editor-src@2.9.6 prestart C:\Tools\swagger-editor-2.9.6\swagger-editor-2.9.6
> npm run build


> swagger-editor-src@2.9.6 prebuild C:\Tools\swagger-editor-2.9.6\swagger-editor-2.9.6
> npm run bower-install


> swagger-editor-src@2.9.6 prebower-install C:\Tools\swagger-editor-2.9.6\swagger-editor-2.9.6
> npm install

npm WARN package.json swagger-editor-src@2.9.6 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Tools\\\\node.exe" "C:\\Tools\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo

npm ERR! network getaddrinfo ENOTFOUND registry.npmjs.org
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Tools\swagger-editor-2.9.6\swagger-editor-2.9.6\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Tools\\\\node.exe" "C:\\Tools\\node_modules\\npm\\bin\\npm-cli.js" "run" "bower-install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! swagger-editor-src@2.9.6 prebower-install: `npm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swagger-editor-src@2.9.6 prebower-install script 'npm install'.
npm ERR! This is most likely a problem with the swagger-editor-src package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install
npm ERR! You can get their info via:
npm ERR!     npm owner ls swagger-editor-src
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Tools\swagger-editor-2.9.6\swagger-editor-2.9.6\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Tools\\\\node.exe" "C:\\Tools\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! swagger-editor-src@2.9.6 prebuild: `npm run bower-install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swagger-editor-src@2.9.6 prebuild script 'npm run bower-install'.
npm ERR! This is most likely a problem with the swagger-editor-src package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run bower-install
npm ERR! You can get their info via:
npm ERR!     npm owner ls swagger-editor-src
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Tools\swagger-editor-2.9.6\swagger-editor-2.9.6\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Tools\\\\node.exe" "C:\\Tools\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! swagger-editor-src@2.9.6 prestart: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swagger-editor-src@2.9.6 prestart script 'npm run build'.
npm ERR! This is most likely a problem with the swagger-editor-src package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls swagger-editor-src
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Tools\swagger-editor-2.9.6\swagger-editor-2.9.6\npm-debug.log


For which software, it's showing proxy error, I don'get it. Can I do it manually ?

**Comment by GuptaAmit311** [comment]
Hi All

Can swagger editor be added into Java server (like JBOSS). My web application is working on JBoss. Can  I integrate swagger editor into it. 

Thanks!

**Comment by mohsen1** [comment]
The dist folder is simply a bunch of HTML/JS/CSS files (static web). You can server however you want.
