### ISSUE TITLE
[bug] Editor can't handle large integers

### ISSUE THREAD

**Issue by zerkei** [swagger-api/swagger-editor#585]
The editor is unable to handle a large integer, which is causes problems for us.
When you pass in some integer parameter that is large, like 708919584551129326, it will send the incorrect integer to our backend.

**Comment by mohsen1** [comment]
That's JSON number limitation. 

```
JSON.stringify({n: 708919584551129326})
=> "{"n":708919584551129300}"
```

**Comment by zerkei** [comment]
Well, looks like we're just going to use strings then.

Thanks!

**Comment by mohsen1** [comment]
:+1:
