### ISSUE TITLE
Setting security doesnt work in IE11 with latest master

### ISSUE THREAD

**Issue by chrisdudley** [swagger-api/swagger-editor#586]
Using latest git master code setting apiKey security credentials for an API (e.g. the example security.yaml) does not work. There will be no green tick for the credentials and they don't get set correctly in the session so aren't then picked up for try operations.
It works fine on http://swagger.editor.io so 2.9.6 seems to be fine.

I am just guessing here but the issue seems to be due to $sessionStorage being undefined.
It works fine in FF and Chrome, just IE that has an issue (in my case IE11 not tried other versions).
I wonder if a change to something like ngStorage has caused it?

**Comment by mohsen1** [comment]
Maybe it's ngStorage or updating the Angular to 1.4 did this.

Possibly related to this https://github.com/gsklee/ngStorage/issues/119

**Comment by webron** [comment]
This should no longer be an issue in 3.X.
