### ISSUE TITLE
Swagger editor accepts invalid swagger.json, empty parameter in parameter array

### ISSUE THREAD

**Issue by dgarry01** [swagger-api/swagger-editor#587]
Hi,

Swagger editor allows you to load invalid swagger containing an empty parameter in a parameter array for a swagger operation e.g. 

```
    "parameters": [
    {}
    ],
```

This is not allowed by swagger UI.

**Comment by mohsen1** [comment]
```yaml
---
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /:
    get:
      parameters: [{}]
      responses:
        200:
          description: OK
```
@webron should this be invalid?

**Comment by webron** [comment]
Yeah. 
```yaml
  parameters: []
```
is fine. However, having an empty object in it is not a valid parameter structure, which should fail. Your snippet will not pass schema validation.
