### ISSUE TITLE
"useYamlBackend" option is PUTting files as application/json

### ISSUE THREAD

**Issue by mrgamer** [swagger-api/swagger-editor#592]
This issue creates errors in simple body parsers as [expressjs/body-parser](https://github.com/expressjs/body-parser)

The middleware tries to decode the json, but throws an error and the PUT operation fails.
Valid mimetype could be a simpler `text/plain;charset=UTF-8`

**Comment by mohsen1** [comment]
[here](https://github.com/swagger-api/swagger-editor/blob/master/app/scripts/services/backend.js#L36) you can use `defaults.useYamlBackend` to add `Content-Type` header to the operation based on YAML or JSON backend. Pretty much like [here](https://github.com/swagger-api/swagger-editor/blob/master/app/scripts/services/backend.js#L86)
