### ISSUE TITLE
unable to print full page

### ISSUE THREAD

**Issue by brightbluerock** [swagger-api/swagger-editor#594]
Hi,

http://editor.swagger.io/#/ is wonderful.

i have entered my REST api YAML which is multipage long. When i click on print to PRINTER or to PDF it is just printing one page, the remaining pages are not printed at all !!

if you can get this print work OR tell me is there a way i can input this YAML elsewhere on your site and export this to PDF or DOC will be helpful.

thanks.

**Comment by mohsen1** [comment]
Hi,

In [print stylesheet](https://github.com/swagger-api/swagger-editor/blob/master/app/styles/print.less) we do all the print specific business. It should hide the text editor and make the preview full-screen. It's a bug that it doesn't do it at the moment. Please open a pull request if you want this fixed immediately.

**Comment by mohsen1** [comment]
I guess it's because of extra `.preview-mode` class [here](https://github.com/swagger-api/swagger-editor/blob/master/app/styles/print.less#L18)

**Comment by brightbluerock** [comment]
Hi Mohsen,

thanks for your quick response. I am using http://editor.swagger.io/#/ online. So can you please push the fix to your server? so that i can put my YAML and try to print again at this url - http://editor.swagger.io/#/

Thanks

**Comment by mohsen1** [comment]
If you need it immediately please issue a pull request. I'll merge and publish
