### ISSUE TITLE
Errors for installing on mac, permission denied, bower-github.yml

### ISSUE THREAD

**Issue by mewren** [swagger-api/swagger-editor#595]
We got errors when installing on iOS mac 10.10

Error: EACCES, permission denied '/Users/<username>/.config/configstore/bower-github.yml'
You don't have access to this file.

- we had to manually chmod the file and then it got past this

**Comment by mohsen1** [comment]
That was an issue on your system. It has nothing to do with Swagger Editor

**Comment by mewren** [comment]
Everyone on my team who installs it gets this error.  Most of us have not installed bower before

**Comment by mohsen1** [comment]
It's permissions of files outside of Swagger Editor folder. I don't know what happened in your system. I can't reproduce it in my Mac.

**Comment by mewren** [comment]
Ok.  For others reading this, just type the following (with your <username>)

sudo chmod 644  /Users/<username>/.config/configstore/bower-github.yml

**Comment by DesignByOnyx** [comment]
This same problem is happening for me. Even after I change permissions, `bower install` will work on its own but fails during and after running `npm start` - the permissions get reverted:

```
npm start
# failure on 'bower install' - permission denied for ~/.config/configstore/bower-github.jso

sudo chown -R myusername ~/.config
bower install
# success

npm start
# failure on 'bower install' - permission denied for ~/.config/configstore/bower-github.jso

bower install
# failure - permission denied for ~/.config/configstore/bower-github.jso
```
