### ISSUE TITLE
Uglify.js != uglifyjs

### ISSUE THREAD

**Issue by mewren** [swagger-api/swagger-editor#596]
Got this error on install on mac iOS 10.10

Running "useminPrepare:html" (useminPrepare) task
Warning: Cannot find module '/Users/<username>/swagger-editor/node_modules/grunt-usemin/lib/config/uglifyjs' Use --force to continue. 

- we cleaned (see https://github.com/swagger-api/swagger-editor/issues/411 )
- then we did a git checkout -b newbranch d54fd7417cfc6abad2a7645a581e3482f322c6ea   (since that version from March was working) and then it worked

**Comment by mohsen1** [comment]
Yea, it was a [bug](https://github.com/yeoman/grunt-usemin/issues/591). It's fixed now

**Comment by mewren** [comment]
thanks
