### ISSUE TITLE
Editor cannot preview composed schemas

### ISSUE THREAD

**Issue by emrehan** [swagger-api/swagger-editor#600]
Hello,

We've the following schema:
```yaml
  ItemidsResponse:
    type: object
    properties:
      count:
        type: integer
      itemids:
        type: array
        items:
          type: string
  RecommendItemsResponse:
    type: object
    properties:
      userids:
        type: array
        items:
          type: string
      recommendations:
        $ref: '#/definitions/ItemidsResponse'
```

However, the editor cannot preview the structure:
<img width="495" alt="screen shot 2015-08-24 at 10 25 26" src="https://cloud.githubusercontent.com/assets/2770895/9434750/8b85506e-4a4a-11e5-9c49-18bc3125aa1a.png">

**Comment by mohsen1** [comment]
Works for me 
<img width="422" alt="screen shot 2015-08-24 at 12 29 19 am" src="https://cloud.githubusercontent.com/assets/543633/9434812/350c9efc-49f7-11e5-9f4f-334ae98c0446.png">

Did it happen during the compose time?

**Comment by emrehan** [comment]
Well, it was like this for hours, not only for this example, but for other schema as well. Until I cut everything and paste it back. 

Shall we close the issue?

**Comment by mohsen1** [comment]
I've seen errors like this before. Happens when typing in the spec. I don't have exact steps to reproduce so we can use that to debug and fix it. If you can come up with exact steps to reproduce this issue please comment below otherwise we can't fix it.

**Comment by emrehan** [comment]
I don't know how to reproduce the issue neither. Thanks a lot!
