### ISSUE TITLE
Under Items is not taking more than one property

### ISSUE THREAD

**Issue by anilnandigam** [swagger-api/swagger-editor#603]
```json
{
	"swagger": "2.0",
	"info": {
		"version": "0.0.0",
		"title": "My bug repro API"
	},
	"paths": {
		"/persons": {
			"get": {
				"description": "Gets `Person` objects.\nOptional query param of **size** determines\nsize of returned array\n",
				"parameters": [],
				"responses": {
					"200": {
						"description": "Successful response",
						"schema": {
							"title": "ArrayOfPersons",
							"type": "array",
							"items": {
								"geoCodeID": {
									"type": "object",
									"properties": {
										"@referenceLayer": {
											"type": "string"
										},
										"@usageContext": {
											"type": "string"
										}
									}
								},
								"Person": {
									"type": "object",
									"properties": {
										"name": {
											"type": "string"
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
}
```

**Comment by webron** [comment]
Swagger doesn't support multiple types for `items` (or `type` for that matter).

**Comment by Darshan-shivashankar** [comment]
@webron wanted to follow up on this a little further. We have model's where we have nested array's.

Can you please guide us on how to define models in swagger where we need to support multiple types under items. We have many use-cases in our enterprise model. 

While also reading we see that the underlying JSON Schema supports this feature but not swagger 2.0.

We have been struggling for past few weeks to get a solution around this. Any guidance would be welcome and it will un-block us to automate our process of creating Swagger 2.0.

Please find some details i pasted here http://stackoverflow.com/questions/32256991/can-i-define-nested-array-objects-in-swagger-2-0?noredirect=1#comment52404417_32256991

**Comment by mohsen1** [comment]
> how to define models in swagger

Swagger uses a subset of JSON Schema [with a little difference](http://stackoverflow.com/a/31780480/650722)

**Comment by Darshan-shivashankar** [comment]
In that case do you suggest the only way we can achieve this is by having to go with use of $ref . 

Is there any frameworks or libraries that we can use to create $ref schema ? Currently we are using some Swagger-Core libraries to generate the swagger 2.0 spec. Any reference to some libraries or frameworks to create $ref schema would be helpful.

The good part is we were able to create nested inline models when all the elements were of type object. We hit the road block when we encountered nested array model.

**Comment by webron** [comment]
@Darshan-shivashankar - The use case presented in SO and the use case presented here are different. What you wanted to do in SO is doable, what you want to do here isn't. There's no workaround for it, it's simply not supported.

**Comment by dolmen** [comment]
If the `geoCodeID` is always at position 0 of the array and the `Person` is always at position 1 in the array, this could work according to the JSON schema of the specification (but I can't tell about support by tools: the Swagger Editor doesn't seem to be able to render that properly):

```
{
    "swagger": "2.0",
    "info": {
        "version": "0.0.0",
        "title": "My bug repro API"
    },
    "paths": {
        "/persons": {
            "get": {
                "description": "Gets `Person` objects.\nOptional query param of **size** determines\nsize of returned array\n",
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "title": "ArrayOfPersons",
                            "type": "array",
                            "items": [
                                {
                                    "description": "geoCodeID",
                                    "type": "object",
                                    "properties": {
                                        "@referenceLayer": {
                                            "type": "string"
                                        },
                                        "@usageContext": {
                                            "type": "string"
                                        }
                                    }
                                },
                                {
                                    "type": "object",
                                    "description": "Person",
                                    "properties": {
                                        "name": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    }
}
```
