### ISSUE TITLE
Absolute references don't work? 

### ISSUE THREAD

**Issue by Darshan-shivashankar** [swagger-api/swagger-editor#606]
We see following error while we load the below Swagger file.

```
Swagger Error
Reference could not be resolved: http://coreapiteam-test.apigee.net/v1/swagger/user.json
Jump to line 18
Details
 Object
code:  "UNRESOLVABLE_REFERENCE"
message:  "Reference could not be resolved: http://coreapiteam-test.apigee.net/v1/swagger/user.json"
 path: Array [8]
 err: Error
crossDomain: true
level: 900
```
```json
{
  "swagger": "2.0",
  "info": {
    "version": "0.0.0",
    "title": "My bug repro API"
  },
  "paths": {
    "/persons": {
      "get": {
        "description": "Gets Person objects",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response",
            "schema": {
              "title": "ArrayOfPersons",
              "type": "array",
              "items": {
                "$ref": "http://coreapiteam-test.apigee.net/v1/swagger/user.json"
              }
            }
          }
        }
      }
    }
  }
} 
```

**Comment by mohsen1** [comment]
is `http://coreapiteam-test.apigee.net` capable of receiving CORS calls from `swagger.io`?

**Comment by Darshan-shivashankar** [comment]
http://coreapiteam-test.apigee.net is proxy configured in apigee and yes i can definitely define CORS through inbuilt policy that apigee supports.

But i tried "$ref": "http://crossorigin.me/http://coreapiteam-test.apigee.net/v1/swagger/user.json#/Person" 

Where i used http://crossorigin.me as mentioned by @webron . This works in Swagger UI but not in swagger editor.

I don't see the CORS issue with this option now but do see one issue.


![image](https://cloud.githubusercontent.com/assets/1955708/9529817/4141d7c0-4cb1-11e5-9880-68692c56b224.png)

I don't see Person object in there. Same with Swagger UI.

Under Model schema 

![image](https://cloud.githubusercontent.com/assets/1955708/9530119/c3ab46f0-4cb2-11e5-983f-41c20b36e71c.png)

**Comment by mohsen1** [comment]
From what I see at your user.json file it seems that you're wrapping the schema in two objects which makes the schema invalid. You Person schema should probably be like this:

```json
{
      "type": "object",
      "title": "Person",
      "properties": {
        "name": {
          "type": "string"
        }
 }
```

**Comment by Darshan-shivashankar** [comment]
@mohsen1 Even after this change to the Person schema i see the same issue where i don't see Person Object.

**Comment by mohsen1** [comment]
Your JSON is invalid. You're missing a `}`

**Comment by Darshan-shivashankar** [comment]
Thanks. One last thing on this issue ,what should be the $ref in this case now ?

"$ref": "http://crossorigin.me/http://coreapiteam-test.apigee.net/v1/swagger/user.json#??

**Comment by mohsen1** [comment]
No need for a fragment here.

**Comment by Darshan-shivashankar** [comment]
@mohsen1  But when i use this "$ref": "http://crossorigin.me/http://coreapiteam-test.apigee.net/v1/swagger/user.json" it throws me anSwagger validation error.

![image](https://cloud.githubusercontent.com/assets/1955708/9531409/aa808cfa-4cba-11e5-9b60-84f4f8cec2a0.png)

**Comment by mohsen1** [comment]
Works for me. What version of editor you're using?
![screen shot 2015-08-27 at 12 57 25 pm](https://cloud.githubusercontent.com/assets/543633/9531544/39c30a5a-4cbb-11e5-9e5f-4d01b8e20349.png)

**Comment by Darshan-shivashankar** [comment]
I am using the online Swagger editor http://editor.swagger.io/#/

Also when i tried the same on Swagger UI which is deployed local is also throwing the below in model and model schema 

![image](https://cloud.githubusercontent.com/assets/1955708/9531636/d48d370e-4cbb-11e5-9476-c94cf2acdc2e.png)

![image](https://cloud.githubusercontent.com/assets/1955708/9531650/e9d736fa-4cbb-11e5-9540-2620d3a459e1.png)

**Comment by mohsen1** [comment]
I don't know about Swagger UI. Open an issue in it's own repo. For the editor please refresh the page and see if it's still having this issue

**Comment by Darshan-shivashankar** [comment]
@mohsen1  Sure. I will open an issue under Swagger UI.

But we still see issue in swagger editor.

{
	"swagger": "2.0",
	"info": {
		"version": "0.0.0",
		"title": "My bug repro API"
	},
	"paths": {
		"/persons": {
			"get": {
				"description": "Gets Person objects",
				"parameters": [],
				"responses": {
					"200": {
						"description": "Successful response",
						"schema": {
							"title": "ArrayOfPersons",
							"type": "array",
							"items": {
								"$ref": "http://crossorigin.me/http://coreapiteam-test.apigee.net/v1/swagger/user.json"
								  
							}
						}
					}
				}
			}
		}
	}
}

**Comment by mohsen1** [comment]
That is working on my machine!

**Comment by Darshan-shivashankar** [comment]
It worked when i tried in a incognito mode :-) Strange though !!!
