### ISSUE TITLE
Code Generator Error - Server Generation

### ISSUE THREAD

**Issue by nilsawesome** [swagger-api/swagger-editor#607]
I am working with the online swagger editor for some weeks now. I wrote a swagger API definition, generated a JAX-RS server and got it running with Wildfly and Eclipse. Everything worked well.

Yesterday i wrote a new definition and got the following error, when trying to generate the JAX-RS server:

![codegeneratorerror](https://cloud.githubusercontent.com/assets/5708742/9520422/6d5024aa-4cc7-11e5-9681-0f94add59b28.PNG)

Server generation only works with the default examples! My old definitions, which worked previously, aren't working anymore :( . I tried the local version of the editor, but got the same error.

Hopefully this is enough information. My boss doesn't want me to provide our source code.

Thanks in advance
Nils

PS:
I already found issue https://github.com/swagger-api/swagger-editor/issues/376, but I never used "default". I tried commenting the last line, but that didn't help.

**Comment by webron** [comment]
I'm afraid we can't do much without seeing the definition itself.

**Comment by nilsawesome** [comment]
Thanks for your reply, I'm extracting a short version from our code right now and will post it soon :)

**Comment by webron** [comment]
Great, thanks.

**Comment by nilsawesome** [comment]
This is a short version of our code. It produces the same error, when trying to generate a JAX-RS server:

swagger: "2.0"
info:
  description:
    Test description
  version: "1.0.0"
  title: Test title
  contact:
    name: Mr. X
host: 134.130.234.19:8080
basePath: /Cloud/rest
schemes:
  - http
paths:
  /sensorservice/status:
    get:
      tags:
        - sensor
      description: Liefert den aktuellen Servicestatus
      operationId: status
      produces:
        - application/json
      responses:
        "200":
          description: SensorService is running
          schema:
            type: string
  /energysavingservice/messwert:
    post:
      tags:
        - messwert
      description: Add a new messwert
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: messwert
          description: messwert object
          required: true
          schema:
            $ref: "#/definitions/messwert"
      responses:
        "200":
          description: successful operation
          schema:
            properties:
              id:
                type: integer
                format: int64
              message:
                type: string
        "500":
          description: Resource not created
definitions:
  messwert:
    properties:
      id:
        type: integer
        format: int64
      sensorId:
        type: integer
        format: int64
      timestamp:
        type: string
      datentypId:
        type: integer
        format: int64
      einheitId:
        type: integer
        format: int64
      berechnungId:
        type: integer
        format: int64
      wert:
        type: number #comment to fix server generation bug

**Comment by webron** [comment]
Fixed the format for you.

**Comment by nilsawesome** [comment]
Great, Thanks! :)

**Comment by webron** [comment]
While it shouldn't fail because of it, you should always add `type: object` when describing an object. Add it to both the `#/definitions/messwert` and the inline definition at 200 response schema, and it would work as expected.

**Comment by nilsawesome** [comment]
I'm sorry, but I don't know where to insert  ```type: object```. Could you post a more detailed description or an example?

**Comment by webron** [comment]
For example:

```yaml
      responses:
        "200":
          description: successful operation
          schema:
            type: object
            properties:
              id:
                type: integer
                format: int64
              message:
                type: string
```

**Comment by nilsawesome** [comment]
Thanks a lot! It's working now :)

Great support! :+1:

**Comment by webron** [comment]
Happy to hear.
