### ISSUE TITLE
 Cannot read property 'tags' of null

### ISSUE THREAD

**Issue by anysite** [swagger-api/swagger-editor#608]
When I'm pasting my (valid) yaml to swagger editor, the html on right not updated. 
This not happening with default code of Uber 
In dev console I get this error:

TypeError: Cannot read property 'tags' of null 
    at f01356c8.scripts.js:1
    at 856914f1.vendor.js:28
    at Fb (856914f1.vendor.js:28)
    at 856914f1.vendor.js:28
    at Function.<anonymous> (856914f1.vendor.js:29)
    at f01356c8.scripts.js:1
    at 856914f1.vendor.js:28
    at Fb (856914f1.vendor.js:28)
    at 856914f1.vendor.js:28
    at Function.<anonymous> (856914f1.vendor.js:29)(anonymous function) @ 856914f1.vendor.js:6

**Comment by webron** [comment]
Can do much without the YAML.

**Comment by anysite** [comment]
Yep, but I don't want it to public yet...
Is there a way to send you file in private?

**Comment by anysite** [comment]
Can I send it to your account mail?

**Comment by webron** [comment]
Yup, just email it to me.

**Comment by anysite** [comment]
Sent. Thanks.

**Comment by webron** [comment]
There are actually a few issues with the YAML which you need to resolve prior to seeing the rest.

First, `swagger` has to have the value `"2.0"`.

Second, one of your paths isn't properly indented. You need to un-indent it one step back and then you'll see the other errors.

**Comment by anysite** [comment]
Thanks! save my day.
(Sorry for the fullishness of the question, I'm nwe in yml and swagger)

**Comment by webron** [comment]
No worries. Just remember that YAML is sensitive to indentation.

**Comment by mohsen1** [comment]
Is this resolved?

**Comment by anysite** [comment]
yes. closing.
