### ISSUE TITLE
Swagger Editor shows error when re-using operation

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-editor#611]
_From @yomexzo on August 31, 2015 12:26_

It appears the `$ref` key is not well supported with operations in the swagger editor. The editor shows the error below for the snippet following below

    ✖ Swagger Error
    Additional properties not allowed: definitions,responses,paths,security,tags,securityDefinitions,schemes,consumes,produces,basePath,host,info,swagger
    Jump to line 39
    Details
     Object
      code:  "OBJECT_ADDITIONAL_PROPERTIES"
      message:  "Additional properties not allowed: definitions,responses,paths,security,tags,securityDefinitions,schemes,consumes,produces,basePath,host,info,swagger"
       path: Array [2]
      0:  "paths"
      1:  "/users/goauth-url"
      level: 900

Snippet

    swagger: "2.0"
    info:
      version: 1.2.0
      title: THE API
      description: "The documentation"
      contact:
        email: "*******"
      version: v3
    host: *******
    basePath: /v3
    produces:
      - application/json
      # - application/xml
    consumes:
      - application/json
    schemes:
      - http
      - https
    securityDefinitions:
      query_param:
        name: access_token
        type: apiKey
        description: "`access_token` is the token provided by the login endpoint on successful login."
        in: query
      # bearer_token:
        # type: basic
        # description: "`Authorization: Bearer access_token_value`. You see 'Basic Authentication' because swagger does not have the 'bearer' option. The prefix has to be`Bearer`"
    tags:
      - name: Users
    security:
      - query_param: []
    paths:
      /users/basic-login:
        $ref: '{base_url}/operations/users#basic-login'

_Copied from original issue: swagger-api/swagger-spec#453_

**Comment by yomexzo** [comment]
thanks @webron

**Comment by webron** [comment]
That's not really a valid reference, and it also looks like the error is related to something else in your definition which you haven't shared.

**Comment by yomexzo** [comment]
it is not? look at this - https://github.com/swagger-api/swagger-spec/blob/master/guidelines/REUSE.md

By the way, the swaggerui renders it pretty good

if you refer to `base_url`, i only put it there as a placeholder for you guys. imagine `http://example.com` there.

**Comment by yomexzo** [comment]
@mohsen1, have you checked the REUSE guideline i shared above? It has examples with using URL.
And like I said, it works well in swagger-ui. The problem is only with swagger-editor

REUSE guideline - https://github.com/swagger-api/swagger-spec/blob/master/guidelines/REUSE.md

**Comment by mohsen1** [comment]
I don't see URL templating for `$ref` values in that document either. Swagger Editor tries to resolve your `$ref`s to show a complete Swagger document. If your `$ref` value is not a valid URI it can't do it.

**Comment by yomexzo** [comment]
really? you can't see the what's circled in the image below?
<img width="937" alt="screen shot 2015-08-31 at 5 37 27 pm" src="https://cloud.githubusercontent.com/assets/3056958/9584271/319024f8-5008-11e5-9a18-c9fc24913729.png">
)

**Comment by mohsen1** [comment]
Yes I can see it, your $ref has `{basePath` in it. It's not a valid URI

**Comment by yomexzo** [comment]
Yo. Please read my previous comments. It's only a placeholder.

**Comment by mohsen1** [comment]
Ah I see! Sorry I missed that. I should work with **absolute** URLs in editor.swagger.io. For example, try this Swagger document:

```yaml
swagger: '2.0'
info:
  version: 0.0.0
  title: My bug repro API
paths:
  /persons:
    get:
      description: Gets Person objects
      parameters: []
      responses:
        '200':
          description: Successful response
          schema:
            title: ArrayOfPersons
            type: array
            items:
              $ref: 'http://crossorigin.me/http://coreapiteam-test.apigee.net/v1/swagger/user.json'
```

Please note that you need to have CORS enabled for those URLs. It's being requested from a different domain.

**Comment by yomexzo** [comment]
Ok. You still missed the fact that swaggerui processes it good. I have it
running in production.

Problem is with swagger-editor.

What I'm talking about here is referencing an entire operation. Not a
definition or schema. Swagger-editor throws error even with the valid
syntax/snippet I provided.

**Comment by mohsen1** [comment]
Ok I was able to reproduce this. I believe it's a bug in sway.

**Comment by yomexzo** [comment]
Finally! Sigh.

**Comment by yomexzo** [comment]
@mohsen1 
I just checked out http://editor.swagger.io/#/ (Version 2.9.7). It appears a few things are broken.
Kindly check/test.

Using parameters `in path` gives error. Also, when you use `$ref` as indicated above, the error below comes up

    Swagger Error
    Additional properties not allowed: definitions,responses,paths,security,tags,securityDefinitions,schemes,consumes,produces,basePath,host,info,swagger

**Comment by mohsen1** [comment]
@yomexzo can you provide a swagger that produces that error?
