### ISSUE TITLE
Add "CORS Proxy Preferences" dialog

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-editor#617]
To resolve remote references cross origin policies are often avoiding resolver to resolve the references. We have CORS proxy in Swagger Editor but it's only for importing swagger documents from other domains. 
This new dialog allow you to:
- Change the CORS Proxy provider
- Maintain a blacklist of domains that should not use the CORS Proxy server

All changes should be saved into browser localstorage. Possibly using `Preferences` service. The `FileLoader` service should also use the same CORS Proxy server. 
#### The default CORS Proxy server

We can use one of many providers or our current one (http://cors-it.herokuapp.com/). I predict the default server will handle a lot of traffic. @fehguy Any suggestion for the default server? Can we launch our own on swagger.io?

**Comment by andylowry** [comment]
A few comments on motivation for this feature:

Swagger [specifically recommends model reuse through JSON references](https://github.com/swagger-api/swagger-spec/blob/master/guidelines/REUSE.md). However, it is currently difficult to do this in the editor, except in cases where the referenced models are hosted in the same domain as the editor itself.

For organizations aiming to promote internal reuse, same-domain is not much of a challenge. For developers hoping to reference models shared in external repositories (notably github), use of a CORS proxy may be the only viable approach.

**Comment by webron** [comment]
Closing as an old ticket.
