### ISSUE TITLE
Open Examples yaml not opening in local server

### ISSUE THREAD

**Issue by GuptaAmit311** [swagger-api/swagger-editor#618]
Hi 

I have added the swagger editor in my existing maven project. And when I am opening  the open examples (for yaml) in File menu, its not opening. On checking the path, it's going to `http://editor-io/swaggerEditor/resources/swaggerJs/dist/spec-files/default.yaml`  path  instead of going to `http://localhost:8080/editor-io/resources/swaggerJs/dist/spec-files/default.yaml`.

Note: 
(1) I updated the examplefolder to path resources/swaggerJs/dist/spec-files/default.yaml (according to my project resources path).

(2) http://editor-io/swaggerEditor/resources/swaggerJs/dist/spec-files/default.yaml  , here swaggerEditor is the action name in controller. I am not sure how http://editor-io/swaggerEditor/resources/..  is coming instead of http://localhost:8080/editor-io/resources/.. .

And thank you for the last time, I am able to add this project in my project using the dist folder.

**Comment by mohsen1** [comment]
What's your `examplesFolder` setting?

**Comment by GuptaAmit311** [comment]
"examplesFolder": "/resources/SwaggerJs/dist/spec-files/",

**Comment by mohsen1** [comment]
Add `swagger-io` to it?

**Comment by GuptaAmit311** [comment]
In examplesFolder  "/resources/SwaggerJs/dist/spec-files/" like 
"swagger-io/resources/SwaggerJs/dist/spec-files/" or 
""/resources/SwaggerJs/dist/spec-files/swagger-io" or different way.

I don't get it. It's not in my path. 
![swaggerissue](https://cloud.githubusercontent.com/assets/8660427/9622316/4df36d4c-50e6-11e5-87d9-3ff1d463e5a0.PNG)

**Comment by mohsen1** [comment]
try opening the file in your browser by manually entering the URL. Then you'll find out what exactly  your `examplesFolder` should be

**Comment by GuptaAmit311** [comment]
ok. One thing what I am thinking example folders value is good but I am not sure about where 
editor-io/swaggerEditor/
 in http://editor-io/swaggerEditor/resources/swaggerJs/dist/spec-files/default.yaml is getting added because it's is not added in exampleFolders.

**Comment by GuptaAmit311** [comment]
Hi 
I  found one work around solution for my problem. In 5954c7da.scripts.js, as the path was coming wrong so I have to change the path, so I took the substring of window.location.pathname as desired (window.location.pathname).substring(0, window.location.pathname.length -14).


function(a,b,c,d,e,f,g,h,i,j){function k(){f.load("yaml").then(function(a){var b,e=!1;c["import"]?(b=c["import"],e=Boolean(c["no-proxy"]),d.search("import",null),d.search("no-proxy",null)):a||(b= (window.location.pathname).substring(0, window.location.pathname.length -14)+j.examplesFolder+j.exampleFiles[0]),b&&g.loadFromUrl(b,e).then(l)})}

As you know the issue is here, if you can suggest any good solution. And thank you for your help.

**Comment by mohsen1** [comment]
URL construction happens [here](https://github.com/swagger-api/swagger-editor/blob/master/app/scripts/controllers/openexamples.js#L18). Please propose a pull request if you see a bug.

**Comment by GuptaAmit311** [comment]
Thanks Mohsen, I will do that.

**Comment by GuptaAmit311** [comment]
I have an aditional question, for generate client and generate server, we have external link to servers": "http://generator.swagger.io/api/gen/servers" and   "clients": "http://generator.swagger.io/api/gen/clients" in defaults.json. 

But my server is behind a proxy. Is there any way to generate clients and servers. 

Thanks.

**Comment by mohsen1** [comment]
Use can host your own codegen. Checkout swagger-codegen project.
