### ISSUE TITLE
Swift client directory structure of hell 

### ISSUE THREAD

**Issue by tomekc** [swagger-api/swagger-editor#619]
Generated Swift client generates a lot of nested subdirectories with repeated files:

Tested on live online demo, with default Uber example:

![screen shot 2015-09-02 at 14 24 19](https://cloud.githubusercontent.com/assets/407463/9631067/b8c801d0-517e-11e5-8bf0-7233a69cc0b8.png)

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger-codegen#1179
