### ISSUE TITLE
Editing problems

### ISSUE THREAD

**Issue by Trevash** [swagger-api/swagger-editor#620]
In the editor it won't let me do anything. Adding or deleting characters doesn't change anything. Have no idea why

**Comment by mohsen1** [comment]
Do you see any errors thrown in browser console?

**Comment by Trevash** [comment]
I was able to figure it out. In the editor preferences i was in JSON and
the data was in YAML. That for some reason wouldn't let me do anything.

**Comment by mohsen1** [comment]
:+1:
