### ISSUE TITLE
Error while trying to access code generator on swagger editor

### ISSUE THREAD

**Issue by humblefools** [swagger-api/swagger-editor#621]
Hi,

I am getting following error while trying to access Code generation client and Server in swagger editor.
I dont see those options there at my code. The code has been deployed in JBOSS environment.

So I am getting following error in browser console

Mixed Content: The page at 'domain.com' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://generator.swagger.io/api/gen/clients'. This request has been blocked; the content must be served over HTTPS

**Comment by mohsen1** [comment]
You're accessing an HTTP endpoint from an HTTPS page. It's a web standard to not allow you to do that. [Read more here](https://developer.mozilla.org/en-US/docs/Security/MixedContent)

**Comment by humblefools** [comment]
Yeah...that's what...so since there is no http so version of http://generator.swagger.io/api/gen/clients

How do I use it to access over my application which is hosted over https

**Comment by humblefools** [comment]
I meant https version

**Comment by mohsen1** [comment]
Checkout swagger-codegen project. You can host your own on your https server
