### ISSUE TITLE
Editor gets js error "function($provide) is not using explicit annotation and cannot be invoked in strict mode"

### ISSUE THREAD

**Issue by DavidBiesack** [swagger-api/swagger-editor#622]
I've pulled a recent version of swagger-editor, then created a local branch and configured it via `app/config/defaults.json`
to use a running local instance of cors-it (to access dev resources inside our firewall)
When I start the editor, everything builds and launches
```
  PORT=9000 npm run develop
```
and it opens the URL of the editor, but the page is blank.

My changes are:

change the host/port in `grunt/connect.js`:
```
module.exports = {
  options: {
    port: developmentPort,
    hostname: 'swagger.na.sas.com',
    livereload: 35729
  },
```
Change proxy in `app/config/defaults.json`:
```
  "importProxyUrl": "http://swagger.na.sas.com:9009/?url="
```
that proxy is working outside of swagger-editor (i.e. curl)

The Editor works in master on localhost. Perhaps the cors-it proxy causes some error?

I see this in the js console (which I do not see when I don't configure a local cors-it)
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module SwaggerEditor due to:
Error: [$injector:strictdi] function($provide) is not using explicit annotation and cannot be invoked in strict mode
http://errors.angularjs.org/1.4.5/$injector/strictdi?p0=function(%24provide)
    at http://swagger.na.sas.com:9000/bower_components/angular/angular.js:68:12
    at Function.annotate [as $$annotate] (http://swagger.na.sas.com:9000/bower_components/angular/angular.js:3742:17)
    at Object.invoke (http://swagger.na.sas.com:9000/bower_components/angular/angular.js:4451:36)
    at runInvokeQueue (http://swagger.na.sas.com:9000/bower_components/angular/angular.js:4379:35)
    at http://swagger.na.sas.com:9000/bower_components/angular/angular.js:4388:11
    at forEach (http://swagger.na.sas.com:9000/bower_components/angular/angular.js:336:20)
    at loadModules (http://swagger.na.sas.com:9000/bower_components/angular/angular.js:4369:5)
    at createInjector (http://swagger.na.sas.com:9000/bower_components/angular/angular.js:4294:11)
    at doBootstrap (http://swagger.na.sas.com:9000/bower_components/angular/angular.js:1655:20)
    at Object.bootstrap (http://swagger.na.sas.com:9000/bower_components/angular/angular.js:1676:12)
http://errors.angularjs.org/1.4.5/$injector/modulerr?p0=SwaggerEditor&p1=Er…er.na.sas.com%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A1676%3A12)
```

**Comment by mohsen1** [comment]
I don't know what's going on with your setup. You can disable `strictDi` to get rid of this error 

https://github.com/swagger-api/swagger-editor/blob/master/app/scripts/bootstrap.js#L32

**Comment by DavidBiesack** [comment]
I'm running dev so should that not be disabled for me already?

**Comment by DavidBiesack** [comment]
Ah, I see - I'm not running on localhost, so it thinks I'm on production. Can this setting use the same logic in connect.js - i.e. if I run `npm run develop' then I should be in develop mode -- set a flag there that is read by boostrap. (I can't use localhost because I want to share this instance with other develoeprs)

**Comment by DavidBiesack** [comment]
setting that to false in my dev branch works - editor comes up.

Still need a fix for production when using a configured local cors-it instance

**Comment by mohsen1** [comment]
Yes, detecting development mode based on URL wasn't a good idea. We need to change that. Follow that feature request [here](https://github.com/swagger-api/swagger-editor/issues/624)
