### ISSUE TITLE
How can I export the HTML of the preview?

### ISSUE THREAD

**Issue by ikarius6** [swagger-api/swagger-editor#623]
I have a preview, but I can't export it, I wasted too many hours doing the documentation for my project, but I would like to have an export for the preview because looks great.

**Comment by mohsen1** [comment]
First of all, that language is not welcome here.

The preview panel is not a replacement for Swagger UI. It has editor specific components in it. Use [swagger-ui](https://github.com/swagger-api/swagger-ui) for that matter.

**Comment by prabhatjha** [comment]
@ikarius6 Would you be able to help implement this feature?

**Comment by ikarius6** [comment]
Sorry, I got upset because I'm new in Swagger and I thought than I could have the preview as the final result... I like the preview even more than swagger-ui, I can try to modify the code to add this feature.

**Comment by ikarius6** [comment]
Its hard to debug the minified angular of this, I hope than the original developers add the versión of the code without minify

**Comment by chrisdudley** [comment]
See 'running in development mode' here in the docs:
https://github.com/swagger-api/swagger-editor/blob/master/docs/development.md
