### ISSUE TITLE
$ref broken in preview

### ISSUE THREAD

**Issue by 3plusalpha** [swagger-api/swagger-editor#627]
When using a $ref (to definitions) in "response", the preview can not resolve the $ref and just shows like on this screenshot. The online editor works like expected, but not the one I just downloaded.

<img width="801" alt="bildschirmfoto 2015-09-05 um 23 10 19" src="https://cloud.githubusercontent.com/assets/1685307/9701306/52e85b24-5423-11e5-9ed2-461074165a6d.png">

I am using version 2.9.6 locally.

**Comment by mohsen1** [comment]
Please use latest master if you are running locally. We will release 2.9.7 soon.

**Comment by 3plusalpha** [comment]
I pulled the latest master, but problem stays the same.
