### ISSUE TITLE
generate example code doesn't render sub-objects

### ISSUE THREAD

**Issue by dothebart** [swagger-api/swagger-editor#628]
I'm loading this json:
https://gist.github.com/e5568d0fe9959b60a26f
into the swagger editor. I open the 'try this operation'-box.

My expectations would be to get the property 'options' as a box containing input fields for its three properties  ["keepNull" "limit", "waitForSync"].

Instead swagger renders a dropdown with the possible datatypes [null/string/number/integer/object/array]

**Comment by mohsen1** [comment]
I see 2 input fields actually and one binary dropdown as I would expect from your schema.

<img width="610" alt="screen shot 2015-09-08 at 10 33 22 am" src="https://cloud.githubusercontent.com/assets/543633/9742462/17bfe050-5615-11e5-8000-e55a81170a71.png">

**Comment by dothebart** [comment]
Check! git pull and restart contained a fix for this.
