### ISSUE TITLE
json editor not loaded

### ISSUE THREAD

**Issue by dothebart** [swagger-api/swagger-editor#629]
I'm loading this json:
https://gist.github.com/e5568d0fe9959b60a26f
into the swagger editor. I open the 'try this operation'-box.

I would expect 'newValue' become an 'edit json control' (like it is if the whole body can be a schema less json) - but instead it is just an empty box.

**Comment by mohsen1** [comment]
Can  you be more clear? I don't see what you're describing here in editor.swagger.io. Are you using a hosted version?

**Comment by webron** [comment]
@mohsen1 - `newValue` is a generic object, and should allow adding arbitrary keys and values to it.

**Comment by mohsen1** [comment]
Got it

**Comment by mohsen1** [comment]
Simpler Swagger for reproducing this issue:

```yaml
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /:
    post:
      parameters:
        - name: body
          in: body
          description: description
          schema:
            $ref: "#/definitions/Test"
        
      responses:
        '200':
          description: OK
definitions:
  Test:
    properties:
      deep:
        type: object
        additionalProperties: true
```
