### ISSUE TITLE
Refresh security authentication values in try operation after authentication changed. 

### ISSUE THREAD

**Issue by davisford** [swagger-api/swagger-editor#631]
This yaml security mechanism used to work, but today when I try (this pared down example), it no longer works with editor.swagger.io

If you hit the `Authenticate` button and paste in any 'ol string as a token, it should be reflected on the outbound POST to `/orgs`, but it is not.  The headers don't get updated anymore it seems?

I have set the top-level security to be 

```yaml
security:
    - jwtAuth: []
```

...and I also tried adding it directly to the `/orgs` POST path, but it seems to have no effect?

Full yaml sample:

```yaml

swagger: '2.0'

# Document metadata
info:
  version: 0.0.0
  title: test
  contact:
    name: foo bar
    url: http://example.com
    email: foo@example.com
  
securityDefinitions:
  jwtAuth:
    type: apiKey
    name: Authorization
    in: header

host: localhost:8080
basePath: /api/v1/admin
produces: ["application/json"]
consumes: ["application/json"]

# top level security
security:
  - jwtAuth: []


# the list of endpoints
paths:
  /auth:
    parameters:
      - in: body
        name: auth
        schema:
          $ref: '#/definitions/Auth'
    post:
      # note this path is explicitly unprotected b/c this is how we get the token
      security: []
      responses:
        200:
          description: Auth success
          schema:
            $ref: '#/definitions/Token'
        401:
          description: Unauthorized

  /orgs:
    post:
      security:
        - jwtAuth: []
      responses:
        201:
          description: Success
          schema:
            $ref: '#/definitions/Org'
 
# global definitions
definitions:
  Auth:
    type: object
    description: Authentication credentials
    required: ['email', 'password']
    properties:
      email:
        type: string
        format: email
      password:
        type: string
        format: password
  Token:
    type: object
    description: Auth token returned upon successful authentication
    properties:
      token:
        type: string
        readOnly: true
  Org:
    required:
      - name
    properties:
      id:
        type: number
        format: int
        readOnly: true
      createdAt:
        type: string
        format: date-time
        readOnly: true
      updatedAt:
        type: string
        format: date-time
        readOnly: true
      name:
        type: string

```

**Comment by mohsen1** [comment]
Thanks for reporting! 
@iflamed is this caused by session storage changes we made recently?

**Comment by chrisdudley** [comment]
Is issue specific to IE? (If so its the session storage bug)

**Comment by davisford** [comment]
It is not specific to IE, I am using Chrome

**Comment by mohsen1** [comment]
Actually I can't reproduce it in editor.swagger.io. Please see the screenshot.

Also note that if your request is cross origin, some of the headers won't be sent.

![screen shot 2015-09-08 at 1 23 46 pm](https://cloud.githubusercontent.com/assets/543633/9746476/fa669298-562c-11e5-9e59-e01b294e7d48.png)

**Comment by davisford** [comment]
It's cross-origin, yep, but I do have a CORS server which happily serves these requests.  In any event, the preview of the outbound POST also doesn't update and show the `Authorization` header.  Not sure if that's a surefire indication that it still wouldn't actually send the header, but in practice when I do send the request, the header is not present.

![screen shot 2015-09-08 at 4 27 26 pm](https://cloud.githubusercontent.com/assets/186677/9746596/d6771316-5646-11e5-9df4-ec2503415a3f.png)

![screen shot 2015-09-08 at 4 27 39 pm](https://cloud.githubusercontent.com/assets/186677/9746599/dbe7930c-5646-11e5-8c8a-78fd8d8a838e.png)


![screen shot 2015-09-08 at 4 29 45 pm](https://cloud.githubusercontent.com/assets/186677/9746602/e0ae65fa-5646-11e5-81b0-497e40c9ea4e.png)

**Comment by mohsen1** [comment]
do you close and open "try this operation" panel after authorizing? It's a known bug that the security authentications don't update the try operation as you change them.

**Comment by davisford** [comment]
@mohsen1 I think you hit the nail on the head.  I was not aware it was a known bug :)  I'm betting that was it, b/c after I tried refreshing and toggling the list all operations button a few times, it finally does appear in the outbound post preview.  Feel free to close or mark as dupe of the other issue.  Thanks for the quick responses.

**Comment by mohsen1** [comment]
I thought we have a bug open for this but apparently we didn't. We'll keep this open until we fix it.

**Comment by chrisdudley** [comment]
https://github.com/swagger-api/swagger-editor/issues/551 :-)

**Comment by mohsen1** [comment]
Thanks @chrisdudley!

**Comment by iflamed** [comment]
@mohsen1  Maybe yes. I will check it today.
