### ISSUE TITLE
"Sinatra" should be under "Generate Server" drop-down menu

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-editor#632]
"Sinatra" is a Ruby web framework/library so it should fall under the "Generate Server" instead of "Generate Client" drop-down menu in http://editor.swagger.io/#/ 

Ref: https://en.wikipedia.org/wiki/Sinatra_(software)

**Comment by webron** [comment]
That's actually a bug in the codegen. 

http://generator.swagger.io/#!/clients/clientOptions
http://generator.swagger.io/#!/servers/serverOptions

**Comment by wing328** [comment]
Now it's fixed.
<img width="367" alt="screen shot 2015-09-09 at 8 08 37 pm" src="https://cloud.githubusercontent.com/assets/934260/9761329/a5354e2e-572e-11e5-8b78-697b970896d3.png">

Do you know what has been done to fix it?

**Comment by webron** [comment]
It's not fixed. That's Scalatra, not Sinatra :)

**Comment by wing328** [comment]
Oh sorry. Will look into the 'swagger-generator` under swagger-codegen...

**Comment by wing328** [comment]
My bad. Fixed in https://github.com/swagger-api/swagger-codegen/pull/1206

**Comment by wing328** [comment]
@mohsen1 FYI. We need to pull the latest master of swagger-codegen server and bounce the service in order to pick up the fix. (I do not have the right to do that)

**Comment by webron** [comment]
That's on @fehguy or me.

**Comment by mohsen1** [comment]
Yup, code-gen menus are populated based on code-gen server response. No work needed to be done on editor side.

**Comment by webron** [comment]
@mohsen1 - that reminds me I may want to open a related issue ;)

**Comment by mohsen1** [comment]
Go ahead @webron. If something is broken we should fix it. :)

**Comment by webron** [comment]
Fine ;)
