### ISSUE TITLE
If there's no access to the codegen server...

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-editor#635]
If there's no access to the codegen server (assuming it is configured), instead of just not showing the codegen menu items (which is fine), provide an error message that the generator server is inaccessible. I'd suggest it would be a floating error that dismisses itself after about 10 seconds (possibly with an option to manually dismiss it).

The reason for it is that a few days ago the server was down and one of the users thought the code generation feature was removed. This would help provide some insight as to why the menu items are missing.

Another option is to still keep the menu items, but when clicked just display a disabled menu item saying the codegen server is inaccessible.

**Comment by mohsen1** [comment]
Does showing something like this works?

<img width="483" alt="screen shot 2015-09-09 at 10 20 48 am" src="https://cloud.githubusercontent.com/assets/543633/9769056/89f35478-56dc-11e5-8258-69c7fe308f2a.png">

**Comment by webron** [comment]
Yeah, that works as a basic functionality, thanks.
