### ISSUE TITLE
feedback why 'Import'-button is not pressable wanted

### ISSUE THREAD

**Issue by dothebart** [swagger-api/swagger-editor#638]
I tried to use 'import from url' to import the swagger json from... https://raw.githubusercontent.com/arangodb/arangodb/devel/js/apps/system/_admin/aardvark/APP/api-docs.json 
The mouse over on the button shows a 'parking forbidden' icon, but no reason why. 
It seems it can either be that its still processing everything (in that case a progress would be nice) or the format of the file is invalid.

**Comment by dothebart** [comment]
https://gist.github.com/5600eec47e9883527e87 has *"required": [],* in line 48 which is wrong. Loading the File via json will also do nothing, only pasting it into the 'Paste JSON' window gave me tracks to the error.

**Comment by mohsen1** [comment]
I believe editor goes to an infinite loop with your spec (the one you posted on original issue). I'm looking into it.

**Comment by dothebart** [comment]
maybe showing a throbber while its loading is a good thing to have? 
Since all the parsing can take a while... Even if there is no infinite loop ;-)

**Comment by mohsen1** [comment]
I've closed this bug which was related to the import dialog. the swagger you have in that URL still crashes the editor but I'll open a separate issue if I can confirm what exactly is going on
