### ISSUE TITLE
Import .yaml File does not work

### ISSUE THREAD

**Issue by ophilippsen** [swagger-api/swagger-editor#640]
# Import .yaml file does not work - not able to press "Import" Button.

1. Select "File"

![bug-01-select-file](https://cloud.githubusercontent.com/assets/4084699/9814793/1e518058-5891-11e5-8956-fd8475cdc8f2.jpg)

2. Select "Import File"

![bug-02-select-file-to-import](https://cloud.githubusercontent.com/assets/4084699/9814798/23197a50-5891-11e5-9e89-5233764a5607.jpg)

3. Select File to upload

![bug-03-file](https://cloud.githubusercontent.com/assets/4084699/9814814/3bfbebc0-5891-11e5-8e34-2eff0936847c.jpg)

4. Import never ends - it is not possible to import selected file

![bug-04-import-not-availabke](https://cloud.githubusercontent.com/assets/4084699/9814821/480de36e-5891-11e5-8c43-21495e34ce45.jpg)

Used Swagger Editor 2.9.6

![bug-swagger-editor-296](https://cloud.githubusercontent.com/assets/4084699/9814843/8453f5f2-5891-11e5-8ca4-942fd62031ca.jpg)

Used Browser: Google Chrome Version 45.0.2454.85 (64-bit Mac OS X)

**Comment by ophilippsen** [comment]
Used latest Release 2.9.7 - but it´s displaying 2.9.6 in Browser.

**Comment by mohsen1** [comment]
After file is selected AngularJS doesn't digest the modal. If you click outside of the blu button it activates.
