### ISSUE TITLE
Chrome Aw! Snap! when pasting this Swagger spec

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-editor#641]
originally from https://github.com/swagger-api/swagger-editor/issues/638

https://raw.githubusercontent.com/arangodb/arangodb/devel/js/apps/system/_admin/aardvark/APP/api-docs.json

**Comment by dothebart** [comment]
you should note that this file is script generated, and thus may change by time - so you may eventually want to remember the git-revision.

**Comment by mohsen1** [comment]
Good point! This includes git sha:
https://raw.githubusercontent.com/arangodb/arangodb/73ada35a0d64edfb821eefa7df26c617f5226d83/js/apps/system/_admin/aardvark/APP/api-docs.json

**Comment by johanhammar** [comment]
We were also affected by this bug. Pasting a large, about 2300 lines, Swagger spec resulted in Chrome crashing. Anyway, now it works! Thanks :+1:

**Comment by saharj** [comment]
This issue should be fixed now. We have web workers that take the load off the main thread.
