### ISSUE TITLE
Open large swagger.json killing Chrome tabs and Firefox app

### ISSUE THREAD

**Issue by vladimir-mhl** [swagger-api/swagger-editor#651]
1. open for instance https://www.callfire.com/api/v2/apidocs/swagger.json in online swagger-editor
2. make any change to schema to break it
3. wait processing
   3.1. Chrome 45.0.2454.85 tab will die with message: "Ah, Snap. Close other tabs to get memory available"
   3.2 Firefox 40.0.3 completely hangs.

**Comment by mohsen1** [comment]
I think we have a memory leak issue #641 is reporting the same issue. These Swagger docs are really large but it shouldn't crash the browser.

**Comment by NeoElit** [comment]
Same issue here. Leaving tab for some period(not exactly sure about the effect) and adding any new element to definitions makes some bundle.js script go haywire on the cpu and makes firefox frozen or asks to force stop the script. Either way, editor becomes unusable without a page reload.

**Comment by webron** [comment]
Hopefully, this is no longer an issue with 3.X.
