### ISSUE TITLE
Add support for rendering the 'example' attribute of schema objects

### ISSUE THREAD

**Issue by chrisdudley** [swagger-api/swagger-editor#652]
Schema Objects support an example attribute to provide a user friendly example of the request/response object.
It would be nice if the editor could render these in the UI somehow.

https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#schemaObject
e.g.
<pre>
properties:
  id:
    type: integer
    format: int64
  name:
    type: string
required:
- name
example:
  name: Puma
  id: 1
</pre>

**Comment by mohsen1** [comment]
That's a request for JSON Schema View dependency.

**Comment by mohsen1** [comment]
This issue was moved to mohsen1/json-schema-view-js#1
