### ISSUE TITLE
500 error when missing response object is missing type

### ISSUE THREAD

**Issue by alkalinecoffee** [swagger-api/swagger-editor#653]
When attempting to generate client docs via the swagger editor demo site, omitting the type from the schema of a response results in a 500 "something bad happened" error.

```yaml
paths:
  /keys/current.json:
    get:
      summary: current key
      description: Returns info about the current key
      responses:
        200:
          description: json with information about the key
          schema:
            type: object <--- errors if this line is omitted
            properties:
              signing_key:
                properties:
                  name:
                    type: string
```

Swagger validation otherwise considers this valid.

**Comment by mohsen1** [comment]
Yes, that's a know bug in swagger codegen. Please follow this: https://github.com/swagger-api/swagger-codegen/issues/1170
