### ISSUE TITLE
Swagger $ref for re-usable response block returns Swagger Error: A deterministic version of a JSON Schema object.

### ISSUE THREAD

**Issue by joewhite101** [swagger-api/swagger-editor#654]
I'm trying to re-use a response block in a large swagger schema but I get an error that says: "Swagger Error A deterministic version of a JSON schema object". Is it possible to re-use response objects in the yml format?

A sample schema that reproduces the error is:

    swagger: '2.0'
    info:
      version: 0.0.0
      title: '<enter your title>'
    paths:
      /persons:
        get:
          description: |
            Gets `Person` objects.
            Optional query param of **size** determines
            size of returned array
          parameters:
            - name: size
              in: query
              description: Size of array
              required: true
              type: number
              format: double
          $ref: '#/definitions/NoBodyResponse'
    definitions:
      NoBodyResponse:
        responses:
              '200':
                description: Successful response

**Comment by mohsen1** [comment]
The way `$ref` works is it overrides all it's siblings and itself with **content** of where it's value pointing at

You can use standard global `responses` hash:

```
swagger: '2.0'
info:
  version: 0.0.0
  title: '<enter your title>'
paths:
  /persons:
    get:
      description: |
        Gets `Person` objects.
        Optional query param of **size** determines
        size of returned array
      parameters:
        - name: size
          in: query
          description: Size of array
          required: true
          type: number
          format: double
      responses:
        200:
          $ref: '#/responses/200'
responses:
  200:
    description: Successful response
```

**Comment by joewhite101** [comment]
Ah thanks. Appreciate the quick response. Closing.

**Comment by abhijeetbhanjadeo** [comment]
Duplicate use of "definitions" in swagger files(referenced/split swagger files) also generates this error - "A deterministic version of a JSON Schema object."
