### ISSUE TITLE
Bug/feature-request: Preview doesn't update after fixing error. Want manual refresh button. 

### ISSUE THREAD

**Issue by tsoernes** [swagger-api/swagger-editor#655]
If I get an error and fix it, the preview does not update. Sometimes it is necessary to reload the file. A manual refresh button would be nice. Swagger 2.0, Editor 2.9.7

Edit: Also, the "collapse"/"open" warning windows does not work. Nothing shows there at all.

**Comment by mohsen1** [comment]
What browser you use? Can you run locally off latest in master and let me know if it's still an issue?

**Comment by tsoernes** [comment]
Firefox 40.0.3. I run the latest (downloaded 6 hours ago) locally which I got from here: `git clone https://github.com/swagger-api/swagger-editor.git`

**Comment by mohsen1** [comment]
Please get the latest again. 45ad38a might have fixed it.

**Comment by tsoernes** [comment]
It still isn't fixed.

![untitled](https://cloud.githubusercontent.com/assets/6782404/9959635/c8f83626-5e15-11e5-84e0-dbda4e9284cc.png)

If I refresh the page the error goes away.

**Comment by mohsen1** [comment]
Can you try again?

**Comment by saharj** [comment]
Seems like this issue has been fixed. Please let me know if you still have this issue.
