### ISSUE TITLE
Bug: The downloaded YAML-file does not have changes

### ISSUE THREAD

**Issue by tsoernes** [swagger-api/swagger-editor#656]
I download the YAML-file of my API in the editor, but I get an old revision, not the new one. The downloaded file has no saved changes. Also happens when downloading as JSON-file.

**Comment by marpatt206** [comment]
Was this issue reintroduced in Swagger Online Editor 2.10.5?  Selecting File --> Download JSON does not capture the latest changes visible in the YAML.

**Comment by webron** [comment]
It shouldn't have been, but I'd suggest you try the new editor, for now hosted at https://editor3.swagger.io.

**Comment by marpatt206** [comment]
Thanks.  Are there any resources available online for new editor info and if this is considered GA?  Assuming beta due to hosted URL.

**Comment by webron** [comment]
It's fairly new, so not a lot of resources. It's GA.
