### ISSUE TITLE
Add "Parameters" and "Responses" block in preview section

### ISSUE THREAD

**Issue by tmack8001** [swagger-api/swagger-editor#657]
Similar to "Paths", "Models", and "Security" there should also be a generic listing of the commonly defined parameters available in the swagger document. Example that is using this common parameters block is the instagram.yaml document which defines 2 parameters `user-id` and `tag-name`. This would help API designers to have a pre-populated set of documented parameters to choose to use via $ref within their route documentation.

**Comment by mohsen1** [comment]
Good idea. There is also `responses` in root level which we can render next to paths.

Pull request welcome!

**Comment by tmack8001** [comment]
I have started looking at adding this feature, right now got ```params``` working locally. Going to try and pull out the parameter specific helpers ```setParameterSchema``` into a shared resource to be shared with ```operation.js```. Also think it would be a good idea to pull the rendering of an individual ```parameter``` out into a shared template, but not sure if I should work too much on that or leave that as a *further enhancement* later on.

Also need to do similar to get the top level ```responses``` as suggested here.

As this is my first attempt to contribute to this repo and to this organization as a whole, any additional information other than create an Issue / Pull Request required?

**Comment by webron** [comment]
We're not planning on supporting that for Swagger/OpenAPI 2.0. It might change in OAS3.0.
