### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by tsoernes** [swagger-api/swagger-editor#658]
Sir I think we have a memory leak:

![untitled](https://cloud.githubusercontent.com/assets/6782404/9948363/a1759512-5da2-11e5-929e-a9f43c0877bf.png)

None of the other tabs are loaded, although it certainly could be a Firefox issue.
Im on https://github.com/swagger-api/swagger-editor/commit/42ac546defaf363761b0fad64ccdb99cb241fa4b. If I close the Editor tab it drops down to 500 mb.

**Comment by mohsen1** [comment]
Yes I believe we have a memory leak. Please see #651 and #641
