### ISSUE TITLE
The version number in About Dialog is 2.9.6, not match the relese 2.9.7.

### ISSUE THREAD

**Issue by zhangxd926** [swagger-api/swagger-editor#659]
As subject.
The version number is better updated by a build system.

**Comment by mohsen1** [comment]
are you sure you're running the latest and it's not cached? It is updated. [See here](https://github.com/swagger-api/swagger-editor/blob/master/app/templates/about.html#L6)

I like the idea of updating it as part of build process. Pull request is welcome for that!
