### ISSUE TITLE
Multiple Enums under Parameters throws an error

### ISSUE THREAD

**Issue by scottefein** [swagger-api/swagger-editor#660]
Here's a gist demonstrating the problem (working is w/o a second enum, broken is with a second enum): https://gist.github.com/scottefein/656d3cb79d00b5e14a6a

When there is more than one enum, the following error is thrown: 

Swagger Error
Data does not match any schemas from 'oneOf'

**Comment by mohsen1** [comment]
@webron @whitlockjc This is interesting!

**Comment by webron** [comment]
It's got nothing to do with the enum, it's the path parameter itself. It has to be required.

**Comment by scottefein** [comment]
Ah-that works! Thanks for looking into that :)

**Comment by mohsen1** [comment]
Error reporting will get better after [this](https://github.com/apigee-127/sway/issues/15) is done.
