### ISSUE TITLE
Import File... not working for YAML file.

### ISSUE THREAD

**Issue by RitwikChatterjee** [swagger-api/swagger-editor#661]
Hi,
When I am trying to import a Swagger definition YAML file, it does not work.

If I try importing a file through the menu: File --> Import File..., the import button is not activated if I choose a YAML file. I can import the same definition in JSON.
If I drag and drop into the editor, nothing happens, either for the YAML or the JSON version of the file.

Note, I am using a YAML file that I created and downloaded from the Swagger Editor.
I have used both Chrome and Firefox to try it out.

Regards,
Ritwik

**Comment by mohsen1** [comment]
Import File works for me. Are you trying the latest build?

**Comment by RitwikChatterjee** [comment]
Thank you @mohsen1, it works fine now.

Regards,
Ritwik
