### ISSUE TITLE
Can't open example on demo editor on Safari

### ISSUE THREAD

**Issue by martinpallmann** [swagger-api/swagger-editor#662]

**Comment by webron** [comment]
That's really not enough info.

**Comment by martinpallmann** [comment]
on Safari 8.0.8 with Mac OS X 10.10.5
If I click on File -> open Example, a Modal window opens but if I click "OK" nothing happens.

I added a Screenshot of the console. There are two errors if I open the page. Don't know if they are relevant though.

![screenshot 2015-09-21 14 29 22](https://cloud.githubusercontent.com/assets/132760/9991785/5b8c74ee-606d-11e5-84f7-f916444d23b3.png)

**Comment by martinpallmann** [comment]
Same thing when I click "Download JSON" or "Download YAML" btw.

**Comment by webron** [comment]
Confirmed. For now, as a workaround, you can use a different browser for now.

**Comment by martinpallmann** [comment]
Yes. Did that. Thank you. Chrome works.

**Comment by mohsen1** [comment]
This is a bug in YAML worker. https://github.com/mohsen1/yaml-worker/issues/3
