### ISSUE TITLE
/definitions and/or responses are not properly updated when pasting whole spec

### ISSUE THREAD

**Issue by dolmen** [swagger-api/swagger-editor#663]
As the editor is currently instable (see #641...), I'm editing my spec using copy/paste from my text editor: `Ctrl+A`, `Delete`, `Ctrl+V` and reload the rendering (I have auto-rendering disabled).

It appears that responses schemas referenced in responses are not properly updated when I change an indirect (`$ref`) response schema. It looks like schema definitions or whole responses are cached.
Workaround: paste the the whole spec, delete `/paths` and `/definitions`, reload the rendering, paste the whole spec again, reload the rendering. 

Editor v2.9.7

**Comment by mohsen1** [comment]
Can you provide exact steps to reproduce this issue? A minimal Swagger spec would be very helpful.

**Comment by mohsen1** [comment]
Also please use the latest version.
