### ISSUE TITLE
Incorrect cursor position when writing in non-latin text (e.g. in Russian)

### ISSUE THREAD

**Issue by rutsky** [swagger-api/swagger-editor#665]
AFAIK Ace editor supports only monospace fonts and used in Swagger Editor Source Code Pro font doesn't have Cyrillic glyphs, so browser uses some other, non monospace, font.

Here is example of how it looks like if I type "ЩЩЩ":
![selection_013](https://cloud.githubusercontent.com/assets/46573/10043510/5f7fb10c-61fc-11e5-9b64-cedd23be6f87.png)

Notice cursor floating in the center of the letter.

Here is how it looks if I disable Source Code Pro font in Firefox style editor:

![selection_014](https://cloud.githubusercontent.com/assets/46573/10043572/d8925bd0-61fc-11e5-84ff-70defd4524d4.png)

**Comment by mohsen1** [comment]
Are you on Windows? It's working fine for me on OS X.

One improvement that we can do on this is to add `unicode-range` to Source Code Pro font family in [fonts.less](https://github.com/swagger-api/swagger-editor/blob/master/app/styles/fonts.less) file.

Source Code Pro has a wide range. I'm pretty sure Russian characters are in it. See [Google Fonts entry](https://fonts.googleapis.com/css?family=Source+Code+Pro) and [Source Code Pro repo](https://github.com/adobe-fonts/source-code-pro)

**Comment by rutsky** [comment]
I'm on Ubuntu 14.04.

Cyrillic support in Source Code Pro was introduced recently, in [July 2015](https://github.com/adobe-fonts/source-code-pro/issues/48).

Looking at https://github.com/swagger-api/swagger-editor/tree/master/app/fonts I can conclude that Swagger distributes own copy of Source Code Pro fonts, and last version of the fonts was updated 4 months ago, when no Cyrillic support was in the Source Code Pro font.

**Comment by rutsky** [comment]
@mohsen1 I think you are lucky that fallback font for Source Code Pro on your system has monospace Cyrillic glyphs.

**Comment by mohsen1** [comment]
I think that is the case. Can you run Swagger Editor locally and update the font file with latest from their GitHub repo and let me know the results? It would be nice if you make a pull request with that change.

**Comment by rutsky** [comment]
I tested latest release of Source Code Pro fonts and cyrillic works there:

![selection_017](https://cloud.githubusercontent.com/assets/46573/10058117/76013248-624c-11e5-8cd9-1d50dc953258.png)

I can provide pull request, but first, why do you embed fonts, why not to install them using Bower?
E.g. 

```
bower install --save-dev git://github.com/adobe-fonts/source-code-pro.git#2.010R-ro/1.030R-it
```

**Comment by mohsen1** [comment]
I would love to take out fonts from source code but not all of them are available in bower/github. If you can do it even partially I would appreciate it.

**Comment by rutsky** [comment]
Source Code Pro is not published in Bower, instead they suggest to install directly from GitHub.

Source Code Pro's release branch doesn't have SVG version of fonts (which are not supported in major browsers anyway), but has WOFF2 version.

**Comment by mohsen1** [comment]
Then lets keep having font files in the source code. It's more reliable and predictable.

**Comment by rutsky** [comment]
> Then lets keep having font files in the source code. It's more reliable and predictable. 

I used specific git sha1 version in PR - this should be reliable and predictable, unless Adobe will decide to remove whole repository.

**Comment by mohsen1** [comment]
ok, works for me. Does it install all variants(thicknesses)?

**Comment by rutsky** [comment]
> ok, works for me. Does it install all variants(thicknesses)?

I believe so.
Previously (according to fonts definitions in `fonts.less`) there was: "font-style: normal; font-weight: 300, 400, 500, 600;";
now (according to `source-code-pro.css`) there is additionally "font-weight: 200, 700, 900" and "italic" variants for all provided thicknesses.
