### ISSUE TITLE
Error starting the editor without default yaml

### ISSUE THREAD

**Issue by xuanli09** [swagger-api/swagger-editor#669]
I'm trying to initialize the editor in a blank state (without any sample file) and getting a 404 in the console.

On main.js 35, if I were to comment out the load defaults or replace it with assign(''); I would get the following in the console on first load of the editor when the editor cache is empty:

404 http://localhost:9000/bower_components/sway-worker/undefined

This is the latest on master.

**Comment by mohsen1** [comment]
Are you running a backend for editor?

**Comment by xuanli09** [comment]
I have left everything the same in defaults.json (useBackendForStorage: false). 

This seemed to started happening since around 2.9.7.

**Comment by mohsen1** [comment]
You can use an empty string with one single space instead of an empty string with no character maybe?

**Comment by xuanli09** [comment]
I tried replacing it with assign(' '); and still results in the same error.

**Comment by mohsen1** [comment]
If you are modifying editor code, please paste you code here so we can see what exactly you're doing

**Comment by xuanli09** [comment]
Here's the isolated change I have done on top of master: https://github.com/xuanli09/swagger-editor/commits/Issue-669

If you run this initially w/o anything in localstorage (EditorCache), you will get this error:

404 http://localhost:9000/bower_components/sway-worker/undefined

**Comment by mohsen1** [comment]
Instead of doing that, why don't you update the default yaml file to be an empty file? Possibly with a single new line or space in it

**Comment by xuanli09** [comment]
Yea I tried adding a new empty yaml file and adding it to the first entry in the defaults.json. It still results in this error.

**Comment by xuanli09** [comment]
Actually Mohsen, I'm seeing this problem with just the HEAD of master without any changes?

When I run grunt test:

````
Browser console log: 
{ level: { value: 1000, name: 'SEVERE' },
  message: 'http://localhost:8282/bower_components/sway-worker/undefined 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
  timestamp: 1443826058910,
  type: '' } 0 [ { level: { value: 1000, name: 'SEVERE' },
    message: 'http://localhost:8282/bower_components/sway-worker/undefined 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1443826058910,
    type: '' }
}
````

**Comment by mohsen1** [comment]
Try cleaning up node_modules and bower_components folders and install dependencies from scratch. Tests are passing in HEAD of master

**Comment by xuanli09** [comment]
This is weird, I have done the following:

rm -rf app/bower_components
rm -rf node_modules
bower cache clean
npm cache clean

npm install
bower install
./node_modules/protractor/bin/webdriver-manager update
grunt build; grunt test

I'm still seeing the test report:

````
Browser console log: 


{ level: { name: 'SEVERE', value: 1000 },
  message: 'http://localhost:8282/bower_components/sway-worker/undefined 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
  timestamp: 1444068121842,
  type: '',
  closure_uid_770408909: undefined } 0 [ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8282/bower_components/sway-worker/undefined 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444068121842,
    type: '',
    closure_uid_770408909: undefined } ]
  Should not have any console errors or warnings - fail
````

**Comment by rlo2014** [comment]
I've pulled latest from head of master and I too have the same error below.  I pulled as of this morning.  Any way to get some other verification on this?  I'm running OS X Yosemite (10.10.5) (Did not upgrade to El Capitan, but up to date besides that).  Bower 1.4.1, npm 2.7.4, grunt v0.4.5.

Browser console log: 


{ level: { name: 'SEVERE', value: 1000 },
  message: 'http://localhost:8282/bower_components/sway-worker/undefined 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
  timestamp: 1444069829660,
  type: '',
  closure_uid_932951173: undefined } 0 [ { level: { name: 'SEVERE', value: 1000 },
    message: 'http://localhost:8282/bower_components/sway-worker/undefined 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)',
    timestamp: 1444069829660,
    type: '',
    closure_uid_932951173: undefined } ]
  Should not have any console errors or warnings - fail


  1) Console tests Should not have any console errors or warnings
   Message:
     Expected 1 to be 0.
   Stacktrace:
     Error: Expected 1 to be 0.
    at /development/workspaces_public/swagger-editor/test/e2e/specs/1_console_test.js:24:32
    at Array.forEach (native)Navigation

**Comment by tyrsius** [comment]
I am also getting this error when running locally (localhost:3000), on Mac OS X El Capitan. This problem also occurs when running the app from production on a subpath (deployed to a public URL), though it does not occur when running from root in production (deployed to a public URL).

I have not been able to narrow down the cause yet,  but it seems like something is asking for a config that doesn't exist, and then making a bad XHR request.
