### ISSUE TITLE
"No additional properties allowed, but property <foo> is set"

### ISSUE THREAD

**Issue by davisford** [swagger-api/swagger-editor#676]
Hi, I'm seeing this validation error in the "Try This" form for one or more apis I've spec'd.  There is no swagger error, i.e. it says `Processed with no error` at the top, but it won't let me submit the form because of this.

I believe it has something to do with the way I've spec'd the post body that includes composition.  Here's a simple example that causes it to occur.  If you try the post in the editor, it fails with:

![screen shot 2015-10-01 at 1 35 17 pm](https://cloud.githubusercontent.com/assets/186677/10228535/52f2836a-6841-11e5-9868-36687911c794.png)

*edit* updated yaml sample with something taken straight out of the spec docs for defining composition.

```yaml
swagger: '2.0'
info:
  title: Uber API
  description: Move your app forward with the Uber API
  version: 1.0.0
host: api.uber.com
schemes:
  - https
basePath: /v1
produces:
  - application/json
  
parameters:
  exterr:
    name: exterr 
    in: body 
    required: true 
    schema:
      $ref: '#/definitions/ExtendedErrorModel'

paths:
  /error:
    parameters: 
      - $ref: '#/parameters/exterr'
    post:
      responses:
        200: 
          description: OK 
          
definitions:
  ErrorModel:
    type: object
    required:
    - message
    - code
    properties:
      message:
        type: string
      code:
        type: integer
        minimum: 100
        maximum: 600
  ExtendedErrorModel:
    type: object
    allOf:
      - $ref: '#/definitions/ErrorModel'
      - type: object
        required:
        - rootCause
        properties:
          rootCause:
            type: string
  
```

**Comment by homerlex** [comment]
I have the same problem when using composition in the model (similar to the way mohsen1 has it above)

**Comment by davisford** [comment]
@mohsen1 it seems this is a newer regression, b/c I've been using editor.swagger.io to test my specs for several weeks now, and this recently popped up.  I can't put my finger on when, but it was a week or so prior.

**Comment by pals-sj-ca** [comment]
I am facing identical problem. I was planning to test my backend without working out a test client, however, this is preventing.  Any suggestion on how to work around this?.   I thought about flattening out and removing the composition, however, I have too many levels/entities in my  composistion

**Comment by fehguy** [comment]
@pals-sj-ca can you please try testing with master, locally?

**Comment by freiit** [comment]
Maybe I have the same issue... The "allOf" seems to be the problem. Have a look: https://github.com/swagger-api/swagger-editor/issues/760

**Comment by freiit** [comment]
@fehguy I tried with the local master one min ago. Same errors.

**Comment by praveensrao** [comment]
oh! God.. after all the effort, now, I need to throw away swagger and use something else because of this bug.

**Comment by fehguy** [comment]
Huh?

**Comment by praveensrao** [comment]
@fehguy 
The problem is -- I am not able to hit the "send request" button because of this.
The whole intention of trying to use swagger was to be able to try out operations.

**Comment by fehguy** [comment]
Ok well, if you want to share details of you issue, then it's possible that we can help.  But not much can be done with your comment from the other day.

**Comment by praveensrao** [comment]
@fehguy Sorry for not explaining the issue.
What I meant to say is -- I use allOf for model extensibility, but, then, it turns out that, I wont be able to send a request using the swagger-editor because I get an error:
"No additional properties allowed, property xyz set"
I thought that this has direct relationship to the issue being discussed here and seems like there is no workaround except for trying it out in swagger-ui.
Is it correct?

**Comment by fehguy** [comment]
You need to share more information.  For example:

```yaml
swagger: '2.0'
info:
  version: "0.0.0"
  title: a demo
paths:
  /persons:
    post:
      parameters:
        - name: size
          in: query
          description: Size of array
          required: true
          type: number
          format: double
      responses:
        200:
          description: Successful response
          schema:
            title: hello
            description: it's an all of
            allOf:
              - $ref: '#/definitions/ArrayResponse'
              - $ref: '#/definitions/Person'
definitions:
  ArrayResponse:
    type: object
    properties:
      count:
        type: integer
        format: int32
  Person:
    type: object
    properties:
      name:
        type: string
```

Works just fine in the editor.

![image](https://cloud.githubusercontent.com/assets/249413/15118455/146787c0-15c1-11e6-9660-308725227991.png)

So if you're having an issue, if you don't share the details then how do you expect to get help?

**Comment by praveensrao** [comment]
@fehguy 
I have attached a snippet of the swagger yaml file.
```
swagger: '2.0'
info:
  title: xcsdfs
  version: 1.0.0
schemes:
  - http
  - https
basePath: /
consumes:
  - application/json
produces:
  - application/json
paths:
  /configuration:
    post:
      summary: Create merchant configuration
      description: Creates a merchant user in the system with the configuration provided. The configured merchant user holds credentials and config data to be used to connect to a Merchant Service Provider (MSP). <br> The response includes the UUID of the newly created merchant user.
      parameters:
        - name: merchantUser
          in: body
          required: true
          description: Merchant user configuration to interact with a Merchant Service Provider (MSP)
          schema:
            $ref: "#/definitions/MerchantUser"
      tags:
        - Configuration
      responses:
        200:
          description: The merchant user created
          schema:
            $ref: "#/definitions/MerchantUser"
        415:
          description: Unsupported media type. Valid content types are application/json and application/xml
          schema:
            $ref: "#/definitions/BaseResponse"
        500:
          description: Unexpected error / internal server error.
          schema:
            $ref: "#/definitions/BaseResponse"
definitions:
  BaseResponse:
    type: object
    properties:
      requestId:
        description: an internally generated UUID for a request
        type: string
  BaseUser:
    type: object
    properties:
      principal:
        description: A principal is some attribute that identifies a subject.
        type: string
      credential:
        description: A credential is an information that identifies the identity of a subject. It could be a password in the most basic form. The credential needs to be base-64 encoded to be used in the API.
        type: string
        format: password
      userType:
        $ref: "#/definitions/UserType"
  MerchantUser:
    description: Represents a merchant user in the system. The merchant would be authenticated based on the username password credentials supplied by means of HMAC digest calculation<p> A merchant has a reference to a PaymentProcessorServer that holds the merchant service provider configuration. <p> A merchant is active only if the MerchantUser active flag is true. <p>
    allOf:
    - $ref: "#/definitions/BaseUser"
    - type: object
      properties:
        merchantProfileId:
          description: A unique ID that represents a merchant in the merchant service provider
          type: string
  UserType:
    description: Type of the user in the system. The user can be a MERCHANT user who can interact with a Merchant Service Provider (MSP) or a SYSTEM user for administrative tasks and with the ability to create new MERCHANT and SYSTEM users.
    type: string
    default: MERCHANT
    enum:
      - MERCHANT
      - SYSTEM
```
You can see those red marks when I want to try the operation and not only that, the "send request" would be disabled.
<img width="718" alt="1462809122" src="https://cloud.githubusercontent.com/assets/12726313/15119094/cecf80fc-162c-11e6-8425-427d2e5c3c9b.png">

**Comment by fehguy** [comment]
Master handles this just fine.

![image](https://cloud.githubusercontent.com/assets/249413/15119292/10c2183e-15c5-11e6-9e87-f446198e8719.png)

**Comment by praveensrao** [comment]
@fehguy 
I am on latest master.
Were you able to click on "Send Request"?
When I hover over it, it just prevents me from clicking on it.
Sorry if I am missing something basic here.

**Comment by fehguy** [comment]
@praveensrao I see the issue.  I have slimmed down the sample below to reproduce it.  @saharj can you please look at this?

```yaml
swagger: '2.0'
info:
  title: xcsdfs
  version: 1.0.0
paths:
  /configuration:
    post:
      parameters:
        - name: testing
          in: body
          schema:
            $ref: "#/definitions/Simple"
      responses:
        200:
          description: A test
definitions:
  Simple:
    allOf:
    - type: object
      properties:
        merchantProfileId:
          type: string
```

![bug](https://cloud.githubusercontent.com/assets/249413/15119870/d32c3bfa-15c7-11e6-87b7-04b077f002af.gif)

**Comment by praveensrao** [comment]
@fehguy Thanks very much

**Comment by saharj** [comment]
This commit will fix this issue. 
0fd38f27e9f67df740f43bb849dc363188e97c03

Please build from master and try it and let me know if you still have this problem.

**Comment by praveensrao** [comment]
@saharj @fehguy 
Thanks, It did work for the straight forward use case. But, faced the same issue with a nested allOf. Can you please reopen the issue?
Example below:
```
swagger: '2.0'
info:
  title: xcsdfs
  version: 1.0.0
paths:
  /configuration:
    post:
      parameters:
        - name: testing
          in: body
          schema:
            $ref: "#/definitions/Simple"
      responses:
        200:
          description: A test
definitions:
  Simple:
    allOf:
    - type: object
      properties:
        merchantProfileId:
          $ref: "#/definitions/BaseId"
  BaseId:
    allOf:
      - type: object
        properties:
          myId:
            type: string
```

**Comment by madorb** [comment]
@saharj I'm facing the same issue as you. Nested allOf do not seem to work at all.
