### ISSUE TITLE
YAML behavior

### ISSUE THREAD

**Issue by lau235623** [swagger-api/swagger-editor#679]
While writing the API I would like to keep the summary and description readable in the YAML format as well, here is an example:

description: |
    1.0) abc &lt;br />
    2.0) bcd &lt;br />

There is nothing goes wrong while writing and save as .yaml, it looks good in both YAML and the HTML, but if I import the saved file to the editor, it randomly replaced the | (pipe) by > (greater than sign) and messed up the whole literal block (although it still looks good in HTML format)

I know the different between the pipe and the greater than sign but I don't want the editor do the replacement for me, it is kinda annoying.

I tried every Editor settings in the setting tab but no pattern found, may I know where can I disable this feature? I am using the lastest released version

Thanks!

**Comment by mohsen1** [comment]
Do you import YAML or JSON؟

**Comment by lau235623** [comment]
Dear sir,
I was importing the .YAML

**Comment by mohsen1** [comment]
I can't reproduce this. Try pasting this YAML in a file and importing it:

```
swagger: '2.0'
info:
  version: 0.0.0
  title: |
    Simple API
    Two
paths:
  /:
    get:
      responses:
        '200':
          description: OK
```

**Comment by lau235623** [comment]
I can finally reproduce the problem
It occurs when one of the sentence is over 80 characters
I tried to setup the margin and wrap mode but it didn't help

**Comment by mohsen1** [comment]
It is just line wrapping. Try making the editor pane wider

**Comment by lau235623** [comment]
Dear sir,

I tried and it didn't help, I was using Chrome to test it

**Comment by mohsen1** [comment]
I can't reproduce this. We do nothing to YAML files that can change structure of the file during import.

**Comment by lau235623** [comment]
It didn't change till the import action, will attach an example asap

**Comment by lau235623** [comment]
swagger: '2.0'
info:
  title: Uber API
  version: 1.0.0
host: api.uber.com
paths:
  /products:
    get:
      summary: Product Types
      description: |
        The Products endpoint returns information about the *Uber* products <br />
        offered at a given location. The response includes the display name <br />
        and other details about each product, and lists the products in the <br />
        proper display order.
      tags:
        - Products
      responses:
        '200':
          description: An array of products
          schema:
            type: integer

This will do the trick, the description's pipe will be replaced by > after import

**Comment by mohsen1** [comment]
Why do you have `<br />` there?

**Comment by lau235623** [comment]
Because new line with pipe require double new line in YAML, it is ugly while making a large document...

**Comment by mohsen1** [comment]
It's not YAML, it's markdown behavior to require double line breaks for paragraph breaks. It's an expected behavior. We are using *marked* module for rendering markdown. It this behavior is not making sense ask them.

**Comment by lau235623** [comment]
So.. is that means if I wanna break the line in html form, I either use > for <br /> or double line break for a new line? I really want to not use it since it works nicer even if I just post the plain saved yaml into the editor (avoided the import action)

**Comment by mohsen1** [comment]
That's right. But the fact that your YAML changes when you import it is weird. Maybe it's a bug. I'll look later.

**Comment by lau235623** [comment]
Thanks sir!

**Comment by lau235623** [comment]
Hi Sir, may I know how is the process and some hints?
