### ISSUE TITLE
Swagger-editor: Using items without type: array still validated ok

### ISSUE THREAD

**Issue by hpoints** [swagger-api/swagger-editor#681]
My yaml validated ok, but then I could not generate any client/server artifacts. Had to manually find the error. My error was using items in some places where schema should have been used.

**Comment by mohsen1** [comment]
A JSON Schema like this: `{"type": "array"}` is describing an array with *any* element. It is valid JSON Schema. This is a problem in swagger-codegen where it doesn't like arrays without `items` schema.

**Comment by mohsen1** [comment]
This issue was moved to swagger-api/swagger-codegen#1344
