### ISSUE TITLE
Markdown in schema descriptions

### ISSUE THREAD

**Issue by henkosch** [swagger-api/swagger-editor#682]
GFM in schema descriptions should be supported according to the specs, but it is displayed as plain text. HTML works, but it is much easier to write gfm, so it would be nice to have that.
http://swagger.io/specification/#schemaObject

Example:
```
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /:
    get:
      description: GFM is supported here. **bold** *italic*
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/TestType"
definitions:
  TestType:
    type: object
    description: GFM should be supported here. **bold** *italic*
```

![gfm](https://cloud.githubusercontent.com/assets/908091/10325488/0bfcf53a-6c92-11e5-842c-dc9c6e79e552.PNG)

**Comment by mohsen1** [comment]
For rendering JSON Schema object we are using [json-schema-view-js](https://github.com/mohsen1/json-schema-view-js) lib which does not support Markdown. Swagger Editor can not change behavior of this lib and this behavior is not something common to add to the lib.

**Comment by michaelkourlas** [comment]
I'm experiencing this issue as well.

I see that the current rendering library doesn't support GFM, but it seems like it might be worth switching to an alternate rendering library then, seeing as this is a question of spec compliance.

**Comment by rdooda** [comment]
how to change the description size in swagger.
