### ISSUE TITLE
Loading spec from localStorage doesn't trigger validation until user types

### ISSUE THREAD

**Issue by xuanli09** [swagger-api/swagger-editor#685]
If you paste the following schema in the editor (editor.swagger.io):

````
swagger: '2.0'
info:
  version: 0.0
  title: Simple API
paths:
  /:
    get:
      responses:
        '200':
          description: OK
````

The validation successfully catches the error on the info.version field.

However, if you refresh the page the validator fails to catch the error until you start typing. This seems to happen for all types of errors.

It seems like the Sway Worker is returning no errors in this case when buildDocs is called.

**Comment by saharj** [comment]
I can not reproduce this. Could you please try again and let me know?

**Comment by xuanli09** [comment]
Looks like this is not a problem anymore, and I can't reproduce with latest. I will close this.
