### ISSUE TITLE
securityDefinitions Support on YAML

### ISSUE THREAD

**Issue by jayonsoftware** [swagger-api/swagger-editor#688]
securityDefinitions:
  api_key:
    type: apiKey
    in: header
    name: Authorization

The above code does not work on the UI Editor. I get the pop up asking for the API key but I do not see the API key getting added to the header.

**Comment by chrisdudley** [comment]
If youre in IE, try a different browser. I think there is a known defect with ngStorage in IE.

**Comment by jayonsoftware** [comment]
Sorry I was not clear on this. 

Here is part of my YAML

~~~~```YAML
security:
  - internalApiKey: []
securityDefinitions:
  internalApiKey:
    type: apiKey
    in: header
    name: Autherization
paths:
  /Ok:
    post:
      description: Simple OK Statment
      operationId: OK
      security:
      - internalApiKey: []
      parameters:
        - in: body
          name: body
          description: Pet object that needs to be added to the store
          required: true
          schema:
            $ref: '#/definitions/Ok'
      responses:
~~~~


When I use the Swagger Editor, the out going request does not contain the header, may be my YAML is wrong ?

Jay

**Comment by jayonsoftware** [comment]
I got this working, it was the same as https://github.com/swagger-api/swagger-editor/issues/329
