### ISSUE TITLE
Start swagger-editor on a remote machine

### ISSUE THREAD

**Issue by MarcinKwiatkowski1988** [swagger-api/swagger-editor#695]
Good morning to all, 

I'm trying to run your swagger-editor on a remote machine (for example 54.54.54.54:8080). The "npm start" works fine and I arrive to the end with :
<code>Running "connect:dist:keepalive" (connect) task</code>
<code>Waiting forever...</code>
<code>Started connect web server on http://54.54.54.54:8080</code>
just as I run it locally, but when I go on browser to the following ip, I'm not seeing the swagger-editor. It's like he can't start the server (like he does on a local machine opening the localhost:8080). It is a bug? Is there any work-around?

Waiting for your reply,
Regards

Marcin

**Comment by saharj** [comment]
Hi, 

That's probably a network issue. I'm not sure if it's related to Swagger Editor itself. If you are still experiencing this issue, please let us know.

**Comment by mukteshkrmishra** [comment]
Hi, I am still experiencing the same issue.
