### ISSUE TITLE
swagger editor shows error "Unable to identify the Swagger version or the Swagger version is unsupported" when pasting the json generated by swagger core. 

### ISSUE THREAD

**Issue by anishmanandhar** [swagger-api/swagger-editor#699]
Dependency used 
<dependency>
    <groupId>com.wordnik</groupId>
    <artifactId>swagger-jaxrs_2.10</artifactId>
    <version>1.3.1</version>
    <scope>compile</scope>
</dependency>

Swagger json : 

{
"apiVersion": "1.0.0",
"swaggerVersion": "1.2",
"basePath": "http://localhost:8080/java-ee-7-sample-project/app",
"resourcePath": "/employee",
"produces": [
"application/json"
],
"consumes": [
"application/json"
],
"apis": [
{
"path": "/employee",
"operations": [
{
"method": "GET",
"summary": "Say Hello World with swagger and java EE 7",
"notes": "Test notes",
"type": "void",
"nickname": "sayHello",
"produces": [
"application/json"
],
"parameters": [],
"responseMessages": [
{
"code": 200,
"message": "OK"
},
{
"code": 500,
"message": "Internal server error"
}
]
}
]
},
{
"path": "/employee{id}",
"operations": [
{
"method": "GET",
"summary": "find employee by id ",
"notes": "Test notes",
"type": "void",
"nickname": "findEmployee",
"produces": [
"application/json"
],
"parameters": [
{
"name": "id",
"description": "Unique identifier to find employee",
"required": true,
"type": "integer",
"format": "int64",
"paramType": "path"
}
],
"responseMessages": [
{
"code": 200,
"message": "OK"
},
{
"code": 500,
"message": "Internal server error"
}
]
}
]
}
]
}

**Comment by saharj** [comment]
Swagger Editor only supports Swagger version 2.
