### ISSUE TITLE
Line breaks not working correctly in Swagger Editor Preview pane.

### ISSUE THREAD

**Issue by mdspielman** [swagger-api/swagger-editor#700]
Raising this as an issue based on conversation on the mailing list.

I am trying to add markdown to my Operation Object Descriptions Fields. So I have played with it in editor.swagger.io and found the following observation. I seem to need two blank lines in order to get a new paragraph in the rendered docs.

I.e. this works:

 ```
description: 
        First paragraph of description.
        
        
        Second paragraph of description
```

This renders as:
```
        First paragraph of description.
        
        Second paragraph of description
```

But this description does not render as I expect:

``` 
description: 
        First paragraph of description.

        Second paragraph of description
```

In the UI, this renders as: (line break is missing)

```
First paragraph of description. Second paragraph of description
```

I believe this is an issue with the editor tool. I also tried adding `<br>` to force the line break but that also did not work in the editor preview pane.

Thanks
Mark

**Comment by carolynnvu** [comment]
Any updates on this?

**Comment by saharj** [comment]
For multiline strings in YAML you need to use a pipe (`|`).
Here is the example:
```
description: |
            First paragraph of description.
            
            Second paragraph of description
```
