### ISSUE TITLE
JSON Schema OneOf not appearing through YAML UI

### ISSUE THREAD

**Issue by stevendearborn** [swagger-api/swagger-editor#701]
I am trying to specify the OAuth standard via YAML.  The OAuth 2.0 token endpoint can take as input different fields based upon the grant_type.  I am trying to model this using JSON schema.

Here is my example I know that grant_type is duplicated because I am not sure where it is best to be defined.  Since the sub-schema to choose is based upon the grant_type, I believe that it should be a part of the oneOf clause.

I just want to specify that the YAML editor user should select the grant_type, and then the appropriate input fields are shown for the end-user to enter.

Here is a snippet of my example:
```yaml
definitions:
  TokenRequest:
    type: object
    properties:
      grant_type:
        description: The type of authorization being requested.
        type: string
        enum:
          - client_credentials
          - password
          - refresh_token
          - code
          - implicit
      oneOf:
        grant_type:
          type: string
          enum:
            - client_credentials
            - password
            - refresh_token
            - code
            - implicit
        $ref: '#/definitions/ClientCredentials'
        $ref: '#/definitions/AuthorizationCredentials'
        $ref: '#/definitions/RefreshCredentials'
        $ref: '#/definitions/ResourceOwnerPasswordCredentials'
      scope:
        type: string
    required:
      - grant_type
```
Thanks.

**Comment by webron** [comment]
@stevendearborn - `oneOf` is not supported by Swagger.

However, for specifying OAuth2, you shouldn't need it as there's an internal way of specifying security access using OAuth2. Check out https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#security-scheme-object for further details.

**Comment by stevendearborn** [comment]
Thanks.  Of course oneOf is supported by JSON schema and so it is supported by the YAML editor, however there is an incorrect interpretation of it as rendered in the swagger editor.  I need to define the OAuth endpoints so that they can become implemented, including grants management and token revocation which are not a part of the present version of the OAuth 2.0 standard.  I am attempting to build a "complete" interface specification for OAuth provider.  The security setting which you mentioned allow you to refer to the endpoints but do not define the input and output parameters, errors and options providers have to implement these standards.

oneOf will be needed for other REST APIs where the input or output JSON structure varies according to something similar to grant_type in OAuth, or some other variable or condition.

**Comment by webron** [comment]
If you paste that snippet into the editor you get an error. The JSON schema used for validation does not allow the usage of `oneOf` (because, as mentioned, it is not supported by the spec). Furthermore, as far as I know, that's not the right construct usage for `oneOf` and what you're actually doing there is defining a property called `oneOf` which I assume is not your intent. I can suggest a more accurate usage of `oneOf` for your case, but that will still not work with Swagger nor the editor.

However, not all is lost. Since you have a `type` property that differentiates between the object options, you can use that as a discriminator and use inheritance to represent the different types. Please take a look at https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#composition-and-inheritance-polymorphism and the following samples for reference.

**Comment by stevendearborn** [comment]
Thanks.  I will have a look at the example. BTW the Swagger YAML editor does not error on the oneOf structure: there are no parse errors displayed; it just does not render the variable structure according to the discriminator value input.  I did not paste the entire snippet since it is too long.  I will try to implement using the examples you cited to see if that works with the Swagger editor UI.

**Comment by fehguy** [comment]
Ok @stevendearborn as @webron said, `oneOf` is simply not supported and if it does, _that_ is a bug.  However we are in the process of updating the specification and this is one of the more requested features.

So unless we wan't to rename this ticket as "swagger editor should not support oneOf", I'm going to close this.  Please jump in the [spec rep](https://github.com/OAI/OpenAPI-Specification) and add your 0.02 bitcoin...
