### ISSUE TITLE
Definitions with property name 'default'  cause 'a.indexOf is not a function' error

### ISSUE THREAD

**Issue by kiftio** [swagger-api/swagger-editor#705]
Properties named default in definitions result in the following error. 

Object
message:  "a.indexOf is not a function"
code:  "ERROR_THROWN_BY_SWAY_CODE:undefined"
level: 900
type:  "Unknown Error"
description:  "a.indexOf is not a function"

---------------------------------------------
E.g. with the following yaml:
```
swagger: '2.0'
info:
  version: 0.0.0
  title: 'entities'
paths:
  /entities:
    get:
      description: |
        Some description
      parameters:
        - name: entities
          in: body
          description: entities
          required: true
          schema:
            type: array
            $ref: '#/definitions/entity'
      responses:
        '200':
          description: Successful response

definitions:
  entity:
    properties:
      id:
        type: string
        description: Unique identifier representing an entity
      **default**:
        type: string
        description: true or false.
```
---------------------------------------------

Changing the name from default allows the document to render correctly.

I'm trying to document an xml request body which is something like:

\<entity\>
&nbsp;&nbsp;&nbsp;&nbsp;\<id\>123\</id\>
&nbsp;&nbsp;&nbsp;&nbsp;\<default\>true\</default\>
\</entity\>

Perhaps some form of escaping is needed?

**Comment by webron** [comment]
@whitlockjc, can you have a look please?

**Comment by whitlockjc** [comment]
This has already been fixed in the last version of sway.  Has swagger-editor updated?

**Comment by emanov** [comment]
Faced with this problem about 1-2 month ago.

**Comment by jamesbennet** [comment]
Hello!

 

New message, please read <http://phanmemoto.com/indeed.php?al>

 

james@james-bennet.com

**Comment by saharj** [comment]
I don't see any issue here with the `default`. Do you still have it?

**Comment by emanov** [comment]
Seems to be it has been fixed.

**Comment by kiftio** [comment]
yep, looks fixed to me too, thanks.
