### ISSUE TITLE
Error on fresh install of swagger editor "Unknown Error a.getLastWarnings is not a function"

### ISSUE THREAD

**Issue by ahouchens** [swagger-api/swagger-editor#708]
Inside of the swagger editor, the error is very visible and it appears the auto doc generation on the right is not working:

"Unknown Error a.getLastWarnings is not a function"

**Comment by ebox86** [comment]
yea getting the same thing. Is this a bug or a problem with the installation?

**Comment by chrisdudley** [comment]
Likely related to https://github.com/swagger-api/swagger-editor/pull/707

**Comment by ahouchens** [comment]
Yeah it's a similar issue to #707 if not the same issue. I fixed my issue by not following the instructions on the swagger website and instead following the installation instructions on the README.md.

**Comment by rajesh38** [comment]
thanx @ahouchens 
followed http-server approach and worked

**Comment by shehi** [comment]
Same here. I just unzipped the archive to some subfolder within my project's web folder, and accessed as normal with something like ```http://my-dev-domain/swagger-editor```. Works fine.

**Comment by namkee** [comment]
i've got same issue. i just clone and run npm start
there is no failure during npm and bower install

i also change branch to v2.9.8 but same message is occured

**Comment by ponelat** [comment]
Its the sway-worker dependency.. to quickly get going. Force bower to use a newer version. I'm sure there'll be an update to fix the dependency? @mohsen1 ?

so
`bower install sway-worker=1.8.0`

**Comment by saugatc** [comment]
Is there a work-around available for this issue in Windows 7 (64 bit)

Unknown Error
api.getLastWarnings is not a function

**Comment by lucapalano** [comment]
There is a pull request for this error (https://github.com/swagger-api/swagger-editor/pull/707). I applied the proposed solution (https://github.com/beenetwork/swagger-editor/commit/a86df27785b6944118b7b69037186e3133ba46b3) to my local copy and it seems to work well (I didn't perform accurate tests). However, it failed to pass CI tests (https://travis-ci.org/swagger-api/swagger-editor/jobs/89501565).

**Comment by fehguy** [comment]
thanks, I've merged #707 (I guess @mohsen1 is on vacation :) )
