### ISSUE TITLE
Editor client generate C# dependency on RestSharp only?

### ISSUE THREAD

**Issue by chitankensuru** [swagger-api/swagger-editor#712]
Not sure if it's already possible. Currently the C# client export has a dependency on RestSharp. I am working on a Xamarin PCL project and unfortunately RestSharp has no PCL implementation.

Is it possible from the editor to define library dependencies? For example that instead of RestSharp it can be generated with use of the Microsoft.Net.Http library or other PCL supported libraries?

**Comment by webron** [comment]
The editor uses the generic templates we have at the [swagger-codegen](https://github.com/swagger-api/swagger-codegen) project. You can easily create your own templates based on the documentation in that project, and if you require any help with that, you can open a ticket directly on swagger-codegen.

**Comment by chitankensuru** [comment]
Ah clear. Thanks

**Comment by wing328** [comment]
@chitankensuru currently C# client does not support HTTP libraries other than RestSharp. Technically it should be possible to do so as we've done it with the Java API client, which supports Jersey1.x, Jersey2.x, okhttp, retrofit, retrofit2.

Please open a ticket [here](https://github.com/swagger-api/swagger-codegen/issues) for tracking purpose.
