### ISSUE TITLE
Description re-write - Sanitation issue?

### ISSUE THREAD

**Issue by koxon** [swagger-api/swagger-editor#718]
Hi,

First, great tool thank you! I'd give you my money if you had a private space to host my API documentation.

In swaggerhub, the editor re-write my description when I save.
It adds newlines, replace | by > and mess up the text. It's not for all descriptions either. Some remain the same. If I use a string "" and put \n in it, I sometimes also see \\n like it has been double escaped.

I think there is an issue with the input validation and sanitation.

See my screenshot. it replaced | by > and has been adding a new line for every save.
![image](https://cloud.githubusercontent.com/assets/3182882/11229306/202ea328-8d62-11e5-8071-27b4e6ea06c4.png)

I don't see anyone reporting this issue though, so I wonder if I'm doing something wrong here?

thanks
koxon

**Comment by koxon** [comment]
I reformatted using | instead of >, I saved and reloaded and now it transformed it in a string "" ...

![image](https://cloud.githubusercontent.com/assets/3182882/11229412/fb089af8-8d62-11e5-87f6-750b457cc180.png)

**Comment by saharj** [comment]
Glad you figured it out.
