### ISSUE TITLE
Using external schema 

### ISSUE THREAD

**Issue by HEDIDIN** [swagger-api/swagger-editor#721]
Can I use an external schema for a $ref? 
I am creating a Swagger that is going ti be used in Healthcare and I need to list medications. There are over 1000 codes that I need to include in an enum

http://hl7.org/fhir/ValueSet/medication-codes

schema:
            $ref: 'http://hl7.org/fhir/ValueSet/medication-codes'

**Comment by webron** [comment]
You certainly can. Keep in mind the external schema has to be a Swagger Schema Object, which is slightly different than pure JSON Schema. For more information, refer to the [Schema Object](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#schemaObject).

**Comment by fehguy** [comment]
Please reopen if you have questions
