### ISSUE TITLE
Same object definition, different required properties

### ISSUE THREAD

**Issue by JoeShi** [swagger-api/swagger-editor#722]
I have the following object definition. When a make a `GET` or `POST` request, the object is the same, but the required properties are different. For example, I want to specify the `email` is a required properties in `POST`, and in `GET` the id is a required properties. It is anyway to achieve this without creating two different objects?

    User:
    type: object
    properties:
      id:
        type: string
        description: Identifier of the user
      email:
        type: string
        format: email
        description: when creating an user, this cannot be null
      phone:
        type: string
        description: phone number
      displayName:
        type: string
        description: 'display name, nick name'
      gender:
        type: string
        enum:
          - male
          - female
        default: male
        description: gender
      birthday:
        type: string
        format: date
        description: birthday
      avatar:
        type: string
        format: url
        description: 'If the user does not provide an avatar, the server will return the default one.'

When i create a user, I make a `post` request. and attach the `User` object in body

    '/users':
    post:
      tags:
        - Users
      summary: create an user account
      description: create an user account
      parameters:
        - in: body
          name: body
          required: true
          description: only support email registration now. 
          schema:
            $ref: "#/definitions/User"
          required: true
      description: use email or phone to register.
      responses:
        200:
          description: OK

When i get the user profile, I make a `GET` request and the following is my definition. 

    '/users/{userId}':
    get:
      tags:
        - Users
      summary: Get the user's profile
      description: Get the user's profile. The special value "me" can be used to indicate the authenticated user.
      security:
        - accessToken: []
      parameters:
        - in: path
          name: userId
          description: ID of the user. 
          type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/User"

**Comment by webron** [comment]
You'd have to create different models. You can still take the common properties and use `allOf` to include them in an extending object to reduce repetition, but still you'd need separate models.

**Comment by JoeShi** [comment]
Thank you @webron.

**Comment by Odenson** [comment]
Hi @webron, so is that the intent of the definition in swagger to have version of a model based on operation? 
IE: I have a clientRecord, and ID is mandatory when GET but not when POST.  In this this case I need a base "Client" definition without ID and then include another "GETClient" definition with ID as required?

example of the API is here : [https://swaggerhub.com/api/Gary/createClientRecord/1.0.3](url)

**Comment by sms81** [comment]
Hi @webron, but using  `allOf ` as you suggested will lead to a ugly structure appearing the keyword `allOf` inside it, for example:

```
swagger: "2.0"

info:
  title: "Cat API"
  version: 1.0.0

paths:
  /cats/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: integer
    get:
      responses:
        200:
          description: Return a cat
          schema:
            $ref: "#/definitions/GetCat"
    put:
      parameters:
        - name: cat
          in: body
          required: true
          schema:
            $ref: "#/definitions/PutCat"
      responses:
        204:
          description: Cat edited

definitions:
  Cat:
    type: object
    properties:
      name:
        type: string
  GetCat:
    allOf:
      - $ref: "#/definitions/Cat"
    properties:
      id:
        type: integer
    
  GetCat2:
    type: object
    required: [name]
    properties:
      id:
        type: integer
      name:
        type: string
        
  
  PutCat:
    type: object
    required:
      - name
    properties:
      $ref: "#/definitions/Cat/properties"
```

I want The structure of GetCat to appear normal as the structure of GetCat2 instead of appearing the keyword `allOf` inside the strucutre

**Comment by webron** [comment]
@sms81 - I can be blamed for a lot of things, but not for JSON Schema's limitations.

**Comment by ironsmile** [comment]
@webron , I am about to resurrect and old issue here but it seems I don't understand how to follow your advice in a previous comment here:

> You'd have to create different models. You can still take the common properties and use allOf to > include them in an extending object to reduce repetition, but still you'd need separate models.

I've tried doing just that with this example:

```yml
swagger: '2.0'
info:
  description: Example
  title: Example
  version: '1.0.0'
consumes:
  - application/json
produces:
  - application/json
paths: {}
definitions:
  InputWithRequired:
    allOf:
      - $ref: '#/definitions/Input'
      - required:
        - id
        - number
  Input:
    type: object
    properties:
      id:
        type: number
        example: 53
      number:
        type: string
        example: "0000000024"
```

But the swagger validator ends up showing the following errors:

```
API Errors:

  #/definitions/InputWithRequired/allOf/1/required/0: Definition requires property but it is not defined: id
  #/definitions/InputWithRequired/allOf/1/required/1: Definition requires property but it is not defined: number
```

Is this a misunderstanding on my part or is it a bug in the swagger validator? As you can see the properties `number` and `id` are clearly defined.

**Comment by darrelmiller** [comment]
@ironsmile  JSON Schema's rules say that in order to pass validation, your input must pass "all of" the schemas listed in an allOf array.

In your example, one of the schemas is:

```
required:
  - id
  - number
```

When you evaluate this schema in isolation (which is what JSON Schema does) you can see it makes no sense.  You can't make properties required if they haven't been defined.

**Comment by webron** [comment]
@ironsmile - I miss Sofia! Haven't been there in ages.

The way `allOf` works is that it defines an array of schemas against "all of "which an input would be validated with. However, this does not mean that the schemas are merged, but rather that each one of them is checked individually. That means that the `required` schema stands alone... and it doesn't like that because those properties are not defined.

Of course, @darrelmiller just posted a similar answer while I was typing this one, but I'm still going to post it.

**Comment by darrelmiller** [comment]
Too slow!

**Comment by webron** [comment]
It's because I miss Sofia so much.

**Comment by ironsmile** [comment]
I see, thank you guys, both! @webron, Sofia is especially sunny and beautiful today so I do understand you.

It seems the my misunderstanding stems from the fact that I do not think in terms of JSON Schema. And in the end, is there a way to achieve what I am trying to do? Short of copying the whole model one more time but with included `required` properties. My real schema models have dozens of properties and supporting nearly identical versions of them with different requirements would border the impossible.

**Comment by darrelmiller** [comment]
@ironsmile Just for a moment, can you ignore everything I said and go and paste your example into Swagger editor https://editor.swagger.io/  I'm not seeing any errors and it appears to be doing what you want.

**Comment by darrelmiller** [comment]
@ironsmile The JSON schema folks seem to be saying what you were trying to do should work.  However, try using this instead:

```
swagger: '2.0'
info:
  description: Example
  title: Example
  version: '1.0.0'
consumes:
  - application/json
produces:
  - application/json
paths: {}
definitions:
  InputWithRequired:
    required:
      - id
      - number
    allOf:
      - $ref: '#/definitions/Input'
  Input:
    type: object
    properties:
      id:
        type: number
        example: 53
      number:
        type: string
        example: "0000000024"
```

**Comment by ironsmile** [comment]
Thanks! It does work and you saved me quite a lot of effort. I've never thought to arrange it this way :D Hope this is useful for others as well.

**Comment by vearutop** [comment]
@ironsmile out of curiosity, what is `swagger-tool` you were talking about?

**Comment by ironsmile** [comment]
This one: https://www.npmjs.com/package/swagger-tools

**Comment by alexandruluca** [comment]
As far as I can see, it is an issue with swagger-tools itself. The above example does not work with version 0.10.4 of swagger-tools

**Comment by mirichan** [comment]
I just arrived at the same conclusion (`swagger-tools` being at fault) and then found this thread. Hope this helps someone else along the line 😂
