### ISSUE TITLE
Golang Support

### ISSUE THREAD

**Issue by sebastianmacias** [swagger-api/swagger-editor#725]
Currently there isn't Golang support neither for server generation nor client generation. Is this a planned feature?

**Comment by wing328** [comment]
For Golang server and client generation, please try https://github.com/go-swagger/go-swagger.

**Comment by wing328** [comment]
FYI. swagger editor leverages swagger-codegen (https://github.com/swagger-api/swagger-codegen) via https://generator.swagger.io to generate API client or server stub.

**Comment by fehguy** [comment]
follow here:  https://github.com/swagger-api/swagger-codegen/issues/325

**Comment by sebastianmacias** [comment]
@fehguy thank you!
