### ISSUE TITLE
Missing Keybinding Files

### ISSUE THREAD

**Issue by joshuazsprague** [swagger-api/swagger-editor#726]
When attempting to change the keybindings, observe the following in the developer console.
GET http://localhost:1013/swagger-editor/dist/bower_components/ace-builds/src-noconflict/keybinding-emacs.js 

When searching through the source, I find these keybindings files in other directories.  After copying to the directory that is apparently expected, then receive the following in the developer console.
misspelled option "foldStyle"

Ultimately - not able to switch to different keybindings.

**Comment by saharj** [comment]
Fixed #780
