### ISSUE TITLE
Encoding error when generate Java client 

### ISSUE THREAD

**Issue by mbamouni** [swagger-api/swagger-editor#727]
I have an enum in my swagger editor that contains "Unité d'appui", when i try to generate a java client , the value "Unité d'appui" was converted to "Unité d& # 3 9 ;appui" with special XML character & # 3 9 ;. When generating python client, i have no problem.

I hope somebody can help me.

Michel

**Comment by xhh** [comment]
You mean it is converted to`Unité d&#39;appui`, right?
I can reproduce the issue, will submit a PR for it.

**Comment by mbamouni** [comment]
Yes, that's right.

**Comment by xhh** [comment]
btw, it's an issue of the swagger-codegen project, which is used by swagger-editor. I'll fix the issue at swagger-codegen, and the fix would be deployed to swagger-editor some time after that.
