### ISSUE TITLE
API version format is too strict

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-editor#733]
_From @0x62ash on November 29, 2015 21:3_

I don't see any limitation for version from spec:

> `version`	`string`	**Required** Provides the version of the application API (not to be confused with the specification version).

But I get error for `version: 0.1` :

>  Swagger Error
> A semantic version number of the API.
> Jump to line 10

_Copied from original issue: swagger-api/swagger-spec#517_

**Comment by webron** [comment]
You're getting that error *where*?

**Comment by webron** [comment]
_From @0x62ash on November 30, 2015 23:56_

Here - http://editor.swagger.io/#/

**Comment by webron** [comment]
In that case...

**Comment by saharj** [comment]
The thing is that in Swagger schema, the type of `version` has to be a `string`, and when you put `0.1` in front of `version`, YAML sees it as a number. That's why you get an error.
The second `.` makes it clear for YAML that the value of `version` is not a number.
