### ISSUE TITLE
Security warning for basic auth

### ISSUE THREAD

**Issue by DarkSorrow** [swagger-api/swagger-editor#734]
Hello,

I'm having a warning when my authentication is set as the following:
```
"securityDefinitions":{  
        "basic":{  
            "type":"basic",
            "description":"blabal"
        }
    }
```
According to the documentation tho, for the basic authentication this is the only field i need, here is the link: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#securityDefinitionsObject
If i add a name in that field then it goes away but showing it on the editor after. Is there something i'm missing or i'm not reading the correct document?

**Comment by webron** [comment]
What's the warning you're getting?

**Comment by DarkSorrow** [comment]
I get this
```
⚠ Swagger Warning
Definition is not used: #/securityDefinitions/basic
```

**Comment by chrisdudley** [comment]
That’s simply saying that you’ve defined a security definition that you’re
not using.
If you created a security section and then listed it as a requirement then
it would go away, and you’d actually require basic authentication to use
your operations.
Currently you’ve not actually said that any operations require that
security definition.
The distinction between defining something, and requiring it.

**Comment by DarkSorrow** [comment]
Ok sorry, i was using swashbuckle to generate my swagger spec and it seems i had to add something to make it work. Strangely at one point when i added a name to the definition the warning was gone and i had nothing but maybe it was a bug with my browser.

I looked at some other post about adding securtiy definition in different path and now i have no warning and errors, sorry for that error and thanks for taking the time to answer me :)
