### ISSUE TITLE
Pasting the same content triggers empty document error

### ISSUE THREAD

**Issue by xuanli09** [swagger-api/swagger-editor#741]
If you copy and paste over the same YAML in the editor, it will trigger an empty document error. It seems like the $rootscope.editorValue is empty when onAceChanged is called after a paste.

This behavior cycles between correct and incorrect when you copy/paste over the content.

**Comment by ajainy** [comment]
Stuck with same error. Any workarounds?

**Comment by Shaun1** [comment]
seeing the same thing

**Comment by dkiitian** [comment]
stuck with same error any update ?

**Comment by noizbuster** [comment]
For me adding empty line to last works

**Comment by saharj** [comment]
I can not reproduce this issue anymore. Does anyone still get the error?

**Comment by saharj** [comment]
Closing this issue due to no response.

**Comment by Herst** [comment]
I can reproduce it:When I'm doing <kbd>Ctrl-A</kbd> and <kbd>Ctrl-V</kbd> in quick succession I am getting it every second time.

**Comment by saharj** [comment]
Thank you @Herst , I am able to reproduce it now. The key is to press `Ctrl-A` and `Ctrl-V` keys very quickly.
I'll look into this issue.

**Comment by brinduc** [comment]
Yes, I can confirm I can reproduce it too, installed the Plugin today.

**Comment by ejfrancis** [comment]
I'm seeing this as well when I paste in the same document

**Comment by karishay** [comment]
Any updates or workarounds? I'm having this issue too.

**Comment by webron** [comment]
This should no longer be an issue in 3.X.
