### ISSUE TITLE
Error thrown using patternProperties

### ISSUE THREAD

**Issue by mm-gmbd** [swagger-api/swagger-editor#744]
The swagger editor throws an error when using patternProperties (at least in a response schema):

The YAML for a response:

    'responses':
        '200':
            'description': 'A description'
            'schema':
                'type': 'object'
                'patternProperties':
                    '[a-z]':
                        'type': 'number'

Swagger editor throws an error that takes some digging to eventually find:

    code: OBJECT_ADDITIONAL_PROPERTIES
    message: Additional properties not allowed: patternProperties

The moment I change `patternProperties` to just `properties`, the error goes away.

I assume this is because the current Swagger 2.0 specification only supports a subset of JSON Schema draft 4 as mentioned [here](https://github.com/swagger-api/swagger-spec/issues/333) -- is this the case?

**Comment by mm-gmbd** [comment]
Preemptively, if that *is* the case, maybe there could be an option for "relaxed" validation where some validation measured are not imposed (i.e. the use of patternProperties or other [non-included JSON Schema keywords](https://github.com/swagger-api/swagger-spec/issues/333)), and then one could move onto the list of "more important" validation failures.

**Comment by webron** [comment]
You are correct that the error is due to it not being supported. While it doesn't make sense for us to not enforce the validations, we do have plans to make the experience easier on the users.

**Comment by saharj** [comment]
As you linked, this is an issue or feature request for Swagger schema.

**Comment by coltonone20** [comment]
Never understood this - There are jsonschema v4 validation modules for javascript which support the full specification.  Why wouldn't swagger-editor use one of those instead of only supporting a subset of the spec?

**Comment by webron** [comment]
Because the spec itself supports only a subset of JSON Schema. It's got nothing to do with swagger-editor.

**Comment by coltonone20** [comment]
@webron That makes total sense, thanks
