### ISSUE TITLE
Cannot import files containing errors

### ISSUE THREAD

**Issue by crystalfp** [swagger-api/swagger-editor#747]
In a parameters section I mistakenly wrote `name: myparam` instead of `myparam:`
When I try to `import file` in the `import a file` dialog I cannot click the `import` button (the no-entry pointer). This makes debugging difficult.
My workaround is to paste the file content in the editor. This way the editor immediately spots the error.
Is it possible to let the editor load the file even if it contains errors? I don't know if this qualifies as a bug or as a feature request.
Thanks!
mario

**Comment by saharj** [comment]
That's an invalid YAML, I'm not sure if we should allow importing that.

**Comment by crystalfp** [comment]
Good morning!
I know it is invalid YAML. I was only trying to find a way to debug my 
swagger file and locate the error. If the file is written inside the 
editor, then the errors are immediately highlighted. But I use Sublime 
text also because the comments are not stripped away as happens in the 
editor (see #697) so I'm trying to find an equivalent debugger.
Thanks!
		mario


On 06-Jan-16 17:52, Sahar Jafari wrote:
> That's an invalid YAML, I'm not sure if we should allow importing that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swagger-api/swagger-editor/issues/747#issuecomment-169385902>.
>

-- 
Ing. Mario Valle
Swiss National Supercomputing Centre (CSCS)
v. Trevano 131, 6900 Lugano, Switzerland
Tel: +41 (91) 610.82.60

**Comment by mohsen1** [comment]
You can use Sway node module for validating your spec.
