### ISSUE TITLE
Editor needs multiple loads to change content

### ISSUE THREAD

**Issue by crystalfp** [swagger-api/swagger-editor#748]
I have loaded my long swagger.yaml file (attached, I hope). If I correct the file in a text editor and issue an `Import file` again, almost always the content does not change.
What I have to do is to `Open Example` and load an example. Again I have to load it multiple times till both panels show the example and not my file. Then I load again my file and this time the new version is loaded.
I'm working inside Chrome latest version on Windows 7 64bits.
Thanks for looking!
mario

**Comment by crystalfp** [comment]
[swagger.txt](https://github.com/swagger-api/swagger-editor/files/66212/swagger.txt)

**Comment by saharj** [comment]
Would you please check it and let us know if you still have this issue?
