### ISSUE TITLE
Not using correct request method in swagger Editor UI

### ISSUE THREAD

**Issue by nazarhussain** [swagger-api/swagger-editor#752]
Hello,

I developed an API, for which a route is using `post` request method. It is showing right method when building request method: 
<img src="https://cloud.githubusercontent.com/assets/112468/11929606/76f9282a-a7fe-11e5-9fc4-3cd87dd3d3c0.png" width="300">

But when we click on send request button it send with wrong method:
<img width="300" alt="editor_request" src="https://cloud.githubusercontent.com/assets/112468/11929623/927837c6-a7fe-11e5-86d6-490317043f19.png">

Can any one suggest what could be the issue?

**Comment by webron** [comment]
CORS.

https://github.com/swagger-api/swagger-editor/blob/f571a6a46145587dfd3e311312cda969844e182c/docs/cors.md

https://github.com/swagger-api/swagger-ui#cors-support

**Comment by nazarhussain** [comment]
@webron Yes you are right. Its the same problem. Better explained at https://en.wikipedia.org/wiki/Cross-origin_resource_sharing#Preflight_example
