### ISSUE TITLE
Editor strips all comments

### ISSUE THREAD

**Issue by crystalfp** [swagger-api/swagger-editor#753]
More than a but this is a feature request.
If I load an external swagger.yaml file containing comments, they are stripped doing an "import file".
I think they are needed besides the "description" fields for example to visually separate file sections.
Thanks!
mario

**Comment by saharj** [comment]
This is possibly fixed by my pull request #750, also see #697.
If you can, please try it on master and let us know if it's fixed.

**Comment by saharj** [comment]
Due to no response, I'm closing this issue. If you still have this problem let us know, and I'll open this issue.
