### ISSUE TITLE
Nested parameters not shown in "try-operation" form

### ISSUE THREAD

**Issue by aviscasillas** [swagger-api/swagger-editor#754]
# Context
Having an endpoint with parameter definition like:
- JSON object in the body. 
- Attributes of the object nested inside a parent node.

# Issue
Nested parameters are not shown in "try-operation" form if they are not in `require` block.

# Reproduce
I wrote a simple snippet to show the failing case. Here you can see the `POST /failing/endpoint` and the `POST /working/endpoint`.

To see the problem:

1. Paste the YAML snippet in http://editor.swagger.io/#/.
2. Click on "Try this operation" on both endpoints.
3. Compare the "Parameters" area: You will see missing fields in the "Failing object".

```yml
swagger: '2.0'
info:
  title: Bug report
  description: |
    Api spec example to report the bug
  version: 0.0.0
produces:
  - application/json
paths:
  /failing/endpoint:
    post:
      summary: This endpoint fails
      parameters:
        - name: body
          in: body
          description: Invitation batch object
          required: true
          schema:
            $ref: '#/definitions/FailingObject'
      responses:
        '200':
          description: Success
  /working/endpoint:
    post:
      summary: This endpoint does not fail
      parameters:
        - name: body
          in: body
          description: Invitation batch object
          required: true
          schema:
            $ref: '#/definitions/WorkingObject'
      responses:
        '200':
          description: Success
definitions:
  FailingObject:
    required:
      - failing_object
    properties:
      failing_object:
        required:
          - attr1
        properties:
          attr1:
            type: string
          attr2:
            type: string
          attr3:
            type: string
  WorkingObject:
    required:
      - attr1
    properties:
      attr1:
        type: string
      attr2:
        type: string
      attr3:
        type: string
```

**Comment by wolli2710** [comment]
Hi @aviscasillas I just saw your open bug report because I'm working on something related.
But actually I think your schema is not complete. I'm not sure if type is a required argument but I think so.
When I tried your failing example, I fixed it by adding the type object like you can see at the following example:

```
FailingObject:
    type: object
    required:
      - failing_object
    properties:
      failing_object:
        type: object
        required:
          - attr1
        properties:
          attr1:
            type: string
          attr2:
            type: string
          attr3:
            type: string
```
hope this fixes your problem,
cheers

**Comment by aviscasillas** [comment]
Ohh!
@wolli2710 thanks for your response. 

I assumed that the type was not mandatory cause there wasn't any explicit error, and the `WorkingObject` was shown correctly even not having the type defined :sweat_smile:.

Now it  works for me too :blush:.

Btw, IMHO if the `type` field is mandatory, then it would be great to have an explicit error shown.

Cheers.

**Comment by webron** [comment]
To clarify, the `type` field is not mandatory. However, the lack of `type` means that the type is a wildcard. Specifying `properties` does not set the type to be an `object` implicitly. It means that *if* the value that's passed is an object, it will be validated against the `properties`, however, the value will also be valid if it's a string, number, boolean, array... you get the idea. As a best practice, you should always specify the `type`.

When it comes to rendering `type`-less definitions, that ends up being challenging for that exact reason.

**Comment by aviscasillas** [comment]
ok, got it! Thx!
