### ISSUE TITLE
Live Demo throwing unknown error on Example Document

### ISSUE THREAD

**Issue by CloudCray** [swagger-api/swagger-editor#757]
<img width="1403" alt="screen shot 2015-12-31 at 4 37 21 pm" src="https://cloud.githubusercontent.com/assets/2027640/12068466/e394d0d4-afdc-11e5-9877-f125b5e0ed8b.png">

Also, File > Open Example won't open the other examples.

Mac OSX 10.11.1
Google Chrome 47.0.2526.80 (64-bit)

**Comment by chrisdudley** [comment]
That doesn't look to be a valid swagger document. Looks like the definition of a model not a full swagger document, so the error is correct.

**Comment by CloudCray** [comment]
Can the default document be changed to a valid document in that case?
Still doesn't fix the error where File > Open Example won't open the other examples.

**Comment by fehguy** [comment]
I believe this is in your local cache.  Are you running locally or on the online version?

The default document is valid.  Let's figure out if this is an environment issue or other.  Please clear your local cache for editor.swagger.io and report back

**Comment by CloudCray** [comment]
Yep, it was the local cache. Thank you!

**Comment by fehguy** [comment]
Great, thanks
