### ISSUE TITLE
Editor preview does not show example values

### ISSUE THREAD

**Issue by ebullient** [swagger-api/swagger-editor#758]
I've been working between the online editor, and JAX-RS generated swagger documentation to verify the appearance/function of my API. The JAX-RS generated Swagger documentation includes the example values, the docs displayed by version 2.9.8 of the online editor (in the right-hand pane) does not.

**Comment by saharj** [comment]
This issue is fixed and will be available on the next deployment.
See #674, #698, #652 and [this](https://github.com/swagger-api/swagger-editor/commit/4f044bf2ad09bad16f2cf7c15d721c5116124f01).

**Comment by ebullient** [comment]
no wonder I couldn't find any open issues. Hooray!
