### ISSUE TITLE
allOf-bug? No additional properties allowed, but property ... is set

### ISSUE THREAD

**Issue by freiit** [swagger-api/swagger-editor#760]
I get a very strange error message when I use allOf in a body request parameter.

When I use this spec

    swagger: '2.0'
    info:
      title: test
      version: 0.0.1

    host: localhost
    schemes:
      - https
    basePath: /v1
    paths:
      /mypath:
        post:
          parameters:
          - name: param
            in: body
            schema:
              $ref: '#/definitions/spec'
          responses:
            default:
              description: unknown error
              schema:
                type: string
            
    definitions:
      metaSpec:
        type: object
        properties:
          v1:
            type: string
      spec:
        type: object
        allOf:
        - $ref: '#/definitions/metaSpec'
        - properties:
            v2:
              type: string

and click on the "Object Properties" button in the only method, select one item ("v1") and enter a value, I get "No additional properties allowed, but property v1 is set".

I didn't expect the "Object Properties" button in the first place...

Any idea what am I doing wrong and/or how I can work around this?

**Comment by saharj** [comment]
Yes this is a bug. I just confirmed it.

**Comment by Bert-R** [comment]
I'm running into this same issue.

**Comment by pranny** [comment]
+1

**Comment by mwalter-healthagen** [comment]
+1

**Comment by saharj** [comment]
This is a dependency issue. An issue has opened.

**Comment by saharj** [comment]
This issue seems to be fixed. Is anyone still has this issue?

**Comment by Bert-R** [comment]
I don't see it anymore.
