### ISSUE TITLE
Combination of allOf and discriminator gives false warnings

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-editor#765]
If you create a schema with definitions that include a `discriminator`, you will get a false warning that some models are not in use.  In fact, they _may_ be in use indirectly.

For example:

``` yaml
  Animal:
    type: object
    discriminator: petType
    properties:
      commonName:
        type: string
  Cat:
    allOf:
      - $ref: '#/definitions/Animal'
      - type: object
        properties:
          isFurry:
            type: boolean
            default: false
```

Will give a warning like such:

![image](https://cloud.githubusercontent.com/assets/249413/12210886/1b711680-b612-11e5-8642-b4a8fbd3ed9b.png)

It can be difficult to decide what _may_ be referenced by a discriminator, I believe we can encapsulate it in a fairly simple rule:
- If a schema contains the `discriminator` field, AND that schema is referenced in an `allOf` construct, AND neither models are inline schemas, we should _ignore_ any warnings that the `allOf` model is unused.

**Comment by saharj** [comment]
Neither in online swagger, nor on master I could reproduce this. Here is my swagger:

```yaml
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /:
    get:
      responses:
        200:
          description: OK
          schema: 
            $ref: "#/definitions/Cat"
definitions:
  Animal:
    type: object
    discriminator: petType
    properties:
      commonName:
        type: string
  Cat:
    allOf:
      - $ref: '#/definitions/Animal'
      - type: object
        properties:
          isFurry:
            type: boolean
            default: false
```

You probably didn't use the schema.

**Comment by fehguy** [comment]
Try changing the response type to `Animal`, which is a common pattern:


```yaml
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /:
    get:
      responses:
        200:
          description: OK
          schema: 
            $ref: "#/definitions/Animal"
definitions:
  Animal:
    type: object
    discriminator: petType
    properties:
      commonName:
        type: string
  Cat:
    allOf:
      - $ref: '#/definitions/Animal'
      - type: object
        properties:
          isFurry:
            type: boolean
            default: false        
```

This will define the basic response as an `Animal` and concrete implementations by the discriminator field.

**Comment by saharj** [comment]
Here is my understanding about this:
`Cat` is using `Animal`, the `schema` is referring to `Animal`, too. So there is nothing that uses `Cat` (`Animal` doesn't use `Cat`). In this case, the warning is valid. 
Am I missing something?

**Comment by fehguy** [comment]
It is a tiny bit different.  Think of `Animal` as the generic response for the operation--it returns some kind of animal but you don't know what.

When the `discriminator` value is set to `Cat` in the response, the client knows that the response type is actually a Cat rather than generic Animal.

Since we don't actually know what type _could_ be in the response (it may refer to `Alien`) of which there is no definition in the schema, we look at the `allOf` references.  Because `Cat` is referencing `Animal` in an `allOf` construct, we know that it's a possible response type, and therefore it is "in use".

Does that make sense?

**Comment by dirisiopablo** [comment]
Hi @fehguy, have you found a workaround to deal with this issue? I'm facing that warning right now and can't make it disappear. 

Thanks in advance. Pablo.

**Comment by fehguy** [comment]
No, as of now there is no work around other than ignoring the warning

**Comment by dirisiopablo** [comment]
Well, I'll do that. Thanks for reply.

**Comment by janslow** [comment]
A workaround which I'm using is to add a custom root property (which is ignored by the processor) which references the "unused" definitions. For example:

```
x-suppress:
  - $ref: '#/definitions/Cat'
  - $ref: '#/definitions/Dog'
```

**Comment by mike-lang** [comment]
Just ran into this myself.  Thanks @janslow for the workaround.

**Comment by AranDekar** [comment]
for me having this doesn't enable the validation on Cat if my derived type is a Cat:
```
paths:
  /:
    get:
      responses:
        200:
          description: OK
          schema: 
            $ref: "#/definitions/Animal"
```

it only works with validation if I have `  $ref: "#/definitions/Cat`

**Comment by webron** [comment]
This should no longer be an issue in 3.X.
