### ISSUE TITLE
Question on pattern / regex

### ISSUE THREAD

**Issue by davisford** [swagger-api/swagger-editor#768]
Hi, no matter what simple or complex regex I try to use for `pattern` on a property, the editor always tells me the input fails.  What am I missing?

e.g. 

```yaml
      birthday: {type: string, pattern: '^(\d{2}-\d{2})$', description: "Birthday\
          \ is optional but if sent, it should be sent in the format `MM-dd` (we do\
          \ not store or care about the year). \n"}
```

![screen shot 2016-01-11 at 2 31 28 am](https://cloud.githubusercontent.com/assets/186677/12228576/77aebbf0-b80b-11e5-8ac5-07382832a68a.png)

**Comment by webron** [comment]
@davisford - which version have you tested it with? Checking with the online version it seems to validate well.

**Comment by mohsen1** [comment]
Yup, works for me. Here is the swagger that I used:

```yaml
swagger: '2.0'
info:
  version: 0.0.0
  title: '<enter your title>'
paths:
  /persons:
    get:
      description: |
        Gets `Person` objects.
        Optional query param of **size** determines
        size of returned array
      parameters:
        - name: size
          in: body
          description: Size of array
          required: true
          schema:
            $ref: "#/definitions/ArrayOfPersons"
      responses:
        '200':
          description: Successful response
          schema:
            $ref: "#/definitions/ArrayOfPersons"
definitions:
  ArrayOfPersons:
    title: ArrayOfPersons
    type: array
    items:
      title: Person
      type: object
      properties:
        birthday: 
          type: string
          pattern: '^(\d{2}-\d{2})$'
          description: | 
            "Birthday\
            \ is optional but if sent, it should be sent in the format `MM-dd` (we do\
            \ not store or care about the year). \n"}
            
        name:
          type: string
        single:
          type: boolean
```

The `gh-pages` version hasn't been updated for a while though. `master` might be different.

**Comment by davisford** [comment]
Huh, that's really bizarre.  I do test my specs with https://editor.swagger.io - I rebuild them and paste them in and point them to localhost server.  So, I tried your snippet above and indeed it does work.  

Let me take another look and see if mine still fails, and what the difference is.

**Comment by davisford** [comment]
Yes, it seems to work now for my spec as well.  Strange.  Did you deploy a new release in the last few days?  Last I tried it was the day I posted this issue, but it does seem to work now, so I'll close.
