### ISSUE TITLE
PHP Generate Client, AccessToken, Configuration (NOTICE/Small bug)

### ISSUE THREAD

**Issue by MTUNNISSEN** [swagger-api/swagger-editor#769]
Hi,

I used the generated PHP client for a Swagger project, and when using it i noticed that setting the AccessToken in Configuration "setAccessToken" function isn't working because it uses 
```$this->$accessToken =``` and not ```$this->accessToken =```.
"Cannot access empty property" is the error I got when using it.
This is on line 214

Atleast.. It isnt accepted in my PHP version, but i think its not accepted in any PHP version is it?

**Comment by wing328** [comment]
@MTUNNISSEN it's fixed in the latest release (2.1.5) of swagger codegen:
```
SwaggerClient-php/lib/Configuration.php:        $this->accessToken = $accessToken;
SwaggerClient-php/lib/Configuration.php:        return $this->accessToken;
```

generater.swagger.io (used by editor for generating clients) may be still pending the update to 2.1.5.

**Comment by MTUNNISSEN** [comment]
Oops, my bad, couldn't find the codegen at first, but indeed it's fixed.

**Comment by wing328** [comment]
@MTUNNISSEN np. Let us know if you've further question or any feedback at https://github.com/swagger-api/swagger-codegen/issues
