### ISSUE TITLE
Cannot input with IME on MacOS

### ISSUE THREAD

**Issue by debuggings** [swagger-api/swagger-editor#771]
The angular directive (mohsen1/angular-json-schema-form) has a bug when using IME.

The keyup event triggers blur and focus, which will interrupt IME on MacOS. Tried with Firefox, Chrome and Safari. But browsers on windows work fine.

**Comment by saharj** [comment]
As you reported, it is a dependency issue. https://github.com/mohsen1/angular-json-schema-form/issues/7

**Comment by webron** [comment]
This should no longer be an issue in 3.X.
