### ISSUE TITLE
Error installing Swagger locally

### ISSUE THREAD

**Issue by gbonk** [swagger-api/swagger-editor#772]
I'm trying to install/run swagger editor on a SLES 11.3 server.

I've attached the logs and output.  

One error I see is...  ./../nan/nan.h:41:3: error: #error This version of node/NAN/v8 requires a C++11 compiler

Exactly which GCC package and version do I need to have ?

[out.txt](https://github.com/swagger-api/swagger-editor/files/87654/out.txt)

**Comment by fehguy** [comment]
eh, well this is probably due to some underlying npm dependencies.  Do you _need_ to rebuild the server?  Or can you use the pre-built version?

**Comment by gbonk** [comment]
I was just following the directions.  I have no desire to rebuild anything.

**Comment by fehguy** [comment]
Got it--then I suggest following this part of the README:

https://github.com/swagger-api/swagger-editor#using-http-server-module

```
npm install -g http-server
wget https://github.com/swagger-api/swagger-editor/releases/download/v2.9.8/swagger-editor.zip
unzip swagger-editor.zip
http-server swagger-editor
```

Note you don't even need to use the `http-server` if you have your own server.  You really just need the contents of `swagger-editor` unpacked and accessible in some http server.

**Comment by gbonk** [comment]
Thanks.  I guess I stayed up too late watching that game.

Question for you. Swagger Editor has a docker image available.  Would you
recommend using that docker image for a production level system ?

**Comment by fehguy** [comment]
No problem.  The docker image is not official (our docker organization is called `swaggerapi`) and we will be adding one there.

**Comment by mohsen1** [comment]
Most of Docker images out there build the editor on start which is pointless. A good Docker image would be only the dist folder + a lightweight webserver. If release of Docker image becomes part of the release it would be super great!

**Comment by fehguy** [comment]
@mohsen1 we are slowly adding docker images to our ci builds and will do it with editor as soon as we fix the failing tests:

http://dockerhub.com/u/swaggerapi

**Comment by fehguy** [comment]
OK I'm going to close this out, please reopen with any other issues.
