### ISSUE TITLE
Is there a sample code for generating a python client library by the online server "http://editor.swagger.io/"

### ISSUE THREAD

**Issue by LouisZou** [swagger-api/swagger-editor#786]
I have a swagger definition file.
I can paste it to swagger-Editor and then generate a python client library using this online web tool.

But can I use a local source code to realize the function. just like to call a restful API .
For example:
1.set body to my swagger definition file.
2.call http://editor.swagger.io/genclient/python/ to get the zip file for python client library.

Could you please provide a simple usage for this?

**Comment by fehguy** [comment]
the swagger editor uses this service, which is online and readily available:

http://generator.swagger.io/

You can generate a client to call that, or script it with python.
