### ISSUE TITLE
Check if path already contains a querystring when adding query apiKey or params

### ISSUE THREAD

**Issue by mikespub** [swagger-api/swagger-editor#793]
When the path in the original YAML already contains a querystring (with some fixed or variable "path" parameters), and you want to add a query apiKey, the URL generated by the Editor simply adds '?' before 'api_key=...' after the path, instead of checking if there already is a ?' in the path.

path: /mypath?myapi=...&mymethod=...&myparam=...
security: api_key=... in query
expexted url: http://myhost:myport/mypath?myapi=...&mymethod=...&myparam=...&api_key=...
generated url: http://myhost:myport/mypath?myapi=...&mymethod=...&myparam=...?api_key=... (oops, another ?)

For a practical use case, see the _path_sec version in:
https://github.com/swagger-api/swagger-codegen/issues/1985#issuecomment-175548581

The same applies for any other query parameters

**Comment by webron** [comment]
This is a non-issue because the spec does not support query parameters in the paths, so that cannot be supported.

**Comment by mikespub** [comment]
Those are not query parameters as defined in the specs, they're a fixed part of the URLs as defined by the API provider, over which we have no control whatsoever. If necessary, they should be treated as path parameters, but otherwise they'll be hard-coded.

So if swagger editor is to have any use in helping clients access existing dirty APIs (as opposed to only new "clean" ones), it should not deliberately reject things it didn't expect...especially since the only thing you need to do here is check if path already contains a ? or not, and use the proper separator to build the final URL. Everything else is already working fine with it...

**Comment by webron** [comment]
Perhaps I didn't explain properly, apologies. Anything that comes after the `?` is query parameters by definition. Even if you define them as part of the path with fixed values, those are still query parameters. That's just how query parameters are defined. The spec simply does not support that. They cannot be considered part of the path, and cannot be treated as path parameters. This has nothing to do with the editor, this has to do with the spec. And the editor should not support things that are not supported by the spec itself, so yes, it would deliberately reject those.

**Comment by mikespub** [comment]
For example, this is where you need to check if you should use ? or not:
https://github.com/swagger-api/swagger-editor/blob/master/app/scripts/directives/tryoperation.js#L572

**Comment by mikespub** [comment]
Most of the swagger tools don't have a problem with using path?querystring as "resource". In fact, they have no problem treating any {stuff} in querystring as path parameters too, just like they would in the path part.

And that's how we want it if we want to be able to model an API where operations on resources are not uniquely identified just by the endpoint path + http method, but by ?action=something as well.

So as long as all swagger-related tools do not support having the same path & http method reused several times with different query parameters without messing everything up at code generation and/or documentation, putting those querystring parameters inside the "path" is the only way to deal with this.

Unless future specs will support other ways to handle this?

**Comment by webron** [comment]
Future spec versions may or may not support it, I have no way of knowing.

Whether 'most' swagger tools support it or not, is not really relevant. It's not even relevant how easy it is to support it, as we simply will not provide support for it if it's not supported by the spec. I'm afraid that with the current spec, this is a definite `won't fix`.

**Comment by mikespub** [comment]
OK, so I guess even though it's validated according to the editor, it won't let me to try it out afterwards then.

To be honest, as a tool to help developers for both clients & servers, I would expect it to behave in reverse, i.e. be strict in validation, but permissive in trying it out :-)

**Comment by webron** [comment]
Validating that is slightly more difficult, though not impossible. We explicitly don't validate is as part of the JSON Schema, but that's not the source of truth. Perhaps it would make sense to add the validation one way or another to avoid such issues in the future. Thanks for the feedback.
