### ISSUE TITLE
2nd Tag description is not visible

### ISSUE THREAD

**Issue by AbrarSyed** [swagger-api/swagger-editor#794]
When adding tag descriptions, the second one is not visible in the editor. This only happens to the second tag in the list, other tag descriptions are perfectly fine.

![2016-01-27-153407_1800x347_scrot](https://cloud.githubusercontent.com/assets/523593/12629208/74f8410c-c50c-11e5-93ec-502cc261e238.png)

Notice in the screenshot that the description for 'Push Trigger' isnt there on the preview pane on the right.

**Comment by webron** [comment]
Well, that's an interesting bug.

**Comment by saharj** [comment]
I could not reproduce this issue. Everything looks good to me.

Here is my code and the preview: 

<img width="1424" alt="screen shot 2016-01-27 at 3 14 55 pm" src="https://cloud.githubusercontent.com/assets/1468463/12631872/d581d56e-c508-11e5-84a7-710824f4b12b.png">

**Comment by AbrarSyed** [comment]
hah, you are right. It has magically fixed itself for me as well.. Must have been caused by some other error somewhere else in my document, though I could have sworn I had none.

**Comment by saharj** [comment]
No problem. Hopefully it does not happen again ;)
