### ISSUE TITLE
embedding in node-webkit - issues with "file" scheme

### ISSUE THREAD

**Issue by jlowcs** [swagger-api/swagger-editor#796]
I'm currently trying to embed swagger-editor in node-webkit.

It's mostly working quite well, as I can use the `branding.js`file to add specific behavior.

That being said, I'm having issues when using remote json-refs. I managed to change the code a bit to allow for a specific location (the open file's parent dir) in the buildDocs function using a preference, but the worker throws an exception when trying to deal with the "file" scheme.

I've submitted an issue on the sway-worker repository: https://github.com/mohsen1/sway-worker/issues/2

**Comment by mohsen1** [comment]
I think "electronification" of the editor is done previously:
http://blog.takuros.net/entry/2015/12/21/091330
https://github.com/malko/swagged

**Comment by jlowcs** [comment]
I'm actually working on malko's version. It works fine as is, except for when using remote json-refs. That's what I'm trying to solve.

**Comment by mohsen1** [comment]
The it's a json-refs issue that mixes a web worker environment with node.js environment I believe. Please confirm and file an issue to [json-refs](https://github.com/whitlockjc/json-refs).

**Comment by saharj** [comment]
I have update sway-worker recently. Can you try with the latest and let me know?

**Comment by saharj** [comment]
With webpack build system this issue should have been fixed.
