### ISSUE TITLE
centos build swagger editor failed 

### ISSUE THREAD

**Issue by wangcansun** [swagger-api/swagger-editor#797]
**Here is the error info**
**Is there anyone who knows the reason! and thank you very much**

`
[wangcan2@localhost swagger-editor]$ clear
[wangcan2@localhost swagger-editor]$ PORT=8765 npm start

 swagger-editor-src@2.9.8 prestart /opt/tuniu/swagger-editor
npm run build

> swagger-editor-src@2.9.8 prebuild /opt/tuniu/swagger-editor
> npm run bower-install

> swagger-editor-src@2.9.8 prebower-install /opt/tuniu/swagger-editor
> npm install

npm ERR! Linux 2.6.32-431.el6.x86_64
npm ERR! argv "/opt/tuniu/nodejs/bin/node" "/opt/tuniu/nodejs/bin/npm" "run" "bower-install"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! swagger-editor-src@2.9.8 prebower-install: `npm install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the swagger-editor-src@2.9.8 prebower-install script 'npm install'.
npm ERR! This is most likely a problem with the swagger-editor-src package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install
npm ERR! You can get their info via:
npm ERR!     npm owner ls swagger-editor-src
npm ERR! There is likely additional logging output above.
npm ERR! Linux 2.6.32-431.el6.x86_64
npm ERR! argv "/opt/tuniu/nodejs/bin/node" "/opt/tuniu/nodejs/bin/npm" "run" "bower-install"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! path npm-debug.log.3457fe9873c55d3a2b08eb3a9c7f4959
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.3457fe9873c55d3a2b08eb3a9c7f4959'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, open 'npm-debug.log.3457fe9873c55d3a2b08eb3a9c7f4959']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.3457fe9873c55d3a2b08eb3a9c7f4959' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/tuniu/swagger-editor/npm-debug.log

npm ERR! Linux 2.6.32-431.el6.x86_64
npm ERR! argv "/opt/tuniu/nodejs/bin/node" "/opt/tuniu/nodejs/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! swagger-editor-src@2.9.8 prebuild: `npm run bower-install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the swagger-editor-src@2.9.8 prebuild script 'npm run bower-install'.
npm ERR! This is most likely a problem with the swagger-editor-src package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run bower-install
npm ERR! You can get their info via:
npm ERR!     npm owner ls swagger-editor-src
npm ERR! There is likely additional logging output above.
npm ERR! Linux 2.6.32-431.el6.x86_64
npm ERR! argv "/opt/tuniu/nodejs/bin/node" "/opt/tuniu/nodejs/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! path npm-debug.log.129192726895180cb5b7c6179aa10ead
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.129192726895180cb5b7c6179aa10ead'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, open 'npm-debug.log.129192726895180cb5b7c6179aa10ead']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.129192726895180cb5b7c6179aa10ead' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/tuniu/swagger-editor/npm-debug.log

npm ERR! Linux 2.6.32-431.el6.x86_64
npm ERR! argv "/opt/tuniu/nodejs/bin/node" "/opt/tuniu/nodejs/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! swagger-editor-src@2.9.8 prestart: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the swagger-editor-src@2.9.8 prestart script 'npm run build'.
npm ERR! This is most likely a problem with the swagger-editor-src package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls swagger-editor-src
npm ERR! There is likely additional logging output above.
npm ERR! Linux 2.6.32-431.el6.x86_64
npm ERR! argv "/opt/tuniu/nodejs/bin/node" "/opt/tuniu/nodejs/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! path npm-debug.log.ec53aacd1d1b4d3f614d6e6cd31825b6
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.ec53aacd1d1b4d3f614d6e6cd31825b6'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, open 'npm-debug.log.ec53aacd1d1b4d3f614d6e6cd31825b6']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.ec53aacd1d1b4d3f614d6e6cd31825b6' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/tuniu/swagger-editor/npm-debug.log`

**Comment by fehguy** [comment]
You don't need to build to use the editor. See the read me or pull the Docker image

**Comment by saharj** [comment]
It is building successfully in Travis CI. It is possibly your environment. Make sure you have all requirements like latest Node.js

**Comment by wangcansun** [comment]
@saharj 

I have the nodejs version 4.2.6
