### ISSUE TITLE
auto-complete doesn't work on Firefox on Mac

### ISSUE THREAD

**Issue by gabrielsroka** [swagger-api/swagger-editor#804]
it does work on Firefox on Windows and Chrome for Mac

**Comment by saharj** [comment]
It does work on my machine. 
<img width="498" alt="screen shot 2016-02-06 at 10 17 13 am" src="https://cloud.githubusercontent.com/assets/1468463/12868402/ebe2e316-ccba-11e5-89ef-9ecd5c3deb86.png">

**Comment by gabrielsroka** [comment]
i cleared Firefox cache, cookies, etc., and now it's working again
