### ISSUE TITLE
Extra double-quote on auto-completing a reference

### ISSUE THREAD

**Issue by Shockolate** [swagger-api/swagger-editor#807]
While entering a reference node, the editor will notice that I want to reference a definition (for example) and show me the valid options. After hitting tab to select, the editor does not account for the characters I have already typed. 
For example, when typing:
```yaml
schema:
    $ref: "d
```
the auto-complete would show me:
* `"#/definitions/def1"`
* `"#/definitions/def2"`
* `"#/definitions/def3"`

Pressing tab (for def1 was desired) causes the file to result in this state:
```yaml
schema:
   $ref: ""#/definitions/def1"
```
Notice the extra double-quote.

similar behavior
```yaml
schema:
   $ref: "#/d
```
to
```yaml
schema:
   $ref: "#/"#/definitions/def1"
```

**Comment by luskwater** [comment]
Notice that behavior (as far as I can tell) when a leading *single-quote* is used appears to be different from that when a leading *double-quote* is used.  Thanks @saharj for catching the duplicate bug.

**Comment by saharj** [comment]
Seems like this issue is fixed, so I'm closing it. Please leave a comment if you thin this should stay open.
