### ISSUE TITLE
Generated code for C# does not include default headers for some methods

### ISSUE THREAD

**Issue by ayuda-yves** [swagger-api/swagger-editor#808]
Some generated methods have the line:

`var headerParams = new Dictionary<String, String>();`

instead of

`var headerParams = new Dictionary<String, String>(Configuration.DefaultHeader);`

Because of this, the default headers are missing when calling those methods.

Not sure why some methods have the correct code and why others don't, but it seems to be based on the method's signature as all methods with the same signature will either all include headers or none do.

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger-codegen#2029
