### ISSUE TITLE
Sync fold status of the code in editor pane with collapse status of elements in preview pane

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-editor#81]
When folding info, collapse info and vise versa
When folding a path, collapse the path and vise versa
When folding an operation collapse the operation and vise versa
When folding folding a schema do the same...

**Comment by zanona** [comment]
Sometimes, when editing documents, even though that are a few paths of the preview which are folded and if there is an error on the markup for example, all folded sections will open in the preview section meaning that, quite constantly I would have to manually close all of the again to focus on a specific area. With an API with more than 20 endpoints it becomes quite difficult to manage if all code and preview folding are not kept in sync unfortunately.
