### ISSUE TITLE
Uncaught TypeError: Cannot read property 'definitions' of null

### ISSUE THREAD

**Issue by mushahidh** [swagger-api/swagger-editor#812]
I am trying to generate docs for the API . The example link [is given here ](http://soundtrybe.com/rest/rest/web/v1/tracks) . i get response from the server but nothing displayed.There is always a  Uncaught TypeError: Cannot read property 'definitions' of null showing on the console. What i am doing wrong here.

**Comment by webron** [comment]
Your use case isn't clear enough. Can you please specify the steps you take to reproduce the problem?

**Comment by mushahidh** [comment]
@webron  Thanks for replying. The petstore example is working fineon my side. but when i want to r eplace  petstore  link with http://soundtrybe.com/rest/rest/web/v1/tracks  link. It shows nothing on the screen but i can see response in network. Also "Uncaught TypeError: Cannot read property 'definitions' of null" comes in console. I want to start writing an Api doc but unable to do that using swagger. I have made API in YII2..

**Comment by saharj** [comment]
From what I can tell, the link you sent is not a swagger file. Can please explain more?

**Comment by mushahidh** [comment]
@saharj  Means i will have to make it swagger first? It's a very big API. How to document it in a easiest possible way?

**Comment by saharj** [comment]
@webron I think you can help with this

**Comment by webron** [comment]
@mushahidh - Would love to help, but this is not the place. Please submit a question to the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket) and we'll try to assist there.

**Comment by jgonzalezd** [comment]
Where did this conversation  go?

**Comment by webron** [comment]
@jgonzalezd not sure it continued on the google group. if you have a question, just post it there.

**Comment by jgonzalezd** [comment]
Ok, so just in case someone else comes here from google check [http://stackoverflow.com/q/36092980/1248725](url)

**Comment by abhilashak** [comment]
@mushahidh  You misunderstood the Working of swagger ui. Actually the text box at the top is not the place to give your api json response. If you gives your api urls there It will show this error. 

 **It is the place to put the JSON endpoint of your valid OpenAPI v2.**

I also misunderstood while configuring it. Here I used Rails 4 Framework, Grape and grape-swagger-rails gem. But the reason is same. 

You can check this here:
https://github.com/ruby-grape/grape-swagger-rails/issues/58

**Comment by eomsungryul** [comment]
if your using spring security, allow swagger url ( "/v2/api-docs", "/swagger-resources/**", "/swagger-ui.html" ,"/swagger/**" )
