### ISSUE TITLE
Auto-complete $ref parameter string appears broken

### ISSUE THREAD

**Issue by luskwater** [swagger-api/swagger-editor#813]
When referring to parameter definitions from the Swagger object, an auto-complete function only appears to work when starting with a single quote, not a double-quote, nor a bare hash-sign. The auto-complete helpfully lists available parameter definitions after typing `'#/p`. 

However, after pressing **Tab** on such a suggestion, the resulting code looks like
```
  $ref: '#/"#/parameters/serviceContextHeader"
```
with *double-quotes* used and the first few characters repeated.
What I'd like to see is
```
  $ref: '#/parameters/serviceContextHeader'
```
since only the single-quote form seems to trigger the lookup anyway.

**Comment by saharj** [comment]
It seem like a duplicate of #807
