### ISSUE TITLE
OPTIONS request during CORS check doesn't take into account securityDefinitions

### ISSUE THREAD

**Issue by famer** [swagger-api/swagger-editor#816]
When editor performs CORS request, first it sends OPTION request to check `Access-Control-Allow-Origin` header. With this request it doesn't take into account `security` directive that is set for the query it performs OPTION request for. So request in general will fail.

**Comment by mohsen1** [comment]
Why you need authentication to respond to an OPTIONS call? I don't know how it's possible to control jQuery's preflight OPTIONS call to be honest.

**Comment by fehguy** [comment]
By definition, you cannot authenticate on OPTIONS.  This is a server configuration, @famer

**Comment by who** [comment]
@famer I used to have that same issue, but got around it by removing the authentication that was being inadvertently applied on the server side. The OPTIONS verb should be auth free.

**Comment by saharj** [comment]
This is a jQuery thing and we have no control over it.
