### ISSUE TITLE
Incorrect font in markdown list and tables

### ISSUE THREAD

**Issue by IvanGoncharov** [swagger-api/swagger-editor#819]
Version `2.9.8` hosted on http://editor.swagger.io/
Small snippet to reproduce:
```yaml
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
  description: |
    Standard Font
    
    Try to make List:
      * Font became bigger
      * And also bold
      
    Same happens with tables:
    
    | Column1 | Collumn2 |
    | ------- | -------- |
    | Same    | here     |
paths:
  /:
    get:
      responses:
        200:
          description: OK
```
![selection_021](https://cloud.githubusercontent.com/assets/8336157/13036134/12eec0b6-d368-11e5-850f-62cd4c92f135.jpg)

**Comment by mohsen1** [comment]
@saharj Can you find what CSS selector is overriding the font-size in this instance?

**Comment by saharj** [comment]
It seems that the font is correct.

**Comment by IvanGoncharov** [comment]
@saharj Did you fix it?
Because it still reproducible on http://editor.swagger.io

**Comment by saharj** [comment]
@IvanGoncharov The font size and style of tables and lists in the Swagger Editor are supposed to be like this.

**Comment by IvanGoncharov** [comment]
@saharj So you saying my screenshot looks normal?
And text in bullet points and inside tables should be bold by default?

**Comment by saharj** [comment]
@IvanGoncharov We are using Github style and the view you get is matching the style.
https://github.com/swagger-api/swagger-editor/blob/master/app/styles/markdown.less

**Comment by IvanGoncharov** [comment]
@saharj This is how it look on Github:

Standard Font

Try to make List:
   * Font became bigger
   * And also bold

 Same happens with tables:

| Column1 | Collumn2 |
| ------------ | ------------- |
| Same      | here         |

**Comment by IvanGoncharov** [comment]
@saharj I believe you can see deference, right? 
<details> 
  <summary>Hint :smile: </summary>
   <p>Only column names is bold.</p> 
</details>

**Comment by mohsen1** [comment]
I believe some parent element is having a `font-size` property. It's not easy to find which parent is it though

**Comment by IvanGoncharov** [comment]
@mohsen1 Thank you. 
@saharj Can you please reopen this issue?

**Comment by IvanGoncharov** [comment]
@saharj So what is status of this issue?
Is it too complicated and `won't fix`?

**Comment by IvanGoncharov** [comment]
@saharj Thank you
