### ISSUE TITLE
[Enhancement] validate the default value with respect to type and format

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-editor#824]
In Swagger Editor, if a parameter type is integer and I provide `5.0` as the default value, it won't show any error/warning but it should as 5.0 is a decimal (not integer).

It would be good to show warning/error so that the user knows the default value is not correct according to the type/format provided.

<img width="715" alt="screen shot 2016-02-23 at 11 51 22 am" src="https://cloud.githubusercontent.com/assets/934260/13241241/350ae75c-da24-11e5-80bd-eb368ddfc642.png">

**Comment by webron** [comment]
At most it can be a warning. JSON Schema is not strict about it (could be a string value for a boolean).

**Comment by wing328** [comment]
To me, warning is fine as long as there's something to notify the user.

**Comment by shockey** [comment]
Unfortunately, this isn't possible in JavaScript because all numbers are IEEE 754 floating points.

As AJV (our schema validation library) says:

> Ajv is the only validator that passes all the tests from [JSON Schema Test Suite](https://github.com/json-schema/JSON-Schema-Test-Suite) (according to json-schema-benchmark, apart from the test that requires that 1.0 is not an integer that is impossible to satisfy in JavaScript).
> 
> [ref](https://ajv.js.org/#features)
