### ISSUE TITLE
Typescript Angular Client validates boolean parameter with !operator

### ISSUE THREAD

**Issue by AndreasM009** [swagger-api/swagger-editor#825]
When creating a Typescript Angular Client which includes methods that has a boolean Parameter, the boolean Parameter is verified using the !Operator. It is not possible to set the boolean Parameter to a false value. Setting the boolean Parameter to false will cause an exception.

Example:
// verify required parameter 'aProductMakerId' is set
            if (!aBooleanParameter) {
                throw new Error('Missing required parameter aBooleanParameter when calling xyz');
            }

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger-codegen#2221

**Comment by wing328** [comment]
@AndreasM009 did you have a chance to look at my reply at swagger-api/swagger-codegen#2221 ?
