### ISSUE TITLE
Depend on Sway directly

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-editor#826]
* [x] Drop `sway-worker` dependency 
* [x] Add [`worker.js`](https://github.com/swagger-api/sway-worker/blob/use-a-bundler/worker.js) to the source code
* [x] Add a grunt task for building the worker.js into fully compiled file with all of dependencies inlined. This grunt task can be a simple binding to already available webpack task in sway worker or a Grunt task that uses browserify 
* [x] Git-ignore the generated file
* [x] update Grunt `watch` task to do the compilation if worker.js has changed 
* [x] update Grunt `copy` task to copy the generated file to `dist` folder 
* [x] Bring in the tests from sway-worker to test `worker.js` file 

Related: https://github.com/swagger-api/sway-worker/issues/6

**Comment by saharj** [comment]
#849 Will fix this
