### ISSUE TITLE
Add loadbalancing support for code gen requests

### ISSUE THREAD

**Issue by abains** [swagger-api/swagger-editor#829]
The swagger editor make two calls to generate code. First a POST to send he JSON/YAML that returns a link to download the code.  It then calls a GET using the link that was returned.  This works fine if there is shared storage backing the code gen servers behind a load balancer.  But it breaks if the code gen servers write the .zip file to their private file systems.
It would be good if this can be hosted behind a loadbalancer without setting up shared storage.

**Comment by fehguy** [comment]
Please open this on swagger-codegen.
