### ISSUE TITLE
Migrate to Angular 2

### ISSUE THREAD

**Issue by chauey** [swagger-api/swagger-editor#831]
I took a crack at this and got halfway there. hacking the Angular 1 code. Curious what the plans are.

Will the move/donation of spec to OAI, affect anything? thx

**Comment by webron** [comment]
There are no immediate plans to migrate the code to Angular 2. The donation of the spec to the OAI doesn't affect the state of the project.

**Comment by chauey** [comment]
Thanks for the info. I will try to share more if when I get further on it. Very cool stuff. cheers!

**Comment by mohsen1** [comment]
Moving to Angular2 doesn't give this project a lot of benefits to be honest. A complete rewrite makes sense but that's a lot of work...

**Comment by chauey** [comment]
Yeah, actually it's probably a lot more work than I think/thought. 

I was thinking of starting with right side where the info, paths, models, try operation are displayed first, this is very similar in functionality with the swagger UI, am I correct? 

How does that part and the swagger UI differ? What do they share? I would appreciate any knowledge and thoughts there. I assume this one is Angular 1.x, the other is javascript, and don't share much code. I peeked at the package.json here and the included js over there. 

Thanks guys. I've been following Swagger some for almost a year, didn't even know MS was too. Still see the value and hoping to make the most of it.

**Comment by mohsen1** [comment]
Even the right side has a lot of Angular 1 dependency. There isn't a lot of benefits to this move at this time. Specially that Angular2 is still in beta. Dependencies are also a blocking factor. Just adding Angular 2 for template rendering doesn't make sense. Angular 1 does a good job for that.

**Comment by chauey** [comment]
Right. I mean the right side of this compared to the swagger ui project.

My personal plan is Angular 2 for the right side by itself first, which might as well be another version of swagger UI. Then later if/when add some code generation, it would be another version of swagger editor. Let me know if that doesn't make sense or your thoughts if any.

BTW, do you know if this and the swagger UI projects share any common CSS style or any other code? thx

**Comment by webron** [comment]
We migrated to React instead ;)
