### ISSUE TITLE
Code-folding not kept across editor refresh

### ISSUE THREAD

**Issue by zanona** [swagger-api/swagger-editor#833]
Apparently when reloading the editor, code-folding is not kept.
Additionally a suggestion of creating a shortcut for collapsing all available fold marks for speeding development.

**Comment by saharj** [comment]
Yes, code folding data is stored in memory not in local storage. We can move it to local storage at some point.

**Comment by webron** [comment]
Closing as an old issue. Please file a new one if still relevant.
