### ISSUE TITLE
Editor settings failing to update keyboard handler (i.e. vim)

### ISSUE THREAD

**Issue by zanona** [swagger-api/swagger-editor#834]
Apparently it's not possible to change keyboard handlers on the local version of Swagger-editor. It works as expected under http://editor.swagger.io/#/

Steps to reproduce:

```sh
$ npm install swagger -g
$ swagger project create test
$ cd test/
$ swagger project edit
```

http://127.0.0.1:49615/#/ (Safari 9, Chrome 48.x - OSX)

1. Select Preferences > Editor Settings
2. Change **Keyboard Handler** option from `ace` to `vim`
3. Browser console outputs `[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (keybinding-vim.js, line 0) http://127.0.0.1:49615/bower_components/ace-builds/src-noconflict/keybinding-vim.js`

**Comment by zanona** [comment]
Just tested and it happens even on the latest downloadable version of this repository

**Comment by saharj** [comment]
This issue should be fixed by #726 #780. Please let me know if you can reproduce it in master.

**Comment by zanona** [comment]
I'm afraid I have only tested on the latest available version since there's no need to build it. Thanks for the feedback though.

**Comment by saharj** [comment]
This issue has been fixed on `master` and it will be fixed on the new release soon.
