### ISSUE TITLE
Typo - duplicate 'type' in sample twitter api

### ISSUE THREAD

**Issue by chrisdudley** [swagger-api/swagger-editor#835]
https://github.com/swagger-api/swagger-editor/blob/master/app/spec-files/twitter.yaml#L232
https://github.com/swagger-api/swagger-editor/blob/master/app/spec-files/twitter.yaml#L236

Still valid YAML but breaks a lot of parsers - in my case it failed to pass through json-refs.

**Comment by fehguy** [comment]
thanks, i've removed it.  If you find any others, please send a PR.

**Comment by chrisdudley** [comment]
There's a duplicate operation in there too: /statuses/retweets/{id}
I'll submit a PR when I get a chance, but mentioning it here so it isnt forgotten.
