### ISSUE TITLE
petstore example: content-type application/xml doesn't display ( application/json does)

### ISSUE THREAD

**Issue by sdavis-r7** [swagger-api/swagger-editor#838]
<img width="696" alt="application xml" src="https://cloud.githubusercontent.com/assets/16342638/13512703/225435b2-e151-11e5-8144-3fc4e76dcd27.png">
<img width="685" alt="application json" src="https://cloud.githubusercontent.com/assets/16342638/13512705/23e78a14-e151-11e5-87fc-cd4a86d8573f.png">

**Comment by saharj** [comment]
We never had XML body preview. We can add this feature for sure.

**Comment by webron** [comment]
This should no longer be an issue in 3.X.
