### ISSUE TITLE
swagger uses CORS within the same domain

### ISSUE THREAD

**Issue by cropr** [swagger-api/swagger-editor#845]
I  am having swagger editor running on localhost port 8000 and my sever that runs the api on localhost port 9000.  
Yet as I am trying the configuration, swagger complains about cross domain calls, and issues first an OPTIONS request

**Comment by fehguy** [comment]
That's a problem with your server, not swagger-editor.  Please enable CORS on your server.

**Comment by chrisdudley** [comment]
Different port on the same server is still a different domain from a CORS point of view. 
This is working as designed.

**Comment by fehguy** [comment]
sorry, that's your server not sending the appropriate headers, not the swagger editor.  tell your server to return `access-control-allow-origin: *` and it'll work fine.

**Comment by saharj** [comment]
Different ports are different domains. This is expected behavior.
