### ISSUE TITLE
Resolution of external references with $ref broken from 2.9.8 to 2.9.9

### ISSUE THREAD

**Issue by ralfhandl** [swagger-api/swagger-editor#847]
Swagger Editor 2.9.9 no longer resolves external references to definitions that themselves contain local references within the referenced files. 

https://raw.githubusercontent.com/ralfhandl/odata/master/TripPin.openapi.json references an object in 
https://raw.githubusercontent.com/ralfhandl/odata/master/edm.json#/definitions/odata.error which itself references substructures defined in edm.json and thus uses local references to #/definitions/...

These references were correctly resolved in Swagger Editor 2.9.8:
![image](https://cloud.githubusercontent.com/assets/951576/13883117/5fef8e70-ed28-11e5-8ed5-025245e65796.png)

Swagger UI also correctly resolves these references:
![image](https://cloud.githubusercontent.com/assets/951576/13883149/771432f4-ed28-11e5-92bc-3f0abbbe7c7f.png)

**Comment by reece** [comment]
I have a similar error that is probably related. 

[minimal-jsonapi.yaml.zip](https://github.com/swagger-api/swagger-editor/files/183329/minimal-jsonapi.yaml.zip) demonstrates the error when trying to use the jsonapi error model within swagger. 

With the demo version (2.9.9), I get:
✖ Swagger Error Reference could not be resolved: #/definitions/links
✖ Swagger Error Reference could not be resolved: #/definitions/meta
Both of those are referenced from the error model and exist in the same document.

**Comment by saharj** [comment]
This is result of Sway upgrade. @whitlockjc is this a bug in Sway?

In #849 we will depend on Sway directly.

**Comment by whitlockjc** [comment]
`sway@master` supports this.

**Comment by saharj** [comment]
@reece & @ralfhandl I guess this issue has been fixed now. Would you please take a moment and see if you still have the same problem on `master`?

**Comment by ralfhandl** [comment]
Problem solved, thanks!

Small caveat: I had to tweak `package.json`, line 82 to

    "source-code-pro": "https://github.com/adobe-fonts/source-code-pro.git#release",
    
(`https://` instead of `git://`) to get `npm install` working - my machine sits behind a proxy. Should I open a separate issue for this?

**Comment by saharj** [comment]
@ralfhandl Awesome!
I made a  new PR to fix the issue [here](https://github.com/swagger-api/swagger-editor/commit/345b1bce9e39e1f12a6783758d6ea74a5b97028e).
