### ISSUE TITLE
c# code generated for "enum" does not work

### ISSUE THREAD

**Issue by edarn** [swagger-api/swagger-editor#848]
It appears to me that the client side c# code generated for enums is not correct for enums. I don´t find any enum at all. However, it looks ok for Java.

 SalesItemBrief:
    type: object
    properties:
      ItemId:
        type: string
      ItemType:
        $ref: "#/definitions/ItemTypeEnum"

  ItemTypeEnum:
    type: string
    enum:
      - ART
      - SPR
      - GPR

Generated c# code:

namespace IO.Swagger.Model {

  /// <summary>
  /// 
  /// </summary>
  [DataContract]
  public class ItemTypeEnum {
    

    /// <summary>
    /// Get the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()  {
      var sb = new StringBuilder();
      sb.Append("class ItemTypeEnum {\n");
      
      sb.Append("}\n");
      return sb.ToString();
    }

    /// <summary>
    /// Get the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson() {
      return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

}

**Comment by saharj** [comment]
This issue was moved to swagger-api/swagger-codegen#2429
