### ISSUE TITLE
The HTTP PATCH background color is hard to read

### ISSUE THREAD

**Issue by who** [swagger-api/swagger-editor#851]
In swagger-editor, each of the HTTP verbs have their own background color; GET is blue, POST is green, etc.

I have found that the background color for the PATCH verb, which is bright yellow, is rather hard to read, as the foreground text is white.

Here's a picture:

![hard-to-read](https://cloud.githubusercontent.com/assets/282534/13993848/4c2717ea-f0df-11e5-9f3f-f4352d23123c.png)

**Comment by saharj** [comment]
Thank you. We will look at this
