### ISSUE TITLE
Running via docker does not work

### ISSUE THREAD

**Issue by prestonvanloon** [swagger-api/swagger-editor#859]
I am greeted with an nginx page, but nothing else. 

```shell
docker build -t swagger-editor .
docker run -ti -p 8080:8080 swagger-editor
```

**Comment by saharj** [comment]
There will be a new update soon that may fix your issue

**Comment by saharj** [comment]
We have updated the build system. Would you please try again and see if you still have the same problem?

**Comment by prestonvanloon** [comment]
Now it doesn't work at all. No nginx page anymore.
I ran this: 
```
docker build --no-cache -t swagger-editor .
docker run -ti -p 8080:8080 swagger-editor
```
Then opened localhost:8080 but it refused the connection.

**Comment by fehguy** [comment]
Looking into this

**Comment by fehguy** [comment]
It looks like this works fine--be sure you follow these steps:

```
# pull deps
npm i

# build the distribution
npm run build

# build the docker image
docker build --no-cache -t swagger-editor .

# run it on localhost:8080
docker run -p 8080:8080 swagger-editor
```

My guess is you were missing the build step.  Can you please re-try and report back?

**Comment by prestonvanloon** [comment]
Just a nginx screen with that. I pulled down the latest on master, then ran the commands you suggested. 

Also, the webpack bit takes several minutes? Maybe it's unrelated, but it seems like an excessive amount of time.

**Comment by fehguy** [comment]
Not possible I think, editor doesn't use nginx

**Comment by saharj** [comment]
@prestonvanloon It is possible that nginx is running in your 8080 port. Please try another port and see if your issue gets fixed.
