### ISSUE TITLE
API keys can no longer be changed

### ISSUE THREAD

**Issue by juleshall** [swagger-api/swagger-editor#865]
An API key defined under security definitions can no longer be entered using the Authenticate or Change Authentication options.  The problem can be reproduced by loading any of the example specs that include security definitions.  e.g. security.yaml

The following error is logged when attempting to authenticate:

angular.js:13424Error: [$injector:unpr] Unknown provider: tProvider <- t
http://errors.angularjs.org/1.5.3/$injector/unpr?p0=tProvider%20%3C-%20t
    at angular.js:68
    at angular.js:4418
    at Object.r [as get] (angular.js:4571)
    at angular.js:4423
    at r (angular.js:4571)
    at i (angular.js:4595)
    at Object.a [as invoke] (angular.js:4617)
    at h.instance (angular.js:10027)
    at ui-bootstrap-tpls.js:4138
    at s (angular.js:15757)

**Comment by jt000** [comment]
Dupe of #862 ?

**Comment by juleshall** [comment]
You're right, it's a duplicate of #862.
