### ISSUE TITLE
Code Generator Error if our definitions have type as Array

### ISSUE THREAD

**Issue by mtsmfm** [swagger-api/swagger-editor#868]
Code Generator Error if our definitions have type as Array:

```yaml
---
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /:
    get:
      responses:
        200:
          description: OK
          schema:
            "$ref": "#/definitions/User"
definitions:
  User:
    type:
    - string
```

## How to reproduce

1. Import
  http://editor.swagger.io/#/?import=https://gist.githubusercontent.com/mtsmfm/02f9a231ac83762945f57e9d5d07fea0/raw/3cdbc2fa74664987589d05721ed4dc34e77bc9c8/sample.yml
2. Click "Generate Client"
3. Click "Ruby"

**Comment by webron** [comment]
@mtsmfm - that's an invalid spec. The `type` has to be a single value. I realize the spec is not super clear about it, but it's not supported.

**Comment by ralfhandl** [comment]
@webron The definition of a [Schema Object](http://swagger.io/specification/#schemaObject) explicitly lists `type` among the properties that are "taken directly from the JSON Schema definition and follow the same specifications". This would include arrays of strings, see [JSON Schema Validation, section 5.5.2.](http://json-schema.org/latest/json-schema-validation.html#anchor79)

Both Swagger UI and Swagger Editor gracefully handle array values for `type`.

Only for Parameter Objects other than body parameters the spec explicitly restricts `type` to a single string value.

**Comment by fehguy** [comment]
@ralfhandl doesn't matter.  The spec isn't supposed to support it.  As said, it's an error in the documentation.  If we supported arrays for `type`, we wouldn't have as many conversations about `anyOf`, etc.

**Comment by ralfhandl** [comment]
@fehguy Seeing the number of people asking for it: is there already a consensus forming on which way the spec wants to go?

**Comment by webron** [comment]
@ralfhandl there's no consensus, but that's a discussion for the spec repository. 

Closing this as not supported.

**Comment by fehguy** [comment]
We're certainly not being consensus driven on the spec, but we do know there needs to be some way to address this.  Please follow https://github.com/OAI/OpenAPI-Specification/issues/579
