### ISSUE TITLE
tag-filter causes reset of api-Specification

### ISSUE THREAD

**Issue by kavanu** [swagger-api/swagger-editor#873]
All changes are lost in case of filtering the api-Specification by tags

Steps to reproduce:
1. Import an api with http://editor.swagger.io/#/?import=http://editor.swagger.io/spec-files/default.yaml
2. Change something in the api
3. Filter an ressource by tag
4. Changes are lost

There is no seperate GET-Request in the access-Log of apache httpd

Version 2.9.8

**Comment by gitms12** [comment]
Can't the preview be filtered by tags without reloading the whole editor? I admit it will be many effort but should be feasible,

**Comment by webron** [comment]
Closing as this feature no longer exists in the editor.
