### ISSUE TITLE
error message for duplicate definition points to wrong definition

### ISSUE THREAD

**Issue by abstratt** [swagger-api/swagger-editor#875]
For the following spec (note r1 is defined twice):

```
swagger: '2.0'

info:
  version: "0.0.0"
  title: s1

definitions:
  r1:
    type: object
  r1:
    type: object
  e1:
    type: object

paths:
  /foo:
    get:
      responses:
        204:
          description: none
```

I get an error reported like this:

```
✖ YAML Syntax Error
Duplicated mapping key at line 12, column 3: e1: ^
Jump to line 11
```

IOW, the error gets reported on the following element, instead of on the offending element, leading to a baffled spec writer ("but e1 is not duplicated!").

![image](https://cloud.githubusercontent.com/assets/2187522/14683947/c9ab534a-0703-11e6-9565-d5bcf80ed741.png)

**Comment by saharj** [comment]
f4c3237253e813a56f954249b792dd4771c1bcb9 will improve the error pointer a little but at its core this is [an issue with yaml-js](https://github.com/nodeca/js-yaml/issues/283).

**Comment by webron** [comment]
This should no longer be an issue in 3.X.
