### ISSUE TITLE
< IE 9 support? 

### ISSUE THREAD

**Issue by owenconti** [swagger-api/swagger-editor#878]
After the Promise polyfill issue was fixed, it seems that < IE 9 fails on missing WebWorkers. I am not familiar at all with WebWorkers. Is this something that would be able to be polyfilled?

It seems like the `yaml-js` or `js-yaml` modules are using WebWorkers?

**Comment by saharj** [comment]
@fehguy Are we going to support < IE 9 ?

**Comment by owenconti** [comment]
I've been instructed to make sure SwaggerHub works with IE9+. Right now, this issue is my blocking factor.

Maybe that will be a big enough issue to push off IE9 support ;)

**Comment by fehguy** [comment]
I believe we were going for IE9+.  But @owenconti you're saying IE9 is not supportable without major efforts?

**Comment by mohsen1** [comment]
http://caniuse.com/#search=webworkers

**Comment by owenconti** [comment]
So IE9 does not support web workers and it appears swagger-editor depends on them. I have zero experience with web workers so I don't know how easy a fix is. some quick googling led me to believe it is not a simple plug n' play fix, but maybe someone more familiar with swagger-editor/web worker setup would have a better idea

**Comment by saharj** [comment]
Files that are running in web workers are these: https://github.com/swagger-api/swagger-editor/tree/master/scripts/workers

I'm not sure how to run them outside of web workers. They are using web workers APIs.
