### ISSUE TITLE
Post missing formData

### ISSUE THREAD

**Issue by kaihendry** [swagger-api/swagger-editor#881]
Using http://editor.swagger.io/#/ and http://s.natalian.org.s3.amazonaws.com/2016-04-22/swagger-formData-no-worky.yaml I can't seem to send a request using formData.

What am I missing?

<img src=http://s.natalian.org/2016-04-22/1461305936_2558x1404.png>

Feel free to see the API working at https://feedback.dabase.com/

**Comment by webron** [comment]
You're missing either `application/x-www-form-urlencoded` or `multipart/form-data` set as the `consumes` value for the operation.
