### ISSUE TITLE
Make it easire to work with very large content

### ISSUE THREAD

**Issue by hlubovac** [swagger-api/swagger-editor#882]
I don't know if anything can be done. "Large" content to me is a 2MB large JSON pasted via File menu. From the moment it's CTR+V'ed into the box, the site becomes so slow that it's impossible to work with (tried Chrome and Firefox). I'm experiencing over 1 min of delay to see a character typed. Scrolling is slow and delayed. And these delays seem to increase over time, too. 2MB is not that large: I'd say there's room for improvement.

The editor works very well with small documents. However, how many services out there will be small...

**Comment by hlubovac** [comment]
Possibly related: https://github.com/swagger-api/swagger-editor/issues/883

**Comment by saharj** [comment]
Have you tried turning off autocomplete and live preview in preferences menu?

**Comment by robsontenorio** [comment]
Yes, I did it.

Is there any other optional javascript that can be turned off? It has too much javascript running...

Swagger Editor can not handle large specs... :(

**Comment by webron** [comment]
Since the release of the new editor, give it another try. If the issue persists, please file a new ticket (preferably with spec samples for testing).

**Comment by finkef-zz** [comment]
Could you kindly add a quick hint on how to "turn off autocomplete and live preview" in the new editor? I'm also running performance issues (most notably severe input delay) with my ~2000 lines swagger model.

**Comment by shibuyaku** [comment]
Could you kindly add a quick hint on how to "turn off autocomplete and live preview" in the new editor? I'm also running into performance issues (most notably severe input delay) with my ~2000 lines swagger model.

**Comment by gganssauge** [comment]
I also could use that hint - my spec is not even 1000 lines and editing is unbearably slow.
