### ISSUE TITLE
Root object name in editor?

### ISSUE THREAD

**Issue by vnalla** [swagger-api/swagger-editor#885]
Why does swagger editor shows the root object name when defined in the specification yaml file for example  the Object name “Profile” and “Error” is shown in the swagger editor for example1.yaml (example1.png) and not shown when separate JSON schema files are used for both Profile and Error objects as in example2.yaml (example2.png), and example3.yaml (example3.png). However swagger UI does not show the object name for “Model Schema” for all these examples in other words it treats all three cases same.
What is the actual Swagger-Spec/OAI Specification recommendation for serializing the root object name? or is left to the JSON provider used like Jackson or Jettison which can be turned on/off? Does not it create an interoperability issue? 

These samples are created from Uber API example.

![example1](https://cloud.githubusercontent.com/assets/11826854/14790766/cec64354-0ae0-11e6-943d-c4f886a29794.png)

![example2](https://cloud.githubusercontent.com/assets/11826854/14790767/cec673f6-0ae0-11e6-9436-274de8ca3c93.png)

![example3](https://cloud.githubusercontent.com/assets/11826854/14790768/ced79424-0ae0-11e6-8282-a61fb4a87299.png)

[example.zip](https://github.com/swagger-api/swagger-editor/files/234946/example.zip)

**Comment by saharj** [comment]
Swagger Editor gets the title from either the title in `schema` or the name of your schema defined in `definitions` section. You just need to add a `title` inside schema to have a similar result.
```
swagger: '2.0'
info:
  title: Test API using a resource from Uber API
  version: 1.0.0
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  /me:
    get:
      description: The User Profile endpoint returns information about the Uber user that has authorized with the application.
      tags:
        - User
      responses:
        '200':
          description: Profile information for a user
          schema:
            title: Profile
            $ref: 'http://localhost:7070/files/example/Profile.json#/definitions/Profile'
        default:
          description: Unexpected error
          schema:
            title: Error
            $ref: 'http://localhost:7070/files/example/Error.json#/definitions/Error'
```
