### ISSUE TITLE
Unable to use $ref with other attributes

### ISSUE THREAD

**Issue by jrbasso** [swagger-api/swagger-editor#886]
Using the following code makes the editor to show an error message and not to show the field information.

```yml
swagger: '2.0'

info:
  version: "0.0.1"
  title: Showing $ref on parameter

paths:
  /{id}/{slug}:
    get:
      parameters:
        - name: id
          in: path
          description: Resource ID
          required: true
          $ref: '#/definitions/IntID'
        - name: slug
          $ref: '#/definitions/Slug'
          in: path
          description: Resource slug
          required: true
      responses:
        204:
          description: Successful response

definitions:
  IntID:
    type: number
    minimum: 1
    format: double
  Slug:
    type: string
```

This results in: 
![image](https://cloud.githubusercontent.com/assets/26548/14798567/487869c8-0b06-11e6-9bfd-ac38c7386f9c.png)

I was able to use it on Apiary:
![image](https://cloud.githubusercontent.com/assets/26548/14798615/8325cd72-0b06-11e6-8089-dc494650fcd3.png)

**Comment by fehguy** [comment]
Hi, you cannot use `$ref` with any sibling attributes.  This isn't an issue with swagger, it's a design constraint of JSON pointers.  It shouldn't be allowed in Apiary's tool, either, you should open a bug there.  Furthermore your use of `$ref` with path parameters is forbidden by the spec.  You can only use primitives or arrays of primitives.

If you want to reuse your definition of, say, `IntID`, consider something like this:

```yaml
# ...
  get:
    parameters:
      - $ref: '#/parameters/IntID'

# ...

parameters:
  IntID:
    in: path
    name: id
    type: number
    format: double
    minimum: 1
```

**Comment by jrbasso** [comment]
Got it. Having the functionality like I put on the swagger example would be nice to have, but I understand why it is not possible. I couldn't determine from the specification if that was valid or not.

The only bad part of using the `parameters` is you have to do a new entry just to change the description field.

Thanks.
