### ISSUE TITLE
Swagger Editor appears stuck in readonly 

### ISSUE THREAD

**Issue by ricardo100671** [swagger-api/swagger-editor#888]
Since this morning I am unable to edit any files

**Comment by saharj** [comment]
Everything seems to work fine. The problem can be from your machine.

**Comment by gbrown-ce** [comment]
@ricardo100671 Did you ever solve this problem? I've run into the same issue.

**Comment by Dudy** [comment]
I had this problem in Chrome, deleted all Cookies and Caches, then it worked again.

**Comment by team-yufei** [comment]
I meet the problem same.

**Comment by julianlfs** [comment]
Same problem here

**Comment by shockey** [comment]
@julianlfs this is a very, very old issue - if you're having a problem, please open a new one 😄
