### ISSUE TITLE
Generate dist folder from source code

### ISSUE THREAD

**Issue by aumerhadi** [swagger-api/swagger-editor#892]
Hi 
What is the steps to generate dist folder from the source code?

**Comment by saharj** [comment]
If you don't have the `dist` folder already, you just need to run `npm install` and `npm run build` to generate the `dist` folder.

**Comment by aumerhadi** [comment]
Hi Sahar, thank you for your quick response , I run npm install but couldn't find the dist folder. I don't thing package.json has the script to create dist folder.

**Comment by saharj** [comment]
After you run `npm install` you need to run `npm run build` to get the `dist` folder.

**Comment by aumerhadi** [comment]
Hi Sahar marhaba, I tried the command you mentioned it , but it generate more than 130 files with strange name ( attached the output from run this command)

Can you please check the txt file and let me know if other thing I need to do ?
[result.txt](https://github.com/swagger-api/swagger-editor/files/241122/result.txt)

**Comment by webron** [comment]
@saharj when you get a chance...

**Comment by saharj** [comment]
There is nothing strange in your output file. That's webpack logs. After that output you should have a working `dist` folder.

**Comment by aumerhadi** [comment]
Thank you Sahar for your response, The dist folder has alot of font files, 3 js files and one css file (attached picture for the dist folder)
I think there are few steps missing, maybe I need to copy files some where else ? please help me solve this issue.
![dist_folder](https://cloud.githubusercontent.com/assets/2063075/15436254/ea29f30e-1e8e-11e6-8b65-a711346d90a9.png)

**Comment by saharj** [comment]
Your `dist` folder looks good. What is the problem exactly?

**Comment by aumerhadi** [comment]
Please correct me if I am wrong, I thought the dist folder will be a packaged project (something like the one we download from this location https://github.com/swagger-api/swagger-editor/releases/download/v2.10.1/swagger-editor.zip) .

**Comment by devloprNaveen** [comment]
> After you run `npm install` you need to run `npm run build` to get the `dist` folder.

Can we run build without a build script ?, Guess we cannot
