### ISSUE TITLE
Unable to import json file in Safari/Mac

### ISSUE THREAD

**Issue by sweetw0r** [swagger-api/swagger-editor#896]
Import button isn't active. Chrome/Mac works fine

Safari Version 9.1 (11601.5.17.1)
Max OS X 10.11.4

![screen shot 2016-04-27 at 12 46 09 pm](https://cloud.githubusercontent.com/assets/12688470/14866206/598ece06-0c77-11e6-9cd7-451367fe36dc.png)

**Comment by saharj** [comment]
I can't reproduce this issue. Can you build from master and try again?

**Comment by sweetw0r** [comment]
That works now.
