### ISSUE TITLE
Import URL if API requires login via POST?

### ISSUE THREAD

**Issue by dflock** [swagger-api/swagger-editor#897]
I'm trying to write a swagger spec for an existing API, which requires you to login first, using a POST request. This creates a session on the server side and give you a token for it.

Can I use the Import URL function in Swagger Editor with endpoints from this API? I can't see any way to tell the editor how to login first?

**Comment by saharj** [comment]
In Swagger Editor when you import, it simply makes a Get request, and there is no way to change that. Maybe you can pass a token in the query parameter.
