### ISSUE TITLE
Unable to type in editor

### ISSUE THREAD

**Issue by ricardo100671** [swagger-api/swagger-editor#904]
Page is throwing exception whenever any key is pressed. Please see attachement

![image](https://cloud.githubusercontent.com/assets/4727540/14908237/9d15e10e-0dcc-11e6-9b74-aaaa346d4499.png)

**Comment by saharj** [comment]
Would you please provide more information? I can't reproduce the issue.

**Comment by saharj** [comment]
I'm closing this issue due to no response.
