### ISSUE TITLE
Epic: Implement GUI based API design features

### ISSUE THREAD

**Issue by earth2marsh** [swagger-api/swagger-editor#91]
New users will not have familiarity with the YAML syntax. To that end, it would be useful to auto-suggest, but since that's a hard problem.

In the short term, we should consider a menu item that allows a user to add a boilerplate `operation`, `parameter`, `response`, `definition`, etc.

**Comment by webron** [comment]
Closing as a very old ticket. Please open a new ticket if still relevant.
