### ISSUE TITLE
Javascript errors using docker image v2.9.9 and latest

### ISSUE THREAD

**Issue by Hendrik-H** [swagger-api/swagger-editor#913]
Using the the v2.9.9 and latest docker image swaggerapi/swagger-editor I get Javascript errors in the browser console when editing a new (File -> New) using Firefox and Chrome. In addition the "Schema" column only shows arrows but no further information.
When I use the latest version of mydock/swagger-editor things do work fine however. No errors in the console and the schema column shows "string" next to the arrows.

**Comment by saharj** [comment]
We will release the v2.10.0 very soon. Until then you can build directly from master.
