### ISSUE TITLE
Question: how can I debug this error?

### ISSUE THREAD

**Issue by paul42** [swagger-api/swagger-editor#917]
There's an error in my swagger spec somewhere - but I don't know what it is - the jump to line link always drops me to line 27 no matter how I move the text around (moving properties up/down)

the error:

    message:  "Maximum call stack size exceeded"
    code:  "UNCAUGHT_SWAY_WORKER_ERROR"
    level: 900
    type:  "Unknown Error"
    description:  "Maximum call stack size exceeded"

the wierd thing is that I have an old browser window (chrome) that I keep open and it works fine, but when I open a new window and paste in my json or import my json this happens. It doesn't appear to happen with the examples so I think it's my code

**Comment by saharj** [comment]
Could you please paste your swagger here?

**Comment by paul42** [comment]
I've made it into a GIST: https://gist.github.com/paul42/4a85567c9136eba058ecc5e571b2b4ef
So I think the issue is I have too many references - I've trimmed out a lot of the stuff and i still get the stack error, but if I remove a refernce, then it goes back to working - 

to reproduce: 
open editor.swagger.io
file->paste json
paste in json from gist
ensure you get max stack exceeded error
remove a single property from a definition that has $ref: '#/definitions/ ' etc
notice that the swagger editor resumes working

is the editor only able to handle a certain amount of references, or am I making mine wrong?

Thanks again for taking a look, I appreciate it.

**Comment by ePaul** [comment]
Hmm, it looks like some of your references are circular, like user → subscribedGroups → group → creator → user.

I'm not sure how this would look like in an actual JSON document?

**Comment by paul42** [comment]
Ah, I see the point, I thought the UI would have a way to deal with circular and stop going too deep, I'll change up my schema
