### ISSUE TITLE
Empty $ref in a definition object's property causes hang

### ISSUE THREAD

**Issue by seijikun** [swagger-api/swagger-editor#918]
I am using the editor [online](http://editor.swagger.io) (so: Version 2.9.9).
The following code sample works just fine when directly pasted into the editor:
```
swagger: '2.0'
info:
  version: 0.1-beta
  title: SlideMaster
produces:
  - 'application/json'

definitions:
  Nested:
    type: object
    description: "Test-Object that will be nested in Parent"
    properties:
      id:
        type: integer

  Parent:
    type: object
    description: "Parent that will contain Nested"
    properties:
      id:
        type: integer
        description: "Unique identifier of this session."
      inner:
        $ref: '#/definitions/Nested'
    
paths:
  '/dummy':
    get:
      responses:
        '200':
          description: "dummy"
```
However, changing line 24 from:
```
$ref: '#/definitions/Nested'
```
to:
```
$ref: ''
```
causes the editor to hang, produce 100% cpu load and start hogging ram.
This is reproducible on `opera 36.0.2130.65` and `firefox 46.0`

**Comment by saharj** [comment]
I wasn't able to reproduce this issue on Chrome or on Firefox.

**Comment by seijikun** [comment]
I was able to reproduce this on 4 machines. (Windows & Linux)
"hang" is probably not the correct word.
The editor remains responsive, however, the editor's right side does not update anymore, because the background thread seems to be in a loop, continuing to allocate memory. (Probably needs a task-manager to notice)

Blink-Based browsers kill the task after some minutes, because of the exceeded memory limit.

**Comment by saharj** [comment]
This might be a Sway issue. You can open a new issue here: https://github.com/apigee-127/sway
