### ISSUE TITLE
Prefill request parameters with example data in try operation 

### ISSUE THREAD

**Issue by saharj** [swagger-api/swagger-editor#926]
Moving #791 to here

Prefilling is already working for parameters with a `default` value. it does not work with JSON Schema parameters. 

For example this Swagger's GET request does prefilling but POST does not:

```yaml
---
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /:
    get:
      parameters:
        - name: limit
          in: query
          description: description
          type: number
          default: 10
        
      responses:
        200:
          description: OK
    post:
      summary: boo
      description: boo
      parameters:
        - name: body
          in: body
          description: description
          schema:
            type: object
            properties:
              foo:
                type: string
                default: MMMMMMMAAAA
        
      responses:
        200:
          description: OK
```

Maybe it is the JSON-Editor dependency that should do this.

**Comment by jorgeorpinel** [comment]
This is a problem in Swagger UI actually. I wonder why this was just closed without explanation...

**Comment by shockey** [comment]
@jorgeorpinel, this issue was closed by a commit that was marked as fixing the issue: https://github.com/swagger-api/swagger-editor/commit/856b5d984a0adf9a1383a7188da9556128b84e37
