### ISSUE TITLE
Export just the output page of editor as html to show clients?

### ISSUE THREAD

**Issue by jasonboggess** [swagger-api/swagger-editor#929]
This editor is fantastic, and a great way to develop. Is there a way we can generate just an HTML version of the right side (the results) to give to clients? Swagger-UI is outdated, and the codegen tool to generate HTML pages misses a lot of attributes (and doesn't look nearly as pretty).

Another suggestion along those lines: Sites like http://jsfiddle.net/ allow you to save your files by short URL. That coupled with "fullscreen mode" that could be activated by url would be an awesome way to share specs.

**Comment by saharj** [comment]
This has been discussed before. We decided to not do that. See #664
