### ISSUE TITLE
2.10.1 dist files contain absolute URLs

### ISSUE THREAD

**Issue by eminence** [swagger-api/swagger-editor#930]
Hello!  

I just downloaded the 2.10.1 release from github.  It seems that several javascript and CSS paths are referenced using absolute paths that start with `/dist/`.  This causes problems when swagger-editor is hosted somewhere other than the root of your web server.  For example, in style.css:

```css
url(/dist/ab28ef22f46ea6dfec154abb4be50aba.woff)
```

If I've deployed swagger-editor into a directory named `swagger-editor`, instead of requesting something like `/swagger-editor/dist/ab28ef22f46ea6dfec154abb4be50aba.woff` the request is for `/dist/ab28ef22f46ea6dfec154abb4be50aba.woff` which a 404.

**Comment by saharj** [comment]
With 5308972 there will be only fonts that suffer from issue. That's an issue in Webpack's file-loader module which is reported here https://github.com/webpack/file-loader/issues/62

**Comment by saharj** [comment]
I've reverted 5408972 but this doesn't mean we will not fix this in the next release. We need to fix it properly.
