### ISSUE TITLE
External schema reference

### ISSUE THREAD

**Issue by Priyanky** [swagger-api/swagger-editor#931]
I am using swagger for visualization using Swagger editor, generate request/response and host a mock server for the backend API. 

My locally hosted version of Swagger Editor , shows  error when my swagger json/yaml has external reference . However as per this [Open API doc link](https://github.com/OAI/OpenAPI-Specification/blob/master/guidelines/REUSE.md) this should work good. Any idea why it is not working
eg:- swagger config

    post:
      description: Create abc
      operationId: abc.create
      responses:
        200:
          description: Successful response
          schema:
            $ref: http://127.0.0.1:8080/schema/response/abc.json

Error

Not a valid response definition
Jump to line 79
Details
 Object
code: "ONE_OF_MISSING"
 params: Array [0]
message: "Not
 a valid response definition"
 path: Array [5]
schemaId: "http://swagger.io/v2/schema.json#"
 inner: Array [2]
level: 900
type: "Swagger
 Error"
description: "Not
 a valid response definition"
lineNumber: 79

I tried relative path also for $ref: ./schema/response/abc.json

**Comment by saharj** [comment]
It can be CORS issues. Please read here: https://github.com/swagger-api/swagger-editor/blob/master/docs/cors.md

**Comment by ashwin-krishnamurthy** [comment]
@saharj The link you've provided results in a 404. Could you provide a more current version of that document?
