### ISSUE TITLE
Cant import the yaml file in editor swagger

### ISSUE THREAD

**Issue by cshar7** [swagger-api/swagger-editor#938]
Hi, I am new to the swagger editor and i m writing one document on the API used in my project.

I want the editor.swagger should be opened directly using my yaml file on click.
syntax i used in my documentation is - 
http://editor.swagger.io/#/?import=https://github.com/DigitalInnovation/api-wcs-tests/blob/promises/swagger/login.yaml

All yaml files are located in one repository of github.
But this is not working. is there any way to do it.

Thanks

**Comment by chitampopo** [comment]
Hi @cshar7,

Your URL https://github.com/DigitalInnovation/api-wcs-tests/blob/promises/swagger/login.yaml get 404 error and I can't import it.

You can should try with raw link. I've test with https://raw.githubusercontent.com/chitampopo/publicweb/master/petstore_simple.yaml and it's ok.

**Comment by saharj** [comment]
After you open http://editor.swagger.io/#/, you can import a file or an URL using the `File` tab.

**Comment by saharj** [comment]
Also if you're using import query parameter accessing a private file you should provide `no-proxy` argument.

**Comment by cshar7** [comment]
I tried that too but it dint work.. can u give me the correct syntax of it please. Also i dont want to use the feature of - you can import a file or an URL using the File tab.

**Comment by chitampopo** [comment]
@cshar7 This is my URL
http://editor.swagger.io/#/?import=https://raw.githubusercontent.com/chitampopo/publicweb/master/petstore_simple.yaml

**Comment by cshar7** [comment]
Yes i am able to see this yaml file. but then y my link is not working- 

http://editor.swagger.io/#/?import=https://github.com/DigitalInnovation/api-wcs-tests/blob/promises/swagger/login.yaml

Is it because the "api-wcs-tests" is the private repository in github. may be some security concern ? i dnt have any idea such.

**Comment by saharj** [comment]
Yes, Swagger Editor is not able to get the information from private repositories.
