### ISSUE TITLE
Can't enable cookies in swagger editor

### ISSUE THREAD

**Issue by ibrahimovfuad** [swagger-api/swagger-editor#939]
I am using swagger editor and i need to access to cookies but i cant enable it. i read about swagger-ui and about enabling cookies from swagger-ui but i cant implement it to swagger-editor.

**Comment by saharj** [comment]
Cookie is just a header. You can define a header parameter for it.

**Comment by viczem** [comment]
Test in Chromium browser. Version 63 (last)
```
...
host: 'localhost:8000'
schemes:
  - http
...
paths:
  '/api/users':
    parameters: 
      - in: header
        name: cookie
        type: string
        required: true
        enum: [' uid=3495345']
    get:
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
```

Response headers:
```
access-control-allow-credentials:true
access-control-allow-headers:Content-Type, *
access-control-allow-methods:POST, GET, OPTIONS, HEAD, PUT, DELETE
access-control-allow-origin:http://localhost:8080
```
Generated curl in Swagger editor: `curl -X GET "http://127.0.0.1:8000/api/users" -H "accept: application/json" -H "cookie: uid=3495345"` is work. But when I send the request from the browser the cookies is empty.
