### ISSUE TITLE
Take code from Yaml

### ISSUE THREAD

**Issue by davidhd0911** [swagger-api/swagger-editor#940]
Hi! 
I'm trying to get code from yaml for spring mvc and in header it appears "Server code generator is unreachable!" and "Client code generator is unreachable!" so I can't get it.

Regards,
David

**Comment by saharj** [comment]
Do you still have this issue?

**Comment by saharj** [comment]
It's possible that codegen server was down at that moment. Please let me know if you're still having this issue.
