### ISSUE TITLE
error generating model for valid swagger document

### ISSUE THREAD

**Issue by stoicflame** [swagger-api/swagger-editor#942]
When I paste [this JSON](https://github.com/swagger-api/swagger-editor/files/273231/swagger.json.txt) into the Swagger editor, I get no validation errors. But when I attempt to download a client library, I get:

> Could not process model 'xml_ns0_category'

Having looked at `xml_ns0_category`, I don't see anything wrong with it and the error message isn't particularly helpful.

**Comment by saharj** [comment]
This issue was moved to swagger-api/swagger-codegen#2918
