### ISSUE TITLE
How can I enable swagger editor in my website?

### ISSUE THREAD

**Issue by srinivascodes** [swagger-api/swagger-editor#946]
**Note on code generation issues**
Please open an issue in [Swagger Codegen](https://github.com/swagger-api/swagger-codegen) repository for any issue with generating code or issues with generated codes.

**My Swagger**

```yaml
 # paste your swagger document here
```

* Swagger Editor version(from Help > About menu): 
* My browser: 

**Issue**

**Comment by srinivascodes** [comment]
@saharj Please kindly tell me the wat how can i enable swagger editor in my website?

**Comment by saharj** [comment]
You can use `iframe` for that.

**Comment by srinivascodes** [comment]
@saharj I need to make it the part of my website without `iframe` so what are the source files and scripts that I need to include in `<script> `tag to make it part of my website? Please kindly help.
