### ISSUE TITLE
How to disable menu items using config/defaults?

### ISSUE THREAD

**Issue by srinivascodes** [swagger-api/swagger-editor#949]
**Note on code generation issues**
Please open an issue in [Swagger Codegen](https://github.com/swagger-api/swagger-codegen) repository for any issue with generating code or issues with generated codes.

**My Swagger**

```yaml
 # paste your swagger document here
```

* Swagger Editor version(from Help > About menu): 
* My browser: 

**Issue**

**Comment by srinivascodes** [comment]
@saharj
I saw in `configuration.md` that we can disable fileMenu. I am trying to disable few menu items like preferences, generateserver , generateclient, help menu items by introducing keys in config/defaults but unable to do it. Please kindly give me the steps to disable these file menu through making changes in config/defaults.json and header.js.

**Comment by SandeshSarfare** [comment]
Hey @srinivascodes can you help me with the error in below screen
![image](https://cloud.githubusercontent.com/assets/16500341/15530375/998e779e-2271-11e6-82ca-f36b05b27df0.png)

**Comment by mohsen1** [comment]
@srinivascodes 
If you want to make a lot of changes why don't you just fork this repo and make those changes manually?
