### ISSUE TITLE
Not a valid parameter definition Swagger.json

### ISSUE THREAD

**Issue by SandeshSarfare** [swagger-api/swagger-editor#950]
I am trying to validate swagger.json but there is one error which is holding me back which is "Not a valid parameter definition"
And below is the snap from editor.
Please help me with this if anyone knows the answer to it

![image](https://cloud.githubusercontent.com/assets/16500341/15565614/8e0e82ec-2339-11e6-9aea-1f737f726380.png)

**Comment by SandeshSarfare** [comment]
I also tried to play with format type for definition but wasn't worth

**Comment by fehguy** [comment]
Hi, that format `JSON` is not supported.  You'll have to leave it as `string` without a format for now

**Comment by SandeshSarfare** [comment]
I had already tried it but it gave me the same error ....eventually I had to remove that method to avoid error however now I am getting warning as "Definition is not used: #/definitions/x-any" and I have exported that to YAML format to import on aws api gateway

**Comment by mohsen1** [comment]
I see that you have a parameter `in: form`. That's not a valid `in` value.

**Comment by fehguy** [comment]
@SandeshSarfare the Amazon API Gateway doesn't support all features in the Swagger Specification.  You can read up on their docs, or use the API Gateway integration on SwaggerHub to do this for you.

**Comment by SandeshSarfare** [comment]
I am can see the api on swaggerhub and integrated with amazon api gateway now how will I Check if its working and I need to keep it private

**Comment by fehguy** [comment]
You'll need to log into the Amazon Gateway console and test it there.  I suggest you move your question over to the SwaggerHub support forum https://community.smartbear.com/swaggerhub

**Comment by SandeshSarfare** [comment]
Ok @fehguy...i already did it

**Comment by SandeshSarfare** [comment]
@fehguy I can't see my api in amazon aws console
