### ISSUE TITLE
Can't import file twice

### ISSUE THREAD

**Issue by dolmen** [swagger-api/swagger-editor#951]
* Swagger Editor version(from Help > About menu): editor.swagger.io 2.10.1
* My browser: Firefox 46.0

**Issue**:
- *File* > *Import file...*
- select a valid JSON spec
- *Import* button
- *File* > *Import file...*
- select the same file
- Can't click on *Import* button: it is blocked with a forbidden mouse cursor

**Comment by saharj** [comment]
I could not reproduce it. Do you still have this issue?

**Comment by saharj** [comment]
Closing this issue due to no response.
