### ISSUE TITLE
Invalid warnings about extra JSON Reference properties "title"

### ISSUE THREAD

**Issue by dolmen** [swagger-api/swagger-editor#952]
**My Swagger**

See attached file: [api-user.json.txt](https://github.com/swagger-api/swagger-editor/files/286435/api-user.json.txt) (GitHub rejects .json extension)
- Swagger Editor version(from Help > About menu): http://editor.swagger.io/ 2.10.1
- My browser: Firefox 46.0

**Issue**
Invalid warnings:
- "Swagger warning: Extra JSON Reference properties will be ignored: title" line 324
- "Swagger warning: Extra JSON Reference properties will be ignored: title" line 508

But the only "title" property in the file is at the root of the document, never along a JSON Reference.

**Comment by dolmen** [comment]
I think the problem doesn't come from my file but from the JSON Schema for Swagger 2.0 or from a bug in the JSON Schema validator that use the schema.

**Comment by chrisdudley** [comment]
It seems to be the definitions that are just $refs to other definitions that it doesn't like.
e.g. <pre>      "DeviceTag": {
         "$ref": "#/definitions/Tag"
      },</pre>
But I can't see anything in the spec to say that isn't allowed.

**Comment by fehguy** [comment]
Correct, that _is_ technically supported but I believe the tooling (including the editor) doesn't like it.

**Comment by dolmen** [comment]
One more workaround to implement in my preprocessor :(

Note that swagger-ui correctly renders that model.

**Comment by saharj** [comment]
@dolmen please follow this issue here: https://github.com/whitlockjc/json-refs/issues/86

**Comment by webron** [comment]
This is no longer an issue with the new editor.
