### ISSUE TITLE
Unknown error when invalid $ref is used

### ISSUE THREAD

**Issue by ePaul** [swagger-api/swagger-editor#955]
**My Swagger**

```yaml
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /:
    get:
      responses:
        200:
          $ref: "#responses/example"
```

(Yes, I know that it is invalid, that's the point.)

* Swagger Editor version(from Help > About menu): 2.10.1 (currently on editor.swagger.io)
* My browser: Chromium 50.0.2661.102 Ubuntu 16.04 (64-bit)

**Issue**

If I have an invalid JSON pointer in one of my `$ref` attribute, the editor shows an non-helpful error message:

```
✖ Unknown Error
ptr must be a JSON Pointer
Jump to line
Details
 Object
message:  "ptr must be a JSON Pointer"
code:  "UNCAUGHT_SWAY_WORKER_ERROR"
level: 900
type:  "Unknown Error"
description:  "ptr must be a JSON Pointer"
```
![swagger-editor-error](https://cloud.githubusercontent.com/assets/645859/15683125/197c2746-2761-11e6-8d18-9cfa16980b92.png)

The "Jump to line" link jumps to some random line (in the example above line 7, which has just the `/`).

**Expected behavior**

It would be nice if that error message showed in which $ref the error occurred (as a line number, and/or as a path to the problematic place, as for other validation errors), and maybe also said in which way the value is not a JSON pointer (in the case here, the `/` is missing after the `#`).

In a real-live API one can have hundreds of `$ref`s, and many API designers even might not know that those are JSON pointers (i.e. that something is wrong with the `$ref`s).

**Comment by kgalli** [comment]
👍  This would be a very nice improvement.

**Comment by saharj** [comment]
This issue was moved to apigee-127/sway#84
