### ISSUE TITLE
Query parameters are not properly encoded

### ISSUE THREAD

**Issue by honnix** [swagger-api/swagger-editor#956]
**Note on code generation issues**
Please open an issue in [Swagger Codegen](https://github.com/swagger-api/swagger-codegen) repository for any issue with generating code or issues with generated codes.

**My Swagger**

```yaml
 # any yaml file with at least one query parameter, the value could be for example id=a#b
```

* Swagger Editor version(from Help > About menu): 
Version 2.10.1

* My browser: 
I have tried Safari and Firefox.

**Issue**
Query parameters are not properly encoded when calling $.ajax in makeCall https://github.com/swagger-api/swagger-editor/blob/13f98d911e74a86e0d0d1f74155dd51777858d52/scripts/directives/tryoperation.js#L791

Actually what is the reason decoding the query string here https://github.com/swagger-api/swagger-editor/blob/13f98d911e74a86e0d0d1f74155dd51777858d52/scripts/directives/tryoperation.js#L571

Thanks!

**Comment by saharj** [comment]
Could you please provide your swagger and your expected url?

**Comment by honnix** [comment]
Let's take a simplest one.

```
swagger: '2.0'
info:
  version: 0.1.0
  title: Test
host: example.com
basePath: /
schemes:
  - http
paths:
  /test:
    get:
      operationId: test
      parameters:
        - in: query
          name: id
          required: true
          type: string
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              type: string
```
Assign the value `abc#def` to parameter `id`, then the requested URL will be `http://example.com/test?id=abc` instead of `http://example.com/test?id=abc%23def`. If the assigned value is `abc%23def` then everything is fine.

**Comment by saharj** [comment]
Please help me understand this.
The URL I get is `http://example.com/test?id=abc#def`. Does the format have to be `http://example.com/test?id=abc%23def`?

**Comment by honnix** [comment]
Yes. # shall be encoded, otherwise when click the send button, the requested URL would become http://example.com/test?id=abc , at least on Safari and Firefox.

Best regards, Hongxin
On Fri, Jun 3, 2016 at 00:42, Sahar Jafari <notifications@github.com> wrote:
Please help me understand this.
The URL I get is http://example.com/test?id=abc#def . Does the format have to be http://example.com/test?id=abc%23def ?
