### ISSUE TITLE
Server not found with Basic authentication

### ISSUE THREAD

**Issue by yukonn** [swagger-api/swagger-editor#957]
I try to test OData(v3) web service(WCF) with swagger editor 2.10.1. I used basic authentication to access the web service. But i always get "ERROR Server not found or an error occurred"

**My Swagger**

```yaml
 ---
swagger: '2.0'
info:
  version: "1.0.0"
  title: Basic Auth Example
  description: |
    An example for how to use Basic Auth with Swagger.
    Server code is available [here](http://navm3.cloudapp.net:90/nav/odata). It's running on NAVM3.

    **You can use below User Name and Password for test.**
    * User Name: `ODATA`
    * Password: `qtkr47PTM3pmzLyEHNrW4DXhhgyjMfM3CKUZfXdn0tk=`
host: navm3.cloudapp.net:90
basePath: /nav/odata
schemes:
  - http
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`
paths:
  /:
    get:
      security:
       - basicAuth: []
      responses:
        200:
          description:  Will send `Authenticated` if authentication is succesful, otherwise it will send `Unauthorized`
```

* Swagger Editor version(Version 2.10.1): 
* IE 10, FF38.05: 

**Issue**
Server not found with Basic authentication
Browser
![swagger1](https://cloud.githubusercontent.com/assets/14740258/15715779/5ee4ee84-2852-11e6-8eca-054133cdccdb.png)

Fiddler
![swagger](https://cloud.githubusercontent.com/assets/14740258/15715473/22fd991c-2851-11e6-80ea-eb12c0c25d3c.png)

I to new on this, i not sure editor issue or something miss on my yaml.

Regards,

**Comment by fehguy** [comment]
By definition, the `OPTIONS` call can **not** be secured.  Please see that you can remove the basic auth requirement from the options call then it should work.

**Comment by yukonn** [comment]
Hi,
     Thanks for your reply. I try as you mention. But still same error. If i not wrong authentication is not bring when i submit. Please take a look my fiddler screenshot.

Regards,

**Comment by MichaelRodrigues** [comment]
Yukonn. Did you solved the problem? I have a same problem.

**Comment by yukonn** [comment]
Hi Michale,

     Sorry, i can't not solved it. I got this error at Swagger Editor. I get data if i use my swagger file with Swagger-UI.

Regards,
Yukon

**Comment by MichaelRodrigues** [comment]
Hi Yukonn,

i solved it.

In the my case, i am doing the back-end with nodeJS, and the problem was with CORS, i enabled the cors.

To enable the CORS in nodeJS you can add the below code, before of the routes.
```
    var app = express();

    app.use(function(req, res, next) {

        res.setHeader('Access-Control-Allow-Origin', '*');

        res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, UPDATE, DELETE, OPTIONS');

        res.setHeader('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept, Authorization');

        next();

    });
```

**Comment by saharj** [comment]
I am going to close this issue. Please let us know if you still have this issue and you think this should stay open.
