### ISSUE TITLE
Where can I find gulp file of the editor? 

### ISSUE THREAD

**Issue by srinivascodes** [swagger-api/swagger-editor#964]
@@**Note on code generation issues**
Please open an issue in [Swagger Codegen](https://github.com/swagger-api/swagger-codegen) repository for any issue with generating code or issues with generated codes.

**My Swagger**

```yaml
 # paste your swagger document here
```

* Swagger Editor version(from Help > About menu): 
* My browser: 

**Issue**

**Comment by saharj** [comment]
This project is not using gulp.

**Comment by srinivascodes** [comment]
@saharj Is it using grunt then? How the dist folder is created and how the minified files are created in the dist folder like bundle.js and styles.css?

**Comment by saharj** [comment]
This project is using Webpack.
