### ISSUE TITLE
npm install is encountering errors using master build

### ISSUE THREAD

**Issue by stevendearborn** [swagger-api/swagger-editor#966]
See here:

https://github.com/adobe-fonts/source-code-pro.git#release
npm ERR! not a package /var/folders/22/7s2ksb0j2z97bnv8m0wrjjx00000gn/T/npm-23901-weNgPBDX/1465223745370-0.0772964193020016/tmp.tgz

on pm install after pull on master

**Comment by saharj** [comment]
Can you try again? Maybe GitHub had issues at that moment. Source Code Pro is downloaded from GitHub during the build process.

**Comment by saharj** [comment]
Closing this issue due to no response.
