### ISSUE TITLE
"Try this operation" should supports discriminator?

### ISSUE THREAD

**Issue by marcusnaweb** [swagger-api/swagger-editor#967]
``` yaml
definitions:
 Document:
    type: object
    required:
      - type
    discriminator: type
    properties:
      code:
        type: string
      type:
        type: string
        enum:
          - RG
          - CPF
          - Passport

  RG:
    type: object
    allOf:
    - $ref: '#/definitions/Document'
      properties:
        issuingAuthority:
        type: string

  CPF:
    type: object
    allOf:
    - $ref: '#/definitions/Document'

  Passport:
    type: object
    allOf:
    - $ref: '#/definitions/Document'
    properties:
      expirationDate:
        type: string
        format: date

```

v2.10.1

Chrome/50.0.2661.86

Hi all. Considering a instance of Document with "type" populated with "RG", should "Try this operation" show properties of #/definitions/RG? Currently, it doesn't (or i'm doing something wrong).
![captura de tela de 2016-06-06 14-40-41](https://cloud.githubusercontent.com/assets/6969675/15832207/845ea2ba-2bf7-11e6-8b48-bfd8c1fd566a.png)
Thanks in advance.

**Comment by marcusnaweb** [comment]
I figured out that the model needs a "subTypes" attribute saying the expected inheritances, but looks like that the editor doesn't support subTypes yet, amirite?

**Comment by saharj** [comment]
Apparently `discriminator` is not supported by Swagger yet. 

https://github.com/OAI/OpenAPI-Specification/issues/333

**Comment by marcusnaweb** [comment]
It's a bit confusing: [The spec(?)](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) actually covers discriminator:

![image](https://cloud.githubusercontent.com/assets/6969675/15893136/2c3be6a2-2d54-11e6-9740-0437d4709907.png)

But there's something in discussion, as you have pointed out. Please disconsider the subTypes thing, it's not on the spec.

**Comment by camminati** [comment]
Hi,
here a bit of the same Problem, please tell me if I am using this wrong or is this a missing feature:

![image](https://cloud.githubusercontent.com/assets/5380553/19516356/e71686ca-95fb-11e6-9dd2-6fb02cf47acd.png)

I derive the `SubTypeA` and `SubTypeB` from `baseType`. But when trying-out the operation, the editor uses the baseType hard, and not one of the Subtypes. (this is actually how I generate this from Java, which is a hint, but could also be wrong because I went all out making `@Apimodel` annonations).

Swagger warns me, that the subtypes are not used, which is actually true, but I would expect to infer the types via the `allOf` reference.

Here is the code if you want to try it out:
```
swagger: '2.0'
info:
  version: 0.0.1
  title: polymorphism example
paths:
  /system:
    post:
      summary: some text
      description: some text
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: "#/definitions/request"
      responses:
        200:
          description: "OK"
definitions:
  request:
    type: object
    required:
    - container
    properties:
      container:
        type: array
        description: some description
        items:
          $ref: "#/definitions/baseType"
  baseType:
    type: object
    discriminator: code
    properties:
      code:
       type: string
  SubTypeA:
    allOf:
    - $ref: "#/definitions/baseType"
    - type: object
      properties:
        A:
          type: string
  SubTypeB:
    allOf:
    - $ref: "#/definitions/baseType"
    - type: object
      properties:
        B:
          type: "string"
```
I even try to make the references in an enum (like for values), but then it gets really weird:
![image](https://cloud.githubusercontent.com/assets/5380553/19516674/516921e4-95fd-11e6-99ad-bbddf532a8ce.png)

**Comment by alessandrousseglioviretta** [comment]
[ReDoc](https://github.com/Rebilly/ReDoc) supports `discriminator`, check it out

**Comment by webron** [comment]
While this is true, now the source of it is in swagger-ui, and there's a ticket for that there. Closing.

**Comment by camminati** [comment]
@webron could you refer the mentioned ticket please?

**Comment by webron** [comment]
https://github.com/swagger-api/swagger-ui/search?q=discriminator&state=open&type=Issues&utf8=%E2%9C%93

**Comment by camminati** [comment]
thanks, sad to hear that is out of scope for the time being. For documentation purposes though,  [ReDoc](https://github.com/Rebilly/ReDoc) (as suggested by @alessandrousseglioviretta looks pretty neat. I'm only missing the possibility sending requests like in Swagger-Editor, which is, what I suppose the difficult part.

**Comment by webron** [comment]
@camminati it's not out of scope as much as it is a lower priority. We have limited resources, but as always, we'd love to get community contributions to support it.
