### ISSUE TITLE
Unable to generate dist/ folder properly

### ISSUE THREAD

**Issue by srinivascodes** [swagger-api/swagger-editor#970]
I am trying to generate the dist folder using gulp by running this following code. 
`gulp.task('swaggerbuild',function () {
 var build=gulp.src('./swagger/index.js');
  return build.pipe(webpack(require('./swagger/webpack.config.js'))).pipe(gulp.dest('./swagger/dist/'));
});`

but in the dist folder all the font files are missing even though i have download all the required font modules. Please kindly help me in eradicating this problem. please tell me where I am wrong or making mistake or lacking.

**Comment by saharj** [comment]
As I mentioned earlier, we are not using gulp in this project.
In order to generate the `dist` folder, after you clone the repository, you need to run `npm run build` in the command line.

**Comment by saharj** [comment]
Also, we don't know much about `gulp`. If you want a good answer for your question, maybe it's better to ask it somewhere else like [stackoverflow.com](http://stackoverflow.com/).
