### ISSUE TITLE
Can't stop swagger editor web service 

### ISSUE THREAD

**Issue by qxt1126** [swagger-api/swagger-editor#971]
**Note on code generation issues**
Please open an issue in [Swagger Codegen](https://github.com/swagger-api/swagger-codegen) repository for any issue with generating code or issues with generated codes.

**My Swagger**

```yaml
 # paste your swagger document here
```

* Swagger Editor version(from Help > About menu): 
* My browser: 

**Issue**
When I start Swagger editor locally from Node.js command window, you can see the Swagger web service is running. 
![image](https://cloud.githubusercontent.com/assets/17728373/15897108/19778672-2d61-11e6-8a85-c0c2b773aa8d.png)
But when I close Node.js command window, the Swagger editor web service is still running. 
![image](https://cloud.githubusercontent.com/assets/17728373/15897122/2ece213e-2d61-11e6-9983-17efffac7f4c.png)

How can I totally close Swagger editor web service or stop it?

**Comment by saharj** [comment]
The development server is a Node.js process. Depending on your OS you can kill that process fairly easily.
