### ISSUE TITLE
overriding parameters on remote operations object

### ISSUE THREAD

**Issue by mattgocc** [swagger-api/swagger-editor#972]
**My Swagger**

```yaml
swagger: '2.0'
info:
  title: operation
  description: operation
  version: "0.0.1"
host: localhost
schemes:
  - https
basePath: /operation
produces:
  - application/json

################################################################################
#                                   Paths                                      #
################################################################################
paths:
  /operation:
    $ref: 'https://raw.githubusercontent.com/mattgocc/test/master/operations.yaml#/operation'
    parameters:
      - name: param2
        in: body
        required: true
        schema:
          type: string
        
```

* Swagger Editor version(from Help > About menu): 2.10.1
* My browser: firefox

**Issue**
Hello,

I would like to be able to take use the yaml for generating the swagger document for another API, and use it to create endpoints with similar, but different, definitions. For example, I would like to take the endpoint and add an extra parameter required in the message body (which is JSON).

I have tried to do this by extracting the operation for an endpoint into its own yaml file, referencing it in my yaml, and adding another parameters property after the $ref, but I get a warning saying 'Extra JSON Reference properties will be ignored: parameters'. I can understand that adding to existing parameters might be problematic, but can I override all of the parameters somehow for my externally referenced operation somehow?

Thanks,
Matt

**Comment by saharj** [comment]
What you're trying to do is not possible with editor. You might be able to achieve this using a Node.js program that resolves Swagger the way you want it.

**Comment by mattgocc** [comment]
Thanks, I assumed that that was the case, but it's nice to have confirmation.

I'll try to work around it by instead extracting each individual parameter and each individual response. I assume that, similarly, there is no way for me to reference a remote collection of parameters, and to add another to parameter to the collection?
