### ISSUE TITLE
How to set the $rootscope.editorValue using a non-default file?

### ISSUE THREAD

**Issue by srinivascodes** [swagger-api/swagger-editor#973]
I want to bring a JSON file of my API from database and then I want to display that particular file inside the editor **without using Import URL** functionality. I am successfully fetching the file but I am unable to display it. I have found that i can set `$rootscope.editorValue` to display but I am not finding the place/file where should I set this value.  Please tell me the way to do it.

**Comment by srinivascodes** [comment]
@saharj please tell me the way to perform the following:
After clicking on an API, the document of that API needs to be fetched from the db and then displayed it automatically on the editor. I am successfully fetching the API JSON doc but unable to display it directly.

**Comment by webron** [comment]
This is no longer relevant in the new editor.
