### ISSUE TITLE
Support relative references

### ISSUE THREAD

**Issue by pgtelus** [swagger-api/swagger-editor#977]
Please add support for relative references to other files.  E.g. if I have an API split into multiple files in my working location:

- MyAPI1.yaml
- MyAPI2.yaml
- MyCommonStructures.yaml

... and I want the two API files to relatively refer to the common structures, e.g.:

$ref: MyCommonStructures.yaml#YadaYada

It would be very convenient to be able to work in the editor with these relative references so that user doesn't need to find/create some mechanism to host the files at some absolute location.

Some possible ideas:

- If the user opens/imports a file then use the base path of that location as the relative reference point (this would be most useful for me)
- An editor setting to allow the user to specify the relative base location
- if neither of the above is selected then by default the relative location would be the editor host URL

**Comment by dolmen** [comment]
When importing a file the editor has no idea of the original location of the file on your filesystem: this is a limit of the browser to protect your files.
Fo a similar reason, the editor which runs at `http://editor.swagger.io` can not access data on another domain or URI scheme such as `file:///...`
So this request is not implementable.

**Comment by pgtelus** [comment]
What about letting the user specify the relative root location on a local filesystem, can that be done?

**Comment by dolmen** [comment]
> What about letting the user specify the relative root location on a local filesystem, can that be done?

An app running in a browser can't access file on a local filesystem. End of game.

**Comment by RodH257** [comment]
Could we import the referenced files ourselves? Ie have an 'import references' feature where we select the referenced files and then the editor uses that when it sees a `$ref` ?

**Comment by saharj** [comment]
We're using [Sway](https://github.com/apigee-127/sway) which uses [JSON Refs](https://github.com/whitlockjc/json-refs) for resolving JSON Pointers. JSON Refs is using [Path Loader](https://github.com/whitlockjc/path-loader) for loading URLs.

Path loader has [`PrepareRequestCallback`](https://github.com/whitlockjc/path-loader/blob/master/docs/API.md#pathloaderpreparerequestcallback--function) option that allows us to override the request location. With that I thought we can replace the request location based on an option set by Swagger Editor user.

If we override origin and base path for each request in `PrepareRequestCallback` during resolution of `$ref`s we will have a working remote resolver. Even if a remote JSON Pointer result have another `$ref` that points to another relative remote JSON Pointer.

Here is an example:

**`index.swagger.yaml`**
```yaml
root:
  $ref: './a.yaml'
```

**`a.yaml`**
```yaml
a: 
  $ref: '../b.yaml'
```

**`b.yaml`**
```yaml
foo: bar
```

Lets say `index.swagger.yaml` is located at `example.com/swaggers/my-swagger/index.swagger.yaml` but we're trying to edit it in Swagger Editor, so we copy the contents to Swagger Editor and tell Swagger Editor to resolve all `$ref`s from `example.com/swaggers/my-swagger` base. 

* `a.yaml` will get requested to `editor.swagger.io/a.yaml` but we override the base with `example.com/swaggers/my-swagger` and it resolves fine
* `b.yaml` will get requested to `editor.swagger.io/../a.yaml` but we override the base with `example.com/swaggers/my-swagger` and resolve it to `example.com/swaggers/my-swagge/../b.yaml` and it will resolve fine as well.

My plan is to add an option to preferences for the base URL of resolving `$ref`s and use that in `$ref` resolution.

**Comment by saharj** [comment]
@pgtelus @dolmen @RodH257 please checkout #1000 and let me know if it works for you.

**Comment by saharj** [comment]
You can try this feature in http://editor.swagger.io now

**Comment by jstephens7** [comment]
Is it not possible to import your entire swagger folder to accomplish the same result?

Say you have your swagger folder containing:
- index.swagger.yaml
- a.yaml
- b.yaml
(possibly subdirectories also)
And import that in your swagger editor. Wouldn't that allow you to resolve the references in the same way they are resolved in your application (node for instance)?

**Comment by alonbl** [comment]
Hi,
Any update on this? I cannot see any option to edit multi-file swagger spec in the editor. Reopen?
Thanks!

**Comment by jstephens7** [comment]
We decided to just build our swagger file from partials on startup.
We have a _defaults which contains our base objects and we just make a copy for each of our specific set of routes. Each file is a full swagger file so it can be opened standalone in the editor, but on start up we pull in all the routes to a main swagger file which is used by swagger.
E.G.
api/swagger
_defaults.yml (contains shared definitions)
message.yml (contains /message routes and shared definitions)
swagger.yaml (contains /message and /user routes and shared definitions)
user.yml (contains /user routes and shared definitions)

We do the names like this so that we can only watch the .yml files for changes with nodemon and also so that our main swagger.yaml builder ignores the swagger.yaml file itself. Hope this helps.
