### ISSUE TITLE
Using Swagger with Zxing.org to make a barcode reading API

### ISSUE THREAD

**Issue by trifwnas** [swagger-api/swagger-editor#979]
**My Swagger**

``` yaml
{
    "swagger": "2.0",
    "info": {
        "version": "v1",
        "title": "BarcodeScanner",
        "description": "A BarcodeScanner API"
    },
    "host": "zxing.org",
    "schemes": [
        "http"
    ],
    "basePath": "/w",
    "paths": {
        "/decode": {
            "post": {
                "tags": [
                    "decode"
                ],
                "operationId": "barcode_post",
                "consumes": [
                  "multipart/form-data"
                  ],
                "produces": [
                    "application/json",
                    "text/json",
                    "application/xml",
                    "multipart/form-data",
                    "text/html"
                ],
                "parameters":[
                        {
                            "name":"f",
                            "in":"formData",
                            "description":"file with barcode to upload",
                            "required":true,
                            "type":"file"
                    },
                    ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string",
                            "items": {
                                "$ref":"#/definitions/barcode"
                            }
                        }
                    }
                },
                "deprecated": false
            }
        },
    },
    "definitions": {
        "barcode": {
            "type": "object",
            "properties": {
                "Id": {
                    "format": "int32",
                    "type": "integer"
                },
                "Name": {
                    "type": "string"
                },
                "BarcodeNumber": {
                    "type": "string"
                }
            }
        }
    }
}
```

**Issue**
http://stackoverflow.com/questions/37955006/using-swagger-with-zxing-org-to-make-a-barcode-reading-api

Hi,
I am trying to use the online swagger editor (editor.swagger.io) in order to create a post request to the Zxing barcode reader web app (zxing.org/w/decode.jspx) and get back the decoded barcode data. In Postman I use the parameter "f" and the setup below and it works. Please help me fix my swagger file! Thank you in advance! :)

FYI, the web app uses the below form:
`<form enctype="multipart/form-data" method="post" action="decode"><tr><td style="text-align:right">Or upload a file (&lt;10MB, &lt;10MP):</td>
<td> <input name="f" type="file"/></td><td><input type="submit"/></td></tr></form>`

![1nmzo](https://cloud.githubusercontent.com/assets/6863495/16260284/031c9a64-3867-11e6-88a0-d1d2c5fd8c30.png)

**Comment by saharj** [comment]
It's possible that your server (zxing.org) is not allowing such request. Please read [here](https://github.com/swagger-api/swagger-editor/blob/master/docs/cors.md) for more information.

**Comment by trifwnas** [comment]
Hi @saharj ,

Thank you for your answer. 
Have you tried changing anything on my code or it should work as is ?

FYI, the web app uses the below form (I have included it in the issue above.)

`<form enctype="multipart/form-data" method="post" action="decode"><tr><td style="text-align:right">Or upload a file (&lt;10MB, &lt;10MP):</td><td>
<input name="f" type="file"/></td><td><input type="submit"/></td></tr></form>`

**Comment by webron** [comment]
@trifwnas - this is indeed a CORS issue. It works well from Postman because it doesn't have the same browser limitations. It works from the basic web form because that's how HTML works. It will not work for web apps though, unless either CORS is enabled on the server itself or if you're using a CORS proxy to add the relevant headers. This is a browser limitation and not something we can control.

**Comment by trifwnas** [comment]
Hi @webron ,

Thank you for your answer.
It was actually a CORS issue and since I have enabled it in my own copy of zxing.org, the requests are being successfully sent to the server (on Azure).

The problem I am facing now is that I get back the response for sending a bad URL so there is probably something wrong on the way the request is being sent from the editor. Could you please help me fix it?

Thank you in advance.

Below is my swagger code:
`{
    "swagger": "2.0",
    "info": {
        "version": "v1",
        "title": "BarcodeScanner",
        "description": "A BarcodeScanner API"
    },
    "host": "barcodewebapppowerax.azurewebsites.net",
    "schemes": [
        "http"
    ],
    "basePath": "/w",
    "paths": {
        "/decode": {
          "get": {
                "tags": [
                    "barcode"
                ],
                "operationId": "barcode_get",
                "consumes": [
                  "text/html;charset=UTF-8"
                  ],
                "produces": [
                    "application/json",
                    "application/xml"
                ],
                "parameters":[
    					{
    						"name":"u",
    						"in":"formData",
    						"description":"url with barcode",
    						"required":true,
    						"type":"string"
    				},
                    ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string",
                            "items": {
                                "$ref": "#/definitions/barcode"
                            }
                        }
                    }
                },
                "deprecated": false
            },
            "post": {
                "tags": [
                    "decode"
                ],
                "operationId": "barcode_post",
                "consumes": [
                  "multipart/form-data"
                  ],
                "produces": [
                    "application/json",
                    "text/json",
                    "application/xml",
                    "multipart/form-data",
                    "text/html"
                ],
                "parameters":[
                        {
                            "name":"f",
                            "in":"formData",
                            "description":"file with barcode to upload",
                            "required":true,
                            "type":"file"
                    },
                    ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string",
                            "items": {
                                "$ref":"#/definitions/barcode"
                            }
                        }
                    }
                },
                "deprecated": false
            }
        },
    },
    "definitions": {
        "barcode": {
            "type": "object",
            "properties": {
                "File": {
                    "type": "string"
                },
                "BarcodeNumber": {
                    "type": "string"
                }
            }
        }
    }
}`

**Comment by webron** [comment]
The problem seems to be with your personal installation on Azure. I've uploaded the same file to both your instance and the original (using the direct website for both) - it didn't work in yours and worked in the original.
![barcode](https://cloud.githubusercontent.com/assets/241629/16344530/df0da78a-39f1-11e6-99f9-3ae30607b369.png)

**Comment by trifwnas** [comment]
Hi @webron ,

There was an error in the file upload form but now it is fixed. The url form, though, was working properly.
Please try again here: [barcodewebapppowerax.azurewebsites.net](barcodewebapppowerax.azurewebsites.net)

**Comment by webron** [comment]
@saharj - now it looks like the request is not being built properly. Can you look into that? The payload ends up being just `f: barcode.png` where it should be:

```
Content-Type: multipart/form-data; boundary=---------------------------13326974253911837651178094888
Content-Length: 4290

-----------------------------13326974253911837651178094888
Content-Disposition: form-data; name="f"; filename="barcode.png"
Content-Type: image/png

PNG


IHDRÜ8ÈbKGDÿÌ¿	pHYsgÒR
SIDATxÚí{tUÕÇ?÷&!oò$Ä	ÊF](±Zl)Ñ("ÖÇ0:(ÌØeÚ2*«­ Î ¢ÕÖjE­¥,Ô´.©"á)ïg!/ò¸¹ßùÃÝÃ¹áRHÑv¹úûðÏeï³ÏÙç|öþíßÞ	H_Aö	Laâgâg8g8ãË'¶íMÖó>×Í2ø¶»A#o²1oð'6RF&¿¥"1´°bFðC{æsÂ«OçFÒÝý×°ÈeÇx¡råGxZ¢+ià&â]ëålz0rþÀ(.f1ÍÜÌ0>¼ÁN R>b"2r,¥¹*q)u,æ¢W Äkì#@7Fók(%Åt}E1PÃo)`$Â¬à@!\Î
>²À âEpEdïPÎ82Ú®AmfRµZÇU¢RÕ»²*])î4]iZ«JõÞ¿BíÔfåh¤iJÓ:¦"_}vx÷@
TÞU¼f{å#ÐkjÔU *WÒx!TªFÍS^Wi°´LzFM)®Qf¡Ú(Iz]ñîùýtDk¢¤Cê/nW¤z
BßQ³R²Vè¸.óz¾@´Wé»
IjÖ÷¼ºinB%:©E

%i$i2ô°¤)ÊÖ¶¶KJ[ãg8g8ÃÄ8ÃÄ&Î0q&Î0q3q3LaâLaâgâg8ÃÄ8ÃÄ&ÎÄ&Î0q&Î0q3L3LaâLaâg8g8ÃÄ8ÃÄ&Î0q&Î0q3q3LaâLaâgâg8g8ÃÄ&ÎÄ&Î0q&Î0q3L3LaâLaâg8g8ÃÄ8ÃÄ&Î0q&Î0q3q3L3Laâgâg8g8ÃÄ&ÎÄ&Î0q&Î0q3L3LaâLaâgâgü3ÓtÍ}£T×¯ûeÝ8@Ä&AâI!É$¹q&Ù7âIB$ â¼òI" F^M	@GrWJ$@)¾§ÅB,ÂÞÓÚy}O"Lû¿}2±HôÞ-Î]ì®xBÄõÄ4§Á}\O'Â, ¸kèN</rÊ«O$Ïkû¯\H!Þ,¥Ð+ïÎBîÄñ(!½ ñLâ¸¥èI?å^ nd0"îa©»6tJx|2xZ  ÐÙ2a4ýèI
s©!tàÒ1ÜÏm#
¾3.H?*	 @¨" ÐÉ£DëtÂT´ç2_yy4O2¾Ñ"X¤éÔ´ºc/ Ì	vÓþ$úÚ}~ÿNpl.uåíèç~5³ôöZä¹Öj¤ú¢Ä`8@O!2HüRÃgì7&>a2Ä H ù<I+jC?ð½&0í®ãn²¼ÃZjHa÷º!pgyÄPÈ­Lôi9Mâ6px¹R_®e>¿a/íèÃpðsêyÿaO1¸jJG-ç4yÅ÷¹ë±Æ5²JRèêUm%	GÇXÀIBõ
<ÆS<äÓ¯r/p?íØÀäQ÷÷2
ÆQÈAr(v«ãæò&ÑÌJî§ÒL&ÌSÍÛL¦Û¼÷|gF)µ,ãçf¯Õ	áÙBÈ­}§ù#Ëx´UÙ&ªD±¢íÔ°:²(<ãÉ§×(Ð*V7uÓhm:£vRµZÇU¢RÕ»²*])î4]iz/¢EµþSÙzNa_YPÔ)_Ù	]¡o«RÒtåi«­\½í~¯St¿·¨îQ£{Ê8
ÐAIÕ¦ÁjÐ2%êiIÕZ®Ýîé*Ó`uí«£V$i¿®S_íq5û4Q¡ë5L
­¾À)Õ`jUz.q}?MX·¡Ô"´Ä½E4EÙÚÑ¦Q/izª«ziv*:Q¶!g=3xçñ#ª.pR×ó/ó·DÌ­<Æ8îór1­ìä2]yÖ»¹¹þqW
â
ÖP
Àj¹ÉÊTÆpO£ô tvOÏd4ûÙçæëäq'Iäs7ûù³kóVñßü(ëÔû¬b"¹­JêîtaTó6øÎÇ<DýùÊü{(zÌx6ðèFñ<÷1Õ·®À.¢ÿEJÄµ{À@òÙâÖ±÷V¯Xú°jÚ»Èàb¯E	>;gç2ÒvSì[GóHâ¨û}ßâRb¢hkæe:pýK
U¼E6]È¹ Ô!D,Ðdîa}Ïo¾oñïJ.Û¸åTDùoE¨ÓOò	=xylôt\ÒýÉà(¨¡£¯}.uÔ¢tß*L{ùú­«xátvC c4úRFÚ»ß¨æCÞb¬oòÏv&s=Wó .`û ½'>|ý;Ç« îw
9xFº^HAòÉñ_\
Y@}[Ï\F±x\åå¯ÑÈ"R©CÜÊÝçª#ÆlbuRiq@3 jHØ¢ÇÑÈ¥ItH®XÈt:ñ# Û1i,á&bZ~M,%çøÜaæÈM@Ëø¦0ãÎT²ØÉ/I ä$i!É½a<¤DÄ"?'ùyoròxlH7ë?ZÕWjêÒ.í÷ÒíÕmÑaIÚæ%-×Uè÷ªÞÚêJ¦+¨ïi½¶ëC=¨Ír÷¥BßJ#U¦°¤råêyß_RG},)¤ñºF5^ù~õÔ]ov+¬ZmÕ	¯v·îPÆx½¤£ºAÙú®fj¦®S;E$K4Q_HN6«îSXÒJjy´!¬¥ùîT®ríRªU®rmS­{»íªtXÛ]rÕ­ ýá,ÉI×L¬AÎ¦.u¾Õ*dq5í)c=ZÞe03é@O0)b-¾±Ýâ(}åòbiñ0!â|½IvçÏò©lç!n#Íw§<Åó¼ÅZÄqb,EcaÆZ"íußb.d8¹^Tì»*nn%Ï!Z¸Æ/¹üü÷qq¼C£¾ ·b:»Tã¸ÖixF²Ï(ÒqÒ;A#ut!àN7ýkdñ$A2øÔ·F6RçTkö3Ã¼È3aÓJ#åL¢ß<Ç[ãIe5ïRËbRzÆ3H8K.x~ÇLÊ¸×wxâ²h¢ÊÍªSH.dSPçÖ© 1usò»éå¥×( lCnE
³N¤.fÇ½¾f.úô)çÅ³dÇAÒ©æWi³1qôdsõÔ±­\v¸OÙsFÖÙÖ0»úW§LqÝha³[÷qèËõÙ³¦±îc7³p£¨r¯+ÖïB[	)¬æZ×f-ÕvéPV²ÏerYË®uyÏ·IÚÛ:V0Ü==ÍÌåw<Æ%ç|§táûpï2G¸¶ÕÀ[xtF_Àý|úq÷9"]q]èË³S@5OÓc>b}éK2ÇYÁëu.±Lá§L¡§xçI£xbFÒÌâ2¹{±ó}:qÙT0Æ¼âq²¹0oñkÆúvuþ­ñ1òXI ²èïËäø9s¸	çõVÞe±tòV°&>¦J>à
ÄßêÚöØTNöÒBH¤ ú¶$ZÆòªDÃÕ_}õ;ý­ìÐDuV:)G}4S^M½~¢\érõVÆkWóÆ([Eê®¢^yP¡:©.R¾P³Wó¾*[ÝT¤,ùî¤ÜñJeªû«¯ë ¯vò5EÇÏòÿ¦jZ³J=µÚ÷¶§k>8Ük+u*Uz«·zëkºF{£^PÔ}àAÞaY¥gÄAUÛhä{©'":F¤M¬ãÐË¹*be©f
&DWFD¬W!6³
2¹âïPN}æÛ¾G­ð¶¼a²èëqGØÄoãÝÿ£þ,Æ5lb·Olà}jÈ¢ü'ìõRé5hEÜß°û[Ñvþ¡âùCµaâg8g8ÃÄýòÿÛl°4ùRtEXtcommentFile source: http://commons.wikimedia.org/wiki/File:UPC-A-036000291452.pngÍ5ýµ%tEXtdate:create2011-04-20T11:49:11+00:006Í»%tEXtdate:modify2011-04-20T11:49:11+00:00GÐuEtEXtsoftwareImageMagick 6.6.2-6 2010-10-23 Q8 http://www.imagemagick.orgäÏtEXtThumb::Document::Pages1§ÿ»/tEXtThumb::Image::height350N?ËtEXtThumb::Image::Width483»{â4tEXtThumb::Mimetypeimage/png?²VNtEXtThumb::MTime1303300151ôVüûtEXtThumb::Size4.83KBH\âLtEXtThumb::URIfile:///mnt/upload6/wikipedia/commons/5/5d/UPC-A-036000291452.png8*èIEND®B`
-----------------------------13326974253911837651178094888--
```

(that's from the sample barcode)

**Comment by trifwnas** [comment]
Hi @webron ,

Thank you for trying to help.

I just need to be able to send the same requests as shown below in postman:

![image](https://cloud.githubusercontent.com/assets/6863495/16421340/edab6316-3d54-11e6-879b-bbc870019b8c.png)

&

![image](https://cloud.githubusercontent.com/assets/6863495/16421423/31e6a9f0-3d55-11e6-9939-e492d5fe0394.png)

Should I change my code or there is something wrong with the editor ?

Thank you in advance.

**Comment by webron** [comment]
It looks like there's a bug in the way that `multipart/form-data` parameters are generated in the editor.

**Comment by trifwnas** [comment]
@webron , please let me know when this is fixed.

Though, I do not think this would affect the get request with the url.
Do you know why this does not work either ?

**Comment by trifwnas** [comment]
Update:
When I use the File -> Paste JSON option in the editor and try to paste my updated code, it gives me the below error:
"Unexpected token ] in JSON at position 1138"
I do not get where my code is wrong.

Thank you in advance for your help.

Updated code here:
`{
    "swagger": "2.0",
    "info": {
        "version": "v1",
        "title": "BarcodeScanner",
        "description": "A BarcodeScanner API"
    },
    "host": "barcodewebapppowerax.azurewebsites.net",
    "schemes": [
        "http"
    ],
    "basePath": "/w",
    "paths": {
        "/decode": {
          "get": {
                "tags": [
                    "url"
                ],
                "operationId": "get",
                "consumes": [
                  "text/html;charset=UTF-8"
                  ],
                "produces": [
                    "application/json",
                  "multipart/form-data",
                  "multipart/related",
                  "application/x-www-form-urlencoded",
                  "text/plain",
                  "text/html",
                  "application/xml",
                  "text/json",
                  "application/x-gzip"
                ],
                "parameters":[
    					{
    						"name":"u",
    						"in":"formData",
    						"description":"url with barcode",
    						"required":true,
    						"type":"string"
    				},
                    ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string",
                            "items": {
                                "$ref": "#/definitions/barcode"
                            }
                        }
                    }
                },
                "deprecated": false
            },
            "post": {
                "tags": [
                    "file"
                ],
                "operationId": "post",
                "consumes": [
                  "multipart/form-data"
                  ],
                "produces": [
                    "application/json",
                    "text/json",
                    "application/xml",
                    "multipart/form-data",
                    "text/html"
                ],
                "parameters":[
                        {
                            "name":"f",
                            "in":"formData",
                            "description":"file with barcode to upload",
                            "required":true,
                            "type":"string"
						}
					          ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string",
                            "items": {
                                "$ref":"#/definitions/barcode"
                            }
                        }
                    }
                },
                "deprecated": false
            }
        },
    },
    "definitions": {
        "barcode": {
            "type": "object",
            "properties": {
                "File": {
                    "type": "string"
                },
                "BarcodeNumber": {
                    "type": "string"
                }
            }
        }
    }
}`

**Comment by saharj** [comment]
@trifwnas I have made some improvements with file parameters. Would you please check to see if this issue is fixed?

**Comment by webron** [comment]
The issue should have been fixed in the older version of the editor and should have no issues with the new eone.
