### ISSUE TITLE
Validation error on array type with string default value

### ISSUE THREAD

**Issue by sjaensch** [swagger-api/swagger-editor#981]
**My Swagger**

```yaml
swagger: '2.0'
info:
  title: title
  version: '0.1'
paths:
  /search/v1:
    get:
      operationId: search
      parameters:
        - default: ""
          description: The categories to filter on
          in: query
          items:
            type: string
          name: categories
          required: false
          type: array
      responses:
        '200':
          description: Search results
      summary: Search for things
      tags:
        - search
```

* Swagger Editor version(from Help > About menu): Version 2.10.1
* My browser: Google Chrome on Mac OS X, Version 51.0.2704.103 (64-bit)

**Issue**

Swagger Editor reports a validation error for the swagger spec: 

```
Details
 Object
code:  "INVALID_TYPE"
 params: Array [2]
0:  "array"
1:  "string"
message:  "Expected type array but found type string"
 path: Array [6]
0:  "paths"
1:  "/search/v1"
2:  "get"
3:  "parameters"
4:  "0"
5:  "default"
description:  "The categories to filter on"
level: 900
type:  "Swagger Error"
lineNumber: 9
```

Changing the default from "" to [] fixes the validation error. But this doesn't seem to be the intended behavior. Check out [this test spec from swagger-codegen](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/globalSecurity.json#L124) for an array field that uses a string default value and currently fails validation in the Swagger Editor.

As to why a string value as default might make sense: if the request parameter is not in `body` the representation as sent by the client will always be a string. `collectionFormat` specifies how exactly this is done, it defaults to `csv`.

**Comment by mohsen1** [comment]
You parameter is describing an array but the default value is an empty string. It should be an array as well.

**Comment by sjaensch** [comment]
Yeah I got that, and initially I thought that's what I'm supposed to use. But have you looked at the test spec from swagger-codegen? I linked a specific field. You can import that spec into swagger-editor and get the same error as my reduced example. Are you saying that spec is wrong?

**Comment by mohsen1** [comment]
Yes that's wrong. Default value should conform to the parameter schema.

**Comment by saharj** [comment]
@sjaensch is your problem solved?

**Comment by sjaensch** [comment]
Not really @saharj since this isn't handled consistently across implementations; it was easy for me to find an example of such a spec in a "official" swagger repository. But I guess if the spec is ambiguous then this is not a swagger-editor bug. Closing the issue.
