### ISSUE TITLE
Cannot build swagger files locally

### ISSUE THREAD

**Issue by srinivascodes** [swagger-api/swagger-editor#983]
when I am running npm run build inside swagger folder which I have made locally. The following error is coming up
 " Failed at the swagger-editor@2.10.1 build script 'webpack --production --hide-modules --stats=errors-only' ". Please tell me how to resolve this issue

**Comment by saharj** [comment]
Please follow all the steps provided [here](https://github.com/swagger-api/swagger-editor/blob/master/docs/development.md) and then let us know if you still get the error.

**Comment by saharj** [comment]
I assume this has fixed the error, so I'm going to close this issue.
