### ISSUE TITLE
json-schema-view-js(0.4.1) or json-schema-view (0.6.0)?

### ISSUE THREAD

**Issue by flaviolsousa** [swagger-api/swagger-editor#984]
Why Swagger Editor project depends on https://github.com/mohsen1/json-schema-view-js instead of https://github.com/mohsen1/json-schema-view ?

Both projects belong to the user: **@mohsen1**

##### json-schema-view
_already implements **allOf** and the date of the last commit was on Apr 5, 2016 (Version 0.6.0)_

##### json-schema-view-js
_His last commit was on Nov 16, 2015 (Version 0.4.1)_

##### Look this demo of json-schema-view:
http://azimi.me/json-schema-view/demo/demo.html

**Comment by saharj** [comment]
The reason is that json-schema-view-js is way faster that the other project. We are hoping that @mohsen1 will include allOf to this project as well, in the near future.

**Comment by flaviolsousa** [comment]
It's OK.
Waiting anxiously for the functionality.
Thanks for your time.
