### ISSUE TITLE
The tags will be list vertical when there are two or more tags without description on a path.

### ISSUE THREAD

**Issue by lqtian** [swagger-api/swagger-editor#986]
**My Swagger**

``` yaml
swagger: '2.0'
info:
  version: '1.0.0'
  title: Swagger Petstore (Simple)

paths:
  /pets:
    get:
      tags:
        - tag1
        - tag2
      responses:
        '200':
          description: pet response
          schema:
            type: integer
```
- Swagger Editor version: 2.10.1
- My browser: Chrome

**Issue**
The tags will be list vertical when there are **two or more tags without description** on a path.

The following code(in the tag-manager service) will pass the index to **registerTag** as the second parameter. So every tag will have a description, even it still not display out.
`_.each(operation.tags, registerTag);`

**Comment by saharj** [comment]
Descriptions can only be on the root “tags” entry. In operation level it can not have description.

**Comment by lqtian** [comment]
I know. 
My point is when I have **more than one tag on a path**, the tags are **not display in the same line**.

**Comment by webron** [comment]
This is no longer relevant in the new editor.
