### ISSUE TITLE
Support raw HTML in descriptions

### ISSUE THREAD

**Issue by ralfhandl** [swagger-api/swagger-editor#987]
https://github.com/OAI/OpenAPI-Specification/pull/720 suggests changing the markdown standard for `description` property values from GFM to CommonMark. The latter doesn't have shorthand notation for tables (yet), but both markdown flavors support raw HTML. 

Unfortunately Swagger Editor does not yet support HTML `<table>` constructs in descriptions, while Swagger UI already does.

Independent of the evolution of the OpenAPI specification it is desirable to have an intersection between the markup/markdown standards supported by my favorite two Swagger tools that includes tables, and raw HTML tables would be a nice fallback for the differing level of support for markdown shorthand for tables, where Swagger Editor is ahead of Swagger UI.

**Comment by saharj** [comment]
We are using `marked` markdown renderer. I'm not sure if that has an option to allow that. I'll take a look.

**Comment by webron** [comment]
This should no longer be an issue in the new editor.

**Comment by ralfhandl** [comment]
Well, it still is an issue: just pulled the latest Swagger UI and what I get is this:
![image](https://user-images.githubusercontent.com/951576/26966903-52c9ebf2-4cfc-11e7-8f7c-172ba1525c6e.png)

When will the HTML be interpreted and rendered by the new editor?

**Comment by webron** [comment]
This is an issue in swagger-ui now, not swagger-editor. I believe we have an open ticket for that, can't find it right now.
