### ISSUE TITLE
The size of styles.css is about 11 MB after uglifying.

### ISSUE THREAD

**Issue by srinivascodes** [swagger-api/swagger-editor#991]
After running swagger editor on my server, I found that styles.css is almost 11MB and taking long time to get load. After uglifying still the size is 11 MB. Is there any way to optimize it. Also is there any way to load styles.css quickly in the browser.

**Comment by saharj** [comment]
Maybe you can consider asking this question on http://stackoverflow.com/

**Comment by saharj** [comment]
You're right. It's because we‘re embedding fonts in the CSS file. We will consider improving it later.

**Comment by brylie** [comment]
This wait time has a negative effect on end users, in terms of delay to render the page. In our case, the delay is over ten seconds:

![screenshot](https://cloud.githubusercontent.com/assets/17307/18472538/bf5ecefa-79c0-11e6-8281-3d4ba5e82940.png)

**Comment by brylie** [comment]
Please consider removing these fonts from the CSS file.

**Comment by saharj** [comment]
@brylie we know it's important but there is a bug in webpack file loader still open. That issue needs to be fixed before we take any action toward fixing this issue.

**Comment by leotu** [comment]
+1

**Comment by webron** [comment]
Apologies for the delayed feedback.

Unfortunately, our code base might have deviated from the time this PR was submitted, and we cannot easily merge it (certainly not against master), and so, we're going to close this PR.

If you find the change important and would like to resubmit it, please let us know. Be aware that we are focused on the 3.X version at the moment (now master), and new changes should be applied to it.

We appreciate the time you've taken into submitting this PR. We're now making extra effort to review PRs within a few days at most, to avoid situations like this.

**Comment by webron** [comment]
Huh, I meant to post it on the relevant PR. However, this should no longer be an issue in 3.X.
