### ISSUE TITLE
electron and chromeapp

### ISSUE THREAD

**Issue by fthamura** [swagger-api/swagger-editor#997]
i propose the swagger editor become electron app

so we can run standalone

and also on chrome app, can run on chromebook

**Comment by sauldhernandez** [comment]
+1

**Comment by firefoxNX** [comment]
👍🏼

**Comment by danielm64** [comment]
+1 !!

**Comment by lazyspark** [comment]
Is this work started? I am interested to contribute to this and build it out.

**Comment by damnhandy** [comment]
This would be a better approach than something like a server-side backend as described in #174.

**Comment by webron** [comment]
We don't have the capacity to build and maintain this feature. If anyone wants to give a try, feel free to submit a PR and we'll review.

**Comment by mbylstra** [comment]
If anyone builds this, I would love a feature to be able to open a file from the command line when starting the app. Eg:

`swagger-editor acme-api.yml`

(opens the file straight into the editor - no need to find the file from the GUI)

**Comment by liguori** [comment]
The request of a standalone app was made almost 2yrs ago. Are there any news from the "official team". Are you guys still waiting for a PR?

**Comment by liguori** [comment]
Hello everyone, i found that at the moment the best fit for this kind of request is Visual Studio Code with 'Swagger Viewer' extension installed (https://marketplace.visualstudio.com/items?itemName=Arjun.swagger-viewer).

Of course it would be nice to have completely separate editor that works standalone and offline even on multiple files (*.yaml and *.json) on the hard drive.

Doeas the swagger-editor's 'official team' considered this feature?

**Comment by ponelat** [comment]
Closing this out as it's outside the scope of the swagger-editor project itself. Would recommend the VS Code, IntelliJ or other IDE integrations with Swagger as great way of editing/working with OpenAPI definitions locally. There are quite a few, some of which are supported by our sponsor -- SmartBear, and quite a few community ones too!
