### ISSUE TITLE
Not a valid parameter definition

### ISSUE THREAD

**Issue by grcreddy** [swagger-api/swagger-editor#998]
Hi,
i am creating XML schema for Swagger 2.0, getting below error. Can someone help on this?
![1](https://cloud.githubusercontent.com/assets/20418763/16765625/c13d5c5e-4852-11e6-9dce-6e0768d4cb87.jpeg)

Attached are the spec.

**Comment by webron** [comment]
You didn't attach the spec...

**Comment by grcreddy** [comment]
[1.yaml.txt](https://github.com/swagger-api/swagger-editor/files/365725/1.yaml.txt)


Hi Ron,
Attached the spec. Please help me on this.

**Comment by webron** [comment]
@grcreddy the attached file is a malformed yaml, and it doesn't look anything like you shared in the screenshot (you have a reference to Pet which isn't even defined there). Can't help with an actual proper file.
