### ISSUE TITLE
Where can I put code to reorder the operations?

### ISSUE THREAD

**Issue by ChriWiChris** [swagger-api/swagger-editor#999]
Hi. I am currently using swagger-editor 2.10.1 and want to reorder the operations. At the moment they are automatically ordered alphabetically but I want to put some code to change the ordering process. In swagger UI this was easy with an option in the swaggerUi constructor:
```
window.swaggerUi = new SwaggerUi({
  //...
  operationsSorter: function (a, b){ ... }
});
```
How can I do this in swagger editor? Thanks in advance!

**Comment by webron** [comment]
@ChriWiChris - following your previous feedback, that's one of the differences between the goals of the tools - swagger-editor is not meant for this kind of functionality.

**Comment by ChriWiChris** [comment]
Thanks for your answer, @webron . Ok I understand the different goals of each of the tools. 
When reordering the operations in the yaml file swagger editor takes this ordering, so I just have to get them in the right order before loading in swagger editor. Maybe I'll write some script to do that or is there a way to tell swagger in my JAX-RS application to use a special ordering?

**Comment by webron** [comment]
There isn't in 2.0 - we explicitly removed the ordering in that version (can be argued, but hey... ;)).

Just remember that currently the operations are in a map, and by definition order is not guaranteed in maps (in JSON). That said, most tools just keep the order, so it's normally not a real concern.

**Comment by ChriWiChris** [comment]
Thank you for the detailed answer.

**Comment by saharj** [comment]
I assume your question was answered @ChriWiChris. I'm going to close this issue for now. Feel free to reopen it if you think otherwise.
